### ISSUE TITLE
Allow keydown events to propagate if Dropdown is closed

### ISSUE THREAD

**Issue by dunal** [twbs/bootstrap#15065]
When element with `data-toggle="dropdown"` is focused, `keydown` events could not be cought on parent elements. For example, it's impossible to close containing modal by `esc`.
It would be better to prevent event propagation only if dropdown is open.

**Comment by cvrebert** [comment]
Tweaked example: http://jsfiddle.net/ku4vqp2y/7/show/

Well, the Up/Down keys in that case open the menu if it's closed, so that seems like reasonable+intentional behavior. I agree that preventing the propagation of Esc when the menu is closed is kinda weird though.
CC: @hnrch02 @XhmikosR @juthilo for their opinions

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
