### ISSUE TITLE
Modal's Esc key functionality not working correctly

### ISSUE THREAD

**Issue by JackEllis** [twbs/bootstrap#15253]
I wanted to make this into an issue rather than attempt to finish my PR (#15252), because I'm unsure on the correct way to write javascript unit tests for the stuff I'm correcting.

2 problems that happen *when pressing the escape key* when the modal is open
* The backdrop isn't removed (see https://github.com/twbs/bootstrap/blob/9a7e365c2c4360335d25246dac11afb1f577210a/js/modal.js#L184)
* The correct method isn't called (see https://github.com/twbs/bootstrap/blob/9a7e365c2c4360335d25246dac11afb1f577210a/js/modal.js#L144 and you'll see it calls hide() instead of hideModal()

I think it would be easier to just call removeBackdrop() from near line 1048 personally.

**Comment by hnrch02** [comment]
I don't understand what the problem is here?

- Both the `hide` and `hidden` events are properly fired.
- The backdrop disappears (not only visually but also gets removed from the DOM).
- Re [wrong method being called](https://github.com/twbs/bootstrap/blob/9a7e365c2c4360335d25246dac11afb1f577210a/js/modal.js#L144): Why do you think it would be the wrong method in this case? If it were to directly call `hideModal` the `hide` event wouldn't fire.

**Comment by Johann-S** [comment]
I think you're right both events are properly fired currently

**Comment by JackEllis** [comment]
@hnrch02 @Johann-S Hey guys - Had to refresh myself on this. I think the issue was related to my set-up. I've just had a look and I can see that hideModal is fired from hide anyway: https://github.com/JackEllis/bootstrap/blob/v3.3.1/js/modal.js#L126

Sorry :)
