### ISSUE TITLE
Bootstrap Multi Tab Switching Issue

### ISSUE THREAD

**Issue by teken** [twbs/bootstrap#15505]
When you have more then one set of tabs on one page and your using the boostrap.js, not bootstrap.min.js (file already fixed), if some of your have tabs that have the same identifiers it fails to change tab when the link is clicked.

Here's how to fix it:

You need to change the line that reads
    'var $target = $(selector)'
in the tab class definition section to
    'var $target = $ul.siblings('.tab-content').children(selector)'

**Comment by cvrebert** [comment]
Having multiple elements with the same `id` is invalid HTML, unless you mean something else by "identifiers".

**Comment by teken** [comment]
it maybe invalid but it still doesn't stop it happening sometimes, did you add the change to the code?

**Comment by cvrebert** [comment]
We don't attempt to accommodate blatantly invalid HTML. Down that road lies madness.

**Comment by teken** [comment]
you already have the fix in the minifed version, you just need to put it in the normal version too

**Comment by cvrebert** [comment]
Suffice it to say that that's not how minification works and that there's nothing broken here in Bootstrap to begin with. What's broken is whatever is generating that invalid HTML.

**Comment by teken** [comment]
The version of the minifed file i was looking at was an older one but the point still stands, in its current way it just search for the first id called that, where as in my method is looks local to its self to find that id. I know that your not suppose to have html elements with the same id but in web applications, and other large projects, sometimes it can happen. This wont promote using the 'invalid html' to people, it will just make bootstrap more robust.

**Comment by ertong** [comment]
Look, guys, I understand your desire not to allow invalid HTML.

But also you should take into account use case, when it is required to place a lot of similar tab widgets.
Please, understand, that generating unique id's is very bad solution (and it become bigger nightmare working with ajax, because server do not know the last used id on the page).

Maybe using id's for switching tabs (and for similar tasks) was totally wrong decision from your side at the very beginning? Didn't you think about that?

Or, maybe, you have better solution how to place a lot of tab widgets on one page without unique ids?

**Comment by salarmehr** [comment]
@ertong +1
