### ISSUE TITLE
Navbar example uses markup against doc recomendations 

### ISSUE THREAD

**Issue by flevour** [twbs/bootstrap#15512]
The code for this example uses nested containers (the root one plus one inside `navbar`): http://getbootstrap.com/examples/navbar/

This example should be updated to reflect the fact that nested containers have been deprecated (https://github.com/twbs/bootstrap/issues/11436), or should have a comment explaining why the exception is fine in this case.

**Comment by mdo** [comment]
There's no problem here—navbars require the use of a container within them, and there's a site-wide container to center the page contents. One is `.container`, the other is `.container-fluid`. The issue of #11436 is that for awhile our `.container`s used fixed `width`s, not `max-width`s. Thus, we use `.container-fluid` on a required nested container.

**Comment by cvrebert** [comment]
@mdo Wait, so only `.container` isn't nestable within `.container` or `.container-fluid`?

**Comment by CorpusCallosum** [comment]
THE ISSUE is that the documentation does not reflect this:
"Bootstrap requires a containing element to wrap site contents and house our grid system. You may choose one of two containers to use in your projects. Note that, due to padding and more, neither container is nestable."

http://getbootstrap.com/css/

**Comment by iatek** [comment]
This recently came up as an issue on StackOverflow:
http://stackoverflow.com/questions/36618433/bootstrap-navbar-should-i-nest-containers/36621583
