### ISSUE TITLE
grid variation without column padding

### ISSUE THREAD

**Issue by rz** [twbs/bootstrap#15530]
This code:

```
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-1" style="background: #eee">X</div>
                    <div class="col-md-10" style="background: #ddd">Blah blah.</div>
                    <div class="col-md-1" style="background: #ccc">X</div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-2" style="background: #eee">Y</div>
                    <div class="col-md-8" style="background: #ddd">Blah blah.</div>
                    <div class="col-md-2" style="background: #ccc">Y</div>
                </div>
            </div>
            <div class="col-md-6">Some Text</div>
        </div>
    </div>
```
renders like this: http://cl.ly/image/2c1Y1O1U080I The expected behavior is that the 2nd X should be in the same row, as it happens in the middle column with the Ys. The problem occurs with .col-{xs, sm, md, lg}-1.

**Comment by cvrebert** [comment]
Your columns are simply too narrow when taking the grid system's constant 15px-on-each-side-of-a-column padding into account.
On a medium viewport, the `container` is 970px, and the `row`s within the `col-md-3`s are each 242.5px wide.
242.5px / 12 = ~20.2px, so your `col-md-1` needs to fit within ~20.2px
However, like all vanilla Bootstrap grid columns, the `col-md-1` has 15px of padding on each side.
2*15px = 30px < 20.2px, so even with no content at all, the column cannot fit within the row.

You'd either need to override the padding at this particular level or use a grid variation that doesn't have any column padding anywhere (which I agree would be a nice variation to offer, since this has come up a few times before).

**Comment by mdo** [comment]
Not going to be adding this as a feature anytime soon, thanks though!
