### ISSUE TITLE
Tooltip not activating/closing for disabled <select> inside <div>

### ISSUE THREAD

**Issue by bbodenmiller** [twbs/bootstrap#15540]
I've encountered a situation where I am trying to show a tooltip on a disabled item. As [suggested by the docs](http://getbootstrap.com/javascript/#tooltips) I have placed the tooltip on a container `div` of the disabled item however if I start/end my hoving over the item from certain directions the tooltip does not show/hide.

In [this JSBin](http://jsbin.com/jivemilate/1/edit?html,output) you can see if I move my mouse from the top of the screen to the bottom of the screen all of the tooltips open but none of them close. If I then move my mouse from the bottom of the screen to the top of the screen they all close. If I start my hoving from the sides of the disabled `select` box the tooltip does not show up. 

![image](https://cloud.githubusercontent.com/assets/1192780/5694458/38a982a6-9911-11e4-9bc7-1ad48751b5c3.png)

Any ideas what is causing this and/or good workarounds besides including empty space on all sides of the disabled item?

Verified in Chrome 39.0.2171.95 m and Firefox ESR 31.2.0 on Windows 7. Does not appear to affect IE11 on Windows 7.

**Comment by twbs-lmvtfy** [comment]
Hi @bbodenmiller!

You appear to have posted a live example (http://jsbin.com/huzetemane/3/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 80, column 11: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 19, column 42: Unclosed element ```` div ````.
* line 18, column 37: Unclosed element ```` div ````.
* line 29, column 58: The ```` for ```` attribute of the ```` label ```` element must refer to a form control.
* line 38, column 58: The ```` for ```` attribute of the ```` label ```` element must refer to a form control.
* line 51, column 58: The ```` for ```` attribute of the ```` label ```` element must refer to a form control.
* line 63, column 58: The ```` for ```` attribute of the ```` label ```` element must refer to a form control.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bbodenmiller** [comment]
[Updated example with errors fixed](http://jsbin.com/jivemilate/1/edit?html,output). Didn't fix anything.

**Comment by cvrebert** [comment]
Might be better to wrap each `select` in a new `div` and put the tooltip on that instead of putting the tooltips on the form-groups.

**Comment by bbodenmiller** [comment]
@cvrebert thanks for the suggestion, unfortunately using that suggestion it [doesn't appear to work at all](http://jsbin.com/cahutesare/1/edit).

**Comment by peterblazejewicz** [comment]
@bbodenmiller 
Try this. Add `fieldset` to contain and scope your disabled content and then:
```
fieldset:disabled .form-group {
  margin-bottom: 0;
  padding-bottom: 15px;
}
```
(swaps bottom margin with padding)
on each form group within disabled `fieldset` add `tabindex="0"`:
```
<div class="form-group" data-toggle="tooltip" title="Message about my disabled item" tabindex="0">
```
This will make your form-groups available for keyboard navigation/focus, etc. It helped in Chrome/FireFox. Not 100% - but should be visible improvement. 
Really no purpose for tooltips on elements that are disabled and otherwise not accessible without mouse.

**Comment by cvrebert** [comment]
`select[disabled] { pointer-events: none; }` works in this case, but requires IE11+ and has too many side effects to be a feasible fix.

**Comment by fat** [comment]
ah yeah working with disabled in this way can be a pain.

if you want to go chris's route (but need more ie support) you could add an invisible screen element on top of the disable element (that way your events will still propagate)

```css
.form-group.is-disabled {
  position: relative;
}
.form-group.is-disabled:before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 2;
}
```

this way the events will still propagate.

Another thing you could try playing with is adding a "readonly" attribute instead of disabled (to get similar styling) then use js to blur the input whenever the user tried to focus it. (pretty hacky though).

Anyways, dont really have any other ideas - hopefully those help!
