### ISSUE TITLE
Missing color variables

### ISSUE THREAD

**Issue by baskerville** [twbs/bootstrap#15635]
The following command:
```
grep -liE '#([a-f0-9]{3}){1,2}|rgba\(' **/*.less
```
when issued inside the `less` directory, yields:
```
button-groups.less
buttons.less
carousel.less
code.less
dropdowns.less
forms.less
mixins/forms.less
mixins/gradients.less
mixins/list-group.less
mixins/nav-divider.less
modals.less
navbar.less
normalize.less
panels.less
popovers.less
print.less
progress-bars.less
scaffolding.less
theme.less
type.less
variables.less
wells.less
```

Shouldn't the output be `variables.less`?

**Comment by kkirsche** [comment]
Why would the output to be only `variables.less`?

You've asked grep for `-l` files with matches, `-i` with case ignored, `-E` using a regular expression which is either a hex value or a rgba value.

In many of those files (e.g. button-groups.less), they use box-shadow with the which uses rgba values which is why, as I understand it, you are getting hits on those files.

**Comment by juthilo** [comment]
We use variables where it makes sense, but there are other color values that don't usually need to be changed. The variables file is a little bloated already, but if you have a specific suggestion, feel free to open a new issue.
