### ISSUE TITLE
Browserify pollution global namespace 

### ISSUE THREAD

**Issue by jesusprubio** [twbs/bootstrap#15638]
This works for me, but I would like not to pollution the window object (adding there jQuery). Is there any "official" way of passing a JQuery object instead of using the global one? BTW the README doesn't reflect anything about browserify or npm, so it's a bit confusing to have to look for responses in the issues and in the code. I'm going to add some notes there, but I need to clear this issue before.

var jquery = require('jquery');
window.jQuery = $;
require('bootstrap');

**Comment by cvrebert** [comment]
The Getting Started docs explain npm usage: http://getbootstrap.com/getting-started/#download-npm
We don't currently explain the usage of any module-related build tools; there are so many of them. And we don't currently use any JS module system. We're hoping to address that in v4.

**Comment by beaugunderson** [comment]
@jesusprubio to do this I followed [Max's recommendation](https://twitter.com/maxogden/status/558423787201245184) and used `browserify-shim` with `{"jquery": "global:$"}` so that I could still `var $ = require('jquery');` in my scripts. (I'm still going to manage bootstrap/jquery with bower for the time being because I can't figure out a good way to include them as `<script>` tags if they're npm dependencies yet).
