### ISSUE TITLE
affix bottom fails if position wasn't relative

### ISSUE THREAD

**Issue by Nemo64** [twbs/bootstrap#15668]
I build a navigation with an affix and noticed that if the navigation didn't had `position: relative` before the affix is applied and one reaches `offset-bottom` the element gets stuck on top of the page.

http://jsbin.com/gevenexusi/1/ The affix in this example works until it reaches `offset-bottom`. After scrolling back up it is stuck at the top.

If position relative is applied via none inline css, it works just fine: http://jsbin.com/gevenexusi/2/

**Comment by twbs-lmvtfy** [comment]
Hi @Nemo64!

You appear to have posted a live example (http://jsbin.com/gevenexusi/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 29, column 9: [W009](https://github.com/twbs/bootlint/wiki/W009): Using empty spacer columns isn't necessary with Bootstrap's grid. So instead of having an empty grid column with `class="col-xs-8"` , just add `class="col-xs-offset-8"` to the next grid column.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @Nemo64!

You appear to have posted a live example (http://jsbin.com/gevenexusi/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 24, column 9: [W009](https://github.com/twbs/bootlint/wiki/W009): Using empty spacer columns isn't necessary with Bootstrap's grid. So instead of having an empty grid column with `class="col-xs-8"` , just add `class="col-xs-offset-8"` to the next grid column.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kweij** [comment]
Hi,

I'm running into the same problem, so I made a JSFiddle right here:
http://jsfiddle.net/yr2p4yud/
The scenario doesn't seem so extraordinary.

The problem is a result of the combination of jQuery and Affix. In Affix, the $element gets an offset at the bottom:


    if (affix == 'bottom') {
      this.$element.offset({
        top: scrollHeight - height - offsetBottom
      })
    }

.. and unsets this offset using:

    if (this.unpin != null) this.$element.css('top', '')

However, jQuery does not only add a css top, but also sets position to relative if the element wasn't relative yet. As quoted from the documentation:
http://api.jquery.com/offset/

_"The .offset() setter method allows us to reposition an element. The element's position is specified relative to the document. If the element's position style property is currently static, it will be set to relative to allow for this repositioning."_

In my case I _could_ just add the following line to Affix as a simple patch:

      if (this.unpin != null) this.$element.css('position', '')

A better fix for me is adding a position absolute to the affix-bottom class:

    .affix-bottom {
            position: absolute;
    }

This causes the jQuery setOffset() to use a different approach and only set the *top* value, which gets calculated accordingly.

Besides these fixes, I suppose that Affix should be able to work without them.

**Comment by fat** [comment]
Yep, you should add the `affix-bottom` class, this is mentioned in the docs here:

> If a bottom offset is defined, scrolling past it should replace .affix with .affix-bottom. Since offsets are optional, setting one requires you to set the appropriate CSS. In this case, add position: absolute; when necessary. The plugin uses the data attribute or JavaScript option to determine where to position the element from there.
