### ISSUE TITLE
Black lines in modal on IE 11, Bootstrap version 3.3.2

### ISSUE THREAD

**Issue by Tiscs** [twbs/bootstrap#15677]
Hi, I used bootstrap version 3.3.2 on IE 11, there was some black lines in modal, see the picture below.
![twbsissues](https://cloud.githubusercontent.com/assets/2810237/5916044/7fab2cd4-a647-11e4-8fa3-66a1b34b07c5.png)
Thanks.

**Comment by ggbhat** [comment]
@Tiscs I have tested it on my machine everything is working fine. Here is screen shot.
![ie-11-bs](https://cloud.githubusercontent.com/assets/4777119/5917966/f566f7b8-a648-11e4-8469-4da25d61df44.PNG)

**Comment by patrickhlauke** [comment]
Confirming that I don't see any black lines in my IE11 either...

**Comment by Tiscs** [comment]
Black lines shown when mouse hovered the button, link, or close button, I test on my surface pro 3 and an other virtual machine running windows server 2012 R2.

**Comment by ggbhat** [comment]
Again confirming that I don't see any black lines in my IE11 either on hover over any button or link

**Comment by cvrebert** [comment]
@patrickhlauke Does hovering make a difference for you?

**Comment by patrickhlauke** [comment]
No it doesn't. I cannot seem to replicate this issue, I'm afraid

**Comment by cvrebert** [comment]
@XhmikosR Are you able to reproduce this?

**Comment by XhmikosR** [comment]
Nope, works fine here.

**Comment by cvrebert** [comment]
Closing since we're unable to reproduce the problem.

**Comment by jamiebeech** [comment]
I had this issue when testing a web app using V3.3.2 on MS Surface  - IE11. It turns out that IE was set to 150% zoom which was causing these random black lines to appear. Set the browser zoom to 100% and the lines should disappear. I've seen this zoom cause so many random errors on the web that just don't make any sense.
![screen shot 2015-06-28 at 11 05 54](https://cloud.githubusercontent.com/assets/5319622/8395909/cc0194f0-1d85-11e5-9de7-6ded0a253922.png)

**Comment by cvrebert** [comment]
@jamiebeech And as noted in our docs, Bootstrap (and a lot of the Web generally) doesn't support that type of non-pinch zooming.
