### ISSUE TITLE
shit all fucked up. 

### ISSUE THREAD

**Issue by cheezedigital** [twbs/bootstrap#15727]
trying to get placement of pagination on the bottom of the page like other pages, however, clearly jacked up. 
![screen shot 2015-02-02 at 12 51 03 pm](https://cloud.githubusercontent.com/assets/4884455/6005775/f0aae1e4-aada-11e4-8c65-0a3c67284565.png)

yo help would be greatly appreciated.

**Comment by kkirsche** [comment]
I would recommend asking about this in [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap) as Bootstrap asks users __do not__ use the issue tracker for personal support requests.

With that said, I think you will get much farther with a clear and respectful title rather than a potentially offensive one.

**Comment by cheezedigital** [comment]
thanks for reaching out, and my bad for imposing.
