### ISSUE TITLE
Carousel.less - Icon-specific selector rule on prev and next controls

### ISSUE THREAD

**Issue by K20** [twbs/bootstrap#15736]
In the carousel.less file, the selector to vertically align the next & prev icons, are based on glyphicon or on another glyph available in bootstrap (icon-next & icon-prev in carousel.less).

There should be a semantic selector, if one would like to change the default font icon for a website.

As an example, if I use Icomoon on a bootstrap based project, the css wouldn't apply anymore.
My prev & next would look like this : 

`<span class="icomoon-chevron-left"></span>`

instead of 

`<span class="glyphicon-chevron-left"></span>`

**Comment by kkirsche** [comment]
@K20 I don't see anything for the icons would like X instead of Y.

Also, I believe this would fall under the fact that Bootstrap does not support 3rd party libraries, which would include icon libraries. Support for using different icon sets, etc. would be something that I'd recommend asking at StackOverflow though if you wanted to do it :+1: 

You'd need one of the admins/collabs though to confirm that.

**Comment by mdo** [comment]
We won't be adding additional classes to the component to account for external projects, but can you can easily override the `.icon-next` and `.icon-prev` classes I imagine.
