### ISSUE TITLE
Stop carousel animation queue to build up

### ISSUE THREAD

**Issue by betasve** [twbs/bootstrap#15753]
Hello, 

I've been looking all over the internet for a hint but I don't seem to find one so I decided to ask here. 

I have this carousel that's modified as follows: 
1. Carousel has a left part, that's the images holder;
2. At the right part is the carousel-indicators which is a list of text links

My problem: When I go fast trough the list (the carousel-indicators) up and down, the animation queue is building up so when I stop moving up and down, there's a period of time that the carousel keeps changing slides quickly in the order I moved I mouse over. 

I've looked up that there is this stop() method that's hooked before the animate method, but I am not sure how it will be the best way of overriding bootstrap's carousel js. Looked in the documentation, there's nothing about this stuff. 

Thanks in advance for your time guys and I hope this question would be helpful for a lot of other people as well. 

Best Regards

**Comment by cvrebert** [comment]
> I've looked up that there is this stop() method that's hooked before the animate method

Bootstrap only uses CSS3 animations, not jQuery animations, so that method isn't applicable.

> the animation queue is building up so when I stop moving up and down, there's a period of time that the carousel keeps changing slides quickly in the order I moved I mouse over.

There isn't an explicit queue, but what you're running into is this:
https://github.com/twbs/bootstrap/blob/b9b824c5922eca4e7c02ecfe8f2836cbfb38ec7e/js/carousel.js#L88
When you click a carousel-indicator, `clickHandler` gets called, and it ends up calling `to(slideIndex)` to switch to the relevant slide.
If `to` is called while a slide animation is already in progress, a callback is setup that waits for the sliding to complete (i.e. for the `slid.bs.carousel` event to fire) and then retries the `.to(slideIndex)` call. If `clickHandler` gets invoked many times quickly, this will result in many pending `to` callbacks. You can clear these callbacks via `$('#your-carousel-here').off('slid.bs.carousel')`, although if you have your own event listeners for that event, this will have the unfortunate side-effect of unsubscribing them.

**Comment by betasve** [comment]
Thank you @cvrebert for your input. 
I will try the solution suggested by you. I'm afraid it won't work though, because I have another event handler the. The thing is... I use the carousel indicators on-click event. On hover you see the image for that carousel indicator (topic title) and on click, you're forwarded to the page for that topic.

**Comment by fat** [comment]
hm @cvrebert was right on.

unfortunately without a bit of hacking i dont think we have the means to do what you want right now.
