### ISSUE TITLE
media-body width 10000px

### ISSUE THREAD

**Issue by mschipperheyn** [twbs/bootstrap#15795]
Well, this screwed up my design

    .media-body {
       width: 10000px;
    }

Why create a hard coded width of 10000px?

**Comment by mschipperheyn** [comment]
I see that it fixes the issue created by moving to from zoom:1 overflow:hidden to display:table-cell not taking full-width, but it seems like quite a hack

**Comment by kkirsche** [comment]
If it's inside of a `.container` it should just hit the max size of the container. Could you post a JSBin of the problem?

**Comment by kkirsche** [comment]
If it ultimately is a personal support requests not an actual bug with Bootstrap, Stack Overflow ([`twitter-bootstrap-3 tag`](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3)) or [IRC](https://github.com/twbs/bootstrap/blob/master/README.md#community) are better places to get help.
But I'd be interested in an example of the issue so that we can see what you are doing and how the problem is actually occurring.

**Comment by cvrebert** [comment]
See #14990.
