### ISSUE TITLE
Input group with CSS triangle causes Mobile Safari to crash

### ISSUE THREAD

**Issue by jackocnr** [twbs/bootstrap#15842]
I have a strange issue - I'm not sure if I should post this here, or in the Mobile Safari bug tracker.

I have a Bootstrap input group with an input on the left and a button on the right, except I want to overlay an arrow on the left of the input, so I wrap the input in a container div, and give it a sibling arrow div (which is used to display a CSS triangle). For some reason, this now causes Mobile Safari to crash if you tap on the triangle! You can reproduce the issue in [this codepen](http://codepen.io/jackocnr/pen/LEQNXx) - or here's a [mobile friendly link](http://codepen.io/jackocnr/full/LEQNXx). Just type something into the input and then tap the triangle - Safari crashes and you can't type anything else!

Tested with an iPhone 5S and an iPhone 6.
Bootstrap 3.3.2.

**Comment by cvrebert** [comment]
I can confirm your issue with iOS 8.1.3 on iPhone 5S. Although I wouldn't call it a "crash" per se, as it doesn't literally kill the browser or make the entire UI completely unresponsive. The `<input>` does seem to ignore further keystrokes or attempts to move the cursor though.

> I'm not sure if I should post this here, or in the Mobile Safari bug tracker.

Since your extra custom CSS is required in order to provoke it and it is definitely a browser-level bug, the latter please. Safari's bug trackers are:
* https://bugs.webkit.org/enter_bug.cgi
* http://bugreport.apple.com (and then you may wish to publicly repost your submission to http://openradar.appspot.com)

Good luck!

**Comment by jackocnr** [comment]
Thanks for your help. I've posted the issue here: https://bugs.webkit.org/show_bug.cgi?id=141822 and on bugreport.apple.com.
