### ISSUE TITLE
Child elements bigger than column size

### ISSUE THREAD

**Issue by xHype** [twbs/bootstrap#15858]
I have a little problem with the bootstrap columns: even though the column width is 316px, an image inside the column gets 317px width, so 1px of the image gets left out uncovered and it looks ugly. Here's some screens: 
Here you can see the column width is 316px: http://i.imgur.com/AFBXmhE.png 
Here you can see the image width is 317px AND I pointed out the 1px of the image that gets left out uncovered by the div's: http://i.imgur.com/c2s0VG8.png

This is the HTML code: https://gist.github.com/xHype/f73b40200fbb6d624746

And this is the CSS:  https://gist.github.com/xHype/3a059a8fccac869a53d9

I have tried setting the image width to 100%, the parent overflow:hidden but none works. What can I do?

**Comment by cvrebert** [comment]
Please make your example into a [JS Bin](http://jsbin.com/). Thanks.

**Comment by kkirsche** [comment]
The gist has PHP in it, so I wasn't able to move it over to JSBin for @xHype

**Comment by xHype** [comment]
I moved it on JSBin and it appears to work correctly.. On my localhost doesn't, though. http://jsbin.com/nomugiwogu

(The problem appears only on md+ screens)

**Comment by twbs-lmvtfy** [comment]
Hi @xHype!

You appear to have posted a live example (http://jsbin.com/nomugiwogu/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 16, column 21: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-xs-12 col-sm-10 col-md-10 pull-left col-sm-offset-1"` is redundant and can be simplified to `class="pull-left col-sm-offset-1 col-xs-12 col-sm-10"`
* line 30, column 21: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-xs-12 col-sm-10 col-md-10 pull-left col-sm-offset-1"` is redundant and can be simplified to `class="pull-left col-sm-offset-1 col-xs-12 col-sm-10"`
* line 44, column 21: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-xs-12 col-sm-10 col-md-10 pull-left col-sm-offset-1"` is redundant and can be simplified to `class="pull-left col-sm-offset-1 col-xs-12 col-sm-10"`
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by xHype** [comment]
http://jsbin.com/nomugiwogu

**Comment by cvrebert** [comment]
> I moved it on JSBin and it appears to work correctly.. On my localhost doesn't, though.

That would indicate an environment problem, which is outside the scope of this issue tracker. Environment-related questions are best asked on StackOverflow or similar. Thanks.
