### ISSUE TITLE
affix losing affix-bottom class

### ISSUE THREAD

**Issue by gareth-gillman** [twbs/bootstrap#15873]
Bit of a wierd one, on http://ww.howheasked.com/ if you scroll down, one of the ads in the right hand side affixes as it should, reach the bottom and it should sit above the footer, but if you scroll up a little and then back to the footer the affix-bottom class isn't being added so the advert overflows over the footer!

Happens on firefox and chrome latest versions!

Anyone know why it's happening and a fix if possible?

**Comment by kkirsche** [comment]
missing a `w` in the link. Should be http://www.howheasked.com/

For me I'm getting it to display sometimes with `affix-bottom` in Chrome and other times it is not. I'm unsure if this may have something to do with how the image is being added. Does this occur if you use a fixed image not something loaded via a script?

This could be an implementation issue rather than an issue with Bootstrap itself which means this should be discussed on Stack Overflow ([`twitter-bootstrap-3 tag`](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3)) or [IRC](https://github.com/twbs/bootstrap/blob/master/README.md#community) to get help with this. Honestly in the current example I'm not sure.

I'd ask if you could simplify this into a JSBin so we can determine if it's an implementation bug or a framework issue.

**Comment by gareth-gillman** [comment]
It happens with a static image as well, could it be js on the site conflicting with it?

The code being used is <div class="row hidden-xs sticky"><div class="col-md-12"><div class="well hha" data-spy="affix" data-offset-top="2500" data-offset-bottom="350">

**Comment by gareth-gillman** [comment]
sorry forgot link - http://pastebin.com/FpNF4Tnt

**Comment by cvrebert** [comment]
@gareth-gillman Sorry, but a pastebin isn't good enough. We'll need a [JS Bin](http://jsbin.com/). Thanks.

**Comment by cvrebert** [comment]
@gareth-gillman Any update on creating a JS Bin demo?

**Comment by cvrebert** [comment]
Closing due to lack of response to our requests.
