### ISSUE TITLE
Double clicking a collapse element breaks active appearance

### ISSUE THREAD

**Issue by au-phiware** [twbs/bootstrap#15932]
I have found that double clicking on a `[data-toggle="collapse"]` will toggle the `active` class twice but trigger the collapse only once. I am using this fix:

    $('[data-toggle="collapse"]').click(function(e) {
        if($($(this).data('target')).hasClass('collapsing'))
            return false;
    });

**Comment by hnrch02** [comment]
- Which version of Bootstrap is affected?
- Where did you experience this problem? Is it replicable on http://getbootstrap.com?

**Comment by au-phiware** [comment]
I've just done a build from master and it is happening there, I'll attempt to make a jsfiddle.

**Comment by au-phiware** [comment]
This exhibits the undesirable behaviour: http://www.bootply.com/oI8gYHJ0nd

Double clicking `$('[data-toggle="collapse"]')` results in an open `.panel-collapse` but the `.btn` is not `.active`.

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://s.bootply.com/render/oI8gYHJ0nd), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 60, column 204: Element ```` label ```` is missing required attribute ```` role ````.
* line 61, column 147: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.
* line 61, column 147: Any ```` input ```` descendant of a ```` label ```` element with a ```` for ```` attribute must have an ID value that matches that ```` for ```` attribute.
* line 70, column 160: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.
* line 60, column 204: The ```` for ```` attribute of the ```` label ```` element must refer to a form control.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by au-phiware** [comment]
Hopefully this one is fixed: http://www.bootply.com/ZnwOepTi4Q

And this is the same but with my own hack: http://www.bootply.com/XibiUkd8mJ

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://s.bootply.com/render/XibiUkd8mJ), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 60, column 156: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.
* line 70, column 160: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://s.bootply.com/render/ZnwOepTi4Q), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 60, column 156: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.
* line 70, column 160: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by au-phiware** [comment]
Added roles:

problem: http://www.bootply.com/IgLrZUZmix

hacked: http://www.bootply.com/aNXza2jcXx

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://s.bootply.com/render/IgLrZUZmix), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 81, column 57: [E009](https://github.com/twbs/bootlint/wiki/E009): Button and input sizing within `.input-group`s can cause issues. Instead, use input group sizing classes `.input-group-lg` or `.input-group-sm`
* line 74, column 45: [W009](https://github.com/twbs/bootlint/wiki/W009): Using empty spacer columns isn't necessary with Bootstrap's grid. So instead of having an empty grid column with `class="col-xs-5"` , just add `class="col-xs-offset-5"` to the next grid column.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://s.bootply.com/render/aNXza2jcXx), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 81, column 57: [E009](https://github.com/twbs/bootlint/wiki/E009): Button and input sizing within `.input-group`s can cause issues. Instead, use input group sizing classes `.input-group-lg` or `.input-group-sm`
* line 74, column 45: [W009](https://github.com/twbs/bootlint/wiki/W009): Using empty spacer columns isn't necessary with Bootstrap's grid. So instead of having an empty grid column with `class="col-xs-5"` , just add `class="col-xs-offset-5"` to the next grid column.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by au-phiware** [comment]
Now Bootply appears to be down!

http://jsfiddle.net/kjm1k8Lb/

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://fiddle.jshell.net/kjm1k8Lb/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by au-phiware** [comment]
http://jsfiddle.net/kjm1k8Lb/2/

**Comment by hnrch02** [comment]
Went ahead and deleted the back and forth, I see what you mean now.

**Comment by hnrch02** [comment]
This is not a problem with the collapse. You wrapped the collapse trigger (the button) in a button group and that's causing the `active` class.
You should rather style the trigger based on the `collapsed` class.

**Comment by au-phiware** [comment]
Yes, I see what you mean. I can change the style by that still remains the issue of the checked property of the checkbox.

I guess I will need to listen to it's change event and ensure that it matches the state of the aria-expanded property.

I think it would be much better, however, if the collapse module could call stopPropagation on the event when it is in transition.
