### ISSUE TITLE
how to disable large desktop behavior ?

### ISSUE THREAD

**Issue by vincent3569** [twbs/bootstrap#16016]
hi
I am not sure it is an issue or not.
in customization of css, I don't want large desktop behavior.
I suppressed  values for @screen-lg, @screen-lg-min, @screen-lg-desktop,@screen-md-max and  @container-large-desktop, @container-lg
but it doesn't work and I have css rulesfor large desktop in compiled css

thanks for your help

**Comment by cvrebert** [comment]
If you want to omit LG classes from the CSS entirely, you'll have to edit the Less source code and remove them.
If you merely want to easily prevent them from ever having an effect, simply set `@screen-lg-min` to an extremely large value.
Please direct further how-to questions to StackOverflow instead of this issue tracker.
Thanks!

**Comment by vincent3569** [comment]
thanks for the answer and for the advice for StackOverflow
