### ISSUE TITLE
Dropdown menu on hover with link on parent element

### ISSUE THREAD

**Issue by saurabh-gohil** [twbs/bootstrap#16033]
Hello all,
This is not an issue but I was not sure where to put it.(Sorry)
It would be nice if you can include this feature.
Currently we have dropdown menu on click event where we can not give the link to parent button.
so it would be nice to have dropdown menu with link on its parent elements.
I am so sorry if I am not able to describe properly, however if you have any doubts please let me know I will try to describe in better way.

**Comment by cvrebert** [comment]
Bootstrap's dropdowns are deliberately click-based rather than hover-based. See http://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/ for the reasons behind this decision.
Your point about being unable to hyperlink parent menu items is specifically addressed:
> Because we use a click to trigger the dropdown in most implementations, there is no option for a parent link (one of the primary complaints in that Stack Overflow article). Pointing back to OS X and other toolbars, I don’t see this as a huge issue as it promotes our advocacy of using clicks to carry out an action instead of hovers.

I don't believe there's been any relevant change of opinion since that blog post (@mdo can please correct me if that's not the case however).
