### ISSUE TITLE
Column children height: 100%

### ISSUE THREAD

**Issue by Libaroba** [twbs/bootstrap#16060]
Am I dumb or it's just impossible? Is there any normal way (not retarded hacks which don't work in every browser) to have all columns in a row with same height and their children applied 100% height?

I'm stuck in middle of the project and I can't find any advice and I really need to get this to work because I just don't want to rewrite everything to another grid framework. To bad that on official website is not a big banner saying: "Sorry folks, we can't do it. Don't use us if you need this feature." :D

**Comment by cvrebert** [comment]
Please address how-to questions to StackOverflow in the future.
See https://css-tricks.com/fluid-width-equal-height-columns/ (in particular, the table-cell and flexbox methods). However, these come with some behavior changes (e.g. `col-*-push/pull-*` not working, stacking differences as mentioned in #13486), which is why there's currently nothing built-in for equal-height grid columns.
