### ISSUE TITLE
jspm, less, again.

### ISSUE THREAD

**Issue by jczerwinski** [twbs/bootstrap#16118]
I'd like to consume bootstrap less via jspm. The current config precludes this. Restricting jspm's files to dist is the problem.

**Comment by guybedford** [comment]
This restriction is actually being caused by the fact that the jspm GitHub endpoint will download the GitHub release zip file instead of the repo, exactly for scenarios like Bootstrap where we don't want to download all the other files which would be a slow download. This is a feature that allows GitHub as a registry to make sense as there is the ability to publish these releases like Bootstrap does.

In this case, the published release doesn't come with LESS so this isn't possible even with this config.

I know the LESS importing is a standard issue here. We're working on enabling a version of Bootstrap that doesn't come bundled with CSS soon, so that you could use this version and then just add the extra LESS compilation step manually. In the mean time, downloading Bootstrap manually or forking the GitHub repo is probably your best bet. Apologies there isn't a better story here yet, but very much aware of these constraints.

**Comment by jczerwinski** [comment]
Ah, got it. Thanks!
