### ISSUE TITLE
Problem when using rem unit together with Bootstrap

### ISSUE THREAD

**Issue by maxsite** [twbs/bootstrap#16131]
Set:
``` body { font-size: 14px; } ```

Writing:
``` <h1 style="font-size: 2rem;">Text</h1>```

Meant to be: 28px 
really: 20px

In scaffolding.less incorrectly set:
``` html { font-size: 10px; }```

The root element when using REM should BODY. Must be removed font-size in HTML-tag.

**Comment by nextgenthemes** [comment]
Why says its "incorrect"? Who says its "meant to be"?

First of all BS3 never used/supported rems. Second of all I think this 10px on the html was actually set on purpose so 1rem is 10px because lots of designers actually do think in pixels. So when I would something to 4rems with vanilla BS3 I would know its like 40px and thats totally fine with me?

I have not followed up rems for some time now, not sure whats wrong with this technique but rems are coming in v4 and I trust mdo and the guys to do it in a good way.

**Comment by maxsite** [comment]
REM - is relative units. Relative to the base font size: @font-size-base

4rem != 40px

4rem = @font-size-base * 4 = 56px

**Comment by andrew-saint** [comment]
Can't you just use @font-size-base: 1.4rem (14px) for now?

Changing the rem base will probably be something in v4 when rem's are officially supported.

**Comment by mdo** [comment]
`rem`s are based on the *root* element, and that's the `<html>` on your page, not the `<body>`. There's no `rem` support in v3 right now, so we can't help you much beyond that.
