### ISSUE TITLE
My Bootstrap v4 wishlist

### ISSUE THREAD

**Issue by alberto** [twbs/bootstrap#16275]
I was told in another thread to open an issue with my suggestions for v4, so here they are.

- (A) The behaviour of xs is inconsistent with the rest of breakpoints. col-xs-* gets kicked starting from 0px not from $screen-xs-min. It’s sometimes useful to have columns even below $screen-xs-min (although not that much without changing the gutter size), but the difference in behaviour with the rest of tiers make it confusing, IMO. Maybe it would be better to have default col-* styles between 0px and $screen-xs-min and make xs work like the rest.

- (B) Add an least an additional breakpoint for small devices. Even with the previous fix, the distance between xs and sm is too big, anyways.

- (C) Allow easily setting a different grid at a custom breakpoint using a make-column mixin. Right now, I workaround it using:
```
  @media (min-width: $bp-bigger-than-xs) {
    @include make-xs-column(4);
  }
```

- (D) Allow different font-sizes for different breakpoints. Using rem instead of px is not enough, the proportion between body and headings is not usually kept constant between desktop and mobile screen sizes.

- (E) Keep specificity to a minimum and avoid deep selectors, using specialized classes instead. It would make overriding styles easier (no need to replicate bootstrap selectors) and would decouple from the predefined html structure that some components require. The worst offender is the navbar, but there are others (carousel, pager, panel).

- (F) Decouple the javascript from the html and CSS and use custom attributes or specific js-* classes. (e.g. accordion effect only works with .panel)

- Improve mobile experience. (G) Animations should be fluid (e.g. navbar toggle), (H) switching between dropdowns should require just clicks.

**Comment by cvrebert** [comment]
(I took the liberty of adding identifying letters to each of your points so that they're easier to reference.)

> (B) Add an least an additional breakpoint for small devices. 

In fact, this has already been implemented in our v4 repo, to address #10203 and friends.

> (E) Keep specificity to a minimum and avoid deep selectors, using specialized classes instead.

This is already part of the plan.

> (F) Decouple the javascript from the html and CSS and use [...] specific `.js-*` classes. 

This is already under consideration for v4; see https://github.com/twbs/bootstrap/issues/14431#issuecomment-53163098

> (G) Improve mobile experience. Animations should be fluid (e.g. navbar toggle)

Unless you have a specific suggestion about how to achieve that, there's nothing more we can really do about the performance of the animations, at least until the browsers themselves fix their `translateZ` bugs; see #15723 and https://github.com/twbs/bootstrap/pull/13649#issuecomment-57767763

> (H) Improve mobile experience. [...] switching between dropdowns should require just clicks.

Now that [iOS's clickability bug](https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile) is more well-understood, it might be possible to address this.

**Comment by cvrebert** [comment]
> (A) The behaviour of xs is inconsistent with the rest of breakpoints. col-xs-* gets kicked starting from 0px not from $screen-xs-min. It’s sometimes useful to have columns even below $screen-xs-min [...], but the difference in behaviour with the rest of tiers make it confusing, IMO.

I am happy to report that in Bootstrap v4 we've made it much easier to add additional grid breakpoints, and that there's no longer any special-casing based on the names of the grid sizes themselves. But we do still special-case the smallest and largest grid sizes in some places, so that all the grid sizes collectively will always cover all possible viewport sizes.

So if you want to add a new breakpoint below XS, it's a one-line change, and your new smaller grid size will then start at 0px, and XS will then start from the non-zero point at which your new smaller grid size ends.
I think this should remedy your concern.

**Comment by mdo** [comment]
@cvrebert has addressed the bulk of this, so closing out.

**Comment by cvrebert** [comment]
@mdo Could you weigh in on (D) at least?

**Comment by mdo** [comment]
We'll be using rem units in v4 and won't be resetting individual sizes by breakpoint. That's a bit too much overhead and seems rather specific to the project.

**Comment by alberto** [comment]
That's great news!
> Unless you have a specific suggestion about how to achieve that, there's nothing more we can really do about the performance of the animations, at least until the browsers themselves fix their translateZ bugs; see #15723 and #13649 (comment)

Thanks, I wasn't aware of those translateZ issues.
> Now that iOS's clickability bug is more well-understood, it might be possible to address this.

Is that the reason for the current behaviour on android too? For reference, [Foundation's dropdowns](http://foundation.zurb.com/docs/components/dropdown_buttons.html) work with one click on android.

**Comment by alberto** [comment]
> We'll be using rem units in v4 and won't be resetting individual sizes by breakpoint. That's a bit too much overhead and seems rather specific to the project.

I raised it because it's something that repeats quite often in projects at our agency, I'm not sure how frequent that need is for other people.

**Comment by cvrebert** [comment]
>> Now that iOS's clickability bug is more well-understood, it might be possible to address this.
>
> Is that the reason for the current behaviour on android too? For reference, Foundation's dropdowns work with one click on android.

The relevant code just does touch event detection, not iOS UA sniffing, so it ends up being applied on Android too. It's possible that there might also have also been some Android Browser bug that necessitated its use; I'm not intimately familiar with the history of that code.
