### ISSUE TITLE
Menu Not Responding to Clicks on Phones

### ISSUE THREAD

**Issue by liben96** [twbs/bootstrap#16308]
Hi guys,

I'm using Bootstrap (last version 3.4.4) as my responsive framework.
Also I am using jQuery v1.11.0.

My site is working ok in computers (Safari, Firefox, Chrome, IE), however when I try to open my site on phones, the responsive menu is not working.
I can see the menu, the menu is collapsing ok, but when I click an option menu is not doing anything. The link doesn´t move to the selected option.

Its working ok in iPad and in some Android Phones, but in most of them is not working.
I have tried in iPhone 4, 5, 6, and in BQ E5, BQ E6.

I researched a lot, I've tried different versions of Bootstrap, but cant find the solution to my problem.
I hope you can help me.

My site is: http://mobile.solucionlegal.es/web/

Thanks,

**Comment by cvrebert** [comment]
Per our [bug reporting policy](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports):
* Please [Bootlint](https://github.com/twbs/bootlint#in-the-browser) your webpage and fix all the errors first.
* If there's still a problem after that, post a *reduced testcase* (not a complex production webpage) and we'll be happy to take a look.

**Comment by liben96** [comment]
Hi Chris,

Why did you close my post?

I have not found the answer to my question in the forum.

Thanks.

**Comment by cvrebert** [comment]
> Why did you close my post?

Because it doesn't comply with our community contribution policies.

(A) Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker , this issue tracker is used only for reporting & tracking bugs and feature requests. It is not to be used for personal support requests, which are better suited to forums specifically dedicated to that purpose, such as StackOverflow.

(B) If your post is instead interpreted as a bug report, then it has failed to comply with https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports , which calls for validating & linting your HTML beforehand and also for producing a *reduced* testcase. Your webpage has many [Bootlint](https://github.com/twbs/bootlint) warnings/errors, and is not nearly simple enough to qualify as a reduced testcase.

Therefore I closed this issue for the time being. If you were to rectify (B) as I outlined in my previous post, we would be happy to reopen the issue for further investigation.

**Comment by liben96** [comment]
OK.

Sorry Chris.

I have tried to resolve some problems with Bootlint, but there are some of them that I can’t solve.

I would appreciate if you could help me.
Im starting to use bootstrap.

One of them it says 
“Resource interpreted as Font but transferred with MIME type font/x-woff: “http://mobile.solucionlegal.es/sl/fonts/fontawesome-webfont.woff?v=4.3.0 <http://mobile.solucionlegal.es/sl/fonts/fontawesome-webfont.woff?v=4.3.0>”

However, the font is in the folder mentioned.

My site is: http://mobile.solucionlegal.es/sl/ <http://mobile.solucionlegal.es/sl/>

So, where do i have to upload my issue to get some help?

Thank you so much.

Kind Regards,

Elí Gálvez

**Comment by cvrebert** [comment]
That font problem is related to [Font Awesome](https://github.com/FortAwesome/Font-Awesome), not Bootstrap.
As stated previously, I recommend taking your question to [StackOverflow](http://stackoverflow.com/tour).
