### ISSUE TITLE
Affixed Sidebar containing accordion div

### ISSUE THREAD

**Issue by Shehab-Eltawel** [twbs/bootstrap#16356]
I use Bootstrap 3 Affix for a sidebar containing an accordion. the issue that when I scroll to the bottom and opening an accordion body , it's flow over the footer , but the offset back normal again when I click on the page. Any Ideas to stop the accordion flow over the footer normally without clicking !

**Comment by cvrebert** [comment]
Have you tried something like:
```js
$('#your-affixed-sidebar').on('hidden.bs.collapse shown.bs.collapse', function (e) {
  $('#your-affixed-sidebar').affix('checkPosition');
});
```
?

**Comment by Shehab-Eltawel** [comment]
Yes I did. it could only fix the position of the affixed div without click, but it still overlapping the footer for a second then back normal. !

**Comment by cvrebert** [comment]
I'm not sure it's feasible to avoid that split-second overlap.

@hnrch02 @XhmikosR You guys think dealing with this inter-widget interaction is inside or outside of our scope?

**Comment by fat** [comment]
I think this should be possible with css alone.

If you are correctly setting an affix-bottom class, you should be able to pin the element to the bottom of the page using the `bottom` css property rather than the `top` property.

Doing so would make your accordion grow from the bottom, up - which would mean that when the element resized it wouldn't overlap your footer.

Hard to tell though without an actual example. If you want to create a jsbin or something similar we could probably help you out.

Feel free to reopen an issue once you do, thanks!
