### ISSUE TITLE
Autocomplete component - don't hide .dropdown-menu when clicking on input 

### ISSUE THREAD

**Issue by freddyboucher** [twbs/bootstrap#16383]
Hi,
I'm using **Dropdown** for my autocomplete component.
Here the simple JsFiddle (without any suggestions refresh to keep it simple)
https://jsfiddle.net/DTcHh/7106/

My issue is; as soon as I click on the **input** and type some text in it like **"bootsrap"**, I **can't click** in the middle of the word to correct it and add the missing **"t"** to **"bootstrap"**.
If I click in it it hides the **.dropdown-menu**.

It should be really useful to have an option to not hide the **.dropdown-menu** when clicking on the **data-toggle="dropdown"** element.
Thx

**Comment by cvrebert** [comment]
My guess is that you'll probably need a few other one-off tweaks in order to make the dropdown work optimally with your widget, at which point you might be better off copying the relevant parts of the dropdown JavaScript into your autocomplete widget's code rather than invoking the stock dropdown plugin.
CC: @fat

**Comment by fat** [comment]
I dont think you'll want to use the dropdown js for your autocomplete widget. We used to maintain a typeahead (https://github.com/twbs/bootstrap/blob/54b2a0b54153debbe27ea284f18c278e0014c8b3/js/bootstrap-typeahead.js) which you could look at for inspiration on how to implement a typeahead.
