### ISSUE TITLE
Removing animated modal from DOM prevents modal on-hide cleanup events from occurring

### ISSUE THREAD

**Issue by russplaysguitar** [twbs/bootstrap#16469]
Steps to reproduce the issue:

1. Open an animated modal dialog (modal must have `fade` class).
2. Call `.modal('hide')` and `.remove()` on the modal element.

Expected result: Modal backdrop should be removed from DOM and `modal-open` class should be removed from `body` tag. 

Actual result: Modal is removed from DOM, but modal backdrop remains and `modal-open` class is still on the `body` tag. 

See test case: [JSFiddle](http://jsfiddle.net/2c4mkndh/11/)

Workarounds: 
A) Call `.remove()` on `hidden.bs.modal`. 
B) Remove `fade` from the modal. 

It makes sense why this issue occurs (modal DOM removal cleans up the transition event listeners, so cleanup never occurs), but it would be nice if the modal cleanup occurred regardless of whether the modal still exists on the DOM.

**Comment by cvrebert** [comment]
Seems to happen due to the synthetic fallback `transitionend` (or browser-prefixed equivalent) event that `emulateTransitionEnd()` fires not triggering a `bsTransitionEnd` event via the jQuery special event machinery like it normally does. I guess jQuery isn't triggering it because the element is outside the DOM?
At any rate, this doesn't appear to be a trivial thing to support and (A) is definitely already The Right Way To Do It.

Since this is similar to #16284, I propose likewise punting this to Bootstrap v4.
@fat What's your opinion here?

**Comment by fat** [comment]
yep, unfortunately, hide is async, so calling remove in a chaining method isn't going to give it time to clean itself up.

for now i think just listening to hidden event is best practice

**Comment by animafact** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

animafact@naver.com 님께 보내신 메일 <Re: [bootstrap] Removing animated modal from DOM prevents modal on-hide cleanup events from occurring (#16469)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kkirsche** [comment]
@animafact It seems you have an autoresponder setup. If you could disable this that would be greatly appreciated as it's generating a fair bit of noise.

**Comment by mdo** [comment]
@kkirsche It's basically spam—I've reported it to GitHub. We've seen this NAVER shit before :\.
