### ISSUE TITLE
dl-horizontal padding on dt and dd

### ISSUE THREAD

**Issue by dourvaris** [twbs/bootstrap#16587]
When adding a padding to dd and dt on a dl-horizontal dl the dd has additional spacing caused by display: table.

This illustrates the problem: 
http://www.bootply.com/QkKOD4TrOV

`b` gets an additional 10px padding underneath it, while `a` does not.

**Comment by kkirsche** [comment]
@dourvaris I wasn't able to reproduce this on JSBin:
http://jsbin.com/fokulokoka/1/edit?html,css,output

Is there something I am missing in this?

**Comment by dourvaris** [comment]
@kkirsche tried in both Chrome and Firefox - the problem happens on large screen (not mobile).

A screenshot of the issue: http://www.bootply.com/QkKOD4TrOV

**Comment by kkirsche** [comment]
@douvaris, my statement wasn't about me not seeing it in general, I see it in Bootply but not on JSBin thus making me think it's bootply related not bootstrap.

**Comment by dourvaris** [comment]
It happens on JSBin as well.

**Comment by kkirsche** [comment]
Ah, oops. Thanks for pointing that out :smiley:. Must have missed that

**Comment by kkirsche** [comment]
So I was able to isolate where it's coming from:

```css
@media (min-width: 768px)
.dl-horizontal dd {
  margin-left: 180px;
}
```

Without that line it fixes the issue.

**Comment by kkirsche** [comment]
Pull request with fix, and example JSBin demonstrating the fix, submitted.

**Comment by kkirsche** [comment]
OK, so after me misunderstanding the original issue, I've looked deeper into what @dourvaris said and it seems to me that this is being caused by the clear fix which bootstrap uses. See here for details on the clear fix: http://nicolasgallagher.com/micro-clearfix-hack/

By removing the clear fix this goes away, but I don't know if there is a specific reason this is being applied here. What are your thoughts @mdo and @cvrebert as you guys are more experienced with when this was implemented and would probably have a better understanding of the implications of removing the clear fix from this?

X-Ref: #16401

**Comment by mdo** [comment]
Don't think there's anything we'll be changing here—can't get away from the clearfix. You're right @kkirsche that this is a `display: table` and clearfix collision problem. I've seen similar things like it across other projects.

I think your best bet is to override/nullify those clearfix properties. Sorry :\,
