### ISSUE TITLE
Chrome bug - Modal open more then one at time

### ISSUE THREAD

**Issue by parisnakitakejser** [twbs/bootstrap#16594]
i use modal dynamic and i use this JS code.

	$("a[data-toggle=modal]").click(function (e) 
	{
		target = $(this).attr('data-target');
		dataTitle = $(this).attr('data-title');
		urllink = $(this).attr('href');
		$("#modalContent").load(urllink, function(){
			onDocumentStart();
		});
	});

This make its easy for me to create links into modal open boxes, and redeclare new stuff. the problem is in Safari the timeline working fine, and i only one 1 extern url from my a tags even if i open/close 10 times, when i do the same thing in Chrome Version 43.0.2357.81 (64-bit) its first time open 1 so 2, 4,8,16 and so every time the last number * 2 for next time i open.

i have recored 2 movies of this bug.
Safarie - working well: https://www.dropbox.com/s/d9g6zs9lsjonk0n/safarie%20-%20okay.mov?dl=0
Chrome - bug: https://www.dropbox.com/s/maeiwxn56m8fb00/chrome%20-%20bug.mov?dl=0

Hope you can explain whats happen for this bug, i use Bootstrap 3.3.4 and jQuery 2.1.4 and here is my html code to open this modal.

Modal HTML:
	&lt;div class="modal fade" id="modalDialog">
		&lt;div class="modal-dialog" id="modalContent">&lt;/div>
	&lt;/div>

Link HTML:
	&lt;a href="{%fpPath%}action/organization/create" data-toggle="modal" data-target="#modalDialog" class="btn btn-block btn-primary" role="button">Add your organization now&lt;/a>

hope my bug message are use full :+1:

**Comment by kkirsche** [comment]
Hey,

Multiple open modals are not supported (if I understood correctly). Any multi open modal support would be a personal support request and would need to be asked on Stack Overflow, Slack or IRC per Contribuiting.md. Thanks for understanding!

If I misread your bug report though, just let me know. I sometimes miss stuff :smiley:

**Comment by cvrebert** [comment]
If you have an `a[href]` with `data-toggle="modal"`, Bootstrap will do the loading of the remote URL itself. This is the **deprecated** `remote` option/feature mentioned in the modal documentation.
In your case, I would recommend you not use `data-toggle` and instead do the showing of the modal (i.e. call `$(...).modal('show')`) in your `load` callback yourself.

**Comment by parisnakitakejser** [comment]
have you see the movie's? Chrome starting to open 1 so 2, 4, 8, 16, 32 and so if you stay on the same pages and open, close, open, close the modal dialog. thats the bug if i do the same in Safarie everyting working as its shut be.

**Comment by cvrebert** [comment]
It's not unlikely that your code suffers from multiple bugs. The code you posted is too incomplete to fully debug. This is why [we specifically request that bug reports include live examples](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports) such as [JS Bins](http://jsbin.com).
Also, given the severity of the problem, the popularity of Bootstrap, and the fact that we haven't gotten any other recent reports of this problem, it's unlikely that your problem is due to a bug in Bootstrap itself.
So this is most likely [a personal support request, which falls outside the scope of this bug tracker](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker) and would be better suited to a help forum such as [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3).

Additionally, IIRC, some folks whose pages unnecessarily/incorrectly load Bootstrap's JavaScript multiple times have run into problems similar to yours, so check to ensure you're not doing that.
