### ISSUE TITLE
Chrome issue with jumpy navbar-text.

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#16606]
1. Go to http://output.jsbin.com/vukoxa/2/ (or http://jsbin.com/vukoxa/2/edit?html,output to be able to edit)
2. Decrease width until menu collapses into hamburger.
3. Increase width again.
4. The navbar has now a second row with the nav-bar text (description) being there instead of its old position.

Reproducible under newest stable Chrome but not Firefox or IE under Windows.

HTML5 validation and bootlint passed.

**Comment by Herst** [comment]
Image illustrating the issue:
![bsissue](https://cloud.githubusercontent.com/assets/1042176/8056781/c2d3cf30-0eab-11e5-9450-bf05b56802d1.png)

**Comment by fokusferit** [comment]
I've looked into it, and it seems that there are different width's calculated -> 

![image](https://cloud.githubusercontent.com/assets/1215719/8057492/0774e150-0eb2-11e5-9e5e-85fdb07d88f5.png)

![image](https://cloud.githubusercontent.com/assets/1215719/8057500/16dc52cc-0eb2-11e5-9029-21d7f4f2b125.png)

min-width: 170px; helps for the beginning.

**Comment by zacechola** [comment]
@fokusferit It's because, when collapsed, the `.navbar-heading` becomes `display: table`.

@Herst You have some options, as explained in #11539:

- Change the grid float breakpoint so that the navbar stays collapsed until the screen is wide enough for your `.navbar-text`.
- Use the [responsive utility classes](http://getbootstrap.com/css/#responsive-utilities) to hide some parts of the navbar at narrower screen widths so that it fits at those widths
- Rework your content's width
- [You can also override the `.navbar-text` to float the text](http://jsbin.com/yocayu/1/edit?html,output), though, depending on the width of your text, you will need to explore the above options, as well.

**Comment by mdo** [comment]
Closing per @zacechola's suggestions. Not much we can do here otherwise I think.

**Comment by Herst** [comment]
Thank you, adding "float: left" really solved it from me and from what I can see even setting an absurdly long description (in my case the user can set it) leads to an acceptable result.
