### ISSUE TITLE
Chrome> table > td > .input-group

### ISSUE THREAD

**Issue by xxwgcg** [twbs/bootstrap#16613]
..................
&lt;td&gt;
&lt;div class="form-group"&gt;
    &lt;label class="sr-only" for="exampleInputAmount"&gt;Amount (in dollars)</label&gt;
    &lt;div class="input-group"&gt;
      &lt;div class="input-group-addon">$</div>
      &lt;input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount"&gt;
      &lt;div class="input-group-addon">.00</div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;td&gt;
..............
This looks very strange
My English is not good

**Comment by patrickhlauke** [comment]
We'd need to see a live example (a reduced test case, just showing the issue itself) on http://jsbin.com/ or http://jsfiddle.net - but fundamentally: if you're using tables for layout and then try to stick Bootstrap components inside, you're likely going to have strange issues. Don't use tables for layout would be the quick answer...

**Comment by xxwgcg** [comment]
this is => http://output.jsbin.com/nuvinogixi
please use chrome and firefox open link

**Comment by xxwgcg** [comment]
I have solved the problem in other way, just to tell you here

**Comment by patrickhlauke** [comment]
your jsbin looks fine to me...not quite sure what your problem here is. As this seems to be a request specific to the way you're (ab)using Bootstrap, rather than a report of a problem with Bootstrap itself, I'd suggest asking for further help/clarifications on StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
Thanks.

**Comment by cvrebert** [comment]
Approximate duplicate of #16372. We've already filed bugs about it with the browser vendors.
