### ISSUE TITLE
Desktop grid works fine, at around 1170px all columns act like a col-lg-12 with a "display: block;" attribute

### ISSUE THREAD

**Issue by realrasputin** [twbs/bootstrap#16709]
Hey guys,

So, I'm creating this website and everything is perfect on a desktop. However, all hell breaks loose at around 1170px or so.

Basically, it doesn't matter which "col-lg-#" class I give the `<div>`, it just turns to 100% width and acts like a block element. For instance, I have three boxes up top with this class:
```html
<div class="col-lg-4 col-md-4 col-sm-12">Content</div>
<div class="col-lg-4 col-md-4 col-sm-12">Content</div>
<div class="col-lg-4 col-md-4 col-sm-12">Content</div>
```
All of them are inline-block elements. However, for some reason, at a certain resolution, these column width classes just seem to be completely ignored, as well as the inline or inline-block attribute. It just doesn't make any sense. I've used Bootstrap before and have never had this issue. But, right now, I cannot figure it out to save my life. 

The only solution I can think of, is putting everything in an unordered list and adjusting the placement of everything with padding. However, that's just dumb and would take way too long.

Here are some screenshots of my issue:
http://imgur.com/a/1nGaJ

I would add my code, but I'm not sure where this issue is occurring because it's occurring for EVERY SINGLE col-lg-#, col-md-#, etc. Therefore, I don't know what I'd throw up here.

**Comment by cvrebert** [comment]
> All of them are inline-block elements.

How? `<div>`s are `display: block` by default and Bootstrap doesn't change that. The `col-*` classes don't override `display`.

---

Sorry, but unfortunately we don't have the resources to debug problems in folks' individual websites without a [reduced test case](https://css-tricks.com/reduced-test-cases/) when the problem is unlikely to be due to a bug in Bootstrap itself (which is the case here, since we'd be getting tons of bug reports if we'd actually broken the grid somehow).
Personal support requests like this should be directed to [StackOverflow](https://stackoverflow.com/questions/tagged/twitter-bootstrap-3) (or similar) rather than this bug tracker.
That said, if you're able to craft a reduced test case that demonstrates the problem, feel free to open a new issue with a link to your test case. See also https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports
Good luck!
