### ISSUE TITLE
Better Navbars.

### ISSUE THREAD

**Issue by neotropic2023** [twbs/bootstrap#16786]
A framework that has a set of specific navbars that like no one uses.Except in examples and demos, LULZ!!!!! 

99% of the websites I visit do not use that. 
MAYBE only when it is mobile. 
Not Desktop.

So make better navbars or more without the logos and make it easier to create a navbar without a logo instead of having to jerry rigg the hell out of the CSS.

**Comment by patrickhlauke** [comment]
Thanks for your feedback. Bootstrap assumes that you're capable, if you don't like elements like the demo navbars, to actually make your own.

**Comment by mdo** [comment]
FWIW, we do need better navbars, but that's not something we can just do whenever we're asked. It takes time to feel out a solution and implement it in a way others can use. The current isn't perfect, but it's useful in many ways still.

I appreciate the comment, but not the snark. Instead of tell us how bad we're doing right now, maybe propose specific changes or examples we could build? Or have a go at it yourself even? We're all about improving things here—we're just short on time in most cases.

<3
