### ISSUE TITLE
panel-group with panel-collapse mixed with table

### ISSUE THREAD

**Issue by tiagocassio** [twbs/bootstrap#16797]
The panel-group component does not mixing the both sides of table component when is inserted inside a panel-collapse. if i put "panel panel-collapse collapse", the panel-heading is rendered without border-size and color.

**Comment by cvrebert** [comment]
@tiagocassio We can't help you unless you post a JS Fiddle that demonstrates the problem.

**Comment by tiagocassio** [comment]
Oh, sorry my bad! Please check:

- This first is inside a panel-collapse without .panel class (see the table border at bottom is not aligned with the panel):
http://jsfiddle.net/ns4t2rbc/

- This other is inside a panel-collapse with .panel class (see, the panel-heading without bottom border. its looks like the table is inserted inside the panel-heading and not the "shadow" panel-body class istead):
http://jsfiddle.net/ns4t2rbc/

**Comment by cvrebert** [comment]
X-Ref: #17395

**Comment by mdo** [comment]
Calling it a won't fix. It wouldn't be *too* difficult to add support for responsive tables in collapsing panels, but I'm honestly completely unmotivated to do it given it'd add a decent amount of new selectors to the compiled CSS. It's possible, but not all the worthwhile (because v4 mostly).

Also, that second example is invalid—no `.panel` class should be on the collapsing element.
