### ISSUE TITLE
Screen reader reads progress bar value twice

### ISSUE THREAD

**Issue by seancurtis** [twbs/bootstrap#16801]
When a screen reader encounters a progress bar it announces the aria-valuenow attribute, but it does so after it's read the text content. This leads to "Six zero percent, sixty percent, progress indicator". The first part is doubled up, and not really nice to decipher. Is this doubling-up just there to support specific screen readers?

Adding role="presentation" to the progress-bar div (and moving the attributes up to the .progress div) fixes this.

**Comment by patrickhlauke** [comment]
Just did some quick testing of the examples in http://getbootstrap.com/components/#progress with Chrome/IE11/Firefox in combination with both Jaws 16 and NVDA. In all combos, the examples are simply announced as "60 - progress bar" or similar. no repetition. What screen reader are you experiencing the issues you described in?

**Comment by patrickhlauke** [comment]
Narrator/IE11 does seem to double up announcement, but in a reasonable way (considering it already announces quite a lot) - "60% complete - 60% progress bar - current value 60 - minimum value 0 - maximum value 100"

Doing some further test with a reduced example:

```
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    <span class="sr-only">60% Complete</span>
  </div>
</div>

<progress value="60" max="100">60 % Complete</progress>
```

Talkback/Chrome on Android seems to completely ignore both ARIA-fied `role="progress"` and native `<progress>` elements...which is a pain.

VoiceOver/Safari on iOS seems to be the one that reads out "60% complete - 60.00 - 60%", while the native `<progress>` is announced as "60.00 - 60%"

VoiceOver/Safari on OSX seems to be the one you alluded to in the original report. This announces "six zero complete [ed. annoyingly, it doesn't actually read it correctly as 60%] - 60 percent - progress indicator" for the Bootstrap/ARIA one and "60 percent - progress indicator". 

In short: no doubling-up with NVDA/JAWS16 in Firefox/Chrome/IE; the doubling-up happens in Narrator/IE (though in an understandable way), VoiceOver/iOS (in a reasonably understandable way) and VoiceOver/OSX (where VO seems to mess up reading "60% complete"). Of these, I'd consider the last one (VO/OSX) to be a bug (reading "six zero complete" instead of "60% complete"), and the other two reasonable.

Considering that the "60% Complete" text inside the `<div role="progress">` is actually meant to also serve as a human-friendly text to be announced (if hidden with `.sr-only`) or displayed (if no `.sr-only` is used), I'm actually more annoyed that NVDA/JAWS16 don't double-up the reading...this means that human-friendly text will have to be injected via `aria-valuetext` as well (and then the text inside it hidden, probably with `aria-hidden="true"` on a `<span>` wrapped around that text).

I'll ponder a change to that effect for the docs, though sadly this makes triple work for people wanting to use this component, as they'll need to programmatically update the `aria-valuenow`, the `style`, `aria-valuetext` and the inner `<span>` ... perhaps time to look at using a native `<progress>` element which would at least cut down on this a bit. Probably something for v4 though. /cc @mdo

**Comment by patrickhlauke** [comment]
Testing a rather crude fix with `aria-valuetext` and `aria-hidden`

```
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;" aria-valuetext="60% Complete">
    <span aria-hidden="true">60% Complete</span>
  </div>
</div>

<progress value="60" max="100" aria-valuetext="60% Complete">60 % Complete</progress>
```

VoiceOver/Safari on iOS now announces both as "60% Complete - 60%" (which is nice, consistent, and suppresses the "60.00" it used to announce for both)

VoiceOver/Safari on OSX, however, makes even more of a mess - now in both cases, it announces "six zero percent complete - 60 percent - progress indicator" ... so definitely something worth reporting as a bug to VO team, I reckon (for the inability to read "60% Complete" correctly)

In Narrator/IE, the `aria-valuetext` is ignored on the native `<progress>`, so the result is unchanged "60% progress bar"

NVDA/IE reads "progressbar - 60" in all cases, ignoring both the contained text of the original, and the `aria-valuetext`.

NVDA/Chrome improves from "progressbar - 60" in the original examples to "progressbar - 60% Complete" for both, which is excellent.

NVDA/Firefox seems to ignore the `<div role="progressbar">` completely once the above fixes with `aria-hidden` and `aria-valuetext` are applied - which is a big fat bug it seems

No time to test other combos just now, but the too long;didn't read here seems to be that this is an area of great inconsistency between browsers/AT. will need to do some deeper testing and compile some form of comparison table, I think...but in the short term, I'm loathe to modify the current pattern used, as that seems to (barring some occasional doubling-up) provide a reasonable compromise that actually works to an extent in most combos.

**Comment by vivek574** [comment]
Hi,

Chromw/NVDA reads ETF ID twice :  


<div style="overflow: hidden; width: 308px; height: 27px;"><div class="com-sencha-gxt-theme-base-client-field-FieldLabelDefaultAppearance-Style-fieldItem" id="v3-widget-v3-widget-EMPLOYER.EMPLOYER_CODE-v3displayfield-v3fieldlabel" style="overflow: hidden; width: 308px; height: 22px;"><label for="v3-widget-EMPLOYER.EMPLOYER_CODE-v3displayfield-input" class="com-sencha-gxt-theme-base-client-field-FieldLabelDefaultAppearance-Style-fieldLabel" style="width: 150px; white-space: normal;">ETF ID:</label><div class="com-sencha-gxt-theme-base-client-field-FieldLabelDefaultAppearance-Style-fieldElement" style="padding-left: 155px;"><div tabindex="-1" id="v3-widget-EMPLOYER.EMPLOYER_CODE-v3displayfield" class="v3displayfield" style="padding: 3px; overflow: hidden; white-space: nowrap; width: 147px; height: 16px;"><input type="text" readonly="readonly" tabindex="0" class="" id="v3-widget-EMPLOYER.EMPLOYER_CODE-v3displayfield-input"></div></div><div class="com-sencha-gxt-theme-base-client-field-FieldLabelDefaultAppearance-Style-clearLeft"></div></div></div>
