### ISSUE TITLE
Strange behavior with tables on firefox

### ISSUE THREAD

**Issue by cristalembalagens** [twbs/bootstrap#16830]
I don't know if this is a firefox bug or bootstrap bug, but as I am using bootstrap and it has some responsive css with different display sizes, I will post it here.

I have a sequence of div and tables to build a report, the tables are within a div with table-responsive but even I remove this class the bug still remains. The issue is when the viewport is 991px or less it shows the first table, when it grows over this size the table just dissapears, if I drop the first node and make the second node to be the first, it also disappears. This behavior happens only on firefox, I didn't see it on Chrome, IE or Safari (on iOS). I took some pictures to illustrate better what's happening.
![imagem da pagina 2015-07-15 - 17 12 57](https://cloud.githubusercontent.com/assets/10708891/8708988/c249e744-2b15-11e5-9120-1f6eb3eef7ed.png)
![imagem da pagina 2015-07-15 - 17 12 47](https://cloud.githubusercontent.com/assets/10708891/8708987/c246c096-2b15-11e5-9f66-5cfa205cc07c.png)

**Comment by Afrodyta127** [comment]
I like this:)
Mariola - Die stolze Polin:)

**Comment by cvrebert** [comment]
@cristalembalagens We can't debug screenshots. Please post a JS Bin or JS Fiddle demonstrating the problem.

**Comment by cvrebert** [comment]
Also, what OS are you using?

**Comment by cristalembalagens** [comment]
@cvrebert I'm using Windows 7 SP1. Here is the JSFiddle http://jsfiddle.net/eurpLuh0/ I just copied the html generated to the fiddle, but you will need a large display to reproduce the behavior. If you resize the result frame to the left you will see that the first table will disappear on firefox when it becomes larger than 991px. The contents copied are the same of those in the screenshots.

**Comment by twbs-lmvtfy** [comment]
Hi @cristalembalagens!

You appear to have posted a live example (http://fiddle.jshell.net/eurpLuh0/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 38, column 66983 thru line 38, column 67039: Duplicate ID ```` tabelapv48347736 ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
After fixing the duplicate ID: http://jsfiddle.net/cvrebert/5w8hfvrj/

**Comment by cristalembalagens** [comment]
I made another fiddle with a fix to duplicated id if you still need it. http://jsfiddle.net/br0rwju4/

**Comment by twbs-lmvtfy** [comment]
Hi @cristalembalagens!

You appear to have posted a live example (http://fiddle.jshell.net/br0rwju4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 38, column 26: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 1340: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 3749: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 6888: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 12947: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 29226: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 30175: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 36964: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 37913: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 46162: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 48571: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 50980: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 53024: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 54338: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 59667: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 62441: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 74340: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 82224: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 83538: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 38, column 26: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 1340: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 3749: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 6888: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 12947: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 29226: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 30175: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 36964: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 37913: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 46162: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 48571: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 50980: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 53024: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 54338: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 59667: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 62441: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 74340: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 82224: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`
* line 38, column 83538: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8"` is redundant and can be simplified to `class="col-md-offset-4 col-lg-offset-4 col-md-8"`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cristalembalagens** [comment]
I deleted the post that generated another automatic post because @cvrebert already fixed the duplicated id.

**Comment by cvrebert** [comment]
Closing per the numerous Bootlint errors, which are likely causing your problem.
As requested in [the bug reporting guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), in the future, please [Bootlint](https://github.com/twbs/bootlint) your code prior to filing an issue.
Also, please avoid posting unnecessarily huge examples in the future. The only reason @twbs-lmvtfy did not complain about my deleted JS Fiddle is because the source code was too large for Bootlint to handle (I checked our server logs).

**Comment by cvrebert** [comment]
(If your problem still persists after fixing all Bootlint warnings/errors, feel free to open a fresh issue with a revised example.)

**Comment by cristalembalagens** [comment]
I didn't know bootlint, I've now made some tests and found what was the problem. When I use class="col-md-offset-4 col-md-8 col-lg-offset-4 col-lg-8" in the div before the div with .table-responsive it causes the issue, but if only remove the classes col-lg-8 and col-md-8 leaving only the offsets it works perfectly, but it's still a strange behavior because it only happened with firefox and in the first table.

I'm so sorry about opening this unproductive issue and now that I know bootlint I will take more care before opening new issues.

Thanks for all the support.
