### ISSUE TITLE
.text-left not working on btn-block v3.3.5

### ISSUE THREAD

**Issue by bslugger** [twbs/bootstrap#16836]
The typography helper classes of .text-left / .text-right are not working on .btn.btn-*.btn-block.  I've even tried adding this class to the buttons on getbootstrap.com with no success.  Looking at the css, .text-left has less priority than the .btn class (which as text-align: center as its value). Attached is a screen-shot.
![screen shot 2015-07-16 at 3 00 05 pm](https://cloud.githubusercontent.com/assets/3834941/8736205/69b16556-2bcb-11e5-99ba-0d5a412abe30.png)

**Comment by cvrebert** [comment]
Perhaps `.text-left` should use `!important`

**Comment by bslugger** [comment]
One way I got this working was by putting a nested div* with class
`.text-left`. Thankfully the div didn't mess with the shape of the button
(since it doesn't seem to be adding a padding or margin). Including a
call-out with an acceptable approach is just as good. On the other hand,
per your suggestion, it does make sense to use `!important` since
`.text-left` is a helper class.

  *I used a div because I used a span for a glyphicon inside this div and
then preceeded with the text, shown below.

```
<a class="btn btn-primary btn-block">
  <div class="text-left">
    <span class="glyphicon glyphicon-file"></span>
    Documents
  </div>
</a>
```

One tangential side note; btn-block doesn't overflow-wrap text.  In the
above example, if the text "Documents" were a longer sentence, the text
would just continue off the button. :(

**Comment by mdo** [comment]
Why do you need `.text-left` in a `.btn-block`? The whole point of those buttons is center-aligned, full-width buttons. Undo-ing that seems counterintuitive.

**Comment by fvignals** [comment]
1. @mdo " Why do you need .text-left in a .btn-block?  ": why not ?
2. @bslugger : text-left mean text left ( I worked hard ), i.e. you must understand: article > p or somethink like that. 
With btn where are in the UI so you must use a new rule (css class) for that. And you must play with the padding and it's ... boring ... since vanilla I hate padding, margin.

**Comment by mdo** [comment]
> Why not?

That's not an approach we subscribe to here :).

Beyond that, there are multiple known issues with those utility classes given they lack any `!important`. However, I'm hesitant to change that behavior in v3 since folks likely don't expect that to change. For the time being, I'm inclined to punt as a won't fix because of that and the fact block buttons are supposed to be center aligned.

**Comment by bslugger** [comment]
@mdo I assumed that the `.btn-block` was more so to have the button span
the width of the parent. If I wanted to have the text centered, I would
have just just used a normal button and then centered the button (or at
least that's my rationale). I was thinking that having control over the
alignment of the text provides a bit more flexibility in terms of
personalization and styling for the btn-block. This includes times when the
width of the parent is larger than expected and the text placement can
effect the how one visually scans for the button.  ~$.02  :)

**Comment by fvignals** [comment]
This is the big problem (or 1 of them) of Bootstrap ... too many paddings that complicate personalization. 
@bslugger : so you must kill the padding : span tag with a display: block; line-height: in px; width: in px; and you could apply a horizontal and even a vertical alignment add the Bs style and you're done. There are many other solutions of course.
@mdo: In my mind v3 must kill most of padding. The UI, at this time is limit to the touch UI (I touch my smartphone, tablet, computer, ... my destock screen and tv are exempt a this time). If UI is good for touch is good for click, the opposite is false imho.
 So we are in static size of the UI elements (the layout and text should be more in percent). Google is oriented 48DP in the design (Android computer with large screen are coming) .
With a static size the padding could be kill. (even it is present in android design ˆˆ).
Hope I'll inspire you

**Comment by mdo** [comment]
The only sensible change here, beyond the button block component, would be throwing `!important` on these helper classes. We can't do that in v3 though since I can imagine ruining folks' lives by making that kind of change so late in the game. So, for now, we're punting on it. Come v4 though we should revisit this kind of stuff so the utilities can do what they need to.

**Comment by bardpresent** [comment]
The trouble is not how to css text-align to the left, the original post was asking if there is a bootstrap class name(s) works for it.
You can check the image from the first post. The .text-left works, but the trouble is there is a .btn that is stronger than text-left, I think this is something bootstrap need to think about.

**Comment by cvrebert** [comment]
@bardpresent This problem has been addressed in Bootstrap v4. As previously mentioned, this isn't fixable in v3 due to backward compatibility requirements.

**Comment by herrherrmann** [comment]
In case anyone is interested in a little solution I came up with: I just created two new classes for this approach since I need to align text in btn-blocks quite frequently.

```LESS
// LESS
.btn-block {
    &.btn-block-left {
        text-align: left;
    }

    &.btn-block-right {
        text-align: right;
    }
}
```
