### ISSUE TITLE
Tooltip bug in a button group

### ISSUE THREAD

**Issue by stanislavfm** [twbs/bootstrap#16854]
There is a problem with displaying the tooltip on a button, which placed in the button group.

https://jsfiddle.net/eex6tv2e/2/

**Comment by acshef** [comment]
This issue has come up a few times in different situations, but it's always because the tooltip (or popover) is getting inserted into the DOM *between* the buttons, and the buttons normally have some form of `.btn+.btn` CSS to control the borders in-between. Here are a couple of reasonable solutions: https://jsfiddle.net/eex6tv2e/4/

The first adds CSS to correct the issue, the second changes which element the tooltip is applied to. I prefer option one, but it's up to you. I have a feeling that the Bootstrap guys would recommend option 2, except the problem is that the inside `div` by itself does not have the full width and height of the button (that's what the corrective CSS is for). So my opinion is, if you're going to have to correct the CSS for that, why not go with option 1 in the first place?

**Comment by twbs-lmvtfy** [comment]
Hi @acshef!

You appear to have posted a live example (https://fiddle.jshell.net/eex6tv2e/4/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 70, column 51 thru line 70, column 55: Element ```` div ```` not allowed as child of element ```` button ```` in this context. (Suppressing further errors from this subtree.)
* line 71, column 51 thru line 71, column 55: Element ```` div ```` not allowed as child of element ```` button ```` in this context. (Suppressing further errors from this subtree.)
* line 72, column 51 thru line 72, column 55: Element ```` div ```` not allowed as child of element ```` button ```` in this context. (Suppressing further errors from this subtree.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
See http://getbootstrap.com/javascript/#callout-tooltip-groups and https://github.com/twbs/bootlint/wiki/W008
