### ISSUE TITLE
What is the minimum version of Less required to compile Bootstrap v3?

### ISSUE THREAD

**Issue by neocotic** [twbs/bootstrap#16876]
I was hoping someone could tell me what the minum version of LESS that is required to compile Bootstrap v3 source code?

I'm currently working on a project that's using Maven to build the frontend files so the versions of LESS that I have available is restricted by the support from the available plugins, unless I wrote my own. I'm not sure if there's an easy way to check this or if it's possible at all.

I'm trying to avoid scanning the source code and comparing to release notes. I couldn't find an official note anywhere of what version is needed so any guidance would be much appreciated.

**Comment by mdo** [comment]
I couldn't tell you off the top of my head without testing them all out myself. Maybe someone else has done just that though?

**Comment by cvrebert** [comment]
Per our `package.json`, we currently depend on `grunt-contrib-less@~1.0.1`, which in turn depends on `less@~2.4.0`. It's possible that older versions might still suffice.

**Comment by cvrebert** [comment]
Since we don't offer official support for compilation methods other than our provided Gruntfile, and since it's unlikely anyone on Core Team wants to do the laborious testing to determine the bare minimum necessary Less version, I'm going to close this. You might try asking your question on [one of the community discussion venues](https://github.com/twbs/bootstrap#community) (e.g. StackOverflow, IRC, Slack) instead. Though if anyone who has the answer happens to be watching this issue, feel free to chime in here. 
Good luck!
