### ISSUE TITLE
Customizer page takes ages to load in China

### ISSUE THREAD

**Issue by mevsme** [twbs/bootstrap#16886]
External jquery lib at ajax.googleapis.com doesn't loads -_-
Customizer doesn't works.

**Comment by kkirsche** [comment]
@mevsme Not as easy, but you could download the LESS source and just modify `variables.less` then build it yourself. Could also probably download the repo, replace `ajax.googleapis.com` with a local instance of jQuery, build the docs, and run the customizer from there (haven't tried that myself though to know if it would work)

**Comment by cvrebert** [comment]
Try using the unofficial Chinese translation of the docs: http://v3.bootcss.com/customize/
It uses its own CDN for jQuery.

**Comment by cvrebert** [comment]
@twbs/team Given that the customizer is going bye-bye in v4 anyway, and the availability of the bootcss.com version, how would folks feel about closing this as WontFix?

**Comment by XhmikosR** [comment]
Actually, this is something I've been meaning to take a look at. Well, not the China issue per se, but adding a local jQuery fallback.

**Comment by coliff** [comment]
HTML5Boilerplate recently switched from Google's CDN to jquery.com's CDN (Ref: https://github.com/h5bp/html5-boilerplate/issues/1737#event-510018696) so that users in China don't have any problems. Could we consider changing the CDN to jQuery?

**Comment by XhmikosR** [comment]
To be honest, why would we care for censorship? I see the point of this, but we already have a fallback anyway.

**Comment by coliff** [comment]
As explained at H5BP (https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/html.md)

"The jQuery CDN version of the jQuery JavaScript library is referenced towards the bottom of the page. A local fallback of jQuery is included for rare instances when the CDN version might not be available, and to facilitate offline development.

The jQuery CDN version was chosen over other potential candidates (like Google's Hosted Libraries) because it's fast (comparable or faster than Google by some measures) and, (unlike Google's CDN) is available to China's hundreds of millions of internet users.

For many years we chose the Google Hosted version over the jQuery CDN because it was available over HTTPS (the jQuery CDN was not,) and it offered a better chance of hitting the cache lottery owing to the popularity of the Google CDN. The first issue is no longer valid and the second is far outweighed by being able to serve jQuery to Chinese users."

**Comment by XhmikosR** [comment]
Still, that doesn't answer why we should circumvent censorship of any way.

I don't want to get political, I simply don't believe we should do do anything about it because it's just compromising.

**Comment by coliff** [comment]
It's not compromising though - the jQuery CDN is comparable or faster than Google's by some measures. Choosing a different CDN doesn't 'circumvent censorship' at all. - its really got nothing to do with politics.

There are about 500 million Internet users in China. Surely its better to use a CDN with 100% global coverage rather than one with less?

**Comment by XhmikosR** [comment]
I personally don't agree with this. Because, to me, changing the CDN isn't worth it in this case.

Either way, feel free to open a new issue.
