### ISSUE TITLE
Different behaviour of .dropup and .dropdown

### ISSUE THREAD

**Issue by Neologist** [twbs/bootstrap#16913]
Referring to the docs (http://getbootstrap.com/components/#dropdowns) the only difference between the .dropdown and the .dropup class should be that one is opening downwards and the other one upwards.

In fact they behave different if you click inside them. The .dropdown will stay open and the .dropup will close immediately. If you just put an `<ul>` with links inside the container you won't notice this issue but if you work with other elements (e.g. a form inside of the container) it won't work because the dropup will close as soon as you want to fill a form field.

**Comment by cvrebert** [comment]
This presumably happens because https://github.com/twbs/bootstrap/blob/5c028448c1fc171cf4a0fd99d3a672b649bef2aa/js/dropdown.js#L160 doesn't include `.dropup`

There are a couple additional instances of this in other plugins:
* https://github.com/twbs/bootstrap/blob/5c028448c1fc171cf4a0fd99d3a672b649bef2aa/js/scrollspy.js#L119
* https://github.com/twbs/bootstrap/blob/5c028448c1fc171cf4a0fd99d3a672b649bef2aa/js/tab.js#L95

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
