### ISSUE TITLE
how to add "screen" media type to Bootstrap's @media queries

### ISSUE THREAD

**Issue by Mrkhagol** [twbs/bootstrap#16981]
Hi,

Is there a way to add "screen" types to @media rules in customized compiled bootstrap css. 

It seems when there is a print in chrome/firefox, they are picking up @media max/min-width rules and setting them up in print preview. 

I was able to do a workaround by implying @media screen  and @media print but was wondering if customized bootstrap allows for adding screen type to @media rules.

Thanks.

**Comment by kkirsche** [comment]
I don't believe so in V3 and I doubt it will be added as that seems a large change as V3 approaches maintenance only — though a large majority of bootstrap uses `@media screen` or `@media print` which should override those even when build in a custom manner

**Comment by cvrebert** [comment]
There's nothing built-in for it, but I'm sure it's possible to write a relatively simple [CSS postprocessor](https://github.com/postcss/postcss) to do that.

Offering nontrivial print styles is currently a non-goal for Bootstrap, not least because [the browsers themselves are buggy](http://getbootstrap.com/getting-started/#support-printing) and not well-standardized in the area of printing.
