### ISSUE TITLE
Focus state issue on btn-primary button

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#17000]
Discovered an issue with focus state of `.btn-primary`. There are two classes that need not be included and are causing the btn to turn to it's bootstrap blue background-color when focused. To test, inspect element on btn-primary, then turn on active and focus states at the same time. A way to solve this issue is to apply a background-color to the following classes. But this is an unnecessary task.

`.btn-primary:active:focus` and `.btn-primary.active.focus` states.

```
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus 
{
    color: #fff;
    background-color: #204d74;
    border-color: #122b40;
}
```

**Comment by cvrebert** [comment]
@guylepage3 
> There are two classes that need not be included

Which two classes? I assume you mean `.active` and `.focus` ?
Need not be included *in what*?

> are causing the btn to turn to it's bootstrap blue background-color when focused.

Please be more specific. `.btn-primary.active.focus` is currently `background-color: #204d74`. Please explain what color you think it should be, and give your reasoning for why.

**Comment by cvrebert** [comment]
Presumable X-Ref: https://github.com/blockstack/blockstack-site/issues/32

If you're trying to customize Bootstrap's buttons, you should either:
* Recompile Bootstrap with the [`@btn-primary-*` variables](https://github.com/twbs/bootstrap/blob/767cbef6d43fc773461ab178162bdf3ace6e750c/less/variables.less#L152) set to different values (and not vendor the vanilla precompiled CSS); or
* Invoke the `.button-variant()` mixin with your own custom color values instead of [the default ones](https://github.com/twbs/bootstrap/blob/767cbef6d43fc773461ab178162bdf3ace6e750c/less/buttons.less#L70)

If you have further questions about how to customize Bootstrap, please use [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3). Thanks.

**Comment by guylepage3** [comment]
Hi @cvrebert, my bad, I meant that the variables should not need be so specific. `.btn-primary.active.focus` Bootstrap is currently requiring this for simple focus states. The designer should not need to get so specific with their variables in classes for something as simple as a `:focus` state.

But after saying that, using the `.button-variat ()` mixin is a better choice.

Thanks for pointing this out.
