### ISSUE TITLE
v4 CSS switch from :before/:after to ::before/::after

### ISSUE THREAD

**Issue by toastal** [twbs/bootstrap#17052]
With the drop of IE8 support in v4, it would make sense to use the *proper* colon-age, `::before, ::after`, to promote best practices since pseudo elements are supposed to have double colons.

**Comment by mdo** [comment]
I'm inclined to stay with the single—everyone supports it still and we didn't do the single `:` just for IE8. Most folks don't write the double anyway.

**Comment by kkirsche** [comment]
@mdo I'm not sure I agree that it should use single. I'd ask what is the reason for straying from what the actual spec is. In my opinion, it makes more sense to follow the spec and use the correct format than to use a deprecated or legacy format just because it maintains support and some people (arguably) have bad habits on using double colons. This also means that should the project want to use all of the pseudo elements possible it would not be able to.

The key reason is (emphasis being mine):
<blockquote>
This :: notation is introduced by the current document in order to establish a discrimination between pseudo-classes and pseudo-elements.
For compatibility with existing style sheets, user agents must also accept the previous one-colon notation for pseudo-elements introduced in CSS levels 1 and 2 (namely, :first-line, :first-letter, :before and :after).
This compatibility <strong>is not allowed for the new pseudo-elements introduced in this specification</strong>.
</blockquote>

From: http://www.w3.org/TR/selectors/#pseudo-elements

**Comment by toastal** [comment]
I'd like to echo @kkirsche for more eloquently voicing my thoughts about the matter. We're unsure how long vendors will support single colon and we know that the spec has been defined to be double--and all major browsers support the spec's syntax now. If anything, a big project like TWBS would teach the 'lazy' folks that they *should* be using the double colon syntax. I know I personally learned quite a bit about CSS & JS because of this project. It's about setting a good example.

**Comment by mdo** [comment]
Ugh fine I guess we'll be responsible then :grin:.

**Comment by mdo** [comment]
Huzzah! #17058
