### ISSUE TITLE
Form won't work when submit button is enclosed by ".col-md-12"

### ISSUE THREAD

**Issue by kento-furui** [twbs/bootstrap#17098]
When I enclose a submit button with a col-md-12 div element, all form won't respond to click or input.

I put submit button like so 

```
<form>
  <!-- forms here -->
<div class="col-md-12">
   <button type="submit" class="btn btn-default">Send</button>
</div>
</form>
```
the submit button itself can be clicked but the rest of the forms accept no input or click.

**Comment by cvrebert** [comment]
Try running [Bootlint](https://github.com/twbs/bootlint) over your webpage.
Your example appears to suffer from the following error: https://github.com/twbs/bootlint/wiki/E014

For future reference, please note that bug reports must include a reduced test case as explained in https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports
Personal support requests that don't allege a bug in Bootstrap itself should be directed to one of the community help forums listed in https://github.com/twbs/bootstrap/blob/master/README.md#community , such as StackOverflow, instead of to this bug tracker.
Thanks!
