### ISSUE TITLE
Themes, and the cost involved

### ISSUE THREAD

**Issue by krisDOTco** [twbs/bootstrap#17143]
Hi there,

I apologise for going to an issues queue about it but there's not really anything else suitable. I don't want to try and condense this for Twitter because I believe the point will be lost.

I'm hoping to understand what it is that means the three new Themes are worth $99 in your eyes. Of course there's a premium assigned to the fact that THE Bootstrap guys developed them, but I'm hoping to gain an understanding of what's involved in skinning a Bootstrap package and outputting it for a hundred bucks when there are countless resources out there offering something of a similar level of quality and quantity for ~$30.

Of course I'm referring to the likes of ThemeForest, and you can generally take it or leave it with the flat Bootstrap themes they put out (some I've seen are absolutely dire) but there are also a lot of resources out there that don't even charge anything (see Codrops or Codyhouse, etc). I'm not saying at all that you shouldn't be charging anything at all for them (I agree you should and I applaud you for doing it) but is it advantageous for you to offer them at such an inflated price in comparison to a market you've propagated that is getting the best out of the framework as you are?

I don't want this to come off as picking a fight, I'm genuinely interested as I've been watching the progress of these new themes and am interested in picking one up. I'm just interested to know why these are worth two-three times the price of similar products elsewhere.

Thank you, and good luck with BS4.

**Comment by kkirsche** [comment]
@krisDOTco can't speak for the core team but this would be my logic:

1.) The themes all provide free updates and will continue to receive updates throughout the life of Bootstrap version 4. Compared to many themes I have purchased, this should be significantly longer than many other premium themes. Looking back, v3 was released 2 years ago (August 19, 2013) and v2 was released on Jan 31, 2012. I feel that the life of the theme in part warrants the cost.

2.) Realistically, I believe the audience who would be aware of themes.bootstrap.com is much lower than that of competing sites such as Themeforest or other premium theme sellers. That may be untrue, but a belief of mine.

3.) Many Bootstrap themes out there are non-semantic div hell. Not all, there are some amazing developers, but a lot that I have seen are very poorly written from a quality standpoint. Headers wrapped in <div> tags with a class of "header" instead of simply using h1/h2/h3/etc tags. That kind of thing. Often because they were simple ports of themes from other frameworks. Bootstrap isn't always the most semantic thing in the world... but some of the Bootstrap themes you can buy out there are sheer crap.

4.) Most importantly what the @twbs organization says on their about page:
<blockquote>
  We keep Bootstrap funded and available for everyone. To date, we have never taken money from investors and have no corporate sponsorships. All our expenses are paid for by us through ad revenue on our docs.
</blockquote> 

I think they deserve not pay for things out of pocket when they have to pay for things, and if it removes ads all the better.

**Comment by fat** [comment]
Hey krisDOTco,

Thanks for the question!

To pile on to @kkirsche's example, our themes aren't really themes in the traditional sense. Most themes (especially on themeforest) are just a simple reskinning, as you pointed out. Which isn't nearly as much work as is going into what we're selling…

In fact, our "themes" are actually really closer to "toolkits" (like bootstrap itself)… that's why several of our "themes" actually include multiple examples of different visual styles - for example marketing includes http://bootstrap-themes.github.io/marketing/ and http://bootstrap-themes.github.io/marketing/bold.

So, what do i mean by we're building toolkits? 

We haven't just tweeked some variables here… instead we set out to build over 20+ custom, responsive components suited for each particular problem (dashboards, marketing, etc) as well as several new, exclusive js plugins. That take times, hundreds of hours in fact.

And to be clear, it's not just "stuff" you're paying for.

You are buying themes from industry leaders, not just some kids in school… or someone who is thoughtlessly throwing some stuff together.

The themes are built by people who have spent years and years working on the web - leading frontend's for major companies like twitter, github, medium, etc. On top of that, we've been the same people behind some of the most successful front end frameworks in the last 5 years - bootstrap, ratchet, skeleton, etc.

So, you're paying for that expertise. And hopefully, you're paying for the trust that the work we produce is going to be of the highest caliber.

Not to mention you get free updates, support, bug fixes, etc. All things you aren't going to get other places.

Anyways, hope that helps - also, quick note - we'd prefer to keep all issues/questions out of bootstrap's core issues (we've got enough to deal with here with v4 on the horizon :) - so if you could please follow up with any other theme related questions on themes+issues@getbootstrap.com that would be much appreciated. 

Thanks again <3

**Comment by renanwatanabe** [comment]
teste
