### ISSUE TITLE
v4: Form validation polyfill

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#17142]
I was wondering if I could get some more information about the requirements would be for a form validation polyfill as mentioned in @mdo's pull request (#17021) under big picture ambitious nice to haves.

**Comment by mdo** [comment]
:shrug: No idea honestly. Folks have asked for it and I haven't had time to dive into it beyond that. Basically some ability to automate the classes being applied to things when a form control has a change to its state—be it disabled, active, checked, required, etc.

**Comment by cvrebert** [comment]
This can get fairly complicated (http://formvalidation.io/validators/ , http://formvalidation.io/api/), plus I bet many folks will want it to integrate with Angular/React/$JS_FRAMEWORK_OF_THE_DAY instead of raw jQuery, so personally I would lean towards deeming this out-of-scope, similar to datepicker widgets.

**Comment by fat** [comment]
im not crazy excited to add/support one –  looks like community already kinda taking care of it – http://1000hz.github.io/bootstrap-validator/

but if you've got a beautiful idea for one and want to knock out some code - i'm not totally against it either as long as you lean on the super simple side

**Comment by mdo** [comment]
Punting as a won't implement for v4.
