### ISSUE TITLE
Documentation: Add pixel values for the rem breakpoints and column sizes

### ISSUE THREAD

**Issue by researchplusdesign** [twbs/bootstrap#17145]
Suggestion... For the grid and media queries, it might be helpful to list the equivalent pixel values for people designing or saving out graphics. Looking through the documentation (http://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints), it wasn't clear what the rem media query values and container widths equate to in pixels.

**Comment by kkirsche** [comment]
Somewhat related to: #17070

**Comment by kkirsche** [comment]
Submitted PR to add those :smiley:

**Comment by chimericdream** [comment]
Because rem and em are related to the base font size, I think it could be worth adding a footnote (or some other unobtrusive indicator) that the pixel values are based on the standard `1em = 16px` formula. If someone changes the base font size either globally or for a particular breakpoint, the relative size of the em and rem units will be modified as well.

That said, I think this sort of touch is helpful because most people probably keep the default value for the base font size. (Of course, this is just an assumption since I don't have any real stats on the sorts of changes developers make to Bootstrap for their various sites.)

**Comment by cvrebert** [comment]
Fixed by #17146
