### ISSUE TITLE
Carousel docs example code snippet shouldn't reference Holder.js

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17217]
See http://v4-alpha.getbootstrap.com/components/carousel/#example
We need to tweak the displayed example code so it doesn't reference Holder.js (`data-src="holder.js/900x500/auto/#777:#555/text:First slide"`) so as to not confuse users. It's fine to use it in the displayed live example though.

**Comment by judgegrubb** [comment]
For reference, in the current bootstrap 3 docs the code uses "..." in place of the src http://getbootstrap.com/javascript/#carousel-examples. It would probably be advantageous to repeat that here if this change is desired.

And in order to have consistency, it should be noted that Card's docs would also need to be changed in a similar fashion. http://v4-alpha.getbootstrap.com/components/card/#example

There may be other places in the docs that would also need to be changed.

**Comment by cvrebert** [comment]
Fixed by #17467.
