### ISSUE TITLE
Firefox<=28 incompatibility since -moz-box-sizing:border-box isn't included

### ISSUE THREAD

**Issue by Ward305** [twbs/bootstrap#17237]
http://v4-alpha.getbootstrap.com/examples/grid/

**Comment by mdo** [comment]
If you're referring to the second to last example, that's intentional—we're clearing a float to bump columns to a new line.

**Comment by Ward305** [comment]
Then the grid doesn't make sense to me in version 4, a sum of 12 nested or
not, no longer renders inside the container neatly as it did. I have to use
a sum of 9 or 10 to get a horizontal alignment - but it had huge margins.
I've been using BS 3.x primarily for its grid.

**Comment by mdo** [comment]
Screenshot of the problem? I do see a difference in the column clearing example since v3, but a screenshot or two would help clarify what you're looking at.

**Comment by Ward305** [comment]
I'm happy to be wrong - you guys are the experts - SEE attached screenshots - all of the examples that span more than "8" wide do not render 10 or 12 wide horizontally. These are just two. All of the examples behave this way.
![untitled-2](https://cloud.githubusercontent.com/assets/13922668/9439468/55719100-4a35-11e5-8ef7-2c0dced0225a.png)
![untitled-1](https://cloud.githubusercontent.com/assets/13922668/9439471/5ba47cc2-4a35-11e5-947b-ee432410be44.png)

**Comment by MrGeneric** [comment]
Which OS and browser and browser version are you using?

**Comment by kkirsche** [comment]
Also @Ward305 what is your screen resolution?

**Comment by Ward305** [comment]
Win7 Ultimate N - Firefox 28
Resolution 1920x1080

**Comment by patrickhlauke** [comment]
Could you try upgrading to a more recent version of Firefox and see if that solves the issue?

**Comment by Ward305** [comment]
For test purposes - or as a 'fix'? - if 'fix' I'd rather stay with BS3.2 : )

**Comment by patrickhlauke** [comment]
As in "you're using a browser that about 1.5 years old to report a problem...let's see if the problem is with our code - though we can't reproduce at the moment - or with your browser..."

**Comment by Ward305** [comment]
Sure - happy to temporarily update to test it.

**Comment by Ward305** [comment]
Yes - rendering properly in Firefox 40.0.2 - > thought I got physically nauseous during that spyware update, so I'm deleting immediately for a rollback. Hope you can fix this!!! Love BS but love 28 more. Thanks.

**Comment by patrickhlauke** [comment]
This would suggest that the problem lies with Firefox 28. As we're not really going out of our way to ensure compatibility with very outdated versions of browsers, I'm afraid this is not going to get worked around at the Bootstrap end. /cc @mdo who may want to weigh in?

**Comment by Ward305** [comment]
Understood - would completely agree for seriously outdated browsers like IE 8 - 9. FF 1 - 18etc.  - but FF28 not a relic and there are millions of us in the "refuse to update FF28 club"

**Comment by MrGeneric** [comment]
Firefox 28 will probably meet your criteria for seriously outdated by the time V4 is actually released. It's still only in the alpha stages.

**Comment by Ward305** [comment]
Not sure what you mean - "close to your criteria for seriously outdated by the time V4" - Meaning will be fixed for FF28 - or by time V4 is released FF28 will be too outdated?

**Comment by cvrebert** [comment]
Our support policy for Firefox is that we only support the latest [Extended Support Release (ESR)](https://www.mozilla.org/en-US/firefox/organizations/faq/) version and the latest stable version, since Firefox is a modern evergreen self-updating browser. FF38 is currently the latest ESR. So FF28 is way too old for us to care about, some folks' Australis hatedom aside.

**Comment by nextgenthemes** [comment]
@Ward305 Could you give me some details or even better links why you not update? I am just very interested in those things. I do not know what you mean but are you sure you can not disable the spying with a setting or addon, I mean using such a old browser under windows is a security risk.

**Comment by cvrebert** [comment]
@nextgenthemes Presumably they dislike the [Australis UI theme](https://blog.mozilla.org/ux/2013/11/australis-is-landing-in-firefox-nightly/) which Mozilla switched to in Firefox 29.

**Comment by nextgenthemes** [comment]
@cvrebert he was speaking of spyware

> though I got physically nauseous during that spyware update, deleting immediately to feel better.

To me this not sounds like UI inconveniences, sounds more like Mozilla sending some data somewhere since 29+

**Comment by Ward305** [comment]
@nextgentheses @cvrebert is correct. Firefox29 and > is less customizable and bloated with Firefox spyware. Since Bootstrap 4.x is not supporting the "real" Firefox I'm now looking for a new framework that, as they say in politics, is more 'inclusive'. I really don't get it, all the BS developers need to do is fix the one element to make it work. Weird.

**Comment by nextgenthemes** [comment]
@Ward305 So its both you not like Australis and some "Firefox spyware". Again could you give me details and facts about this supposed "Firefox spyware" as I am very curious. I am more and more thinking there is no such thing.

**Comment by Ward305** [comment]
I don't think it matters to BS if is either is true... BS development has taken on the strategy of Steve Jobs. "I don't give them what they want, I give them what I think they want." Steve got away with it, a free framework can't.

**Comment by mdo** [comment]
This is a `box-sizing` problem. We're not including `-moz` in there, likely because of our Autoprefixer settings. I wonder if we should revisit that. I assume we're good to leave it given the low usage rates of v28, but could be worth diving into more.

**Comment by Ward305** [comment]
Don't want to be combative - I really like BS - My main point is, why would I want to move to 4.x that will not properly render a 1 year old browser (F28) - when 3.x will render IE 8 - > how old is IE8? 6+ years old. 

I get moving one from IE 8-9 support - but not 1+ year old browsers. Doesn't make good business sense to me.

**Comment by cvrebert** [comment]
Mozilla themselves no longer support Firefox 28; it doesn't get security patches or bug fixes.
Perhaps consider using [Classic Theme Restorer](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/) or switching to a different Gecko-based browser.

**Comment by Ward305** [comment]
Again, this is not about me - it's about my visitors. Moving to BS 4.x will exclude many users from viewing my website properly.

**Comment by mdo** [comment]
@Ward305 Echoing what @cvrebert just mentioned, those version numbers increment very quickly via auto updates. If you don't update to get the latest performance, stability, security, etc changes, you're putting yourself in that position. Firefox autoupdates just like Chrome now, so there's significantly less risk to supporting those older versions (which according to caniuse.com is at 0.4% I think).

**Comment by mdo** [comment]
@Ward305 Then don't move to v4. v3 will still be maintained for critical bug fixes and docs updates.

**Comment by nextgenthemes** [comment]
@Ward305 so you can not name any facts about your imaginative "Firefox spyware" Mozilla according to you supposedly build into Firefix with the 29 update, as I thought. Don't get me wrong I am glad if I hear up people not just taking everything without any thought. For example Stallman **rightfully** called Ubuntu out for having spyware build in and enabled by default. It sends all private **desktop searches** you make to Amazon (and maybe other Partys) and I am glad that are ppl who care about this things. https://fixubuntu.com/. Mozilla every since sends everything you search directly to google for search suggestions, I think enabled by default (Mozilla once had 40% of their funds came from google). But I am still not aware of anything like that that came with version 29.

So until you prove your claim about spyware in Firefox 29+ I think its totally ridiculous to sit on Windows 7 *cough* with a hopelessly outdated browser (about 1.5 years said patrick above) and then come up with the ridiculous critique of BS because you not like innovative change that totally makes sense (Australis). Go ahead search your other frameworks because this evil guys not support stone-age Browser because you refuse to adapt a new and better UI.

The thing about the IE support is just the usage rate, not about how old the browser is, sadly more people use old IEs then people use somewhat old FF.

On top off all that cvrebert just gave you the ultimate solution: https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/, not sure if you deserve it though.

**Comment by patrickhlauke** [comment]
so, i think this conversation has now run its course...

**Comment by Ward305** [comment]
Sadly it has run its course - going to learn another framework that me and my users can grow with - take care.

**Comment by patrickhlauke** [comment]
have fun

**Comment by mdo** [comment]
Alright, that was dick-ish all across the board @nextgenthemes and @patrickhlauke. Ease up on @Ward305. Regardless of the Firefox versioning and their policies, he's asking very valid and particular questions about our project. We have infinitely more context and knowledge than this person—acknowledge that and embrace it by being positive and helpful in all your comments.

**Comment by mdo** [comment]
@Ward305 To clarify, there's no immediate need to update to v4, for yourself or your users. v3 will be maintained moving forward so if you need those specific browsers supported, we've got you covered there.

In addition, I'd like to adjust our browser support to unofficially include the prefixes we need to fix that layout issue.

**Comment by kkirsche** [comment]
@mdo is there a timeframe for how long support for V3 will last? Curious what the <abbr title="End of Life">EOL</abbr>/<abbr title="End of Maintenance">EOM</abbr> is for V3? If that's off topic for here though I can make a new issue if needed

**Comment by mdo** [comment]
Not yet @kkirsche. We'll solidify that once v4 is final. Until then, v3 will most assuredly be maintained :).

**Comment by nextgenthemes** [comment]
> Again, this is not about me - it's about my visitors. Moving to BS 4.x will exclude many users from viewing my website properly.

If you really have so many v29 update refuser’s at visitors (I actually doubt that this "club" is that big) and are concerned about them having a wrong grid layout I would detect them and display a message to them about https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/ and encourage them to update, rather then switching the framework in this childish way. You would probably do them a favor because, as mentioned, v28 is not supported by Mozilla any-more and probably has a lot of holes for now very well known exploits, especially on windows, that is probably also on update refusal mode ;). Concerned about spyware but opening yourself up to all kinds of other stuff is pretty oxymoronic to me. Anyway I think I wasted my time here ...

@mdo And again I am the evil rude guy for my honest outspokenness. He has made up his mind anyway and now you give him what he wants, unofficial support and encourage others to use a insecure totally outdated browser ... OMG. Your be super-nice to every stubborn dude is annoying, honestly. It happened b4, nobody is supposed to be a tiny bit rude here. Just accept every stupid decision and even help them out ... no matter if it makes sense or not, just be nice, never question and let them dig their own graves ...

**Comment by mdo** [comment]
@nextgenthemes You can make your point without telling someone they're being childish, ridiculous, etc. And if you don't like me being nice to someone here because you were rude, that's a-okay with me. I don't need any validation for how I choose to interact with another person.

> He has made up his mind anyway and now you give him what he wants, unofficial support and encourage others to use a insecure totally outdated browser ... OMG.

You're mad I want to make sure millions of people have a minimally useable website when building on Bootstrap? The fix for the mentioned problem here is one line–`-moz-box-sizing: border-box`. Who cares that the browser is officially not supported? Basic layout stuff should be as in-tact as possible if we can help it easily enough.

> Your be super-nice to every stubborn dude is annoying, honestly.

If my being a good person to other human beings annoys you, well you've got your own shit to deal with. We're all people here trying to make stuff and I'll be damned if I let anyone's personal opinions on how to talk to people stop me from helping someone.

> Just accept every stupid decision and even help them out ... no matter if it makes sense or not, just be nice, never question and let them dig their own graves ...

You might want to step back through some of our issues and PRs here. I regularly shut down ideas I don't agree with, punt folks to other more appropriate mediums, etc. We say no the vast majority of the time.

---

There's a lot we can't do here in our limited time we have for open source. We can, however, be welcoming and encouraging in our responses to everyone—especially folks like @Ward305 who is **brand new to GitHub**. We shouldn't be setting folks up to dig their own graves, we should be boosting them up.

If it's your prerogative to degrade people, be overly negative, etc, that's fine. If you don't like it, just leave. I have zero patience for folks being jerks to others here, especially brand new users, and want none of it in this community.

**Comment by Ward305** [comment]
@mdo Thank you for the professional reply and explanation. Perhaps I should have framed my original inquiry as a concern for maximizing return visits to my website, rather than for "my browser". My initial thought was if 4 does not work in a relatively new browser, what other environments might it ALSO not work in. Now I get the feeling 4.x is being designed exclusively around Chrome and Chrome cloans ->FF29+. Which many users do not like to put it nicely. Only because they do not like the UI of course, not because Google or its cloans would ever tracks clicks, preposterous anyone would think that. 

Jokes aside.. If I might ask one last question - is it possible for me to add <b>"moz-box-sizing: border-box"</b> myself? I only attend parties I'm invited to, so if not possible, no worries. Thanks again!

**Comment by cvrebert** [comment]
> is it possible for me to add "moz-box-sizing: border-box" myself?

Yes, you could either tweak [the Autoprefixer settings](https://github.com/twbs/bootstrap/blob/4b33684cd65b0f3dd6f9973f226db572047672ff/grunt/configBridge.json#L13-L22) or manually add a `-moz`-prefixed copy of [the `box-sizing: border-box` reset](https://github.com/twbs/bootstrap/blob/4b33684cd65b0f3dd6f9973f226db572047672ff/scss/_reboot.scss#L20-L28). It won't interfere with or break anything.

**Comment by mdo** [comment]
@Ward305 Yup, what @cvrebert said :).

And FWIW, whatever your preferences on specific browsers, you'll want to research some current browser trends, your own site's analytics, etc to find out what kind of browser support you need <3.

**Comment by mdo** [comment]
Never got around to making any changes here. Once we hit beta we'll audit this a little closer as folks star to use v4 in more production environments.
