### ISSUE TITLE
Don't break backward compatibility in v4

### ISSUE THREAD

**Issue by iang0ld** [twbs/bootstrap#17240]
I didn't know where else to post this...

Please consider lessons from the success of jQuery, and how commercial companies grow loyal customers; about the Angular 2 mistake and the sudden growth of React due to uncertainty about Angular.  Let us all move forward with Bootstrap without throwing away all the good work the community has done.  

Please don't encourage us to look for alternatives.  Consider the benefits of backward compatibility - consistency, protection and respect for users time and effort.

Keep wells, panels, etc. in Bootstrap 4. Depreciate old selectors rather that remove them. We want to move forward with Bootstrap 4.  Don't break what already works.  Let just do better in the future.

From a dedicated user from the beginning.

**Comment by kkirsche** [comment]
@iang0ld Major version changes by definition in semantic versioning are for non-backwards compatible changes. That is one aspect of it which I do personally think is important.

I also think that after 2 years, Bootstrap needs to be able to upgrade and move to more current best practices as well as re-evaluate it's own current practices as it is doing in V4.

Honestly, I don't think this is an instance such as what occurred with Angular 1 -> 2 or Python 2 -> 3. Every prior instance has been a rewrite and we are working on migration documents for users. I also have interest in creating a migration script to automate it for people.

But I don't believe it's fair to Bootstrap as a project to force it to maintain compatibility because it would inconvenience developers who would need to update their sites or come to grips with the changes.

**Comment by iang0ld** [comment]
I agree to disagree.

In my world I cannot inconvenience customers or I do not eat, I lose money when I have to rewrite code, and  I use HTML, CSS, SQL, C#, PHP and JavaScript because they are backward-compatible, despite major version changes.  I envy you for not being in that position.

Nonetheless, Bootstrap 4 looks like a great product. Congratulations!

**Comment by patrickhlauke** [comment]
> In my world I cannot inconvenience customers or I do not eat, I lose money when I have to rewrite code

stick with v3, don't upgrade to v4. or am i missing something?

**Comment by kkirsche** [comment]
Probably important to reiterate the V4 doesn't mean V3 goes away. We'll support it for awhile but it won't stop working and is in my opinion pretty stable overall. I'd just say develop new apps as they come up in V4 and leave existing ones on V3. It won't hurt to not be on the latest and greatest.

**Comment by iang0ld** [comment]
Yes I think you are.

**Comment by iang0ld** [comment]
Thank you.  I totally agree.  I appreciate having the opportunity to provide input and food for thought.  Only trying to help and raise alternate thoughts.

Keep well.

**Comment by abitdodgy** [comment]
Stick with V3 if you can't upgrade. Semantic versioning inevitably introduce non-backward compatible changes in major releases. This is the nature of software and it's not fair to hold back its evolution because it introduces a financial burden on some users. Bootstrap 4 is a fantastic evolution, and an optional one. Bootstrap 3 is not going away. When you can provision the resources to upgrade, go ahead and do so.

**Comment by hnrch02** [comment]
We got rid of some of the annoying and obsolete parts, merged some of the redundant stuff and introduced a few new and exciting things but that's basically housekeeping not "throwing away all the good work the community has done" like you put it - no complete change of course that would make migrating from v3 to v4 next to impossible.

And I think it is absolutely vital for the continued existence of Bootstrap to do that - things need to be changed up every now and then or else the maintainers will start loosing interest in it eventually and move on to more interesting projects. Unlike jQuery UI (or Angular or React, for that matter) there's no organization behind Bootstrap that ensures the continued maintenance of the project, we rely on the interest of the maintainers (and not Twitter like some people still seem to think). 

And besides, the examples you mentioned - wells and panels - can be easily replicated with cards. Have you looked at our [migration guide](http://v4-alpha.getbootstrap.com/migration/) yet?

**Comment by cvrebert** [comment]
Backward compatibility is not free. It incurs a maintenance burden on our small and already overstretched Core Team. It adds bloat, which I guarantee people would gripe about. It makes it impossible for us to fix certain annoying bugs. The whole point of bumping the major version number under SemVer is to allow us to make improvements that require breaking strict backward compatibility.
(Also, at this point, we've already gone too far down this path to be able to make such a drastic course change...)

The only specific features you mentioned ("wells, panels") are among the very easiest for users to migrate away from (to the new Cards widget), so especially in those particular cases, the benefit to adding them back would be relatively low. Thus, I don't think it's worth it to add them back. However, given the relative simplicity of those widgets, it should be pretty easy for yourself or other interested members of the Bootstrap community to create a small v4-compatible add-on library to ease your upgrading process if you find it necessary.

**Comment by mdo** [comment]
Yeah, no change here on our major version strategy. We've done it this way for four years and have already committed to breaking (nearly) all the things for our own sanity :).
