### ISSUE TITLE
v4 - progress bar: not able to show custom text over bar

### ISSUE THREAD

**Issue by valorkin** [twbs/bootstrap#17264]
Good day, in bs3 was an option to show custom text(elements) over progress element (using div.progress), see image.
But when using `<progress>` element, I will be not able to reproduce this behaviour (same in bs3).
<img width="944" alt="screen shot 2015-08-24 at 11 37 58" src="https://cloud.githubusercontent.com/assets/1107171/9436072/82f57586-4a55-11e5-9512-446e2f596237.png">

**Comment by cvrebert** [comment]
I don't think putting the caption on top of the progress bar is a feasible pattern.
* It's not clear how to make it work when the browser natively supports the `<progress>` element, which also introduces inconsistencies between `<div>`-based progress bars and `<progress>`-based progress bars.
* It tends to break in hard-to-fix ways at low percentage values. There tends to be insufficient room for the text, and the white-on-gray portion that overflows doesn't have enough contrast to be legible.

These problems are easily avoided by putting the progress bar's caption below it or above it instead of inside it. I do think it would be good for some of the examples in the docs to demonstrate this captioning method.

**Comment by valorkin** [comment]
@cvrebert thanks for clarification, good point indeed
what about stacked progress bars, for complicated flows, like displaying
image upload, compression, resize, uploading in one progress bar (Stacked sample on image)
I suppose it doesn't feat new concept too?

**Comment by cvrebert** [comment]
X-Ref: #12848 
I did come across https://css-tricks.com/reverse-text-color-mix-blend-mode/ , which is cool but unusable due to [lack of IE/Edge support](http://caniuse.com/#feat=css-mixblendmode)

**Comment by mdo** [comment]
Punting on making this a thing—it's not great for the reasons @cvrebert mentioned.

**Comment by valorkin** [comment]
@mdo so there are a chance to make this happen(working)?

**Comment by cvrebert** [comment]
@valorkin We have no plans to investigate this further ourselves.
Probably we'll add captions above the example progress bars instead.

**Comment by valorkin** [comment]
@cvrebert oh, ok. than I did not understood correctly comment by @mdo
