### ISSUE TITLE
Why don't .col-push-* and .col-pull-* use the flexbox `order` CSS property?

### ISSUE THREAD

**Issue by mmjaeger** [twbs/bootstrap#17313]
Hello
I was wondering why when using flex box you don't use "[order](https://developer.mozilla.org/en-US/docs/Web/CSS/order)" to re-arrange the columns?

Thanks

**Comment by cvrebert** [comment]
I'm not sure pull/push can be expressed in terms of `order`, since `order` seems to be absolute ("this is the Xth item") whereas push/pull are relative ("move this item over X columns from its normal position").

**Comment by mmjaeger** [comment]
I have the following structure .content, .sidebar-primary, .sidebar-secondary and like to have three layouts: .content-sidebar-sidebar, .sidebar-sidebar-content, and .sidebar-content-sidebar - in this scenario, using order is ideal I think

**Comment by MichaelRushton** [comment]
How about adding `.col-{size}-position-{n}` to complement the offsets, pushes, and pulls?

**Comment by wesruv** [comment]
Agree with @cvrebert, this is fundamentally different.

I made something along the lines of @MichaelRushton is proposing, but I did:
`.order-{breakpoint}-{n}`

I wrote up some docs and described it as 'weighting' the columns, heavier weights appear last.

I ended up abandoning this approach because for the project I'm on we're preferring to stay closer to Bootstrap for the 'people know it' reason. I was also prefacing all my layout classes with `l-`. You can find my stab at it here:
https://github.com/backdrop-contrib/basis/blob/master/css/grid-system/flexbox-grid.css#L1587-L1802

If I redid it I'd probably do -4 through 4, instead of 1-5.

**Comment by wesruv** [comment]
It feels a lot better than push or pull, but if you fallback to floats on older browsers the layout order will go back to source order.

**Comment by mdo** [comment]
Sticking with the current solution for now given the feedback on `order`.

**Comment by AdsonCicilioti** [comment]
Could you update the documentation page?

**Comment by mdo** [comment]
Hosted docs site get updated with each release, not every push.

**Comment by AdsonCicilioti** [comment]
The order-[num] classes d'nt work for me.
