### ISSUE TITLE
a.navbar-btn in navbar (enhancement/suggestion)

### ISSUE THREAD

**Issue by My1** [twbs/bootstrap#17437]
for starters, I am more than aware that is isnt really supported (yet) to use an a element as a .btn in the navbar. but I think this really should be added especially if you cannot/dont want to rely on javascript all the time (for example for accessibility reasons or people not that well versed in js or whatever)

right now it works pretty solid having a p.navbar-btn and inside the a.btn
and button groups (even with dropdown) seem to work as well if you have the a with both btn and navbar-btn in that case.

but it would be nice to have a less roundabout way for it, and why go to a new page with a script if you can just do a link?

**Comment by cvrebert** [comment]
@My1 You are referring to Bootstrap v3.x.x, correct?

**Comment by My1** [comment]
what other bootstrap should I mean?  2 is outdated as hell (3.0.0 was released in mid-2013 so over 2 years ago and is is way out of the question.
also the recent docs state the non-supported state of it (even though it does work with some tricks, but that doesnt make it supported, obviously)

**Comment by cvrebert** [comment]
[Bootstrap v4 (alpha)](blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/)

**Comment by cvrebert** [comment]
Bootstrap v4 completely overhauls the navbar and aims to remedy the many problems with the v3 navbar, such as the one you mentioned. You can check out the current draft on http://v4-alpha.getbootstrap.com/components/navbar/ (we acknowledge that it still needs some work; that's why it's in alpha).

We're no longer making significant changes to Bootstrap v3 at this point, in order to focus on v4, so I'm closing this issue as WontFix since it targets v3, isn't a bugfix per se, and would be a nontrivial change.

**Comment by My1** [comment]
will there be again a non-flat theme? I cant stand this flat stuff...

**Comment by cvrebert** [comment]
There are global variables to enable/disable traits typically associated with either flatness or skeuomorphism (including gradients): http://v4-alpha.getbootstrap.com/getting-started/options/

**Comment by My1** [comment]
okay this is epic. while we're at it, is there an scss compiler for windows?

**Comment by cvrebert** [comment]
You poor soul. Yes, there are. But now we're veering off topic; ask that sort of question on StackOverflow, IRC, or Slack: https://github.com/twbs/bootstrap/blob/master/README.md#community
