### ISSUE TITLE
v4 - Flexbox builds only using "display: flex"

### ISSUE THREAD

**Issue by SuperiorJT** [twbs/bootstrap#17480]
Currently generating a bootstrap-flex build only supports browsers that use the new syntax for flexbox. Currently using Safari 8 and bootstrap-flex will not work since `-webkit-box` is not included. Use the below codepen to test with Safari.

<p data-height="397" data-theme-id="0" data-slug-hash="EjqbPj" data-default-tab="result" data-user="ncerminara" class='codepen'>See the Pen <a href='http://codepen.io/ncerminara/pen/EjqbPj/'>Bootstrap 4 Flex Box Grid Demo</a> by Nicholas Cerminara (<a href='http://codepen.io/ncerminara'>@ncerminara</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by cvrebert** [comment]
@SuperiorJT That pen is working fine for me:
<img width="1267" alt="demo" src="https://cloud.githubusercontent.com/assets/419884/9697776/44cff7aa-5350-11e5-9283-fa78c8d2ea63.png">

Did you forget to click the button or something?
[caniuse](http://caniuse.com/#feat=flexbox) and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes#Browser_compatibility) say that OS X Safari supports the new syntax since v6.1 (albeit still `-webkit` prefixed).

**Comment by mdo** [comment]
Yeah, our build tools add the necessary prefixes, too btw.

**Comment by LukeSheard** [comment]
<img width="1920" alt="screen shot 2015-09-04 at 11 44 06 pm" src="https://cloud.githubusercontent.com/assets/9877376/9698161/d9b23212-535e-11e5-8170-1b815a95849a.png">

Forgot to include an about safari. But this is 9.0.

**Comment by cvrebert** [comment]
@LukeSheard After clicking the "Flex Box BS4 Grid" button?

**Comment by LukeSheard** [comment]
@cvrebert Apparently it didn't register the click the first time I tried. Can confirm it works. Weird, sorry guys.
