### ISSUE TITLE
Add off-canvas navigation sidebar component

### ISSUE THREAD

**Issue by shanksdev** [twbs/bootstrap#17502]

**Comment by cvrebert** [comment]
@shanksdev Do you mean something similar to a vertical nav menu ( http://v4-alpha.getbootstrap.com/components/navs/#stacked-pills ), or similar to an off-canvas menu (like http://getbootstrap.com/examples/offcanvas/ with its "Toggle nav" button when the screen is narrow)?

**Comment by shanksdev** [comment]
The off-canvas menu with toggle nav was something i was looking for. I came across this need when i was first time getting my hands on bootstrap i came up with the sidebar using the nav stacked-pills, something like this
![sidebar](https://cloud.githubusercontent.com/assets/13146262/9721624/e11521a4-55bb-11e5-887f-1b64a644fb87.jpg)
Sorry, I didn't knew about offcanvas.css and offcanvas.js that time. But after reviewing the code of both js and css files it seems easy to implement. :)
Still, if you think that its worth adding that much code of both files in your bootstrap's js and css then please do, we can save 1 or 2 http requests. :)

**Comment by mattez** [comment]
YES. **Off Canvas Menu** is more and more often used UI component these days. It would be nice if it become an official Bootstrap 4 component with standardized implementation process.
I'm not sure how sophisticated and bullet-proof this [v3 (old) Off Canvas example](http://v4-alpha.getbootstrap.com/examples/offcanvas/) is. Some of Bootstrap GURUs should revised that solution and update it. Because this [v4 Off Canvas example](http://v4-alpha.getbootstrap.com/examples/offcanvas/) is only copy of that v3 (old) solution.

**Comment by laminsk** [comment]
Will be great to see this in next v4 alpha. cheers.

**Comment by michaelwoodruff** [comment]
+1

**Comment by av3** [comment]
+1

Those drawers are also used in Material Design, therefore I would like to use drawsers for the main navigation of my mobile optimized websites (like used in materializecss.com, but with a horizontal navbar on non-mobile devices)

**Comment by tlaverdure** [comment]
+1

This seems to be a popular feature. I've used a bootstrap plugin (http://www.jasny.net/bootstrap/examples/navmenu/) for this sort of thing before but it would be great to have official support for something like this.

**Comment by cvrebert** [comment]
X-Ref: #15796

**Comment by adiramardiani** [comment]
I think in [Collapsible content](http://v4-alpha.getbootstrap.com/components/navbar/#collapsible-content) is the best method to create off-canvas, drawer, or whatever name to references this.

If this feature is add example not only on the top, maybe in right, left or bottom. If added a **OVERLAY** option, this will be great :)

Actually/currently method to handle `off-canvas` in other framework
And overlay method to handle ui like `material-design` menu implement now

**Comment by RyanZim** [comment]
Here is a proof-of-concept of @adiramardiani's method: https://jsfiddle.net/2q4ppqm5/2/. I was able to use all existing BS classes except I added added an `.overlay` class that sets:
```
.overlay {
  height: 100vh;
  position: fixed;
  background-color: #FFF;
  border-right: solid 1px ;
}
```
A few problems with my example:
- Navigation should come in from the right instead of the top.
- It isn't possible to make the drawer visible as a sidebar. (This probably could be done, but I didn't take the time to figure out how.)

Note that this example has two buttons, one on the page, and one in the drawer (for closing).

I think this might be a good idea, it will just take a little work. Also, `.navbar-toggleable-*` & `.navbar-toggle` would need to be renamed if we implement drawers with this method.

**Comment by twbs-lmvtfy** [comment]
Hi @RyanZim!

You appear to have posted a live example (https://fiddle.jshell.net/2q4ppqm5/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 10181, column 5: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by RyanZim** [comment]
Updated: https://jsfiddle.net/2q4ppqm5/3/

- Added `.col-xs-12` to main content to fix lmvtfy errors
- Moved `<nav>` outside `.row`
- Added `z-index: 1` to `.overlay`

**Comment by twbs-lmvtfy** [comment]
Hi @RyanZim!

You appear to have posted a live example (https://fiddle.jshell.net/2q4ppqm5/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 10164, column 3: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Punting on adding this in v4 for the initial launch. Let's tackle it with a follow-up release.

**Comment by mojimi** [comment]
Is this possible as of now? The off canvas example on the website doesn't seem to be working as a side drawer

**Comment by jktravis** [comment]
The offcanvas example is confusing since it seems to be broken.
