### ISSUE TITLE
Support for half-column offsets

### ISSUE THREAD

**Issue by jookes** [twbs/bootstrap#17524]
For Bootstrap 4 it would be nice to have half column offset/push support so that we can center a col-md-5 :)

**Comment by cvrebert** [comment]
That seems kinda contrary to the purpose of a grid system.
Alternatively, you could use the mixins to generate a grid with the right number of columns such that the arithmetic works out in your case.
There have also been requests in the past for an easier way to center a column within a grid row. IMHO that seems like a more palatable route, if this issue is deemed to be worth addressing.

**Comment by mdo** [comment]
I'm going to say we punt on this for simplicity's sake (even though our grid system is already rather complex).

**Comment by tomlutzenberger** [comment]
@jookes If you double the columns from 12 to 24, you're more flexible and have the same effect.

**Comment by robertpataki** [comment]
@tomlutzenberger man, this is such a simple yet super powerful solution, this is exactly what I needed! Thanks :)
