### ISSUE TITLE
Indicators are not changing on Carousel control

### ISSUE THREAD

**Issue by rusalka805** [twbs/bootstrap#17557]
I've downloaded latest customized version of Bootstrap. I only got Glyphicons, Carousel and Component animations (for JS). Also I've included JQuery plugins for Carousel functionality and Transitions. Carousel works as expected and but indicators don't change active state. I've researched around and tried to include js code fixed but nothing helped so far. Do i need to get any other components when getting Custom version for this to work?

Thank you in advance.

**Comment by cvrebert** [comment]
Please show us either your `config.json` or your unique customizer URL (http://getbootstrap.com/customize/?id=XXXXXXXX)

**Comment by rusalka805** [comment]
Hello here is the unique customized URL http://getbootstrap.com/customize/?id=7e000ab23e89295d1cf6

**Comment by rusalka805** [comment]
Hello, any progress on this? Do you need anything else that i can provide to get this resolved?

**Comment by cvrebert** [comment]
Unable to reproduce in Chrome.
Testcase: http://jsfiddle.net/cvrebert/vg46jh00/1/

**Comment by cvrebert** [comment]
Additionally:

Since we are now focusing on Bootstrap v4, the Bootstrap Core Team is no longer investigating non-critical issues in the Bootstrap v3 Customizer.
However, patches to fix such issues would be welcomed and we would gladly merge such patches; we just won't be writing any ourselves due to time/manpower constraints.
Thank you for your understanding.
