### ISSUE TITLE
Why I need to write col-xs-12 if I want full column width on mobile with Flexbox grid?

### ISSUE THREAD

**Issue by smajl** [twbs/bootstrap#17603]
In v3, every column class (if not specified otherwise with `col-xs-?` class) was breaking to full width on mobile. In v4 Flexbox version I need to write `col-xs-12` manually everywhere to achieve the same thing. Is this by design or bug?

**Comment by matt-hernandez** [comment]
It isn't so much with mobile, so much as whenever the screen falls beneath any breakpoint in v3, if there isn't a `.col-*` class to handle sizing at that point, the columns break to full width. This is because the styling for the width and float disappear at that breakpoint, and the `<div>` elements snap to their default browser width, which is 100%.

With flex, `<div>` elements don't break to 100%, and instead behave more like `inline-block`.

Would it be possible to have `flex-basis:100%` in the `.col-*` classes? This could be easier to do if #17228 is implemented.

If not, then @smajl you may have to put `col-xs-12` everywhere.

**Comment by smajl** [comment]
@matt-hernandez Yeah, I know, with "mobile" I was referring to resolutions <34em rather then to physical device. :) This was not so clear.

Thanks for the explanations of the problem. The "parent" `.col` class could be the easiest way of solving this problem in flex grid system. Till then, I'll use my own helper class until the #17228 is decided:

```scss
@if $enable-flex {
  @include media-breakpoint-down(xs) {
    .col {
      flex-basis: 100%;
    }
  }
}
```

**Comment by tnoetzel** [comment]
+1 to adding `flex-basis: 100%` on the `.col-*` classes.

Modified the snippet from @smajl so it doesn't depend on the .col class:

```
@if $enable-flex {
  @include media-breakpoint-down(xs) {
    [class*="col-"] {
      flex-basis: 100%;
    }
  }
}
```

**Comment by mdo** [comment]
Resolved with #17603, which adds auto layout to flexbox grid cols.

**Comment by mdo** [comment]
Actually, this wasn't "resolved", but the grid behavior has changed and you need the default `.col-xs-12` on `xs` viewports. See #19099 for more details.

**Comment by e-oz** [comment]
> and you need the default .col-xs-12 on xs viewports.

@mdo please add details what to write and where to get columns expanded to full width by default. I couldn't find instructions in #19099

**Comment by e-oz** [comment]
My question is to grid without flexbox.
