### ISSUE TITLE
ie 8 - respond.min.js

### ISSUE THREAD

**Issue by kmaier** [twbs/bootstrap#17605]
i am having some issues with ie 8 not rendering the media queries correctly. 

I have this referenced:
src="/App_Themes/bootstrap/js/html5shiv.min.js"
src="/App_Themes/bootstrap/js/respond.min.js"

But anytime I check in ie 8 it takes the last query.
http://support.enerconind.com/

Any idea what I am missing?

**Comment by wolfy1339** [comment]
What version of Bootstrap?
And can you reproduce a [JSBin](http://jsbin.com/lefey/1/edit?html,output] of the issue, using only Bootstrap?

**Comment by kmaier** [comment]
3.3.5
it seems to be working fine otherwise, except for ie 8 
http://jsbin.com/xedale/1

**Comment by cvrebert** [comment]
Please ask personal support questions like this on StackOverflow. Thanks!

**Comment by kmaier** [comment]
Made a direct reference to the files and with the exact same html. support.enerconind.com/offcanvas.html vs. getbootstrap.com/examples/offcanvas how is it possible i am still seeing different results between the two files in IE8??

**Comment by cvrebert** [comment]
Protip: Read the docs: http://getbootstrap.com/getting-started/#respond-js-x-domain

**Comment by cvrebert** [comment]
Well, that's why http://support.enerconind.com/offcanvas.html is broken anyway. Looks like http://support.enerconind.com/Home.aspx isn't using cross-domain CSS, so the problem there is different.
Again, [this is a bug tracker](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker), not a support forum. Please ask your question on StackOverflow, IRC, or Slack instead: https://github.com/twbs/bootstrap/blob/master/README.md#community
Good luck!
