### ISSUE TITLE
Collapse.js v4 only toggles one target?

### ISSUE THREAD

**Issue by thecristen** [twbs/bootstrap#17643]
http://www.bootply.com/1lBIRBwnA0 
This example, using Bootstrap v3, properly shows the two hidden rows when clicking the first plus button.

The same markup using the v4 source only toggles the _first_ row.

**Comment by twbs-lmvtfy** [comment]
Hi @thecristen!

You appear to have posted a live example (http://s.bootply.com/render/1lBIRBwnA0), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 56, column 11 thru column 175: The ```` aria-controls ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@fat Is this intentional?

**Comment by codeConcussion** [comment]
I also ran into this problem. Here's another short example...  
[Working in v3](https://jsfiddle.net/Ljwzapjn/)
[Broken in v4](https://jsfiddle.net/6j6odwzp/)

**Comment by codeConcussion** [comment]
Has anyone found any workarounds for this issue?

**Comment by maxbeatty** [comment]
[v3 was selecting all targets](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L163) where as [v4 is selecting only the first target](https://github.com/twbs/bootstrap/blob/0416f761dddae04a1b4d3ce70afece518330ca4d/js/src/collapse.js#L312) which explains the difference in behavior. 

As I started to refactor v4 to act like v3, the decision to only select the first target seems intentional. In v3, [the `data` used to determine whether to toggle or instantiate](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L206) is based off only the first element (`$target.data('bs.collapse')` is really doing `$target.first().data('bs.collapse')`). The state of your first target is going to be used for _every_ target which could introduce problems. With the v4 implementation, that isn't left to chance.

> Has anyone found any workarounds for this issue?

You could use the `hide.bs.collapse` event and some mix of show/hide calls to recreate the behavior in v4.

**Comment by codeConcussion** [comment]
> The state of your first target is going to be used for every target

@maxbeatty - Maybe I'm misunderstanding what you're saying, but it seems like [this v3 example](https://jsfiddle.net/Ljwzapjn/4/) contradicts what you're saying. There are two divs and their toggle states are opposite one another. Any button click shows the hidden div and hides the visible div.

I can achieve the same thing in v4 but I have to use javascript. It's just really nice to accomplish this without scripting.

**Comment by maxbeatty** [comment]
_I don't have a dog in this fight. I could have misunderstood the code and intentions. I was mainly trying to help with v4 issues_ 🚂 

> There are two divs and their toggle states are opposite one another.

Before any clicks, those two divs are plain HTML divs with CSS classes dictating their appearance. 

2. On that first click, [the first div is asked for data about 'bs.collapse'](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L206). There isn't any because it's new (hasn't been used by collapse yet) so the plugin is called with the click event target's data and _each_ `data-target` uses those options. 
3. Each div has no existing data for 'bs.collapse' so [each is instantiated](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L177). 
4. The [default is to toggle](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L38) so [at the end of each instantiation, toggle is called](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L30)
5. [toggle calls `hide` or `show` based on the element having the `in` class](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/js/collapse.js#L136) which is why your "Delete" button hides and your "Yes/No" buttons show.

If in v3 your second div is already instantiated for some reason or another, it behaves the same as v4 https://jsfiddle.net/bnz8sa2L/1/

My outsider opinion is that it's better to declare the behavior as you need to in v4 than to depend on assumptions about how it'll behave like in v3

**Comment by michaelzangl** [comment]
I ran into the same issue. I'd like to toggle all targets and not the first one. This is the whole point in using CSS selectors... This is how I hacked a fix for it:
```
--- a/public/js/bootstrap.js
+++ b/public/js/bootstrap.js
@@ -1284,7 +1284,10 @@ var Collapse = (function ($) {
         var selector = '[data-toggle="collapse"][data-parent="' + this._config.parent + '"]';
 
         $(parent).find(selector).each(function (i, element) {
-          _this6._addAriaAndCollapsedClass(Collapse._getTargetFromElement(element), [element]);
+          var element = element;
+          Collapse._getTargetsFromElement(element).each(function() {
+            _this6._addAriaAndCollapsedClass(this, [element]);
+          });
         });
 
         return parent;
@@ -1305,10 +1308,10 @@ var Collapse = (function ($) {
       // static
 
     }], [{
-      key: '_getTargetFromElement',
-      value: function _getTargetFromElement(element) {
+      key: '_getTargetsFromElement',
+      value: function _getTargetsFromElement(element) {
         var selector = Util.getSelectorFromElement(element);
-        return selector ? $(selector)[0] : null;
+        return $(selector ? selector : []);
       }
     }, {
       key: '_jQueryInterface',
@@ -1353,11 +1356,14 @@ var Collapse = (function ($) {
   $(document).on(Event.CLICK_DATA_API, Selector.DATA_TOGGLE, function (event) {
     event.preventDefault();
 
-    var target = Collapse._getTargetFromElement(this);
-    var data = $(target).data(DATA_KEY);
-    var config = data ? 'toggle' : $(this).data();
-
-    Collapse._jQueryInterface.call($(target), config);
+    var $this = $(this);
+    var targets = Collapse._getTargetsFromElement(this);
+    targets.each(function() {
+           var data = $(this).data(DATA_KEY);
+           var config = data ? 'toggle' : $this.data();
+       
+           Collapse._jQueryInterface.call($(this), config);
+    })
   });
 
   /**
```

The patch is against the final bootstrap.js file.

**Comment by mdo** [comment]
I'd definitely welcome a PR to address this in our next alpha. Having multiple targets trigger the same collapse element would be awesome.

**Comment by vanduynslagerp** [comment]
X-ref #21692
