### ISSUE TITLE
Document removal of vendor prefix mixins in v4 migration guide

### ISSUE THREAD

**Issue by webtuts4u** [twbs/bootstrap#17645]
I am shifting from less to scss and going to work with bootstrap v4. But the vendor prefixes mixins are missing in scss master. Then how can i use when require ? 

I am new in sass.

**Comment by cvrebert** [comment]
We're using [Autoprefixer](https://github.com/postcss/autoprefixer), which makes vendor prefix mixins unnecessary. That's why [they were deprecated as of v3.2.0.](https://github.com/twbs/bootstrap/blob/v3.3.5/less/mixins/vendor-prefixes.less#L3-L4)

We ought to add an explanation to the v4 migration docs.

**Comment by mdo** [comment]
There's an explanation in the docs about these no longer being in our Sass files for v4.
