### ISSUE TITLE
That closure vs bind

### ISSUE THREAD

**Issue by pinoniq** [twbs/bootstrap#17673]
Is there a specific reason why the JS code of bootstrap is riddled with closures?
```
var that = this;
```

For instance the modal:

```
  var that = this;
  this.backdrop(function () {
      var transition = $.support.transition && that.$element.hasClass('fade')

      if (!that.$element.parent().length) {
        that.$element.appendTo(that.$body) // don't move modals dom position
      }

      ...
  }

...

  Modal.prototype.backdrop = function (callback) {
    ...
        callback()
  }
```

We are passing a callback to a method of the same object. We could remove the var that = this; and call the callable using:

```
callback.apply(this);
```

Maybe this could/should all be cleaned up.

**Comment by cvrebert** [comment]
In Bootstrap v4, there's no more `that`. It's all `$.proxy(...)` instead.
Although since v4 uses ES6, I don't know why it doesn't just use [arrow functions](https://babeljs.io/docs/learn-es2015/#arrows-and-lexical-this) instead...
You'd have to ask @fat as to the "why?" of it all.

In any case, my guess is that we wouldn't want to tweak any of this in v3, for the sake of avoiding churn since it's in maintenance mode.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
