### ISSUE TITLE
CamelCase support for text-transform of Upper case words

### ISSUE THREAD

**Issue by sanspace** [twbs/bootstrap#17672]
It'd be great if CSS supported this natively. However, It's a very common use case.
    `<p class="text-capitalize">Capitalized text</p>`
    `<p class="text-capitalize">UPPERCASE TEXT</p>`
yields

    `Capitalized text`
    `UPPERCASE TEXT`

The feature I request is,

    `Capitalized text`
    `Uppercase Text`

I tried applying `class= 'text-lowercase text-capitalize'` thinking that it  would apply lowercase first and then capitalize. But, it didn't work that way.

I'm just looking for a feature that makes it easy to convert uppercase characters.

**Comment by cvrebert** [comment]
Like you said, CSS simply currently doesn't provide such a feature, so there's not much we can do here.
I doubt there'd be interest in adding JavaScript for this into core Bootstrap. It wouldn't really fit in well with the other JS plugins, which are all about fairly meaty widgets, rather than something tiny like this.
Short of finding/writing a JS micro-library for this yourself, you might consider proposing the addition of a new `text-transform` value that does what you're suggesting on [the Web Incubator Community Group forum](http://discourse.wicg.io/).
Good luck!

**Comment by cvrebert** [comment]
Rejection confirmed by @mdo in https://github.com/mdo/ama/issues/187#issuecomment-144111633
