### ISSUE TITLE
Cards in columns ordering

### ISSUE THREAD

**Issue by Ayaweb** [twbs/bootstrap#17709]
Hi, 
I have got an issuer with ordering cards in columns in Bootstrap 4 - is it possible to order cards line by line, so they are like:
card1 card2 card3
card4 card5 card 6
card7
etc.? 
Here is the blog page I wanna organize www.sdetkami.spb.ru

**Comment by cvrebert** [comment]
Yes, you just utilize the grid system. See e.g. http://v4-alpha.getbootstrap.com/components/card/#sizing , http://v4-alpha.getbootstrap.com/layout/grid/#example-column-wrapping
Please use StackOverflow instead of this bug tracker for future how-to questions. Thanks!

**Comment by taylordowns2000** [comment]
Hi @cvrebert ,

It's possible that @Ayaweb was actually looking for [card-columns](http://v4-alpha.getbootstrap.com/components/card/#columns) ordering to go across rows, rather than top to bottom in columns—hence the name, I suppose. Either way, I know that I am!

The masonry effect is wonderful, but I run a marketplace with 117 cards, ordered (in Angular) by number of 'upvotes'. My `ng-repeat` inside the `card-columns` div and it looks like:

|1st | 39th | 72nd 
|---|---|---
|2nd | 40th | 73rd
|3rd | 41st | 74th |
|4th|42nd|75th

And so on. Is it possible to use `card-columns` but order in rows? (Maybe call it `bootstrap-rows`?)

Thanks in advance for your time,
Taylor

**Comment by cvrebert** [comment]
@taylordowns2000 Please open a new issue and we'll take a look.

**Comment by Ayaweb** [comment]
this is absolutely what I meant, why do you open another issue? Please post the link here if so

**Comment by cvrebert** [comment]
See #17882.
