### ISSUE TITLE
v4: Replacement of affix with position:sticky does not address all use cases

### ISSUE THREAD

**Issue by acch** [twbs/bootstrap#17819]
I understand that with v4 the affix js component is to be dropped. Instead, `position:sticky` (with or without polyfill) is supposed to take its place. I agree that for most scenarios `position:sticky` is a valid replacement - however, there are scenarios which can not be addressed with it.

I use affix js on a few sites / apps in the following way: I have a fixed navbar on top, and use affix to apply a certain style / class upon scrolling. Initially (when window is scrolled to top), the navbar integrates seamlessly into the page (i.e. no shadow, no accentuation...) When scrolling the window, I apply a custom style / class to make the navbar stand out (i.e. drop shadow, etc.). This greatly improves the effect of the navbar 'hovering' above the page...

This is something which can not be addressed with `position:sticky`, and AFAIK no other bootstrap component provides this functionality (happy for being corrected on that one). Thus, removal of affix would break these kind of scenarios.

Please let me know how I can help...
All the best!

Achim

**Comment by danimalweb** [comment]
I have message bar above my BS Navbar and use affix to lock the position of the navbar once the message bar has been scrolled past. Example: http://www.avantagesemark.com/

I've checked out the docs for postion: sticky as I don't see how I can achieve the same. +1 for keeping Affix.

**Comment by cvrebert** [comment]
@danimalweb That's the exact sort of thing that `position: sticky` can take care of. See http://filamentgroup.github.io/fixed-sticky/demos/demo.html and http://wilddeer.github.io/stickyfill/test/ to get a feel for what `position: sticky` is capable of.

**Comment by cvrebert** [comment]
It's tricky to get all the edge cases of Affix to work correctly. As a result, it was fairly buggy. (The fact that the popular `position:sticky` polyfills are their own freestanding projects is one indication of how complicated the problem is.)
The Bootstrap Core Team sadly doesn't have a lot of frontend JavaScript manpower. And since `position:sticky` covers the intended use case of Affix quite well, the decision was made to remove Affix so that we can devote more effort to our remaining jQuery plugins and so that users could be better served by migrating to one of the more robust `position:sticky` polyfills.
We admittedly were not aware of other use cases like @acch's when discussing the removal internally, but the core problems of buginess and scarcity of JS dev person-hours remain the same regardless.
It's unfortunate, but your best bet would likely be to engage with the `position:sticky` polyfill developers about adding functionality to support your use case.

CC: @twbs/team

**Comment by acch** [comment]
Thanks much for your detailed response @cvrebert, much appreciated. I agree that removing Affix in its current form is a good thing, as it's tricky to address all edge cases with such a powerful (read: complex) component.

But I don't think that the mentioned polyfill (which, by itself, is a temporary solution only) is the right place for the desired functionality either. `position:sticky` handles, well, the position of elements. Adding custom styles (color / bg are quite popular) is outside of the scope of that one - I'm a big fan of doing one thing and doing it right ;-)

I've come up with the following piece of JS code to address the scenario outlined above:
https://gist.github.com/acch/210467dc8478d8867658
It simply applies a style / class when below a certain scroll position, and applies another one when above... works well in my projects and (hopefully) is as unobtrusive as possible. I'm guessing that many of the (originally unintended) use cases of Affix could be addressed that way.

Assuming that more users will stumble upon this question when Affix is removed in v4, I'd be more than happy to properly document the workaround. What do you think about adding a Wiki page which could be referred to in the migration notes? Sounds like a low hanging fruit to me...

Please let me know how you want me to proceed on this - happy if I can help...
All the best!

Achim

**Comment by cvrebert** [comment]
> Adding custom styles (color / bg are quite popular) is outside of the scope of that one - I'm a big fan of doing one thing and doing it right ;-)

Well, if it's just a matter of adding support for either events or callbacks for when the scroll position state changes, and then doing the class/style manipulations in your own user-level callbacks, that seems within the realm of reasonable, IMHO, since it'd be fairly generic.

But yeah, the other option is to start a third-party JS library specifically for use cases like yours. If you want to go that route, it would be great if you could make your Gist into a full-fledged GitHub repo for easier collaboration. I think we'd be happy to mention and link to such a repo in our v4 Migration Guide page.

**Comment by hnrch02** [comment]
I agree with @cvrebert. The intended use case for affix (at least as far as I understand it) is covered by `position: sticky` and works much better with it. Maybe we'll see a `:stuck` pseudo class in the future. That [has been discussed before](http://w3-org.9356.n7.nabble.com/stuck-psuedo-class-WAS-specifying-position-sticky-td263024.html) but the discussion didn't go anywhere useful.

In the meantime you could use [Filament Group's polyfill](https://github.com/filamentgroup/fixed-sticky) which gives you both the polyfill for `position: sticky` and adds `.fixedsticky-on` to the element when it is in sticky mode. You could rely on that cross-browser by [forcing it to ignore any potential native support](https://github.com/filamentgroup/fixed-sticky#using-the-polyfill-instead-of-native).

**Comment by hnrch02** [comment]
> But yeah, the other option is to start a third-party JS library specifically for use cases like yours. If you want to go that route, it would be great if you could make your Gist into a full-fledged GitHub repo for easier collaboration. I think we'd be happy to mention and link to such a repo in our v4 Migration Guide page.

I think that's the way to go. It's not that common that we need to include it in Bootstrap but mentioning an alternative in the docs seems fair.

**Comment by acch** [comment]
Thanks much for your help - I will go ahead and turn my Gist into a GitHub repo including readme and a demo (will post the link here). My JS is fairly generic, so it might address some use cases for which Affix was abused in the past...

Feedback and opinions are highly welcome, of course!

Again, your responses are greatly appreciated.
All the best!

Achim

**Comment by acch** [comment]
Here is a first draft:
https://github.com/acch/scrollpos-styler

As I'm fairly new to the game: please let me know what else needs to be done to make this a 'proper' third-party Bootstrap citizen... I did read the Contributing guide already.

Again, thanks much for your help.

Achim

**Comment by cvrebert** [comment]
Posted some suggestions at https://github.com/acch/scrollpos-styler/issues/1

**Comment by cvrebert** [comment]
Added a ScrollPos-Styler mention to the migration docs in ba16aa44d06be8a6a4ba61a532906bb0c75f607e.
Good luck Achim!

**Comment by acch** [comment]
Chris, thank you very much for your assessment of this issue, for your recommendations on how to deal with it, for taking the time to review my repo, and for your constructive feedback. I know that helping beginners is not everyone's favorite... Very much appreciated!
