### ISSUE TITLE
`.table`'s `width:100%` not work in `.table-responsive`

### ISSUE THREAD

**Issue by chenweiyj** [twbs/bootstrap#17826]
I have big table. If I use `.table` on `<table>` tag only without wrapping by `.table-responsive`, the words in each cell are able to be wrapped. However, if there are too many columns, the width of the table will exceed the width of the window. So I wrap it in `.table-responsive` as follows:

```
<div class="table-responsive">
  <table class="table">...</table>
</div>
```

Then the words in the each cell are not wrapped well, making the width of the table very large, which seems that `width:100%` in `.table` class does not work if I use `.table-responsive`. Because I do not want users to scroll too much on the table, how can I solve it?

**Comment by cvrebert** [comment]
What version of Bootstrap are you using?

**Comment by chenweiyj** [comment]
I am using bootstrap 3.3.5

**Comment by cvrebert** [comment]
> the words in the each cell are not wrapped well, making the width of the table very large

It's possible that there might be other solutions, but the obvious one is to add `<br>`s or explicit `(max-)width` declarations, or similar, so that the text wraps more.

**Comment by cvrebert** [comment]
> seems that `width:100%` in `.table` class does not work if I use `.table-responsive`

It is working, but apparently not achieving the result you're desiring. It's not entirely clear what you mean here.
A naive (& incorrect) interpretation of `width:100%` in this case would be "the table should be exactly as wide as the bounds of its parent `.table-responsive` element", but that makes no sense since removing the `.table-responsive` would yield the same result and would presumably squeeze the table too much.

**Comment by mdo** [comment]
Unsure exactly what you're referring to, but given our priorities and where v3 is on it's timeline, I'm closing this as a won't fix.
