### ISSUE TITLE
Tooltip causing memory leak

### ISSUE THREAD

**Issue by sanchitgangwar** [twbs/bootstrap#17973]
The destroy method in Tooltip sets all the DOM references to `null` except `$element`. This causes DOM nodes to leak even after the destroy method is called.

Nullifying this variable removes the leak.

**Comment by cvrebert** [comment]
@sanchitgangwar Which version of Bootstrap are you using?

**Comment by sanchitgangwar** [comment]
@cvrebert Using version 3.3.5.

**Comment by cvrebert** [comment]
X-Ref: #16451

**Comment by gregsheremeta** [comment]
Still an issue in 3.3.6. I've made a simple JSBin that reproduces the issue. http://jsbin.com/pofomo/7/edit?html,console,output

To try it yourself, let the JSBin run for 10 seconds (console will say "done" when it's finished) and take a heap snapshot. While it is running, mouseover the html document contents so that some tooltips render. When finished, look in Summary view and you'll see there is one Detached DOM tree that is not related to tooltips.

Now comment out `that.$element = null` in the JSBin and re-run the above procedure (don't forget to mouseover the tooltips!). This time in Summary view, you'll see more than one Detached DOM tree -- you should see lots of HTMLSpanElements that are retained by $.cache

![selection_064](https://cloud.githubusercontent.com/assets/2248293/14094763/4ce73eca-f527-11e5-8a8f-4d175a94dcf4.png)

**Comment by gregsheremeta** [comment]
X-ref: https://github.com/twbs/bootstrap/pull/16039#issuecomment-99463892
