### ISSUE TITLE
Examples of code using HTML5 semantic tags

### ISSUE THREAD

**Issue by ripper2hl** [twbs/bootstrap#17978]
For example in [paneles.html](https://github.com/ripper2hl/bootstrap/blob/master/docs/_includes/components/panels.html) :

```
   <div class = "panel-heading">
     <h3 class = "panel-title"> Panel title </ h3>
   </ div>
```

change for

```
   <header class = "panel-heading">
     <h3 class = "panel-title"> Panel title </ h3>
   </ header>
```

this for combating bad practices on the web.

**Comment by kkirsche** [comment]
@ripper2hl personally, I don't believe that would be the right move for Bootstrap without having to go into much more detail about when to use them as they shouldn't be used any time you use those classes as it's dependent on the `<section>` that you are in. Also, it may not actually be used as a true footer, but rather as simply a stylistic "footer". While semantically it may be a footer anyway, I'm not sure it would match the W3C's description / details of a footer, "A footer typically contains information about its section such as who wrote it, links to related documents, copyright data, and the like." [Source](http://w3c.github.io/html-reference/footer.html)

**Comment by ripper2hl** [comment]
We could discuss who is and who is not a `<footer>`, but the point is to use semantic tags, rather than an infinity of nested divs, obviously divs are not bad, but what about header, nav, article, section, aside and footer?

This is a proposal for improving the documentation, not more

**Comment by kkirsche** [comment]
I'm not necessarily saying it is or it isn't, my point is simply that many users use bootstrap's documentation as general HTML how should I code. By using semantic tags without proper and full explanations, we run the risk of having many (arguably) "incorrectly" coded websites. My concern is simply that for users who do not truly understand when semantic tags should be used and for what type of content that it will hurt the quality of pages due to the reach of a major project like Bootstrap.

**Comment by brettryan** [comment]
I would strongly oppose this change, your argument as for this to combat bad practices on the web. I don't see how the use of `<footer>` would help, I think it would introduce bad semantic. A `<footer>` should only appear once within its closest sectioning content, thus, if one was to use a div as a panel, the footer may actually incorrectly apply to the whole page, this would be even worse if multiple panels were to be used. You could then argue that a panel should be within an `<aside>`, which may be true for some cases but certainly most uses of a panel would not be in such a case. Due to this a footer does not introduce a new sectioning content area within a document.

**Comment by ripper2hl** [comment]
no more footer example xD

**Comment by mdo** [comment]
Not happening for v3 and unlikely to happen universally in v4.

Most of our CSS is targeting against specific classes—the elements don't matter. Things like `article`, `header`, etc don't have as much semantic value when compared to `button`, `input`, etc. where there is legitimate browser behavior that comes into play.

Those HTML5 elements only have `display` specified in our base styles. The spec might say that they have specific meaning, but in most cases the elements do nothing more than serve as `div` replacements.

Lastly, we do use a number of HTML5 elements in our docs—`nav` and `header` come to mind in a number of places. If there are other places we could update, feel free to suggest those in some pull requests.
