### ISSUE TITLE
v4 alpha: 767px viewport registers as both "small" and "medium" 

### ISSUE THREAD

**Issue by snarkq** [twbs/bootstrap#17992]
You can see at:

 http://v4-alpha.getbootstrap.com/layout/responsive-utilities/

If you set the viewport to 767px it says the viewport is "exactly" small and "exactly" medium.

This means if I use the responsive utility classes I get a weird result at 767px where both small and medium content is displayed at the same time.

What is the best way to get around/deal with this?  Thanks for any help!

**Comment by tshinnic** [comment]
A somewhat frustrating confirmation and non-confirmation.  I can reproduce what (I think) you are seeing at http://v4-alpha.getbootstrap.com/layout/responsive-utilities/#test-cases : 

![17992_767px viewport_nok](https://cloud.githubusercontent.com/assets/842881/10618580/5acb011c-7736-11e5-9d93-952ef90fa66f.png)

But then I *can't* reproduce on a recent (yesterday) copy of the `v4-dev` branch.  That is, I think the problem has gone away in newer sources.  I do see many changes in the resulting `bootstrap.css`, some very interesting indeed:
```
        5186c5184
        < @media (min-width: 48em) {
        ---
        > @media (min-width: 768px) {
```
So I have to think they've since 'fixed' what you were seeing.  Key is that they are *not* refreshing the `v4-alpha.getbootstrap.com` web pages, apparently waiting until the next alpha release.  (I suppose it makes sense that the alpha doc site should match the latest alpha release)  Maybe you can grab the `v4-dev` alpha branch and run with that?

**Comment by snarkq** [comment]
@tshinnic Thanks for taking the time to look into this. You were exactly right - this is solved in the `v4-dev` alpha branch.

Closing this issue.

**Comment by cvrebert** [comment]
Approximate duplicate of #17388.
