### ISSUE TITLE
Add Bootstrap 4-alpha to NPM registry

### ISSUE THREAD

**Issue by ryzy** [twbs/bootstrap#18006]
Hi,

Any plans to make 4.0.0-alpha available in the npm registry?

**Comment by kukac7** [comment]
@ryzy `npm install https://github.com/twbs/bootstrap.git#v4-dev`

**Comment by cvrebert** [comment]
We'll publish the next alpha version (`v4.0.0-alpha.2`) when it gets released.

**Comment by saponifi3d** [comment]
Any word on when alpha 2 is going to be released to NPM? Thanks!

**Comment by kkirsche** [comment]
Due to the strict release cycle as described in the blog post for alpha 1 the core team is focusing on a longer beta for the first alpha or two to ensure that as many bugs as possible are caught in each release and Bootstrap 4 isn't rushed out with bugs. At this point, no date is publicly announced to my knowledge for any future release (alpha, beta or production)

**Comment by saponifi3d** [comment]
:+1: okay cool. thanks for the update.

**Comment by schnerd** [comment]
@cvrebert Do you all still plan to add `v4.0.0-alpha.2` to npm now that it's been released?

**Comment by cvrebert** [comment]
@schnerd It's already on npm. See #18520.

**Comment by schnerd** [comment]
Awesome–thanks. Was expecting a different package for some reason.
