### ISSUE TITLE
Problems with .btn -webkit-font-smoothing on older Safari versions

### ISSUE THREAD

**Issue by insad** [twbs/bootstrap#18017]
In CSS, .btn needs an extra rule:

-webkit-font-smoothing: auto;

If not, in older Safari versions (< 9) a button gets a value "auto" here, but a link styled as a button gets value "antialiased" here, which gives weird looks for the texts on the same (looking much thinner on the link than on the button)!

**Comment by kkirsche** [comment]
@insad I'm not sure Bootstrap wants to get into doing this for older versions since it's not technically a "supported" version:

<blockquote>Bootstrap supports the latest versions of each major platform’s default browsers.</blockquote>

With that said, while easy my concern is that this isn't picked up by autoprefixer and as such we will then have webkit specific stuff but we won't have the equivalent Mozilla (` -moz-osx-font-smoothing`) or Blink (if it has a unique format) version.

**Comment by mdo** [comment]
We won't be tweaking the font smoothing—we've had that in the past and pulled it all. (ProTip: if you want thinner text across your Mac, disable LCD font smoothing in your System Prefs.)

**Comment by cvrebert** [comment]
X-Ref: #7253
