### ISSUE TITLE
scrollspy fails handling fragment IDs that include a "#", like ##about

### ISSUE THREAD

**Issue by unruledboy** [twbs/bootstrap#18041]
in angularjs, we need use double hash tags like "##about" to do in page navigation.

but scrollspy in v3.3.2, line number:1876, throws exceptions saying syntax error in Internet Explorer 11:

var href  = $el.data('target') || $el.attr('href')

//0x800a139e - JavaScript runtime error: Syntax error, unrecognized expression: ##about

**Comment by cvrebert** [comment]
Based on my reading of the URL spec (in particular, https://url.spec.whatwg.org/#syntax-url-fragment ), `#` is not a valid fragment ID character, so `##about` is not a valid URL (as opposed to `#about`, which is valid).
Also, v3.3.2 is outdated. Upgrade to Bootstrap v3.3.5.

**Comment by cvrebert** [comment]
Or if we consider `##about` as a CSS selector, then it's invalid because [CSS ID selectors](https://drafts.csswg.org/selectors-4/#id-selectors) require the ID value to be a [CSS identifier](https://drafts.csswg.org/css2/syndata.html#value-def-identifier), and those cannot contain unescaped `#` characters.

> in angularjs, we need use double hash tags like "##about" to do in page navigation.

<sup>[[citation kindly requested](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)]</sup>

**Comment by unruledboy** [comment]
so rather than using "##about", I believe better to work around it like this: http://stackoverflow.com/questions/14712223/how-to-handle-anchor-hash-linking-in-angularjs

thanks.

**Comment by cvrebert** [comment]
Glad you found a solution.
