### ISSUE TITLE
Allow customization of icons for .form-control-success, etc.

### ISSUE THREAD

**Issue by ricordisamoa** [twbs/bootstrap#18057]
I'm glad you dropped Glyphicons from v4, but now you even _embed_ base64 SVGs for `form-control-success`, etc?

**Comment by arashataei** [comment]
I think yes.  It is working now

**Comment by cvrebert** [comment]
We already have `$form-icon-*` variables to allow these icons to be overridden.

**Comment by ricordisamoa** [comment]
> We already have $form-icon-* variables to allow these icons to be overridden.

I saw them, but I can't find a proper way to use, say, Font Awesome in pure CSS.
Thanks for the prompt reply.

**Comment by arashataei** [comment]
U first import it to ur main structure and get an object from that icon
wherever u want

**Comment by cvrebert** [comment]
You'd use something like
```css
.has-warning .form-control-warning {
  background-image: none;
}
```
to kill Bootstrap's SVG icons, and then add some font-specific CSS and extra boilerplate HTML elements.
Example: http://jsfiddle.net/cvrebert/kpy3Lqe3/ (Alternate approaches likely also exist)

We should definitely document how to disable the built-in icons, and perhaps consider moving the `url()` into the icon variables themselves so that e.g. simply `$form-icon-success: none` would work.

But I don't know whether we'd be interested in adding anything outside of that.
CC: @mdo

**Comment by mdo** [comment]
You can pipe in whatever you want—`none` or a custom `url()` now. Merged in a bunch of changes there for the URL handling. Also mentioned some of this in the docs in 365db6e.
