### ISSUE TITLE
Custom forms: use an SVG image instead of PNG

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#18065]
/CC @mdo @cvrebert: where did the current image come from?

**Comment by cvrebert** [comment]
From Primer:
* https://github.com/twbs/bootstrap/blob/aedf1f9ad96aa69e6d8beeeba94e74f8223e9ce4/scss/_custom-forms.scss#L127-L138
* https://github.com/primer/primer/blob/7127c81fd9522a5b7c07171511119a569732a7d5/scss/_forms.scss#L514

**Comment by XhmikosR** [comment]
Can we find that in SVG? It's the only Base64 PNG in v4.

**Comment by tshinnic** [comment]
Before, as png
![18065_before_as_png_screenshot](https://cloud.githubusercontent.com/assets/842881/10747230/c919fd82-7c20-11e5-9339-91f8bb00194e.png)

After, as SVG
![18065_after_as_svg_screenshot](https://cloud.githubusercontent.com/assets/842881/10747234/d3c3b502-7c20-11e5-928c-3aad1f46ed35.png)

These screenshots are blown up in the browser.  The SVG one is slightly sharper I think.  It is possible I don't have the color correct, but it looked like the png was the equivalent of `#333333`.  And maybe the discrepancy is again because the png was blown up?  If wrong, someone can base64 decode - change fill color - encode - and replace.

**Comment by cvrebert** [comment]
@tshinnic Which browser and OS?

**Comment by tshinnic** [comment]
Firefox 41 / Win10 
This was captured from the comp/forms docs page, first using the previous png, and then the replacement SVG, all via the `bootstrap.css`.

I whittled the SVG down to the basics.  I could post it if you want.... Oh, Fargo!  I forgot to delete the unneeded `x=` and `y=` ...

```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     zzx="0px" zzy="0px"
     width="16" height="20" viewBox="0 0 16 20"
     enable-background="new 0 0 16 20">
  <path style="fill:#333333;" d="M 8,0 0,8 16,8 Z" />
  <path style="fill:#333333;" d="M 8,20 0,12 16,12 z" />
</svg>
```

**Comment by tshinnic** [comment]
Now it is 
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="16" height="20" viewBox="0 0 16 20"
     enable-background="new 0 0 16 20">
  <path style="fill:#333333;" d="M 8,0 0,8 16,8 Z" />
  <path style="fill:#333333;" d="M 8,20 0,12 16,12 z" />
</svg>
```
with exactly the same appearance.

**Comment by mdo** [comment]
Done in #17222.
