### ISSUE TITLE
Hovering over <td rowspan="..."> in .table-hover only highlights first spanned row

### ISSUE THREAD

**Issue by ilmoralito** [twbs/bootstrap#18102]
If i have a table with rowspan in some td i get a strange behavior in the hover, only the first row is highlighted.

You can see the behavier in this image where i am hovering over the first cell in the first row

![nami](https://cloud.githubusercontent.com/assets/928920/10832023/6c68ec58-7e4e-11e5-97c0-083831ef0447.png)

The code i am using is here https://jsfiddle.net/tja6gtz1/

If i am missing something, let me know. Thanks in advance

**Comment by cvrebert** [comment]
This is simply how the `tr` selector works in CSS. It affects the children of the `tr` rather than the members of the "logical rows" established by using `rowspan`. AFAIK, there's no non-super-hacky way to select such "logical rows" using CSS, so this is the best we can do.
CC: @mdo for confirmation

**Comment by mdo** [comment]
Yup, that sounds right to me.

**Comment by ThangPhamIT** [comment]
hi guy,
please ref this url https://codepen.io/paulofsis/pen/xfHtC
