### ISSUE TITLE
Double scrollbars when expanding a dropdown in a collapsed fixed top navbar

### ISSUE THREAD

**Issue by stevebread** [twbs/bootstrap#18124]
This can be reproduced in the fixed-top sample (http://getbootstrap.com/examples/navbar-fixed-top) by shrinking the browser window to collapse the navbar and expanding the Dropdown menu item. A scrollbar is introduced even if the display is large enough to show the whole menu.

**Comment by cvrebert** [comment]
The Bootstrap v3 navbar unfortunately has several known issues, many of which cannot be feasibly resolved without overhauling the architecture of the navbar, which would break backward compatibility.

Also, in order to focus on the upcoming Bootstrap v4 and avoid code churn (& the associated possibility of thereby introducing other bugs), we're no longer making significant changes to Bootstrap v3's navbar at this point, unless perhaps an issue is a critical showstopper, which this thankfully isn't.

In response to said known issues, Bootstrap v4 (which isn't backward-compatible) completely overhauls the design of the navbar. You can check out the current draft on http://v4-alpha.getbootstrap.com/components/navbar/ (note that it's a work-in-progress; that's why it's in alpha).

So unfortunately I have to close this as WontFix. You have our sympathies if you have to hack around this problem by yourself. We wish you good luck and would welcome any feedback you have regarding Bootstrap v4's draft navbar component.

/fyi @mdo

**Comment by stevebread** [comment]
No problem :) Thanks for the information on v4. I worked around this on v3 using hidden-xs/visible-xs to show the dropdown items in the navbar itself when shrunk.
