### ISSUE TITLE
V4 recommendation: tabs .active class be applied to <li> rather than <a>

### ISSUE THREAD

**Issue by gxclarke** [twbs/bootstrap#18147]
In V3 of the tabs component, the `.active` class was applied to the `<li>` element.

In V4, it is now applied to the child `<a>` element instead.

This imposes styling limitations on the active tab. Please consider reverting so that the `<li>` element can be styled for an active state.

Ref: #17799

**Comment by cvrebert** [comment]
Refs c8306d2f704685dfc68e530cf3e820cb65cedc18
Obviously only @mdo can give the exact rationale behind that commit, but in general, v4 tries to allow for more flexible markup, so that e.g. you aren't required to use a `<ul>`/`<ol>` and the `<a>` can be a descendant of the `<li>` instead of only a direct child of the `<li>`.

**Comment by gxclarke** [comment]
Thank you, Chris. Understood on the increased flexibility markup in V4, but I'm thinking this wouldn't be sacrificed by targeting `<li>` instead. Is there a way to tag this issue for @mdo to weigh in?

**Comment by cvrebert** [comment]
The @-mentions of his username have already accomplished that.

**Comment by mdo** [comment]
It'll stay as a modifier on the link itself—makes more sense than requiring the parent element and limiting markup more. We could support both, but that just means doubling some of our CSS for little benefit.

> The @-mentions of his username have already accomplished that.

Plus I watch the repo, so I get pinged for all activity 'round these parts :grin:
