### ISSUE TITLE
Cards have a transparent background

### ISSUE THREAD

**Issue by BlameDylan** [twbs/bootstrap#18153]
When using the latest v4 Alpha 1, cards do not have a white background as expected (like in v3) when placed on a jumbotron or other image.

![Cards no Background](https://cloud.githubusercontent.com/assets/2935060/10928237/68c97d66-826c-11e5-8481-8d9933fb4882.png)

**HTML Code:**
```
<div class="jumbotron">
    <div class="container-fluid col-xs-12 col-sm-8">
        ...
    </div>
    <div class="col-sm-4">
        <div class="card card-default">
            <div class="card-header">Featured</div>
            <div class="card-block">
                Hey
            </div>
        </div>
    </div>
</div>
```

**Custom Jumbotron CSS (Written in style tags)**
```
.jumbotron {
position: fixed;
background: #000 url("https://static.mywebsite.com/photos/image.jpg") center center;
top: 0;
left: 0;
min-width: 100%;
min-height: 100%;
}
```

Thank you for your time and amazing software!

**Comment by cvrebert** [comment]
IMHO, the existing transparency seems like a reasonable approach (although so would inheritance, which I believe would avoid your particular problem). I can imagine some folks could see the transparency effect as a feature.
Perhaps instead there should be a [card background variant](http://v4-alpha.getbootstrap.com/components/card/#background-variants) class (spitballing: `.card-light` ?) that could be used to set a white background when necessary.

**Comment by BlameDylan** [comment]
Heres my two cents: I think a white background should be the default, and then possibly a `.card-transparent'. Could you elaborate more on what you mean but inheritance?

**Comment by cvrebert** [comment]
I'm betting a lot of the time folks will just want to inherit the background color from the parent (i.e. `background-color: inherit`), oftentimes inheriting the color of the `<body>`/container. If cards were white by default, then folks would have to create+use a custom `.card-my-color` or `.card-bg-inherit` class when they wanted to accomplish what I described.

IIUC: `background-image` isn't an inherited property, so setting `background-color: inherit` instead of `background-color: transparent` would use the inherited fallback background color instead of the image in your example.

**Comment by Skwai** [comment]
+1

**Comment by judetucker** [comment]
+1 for ```card-transparent``` option.

I have found that  ```card-default``` being white and providing a ```card-transparent``` option is extremely helpful.

**Comment by mdo** [comment]
Resolved already (see https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L9).
