### ISSUE TITLE
v4: Less vs Sass

### ISSUE THREAD

**Issue by ionas** [twbs/bootstrap#18197]
So one reason to stick with Bootstrap over Foundation was LESS.
That basically says it all.

**Comment by cvrebert** [comment]
To summarize why we switched, quoting from [the v4 alpha blog post:](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/)
> **Moved from Less to Sass.** Bootstrap now compiles faster than ever thanks to Libsass, and we join an increasingly large community of Sass developers.

(Ruby Sass' slowness was one reason Less was chosen over Sass for Bootstrap v2. With libsass, speed is no longer a concern.)

Also, Sass is more pleasant to program in than Less since it has (among other things):
* [a map datatype](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps)
* built-in loop syntax (versus [having to manually translate loops into recursion](http://lesscss.org/features/#loops-feature) in Less)
* [placeholders](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholders)

...which together allow "fancy" code like the grid system to be expressed more cleanly in v4 than in v3.

Additionally, quoting from a response to a similar request to use a different preprocessor (https://github.com/twbs/bootstrap/issues/17484#issuecomment-138100600):
> * We've already committed to Sass for v4. I doubt folks out there will be saying thank you to us for switching mid-development to yet another preprocessor that [fewer] folks use by comparison.

So, we won't be switching back to Less. Sorry...
/cc @mdo 

> So one reason to stick with Bootstrap over Foundation was LESS.

Fortunately, plenty of other reasons still remain. :-)
And back when we were using Less, some folks criticized us for not using Sass like Foundation. See the irony?
No matter which preprocessor we use, our choice is always going to leave some group of folks unhappy.

**Comment by mdo** [comment]
Yup, Sass it is.

**Comment by jhli** [comment]
That's all okay but means I am going to consider Foundation because I don't have a preprocessor choice anyway.
