### ISSUE TITLE
Wrong behaviour while animating

### ISSUE THREAD

**Issue by twKrash** [twbs/bootstrap#18287]
He all.
Got an issue. If you try to show tooltip while fadeout animation is in progress tooltip blinks and is not shown.  Here is an example:

https://jsfiddle.net/24g9pokL/

Also this happens with destroy action. (As I found destroy does not destroy an object actually... that's weird).

**Comment by kafeltz** [comment]
Try this, it works for me.
Your example is weird. You init, show and hide at the same time.

$(function() {
	var selector = '#selector1'; 
    $(selector).tooltip({placement: "right",title: "Tooltip WITH animation",trigger: "manual"});
    
    $('#test1').on('click',function(){
		$(selector).tooltip('toggle');
    });
});

**Comment by twKrash** [comment]
@kafeltz, No... It won't help me....

I'm using tooltip as validation error notification . In my case I need to hide tooltip and after that show again if validation fails.
Already have a workaround but it's pretty ugly: 
```javascript
var initialized = {};
var selector = '#name';

function testShow(){
	if(undefined === initialized[selector]) { 
		initialized[selector]=true;
		$(selector).tooltip({placement: "right",title: "Tooltip Fix",trigger: "manual"}).tooltip('show');
	} else {
		$(selector).one('hidden.bs.tooltip',function(e){
			$(selector).tooltip({placement: "right",title: "Tooltip Fix",trigger: "manual"}).tooltip('show');
		});
	}
}
testShow();
$(selector).tooltip('destroy');testShow();
```

**Comment by cvrebert** [comment]
Code like this:
```js
$(selector).tooltip('hide');
$(selector).tooltip('show');
```
is invalid since the `hide` and `show` methods are asynchronous (as mentioned in the docs). The hiding may not have completed by the time you attempt to show. You need to listen for the `shown.bs.tooltip` / `hidden.bs.tooltip` events before performing the next show/hide. (And `destroy` calls `hide` prior to performing the actual destruction.)

#17800 will make this type of mistake more obvious.
