### ISSUE TITLE
Add containers which responsively switch between being fluid or fixed-width

### ISSUE THREAD

**Issue by ucavus** [twbs/bootstrap#18335]
E.g. there are no classes like `container-md`. I wrote [a gist](https://gist.github.com/ucavus/13fb483dabab0ce9dec9) to work around the issue.

It seems odd that the framework allows column styles to be invoked only at certain screen widths, but not for containers (and rows).

**Comment by mdo** [comment]
Containers are `max-width` right now, so they're always "responsive" in v4. Not sure I see much value in replacing the existing grid and container system with this—feels over engineered to me.

**Comment by ucavus** [comment]
@mdo Yes, containers are already responsive but they cannot switch between fluid and fixed-width which provide very different layouts, especially on larger screens. The issue was not about making them responsive, but about allowing the same flexibility for containers as is done for columns.

**Comment by mdo** [comment]
I should've written that clearer—it's less about any particular behavior and more about the over-engineered aspect. The columns within those containers behave the same though—column widths are all set in percentages. A pixel-based `max-width` vs a `width: 100%` doesn't matter much.

The kind of control seems ripe just for overrides rather than a rethinking of a core part of the grid system at this point in v4's development process.
