### ISSUE TITLE
Carousel keyboard not working as expected

### ISSUE THREAD

**Issue by mluce194** [twbs/bootstrap#18347]
It is said in the documentation that, by default, the carousel should react to keyboard events. In my case, it does react to keyboard events but what it does is that it makes my slide shift slightly from left to right, or right to left (depending on what keyboard arrow I press) but it does not make carousel move to the next slide. Isn't it what it should do?

**Comment by patrickhlauke** [comment]
Please provide a simplified test case (in something like jsfiddle) showing the problem you're experiencing.

**Comment by mluce194** [comment]
I just put up a jsfiddle together to show you the issue. Please check it out here: https://jsfiddle.net/mluce194/yn2tp1do/

**Comment by patrickhlauke** [comment]
carousels only react to keyboard when one of their focusable components (like the "<" or ">" arrow) currently have focus. it seems that you're expecting the carousel to reach to keyboard no matter where the user's current focus is on the page? if so, that's not intended behavior. the fact that you're seeing left/right shifting is because your page is subtly wider than the window.

**Comment by cvrebert** [comment]
@patrickhlauke Please label issues when closing them in the future. Thanks. Sorry to nag.
