### ISSUE TITLE
Firefox: Focus gets lost in modal when active tab/window changes

### ISSUE THREAD

**Issue by robsch** [twbs/bootstrap#18365]
I've tested this with Chrome and Firefox. In Chrome all is fine, in Firefox I've got the problem:
You can test it right here: http://getbootstrap.com/javascript/#modals-related-target . If you open one of the modals, focus an input, enter some characters, switch to another Firefox tab or to another window and then come back to the tab with the open modal, the input is not focused anymore. The user has to click again into the input. In Chrome the input is still focused, in Firefox not.

Can you recommend a workaround for this?

**Comment by cvrebert** [comment]
Filed Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1228802
(I'd recommend adding yourself to the CC List of the bug.)

The `<input>` loses focus because, when switching back to the tab, Firefox, unlike all the other browsers and in apparent violation of [the relevant spec](https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps), fires an initial `focus` event at `window.document`. Bootstrap's code interprets this as an attempt to move focus outside of the modal, so it refocuses the modal itself, thus interrupting the subsequent `focus` events which would normally fire at the `window` and then at the `<input>` to restore the normal focus, as happens in the other browsers.

In my limited testing, it does not appear to be possible to actually focus the `document` per se, so it seems like we could fix this by adding a special case in `enforceFocus` to ignore the `focus` event if its target is `document`.

**Comment by robsch** [comment]
Thank you for your efforts! If anyone is interested or can provide a workaround you may want to take a look at http://stackoverflow.com/q/33970707/57091 .

**Comment by cvrebert** [comment]
Added relevant web-platform-test: https://github.com/w3c/web-platform-tests/pull/2571
