### ISSUE TITLE
Hidden Class v4 bootstrap

### ISSUE THREAD

**Issue by xc4patryk** [twbs/bootstrap#18382]
why put two of the same class ?
hidden-xs-up = hidden-xl-down

and i have proposals to add show class like hidden

Best regards :)

**Comment by cvrebert** [comment]
> why put two of the same class ?
> hidden-xs-up = hidden-xl-down

For uniformity's sake, since these classes all follow the pattern `hidden-{xs,sm,md,lg,xl}-{up,down}`. It saves folks from having to remember a special case that exactly one of those classes doesn't exist. A single duplication isn't so bad in the grand scheme of things.

> and i have proposals to add `show` class like `hidden`

We've deliberately removed `show-*` classes in v4. We had them in v3, and they caused problems because they require setting an explicit non-`none` value for the `display` property, which can override the desired `display` set by other classes. We worked around this late in v3 by adding variants for common `display` values (e.g. `.visible-xs-block`, `.visible-xs-inline`, `.visible-xs-inline-block`), but (a) it wasn't elegant, (b) it didn't cover [all possible `display` values](https://developer.mozilla.org/en-US/docs/Web/CSS/display#Syntax) since that would have ballooned the number of classes, and (c) it makes their usage become context-sensitive because the user has to know ahead of time what `display` value is appropriate in a given situation.

By contrast, v4's `hidden-*` scheme doesn't suffer from those issues.
The v4 migration guide ([and v4's docs](http://v4-alpha.getbootstrap.com/layout/responsive-utilities/)) explain how `show-*` effects can be achieved by combining `hidden-*` classes instead: http://v4-alpha.getbootstrap.com/migration/#responsive-utilities

**Comment by v3nt** [comment]
how do i include '.hidden-md-up' in my scss files? Seem to be having an issue here. Thanks
