### ISSUE TITLE
Simple question - .row > div

### ISSUE THREAD

**Issue by marekkobida** [twbs/bootstrap#18589]
Why did you use this
```
.col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}
```
instead of this
```
.row > div {
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}
```

**Comment by cvrebert** [comment]
Tag selectors are evil (because there are cases where the user wants to use something other than a `div`, such as `aside` or `form`), and child selectors are evil (because of CSS specificity).
There is some debate over the merits of adding a `.col` class and moving these declarations into that class, but there are some concerns over the loss in convenience by having to write `<div class="col col-sm-3">` instead of `<div class="col-sm-3">`. That discussion is smouldering elsewhere.
