### ISSUE TITLE
.table-responsive doesn't fill up width in Firefox

### ISSUE THREAD

**Issue by aimeos** [twbs/bootstrap#18612]
When adding the v4 ".table-responsive" class to a table, the thead and tbody elements will use only the absolute necessary space in Firefox despite of the width of 100% of the table itself. This is due to the "display: block" necessary for the overflow.

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem.
A screenshot would also be appreciated.

**Comment by stephaniepurvis** [comment]
I made a JS Fiddle for this issue (<a href="https://jsfiddle.net/stephaniepurvis/pj6w2n64/2/" target="_blank">here</a>) and didn't see a problem in Firefox 43.0.1 on Mac.

**Comment by twbs-lmvtfy** [comment]
Hi @stephaniepurvis!

You appear to have posted a live example (https://fiddle.jshell.net/stephaniepurvis/pj6w2n64/2/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 52, column 12 thru line 53, column 10: ```` td ```` start tag in table body.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by stephaniepurvis** [comment]
I made a JS Fiddle for this issue (<a href="https://jsfiddle.net/stephaniepurvis/pj6w2n64/2/" target="_blank">here</a>) and didn't see a problem in Firefox 43.0.1 on Mac.

**Comment by stephaniepurvis** [comment]
Trying again (I can't seem to do anything right today!).  I made a JS Fiddle of this issue here: https://jsfiddle.net/stephaniepurvis/pj6w2n64/6/

I don't see a problem with the table though. I am viewing this in Firefox 43.0.1 for Mac.

**Comment by aimeos** [comment]
Sorry, my fault!
I've added ".table-responsive" to the table itself instead of wrapping a ```<div class="table-responsive"></div>``` around

**Comment by cvrebert** [comment]
See also https://github.com/twbs/bootlint/wiki/E027

**Comment by Quy** [comment]
Per `Migrating  to v4`:
```Responsive tables no longer require a wrapping element. Instead, just put the .table-responsive right on the <table>.```

Will this be the case and just has not been implemented yet?

**Comment by cvrebert** [comment]
@mdo Are the docs wrong, or is the new `.table-responsive` broken?

**Comment by cvrebert** [comment]
@mdo Ping.

**Comment by creative3d** [comment]
Hello. Sorry to bother you. I've faced with the same issue, don't know how to solve it correctly because I need to change about thousand pages. Can't do this huge work twice or more.
The issue is not only with Firefox. So, if to wrap a table with div = table-responsive, then everything is fine (see the first table), but if just use a table with class = table-responsive, then the table don't expand 100% (see table 2).
![screenshot](https://cloud.githubusercontent.com/assets/19249899/19317742/3a7fe40e-90d0-11e6-873e-bb0672a4d43e.jpg)
[html file for testing](https://github.com/twbs/bootstrap/files/525033/test-responsive.txt)
I'd like to know if this is gonna be fixed or should I wrap tables in div tags? I'm worried that div tags will stop working one day because it's kind of old feature... or will it be working forever? :)

**Comment by cvrebert** [comment]
@mdo PING.

**Comment by mdo** [comment]
> @mdo PING.

Hi there! Yes, I've been in and out and outlandishly unresponsive to almost everything. Apologies for that—getting caught up slowly but surely.

> @mdo Are the docs wrong, or is the new `.table-responsive` broken?

It's now a modifier, not a wrapper. PR has been opened to address that.

Lastly, there's no bug here near as I can tell. FF50 and latest Safari look great.

**Comment by dumb** [comment]
I apologize for dragging a closed issue back into the light, but I'm not sure the responsive table is behaving as it should.

As of v4.0.0-alpha.6, the problem seems to remain:
- tables with the `.table` class are 100% of the width of their parent
- tables with `.table .table-responsive` are only as wide as their content
- tables with the class `.table` that are also wrapped with `<div class="table-responsive">` are %100 of the width of their parent

Here's a fiddle:

https://jsfiddle.net/45tbox4f/

Example 2 and 3 are both scroll horizontally, but the non-wrapped table doesn't expand to its parent as @aimeos pointed out. I believe the example in the docs appears to work because its content is already quite wide(?)

(Tested on the latest Safari, Chrome OSX, FF OSX, Chrome Win and FF Win)
