### ISSUE TITLE
Default outline on links and buttons on mobile

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#18650]
In Microsoft Edge / Windows 10 Mobile, the browser applies the default dotted outline to links - while Safari/iOS and Chrome/Android don't. This can lead to some unsightly effects after tapping pagination links, for instance.

![outline-win10mob1](https://cloud.githubusercontent.com/assets/895831/11979077/45bfdd86-a988-11e5-8a53-fd59fa8ff868.png)

![outline-win10mob2](https://cloud.githubusercontent.com/assets/895831/11979081/4960face-a988-11e5-94ca-f432752dfb55.png)

![outline-win10mob3](https://cloud.githubusercontent.com/assets/895831/11979084/4d401634-a988-11e5-8181-db77cc343a1e.png)

Related, outline is also shown for buttons both on Microsoft Edge / Windows 10 Mobile and Chrome / Android.

![outline-win10mob-button](https://cloud.githubusercontent.com/assets/895831/11979110/7e8fce46-a988-11e5-998e-62a48b7f13aa.png)

![outline-android-button1](https://cloud.githubusercontent.com/assets/895831/11979165/fa857898-a988-11e5-86f9-610a553ae808.png)

![outline-android-button2](https://cloud.githubusercontent.com/assets/895831/11979167/fe690efc-a988-11e5-9352-58cddc567f81.png)

On iOS, links and buttons do not receive any standard outline, and the same for links in Chrome / Android.

As both pagination links and buttons provide some fairly clear change in style when focused already, wondering if we could/should explicitly suppress outline on them. May be a mild accessibility-related issue, though.

**Comment by bassjobsen** [comment]
about the outline for the buttons. This outline is set by the `tab-focus()` mixin in the `scss/mixins/_tab-focus.scss` file. It look like that shown beneath:

    @mixin tab-focus() {
      // Default
      outline: thin dotted;
      // WebKit
      outline: 5px auto -webkit-focus-ring-color;
      outline-offset: -2px;
    }

The  `outline: 5px auto -webkit-focus-ring-color;` makes the outlines look different as explained at http://stackoverflow.com/a/11929801/1596547

If we do need an outline for the focus and active states i can not find a reason to `outline: 5px auto -webkit-focus-ring-color;` and not only `outline: thin dotted;`. The `outline: 5px auto -webkit-focus-ring-color;` looks different on diffent browsers.

The reason to use a outline will be explained in `scss_reboot.sccs`:

    // Work around a Firefox/IE bug where the transparent `button` background
    // results in a loss of the default `button` focus styles.
    //
    // Credit: https://github.com/suitcss/base/
    button:focus {
      outline: 1px dotted;
      outline: 5px auto -webkit-focus-ring-color;
    }

Finally notice that `outline: 1px dotted` does not set the `outline-color` property. The initial value for this property is:
>`invert`, for browsers supporting it, `currentColor` for the other

See: https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color
Only IE and Edge do support the `invert` keyword, that's why the outline looks different on IE and Edge.

Putting all together, if we have to set outlines for buttons (and other elements), i suggest to change the  the `tab-focus()` mixin as follows:

    @mixin tab-focus() {
      outline: thin dotted currentColor;
      outline-offset: -2px;
    }
The `tab-focus()` mixin is also used  in `scss_reboot.sccs` to set a default outline for the `a` elements

**Comment by patrickhlauke** [comment]
My initial suggestion was to actually suppress the outline for pagination links, and potentially for buttons as well, since they have fairly obvious focus styles already.

**Comment by bassjobsen** [comment]
to remove the outlines i suggest to change the mixin into:

    // You can remove the outline as long as you style the focused element differently
    // http://a11yproject.com/posts/never-remove-css-outlines/

    @mixin tab-focus() {
      outline: none;
    }

Notice the above removes the outline from every `a` element, so we should check if the focus state is styled differently indeed for every component. Also notice that components do not provide styles for the styling of the `a`s now, except from the disabled states, also see: https://github.com/twbs/bootstrap/issues/18630.

**Comment by patrickhlauke** [comment]
I'd rather not remove ALL focus outlines, but only surgically for known situations where it's safe. i'll revisit this in the new year once I get a chance.

**Comment by mdo** [comment]
We've revamped our focus styles, so closing this for now. I don't expect much to change after we implemented custom focus states via box-shadow.
