### ISSUE TITLE
Bring back .pull-left

### ISSUE THREAD

**Issue by hanakin** [twbs/bootstrap#18674]
since we are using breakpoints now we are needing to specify pull-xs-left which is counterintuitive if we always want to pull something it should instead have a default of pull-left to encompasses all breakpoints. This applies with all the new responsive utilities

**Comment by cvrebert** [comment]
X-Ref: #18340.

It's not really any less intuitive than the grid system's column classes (e.g. `.col-xs-N`), and is consistent with the grid system's scheme.

Also, having both `.pull-left` and `.pull-{xs,sm,md,lg,xl}-left` raises questions about what happens when you apply both `.pull-left` and responsive pull class(es) on the same element. And it means that the same pull semantics could be expressed in multiple different ways, hindering readability. Eliminating `.pull-left` avoids these issues without decreasing power.

Also, if someone decides later that they want to make an existing non-responsive float be responsive, starting from `.pull-xs-left` makes that transition slightly easier.

/fyi @mdo
