### ISSUE TITLE
v4: Specify how the validation cases should be used

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#18702]
I don't understand the difference between danger and warning and the documentation gives no suggestions about when to use what.

The way I understand forms they have a default style and an error style. I do understand the success style for cases where you have inline validation. But what are the use cases or usage szenarios for danger and warning?

Suggestions:
- Add a sentence or two about when to use danger and when to use warning – the decision should not be a visual but a semantic one, so what is the semantic?

- Ideally: Link to some blog post or book that describes having those two cases as separate styles as a best practice from a user / usability point of few. My go to guy for web form best practices is LukeW. He wrote about best practices for inline validations http://alistapart.com/article/inline-validation-in-web-forms and he wrote a book an many presentations about form in general (http://static.lukew.com/webforms_lukew.pdf and http://www.lukew.com/resources/web_form_design.asp). Unfortunately for bootstrap, there is no indication that it even makes sense to have a warning and danger as two separate indicators. So maybe this is something that should be reduced to one in version 5?

This is the part I am referring to:
http://v4-alpha.getbootstrap.com/components/forms/#validation

> Validation
> Bootstrap includes validation styles for danger, warning, and success states on form controls. To use, add .has-warning, .has-danger, or .has-success to the parent element. Any .form-control-label, .form-control, and .text-help within that element will receive the validation styles.

**Comment by cvrebert** [comment]
`.has-danger` is the much more popular class, and is for typical cases where the user has entered a definitely-invalid value into a form field.

----

Here are two example use-cases for `.has-warning`:
* The user has entered `example@hotmail.co` as their email address. Perhaps they made a typo and meant `@hotmail.com`, or perhaps their email provider really is the much-less-well-known `hotmail.co`.
* The user has entered a weak password in the Password field of an account creation form. While it's good to alert the user to the fact that their password is weak, perhaps the website in question is just Reddit instead of Citibank, so the account's security really isn't terribly important in the grand scheme of things.

In general, AIUI, `.has-warning` is for cases where the input is not definitely invalid, but only *potentially* invalid.

**Comment by Studio384** [comment]
Actually, I find```.has-warning``` quiet useful for passwords fields as in ```.has-danger``` is too weak, ```.has-warning``` is average but good enough and ```.has-success``` as strong. That's how I use it...

**Comment by mdo** [comment]
Coming in #19141.
