### ISSUE TITLE
Hyperlink URLs cause ugly text overlap when printing the docs

### ISSUE THREAD

**Issue by StefanKern** [twbs/bootstrap#18711]
The print view in the preview mode for safari 8 is cut on the right side.
I couldn't reproduce this on any other browser in windows.

The closest bug I found was " https://github.com/twbs/bootstrap/issues/14868 "

[Mac Safari 8.0.3 Getting started · Bootstrap.pdf](https://github.com/twbs/bootstrap/files/73330/Getting.started.Bootstrap.pdf)

[Windows (Chrome 47)-  Getting started · Bootstrap.pdf](https://github.com/twbs/bootstrap/files/73335/Windows-.Getting.started.Bootstrap.pdf)

**Comment by StefanKern** [comment]
Created stackoverflow question to target the same issue (http://stackoverflow.com/questions/34507754/gird-cut-on-safari-8-0-3 )

**Comment by cvrebert** [comment]
Chrome's different rendering is actually due to a known bug in Chrome; see http://getbootstrap.com/getting-started/#support-printing

The text overlapping you're observing is due to the URLs of `<a>`s being included when printing. The buttons and advert on the page in question were not designed to account for this.
We have removed the print styles in question in Bootstrap v4; see b9164b3690d63187e91fcef39cc81aa8c066806d. We cannot remove the styles in Bootstrap v3 due to backward compatibility.

I suppose we could add some special CSS to the docs to account for the URL text (or perhaps disable it).
CC: @mdo

**Comment by StefanKern** [comment]
I see, so that is the reason. I found the .container {width: auto;} fix,
included it and it solved my problem. However I wasn't sure why, and if it
has some side effects.

Definitly add it to the docs, and maybe to the print.css, cause it makes a
bad impression, if the site is not homepage of the framework is not printed
correctly. It kinda destroyes the trust in... Also I was really supprised,
that noboddy had this issue, guess nobody want's to print docs on Chrome
for Mac :D (and I was really anoyed to fix it)
