### ISSUE TITLE
Question: why have glyphicons been dropped?

### ISSUE THREAD

**Issue by Gum-Joe** [twbs/bootstrap#18749]
Hello,
Why glyphicons been dropped?
It was one of the best features of bootstrap and it made understanding a web-page even easier.
If you removed it because no one used it, sorry for opening this pointless issue.
If you removed it because of costs, I can understand that.
However, if you plan to add them in the future, I am happy :+1: 

Thanks in advanced!

**Comment by patrickhlauke** [comment]
icon fonts have issues - see http://blog.cloudfour.com/seriously-dont-use-icon-fonts/, https://speakerdeck.com/ninjanails/death-to-icon-fonts

nothing's stopping you from adding your own icon fonts (or transitioning to using SVG icons instead), and our migration guide will provide resources for that http://v4-alpha.getbootstrap.com/migration/#components

**Comment by Gum-Joe** [comment]
Ok.
No wonder you dropped them, considering they apparently fail often.
I understand that.
Thank you!

**Comment by cvrebert** [comment]
While icon fonts in general do have some issues, I don't recall that being the primary consideration for dropping them. The more pressing concern was that (A) some folks don't need/want icons (B) many folks were using other icon fonts (such as Font Awesome); for folks in these circumstances, Bootstrap including its own icon font led to unnecessary bloat. Plus, dedicated icon font projects could do a better job than us.

Tertiary concerns:
* How to best deal with the paths of assets (such as web fonts) in Less/Sass packages seems to be a bit of an open question. Dropping the icon font means we don't have to wrestle with this.
* Since we merely packaged Glyphicons and aren't font authors ourselves, all we could do regarding reports of bugs in Glyphicons itself was forward them to the author of Glyphicons. (To his great credit, he was fairly responsive, especially considering that it was a free product.)
* There are some misc. issues related to the design of Glyphicons itself and/or interactions with Bootstrap's choice of default font sizes: #13657, #15011

**Comment by Gum-Joe** [comment]
Ok
