### ISSUE TITLE
.control-label has no padding-top on XS screens

### ISSUE THREAD

**Issue by ptijul** [twbs/bootstrap#18765]
Hello,

I've migrated from v3.1.1 to v3.3.6 (generated from Custom module to define my own number of bootstrap grid units). Since now, under 768px the control-label have no more padding-top which they had in.

Comparing the two version I see that now the padding-top is only added like that:
@media (min-width: 768px) {
     .form-horizontal .control-label {
         padding-top: 7px;
          ...
    }
}

So now my form is badly aligned vertically for small devices or when I resize the page to "become a small device".
In the meantime I can only override it in my CSS but I wonder know why this has been done and if this will perhaps be fixed in a future release?

Thanks.

**Comment by cvrebert** [comment]
Please post a JS Fiddle or JS Bin that demonstrates the problem.

**Comment by ptijul** [comment]
Here is the link : https://jsfiddle.net/6ku53tn6/.

Steps to reproduce: 
1. Ensure to see properly the sample form that the label ("Site web") and the value ("http://www.google.com") are properly aligned vertically.
2. Resize the window to become smaller than 768 px.
Observe that the label (with class "control-label") and the value (no classname "control-label") are not aligned properly as the padding-top is not set. 

I'm based on the example http://getbootstrap.com/css/#forms-horizontal but instead of a input control next to the label I have an information text coming from the database. 
For me, the <label> is the static text and a text showing a dynamic value is not a <label>, is that wrong?
That's properly here the problem and I should declare both as <label> with class="control-label", shouldn't I?

**Comment by twbs-lmvtfy** [comment]
Hi @ptijul!

You appear to have posted a live example (https://fiddle.jshell.net/6ku53tn6/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 64, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-2"` is redundant and can be simplified to `class="control-label col-xs-2 col-lg-1"`
* line 65, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-lg-5 col-md-5 col-sm-4 col-xs-4"` is redundant and can be simplified to `class="col-xs-4 col-md-5"`
* line 68, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-2"` is redundant and can be simplified to `class="control-label col-xs-2 col-lg-1"`
* line 69, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-lg-5 col-md-5 col-sm-4 col-xs-4"` is redundant and can be simplified to `class="col-xs-4 col-md-5"`
* line 72, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-2"` is redundant and can be simplified to `class="control-label col-xs-2 col-lg-1"`
* line 73, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-lg-5 col-md-5 col-sm-4 col-xs-4"` is redundant and can be simplified to `class="col-xs-4 col-md-5"`
* line 76, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-2"` is redundant and can be simplified to `class="control-label col-xs-2 col-lg-1"`
* line 77, column 5: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-lg-5 col-md-5 col-sm-4 col-xs-4"` is redundant and can be simplified to `class="col-xs-4 col-md-5"`
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ptijul** [comment]
Here is the updated link : https://jsfiddle.net/6ku53tn6/1/

**Comment by twbs-lmvtfy** [comment]
Hi @ptijul!

You appear to have posted a live example (https://fiddle.jshell.net/6ku53tn6/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ptijul** [comment]
Here is the updated link : https://jsfiddle.net/6ku53tn6/2/
Sorry for the multiple message links. I've fastly converted my code (based on 36 bootstrap units) to a sample code (based on 12 bootstrap units) and so I got Bootlint errors. 
Here should be ok.

**Comment by cvrebert** [comment]
The `padding-top` was added in 1a5fb4ef24f6d1beb71df946fa4781df10eab6e1 to fix #12843. The comments say it was intentionally scoped within a media query.

**Comment by cvrebert** [comment]
Although forcing your form to remain horizontal even on XS screens like you're doing in your example (by using `.col-xs-*` classes) is generally not good practice.

**Comment by ptijul** [comment]
Thanks @cvrebert for your great response!! 
You helped me a lot and you were right: I was not using it properly so now I let the form to be displayed vertically `.col-xs-*` classes but also for `.col-sm-*` classes (as it's a 2 columns form).
My form is a readonly form and I was convinced to display all as text....but finally I display the data information in a label with `form-control`.

For anyone coming with the same problem, I changed from :
`<div class="form-group">
       <label class='control-label col-lg-3 col-md-4 col-sm-6 col-xs-6'>My label</label>
      <div class='col-lg-15 col-md-14 col-sm-12 col-xs-12 '>
          <label class='**form-control-static**'><a href='http://www.google.com' target='_blank'>http://www.google.com</a></label>
      </div>
</div>`

to
`<div class="form-group">
       <label class='control-label col-lg-3 col-md-4'>My label</label>
      <div class='col-lg-15 col-md-14 '>
          <label class='form-control'><a href='http://www.google.com' target='_blank'>http://www.google.com</a></label>
      </div>
</div>`
(The second label, what I call "label-value" has now `.form-control` and no more `form-control-static`.

So now my label and label-value are distinct graphically there is no more problem to have label and label-value one below each other on "sm" and "xs" display. 
In fact, I accept now the standard behavior

=> I close the issue. Thanks again !
