### ISSUE TITLE
Buttons are editable in Microsoft Edge

### ISSUE THREAD

**Issue by riwakawebsitedesigns** [twbs/bootstrap#18800]
Hello I am not sure if any one has come across this but when I am using bootstrap version 3.3.6 in Microsoft Windows 10 edge 

For some reason the buttons are editable? Not sure why?

**Comment by cvrebert** [comment]
@riwakawebsitedesigns Please:
(a) Clarify what you mean by "editable".
(b) Post a JS Bin or JS Fiddle with instructions that demonstrate the problem.

**Comment by riwakawebsitedesigns** [comment]
I have no fiddle.  What I mean by button being editable. Is when I view webpage in Microsoft edge the button name I can change when click on it. It should only be done in editor changing the name. The bootstrap site works fine in Microsoft edge when click on button but not on my localhost project

**Comment by patrickhlauke** [comment]
Without an example that lets us actually see the problem you're experiencing, we can't really help you. And from your description, it sounds like the problem is at your end, with whatever localhost project you're working on (did you put `contenteditable` on your buttons or similar). I suggest asking for help with your project on StackOverflow or similar, as per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by riwakawebsitedesigns** [comment]
I only have contenteditable one div
