### ISSUE TITLE
Use will-change: transform in elements with position: fixed

### ISSUE THREAD

**Issue by saviomd** [twbs/bootstrap#18832]
Doing so prevents unnecessary repaints as explained here:
https://www.youtube.com/watch?v=2vFrZXWiwIc

**Comment by cvrebert** [comment]
We've already tried applying `transform: translate3d(0,0,0)`, which FWICT is an approximate moral equivalent of `will-change: transform`, and ended up having to revert it because of (a) Safari bugs (b) it creates a new stacking context, which is often undesirable.
See https://github.com/twbs/bootstrap/pull/14667 and https://github.com/twbs/bootstrap/pull/13649#issuecomment-57767763

So I don't think we'd be terribly eager to try this.

**Comment by saviomd** [comment]
According to mdn (https://developer.mozilla.org/en/docs/Web/CSS/will-change#Values) it creates a new layer or a new stack, didn't know that..
(my navbar is very simple, so I didn't run into anything strange, but I can see the problems that it can cause to other people).
Ok then.
