### ISSUE TITLE
Hover trigger for popovers doesn't appear to work through data API when using event delegation

### ISSUE THREAD

**Issue by djmattyg007** [twbs/bootstrap#18947]
The subject line pretty much sums it up. You can check out this jsfiddle for a working example: https://jsfiddle.net/7a2emqu4/

If you remove the data-trigger attribute and uncomment the trigger line in the javascript, it works as expected.

**Comment by FLasH3r** [comment]
can confirm it happens on 3.3.5

**Comment by lukeasrodgers** [comment]
I suspect this may be difficult to work around. Since you're using event delegation, i.e. popover elements may be dynamically added and removed from the DOM, how could the plugin know what trigger events to use? It would have to do something like bind a global mouseover listener and then, when the user moused over a given element, determine the actual popover options based on data attributes and potentially bind new listeners on that element.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
