### ISSUE TITLE
Add (sticky) footer component

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19019]
Maybe it's time to add new component for footers / sticky footers into bootstrap 4 out of the box? I can make PR if you agree.

**Comment by cvrebert** [comment]
You mean like http://v4-alpha.getbootstrap.com/examples/sticky-footer/ ?

**Comment by corysimmons** [comment]
That have a flexbox enabled option that isn't a fixed height?

https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by Mevrael** [comment]
@cvrebert yes, sticky footer, base footer class, colors, border-radius, whatever else easily configured using variables.

**Comment by mdo** [comment]
Going to pass on doing that. We have the example, and it'd be nice to have a flexbox version of that eventually, but not adding a new component for that.

**Comment by cvrebert** [comment]
Because of bloat or...?

**Comment by mdo** [comment]
Because it could be done any number of ways and I don't see value in building one particular method into the project. Full or fixed width, rounded or not, attached or spaced away from the viewport, overlaying other content or another pane outside the rest of the content, etc. That kind of stuff is what the examples and extra CSS outside the project are for :).

**Comment by corysimmons** [comment]
I agree with you @mdo 

I got confused and thought the example was a component. :+1:

**Comment by CodeChief** [comment]
At least one out-of-the-box class "sticky-bottom" would be worthwhile to enable a complete solution to be made without hard-coding height. This 60px is highly unlikely to be consistent across all devices and sizes and becomes something which needs special attention and further workarounds should the footer be different on some areas of the site.

In testing I found the bottom padding of the main content was not respected because the overall height margin required to cover the footer was different when the navbar is collapsed. Please forget the things a CSS expert thinks are easy and you are probably right about, to think of the API itself at an architectural non-technical level. Bootstrap should have a solution for all common layouts and controls as standard without having to drop down to CSS overrides and fixed sizes.

For that reason, please re-consider implementing one of the most compatible solutions for sticky footers in the next feature update. People who don't agree can always do their own CSS magic, but that is no reason to block the masses from having a dynamic, simple out-of-the-box solution which works regardless of footer height.
