### ISSUE TITLE
Inconsistent JS file encodings

### ISSUE THREAD

**Issue by idleberg** [twbs/bootstrap#19028]
Not necessarily a bug, but I have noticed the file encoding and MIME types in `scss/` isn't streamlined:

    cd bootstrap/scss/; file -I *
    _alert.scss:                text/x-c++; charset=us-ascii
    _animation.scss:            text/x-c++; charset=us-ascii
    _breadcrumb.scss:           text/plain; charset=us-ascii
    _button-group.scss:         text/x-c++; charset=us-ascii
    _buttons.scss:              text/x-c++; charset=us-ascii

And inside `dist/js/, it looks like this (even though I could imagine *minified* files are meant to be US-ASCII):

    bootstrap.js:     text/x-c++; charset=utf-8
    bootstrap.min.js: text/x-c++; charset=us-ascii

As I said, this is not necessarily a bug, maybe a question of maintaining standards. I only stumbled across this by chance when trying to load a file from `scss/` using `decodeURIComponent()` inside my `$.ajax` success function.

**Comment by cvrebert** [comment]
Thanks for reporting this. Fixed in f2d77b674c4fc6ecaaf56e09dedf8489657b4ad2.
`scrollspy.js` had a Unicode ellipsis in a comment, which made that file and the generated JS files be UTF-8.

As for the MIME types, those are only the `file` command's guesses that it makes using heuristics which are far from perfect. The fact that it guesses wrong doesn't matter much in practice, and more importantly we can't do anything about it on our end.
