### ISSUE TITLE
Example CSS differs from dev CSS

### ISSUE THREAD

**Issue by robertandrews** [twbs/bootstrap#19038]
Pages appear with different formatting depending on Bootstrap 4 CSS URL used.

ie. The page at https://v4-alpha.getbootstrap.com/examples/jumbotron/ (which uses https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css) appears as it should).

But, when I use the same markup with CSS https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css, the jumbotron has far more padding and font tracking is too spacious, for example.

Which should I use? The one on v4-alpha looks right(er).

**Comment by cvrebert** [comment]
Yes, that's to be expected. https://v4-alpha.getbootstrap.com uses the latest tagged release (v4.0.0-alpha.2), whereas the `v4-dev` branch in git is the bleeding-edge code which will eventually result in v4.0.0-alpha.3.
`v4-dev` is the absolute latest version of the code, but if you use it, you'll need to refer to the local docs instead of the hosted docs (https://v4-alpha.getbootstrap.com), since the hosted docs are for a slightly older version of the code.
