### ISSUE TITLE
Duplicate border-color & filter properties in .btn-default's CSS

### ISSUE THREAD

**Issue by lupugabriel1** [twbs/bootstrap#19151]
In [dist/css/bootstrap-theme.css:64](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap-theme.css#L64) for .btn-default there are duplicated CSS rules for filter & border-color :  
 ```
.btn-default {
  text-shadow: 0 1px 0 #fff;
  background-image: -webkit-linear-gradient(top, #fff 0%, #e0e0e0 100%);
  background-image:      -o-linear-gradient(top, #fff 0%, #e0e0e0 100%);
  background-image: -webkit-gradient(linear, left top, left bottom, from(#fff), to(#e0e0e0));
  background-image:         linear-gradient(to bottom, #fff 0%, #e0e0e0 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff', endColorstr='#ffe0e0e0', GradientType=0);
->filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
  background-repeat: repeat-x;
  border-color: #dbdbdb;
->border-color: #ccc;
}
```

**Comment by ameya-pandilwar** [comment]
The duplicate 'border-color' property has been fixed. However, the 'filter' property still remains as it was introduced in this fix - https://github.com/twbs/bootstrap/issues/10620

**Comment by mdo** [comment]
Going to punt as a won't fix. Honestly comes down to a lack of interest, low priority (meaning not a major/breaking bug), and lack of time given the emphasis on v4.

Those overrides—at least for the `border-color` are intentional as the mixins we used in the `theme.less` file didn't cut it for the default button styles. Had to tweak some things to get it looking/feeling better.

**Comment by lupugabriel1** [comment]
Thanks for the effort and feedback !
