### ISSUE TITLE
Question - Any JavaScript features or fix for V4 alpha 3 ?

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#19162]
Hi,

I follow Bootstrap and I see a lot of CSS features or bug fix merged. But nothing about JavaScript and their are a lots of PR waiting for a review.
So my question is alpha 3 only target CSS improvements ?

**Comment by cvrebert** [comment]
> [Does] alpha 3 only target CSS improvements ?

No, there's no such explicit policy. Things merely just-so-happen to have turned out that way thus far.
Personally, I would attribute it to JS generally requiring more review/effort than CSS (JS is a Turing-complete language after all, whereas CSS isn't), and a relative lack of JS manpower/leadership within the Bootstrap Core Team.

**Comment by Johann-S** [comment]
Thank you for your quick answer !
