### ISSUE TITLE
Namespacing *On Customization* of Bootstrap

### ISSUE THREAD

**Issue by machineghost** [twbs/bootstrap#19187]
I understand that you have already rejected namespacing the entire library in this issue: https://github.com/twbs/bootstrap/issues/17474.

While that's a reasonable decision, it's unfortunate for a certain class of developer.  Just because you want to use Bootstrap and have a legacy codebase that doesn't play well with it, that doesn't mean that you use a CSS pre-processor.  Or even if you do, it doesn't mean you want to deal with integrating 3rd party code in to your build process.

However, there's a simple way this could be solved, while still respecting https://github.com/twbs/bootstrap/issues/17474: add a namespace option to the customizer.

The Boostrap customizer can already give me just the grid CSS or just the modal JS.  It can also fill in a bunch of Less variables.  Since it can already do all that, wouldn't it be great if it could also have just one extra input asking for a namespace, and then apply that namespace to the generated file?

**Comment by hebbet** [comment]
afaik the customizer in Browser is currently not planed for v4.

**Comment by dkfiresky** [comment]
@machineghost if you're trying to use bootstrap in your site, it's apparently meaning that you're integrating third-party code into your codebase.

Bootstrap, as originally was developed, should be used as a base for your own styles, so that's the reason why they (bootstrap developers) write the framework by using css pre-processors – it's for you to integrate with bootstrap and build upon it. If you're not using css pre-processors, then you probably should (I assume you want to use bootstrap).

If you wish to use bootstrap prefixed, you can do prefixing on your own, there are no reasons for this feature to be implemented in the framework itself.

**Comment by cvrebert** [comment]
Bootstrap v3 is no longer accepting new features, so this would have to target v4.
But as @hebbet notes, we are dropping the customizer in v4, so there's no version for this could target.
And as @dkfiresky notes, there are third-party tools (e.g. PostCSS) that are capable of doing this namespacing. And I suspect some of the third-party customizers that will inevitably be created for v4 would be open to this feature request.
Therefore, closing this.
