### ISSUE TITLE
What about a bootstrap XML vocabulary ?

### ISSUE THREAD

**Issue by charlycoste** [twbs/bootstrap#19182]
The only problem I have with bootstrap is that it relies on the document-oriented semantic of HTML.

Indeed, when a developer wants to add a navbar, he should write that he wants a navbar, not 3 or 4 embedded `<div>` with many classes and roles.

I've tried once to write an XSLT file to allow me use of XUL vocabulary (`<menubar>`, `<hbox>`, etc.) and transform it to html using bootstrap style. (you have a proof of concept here: http://xul.ccoste.fr/, just have a look to the source code of the page...)

But XUL is deprecated and Bootstrap is evolving too fast so I can't do it on my own in my cave...

What about specifying a vocabulary with bootstrap specific UI components like `<navbar>`, `<jumbotron>`, `<panel>`, and so on...?

I think it could help to make templates a bit more easy to read if we could use something like :

    <tabbox>
      <tabs>
        <tab>Home</tab>
        <tab>Profile</tab>
        <tab>Messages</tab>
        <tab>Settings</tab>
      </tabs>
      <tabpanels>
        <panel>...</panel>
        <panel>...</panel>
        <panel>...</panel>
        <panel>...</panel>
      </tabpanels>
    </tabbox>

Instead of:

    <div>
      
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
      </ul>
      
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">...</div>
        <div role="tabpanel" class="tab-pane" id="profile">...</div>
        <div role="tabpanel" class="tab-pane" id="messages">...</div>
        <div role="tabpanel" class="tab-pane" id="settings">...</div>
      </div>
    </div>

**Comment by cvrebert** [comment]
> Bootstrap is evolving too fast so I can't do it on my own in my cave...

Bootstrap 3 is very stable markup-wise at this point. Bootstrap 4 will settle down and have a stable release eventually, after which it should remain pretty stable for the purposes of your XSLT. So for now I'd simply suggest waiting for a stable release of v4, and only then embarking on writing your XSLT.

---

I doubt the team would be interested in maintaining XSLT ourselves (my sense is that it's a relatively unpopular approach), but it seems like something that could quite reasonably be pursued as a third-party add-on project by interested community members.

While there have been [some experiments with non-standard non-WebComponents custom elements](http://mdo.github.io/mdoml/), I don't think anyone would seriously recommend that approach for production use, particularly given that such HTML would epically fail [validation](https://validator.w3.org/nu/). And it would also fail to fully address the brevity issue, since it'd most likely still require the `role`, `aria-*`, `id`, and `href` attributes in the markup itself, and thus still bear much resemblance to your 2nd "bad"/"verbose" code snippet.

Over the medium/long term, once [Custom Elements become more universally supported](http://caniuse.com/#feat=custom-elements), it would be worth considering adding integrated support for them in Bootstrap itself, which could then allow for HTML approximating your 1st code snippet. But the underlying technology/specs simply don't seem mature enough at this point in time.

CC: @twbs/team for other opinions

**Comment by mdo** [comment]
Yeah, probably not going to happen from us anytime soon :).

**Comment by charlycoste** [comment]
Thank you so much for this feedback, with very interesting comments. I will just add 2 points for information only, if someone see this page later...
Custom elements may be cool but are still very young and not supported by old browsers whereas backward compatibility is my hobby-horse . My goal is not to make the browser read `<navbar>` by itself or even to transform it by XSLT on client side (this is only for dev purpose in my sample), it's more about processing it on the server **before** sending it to the browser. So it could be valid HTML5, xHTML+RDFa or even a newer one.

For instance, on http://xul.ccoste.fr/index.php the answer is just HTML thanks to this script :

    <?php
    $xml = new DOMDocument();
    $xml->load('index.xml');

    $xsl = new DOMDocument;
    $xsl->load('xul-bootstrap.xsl');

    $proc = new XSLTProcessor;
    $proc->importStyleSheet($xsl);
    echo $proc->transformToXML($xml);

By the way, I will follow your advice and wait for Bootstrap v4, then maybe create a third-party project.
Thank you.

**Comment by patrickhlauke** [comment]
> it's more about processing it on the server before sending it to the browser.

I would hazard a guess that the large majority of people using Bootstrap are doing so in environments where they aren't/can't process stuff server-side first. So yes, doing it as a third-party project sounds like the best approach, rather than doing it in core BS.
