### ISSUE TITLE
Breakpoints documentation (em vs px)

### ISSUE THREAD

**Issue by andrewtch** [twbs/bootstrap#19271]
Hi, should the docs be updated? 

Source says that px are used: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L121
And documentation states about em: http://v4-alpha.getbootstrap.com/layout/overview/

**Comment by hebbet** [comment]
that was changed with 4c5ba3e5

**Comment by andrewtch** [comment]
So, the production wasn't yet updated?

**Comment by cvrebert** [comment]
The website is basically only updated when each new release is shipped, to avoid being inconsistent with the release version's code. The v4 site doesn't track the bleeding-edge `v4-dev` branch.
As stated on the v4 website's homepage and footer, the site currently corresponds to v4.0.0-alpha.2.
We switched from em to px shortly after v4.0.0-alpha.2, so the site still uses em.
The site will be updated when alpha 3 (or equivalent) ships.
If you're using the bleeding-edge `v4-dev` branch and want fully accurate docs, you should run the docs locally and consult them instead of the getbootstrap.com hosted docs.
