### ISSUE TITLE
JS inside Modal

### ISSUE THREAD

**Issue by steveb26** [twbs/bootstrap#19290]
I am trying to do something pretty basic as far as I'm concerned, 

I have this script:

```
        <script type="text/javascript">
        $(function() {
    jQuery.noConflict();
            var availableTags = <?php include('acname.php'); ?>;
            $("#department_name").autocomplete({
                source: availableTags,
                autoFocus:true
            });
        });
        </script>
```

and this is the actual line that runs what it needs to for the textbox to have the autocomplete data:

`<input type = "text" id = "department_name" name = "department_name" value = "" size="50" />
`
It works perfectly when outside of the modal but once it is in the popup modal it just fails to autocomplete, any advice here would be greatly appreciated!

Thanks!

**Comment by patrickhlauke** [comment]
Unfortunately we can't help with how-to/support questions such as this one. Suggest you ask on StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

(however, at first glance, I'd say the problem is that the above code needs to be executed once the modal is displayed, rather than on page load which is presumably where it's currently running)
