### ISSUE TITLE
.img-responsive isn't centered when it's smaller than a parent

### ISSUE THREAD

**Issue by ischerbakov** [twbs/bootstrap#19318]

**Comment by ischerbakov** [comment]
=)

**Comment by cvrebert** [comment]
Technically Bootstrap 3's docs don't make any statements about `.img-responsive` implying centering, and we explain how to accomplish centering for such images in the 2nd paragraph of http://getbootstrap.com/css/#images-responsive

Due to backward compatibility, I don't think we can change this in Bootstrap 3. It could be worth considering for Bootstrap 4 though.

@mdo Your thoughts?

**Comment by ischerbakov** [comment]
Yes, I totally agree.  Now I understand.

**Comment by mdo** [comment]
Yup, we've left alignment to be up to folks using Bootstrap. I don't see us changing that up either in v4. The goal is to ensure images don't bust layouts—by constraining them to `max-width: 100%`—and not to prescribe a particular alignment.
