### ISSUE TITLE
button group stops working on resize

### ISSUE THREAD

**Issue by danielok1993** [twbs/bootstrap#19346]
Hello I have added button group to my new website and it seems that two first buttons stop working on smaller screens ? Also if I remove text-center div they all stop working.

http://danielszweda.azurewebsites.net/

Any help would be appreciated.

**Comment by hebbet** [comment]
for support questions please use stackoverflow.

**Comment by patrickhlauke** [comment]
Yes, as per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker support requests should be directed at StackOverflow or similar.

I'll give you a starter though: the buttons don't work because they're overlapped by the sidebar which swallows the clicks.

![untitled-1](https://cloud.githubusercontent.com/assets/895831/13381025/aed2912a-de48-11e5-952e-bad5fcc68249.png)

**Comment by danielok1993** [comment]
I will make sure to post it to stack next time :) Thanks for your help ! :+1:
