### ISSUE TITLE
Bootstrap 4 - alpha

### ISSUE THREAD

**Issue by mmjaeger** [twbs/bootstrap#19403]
hello
is BS 4 ever going to be out of alpha??

**Comment by patrickhlauke** [comment]
yes. when, that's another question (whose answer is "when it's done")

**Comment by calvinf** [comment]
For those observing, how do you recommend we track progress towards "done"?

**Comment by TheBuzzer67** [comment]
Kind of flow chart with future release dates if possible and for the flow of issues, we have a good idea on the pulse tab!

**Comment by isapir** [comment]
15 months later...

**Comment by patrickhlauke** [comment]
@isapir yeah i'm surprised, particularly considering your extensive contributions to the project...

**Comment by isapir** [comment]
All we're asking is for some time frame so that we would know to plan our projects ahead.

I don't think that it is very professional to reply with answers like 
>when, that's another question (whose answer is "when it's done")

And then almost a year and a half later when the project is still in `alpha` be sarcastic about it.

No one is criticizing or complaining about the project, but Bootstrap is a major project on which many developers rely, and it is very legitimate to ask for a time frame so that we can decide whether to plan for `v4` or stick with `v3` or find another solution.

**Comment by rafalp** [comment]
> Bootstrap is a major project on which many developers rely

Well, I guess those developers gotta learn what the trade offs are of relying on the open source project? I mean, thats what professionals would do, instead of, I don't know, relentlessly assaulting group of passionate volunteers trying to find time to maintain most popular open source project on GitHub with gazillion-times answered questions again and again and again? :]

> be sarcastic about it

"Sarcasm is all I got! Sarcasm! And room full of guys who demand timeframes from project that is being worked on by few folk in their (limited) free time!"

**Comment by isapir** [comment]
>relentlessly assaulting group of passionate volunteers trying to find time to maintain most popular open source project on GitHub with gazillion-times answered questions again and again and again?

I found 8 tickets about that in about 18 months (including this one), all pointing to this one.  And the question was not answered gazillion times -- in fact, it wasn't even answered once, as the other tickets point to this one and this one has no answer.

I really don't think that this qualifies as "relentless assaults", but OK -- I will not ask anymore.

**Comment by rafalp** [comment]
> in fact, it wasn't even answered once

Sometimes the lack of answer is the answer. "Hey, when you gonna release?" "Dunno, when its ready?" "Ohhh". Like [this exchange](https://github.com/twbs/bootstrap/issues/22889#issuecomment-310556021) from week ago.
