### ISSUE TITLE
jQuery 3.0 in Bootstrap v4

### ISSUE THREAD

**Issue by accidentalmeme** [twbs/bootstrap#19433]
As the title says, can you add support for jQuery 3.

**Comment by cvrebert** [comment]
Yes, though we probably won't start work on it until jQuery 3 ships a stable release; jQuery 3 is currently still in beta.

**Comment by dmethvin** [comment]
The jQuery 3.0 release candidate should be coming out next week, feel free to mention me in other tickets. Are the tests on master the ones I should be checking against?

**Comment by cvrebert** [comment]
@dmethvin No, the `v4-dev` branch.

**Comment by accidentalmeme** [comment]
Will you start implementing the jQuery 3.0 rc-1 now that it is  out. They say the api should stay the same. Thank you.

**Comment by dmethvin** [comment]
The v4 branch passes all tests with jQuery 3.0.0-rc1 once #19906 is landed. Even that was a unit test issue, nothing failed in the actual v4 code. If you find otherwise and it's due to Bootstrap (not your own code) open a ticket here and ping me in. Note that jQuery Migrate will find many of the issues so be sure to use it in your code.

**Comment by mkurz** [comment]
jQuery 3.0 final has been released.

**Comment by bardiharborow** [comment]
You can temporarily override the version check with this: `<script>$.fn.jquery = "2.2.4";</script>`

**Comment by apiweb** [comment]
The stable version of jQuery 3 was launched, I believe that as the Bootstrap 4 is still in development, it would be interesting to use this latest version.
I did a test only replacing the linked version, and it worked normally.
I think I would have no problem in updating the version.

**Comment by Arcesilas** [comment]
Bootstrap 3.3.6 does not support jQuery 3: at least dropdowns are broken.

**Comment by TheBuzzer67** [comment]
jQuery v3.0 is out, will you join this new version with Bootstrap v46

It seems to be more compatible then any other version! I did switch with v3.0 on some web site and I didn't have compatibility problem!

**Comment by cvrebert** [comment]
X-Ref: #16834

**Comment by cvrebert** [comment]
We have some unit test problems to fix before we can comfortably claim jQuery 3 compatibility: #20182

**Comment by cvrebert** [comment]
Fixed by #20190, #20191, #20198.

**Comment by TheBuzzer67** [comment]
For when the v4.0.0.0-alpha.3??

**Comment by indolering** [comment]
@TheBuzzer67 You can set your package.json/bower.json file to point to the raw v4 repo or monkey patch whatever development version you are using.  The version check is in the first few lines of the minified file.

**Comment by TheBuzzer67** [comment]
Want to know when alpha.3 version will be available on the web site?

And I'd like to follow the evolution of the development, is there a site where we can follow?

**Comment by calvinf** [comment]
The v4.0.0-alpha.3 milestone has 24 open issues right now.  That's the closest thing I've found for tracking status:

https://github.com/twbs/bootstrap/milestones/v4.0.0-alpha.3

**Comment by cvrebert** [comment]
> Want to know when alpha.3 version will be available on the web site?

Please refer to #19403.
But given the number of "duplicate, already fixed in `v4-dev`" issues I'm seeing, we should try to ship it soonish.

> And I'd like to follow the evolution of the development, is there a site where we can follow?

You can follow https://github.com/twbs/bootstrap/tree/v4-dev to see what we're committing.
You can follow http://blog.getbootstrap.com for release announcements.
There's currently no official "this week in Bootstrap 4"-type summaries, if that's what you mean.
