### ISSUE TITLE
Add tables with pinned header row & column when scrolling

### ISSUE THREAD

**Issue by rstegeby** [twbs/bootstrap#19546]
Hi,

I would like to request the functionality to be able to pin the left side and the header and then allow the rest of the table area to be scrollable.

I couldn't find this in the documentation of the bootstrap 4 but it's a very common functionality to have in for example a grid environment such as Excel or similar.

Searched among the issues but couldn't find a relating issue.

**Comment by cvrebert** [comment]
You could always use DataTables: https://datatables.net/extensions/fixedcolumns/ , https://datatables.net/extensions/fixedheader/
They even have a Bootstrap theme these days.

**Comment by mdo** [comment]
Punting on this—no plans for adding it to v4.

**Comment by martenlehmann** [comment]
Why is that a problem? DataTables are not a solution and have nothing in common with Bootstrap. Using this argumentation there shouldn't exist a `.navbar-fixed-top` class today, because there's probably some external project that does the same.

Pinning to the left is quite complicated, pinning to the top is not. Why not focus on top only and add a key feature of mobile platform table presentation from iOS and others to Bootstrap?

**Comment by martenlehmann** [comment]
Actually, since [Sticky Positioning](https://www.w3.org/TR/css3-positioning/#sticky-pos) is part of the CSS3 working draft, we may indeed skip implementation in Bootstrap and hope that browsers will implement this soon. Currently, it's only recent versions of Firefox and Safari that [can handle it](http://caniuse.com/#feat=css-sticky).

**Comment by cvrebert** [comment]
And we already exited the "simulate `position:sticky`" business in v4 by [dropping the Affix plugin](http://v4-alpha.getbootstrap.com/migration/#components). There are polyfills that do a better job and are better maintained.

**Comment by slidenerd** [comment]
Data tables compatibility chart clearly states that you cannot do fixed headers and fixed columns at the same time in case you missed
