### ISSUE TITLE
Adding GUI mirroring feature for Bidi (RTL) users 

### ISSUE THREAD

**Issue by Ashamandi** [twbs/bootstrap#19555]
Hello @mdo, 
I am interesting to add GUI mirroring feature at bootstrap, and following is the approach that I will follow:
(https://cloud.githubusercontent.com/assets/17547411/13808034/d55512ce-eb6c-11e5-99de-b85e489e93f4.jpg).

**Comment by cvrebert** [comment]
RTL support is currently slated for a future minor release after v4.0.0 has a stable release.
It will likely use some tool similar to [rtlcss](https://github.com/MohammadYounes/rtlcss) or [cssjanus](https://github.com/cssjanus/cssjanus) rather than the approach in your screenshot. (Having an RTL variant of every SCSS file sounds too messy.)
For now, please wait until we ship a stable v4.0.0 release. At that point, we'd gladly welcome a pull request that implements a primarily-conversion-tool-based approach to RTL.

**Comment by Ashamandi** [comment]
Hello,
I would like to tell you that adding RTL at v4 now is very important for us as a globalization team at IBM, we have many tasks depending on this feature, so we can help you to do that, we have a time and a team for that.
so we really appreciate if you put your preferable design approach in more details so we could able to create a pull request and start implementation now.

**Comment by cvrebert** [comment]
See also #20075.

**Comment by afattahi54** [comment]
+1

**Comment by emamirazavi** [comment]
+1

**Comment by FMCorz** [comment]
@Ashamandi have you figured out a way to achieve RTL using the approach described in your first comment? We, at Moodle, are interested in this as well.

**Comment by MahdiMajidzadeh** [comment]
As an user who use rtl language, rtl version must be a class that add every where I need use rtl layout, not a fully version rtl that made by some tools

**Comment by cvrebert** [comment]
It should be possible to accomplish such a class-based approach using the tools.

Though there doesn't seem to be obvious consensus in the Web developer community at large about what architectural approach is best for RTL. I've seen various different approaches suggested in past RTL feature request issues.

**Comment by IdanCo** [comment]
Maybe i'm missing out on something, but I've been working on an RTL project for a few days now, and by switching on the ```$enable-flex``` alongside with ```body {direction: rtl;}``` everything works like a charm. I know this recipe isn't IE Minus 40 friendly or something, but I'm just so tired of slaving for old browsers that i simply don't care anymore.

**Comment by MahdiMajidzadeh** [comment]
@idanco , as I know `body {direction: rtl;}` maybe solve a lot but not all

**Comment by Ashamandi** [comment]
Hello @mdo, Can we start in supporting Bootstrap with GUI mirroring feature for RTL users now?

**Comment by amrdarwish1975** [comment]
@cvrebert , 
Issue subject is a basic feature which is blocked since a while now. Me & my colleague @Ashamandi are part of Globalization team@IBM  (Arabic/Bidirectional languages) having several contributions in many other technologies in context of providing Bidi & Arabic support. On the same context other colleagues form Bidi team @IBM (Hebrew/Bidirectional languages) work side by side with us to have full Bidi support (pls refer to PR related for another Bidi feature which in progress now under this link [https://github.com/twbs/bootstrap/pull/21116](https://github.com/twbs/bootstrap/pull/21116))
What I am asking you is to accept to let @Ashamandi open same like above PR to do the GUI mirroring feature. Your kind approval is highly appreciated?

**Comment by parsmizban** [comment]
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck

**Comment by VSG24** [comment]
Any updates on this?

**Comment by Ashamandi** [comment]
Hi @cvrebert  @mdo , Any updates in support RTL mode soon? Many of our work is redundant because of missing RTL at Bootstrap. I know that you are closing discussion in this issue till releasing v4 but you don`t set any date for that and we want to participate in adding such an important feature and then planning our time based on your plan.

**Comment by parsmizban** [comment]
@Ashamandi ,
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy

**Comment by Johann-S** [comment]
@Ashamandi as cvrebert said, RTL support will arrive when we had released a stable version of Bootstrap

**Comment by amrdarwish1975** [comment]
@Johann-S 
I am leading @Ashamandi in mail subject issue. Both of us are IBM opens source contributors. Regardless of issue subject, the expectation is to have a "Release Plan", at least on quarterly basis, including dates. The question is: What is the "Planned Date" for such stable version? If you do not have the answer, kindly advise the contact for the "Release Manager"?

**Comment by mdo** [comment]
There's no release plan for v4 or a RTL feature, no planned dates for either, and no release manager other than myself. For now this feature is addressed with third party tools.
