### ISSUE TITLE
missing responsive screen size variables

### ISSUE THREAD

**Issue by craigmichaelmartin** [twbs/bootstrap#19561]
The [migration docs](http://v4-alpha.getbootstrap.com/migration/#responsive-utilities) indicate that the variables `screen-sm-min`, `screen-sm-max`, etc should be used, but I can't seem to find them :P 

If this is confirmed, I would be happy to make a PR!

**Comment by cvrebert** [comment]
As noted in another section of the migration docs, v4 now uses Sass maps instead of those variables; see 2nd-to-last bullet in https://github.com/twbs/bootstrap/blob/v4-dev/docs/migration.md#grid-system
But it looks like the section your're referring to hasn't yet been updated to reflect this. A PR would be welcomed.

**Comment by mdo** [comment]
Addressed in #19567 it seems.
