### ISSUE TITLE
jspm: downloads only "dist" dir

### ISSUE THREAD

**Issue by mychalvlcek** [twbs/bootstrap#19592]
[v4] i am not able to use sass sources with jspm package manager. How its possible to achieve that or is it possible to add another src directory to the current package.json (jspm section)?

**Comment by cvrebert** [comment]
It's not clear to me if/how jspm is supposed to work with Sass.
@guybedford Would you be able to offer us any guidance?

**Comment by VojtechKlos** [comment]
@cvrebert there is a configuration in bootstrap's package.json which tells jspm to only download specific files

`"jspm: {
   files: {
        "css": "...",
        "js": "....",
        "fonts": "...."
    }
}"`

it would suffice to add a sass source folder into the config, or at least that's what i think

**Comment by guybedford** [comment]
This is because jspm 0.16 will use the published release archive for Bootstrap.

I'd suggest trying jspm 0.17 here. In this version release archive downloads from GitHub are deprecated, and you get the whole repo.

**Comment by VojtechKlos** [comment]
@guybedford just installed jspm 0.17 and when i try `jspm install bootstrap@4.0.0-alpha.2` it still only downloads css and js folders

**Comment by guybedford** [comment]
@VojtechKlos right, I missed that this was a v4 issue specifically. As you noted version 3 gets the whole repo in jspm 0.16. So for this Bootstrap 4 version, the override added at https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%404.0.0-alpha.2.json is applying here, which is why you're just getting those files.

If we want to target a change to the override, there are changes we can do that are non-breaking, but altering the `directories.lib` value is a breaking change to the override that would be need to be set for the major release.

**Comment by VojtechKlos** [comment]
thanks, now i get it. would you be able to provide me some guidance in what steps do i need to take to make bootstrap v4 sass working with jspm 0.17? I would appreciate it very much much, thank you in advance.

**Comment by guybedford** [comment]
@VojtechKlos sorry for the delay here... I think the best we can hope for is to catch the Bootstrap 4.0.0 stable release, and deprecate the `directories.lib` setting in the package.json override when this happens, as prerelease to stable can get away with some breaking changes. So we can prepare for that now by creating an override for the 4.0.0 version - I've gone ahead and set that up at https://github.com/jspm/registry/commit/664dd34a9ab0c4a7ab24b5ddeadac3463f9b8c61.

**Comment by mdo** [comment]
Closing as I don't think there's something here for us to address? Please holler if that's not the case <3.
