### ISSUE TITLE
Drop IE9 and IE10 in Bootstrap v4

### ISSUE THREAD

**Issue by fatihhayri** [twbs/bootstrap#19607]
Bootstrap v4 drop IE9 and IE10 

http://gs.statcounter.com/ last 3 months 

http://gs.statcounter.com/#all-browser_version_partially_combined-ww-monthly-201512-201602-bar

**Comment by cvrebert** [comment]
X-Ref: #16310, #13944

**Comment by cvrebert** [comment]
I'm doubtful that the Core Team would be eager to deal with the backlash that removing IE9 support would cause (much less IE10). Wait for Bootstrap v5, probably. :smile: 
CC: @mdo

**Comment by cvrebert** [comment]
So, I had to rejigger the [graph to only Desktop browsers](http://gs.statcounter.com/#desktop-browser_version_partially_combined-ww-monthly-201512-201602-bar) to get it to break out numbers for IE9 & IE10 specifically, but after doing that:
* IE9: 1.37%
* IE10: 1.35%

Whereas [according to NetMarketShare](https://cloud.githubusercontent.com/assets/419884/14029564/fe353ddc-f1bf-11e5-9e77-01dca3b74bf8.png):
* IE9: 6.00%
* IE10: 3.56%

(Cue debate over the accuracy/representativeness/relevance of either of these data sources...)

**Comment by patrickhlauke** [comment]
Indeed, removing support for 9 and 10 seems a bit premature at this point in time, I'd say.

**Comment by alvipeo** [comment]
Don't just yet!

**Comment by mdo** [comment]
Yeah, not going to.

**Comment by fatihhayri** [comment]
Bootstrap v4 still in alpha version. That these rates until the stable version will fall below 1%.

The differences are (IE9 and IE10 IE 11):

http://caniuse.com/#compare=ie+9,ie+10,ie+11

**Comment by patrickhlauke** [comment]
even 1% on a site that gets tens of thousands of hits equates to people not being able to see/use your stuff. that's a decision that I think is quite opinionated for a framework to take.

being more specific, which specific aspects of support for IE 9/10 are people here so concerned about that they want to drop them?

**Comment by alvipeo** [comment]
Look, I have pretty big corporate clients that use IE 9 (not even 10). I don't care if it's 0.00001% - these people do pay money! Until Microsoft owns enterprise IE9 and 10 must be supported.

**Comment by tkrotoff** [comment]
> even 1%



> I don't care if it's 0.00001% - these people do pay money!

According to your reflexion IE8 should be supported by v4 since it's still > 1% (IE6 too with 0.30%?).

[StatCounter march-april 2016](http://gs.statcounter.com/#desktop-browser_version_partially_combined-ww-monthly-201603-201604-bar):
- IE10: 0.88%
- IE9: 0.94%
- IE8: 1.39%

[NetMarketShare march-april 2016](https://cloud.githubusercontent.com/assets/643434/15340070/ddcd8516-1c87-11e6-8f6d-02a96a8d942b.png):
- IE10: 4.38%
- IE9: 3.48%
- IE8: 6.77%
- IE7: 0.60%
- IE6: 0.30%

=> IE8 is more common than IE9 and IE10 !!

<br>

Rationales:
- IE9 and IE10 are less used than IE8
- By the time v4 is final, their market share will be even lower
- v3 supports IE9 and IE10
- Testing and fixing IE9 takes time
- Prevents from using [some features](http://caniuse.com/#compare=ie+9,ie+10,ie+11)
- v4 lifetime will probably be 3 years like v3 (released in 2013-08), will IE9 and IE10 be relevant in 2017-2019?

If supporting IE9 does not take time nor causes feature restrictions then it's fine but I doubt that.

<br>

IE9 forecast using 1 year of NetMarketShare data:

![trend](https://cloud.githubusercontent.com/assets/643434/15341696/810264c4-1c90-11e6-9a0f-85b793188597.png)
