### ISSUE TITLE
"Incompatible units" error when defining breakpoints in `rem` instead of `px`

### ISSUE THREAD

**Issue by wesm87** [twbs/bootstrap#19619]
Here's the error that I'm getting:

```
bower_components/bootstrap/scss/mixins/_breakpoints.scss
Error: Incompatible units: 'px' and 'rem'.
        on line 38 of bower_components/bootstrap/scss/mixins/_breakpoints.scss
>>   @return if($next, breakpoint-min($next, $breakpoints) - 1px, null);
   --------------------^
```

As a temporary fix I copied the main `bootstrap.scss` file into my project and commented out this line:

`@import 'bootstrap/scss/utilities-responsive';`

That being said, given the switch to `rem` / `em` values everywhere else in v4 I expected this to work. Adding some basic unit checks to the offending function seems to fix the issue:

```
@function breakpoint-max($name, $breakpoints: $grid-breakpoints) {
  $next: breakpoint-next($name, $breakpoints);

  @if not $next {
    @return null;
  }

  $max: breakpoint-min($next, $breakpoints);

  // Support breakpoints defined as `rem` values
  @if unit($max) == 'rem' {
    @return $max - 0.0625rem;
  }

  @if unit($max) == 'px' {
    @return $max - 1px;
  }

  @return null;
}
```

**Comment by glebm** [comment]
Why do you want to define breakpoints in rem? Using rem for breakpoints has issues such as off by one px errors and surprising behaviour on root font size change.

**Comment by cvrebert** [comment]
> `@return $max - 0.0625rem;`

Converting `rem` to `px` like that without taking the `<body>`'s `font-size` into account isn't valid AFAIK.
(And perhaps we/you shouldn't expect to be able to know what that `font-size` is ahead of time; see #19460)

----

Our conclusion from #17403 and friends (notably #17070) is that using `em`s in media queries isn't the way to go. It'd also make the breakpoint math you're referring to even fiddlier than what you're suggesting; see #18414 & #17388.

So since we don't use or recommend `em`/`rem`, I don't see much reason to try to support it here.

**Comment by glebm** [comment]
+1, the other caveat is that in media queries the root font size is not effective, i.e. the breakpoint width is converted at 16px by the browser always no matter what the html font size is.

**Comment by mdo** [comment]
Yup, what @cvrebert and @glebm said. <3
