### ISSUE TITLE
'Collapse' makes some menus transparent.

### ISSUE THREAD

**Issue by ClockMan** [twbs/bootstrap#19636]
Bug is in Collapse.prototype.hide.
<code>
Instead of:
 var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')
        .trigger('hidden.bs.collapse')
    }

Should be:
 var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')[dimension]('')
        .trigger('hidden.bs.collapse')
    }
</code>
Or 'Collapse' will leave ul with style="height: 0px", and that's wrong.

Issue visible here:
https://colorlib.com/polygon/metis/

Reproduction:
1. Click on 'Forms' (collapse in)
2. Click on 'Forms' (collapse)
3. Move cursor above 'Forms' and into right side, shown menu (right side) will be transparent when it shouldn't be.

**Comment by RyanZim** [comment]
Thanks for reporting this.

Could you provide a reduced test case (JSBin/JSFiddle)?

**Comment by ClockMan** [comment]
do you want also french fries for that ?

--
No,
Setting dimension (height) to "" works for me.

**Comment by patrickhlauke** [comment]
> do you want also french fries for that ?

do you want to lose that attitude please? a reduced test case is necessary to see if the problem is indeed one relating to bootstrap itself, or the way in which you've used it (perhaps wrongly, perhaps with errors in some other code/style/js). otherwise i'm afraid we're not going to be able to dissect your specific site to see what's causing the issue.
