### ISSUE TITLE
Can't change color of navbar item text

### ISSUE THREAD

**Issue by thomasfurst99** [twbs/bootstrap#19686]
When using new sass file overriding nav-item color, nothing happens.

**Comment by cvrebert** [comment]
Please post step-by-step instructions for how to reproduce the problem.

**Comment by thomasfurst99** [comment]
I created this demo.scss file:

    $darkred: #AE2632;
    $lighttext: #FFFFFF;

    .bg-darkred {
        background-color: $darkred;
    
        .nav-link {
            color: $lighttext;
            text-decoration: none;
        }
    }

than applied it to the HTML:

    <nav class="navbar navbar-light bg-faded bg-darkred">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Item 1</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link" href="#">Item 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Item 3</a>
            </li>
        </ul>
    </nav>

**Comment by cvrebert** [comment]
@thomasfurst99 And how was that SCSS file included into the Bootstrap build (or vice versa)?

**Comment by thomasfurst99** [comment]
Used as additive .css file

**Comment by cvrebert** [comment]
We offer various `$navbar-*-color` variables you can override when compiling Bootstrap to control the navbar colors.
If you want to override the colors using custom CSS instead, then that's a how-to question rather than a bug report, and thus outside the scope of this issue tracker. See https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md#using-the-issue-tracker for our bug tracker policy and for links to community StackOverflow, IRC, and Slack forums which would be more appropriate for such a how-to question.
