### ISSUE TITLE
Why are we nullifying the iOS tap highlight?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#19709]
I tend to agree with the commenter in https://github.com/twbs/bootstrap/commit/85db846b651842444d374f8e54f3f362ca18d08e#diff-ef2c30c269c7f0b514325e65587e24deR13
The [tap highlight](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color) seems like a nice affordance. Why does Reboot kill it?
CC: @mdo @patrickhlauke

**Comment by patrickhlauke** [comment]
Adding https://developers.google.com/web/fundamentals/design-and-ui/input/touch/active-states?hl=en for more reference.

Generally, I believe some developers suppress the webkit tap highlight because it's only half-arsed. You can only set a single color, which is then applied as a semitransparent color block over your links/controls when tapped. It does not provide any control over foreground/background color or other factors, and - for anything other than links to other pages, e.g. in-page controls - it can look rather odd / out of place with the rest of the visual styling.

As iOS requires extra JS to trick/enable proper `:active` support, though, I'm not sure what would be the lesser evil here. Provide proper affordance for most/all browsers using `:active` where necessary (and do the iOS magic dance of adding empty `touchstart` handlers...which is just urgh), or leave it all as is (suppressing the tap highlight).

**Comment by cvrebert** [comment]
At any rate, the [code comment for it in Reboot](https://github.com/twbs/bootstrap/blob/6d8cf0fb48002ff0c88bb1629e3cbd5c23c38a85/scss/_reboot.scss#L67) ought to explain *why* it's being done, not just what's being done.

**Comment by gabrielecirulli** [comment]
Just noticed the issue, thanks for filing. It was an oversight on my part not to do this sooner. 

To add my 2 cents to the discussion (hoping it's still relevant), I believe that however basic the tap highlight is or feels, it's important to have it merely because of an expectation the users have built of how websites look and feel on mobile: when you tap a link, you get a tap highlight.

Due to the nature of these widespread affordances, removing or circumventing them gives a very uncanny feeling to the experience. _Something_ will feel off to the user, which as a result may impact their experience with the application or site.

That, in my opinion, would be a very good reason to keep the tap highlight, or at most make the removal optional.

I do agree that the tap highlight is often unnecessary in sites that try to mimic the behaviour of native applications, but that might only be a fraction of the users, so I'm not sure it's safe to impact everyone else with this decision.

**Comment by mdo** [comment]
PR coming in #22964.

**Comment by patrickhlauke** [comment]
Commented over on the PR, but probably more relevant here:  how does this affect in-page controls, like dropdown menu triggers? Does it leave them weirdly highlighted? If so, I'd tend to actually say we should leave the suppression as is, OR be very surgical about where we enable it/disable it. Because otherwise these controls may visually suggest to users that they're somehow "toggled" or disabled or whatever, which gets very confusing

**Comment by patrickhlauke** [comment]
see my late comment over on the PR https://github.com/twbs/bootstrap/pull/22964#pullrequestreview-86015844

i *think* it may be best to close this issue/PR and revisit at a later date, giving some more consistently thought out explicit `:active` styles

**Comment by XhmikosR** [comment]
Closing since the PR has been closed.
