### ISSUE TITLE
Combined HTML5Shiv and RespondJS libraries via CDN

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#19767]
JSdeliver.net supports combining libraries so for IE8 we could replace: 
```
https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js
https://oss.maxcdn.com/respond/1.4.2/respond.min.js
```
with just:
`https://cdn.jsdelivr.net/g/html5shiv@3.7.3,respond@1.4.2`

Will save a HTTP request and make the code slimmer. :-)

**Comment by RomainSauvaire** [comment]
Dear Coliff,

Since the arise of HTTP/2, it is no more recommended to "save" HTTP requests on same domain. Here is an in-depth article explaining why and how : https://rmurphey.com/blog/2015/11/25/building-for-http2

So my advice here is to continue having two separated calls and allow the developpers to merge them if they don't [want to support HTTP/2](http://caniuse.com/#feat=http2)

**Comment by cvrebert** [comment]
Thanks, but we'll pass on this.
