### ISSUE TITLE
[v4] npm module scss usability

### ISSUE THREAD

**Issue by langpavel** [twbs/bootstrap#19795]
I'm going mad with this. **What I can use bootstrap npm package v4 with webpack style loader?**

There are so many answers on google like `bootstrap-loader` or `bootstrap-sass-loader` but nothing really fits.

I've installed bootstrap with npm: `npm install --save bootstrap@4.0.0-alpha.2` ind wish to use scss files.
How can I use files from `scss` directory?

Bootstrap.scss starts with:
```css
@import "variables";
@import "mixins";

// Reset and dependencies
@import "normalize";
@import "print";

// Core CSS
@import "reboot";
@import "type";
...
```
but really, trere are files like <tt>**_**_somefile_**.scss**</tt> or `mixins`, it's directory!

I'm using `react-starter-kit` but this is not important.

Why there are <tt>@import</tt> which ommits preceding underscore and ignoring `scss` suffix?

**Comment by langpavel** [comment]
Oh, now I see, `mixins` is directory, but `_mixins.scss` is also a file! It's even more confusing!

**Comment by langpavel** [comment]
My webpack `module/loaders` configuration is:
```js
      {
        test: /\.scss$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: DEBUG,

            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',

            // CSS Nano http://cssnano.co/options/
            minimize: !DEBUG,
          })}`,
          'postcss-loader?parser=postcss-scss',
        ],
      },
```

Note that `isomorphic-style-loader` is same as `style-loader`

**Comment by F1shbone** [comment]
When you import a file you don't need to include the file extension .scss (.sass). Sass is smart and will figure it out for you. You'll feed the bootstrap.scss file into your preprocessor and import all partial files (The underscore lets Sass know that the file is only a partial file). So the `@import "mixins"` references the _mixins.scss file (which in turn imports all mixins from the mixins folder).

See http://sass-lang.com/guide for details

**Comment by cvrebert** [comment]
> [How] I can use bootstrap npm package v4 with webpack style loader?

I don't believe anyone on the Bootstrap Core Team has experience with webpack, so we're unfortunately unable to give you webpack-specific guidance. How-to questions like that [aren't really appropriate for this bug tracker](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md#using-the-issue-tracker) and would be more suitable for [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community) instead.

If there's some sort of metadata that webpack needs that we lack, we'd be happy to consider adding more metadata; just let us know.

> How can I use files from `scss` directory?

Compile `scss/bootstrap.scss` with a [Sass compiler](http://sass-lang.com) and then run [Autoprefixer](https://github.com/postcss/autoprefixer) over the resulting CSS. If you want the vendor prefixing to match [our browser support policy](http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#supported-browsers), you should use [our Autoprefixer configuration.](https://github.com/twbs/bootstrap/blob/v4-dev/grunt/autoprefixer-settings.js)

If you're customizing Bootstrap, then copy `scss/bootstrap.scss`, edit it appropriately, and compile & autoprefix it as described above.

If you're trying to use only individual components of Bootstrap, you just `@import` the relevant files in your own Sass file, and then compile & autoprefix your Sass file as described above.

> Why there are `@import` which omits preceding underscore and ignoring scss suffix?

Because that's how imports work in SCSS.

**Comment by langpavel** [comment]
Thank you guys, It made me almost insane yesterday :smile:
