### ISSUE TITLE
Does bootstrap depend on jQuery?

### ISSUE THREAD

**Issue by trusktr** [twbs/bootstrap#19809]
If so, then there could be a bug in the fact that it's not listed in it's NPM dependencies: https://www.npmjs.com/package/bootstrap

**Comment by yasinkocak** [comment]
https://www.npmjs.com/package/jquery ?

**Comment by F1shbone** [comment]
Could be an error in the npm package, Bootstrap requires jQuery (see http://getbootstrap.com/getting-started/#whats-included)

**Comment by DaSchTour** [comment]
It's an error in package.json
jQuery isn't listed there.
I guess this is a conceptional problem when using bower and npm side by side.
package.json at the moment only contains dependecies that are needed to build Bootstrap. Therefore jQuery isn't needed. In bower.json only jquery is listed as a dependecie because it is needed for productiv usage.

**Comment by trusktr** [comment]
Thanks for confirming! Placing it there will be nice for people who use NPm exclusively (with Browserify, Webpack, and others).

**Comment by mdo** [comment]
Listed as a dependency in v4.

**Comment by dermeister0** [comment]
> Listed as a dependency in v4.

Bootstrap 4.1.0 has 0 dependencies again. I had to add jquery and popper.js manually.

**Comment by wolfy1339** [comment]
They are listed as `peerDependenies`, because you don't need them to use Bootstrap without the JS.
That behavior is intended. NPM should warn you to install them
