### ISSUE TITLE
v4: How to make use of rem?

### ISSUE THREAD

**Issue by bkgunby** [twbs/bootstrap#19800]
Is the rem addition an opt in feature? Or do I have the wrong idea on how to use it? 

This was my first time working with relative units, and it took me a while to notice that I had to change `font-size-root` to `100%` from `16px`. Now whenever I change my browser's font size, the website changes as well. Is this the intended way to use it?

**Comment by rafalp** [comment]
Yes, when you change browser's font size, you change value of 1rem, thus changing sizes specified in CSS.

**Comment by bkgunby** [comment]
Gotcha, so it's being used to reset to the same font size across browsers. This didn't come to mind since I assumed the default was `16px`, but I see that it's not always the case.

But what about being able to increase the browser's font size to take advantage of relative units? Maybe there are some more advantages I'm not familiar with, but that's the one that immediately sprung to mind when using em/rem. 

I guess there was already a discussion on this, and the benefits of the consistent `font-size-root` outweighed the ability to change relative to the browser's font size. hmm

**Comment by bkgunby** [comment]
I guess what I want to ask is why move to `rem` if this were the case? Again I'm not very knowledgeable on this topic, so I'm probably missing something. But if our only goal is to make every default browser font size to be `16px`, couldn't we have just used `px` instead of `rem`? I thought the whole point of using relative units is because we don't know the browser defaults or user font size settings.

**Comment by rafalp** [comment]
In Bootstrap before v4 dimensions were either specified on their own or as multiples/fractions of other dimensions.

This made things hairy when people were customising `@font-size-base`, as some things changed their sizes while others didn't, things that fit neatly in smaller breakpoints suddenlly required resizing, other things visual rythm changed because content scaled up/down, but margins/paddings didn't, etc ect. 

Untangling this knot turned out to be time consuming, so idea for v4 was to make all sizes relative to one global size, so you have single "point of origin" when changing base size for your design, and rem provides that.

**Comment by bkgunby** [comment]
Ah that makes sense now. And you could adjust the base font size for different viewports as well. Thanks.
