### ISSUE TITLE
Comment: Bootstrap 4 should have gone pure Flexbox.

### ISSUE THREAD

**Issue by dukedougal** [twbs/bootstrap#19901]
I think it's a pity Bootstrap 4 didn't go "pure Flexbox".  

Seems to me that Bootstrap 3 was just fine for previous generation and with the major version bump it was a chance to shift entirely to Flexbox.  Now all those compatibility headaches will carry over for the next 8 years along with all the complexity of having two major approaches under one roof, when at the same time browsers rapidly leave "the old way" behind.

People who needed compatibility would have been just fine with Bootstrap 3.

In a way it weakens Bootstrap's dominance and leaves the door open for pure Flexbox solutions.

**Comment by mdo** [comment]
You're entitled to your opinion :).

**Comment by Starsam80** [comment]
It's because of support in browsers, see http://caniuse.com/#feat=flexbox for details. In fact, the docs say this as well at https://v4-alpha.getbootstrap.com/getting-started/flexbox/#browser-support. If you have users that use up to date browsers, then you can enable it by adding `$enable-flex: true` to your `scss/_custom.scss` (or something like that)
