### ISSUE TITLE
Button.js adds disabled class which Bootlint criticizes, rightly so?

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#19961]
I originally reported this as a Bootlint issue at https://github.com/twbs/bootlint/issues/379 but now I am not sure whether Bootlint isn't actually correct and `button.js` of Bootstrap (v3) is doing something useless here.

What happens is that Button.js is adding the disabled class to a button in it's loading state (using `.button('loading')`) while the disabled attribute would suffice. The code where it happens is at [button.js, line 44](https://github.com/twbs/bootstrap/blob/master/js/button.js#L44) and it triggers the warning W016 in Bootlint (_"Using the `.disabled` class on a `<button>` or `<input>` only changes the appearance of the element. It doesn't prevent the user from interacting with the element (for example, clicking on it or focusing it). If you want to truly disable the element, use the `disabled` attribute instead."_). The Bootlint code for this warning can be found at [bootlint.js, line 578](https://github.com/twbs/bootlint/blob/master/src/bootlint.js#L578) (note how line 579 just checks for whether the disabled class is set for the input/button, it does not care about the disabled attribute, also the warning says _"…**instead**"_).

So who is right, Bootstrap or Bootlint?

**Comment by cvrebert** [comment]
Adding the `.disabled` class in addition to the `disabled` attribute is indeed useless for non-`<a>` buttons.
While it is pointless, I don't believe it has any negative side-effects.
We probably can't fix this in v3 due to backward compatibility concerns. (If someone on Core Team disagrees, feel free to reopen this.)
v4 doesn't suffer from this bug since the relevant feature of the buttons.js plugin has been removed from it: https://github.com/twbs/bootstrap/blob/v4-dev/docs/migration.md#buttons
