### ISSUE TITLE
Modals not working in Safari or demo on http://getbootstrap.com/javascript/#modals

### ISSUE THREAD

**Issue by designerwhocodes** [twbs/bootstrap#19974]
Hi,

I'm trying to troubleshoot why modals aren't working in Safari v9 desktop. Works fine in Chrome, Firefox. Not even the demo Currently v3.3.6 on http://getbootstrap.com/javascript/#modals is working in Safari v9 Desktop. Any ideas?

**Comment by cvrebert** [comment]
Define "not working". It works fine on my MacBook. Probably something wrong with your specific machine, otherwise this issue would have 10 duplicates. (Safari Extensions perhaps?) For troubleshooting help, ask on StackOverflow, Slack, or IRC; see https://github.com/twbs/bootstrap/blob/master/README.md#community for links.

**Comment by designerwhocodes** [comment]
no special config in safari. not working meaning doesn't load on clicking the element or the version we have to load on page load.

**Comment by designerwhocodes** [comment]
figured it out. thanks for your time.

**Comment by cvrebert** [comment]
Out of curiosity, are you able to share what the cause turned out to be?

**Comment by designerwhocodes** [comment]
Huge lack of sleep leading to forgetting to re-enable JS in dev mode... haha! hurray!

**Comment by designerwhocodes** [comment]
close

**Comment by designerwhocodes** [comment]
Close designerwhocoes/bootstrap#19974
