### ISSUE TITLE
Support for text-only items in navbar

### ISSUE THREAD

**Issue by AaronLS** [twbs/bootstrap#20116]
I have the same issue shown here:
https://github.com/twbs/bootstrap/issues/11735

The conclusion stated was that navbar-text is not meant for the li items in a list.
".navbar-text is used directly inside div class="navbar-collapse""
"The .navbar-text is not meant for placement in nav components."

Therefore, when you need an li that is not a link, but is just text, we don't have a class as far as I know that can be applied to ensure it aligns properly in both non-collapsed and collapsed.

It seemed like navbar-text is part way there, but doesn't align properly in collapsed mode.  A new navitem-text or something similar would be great to handle this scenario.

**Comment by cvrebert** [comment]
For stability/compatibility reasons, and in order to focus on Bootstrap v4, we're no longer making any further changes to the navbar in Bootstrap v3. [We're also no longer adding new classes to Bootstrap v3 in general.](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#feature-requests)

We're in the process of overhauling the navbar component in Bootstrap v4 to address several shortcomings of v3's navbar. I will leave this issue open but retarget it for v4.
