### ISSUE TITLE
Release date for Bootstrap 4

### ISSUE THREAD

**Issue by cristian-sima** [twbs/bootstrap#20146]
This is not an issue in the sense of code, but it is a question.

The question is when the stable version 4 of Bootstrap will be released.

**Comment by patrickhlauke** [comment]
The usual answer is "when it's ready". But seriously, there's no set timeframe at this point, I'm afraid.

**Comment by cvrebert** [comment]
Duplicate of #19403.

**Comment by jofran73** [comment]
I would also really appreciate to see at least some kind of updated roadmap.
For my next project, I'll be using angular 2 and asp.net core, both of which have reached rc2. I'd like to choose an ui-framework that intends to support bootstrap 4, i.e. Kendo-UI from Telerik.
However, bs4 remained in alpha 2 since december, which makes me hestitate to include it into my set of tools.
I do recognize the work being done and I really appreciate it. I'm just saying it would be helpful.

**Comment by takuhii** [comment]
Isn't this something to do with conflicting dependencies?

**Comment by takuhii** [comment]
Sorry wrong thread!!

**Comment by ryanlin1986** [comment]
We are also about to rewrite some port of our project code base to use most promise technologies such as bootstrap 4 to replace jquery ui( since the update cadance of jquery ui is really slow,kind of out of date)
