### ISSUE TITLE
Missing doc for tag

### ISSUE THREAD

**Issue by bsr203** [twbs/bootstrap#20148]
I see the doc suggests[ pill tags are replacement for badges](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tags.scss#L43) here. But, don't see any docs along with other components.
http://v4-alpha.getbootstrap.com/components/label/
Is this an oversight?

**Comment by bsr203** [comment]
This may answer it. Last release alpha.2 is in Dec 8, which is the current doc based on.

https://github.com/twbs/bootstrap/pull/19157

**Comment by cvrebert** [comment]
They're documented: https://github.com/twbs/bootstrap/blob/v4-dev/docs/components/tag.md#pill-tags
v4-alpha.getbootstrap.com hosts the docs for the latest release version, currently v4.0.0-alpha.2 (see the footer of every page).
There have been many commits to the `v4-dev` git branch subsequent to the v4.0.0-alpha.2 release.
If you're using the bleeding-edge `v4-dev` branch, then for accurate and up-to-date docs, you should run+browse the docs locally (as described in http://v4-alpha.getbootstrap.com/getting-started/build-tools/#local-documentation ) instead of consulting v4-alpha.getbootstrap.com
We don't currently host any `v4-dev` docs because it would be a moving target.

**Comment by bsr203** [comment]
thanks @cvrebert. I found the same just before you posted the answer. sorry, I missed that. Will do run the doc locally.
