### ISSUE TITLE
Consider adding what-input as an (optional?) dependency

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20157]
i.e. https://github.com/ten1seven/what-input
Refs https://github.com/twbs/bootstrap/pull/19708#issuecomment-208103768
Refs https://github.com/twbs/bootstrap/issues/19968#issuecomment-221686064

This would allow us to robustly prevent sticky `:hover` styles and prevent non-keyboard interaction from triggering `:focus` on `<button>`s etc.

@patrickhlauke Any other arguments/details you'd like to present?

**Comment by patrickhlauke** [comment]
nothing more other than to say that this will also allow to solve long-standing visual annoyances like not having focus indication on dropdowns in navbars (which we avoid due to their current sticky/unsightly look when using mouse) http://v4-alpha.getbootstrap.com/components/navs/#tabs-with-dropdowns

(oh, and a courtesy ping to @ten1seven to alert him of this)

**Comment by cvrebert** [comment]
CC: @twbs/team for discussion

**Comment by hnrch02** [comment]
Sounds interesting, not sure it's worth the added weight though. I didn't follow the past discussions. Is this more of a nice-to-have or a big accessibility issue?

My main concern is that with this our JS dependencies would grow to be jQuery, Tether and What Input, correct? That's three dependencies devs would need to include individually which seems pretty inconvenient.

**Comment by hnrch02** [comment]
Maybe we need a JS bundle that includes jQuery + Tether and possibly this? But that would be a different discussion.

**Comment by hnrch02** [comment]
Also, (sorry for the posts in quick succession) I don't like the thought of this being optional. If it is an accessibility issue then we should enforce this. And if it's not a accessibility issue then what's the point of including it from a dev's perspective. Just another dependency to include for rather little return.

**Comment by patrickhlauke** [comment]
the main issue is: for sighted keyboard users, we really must provide a visual indication of focus. we do in some cases (and then get bugs filed about styles being "sticky" on mobile and after mouse clicks), and we don't provide focus indication in others (like dropdown triggers). integrating what-input, or something like it (heck, it could be forked/rewritten to be core, rather than an external dependency) will allow to solve both problems without half-baked half-solutions. and no, i wouldn't make it optional.

**Comment by mdo** [comment]
Closing as stale.
