### ISSUE TITLE
Modal scroll by touchpad/trackpad does not work on IE11

### ISSUE THREAD

**Issue by jhyle** [twbs/bootstrap#20216]
In IE 11 scrolling a modal that is higher than the viewport does not work. It does work when using the up and down keys. Is it reproducable by me with Windows 7 / IE 11 on the modal live example at http://getbootstrap.com/javascript/#modals.

**Comment by cvrebert** [comment]
Unable to reproduce in Win 7 IE11 on Sauce Labs:
https://saucelabs.com/beta/tests/35711af9201a43e0a4346aced99fbbb5/watch

**Comment by jhyle** [comment]
Thank you for testing. As the video looked like a mouse wheel was used, I tested that on my laptop. Result: Mouse wheel works (as in the video), touchpad does not. Sorry for not being detailed enough.

**Comment by cvrebert** [comment]
I think touchpads just emit [`wheel`](https://developer.mozilla.org/en-US/docs/Web/Events/wheel) events like mice do, so the difference you're describing would presumably be due to a bug in either IE11 itself or your touchpad drivers. Assuming that's the case, there's unlikely to be a way to workaround it on our end.

@twbs/team (or anyone else reading this): Anyone happen to have a Windows laptop handy (with Win 7 if possible)?

**Comment by cvrebert** [comment]
@patrickhlauke Do you happen to have a Windows laptop w/ IE11?

**Comment by alexlamsl** [comment]
FWIW, I've tried on my Win7/IE11 laptop with (Synaptics) touchpad, and the scrolling seems to work as expected.

**Comment by cvrebert** [comment]
Going to assume the problem is specific to @jhyle's particular setup then.
We'll keep an eye out for any future reports of the same problem though.
