### ISSUE TITLE
Consider loading CSS files asynchronously 

### ISSUE THREAD

**Issue by TheTannerRyan** [twbs/bootstrap#20334]
CSS files should be loaded asynchronously to speed up page loading.

Standard way:

`<link href="../dist/css/bootstrap.min.css" rel="stylesheet">`

Asynchronous way (with non-javascript fallback):

`<script>!function(e){"use strict";var t=function(t,n,o){function i(e){return s.body?e():void setTimeout(function(){i(e)})}function r(){a.addEventListener&&a.removeEventListener("load",r),a.media=o||"all"}var d,s=e.document,a=s.createElement("link");if(n)d=n;else{var l=(s.body||s.getElementsByTagName("head")[0]).childNodes;d=l[l.length-1]}var f=s.styleSheets;a.rel="stylesheet",a.href=t,a.media="only x",i(function(){d.parentNode.insertBefore(a,n?d:d.nextSibling)});var u=function(e){for(var t=a.href,n=f.length;n--;)if(f[n].href===t)return e();setTimeout(function(){u(e)})};return a.addEventListener&&a.addEventListener("load",r),a.onloadcssdefined=u,u(r),a};"undefined"!=typeof exports?exports.loadCSS=t:e.loadCSS=t}("undefined"!=typeof global?global:this),loadCSS("../dist/css/bootstrap.min.css");</script><noscript><link href="../dist/css/bootstrap.min.css" rel="stylesheet"></noscript>`

**Comment by cvrebert** [comment]
Not sure that's worth the ugliness and increased difficulty of understanding.

**Comment by tomlutzenberger** [comment]
How about just using the `async` atrribute in the `<link ...>` ?

**Comment by Alanaktion** [comment]
@tomlutzenberger The `async` attribute isn't supported by link tags.

I'm not sure there's an advantage to loading Bootstrap's CSS asynchronously, since this would allow a faster page render, but without the scaffolding or anything, so the page will look quite broken until it loads anyway. You generally only want to asynchronously load extra styles that effect the page less, ideally below the fold.

**Comment by mdo** [comment]
Punting on this.
