### ISSUE TITLE
Consider adding a fix for fragment IDs on pages with position:fixed navbars

### ISSUE THREAD

**Issue by idleberg** [twbs/bootstrap#20344]
One of the most annoying bits when using sticky navbars is the need to add fixes for anchor links on that page. Whenever one clicks on an anchor link, the target will be hidden below the navbar. This happens _every time_, whether you're using Bootstrap or not.

I know you guys are reluctant on adding additional libraries and I generally think that's a good policy. Yet, I thought addressing the problem mentioned above could be a feature welcome by many users – at least those who prefer working with sticky navbars, if not all of them.

One script that addresses this is [sticky-pagination-fixer](https://github.com/murtaugh/sticky-pagination-fixer), but more importantly its `README` describes the problem in detail.

Screenshots nicked from the mentioned `README`:

![a diagram of a normal pagination event](https://github.com/murtaugh/sticky-pagination-fixer/blob/master/demo-assets/img/figure-1.png?raw=true)
_Fig 1: Normal navbar_

![a diagram of a pagination event with a sticky header](https://github.com/murtaugh/sticky-pagination-fixer/blob/master/demo-assets/img/figure-2.png?raw=true)
_Fig 2: Sticky navbar_

**Comment by tomlutzenberger** [comment]
I don't think there's a solution that would be dynamic and abstract enough. Because not every sticky navbar/header is the same height. This would mean to introduce an extra variable (e.g. $navbar-height).

But what if navbar(s) and the header are not combined but some individual elements? In this case you need 2 variables and calculate them to get the needed offset.

The script/library you mentioned could be a solution. But not everyone can or wants to use Javascript.

**Comment by mdo** [comment]
Yeah, it's come up a handful of times before and we're not going to be writing anything for it. Would love to see community options for this instead.
