### ISSUE TITLE
This is a bug in card-deck?

### ISSUE THREAD

**Issue by mikeandersun** [twbs/bootstrap#20460]
Why this [sample](http://www.quackit.com/html/html_editors/scratchpad/preview.cfm?example=/bootstrap/bootstrap_4/tutorial/bootstrap_4_cards_card_deck) have horizontal scroll?

**Comment by tomlutzenberger** [comment]
Can reproduce on Chrome v52, Ubuntu 14.04.
Bootlint says "no errors".

The reason seems to be that `.card-deck-wrapper` has -20px margin on both sides, while the `.container` has 15px padding on both sides. This means that the wrapper overflows 5px on each side which results in a horizontal scrollbar.

I tried a `max-width: 100%` on the wrapper but it messes up the grid :confused:

**Comment by cvrebert** [comment]
Duplicate of #19883, FWICT.
