### ISSUE TITLE
Bootstrap v4 stability

### ISSUE THREAD

**Issue by eronaeon** [twbs/bootstrap#20461]
I am fully aware that is too generic and this may not be the convenient place to ask and I apologize for that. Is Bootstrap v4 current state (i.e. alpha 3) is stable enough to start a production project? Since there is no roadmap for the final stable version, I can't understand how stable the current version is. I would deeply like to get rid of Bootstrap v3 and start using v4. The first alpha has been there for a year now. So I need to know from contributors or developers how they really feel about the current state of stability for a production project. Thank you for your patience!

**Comment by andyrichardson** [comment]
I use alpha 2 on my website with no issues. That being said, if something were to go wrong, you would have to explain to your client that you used a technology labelled as being in 'alpha' on their website. I'm not sure how that would go down.

**Comment by judetucker** [comment]
@eronaeon alpha doesn't necessarily mean unstable. I have been using alpha.2 in production since January with very limited problems. Really the only thing to keep in mind is when upgrading that things  tend to change pretty radically while in alpha stage. Perfect example is when we upgraded from alpha.2 to alpha.3, we had to change all of our `labels` to `tags` and figure out why all of the stuff that used to be centered, wasn't anymore. But other than that, it was fine.

Finally, an issue ticket is not the best place to discuss this type of thing. I recommend you close this issue and move this conversation to [Stack Overflow](http://stackoverflow.com/questions/tagged/bootstrap-4).

**Comment by acshef** [comment]
I believe this is partly why Bootstrap adheres to the [Semantic Versioning](http://semver.org/) methodology. Any changes that are backwards-compatible (and don't require any inspection on your part) would be a PATCH, aka `__.__.XX`

Semantic versioning helps users/clients of Bootstrap know *how* the changes will affect their workflow. It seems the Bootstrap team have chosen to use pre-release notation specifically because there is NO GUARANTEE about any sort of compatibility. Indeed, looking at the [SemVer Specs](semantic-versioning-specification-semver) reveals the following about pre-release versions:
> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

**Comment by cvrebert** [comment]
We're in alpha. Make of that what you will. 😄
Feel free to continue discussing here with your fellow community members.
But since this isn't a bug or feature request, I'm marking it as closed to keep the issue tracker tidy.
