### ISSUE TITLE
Why Bootstrap forces display: x on .visible-{size} classes?

### ISSUE THREAD

**Issue by darkogj** [twbs/bootstrap#20509]
I don't quite understand why Bootstrap does this, why not have a simple .visible-{size} class which won't apply the display: block/inline/inline-block? Why have 3 separate .visible classes for each display type?

**Comment by cvrebert** [comment]
> which won't apply the display: block/inline/inline-block?

I don't quite know what you mean by that.

Anyway, there are 3 sets of classes because we have no way of magically knowing which `display` value (block/inline/inline-block) is the right one to apply in any given situation. So the developer, who is in a position to know the appropriate value, needs to select the appropriate corresponding class.

In v4, we've reworked the visibility classes so that only `.hidden-*` classes exist, thus sidestepping the problem (see http://v4-alpha.getbootstrap.com/migration/#responsive-utilities ) since they never declare any non-`none` `display` values. When the viewport size is such the element should be shown, the `.hidden-*` class's media query simply no longer applies, allowing the original `display` value to apply, thus showing the element.

**Comment by cvrebert** [comment]
Closing since Bootstrap v3 is in maintenance mode and no longer accepting new features (such as hypothetical additional visible/hidden classes) anyway.
