### ISSUE TITLE
[Firefox] Retuning non-object value by iterator.next() will throw

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#20518]
https://www.fxsitecompat.com/en-CA/docs/2016/retuning-non-object-value-by-iterator-next-will-throw/

**Comment by cvrebert** [comment]
Doesn't affect us.

**Comment by idliuyang** [comment]
Sorry,I deleted.thank you for your propeting message.发自网易邮箱大师
            On 08/15/2016 12:28, Chris Rebert wrote:Doesn't affect us.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/twbs/bootstrap","title":"twbs/bootstrap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/twbs/bootstrap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cvrebert in #20518: Doesn't affect us."}],"action":{"name":"View Issue","url":"https://github.com/twbs/bootstrap/issues/20518#issuecomment-239727240"}}}
