### ISSUE TITLE
.table-reflow on XS screen

### ISSUE THREAD

**Issue by cristian-sima** [twbs/bootstrap#20510]
The code is this

``` html
         <table className="table table-reflow table-striped">
            <thead>
              <tr>
                <th>Cod de identificare fiscală</th>
                <th>Număr Registrul Comerțului</th>
                <th>Denumire</th>
                <th>Nume administrator</th>
                <th>Calitate administrator</th>
              </tr>
            </thead>
            <tbody>
              <tr scope="row">
                <td>{Cif}</td>
                <td>{Registration}</td>
                <td>{Name}</td>
                <td>{AdministratorName}</td>
                <td>{AdministratorQuality}</td>
              </tr>
            </tbody>
          </table>
```

It is ok on big screens:

![image](https://cloud.githubusercontent.com/assets/12199042/17622402/db3554b4-60a2-11e6-9486-9ce98c2d8286.png)

But on `XS` screen, the output is:

![image](https://cloud.githubusercontent.com/assets/12199042/17622409/e4ac7cac-60a2-11e6-9574-b78679365ae0.png)

Hmm.. the visual output is not great, because for a long list I do not understand what to which corresponds. I tried to wrap the table in a `table-responsive`, but it is the same output.

A workaround is to wrap the table in a `table-responsive` and to **set the table width to a fix value** (in this case 400px) and the output is much nicer

![image](https://cloud.githubusercontent.com/assets/12199042/17622481/58594a7c-60a3-11e6-8e2c-c4c522616695.png)

Any idea to make it working without the workaround for `xs` screens?

**Comment by Drakenhart** [comment]
@cristian-sima 

My first thought is "wow that's a LOT of white space around the table on the smaller screen". So my first mental response would be to try reducing the over all outside padding around the table on those much smaller screens? 

My second thought is a less avory one, as I like my titles (as a designer) the way you have them now. But for space considerations, maybe have the '<th>' content wrap so longer titles fold under themselves visually?

My third thought may not be doable without javascript or something to rearrange the table so that the '<th>' has it's '<td>' under it. This is not as good an option as it requires re-writing the DOM, and we need to be sure that aspects of the site will still display properly if javascript is turned off (accessibility needs).

Thoughts?

**Comment by cvrebert** [comment]
Doesn't seem like a bug to me. Sounds like you just don't like the result of the reflow in this case (so I would simply advise not using .table-reflow), but it looks reasonable to me and I don't see a feasible pure-CSS alternative.
CC: @mdo

**Comment by mdo** [comment]
Going to be dropping the reflow table entirely, so closing this out.

I spent some time trying to get this to work in the most flexible of situations, but it falls apart really quickly. Since we're turning *rows* into *columns*, we cannot equally size the cells from one column into another column. So if you have complex or variable length content across cells, your table will be janky.

**Comment by cristian-sima** [comment]
Hope next version is out soon... just hoping
