### ISSUE TITLE
Grid cells overlap when different col-xx are applied

### ISSUE THREAD

**Issue by justdmitry** [twbs/bootstrap#20559]
I have two cells in a row, one with `col-sm-8 col-md-6` and second with `col-md-6` only. I expect second cell be full-width on `sm` screen.

But both tested browsers (FF 48.0 and Chrome 52) show one cell over another on sm-sized page.

![screenshot](https://cloud.githubusercontent.com/assets/3540597/17863779/d26f3a1c-68a3-11e6-84e8-b3a12fa3071f.png)

Html source:

```html
<!DOCTYPE html>
<html class="no-js" lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css">
</head>
<body>
    <br/>
    <div class="container">
        <div class="row">
            <div id="div1" class="col-sm-8 col-md-6" style="border:solid 2px red; color: red;">div 1</div>
            <div id="div2" class="         col-md-6" style="border:solid thin green; color:green; padding: 1ex;">div 2</div>
        </div>
    </div>
</body>
</html>
```

(thick border for div1 and padding to div2 are added for better visual demonstration only, cells are overlapping without them too)

I can solve this problem by adding `col-sm-12` to div2, but... is this a feature or a bug?

**Comment by mdo** [comment]
This is working as intended, provided you're using the default grid and not our flexbox grid. Columns at each breakpoint are floated, and without something to explicitly clear that, our rows are expecting more columns to fill in that space (e.g., with a `sm-8`, we'd expect a `sm-4` or equivalent).

Otherwise this behaves just like any other floated content—everything around it will wrap. To fix it, I'd suggest adding the `col-sm-12`.

Hope that helps!

**Comment by ryantheleach** [comment]
I am also experiencing this issue on 3.
http://stackoverflow.com/questions/42969468/bootstrap-large-column-overlay-medium
Did I miss somewhere in the docutmentation stating that you needed to "fully/over" define each element with col-xs-12 col-md-6 ? i thought that col-md-6 automatically implied col-xs-12?
