### ISSUE TITLE
Custom checkbox/radio focus outline misplaced in Firefox

### ISSUE THREAD

**Issue by Macsch15** [twbs/bootstrap#20586]
Custom checkbox on "focus" state:
![2016-08-26_16-18-00](https://cloud.githubusercontent.com/assets/1592053/18009024/71360760-6ba2-11e6-96b7-6cff8b8b84db.png)

Windows 10 x64 (1607)
Firefox 48.0.2
Bootstrap 4 Alpha 3

In *-webkit browsers is fine.

PS: This issue is also in Radios
![2016-08-26_16-45-00](https://cloud.githubusercontent.com/assets/1592053/18009448/3738b394-6ba4-11e6-8c7a-3b62e4b4c090.png)

**Comment by bardiharborow** [comment]
Interestingly, I get no `:focus` border at all on `Mac 10.11.5 Firefox 49.0b7`, but it works perfectly on `Mac 10.11.5 Chrome 53.0.2785.80`.

**Comment by mdo** [comment]
In Edge and IE11 I'm seeing this as well, and it's due to some aggressive rounding of rem unit values there. Funnily enough there's that PR about the percentages and rounding in IE11, but never saw an issue there. This is the first time I'm seeing overzealous rounding.

Rather than try to deal with that, I'm moving to pixel units for this shadow/focus style. It's not infinitely scalable, but should get the job done without the side effects.
