### ISSUE TITLE
Wrong position of tooltip arrow when 'constraints' is used

### ISSUE THREAD

**Issue by WitoTV** [twbs/bootstrap#20685]
[I have not seen a similar issue so I made a new one.]   

**Bootstrap 4.0.0-alpha.3 was used for this.**   
I was trying to add a tooltip to the side of the page but I found out that sometimes when tooltips content is too wide it goes out of the page, so I used 'constraints' to move it back inside but now I see that tooltip arrow always stays at the center ot the tooltip.   
I'm not sure it this is a bug or I'm just missing something.   
Tested on OSX El Capitan 10.11.6

- Firefox 48.0

- Safari 9.1.2

- Chrome 52.0.2743.116 (64-bit)

**Example: [JSBin](https://jsbin.com/nixuvuyuqu/3/edit?html,css,js,output)**

_IDEA:_   
This can be hot-fixed by adding a tooltip arrow as ::after for element on which tooltip is assigned

**Comment by cvrebert** [comment]
Tooltip positioning is handled by https://github.com/HubSpot/tether
Please file a bug with them.

**Comment by timfish** [comment]
This bug is not in tether, its due to the way bootstrap draws the arrow. @WitoTV was saying that when constraints are used, the arrow doesn't line up with the target element. This has nothing to do with tether as tether is putting the tooltip in the right place. The arrow is in the wrong place as bootstrap has it fixed to 50% of the width.
