### ISSUE TITLE
.nav-tabs doesn't look good in smaller screens

### ISSUE THREAD

**Issue by bigomega** [twbs/bootstrap#20726]
The styling could be improved for smaller screen sizes.

< SCREENSHOT >

![image](https://cloud.githubusercontent.com/assets/2320747/18549334/7e9b4c02-7b6b-11e6-8a61-689a816ab330.png)

**Comment by Ap110460** [comment]
Android

**Comment by Ap110460** [comment]
Close

**Comment by tomlutzenberger** [comment]
You will almost never be able (maybe through icons instead of text) to display a large amount of tabs properly on mobile devices. In the agency I work, we did the following: 
On mobile devices (Breakpoint XS, sometimes SM) we hide the tabs and display a dropdown instead. By clicking one of those dropdown items, the tab-show-function is triggered and display the corresponding content.

**Comment by mdo** [comment]
Yup, you're bet best is to customize those things for your own use case and ensure that folks don't have a dozen tabs to look through on their mobile devices. I might have some ideas on how to improve these, but can't dive into them unto after v4 ships.
