### ISSUE TITLE
On close, modals should return focus to launching element

### ISSUE THREAD

**Issue by maruthikumars** [twbs/bootstrap#20788]
I've a page with Two buttons "Goto" and "Previous".

When I click "previous" button a modal will open. This modal will have some text followed by two buttons
Yes and No.

when we click"No", the focus should return to "Previous".

```
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">

<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Yes</button>
        <button type="button" class="btn btn-primary">No</button>
 </div>
```

do I need to add anything else here. to use bootstrap api? 

Note: when I click Previous button it is using bootstrap api. When I click on No in modal I couldn't able to debug the bootstrap code.

**Comment by cvrebert** [comment]
> On close, modals should return focus to launching element

Our modals already do that by default. It just sounds like your markup (or JS?) isn't entirely correct.

I also note that the HTML in your snippet is missing a `</button>` close tag (and presumably the word "Previous" within the button).

> when we click "No", the focus should return to "Previous".

Then you will need to either add `data-dismiss="modal"` to your "No" button (like you already did with the "Yes" button) or call [the `.modal('hide')` method](http://getbootstrap.com/javascript/#modal-hide) in your `click` event handler for the button.

> do I need to add anything else here. to use bootstrap api?

Questions about how to use Bootstrap (as opposed to feature requests or bug reports) should be addressed to [our community forums](https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community) (e.g. StackOverflow) rather than this bug tracker. Thank you for your understanding.

**Comment by russplaysguitar** [comment]
I had the same problem. It appears that Bootstrap only returns focus to the launching element if your modal is defined via data-attributes. If you create and open the model via JS, focus is not returned to the launching element. I do not know if this is by design. 

I think that is line that restores focus in v4: https://github.com/twbs/bootstrap/blob/3f01134031b15a934d5e233bb26a407a7e05492b/js/src/modal.js#L506 

Tested version: Bootstrap 3.3.6.

**Comment by surya-ptg** [comment]
I have the same type of problem, but in  my requirement I have a button. when i clicks on it will open a fly-out(Div) with some dynamic data and close button. when i click on close button i should get the focus on the button which i clicked to open the fly-out(Div).

Can someone help me out in resolving this...
