### ISSUE TITLE
Migrate Travis build from npm shrinkwrap to Yarn

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20884]
https://github.com/yarnpkg/yarn

Sounds 100x better than our homegrown npm-shrinkwrap-based scheme.

**Comment by bardiharborow** [comment]
Very open to being convinced, but from first glance it seems like a npm fork with fairly limited benefits for the added complexity. Would you care to elaborate on the reasoning?

**Comment by kkirsche** [comment]
For me, I think the key benefit that Yarn offers is that by design, it is deterministic in it's builds, which is my understanding of the purpose of the npm-shrinkwrap system. Based on it's configuration (https://yarnpkg.com/en/docs/configuration) I'm not sure that I know what added complexity this brings. Would you be able to elaborate on the perceived complexity that Yarn would add?

**Comment by bardiharborow** [comment]
@kkirsche, my main concerns are around the added dependency that would need to be downloaded to the Travis VM every build and the general feeling that forking/rewriting what is effectively just npm fragments the community and is another io.js waiting to happen. Fixing issues with npm-shrinkwrap upstream would be a much better way to go.

**Comment by XhmikosR** [comment]
@bardiharborow I think we can close this since we use npm 5.
