### ISSUE TITLE
Bootstrap carousel blank slide issue iphone

### ISSUE THREAD

**Issue by nihad21** [twbs/bootstrap#20929]
While using bootstrap carousel a white blank screen appears after sliding on iPhone and other iOS devices. It is working perfectly fine on other platforms. 1 issue I realized that iPhone does not support transition effect. 

I will be glad if anyone will try to help me out.

Cheers!

**Comment by mdo** [comment]
Have a link to a reduced test case showing this?

**Comment by mdo** [comment]
Closing out since we never heard back.

**Comment by lukatiks** [comment]
I think I do, please reopen.

http://jsbin.com/miwakekefo

When viewing using Safari on iOS 10.2 the image sliding in is usually empty and is only shown after the transition is complete.

Note that the jsbin is a simplified Carousel example from the docs, but the docs example does not exhibit this behaviour. That's because the example loads holder.js library which repeatedly calls requestAnimationFrame like this:

```
function visibilityCheck() {
    // ...
    setTimeout(function () {
        global.requestAnimationFrame(visibilityCheck);
    }, 10);
}

// ...
visibilityCheck();
```

Adding such code to the jsbin code fixes the problem.

**Comment by GeneLM** [comment]
I am in the same boat with this.  First image transitions left leaving blank slide, next image appears without transition.

**Comment by RaffaeleT** [comment]
Mine is showing same behaviour too: the outgoing image slides out with a transition, leaving a white board and then the next image appears without transition.

**Comment by pawan163** [comment]
I tried this and it worked for me:

.carousel-inner > .item {
    -webkit-backface-visibility: visible;
            backface-visibility: visible;
}

Feedback are welcome.
