### ISSUE TITLE
Bower installs miss the CSS

### ISSUE THREAD

**Issue by ekkis** [twbs/bootstrap#20992]
I've installed bootstrap using Bower and use grunt-bower-install, which automatically inserts references in my html files from the `bower.json`.  The inclusion fails on account of Bootstrap's "main" declaration, which contains the following:

```
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],

```

which is missing the CSS.  this definition should fix that problem:

```
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js",
    "dist/css/bootstrap.min.css"
  ],
```

and I'm guessing that including the bootstrap-theme file might be desirable as well.  I'm happy to create a pull request if I have a reasonable expectation that it will be accepted

**Comment by fchiumeo** [comment]
see #16663

**Comment by mdo** [comment]
This won't be changed, that's not how the Bower spec requests to be used and v3 isn't going to see any more changes like this.

**Comment by ekkis** [comment]
@mdo, @fchiumeo, goodness I had no idea so much discussion had gone on with regards to this topic.  after reading it I'm left with 2 questions:

1) it's suggested I can address the issue temporarily with the "overrides" keyword, but that is not defined in the bower.json spec, so where am I supposed to put it?

2) I presume this is the official spec: https://github.com/bower/spec/blob/master/json.md - and if so, it shows the "main" as having both a `.js` and a `.scss` - so what would be wrong with my suggestion?

thanks for addressing my questions.  I'm one of the developers that got left stranded from the referenced turf war and just trying to make my way home

**Comment by ekkis** [comment]
from reading this: http://blog.getbootstrap.com/2015/06/15/bootstrap-3-3-5-released/#wiredep-and-bower I see it goes in my project's `bower.json` but I don't see that keyword in the spec#70, which is the latest... ??

**Comment by ekkis** [comment]
all right.  I tried the overrides but it doesn't work... bower v1.7.9, grunt v 0.4.5, grunt-bower-install v 1.6.0 - though I'm not sure what is broken now because I'm not getting anything for the  or  containers.  sigh.  it's late.  maybe tomorrow I figure it out

**Comment by publicocean0** [comment]
you can use https://github.com/publicocean0/bindep

**Comment by ekkis** [comment]
thanks mate but stick with `grunt-bower-install`.  swapping tools often just leads to more hair-pulling for other reasons

**Comment by publicocean0** [comment]
I can understand . I swapped to bindep because I m working on complex project with many bower components and in many cases I couldn't automatically inject because bower.json has a too much simplified structure . In many cases for example there are JavaScript plugins having a optional part in a secondary file I won't inject , or I want inject just i a specific case . In other case there are plugins for making a specific thing but It contains  many features not necessary for my needs so I m loading huge files for any Reason. In other cases the plugin inject a default CSS but I want embedded a personalized version so I need to skip a specific file . This not flexible way to work force to multiply plugins doing the same thing instead to reuse it with your target.

**Comment by ekkis** [comment]
well, I figured out how to override a package's bower.json sections so I've been able to include optional components and swap out files as I need or remove files being included.  frankly there needs to be a better approach to how packages declare the assets they offer and how developers consume them.  the Bower spec needs rethinking

**Comment by ekkis** [comment]
and I also think that Bootstrap should be more accommodating to its developers.  refusing to make a small change, especially a harmless one, on the basis that it isn't canonical to the Bower spec doesn't help me use the module

**Comment by publicocean0** [comment]
Bindep extends bower json definition as you told ... in more complex assets . Bower is designed badly For my opinion bootstrap instead give a correct definition . Just enprovement possible in bootstrap is not to pass to CSS but to permitting to use preprocessor for building CSS passing parameters in the HTML block so we can load just parts useful for specific project  parameters directly in the HTML .bindep permits it. If in my project I use just 30 percent of bootstrap CSS and JavaScript why  to include all? In addition  bootstrap might enprove javascript modules because contains too many limits I worked for example with popover and if I use a popover over another don't work , if I use in a static position div don't work , if I want colour dinamically background I can't.  . Bindep define sectons in json as  resources and modules in which I can defines a child embedded bower subcomponebt I can include or not in the main core just writing bootstrap( popover )

**Comment by ekkis** [comment]
all right.  you've convinced me.  I've put bindep in my TODO list

**Comment by publicocean0** [comment]
Cool ah ah
