### ISSUE TITLE
Column Count not working on alpha 5

### ISSUE THREAD

**Issue by esfomeado** [twbs/bootstrap#21053]
After upgrading my code to alpha5 the column count for cards didn't work as expected.
In alpha4:
https://jsfiddle.net/efsjbptn/

In alpha5:
https://jsfiddle.net/11r184v9/

It should show 7 cards but is only showing 4.

Tested in chrome v54

**Comment by mdo** [comment]
Super weird. This works fine in Safari, but not Chrome. Messing around in inspector, changing the `.card` back to `display: block;` fixes the issue in Chrome. However, that'll likely cause some issues we've fixed in the past to come back. Will dig in more soon.

(As a note to my future self, this likely needs to make use of `break-inside: avoid`.)

**Comment by dobozysaurus** [comment]
I pulled Chrome 55.0.2883.75 this morning, and it looks to be working there (it renders identically in alpha 4 and alpha 5). Possibly related to this bug: https://codereview.chromium.org/2395683002.

**Comment by mdo** [comment]
Sadly I don't think I can fix this. For some reason, Chrome wants to see these cards get `display: block;`, but as soon as you do that and have uneven heights across these columns, you'll run into rendering problems with cut off cards.

My suggestion for you is to use the grid layout here. I'm adding better card styles and docs in #21403, to be merged shortly, that may help.
