### ISSUE TITLE
Button above carousel with float right appears inside carousel

### ISSUE THREAD

**Issue by jakefb** [twbs/bootstrap#21126]
I have a button Inside a p tag with float-xs-right above a carousel. The button gets display displayed inside the carousel, and is not clickable.

Is this possible to fix? Thanks

Here's the code https://jsfiddle.net/nwsmsmzn/

**Comment by hruship** [comment]
Hi @jakefb 

I have found the issue is with the float. The carousel is occupying the whole space which includes the button and creates the issue of overlapping. 

Applying **clear: both** or **display: inline-block** to the carousel div, will clear the issue and makes your button clickable. 

Ref: https://jsfiddle.net/nwsmsmzn/1/

Regards

**Comment by mdo** [comment]
What @hruship said :).
