### ISSUE TITLE
Inconsistency on floating badge on .list-group-item

### ISSUE THREAD

**Issue by j0an** [twbs/bootstrap#21137]
When I'm trying to float an badgeon a .list-group-item (in this case into a `.card`) the badge only float adding a viewport modifier `.float-xs-right` and not with the plain `.float-right`

Here an example.
https://jsfiddle.net/8aLskrzy/3/

edit:
i'm using `4.0.0-alpha.5`

**Comment by j0an** [comment]
I detected that the bug occurs where `$enable-flex: true` because `float` inside a `flex` 🤔

**Comment by lhirales** [comment]
According to the [documentation](https://v4-alpha.getbootstrap.com/migration/) .float-right has been removed because it is redudant to .float-xs-right.

> Utilities
Added .float-{xs,sm,md,lg,xl}-{left,right,none} classes for responsive floats and removed .pull-left and .pull-right since they’re redundant to .float-xs-left and .float-xs-right.

**Comment by ArunHub** [comment]
@j0an - And also there is no class called .float-right . @lhirales is right

**Comment by mdo** [comment]
`.float-right` is back in `v4-dev`, but this isn't reflected on the hosted docs as we haven't done a release since those changes were made. @j0an's comment is accurate—you'll need to switch from a float to a flex-based implementation. The docs in `v4-dev` branch include a special callout for moving from the default layouts to flexbox.

From the `list-group.md` docs page:

```
## Badge

Add badges to any list group item to show unread counts, activity, etc.

{% example html %}
<ul class="list-group">
  <li class="list-group-item">
    <span class="badge badge-default badge-pill float-right">14</span>
    Cras justo odio
  </li>
  <li class="list-group-item">
    <span class="badge badge-default badge-pill float-right">2</span>
    Dapibus ac facilisis in
  </li>
  <li class="list-group-item">
    <span class="badge badge-default badge-pill float-right">1</span>
    Morbi leo risus
  </li>
</ul>
{% endexample %}

When in flexbox mode, you'll need to rearrange the contents of your list group items. To replicate the right-aligned badges as shown above, use the following example's code. Note the [`flex-items-xs-between` utility class]({{ site.baseurl }}/layout/flexbox-grid/#horizontal-alignment), the badge's placement, and the lack of a float utility on the badges.

{% highlight html %}
<ul class="list-group">
  <li class="list-group-item flex-items-xs-between">
    Cras justo odio
    <span class="badge badge-default badge-pill">14</span>
  </li>
  <li class="list-group-item flex-items-xs-between">
    Dapibus ac facilisis in
    <span class="badge badge-default badge-pill">2</span>
  </li>
  <li class="list-group-item flex-items-xs-between">
    Morbi leo risus
    <span class="badge badge-default badge-pill">1</span>
  </li>
</ul>
{% endhighlight %}
```

**Comment by j0an** [comment]
Thanks @mdo I will check this out :)

**Comment by j0an** [comment]
🎉 Works fine @mdo 
thanks for the insight :)

**Comment by johnunclesam** [comment]
@mdo, and what if I need more than two "objects" in one <li>? Like this with Bootstrap 4.0.0-alpha.6: https://plnkr.co/edit/zgjGg2ZoX0JbjWaeWUIT

**Comment by j0an** [comment]
+1 to this flexbox solution :)
