### ISSUE TITLE
Numbers alignment in .tag-pill displayed not in center

### ISSUE THREAD

**Issue by subprime** [twbs/bootstrap#21317]
I'm currently switching from Bootstrap 3 to Bootstrap 4. In the previous version i use the .bagde class and i read that this is no longer supported and the peoples should use .tag-pill instead of .bagde.

After drop of .badge numbers displayed not in center of the .tag-pill
![tag-pill-issue](https://cloud.githubusercontent.com/assets/17912160/21002949/ca9e5f28-bd28-11e6-839f-062700e9d59b.PNG)

**Comment by copynpaste** [comment]
Tag will be renamed back to badge - #20939

**Comment by mdo** [comment]
This is more likely to do with cross-browser font rendering with our switch to system fonts than anything else. For the time being, I'm inclined to close as a won't fix because it's basically impossible to get this right for every browser and OS. Open to suggestions if folks have them though for improved rendering across all supported browsers!
