### ISSUE TITLE
Popover can't be hidden if jquery's element is already .remove()'ed

### ISSUE THREAD

**Issue by sliterok** [twbs/bootstrap#21326]
Popover can't be hidden if jquery's element is already .remove()'ed
https://jsfiddle.net/orbrjjxa/

**Comment by Johann-S** [comment]
Maybe we can think about adding MutationObserver to Bootstrap (see : https://developer.mozilla.org/en/docs/Web/API/MutationObserver) but the compatibility is IE11 not IE10.

Any thoughts @bardiharborow ?

**Comment by sliterok** [comment]
I've just noticed, that i've kinda screwed up part of code, where it's removing popover, but if i fix it, it still doesn't work

**Comment by hnrch02** [comment]
> Maybe we can think about adding MutationObserver to Bootstrap (see : https://developer.mozilla.org/en/docs/Web/API/MutationObserver) but the compatibility is IE11 not IE10.

That would mean tremendous overhead for something that developers should have to deal with themselves.

I'll close this as a WontFix since we can't reasonably detect when the original element is removed from the DOM. Please consider the state of tooltips/popover before just flat out removing elements. I'll file a issue about adding a note in docs for this.
