### ISSUE TITLE
Button Toggle States Would Look Cool if btn-secondary was the inactive, and another class (btn-primary, btn-danger, etc) could be the active state

### ISSUE THREAD

**Issue by bradlis7** [twbs/bootstrap#21335]
I feel like the Button Toggle Inactive and Active states are not clear. I would prefer it myself if the inactive state was styled as `btn-secondary`, and active state actually used the applied class (such as `btn-primary`). Maybe a new class would be applicable, so users aren't confused (`btn-primary-active`).

Here's an example of what I'm talking about:

![image](https://cloud.githubusercontent.com/assets/7062604/21168668/99b95226-c17b-11e6-8078-0a18def1136d.png)

Here's some CSS to make it work now (it still uses the off color for .active).

    [data-toggle="buttons"] .btn:not(.active) {
      color: #373a3c;
      background-color: #fff;
      border-color: #ccc;
    }

**Comment by cvrebert** [comment]
Not sure of the accessibility implications of the white vs. colorful approach you're suggesting. (/cc @patrickhlauke )

> Maybe a new class would be applicable, so users aren't confused

Yeah, if we want this, I think we'd have to go with that route, for consistency and clarity.

Keep in mind that we can't include every permutation of button styles that folks might possibly want; otherwise the framework would become bloated. So this might end up rejected as "interesting, but not common enough".

/cc @mdo to evaluate whether we want this

**Comment by patrickhlauke** [comment]
the colourful version wouldn't be more accessible/inaccessible than the current way of doing it (modulo colour contrasts...which reminds me i need to check the ratios since @mdo changes these recently).

reminder that for each of those states you'll also need a "focused but inactive" and a "focused but active" styling

my main concern though would be that this use of the colour palette may be a bit too....visually opinionanted?

**Comment by mdo** [comment]
We won't be going this route or providing additional classes for this. Thanks though!
