### ISSUE TITLE
pagination not wrap it's overflow on mobile screen in v4

### ISSUE THREAD

**Issue by pixieaka** [twbs/bootstrap#21505]

**Comment by slavanga** [comment]
The ```.pagination``` class probably needs ```display: flex-wrap;``` to wrap on small screens.

**Comment by pixieaka** [comment]
when pagination hit 1000 record , then it over flow and show horizontal scroll on xs screen,, we need to wrap it,,

**Comment by mdo** [comment]
Pagination has never been designed to wrap; it's meant to be one solid block of links attached to one another. I'd suggest that perhaps we revisit the design, but then it basically becomes an inline navigation component of sorts. Closing as a won't fix for now.

**Comment by ffoodd** [comment]
@mdo May we consider this again for v5?

The design concern about "one solid block" [depends on `$pagination-margin-left` equaling to `-$pagination-border-with`](https://github.com/twbs/bootstrap/blob/ffb19e925cb18c46fc4efa73b1f839ace28a06a1/scss/mixins/_pagination.scss#L10) (which makes sense).

May we consider to allow wrapping otherwise, since we suppose that there's no solid block? We're  already applying a `border-radius` everywhere, in that case.
