### ISSUE TITLE
sidebar in blog.css pushed to bottom

### ISSUE THREAD

**Issue by MalikRumi** [twbs/bootstrap#21514]
I hesitate to post this since by no means am I a css, js, or bootstrap expert, but I just copied and pasted the new blog.css and blog template examples from this repo **without changes** and the sidebar is all the way at the bottom, instead of on the right side as in the example on getbootstrap. 

The main body container is sm-8, and the sidebar is sm-3 with an offset of 1, so 8 + 3 + 1 = 12, and I assume that is right. But when I look at it in the inspector, both the main and the sidebar have a _width of 1080_. I also note that the well background to "About" is quite a bit wider than the rest of the sidebar. 

I suspect this is the problem but I am not entirely sure how to fix it, since I thought that was what the col settings were for. 

Ubuntu 16.04, Firefox 50.1.0

--update, 5 minutes later--

I got an idea to look at the example http://getbootstrap.com/examples/blog/ in the inspector and sure enough, there, blog-main is col-sm-8, but it is also 862.222 wide while sidebar is 323.333. Maybe there is some relative setting here that determines the widths, I'm not sure, but still, since I haven't changed anything, shouldn't that have worked unchanged?
I've also counted divs and I don't see any missing or unclosed tags.

**Comment by mdo** [comment]
This template hasn't been modified in any significant way for a couple years now. This could be an issue with copying the code into the wrong version of Bootstrap (I don't think this works with v4). You could also be missing Bootstrap's CSS entirely? Hard to tell without a live demo.

If none of those things are the problem, please share a reduced test case (something on JS Bin or similar) so we can look at your code. Otherwise, there's nothing we can do here, especially since this is for v3, which we're not currently developing any further.
