### ISSUE TITLE
Automatically scrolling after folding accordion

### ISSUE THREAD

**Issue by diox76** [twbs/bootstrap#21531]
OS: MAC OS X 10.11.6 (15G1004)
Opera: 42.0.2393.94

[Webpage affected](http://www.radiovillegas.com/v2/quieroserartista.php)

Steps:

1. Scroll down until accordion.
2. Click several times (at least 10) on the first header.
3. Look at how the scrollbar moves

Best regards.

**Comment by mdo** [comment]
You need to produce a reduced test case for bug reports; we cannot sift through full sites like this. Looking at it though, I'd guess your problem is with the numerous things happening on the page, including those `.flake`s constantly repositioning themselves, the changing header position, etc.

If you can still produce the bug with just our HTML, CSS, and JS, please comment here with a JS Bin demoing it and I'll reopen. <3
