### ISSUE TITLE
Heading text overflows

### ISSUE THREAD

**Issue by julmot** [twbs/bootstrap#21562]
Here's a screenshot of the BS4 documentation with a heading like e.g. `<h2>`:

![text-overflow](https://cloud.githubusercontent.com/assets/8310677/21716084/844c9fe8-d408-11e6-8459-fca0db56b67a.png)

Seems like the descender height of "g" doesn't fit into the specified line height of `1.1`.

Why this is a problem for me? I'm adding a marquee effect if text overflows and currently it always overflows. I needed to override the default line height to solve it.

- Firefox 52.0a2
- Windows 7

**Comment by julmot** [comment]
Same applies to e.g. inputs (have a look at "e.g.")

![inputs](https://cloud.githubusercontent.com/assets/8310677/21729838/264f621e-d44d-11e6-8575-ba2f4be87987.png)

**Comment by thiagotomasi** [comment]
@bardiharborow do you mind if I how in this one?

**Comment by thiagotomasi** [comment]
@mdo can I proceed with this?

**Comment by Quy** [comment]
@thiagotomasi No one is assigned to this issue so I would say go for it. 👍

**Comment by mdo** [comment]
> I'm adding a marquee effect if text overflows and currently it always overflows. I needed to override the default line height to solve it.

If you're adding some styles, I suspect you'll need to add additional ones. I don't quite see what needs changing here on our end; what's the proposal?

**Comment by thiagotomasi** [comment]
@mdo I believe we can play a little with the 'line height' default to fix this, what you think?
I'll make some test and came back to you.

**Comment by julmot** [comment]
> If you're adding some styles, I suspect you'll need to add additional ones. I don't quite see what needs changing here on our end; what's the proposal?

You'd need to modify the `line-height` that all characters fit into it.

**Comment by thiagotomasi** [comment]
@julmot I played with the `line-height` and I believe it is not a good idea modify the `line-height`  into the bootstrap core. Because it's not a `bug` but one particular case.

Here are the tests I made with **Firefox**, **Chrome**, **Opera** and **Firefox developer edition**, and you can see that the select text behave the same way in all of these Browsers and if you check the Firefox developer edition this detail with the font is `fixed`, so soon every Browser will behave the same way!

## Opera
![opera](https://cloud.githubusercontent.com/assets/4387026/22255835/64a53878-e261-11e6-8fa7-ac49982e4d9e.png)

## Google Chrome
![google](https://cloud.githubusercontent.com/assets/4387026/22255847/7188c636-e261-11e6-9efc-c1903bf5e168.png)

## Firefox
![firefox](https://cloud.githubusercontent.com/assets/4387026/22255852/745acfa8-e261-11e6-9249-feea68309fe7.png)

## Firefox Developer Edition
![fde](https://cloud.githubusercontent.com/assets/4387026/22255859/75e54ab0-e261-11e6-89f6-22c995cac2a7.png)

I hope this may help you 😄
And let me know if I misunderstood your need!

**Comment by mdo** [comment]
Yup, don't think we're going to make any changes here. You can easily override the default line-height or customize on one-off situations if needed though.
