### ISSUE TITLE
Suggestion for classes of align

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#21680]
By default, all cells in table align top (cant change this by variables).
If i want align middle for all table, now i have to use `align-middle` on each `td`.
Will be nice if i apply `align-middle` only on `tr` or `tbody` or `table`  and all `td`'s will align middle automatically 😄

**Comment by mdo** [comment]
If you need this on every child element, you should write custom CSS. We won't be adding classes to tackle that.

**Comment by cupofjoakim** [comment]
@mdo I see that this is an old PR, but I just wanted to gice my two cents. I think it'd be "bootstrap"-like to actually do what @projct1 is asking about, atleast on a row basis. Something like this would be sufficient:

```
tr.align-middle > td {
  @extend .align-middle;
}
```

Now, this is basically **nothing** to write yourselves as custom css, so the issue doesn't lie there, it's more of an issue in terms of expected behaviour.
