### ISSUE TITLE
Feature Request: Grid System with (real) margins gutter (2nd try)

### ISSUE THREAD

**Issue by 7R5N** [twbs/bootstrap#21828]
I posted this issue ~2 years ago, and it was rejected (see #16358)

_Now_, that with the last alpha version, bootstraps whole grid system is based on flexbox, I keep myself asking why you don’t switch the grid gutters to margin _now_ …!? 
- It’s HTML’S correct attribute for this purpose (=> outer space around boxes)
- You can use padding alongs, without having to nest another DIV for the actual paddings
- It simply works. Without any "last-element-has"-float-fixes, width calculations or else … 

Especially the 2nd point sometimes really bugs me; on some projects I even 'hacked' the grid mixin to use margins. 

I think this would be a great deal. 

Make bootstrap great again!  ;-)

**Comment by IamManchanda** [comment]
Hmmmnnnn.... reminds me of

**Comment by mdo** [comment]
> Now, that with the last alpha version, bootstraps whole grid system is based on flexbox, I keep myself asking why you don’t switch the grid gutters to margin now …!?

How is the move to flexbox related to margins, or any other CSS property, at all?

> It’s HTML’S correct attribute for this purpose (=> outer space around boxes)

Right, but we want `padding` because it provides space within the column. This is especially useful for setting background-colors, positioning borders, etc.

> You can use padding alongs, without having to nest another DIV for the actual paddings

Because of `box-sizing: border-box`, padding has no impact on the column width. Change the padding if you need to. (Yes you do need to be aware of negative margins for rows.)

> It simply works. Without any "last-element-has"-float-fixes, width calculations or else … 

The grid also simply works now, without any float fixes. The width is a single property (minus flexbox bugs).

I appreciate your questioning the assumptions here, but we're on our way to our first beta and changing the grid *now* vs 1-2 years ago when we were actively rewriting key areas of the project isn't manageable. Thanks, but we'll pass on moving back to margins.

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/22623677/99807c38-eb30-11e6-8d7b-2bec66b20b2a.png)

![image](https://cloud.githubusercontent.com/assets/224636/22623692/ec3717c0-eb30-11e6-80aa-adbc94914270.png)

**Comment by corysimmons** [comment]
[Again for posterity](https://github.com/twbs/bootstrap/issues/19026#issuecomment-318867320), I think Foundation's new XY grid is nice because it offers both, but if I had to pick one over the other, I'd now go with padding.

Markup is bloated, but reusability (especially with components frequently found in React/Vue) is nicer in the long run: http://rscss.io/layouts.html#avoid-positioning-properties
