### ISSUE TITLE
Alert close button overflowing its container causing extra space to appear below

### ISSUE THREAD

**Issue by jleider** [twbs/bootstrap#21889]
This is a continuation of #21733 with working examples, comment in SCSS for fix:

https://jsfiddle.net/kpyh492r/5/

The bug appears in all major browsers.

![image](https://cloud.githubusercontent.com/assets/38108/22486253/c50bd67a-e7d6-11e6-89fc-8a13b10b6784.png)

**Comment by WilsonMontelo** [comment]
Na classe "alert" você coloca overflow: hidden que ela vai ajustar o tamanho e utiliza o padding para ajustar os espaçamentos.

.alert {
    padding: 20px 0px 0px 15px;
    margin-bottom: 1rem;
    border: 1px solid transparent;
    border-radius: .25rem;
    overflow: hidden;
}

No botão ".alert-dismissible .close" você somente ajusta a posição

.alert-dismissible .close {
    position: relative;
    top: -0.80rem;
    right: -0.25rem;
    padding: .75rem 1.25rem;
    color: inherit;
}

**Comment by bronboek** [comment]
I can confirm this issue, removing position + padding is the best option for now imho. It makes the button smaller, but that's less of a concern than the extra height it causes.

**Comment by xdiego1** [comment]
Infatti... bravo


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: bronboek <notifications@github.com> 
Data: 04/02/17  12:08 PM  (GMT+01:00) 
A: twbs/bootstrap <bootstrap@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Oggetto: Re: [twbs/bootstrap] [Alpha 6] Alert close button overflowing its
  container causing extra space to appear below (#21889) 

I can confirm this issue, removing position + padding is the best option for now imho. It makes the button smaller, but that's less of a concern than the extra height it causes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/twbs/bootstrap","title":"twbs/bootstrap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/twbs/bootstrap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bronboek in #21889: I can confirm this issue, removing position + padding is the best option for now imho. It makes the button smaller, but that's less of a concern than the extra height it causes.  "}],"action":{"name":"View Issue","url":"https://github.com/twbs/bootstrap/issues/21889#issuecomment-277435911"}}}

**Comment by matthaliski** [comment]
Removing .alert-dismissible (thus, positioning and padding) seems to work.

**Comment by LarryAzevedo** [comment]
**I would suggest changing the output from:**

```
.alert-dismissible .close {
  color: inherit;
  padding: 0.75rem 1.25rem;
  position: relative;
  right: -1.25rem;
  top: -0.75rem;
}
```

**to:**

```
.alert-dismissible .close {
  color: inherit;
  padding: 0.4rem 1.25rem;
  position: relative;
  right: -1.25rem;
  top: -0.3rem;
}
```

That way it's still user-friendly on touch devices.  Please reference https://github.com/twbs/bootstrap/issues/20013
