### ISSUE TITLE
$font-size-base does not scale padding/margins in v4

### ISSUE THREAD

**Issue by briancray** [twbs/bootstrap#21899]
If I set $font-size-base to .75rem it does not scale all padding and margins to that base font-size, making the padding and margins too large for the scale of the type. I could manually set html font-size but it seems like this scaling should be officially supported.

**Comment by mdo** [comment]
Correct, `rem` units are based on the root element, the `<html>` element. The scaling is based on that, not the `<body>`'s font-size. Some discussion can be found in the PR at #21524 and it's connected issues.

**Comment by IT-CASADO** [comment]
I'm trying to use in one of our project 15 px as a font-size-base, but figuring out the same problem with padding and margin as briancry mentioned. 

Bases on this [approach](https://getbootstrap.com/docs/4.1/content/reboot/#approach) it should be the right way. But because of $font-size-base is applied to the [BODY](https://github.com/twbs/bootstrap/blob/master/scss/_reboot.scss#L36) instead of [HTML](https://stackoverflow.com/questions/48451764/how-to-set-base-size-for-rem) (root), all my margins and paddings are calculated based on 16px (browser default for HTML element).

So for me this seems to be a bug, or do i miss something!?

**Comment by patrickhlauke** [comment]
@mdo i believe this is actually a bug now in our styles, as @IT-CASADO notes. if paddings/margins are based off of the font size of the `<html>` element now, but `$font-size-base` only actually changes the size on `<body>`, then paddings/margins are always the same regardless of specified base font size...surely they should be based off of THAT instead? i.e. should `$font-size-base` be set on the `<html>` element?
