### ISSUE TITLE
Radio buttons group: incorrect aria-pressed behavior

### ISSUE THREAD

**Issue by thbt** [twbs/bootstrap#22040]
When clicking on a [radio button in the v4 demo]( https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons) and using chrome devtools, I noticed a weird behavior : 

- clicking on one of the radio button `Radio 2` of the group will set it's `aria-pressed` attribute to `true`.
- clicking on `Radio 3` will set it's `aria-pressed` attribute to `true`, and `Radio 2` will still have `aria-pressed=true` as well, even though it's not toggled anymore.
- clicking on `Radio 3` again will set it's `aria-pressed` attribute to `false`, even though it's still toggled.

It looks like the `aria-pressed` logic is the same as the one from the checkbox. Testing it with NVDA gives the wrong output (the checked button is not the intended one). I have yet to test it with JAWS and VoiceOver.

Is this the correct behavior ?

**Comment by patrickhlauke** [comment]
There seems to indeed be something broken here. Fundamentally, `aria-pressed` should not be set at all on the `<label>` elements, as it makes no sense there - it's the visually hidden radio buttons that carry the checked/unchecked state.

I worked on some form of simplication of the whole checkbox/radio button logic ages ago...will try to dig this out and address the problem.

**Comment by thbt** [comment]
> Fundamentally, aria-pressed should not be set at all on the <label> elements, as it makes no sense there

That's what I thought as well

**Comment by joe-watkins** [comment]
@patrickhlauke I took a quick look at this and wondering if ARIA is needed at all on the `checkbox` and `radio` examples. AT will communicate checked state naturally because they are native elements and well supported.

If the roles of these elements were being changed I'd think this may be required but don't here.. what ya think?

**Comment by patrickhlauke** [comment]
handling `aria-pressed` in the checkbox/radio case, if implemented the way we show in the documentation, is indeed superfluous. the JS here is only really there to set the correct CSS class to the `<label>` (in absence of a parent selector in CSS). i don't believe it's the intention for the CSS to handle arbitrary elements being used as radio/checkbox elements (as it would otherwise need lots more logic here and ideally only work with the appropriate `role="..."` elements etc).

i think fundamentally this whole "button groups for checkboxes/radio buttons" thing could be handled differently and split out/away from JS completely...but for now i've made an initial patch here https://github.com/twbs/bootstrap/pull/22400
