### ISSUE TITLE
Remove "important" rule from CSS class "d-flex"

### ISSUE THREAD

**Issue by nikkwong** [twbs/bootstrap#22076]
I'm not understanding the necessity of ```!important``` on the class ```d-flex```:

```
.d-flex {
    display: -webkit-box!important;
    display: -webkit-flex!important;
    display: -ms-flexbox!important;
    display: flex!important;
}
```

This makes dynamically changing the ```display``` property difficult—we now have to use the ```!important``` rule any time we're trying to override this rule with a more specific selector. 

It begs the question for why ```!important``` is used in the first place.

**Comment by bardiharborow** [comment]
1. [CSS selector specificity](https://developer.mozilla.org/en/docs/Web/CSS/Specificity) can often interfere with correct application of `.d-flex`, and hence the class chooses to use `!important` to ensure this does not happen.
2. If you are having difficulty dynamically changing the `display` property, have you considered switching the classes out instead (which you should probably be doing anyway, rather than applying CSS directly from JavaScript).

**Comment by IamManchanda** [comment]
Important is very important for. Utility classes considering immutability

**Comment by arcanereinz** [comment]
How about an alternative version of d-flex that does not have important. We're using css in js where the classnames are dynamic so !important isn't that important and we discourage the use of important given the css is isolated to each React component.

**Comment by D3faIt** [comment]
Are there no way to **not** set important?
Yes, I can see it being useful how it is, but sometimes you would want to add custom style on top of it, and have some control of the style with `:active` `:hover` `:focus` etc...

I think it's a bit unnecessary having to write a new custom class only to prevent it being `!important`.
I think it would be a good idea to be able to set a "flag" to prevent `!important`.
Something like:

    <div class="d-flex-ni h-100-ni">something</div>

**Comment by ffoodd** [comment]
You can set `$enable-important-utilities` to `false`, read the [Sass options documentation](https://getbootstrap.com/docs/5.1/customize/options/).
