### ISSUE TITLE
Waves for buttons and links...

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#22117]
I love Bootstrap, but there's one thing I do not like, only this one, I swear. I would like an effect (such as Waves, Ripples, Material Design) for when I click on a button or link. It's so difficult? What do you advise?

Especially on touch mobile devices it is difficult to understand (if the result is not immediate) that you clicked. How to solve?

**Comment by mdo** [comment]
Focus and active states provide enough indication in my opinion, but anything beyond that like the styles of Material, aren't something that fits into this framework. Thanks for the suggestion though!

**Comment by johnunclesam** [comment]
> anything beyond that like the styles of Material, aren't something that fits into this framework

Why?

**Comment by patrickhlauke** [comment]
> Why?

because beyond some basics, Bootstrap tries to be fairly non-opinionated to work as a basis/launching-off point for people to customise their own site designs on top of it. If you incorporate very specific design/animation choices into core, that defeats purpose. Sure, it could be added as optional classes, but really the better solution here is for people to build custom themes on top of BS separately.
