### ISSUE TITLE
Display properties do more harm than good

### ISSUE THREAD

**Issue by aleemb** [twbs/bootstrap#22149]
@mdo related to https://github.com/twbs/bootstrap/pull/22113

`d-block` and `d-none` (which is now `hidden-*-up`) has a few issues I noticed since when our UI devs started using them.

1. The first is that `d-block` and `d-inline` led to bad HTML semantics. It's best to use `div` and `span` for the purpose they exist but since these classes exist, they got used, albeit incorrectly.

2. The `hidden-*` classes seemed more semantically correct in that the end goal was to show hide elements and the markup read more correctly: "This element should be hidden" and "this element should be visible".

3. It's also more book keeping. Unhiding an inline element would require `display-inline` and unhiding a block level element would require `display-block`. Unhiding a list item would require `display-inline-block`. This can and will lead to bad behaviour and errors. Ideally unhiding could be `display: inherit` so the state gets restored to what it was.

**Comment by mdo** [comment]
> The first is that `d-block` and `d-inline` led to bad HTML semantics

This problem isn't unique to these classes existing. Folks do this all the time without having access to these utilities. I do agree it's potentially an increased risk, but these exist mainly as *utilities*. Components shouldn't be completely built on utilities; they're modifiers to provide quick access to certain types of behaviors without the need for constant custom CSS.

That's the entire point of utilities—turn the most commonly repeated property-value pairs into easy to use classes so that your CSS can avoid unnecessary rulesets, selectors, and classes just for toggling display, text alignment, floats, etc.

> The hidden-* classes seemed more semantically correct in that the end goal was to show hide elements and the markup read more correctly: "This element should be hidden" and "this element should be visible".

Maybe. `.hidden-*` doesn't map to a CSS property, while the rest of our utilities typically do. `.d-sm-none` tells me the same as `.hidden-sm` IMO, provided you have the context this affects display (which is unclear to anyone new to this regardless of the `d` or `hidden`). That's why we have docs though :).

> It's also more book keeping. Unhiding an inline element would require display-inline and unhiding a block level element would require display-block. Unhiding a list item would require display-inline-block. This can and will lead to bad behaviour and errors. Ideally unhiding could be display: inherit so the state gets restored to what it was.

This isn't any more or less book keeping than the hidden classes. `.hidden-sm` and `.d-sm-none` do the same thing, and would require the same override to undo. Your point about restoring the default value of `display` is a good one, though `inherit` is the wrong one (we'd want `initial`, which isn't supported in IE11).

**Comment by aleemb** [comment]
Thanks for clarification regarding classes with say-what-they-do naming -- I suppose it does keep things simpler and solves a different problem (economy of selectors).
