### ISSUE TITLE
Firefox mobile - modal close after input focus

### ISSUE THREAD

**Issue by Gazvenn** [twbs/bootstrap#22178]
Using Firefox 52.0 on Android

if any form of input is focused inside a modal then the close button will no longer work. 

problem found on own project and confirmed on http://getbootstrap.com/javascript/#modals-related-target

**Comment by hhsmedia** [comment]
I have the same issue after a tooltip is activated. Have seen it happen on both my own application and in the [documentation example](https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers).

**Comment by patrickhlauke** [comment]
confirming the problem with inputs in modals and firefox/android (using https://v4-alpha.getbootstrap.com/components/modal/#varying-modal-content since v3 is in maintenance mode)

same problem with https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers also seems to happen in Chrome/Android

**Comment by samozzy** [comment]
Can confirm the bug in Chrome 57.0.2987.133 on [docs page](https://v4-alpha.getbootstrap.com/components/modal/).

**Comment by patrickhlauke** [comment]
Seems to be resolved in latest v4 beta 1
