### ISSUE TITLE
form-control-success is required to display the validation icon

### ISSUE THREAD

**Issue by weechong-ong** [twbs/bootstrap#22182]
In [the documentation](https://v4-alpha.getbootstrap.com/components/forms/) , it mentions that 

> To use, add .has-warning, .has-danger, or .has-success to the parent element. Any .col-form-label, .form-control, or custom form element will receive the validation styles.

But, if we only add .has-success to the form-group div, the form-control-success will still need to be manually applied to the input textbox to show the validation icon.

Have I misunderstand the documentation?

**Comment by vatsalyakolluru** [comment]
It is not mandatory to provide "form-control-success" on the input fields because adding .has-warning, .has-danger, or .has-success to parent element provides style like border color to the input field where as form-control-success adds a background-image like a check.

Finally, both the classes are provided to add validation styles to the input elements but need not to be together.

.has-success .form-control-success {
    background-image: url(data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' v… 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3E%3C/svg%3E);
}

.has-success .form-control {
    border-color: #5cb85c;
}

.form-control-danger, .form-control-success, .form-control-warning {
    padding-right: 2.25rem;
    background-repeat: no-repeat;
    background-position: center right .5625rem;
    background-size: 1.125rem 1.125rem;
}

**Comment by mdo** [comment]
Revisiting validation states in #22762.
