### ISSUE TITLE
[feat][question] jQuery free version 

### ISSUE THREAD

**Issue by michaeljota** [twbs/bootstrap#22194]
Hi! I wondering if you have plans for release a jQuery free version of Bootstrap. I search for this, but did not find anything about it. I know it's been a lifetime together, but all the good things comes to an end, and that's not bad. I guess web just had evolved in something that doesn't need jQuery. 

There are several CSS frameworks that relays on jQuery, but this is the biggest, if this start to ship a jQuery free version, I bet that others would also consider this as well. 

This would made integration with other JS frameworks and libraries more lightweight and straightforward. 

Anyhow, just wondering, if this is a duplicate, I'm really sorry, I try my best to find something about this, I guess it's not easy topic to search about.

**Comment by jhabdas** [comment]
@michaeljota It's my understanding such an approach would lead to browser inconsistencies and a slew of bugs, making Bootstrap less accessible. They did switch to jQuery lite in Boostrap 4 and are using tether in replacement for what might otherwise be a jQuery plug-in, so that's a good step in the right direction. If you're only supporting modern browsers you may want to look at a CSS microframework like [Bulma](http://bulma.io/) and roll your own JS. To get a feel for what the JavaScript might start to look like if you wanted to roll vanilla and support older browsers, check out the [PhotoSwipe](http://photoswipe.com) example code.

**Comment by Olivia101** [comment]
Since Bootstrap 4 now only supports IE 10+ it might be a good idea to switch to vanilla JavaScript.

**Comment by bardiharborow** [comment]
This isn't something we'll be doing at this stage in v4 development (when we're working on shipping betas). We'll look at this again when v5 swings around.

**Comment by fatihhayri** [comment]
http://youmightnotneedjquery.com/
