### ISSUE TITLE
Feature: Fix the Issue of Poor Contrast levels. AT is Important.

### ISSUE THREAD

**Issue by GeorgeWL** [twbs/bootstrap#22247]
> Currently, some of the default color combinations available in Bootstrap (such as the various styled button classes, some of the code highlighting colors used for basic code blocks, the .bg-primary contextual background helper class, and the default link color when used on a white background) have a low contrast ratio (below the recommended ratio of 4.5:1). This can cause problems to users with low vision or who are color blind.

Maybe the Base CSS should be Accessible as Standard when it comes to that?

**Comment by mdo** [comment]
It's something I'm aware of, but we're not actively working on right now. There have been a few attempts and a handful of issues related to this in v4. Most efforts end up making it all look far too dark across the board and lose out on the general Bootstrap feel.

Closing for now though since I don't have too much time to spend on this part of things right now and we're not planning any major changes right now. If there are specific recommendations, I suggest opening a new issue or a focused PR to show screenshots of changes.

**Comment by GeorgeWL** [comment]
Glad you're aware. I feel like it's not something that should be an oversight like the previous version.

Especially with statistics showing that the number of disabled users that use the internet is on the rise thanks to the tech becoming more affordable, easier to use and taught to those who require it from a younger age.
