### ISSUE TITLE
Units tests failed on OSX and Linux

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#22332]
Due to this commit https://github.com/twbs/bootstrap/commit/a14451deb3b8368de76aad6e728b27032bf8097a

job : https://travis-ci.org/twbs/bootstrap/jobs/217756286

Maybe @Deilv, do you have any idea why ? 

Edit maybe it would be better to move unit test relative to this commit in a visuel unit test

**Comment by Deilv** [comment]
All tests passed before the merge, will look into it asap

**Comment by Deilv** [comment]
I just successfully built on Linux, no errors whatsoever. Maybe Travis is acting up again? Will test on macOS in a few minutes.

**Comment by Deilv** [comment]
Builds fine on macOS, too. I also synced my forked repository and travis tested [fine](https://www.travis-ci.org/Deilv/bootstrap/builds). The travis/twbs logs indicate that all tests fail under certain configurations, but give no indication why. I want to investigate this further, but it's hard since I don't get any errors locally or remotely. Any chance you can add a separate branch for this on twbs and give me access, so I can push and test there?

**Comment by Deilv** [comment]
I found the issue, PR coming up. The modal works great, but the test has to take into account macOS behaviour.

**Comment by Johann-S** [comment]
Thank you @Deilv 👍 
When you'll open your PR I'll create a temporary branch on BS repository to test on SauceLabs via Travis

**Comment by Deilv** [comment]
@Johann-S @mdo The PR with the fix should be ready to merge and resolve all build errors. I'm sorry for the trouble, but I really doubt I could predict such an exotic issue :)

**Comment by Johann-S** [comment]
Don't worry it's ok 👍 it's hard to test on multi OS
