### ISSUE TITLE
Bootstrap 3.3.5 end of life

### ISSUE THREAD

**Issue by mjadhav-bayer** [twbs/bootstrap#22343]
Is there an end of life/support date announced for Bootstrap 3.3.5?
Thanks.

**Comment by mdo** [comment]
We stop supporting old versions as soon as the new one comes out honestly. So 3.3.5 is done because 3.3.7 is out. We're not actively developing v3.3.7 any further though because we're focused on v4.

**Comment by babatundeko** [comment]
Hi, Bootstrap helpdesk,

My organization is currently using Bootstrap v3.3.7 for the internal web application and plan to upgrade v.3.4.1 due to XSS vulnerability issue. However, is a Bootstrap v2.x and v3.x end of life(EOL)? And no longer supported and maintained? If not, then we need an upgrade to Bootstrap v4.x. Please confirm and provide a brief description of why these versions no longer supported/maintained. Any significance information relates to EOL would be appreciated. 

Thanks, 
Kazeem

**Comment by mdo** [comment]
Please see comment in the issue you opened. https://github.com/twbs/bootstrap/issues/28434#issuecomment-471025866
