### ISSUE TITLE
Why keep non-tether css?

### ISSUE THREAD

**Issue by IdanCo** [twbs/bootstrap#22443]
Both tooltip and popover keep maintaining a `.tooltip-[direction]` and `.popover-[direction]` classes, **in addition** to the tether classes:

```sass
// from scss/_tooltip.scss
  &.tooltip-top,
  &.bs-tether-element-attached-bottom {
    padding: $tooltip-arrow-width 0;
    margin-top: -$tooltip-margin;
```

I admit these non-tether classes are prettier than the tether ones, but they increase the minified bootstrap.css **by almost 1k** ([see non-minified compare](https://www.diffchecker.com/jJfJTNNr)), and I can't see the purpose they fulfill. Perhaps it's a relic from the [pre-tether](https://github.com/twbs/bootstrap/commit/a58febf71a5eac2161ce2db08c7d723755ed1163#diff-6972cbb37f0ec48771217d4915ea7e6fR4011) era.

Worth mentioning that these classes are currently used in the docs in the [static demo](http://v4-alpha.getbootstrap.com/components/tooltips/#static-demo) section. Even so, they can be easily replaced by the tether classes:

```diff
--- docs/components/tooltips.md	(date 1492073561000)
+++ docs/components/tooltips.md	(revision )
@@ -50,7 +50,7 @@

-  <div class="tooltip tooltip-top" role="tooltip">
+  <div class="tooltip bs-tether-element-attached-bottom" role="tooltip">
     <div class="tooltip-inner">
       Tooltip on the top
     </div>
```

Is it PR worthy? Notice that this will be a breaking change (in case someone relied on these classes), so it might be worth considering before the beta release.

**Comment by pkozlowski-opensource** [comment]
Just one thing to consider: we (https://ng-bootstrap.github.io) are building Angular-specific widgets based on Bootstrap CSS and we do not use tether for positioning. So the proposed change would be indeed a breaking change.

But I feel like the proposed change would impact anyone just writing CSS (without using JS to open tooltips / popovers) - not only a breaking change but also a more verbose alternative.

More importantly I feel like the proposed change would "leak" internal implementation details of Bootstrap (3rd party lib being used). Since I think I've seen some chatter about replacing tether with sth else so the mentioned "leak of impl details" would play a role here.

**Comment by pkozlowski-opensource** [comment]
Bum, speaking of replacing tether: #22444 :-)

**Comment by IdanCo** [comment]
good points @pkozlowski-opensource , when you put it like that it's worth the extra k.

**Comment by mdo** [comment]
We'll leave them as-is until we determine what we're doing with the Tether replacement.
