### ISSUE TITLE
<select> support for input groups

### ISSUE THREAD

**Issue by Eugeny** [twbs/bootstrap#22457]
As per #22283, `<select>` inside input groups generally work, except for the vertical alignment in Chrome/macOS (possibly also other browsers), which is caused by `display: flex` applied to the select element.

IMHO this should be supported in BS4 just like it was in BS3.

Demo (Bootstrap 4): https://plnkr.co/edit/VzaynmMMWmahVQVjviO7?p=preview
Demo (Bootstrap 3): https://plnkr.co/edit/zV3Y4AKDNXaB4iCDfNiS?p=preview

**Comment by mdo** [comment]
To be clear, select elements have never been supported in input groups, in v3 or v4.

**Comment by a2line** [comment]
Playing with demo, I see that, in Chrome, the letters with descender (g, j, p, q and y) are truncated in normal and large select. It's all right with `form-control-sm`, `custom-select` (or if they are inside an `input-group`). That’s really annoying because g completely looks like q, and j like i too… Can this help to fix the first two cases behaviour?

![image](https://cloud.githubusercontent.com/assets/10353895/25513778/3c90cd78-2bd8-11e7-83f7-5d67f033b9a3.png)

See https://plnkr.co/edit/XkGRvb4nMTYl5io3aPRL?p=preview
