### ISSUE TITLE
bootstrap-grid.css doesn't include styles for additional flex alignment options

### ISSUE THREAD

**Issue by ova2** [twbs/bootstrap#22494]
Some time ago I've created this issue for Boostrap 4: https://github.com/twbs/bootstrap/issues/20950 The flexbox layout is a default now, since alpha 6 release. Great. I've installed this version with NPM and imported **bootstrap-grid.css** in my Sass file as follows:

`
@import "~bootstrap/dist/css/bootstrap-grid.css";
`

This works very well, but I'm missing styles for additional flex alignment options such as `flex-first`, `justify-content-start`, `align-content-start`, etc. They all are defined in `utilities/_flex.scss`, but this file is not imported in `bootstrap-grid.scss`. Why? Is it an intention? I think `bootstrap-grid.scss` should import `_flex.scss` as well because we can use then all flexbox related classes for creating stunning layouts. This tutorial shows these style classes in details: http://tutorialzine.com/2016/11/boostrap-4-regular-vs-flex-grid/

To clarify: I don't want to include the complete `bootstrap.css` in my application. I ONLY want to use the flexbox layouts with Angular and PrimeNG :-).

I can create a Pull Request if it's ok for you. Thanks!

**Comment by ova2** [comment]
Hmm... I read this tutorial and didn't find the class `d-flex` too. It is in the `bootstrap.css`, but not in the `bootstrap-grid.css`. It looks like the flexbox related classes are scattered in all CSS files :-) I think the output files should follow separation of concens. I suggest the following output structure:

1. `bootstrap-reboot.css` - resets, etc.
2. `bootstrap-grid.css` - only layout stuff
3. `bootstrap-components.css` - only components
4. `bootstrap.css` = ` bootstrap-reboot.css`  + ` bootstrap-grid.css`  + ` bootstrap-components.css` 

This will bring the flexibility. We can then only include one file and use any custom grid systems and components. E.g. the following scenarios are possible:

- Inlcude only `bootstrap-reboot.css` and use any custom layout system and component frameworks
- Inlcude only `bootstrap-grid.css` and use custom components
- Include only `bootstrap-components.css` and use custom grid system
- Include `bootstrap.css` if we want to use everything from Bootstrap.

What do you think?

**Comment by oktalk** [comment]
The class `.d-flex` is defined in the file `scss/utilities/_display.scss` which is a utility available to the whole framework -- also in that file are some print specific classes.

On a whole, everything is parsed up just as you've suggested. I would argue that the specific class you've used as an example shouldn't be included in the Bootstrap grid because it is not necessary in implementing the grid system.

Also, it seems that quite a bit has changed since the last release. The flex utilities are included in the grid only framework now. It's possible that the utility classes could be better organized, but I haven't seen evidence of that yet.

**Comment by mdo** [comment]
Yeah, closing out since we added flex utils to the `bootstrap-grid.scss` file awhile back. Unsure if we need the display ones too—the grid rows already set `display: flex`.
