### ISSUE TITLE
.text-center inside th

### ISSUE THREAD

**Issue by thomasniederberger** [twbs/bootstrap#22519]
By using `<table class="table text-center">` the text is only centered in `<td>` but not in `<th>`.

Happens at the latest version:
`<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">`

**Comment by bkdotcom** [comment]
reboot.scss is the culprit:

```
th {
    text-align: left;
}
```

**Comment by oktalk** [comment]
It's the same behavior that exists in v3. You should add the `.text-{ALIGN}` class to the `td` or `th`.

**Comment by thomasniederberger** [comment]
adding a class to the `td `or `th` is always possible and also easy. just ask if it make sense that the `td `acts as child of the table used `center` and the `th `not.

**Comment by oktalk** [comment]
@thomasniederberger here is a great discussion on the matter:
http://stackoverflow.com/a/11321700/2564886

Since the `th` element is so opinionated from browser to browser this issue is a bit complicated. I do think Bootstrap is being a bit too opinionated itself by applying `text-align: left` in the first place -- even `normalizer.css` didn't do that. However, this has been the standard convention in Bootstrap for a while.

That being said, one way to handle this issue might be with an extra class such as `.table-align-left`. This would force the behavior of left aligning the `th`, and `td` elements -- kind of an opt-in method of left aligning the `th`.  I think this goes against the philosophy of Bootstrap however. Bootstrap is an easy way of implementing common design patters. And, left aligning the `th` is a common design pattern.

**Comment by mdo** [comment]
Near as I can tell, there aren't any differences in `th` styles across browsers. The intent in left-aligning it is to match the table cells. I'm unsure how best I'd like to proceed on this though.

**Comment by thomasniederberger** [comment]
I would center it. Lets leave the technical aspect on the side, out of a typograpic view, it doesn't make sence to have centred elements in the table but the headers are not. Well thats my opinion :).

**Comment by mdo** [comment]
Fix inbound at #22858.
