### ISSUE TITLE
WAI-ARIA

### ISSUE THREAD

**Issue by Decrepidos** [twbs/bootstrap#22543]
Although you develop a great product --- I see you're still implementing invalid ARIA attributes. For example for the carousel
<div class="carousel-inner" role="listbox">
Required children not present role="option". But if you add this child element it can contain no active elements. So remove role listbox and wrap the carousel in a role region with an aria-label or aria-labelledby. No other aria is required. Additionally the carousel should pause on focus and mouseover.
You use role button on the anchors but they are not triggered by the spacebar as expected for a button element, only enter key.

There are other issues in relation to accessibility for most of the functionality.

Just saying :-)

**Comment by Johann-S** [comment]
We are open for PRs to improve our accessibility do not hesitate @Decrepidos 👍

**Comment by patrickhlauke** [comment]
`role="listbox"` has already been removed in https://github.com/twbs/bootstrap/pull/22405

more tweaks are planned for this component. admittedly, the carousel is the worst offender at this point (mainly because there's no absolutely "correct" way of doing a carousel, since it's a widget that doesn't immediately map to an equivalent native widget nor ARIA pattern)

**Comment by patrickhlauke** [comment]
i'll close this issue for now, but rest assured that all of the current shortcomings of the carousel are on my radar to be tackled :)

**Comment by Decrepidos** [comment]
Thanks for the reply and update 😁
