### ISSUE TITLE
Feature Request: Add col-12-8-6-1 type classes

### ISSUE THREAD

**Issue by aleemb** [twbs/bootstrap#22575]
A shorthand for specifying column grids across various screen sizes would make life quite easy and the code would be intuitive to read at the same time.

```
# presently
col-xs-6 col-sm-4 col-md-2 col-lg-1

# shorthand
col-6-4-2-1
```

This would encourage more considered grids, easier find-replacing and would be in the same spirit as the terseness of margin/padding.

**Comment by browner12** [comment]
what do you do when you want to skip a level?

`col-6-x-2-1`

or do you have to define every level?

`col-6-6-2-1`

This seems like it would create a large amount of unnecessary CSS because you'd have to create a class for **every single combination**.

5 levels (xs, sm, md, lg, xl) and 12 options each... 12^5 = 248832

is my math right? 248832 classes?

**Comment by oktalk** [comment]
This isn't feasible. You should look into CSS grid if you're interested in defining columns this way. Here's an example: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

**Comment by mdo** [comment]
Thanks, but this isn't feasible, so we'll be passing on it.
