### ISSUE TITLE
Dropdown component is never instaciated

### ISSUE THREAD

**Issue by ygatesoupe** [twbs/bootstrap#22595]
Hello,

I noticed in dropdown.js that Dropdown toggle method is not called through the _jQueryInterface mechanism

```javascript
$(document)
...
.on(Event.CLICK_DATA_API, Selector.DATA_TOGGLE, Dropdown.prototype.toggle)
```
Toggle() is the only public method. Therefore Dropdown component is never instanciated. It doesn't prevent it to work but this lacks of consistancy regarding others component. Or is there any special resaon I'm missing ?

Seen in v4

**Comment by Johann-S** [comment]
IMO it's because the only public method is toggle that's all but yes if toggle had more public methods we should add _jQueryInterface

**Comment by Lausselloic** [comment]
Yes toggle is (quite) the only public method, but today something goes wromg IMO.
Because all events (keydown and click) are managed by : 
```
$(document)
    .on('load',Dropdown._addAccessibility()) // Boosted mod
    .on(Event.KEYDOWN_DATA_API, Selector.DATA_TOGGLE,  Dropdown._dataApiKeydownHandler)
    .on(Event.KEYDOWN_DATA_API, Selector.MENU, Dropdown._dataApiKeydownHandler)
    .on(`${Event.CLICK_DATA_API} ${Event.KEYUP_DATA_API}`, Dropdown._clearMenus)
    .on(Event.CLICK_DATA_API, Selector.DATA_TOGGLE, Dropdown.prototype.toggle)
    .on(Event.CLICK_DATA_API, Selector.FORM_CHILD, (e) => {
      e.stopPropagation()
    })
```

So if you create your webpage with all component and classes all will work.

But if you'd like to create a dropdown on the fly and said ```$('#mydropdown').dropdown() ``` the _jQueryInterface will call the constructor, wich will call the 
```
_addEventListeners() {
      $(this._element).on(Event.CLICK, this.toggle)
    }
```

Wich only add click event listening, so we loose the keyboard event (I need to test it, will create a pen), and also unit tests use the _jQueryInterface, wich is never used by default in bootstrap.

So IMO, it's possible to keep an auto init for existing element wich will call the _jQueryInterface on document load, but put back all event handler into the plugin itself will be more robust?

**Comment by Johann-S** [comment]
In my PR (https://github.com/twbs/bootstrap/pull/22444) `toggle` method is called by `_jQueryInterface`

I'll close this because my PR will be merged soon 👍 

About what you said @Lausselloic , I checked on my PR (#22444) with this function : 

```javascript
function addDynamicDropdown() {
  var strDrop = ['<div class="dropdown">',
    '<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButtonDyn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">',
      'Dropdown dynamic',
    '</button>',
    '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">',
      '<a class="dropdown-item" href="#">Action</a>',
      '<a class="dropdown-item" href="#">Another action</a>',
      '<a class="dropdown-item" href="#">Something else here</a>',
    '</div>',
  '</div>'].join('');
  $('.container').append(strDrop);
  $('#dropdownMenuButtonDyn').dropdown()
}
```
And every keyboard events worked.

**Comment by Lausselloic** [comment]
Oh what a good news! I'will wait for the PR to be merged. Thanks

**Comment by Johann-S** [comment]
It works too with the current version of `v4-dev` branch 😉
