### ISSUE TITLE
Dropdown menu right and dropdown with min-width misplaced

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#22653]
Dropdown menu right and dropdown with min-width misplaced

https://codepen.io/danijelGombac/pen/eWLmOK

**Comment by Johann-S** [comment]
Issue with navbar will be fixed by : https://github.com/twbs/bootstrap/pull/22644

Please note to use `.dropdown-menu-right` use the recommanded markup see : https://v4-alpha.getbootstrap.com/components/dropdowns/#menu-alignment and
`.dropdown-menu-large` don't exist on Bootstrap

But yes they are an issue with `.dropdown-menu-right` 
![image](https://cloud.githubusercontent.com/assets/1689750/26263133/ae7d847a-3cd7-11e7-87b5-c5ec735f38b2.png)

**Comment by Johann-S** [comment]
@danijelGombac can you check this PR : #22664 ?

**Comment by danijelGombac** [comment]
I try dropdown right with links and with form, both with different min-width and i think that works perfect.

**Comment by Johann-S** [comment]
I have some tests to do with dropup before merging this PR

**Comment by Johann-S** [comment]
@danijelGombac the two PRs which handle your issues have been merged, if the problem with the navbar is still present do not hesitate to /CC me 😉
