### ISSUE TITLE
Dialog width - media rule

### ISSUE THREAD

**Issue by matejlednar** [twbs/bootstrap#22668]
Current CSS
@media (min-width: 576px)
.modal-dialog {
    max-width: 500px;
    margin: 30px auto;
}

Dialog's width is too small on bigger screens.

Maybe it should be:

@media (max-width: 576px)
.modal-dialog {
    max-width: 500px;
    margin: 30px auto;
}

similar problem with form-group

**Comment by mdo** [comment]
Those sizes are correct. They were changed in #21207.

**Comment by bakasmarius** [comment]
The problem is not with the sizes themselves, but rather applying css **from** a certain size: 
@media (**min**-width)
instead of **to** a certain size: 
@media (**max**-width)

I currently have an issue where the CSS below gets applied to a modal on a screen which is 1920px wide and if change the CSS from **min** to **max** in Chrome DevTools, everything works as expected
```
@media (min-width: 576px)
.modal-dialog {
  max-width: 500px;
  margin: 30px auto;
}
```
