### ISSUE TITLE
form-control-success icon doesn't always appear

### ISSUE THREAD

**Issue by Neve12ende12** [twbs/bootstrap#22696]
Sometimes the checkmark shows up, sometimes it doesn't.  Am I doing something wrong? While working on the example, I appeared that the problem seems to only occur when the input is in a modal.

[Example](https://jsbin.com/levujopira/1/edit?html,js,output)
![image](https://cloud.githubusercontent.com/assets/6911359/26603340/1ae840f6-454c-11e7-8199-efaba1a6f6b3.png)

Bootstrap: 4.0.0-alpha.6
Browser: Microsoft Edge 38.14393.1066.0
OS: Windows 10 Pro 1607

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Neve12ende12** [comment]
@Johann-S Updated original comment

**Comment by mdo** [comment]
Your example appears to work for me—I see the icon every time.

**Comment by Neve12ende12** [comment]
@mdo I've updated original post with screenshot of missing checkmark icon.

**Comment by wolfy1339** [comment]
Confirmed working on Microsoft EdgeHTML 15.15063 (Microsoft Edge 40.15063.0.0)

**Comment by mdo** [comment]
Will revisit with #22762.

**Comment by jimjaeger** [comment]
Using bootstrap 4.0.0-alpha.6 SCSS file with angular 4 CLI app.

Hi,

today I have the same issue that was reported in #22696. The form input validation icons have not been shown in the browser. I analyzed why it happen and the browser (chrome) mentioned invalid property in the debug console and also ff could not load the inline svg markup.

In contrast to the local SCSS loading that does not work I saw that the the bootstrap 4 examples in the docu (https://v4-alpha.getbootstrap.com/components/forms/#examples works) for me in the same browsers.

In error case:
The Chrome show the following CSS snippet in the debug view (maybe already decoded). That is indeed not correct: 
background-image:
"data:image/svg+xml;charset=utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'><path fill='%235cb85c' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/></svg>"

The url(..) surrounding is missing.


In good case from the example page:
The browser shows  url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%235cb85c' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3E%3C/svg%3E")

that contains the url surrounding..

---------
Analysis result:
After I had a example for working and not working example I changed the css snippet in the _forms.scss and replaced the form-icon-success variable with the working url(..) sample and after it it also works in the not working example. It indicates that the variable replacement does not work correctly in this case.

Can we reopen the issue here?
