### ISSUE TITLE
Transition weirdness from disabling inputs/buttons

### ISSUE THREAD

**Issue by langdonx** [twbs/bootstrap#22784]
https://jsfiddle.net/langdonx/enztjawz/

The `transition` on `.btn` has it appearing disabled slightly behind its neighbors.

Is there anything that can be done to also transition the inputs to disabled, or is that a browser thing that we have no control over?

**Comment by dillonchanis** [comment]
The `.btn` class has a transition duration of 0.2s while the `.form-control` class has transition of 0.15s which is why you're seeing the delay.

You could just override the CSS of the `.btn` or `.form-control` classes to match like so:
[https://jsfiddle.net/enztjawz/3/](https://jsfiddle.net/enztjawz/3/)

Not sure if that was intended, if needed I could submit a PR for it to update transitions to all match but its a quick fix to do in your own CSS file.

**Comment by mdo** [comment]
Transitions matching as of e7ae1d90698a618d4c7847621c50a13ce31ae7f9.
