### ISSUE TITLE
[Bootstrap 4.0.0-alpha.6] Modal displaying under modal backdrop when wrapped in a fixed element

### ISSUE THREAD

**Issue by desirelabs** [twbs/bootstrap#22801]
Description : using modal within a fixed html element makes the modal backdrop appearing on top of all elements, including the modal box itself.
This behaviour makes modal unusable in fixed top navigation for instance.

![image](https://user-images.githubusercontent.com/24223583/27027915-68668b50-4f63-11e7-8ac0-60f1da953545.png)

Bootstrap version : 4.0.0-alpha.6
Operating system : Ubuntu Gnome 16.04
Browsers : Chrome 59, Firefox 53, Opera 45
Reduced test case : https://codepen.io/neovea/pen/JJYebg

**Comment by dillonchanis** [comment]
I believe the issue here as to do with stacking context.  The `.modal` class itself has a `position: fixed` alongside a `z-index: 1050`.  The `.modal-backdrop` class also has `position: fixed` but with a lesser z-index of `z-index: 1040`.  This isn't unique to Bootstrap 4 either, you will come across the same issue utilizing Bootstrap 3 modals.  

In the documentation a modal is seen used within elements that have a `relative` positioning.  Elements with `position: relative` and `position: absolute` have a higher stacking context than those of `position: fixed` or `position: sticky`.  If you changed your `modal-component` class to have a `position: sticky` you would see the same issue arise. [More on stacking context here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context)

To remedy, if your parent element is going to be of `position: fixed` or `position: sticky` also provide it with a `z-index: 1050`.

**Comment by dreamingrainbow** [comment]
just wanted to thank @dillonchanis for z-index:1050 on the element with fixed.. I have a fixed footer.. and this fixed it in  v4.0.0-beta.2

**Comment by MartijnCuppens** [comment]
closing this, see https://github.com/twbs/bootstrap/issues/23916#issuecomment-364618947
