### ISSUE TITLE
Modal issues

### ISSUE THREAD

**Issue by sidewinderZ** [twbs/bootstrap#22906]
I have a modal and I get this error when opening it:

Uncaught Error: Modal is transitioning

This may be the cause:

bootstrap.min.js:7 Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)

There should be information on tether requirement on Bootstrap download page and there isn't.

Now when including tether after jQuery and before Bootstrap:

Uncaught TypeError: $(...).modal is not a function

I don't know what to say except that the person responsible for this should be immediately kicked out from the project and not be allowed to contribute ever again.

**Comment by denormative** [comment]
https://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start

Looks to be clearly there to me, both in cut and paste and starter template.

Also, for someone on such a high horse, you really need to follow the bug reporting guidelines, you did read them right? https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Specifically the section that mentions: "A good bug report shouldn't leave others needing to chase you up for more information."

So which page are you referring to that is supposedly missing this information? Because the first one I looked at spells it out clearly.

**Comment by rafalp** [comment]
I would actually start with searching the issue tracker:

#22372, #22334. #22314, #21743, #21727, #21687
