### ISSUE TITLE
[meta] This project needs actual management

### ISSUE THREAD

**Issue by bootstrapisajoke** [twbs/bootstrap#23027]
Okay, so the point of this issue is to try and understand what is _actually_ happening with Bootstrap regarding versioning and when we're actually going to get a release of v4.

Some primers:

When 3.3.0 was [released](http://blog.getbootstrap.com/2014/10/29/bootstrap-3-3-0-released/) way back in 2014, we got our first indication version 4 was under development.

Version 3.0 was released August 19th 2013, a whopping 1420 days ago. 3.3.9 was released 349 days ago.

Let's be clear: the latest _stable_ version is almost 1 year old, and version 4 has been in 'development' for 984 days!

I am sure the wider community can understand why, and how, this is a _massive_ problem for anyone wanting to use bootstrap in their project: use a year old version with bugs and potential problems, or use an alpha version that will include another 756 changes when beta-1 drops.

Laravel has LTS/known release schedule
NodeJS has LTS/known release schedule
Angular 4 now has LTS/known release schedule

Bootstrap is the exception. Seemingly mdo decides at his whim when to release changes and what those changes will include. Looking at themeforest and other sites, alpha's of this project are being _**sold**_ and I challenge everyone to use the latest bootstrap CSS and not have many things broken between each release.

What is going on here? When is version 4 going to actually be released to sable, if ever? Do we have a known release schedule or is it when this random internet dude can be bothered? How do actual people who are meant to use this do so when you are NEVER supposed to use alpha level software.

At the moment, bootstrap is a complete joke in the web community, it's time you got serious.

**Comment by marcoarib** [comment]
Joke is people like you, bastard! Bootstrap is a wonderful job of people who do it without receiving any penny. Everyone has their own life, their problems and they do their best to maintain the best framework on the internet.

If you are not satisfied with the progress of version 4, help the project. If you do not want to help, use version 3. If you're still not satisfied, go get something useful to do. If you can not find anything to do, go to hell and stop criticizing the serious work of others.

**Comment by jipexu** [comment]
Hi
this seems to me a little be acid ... dont be hurry you will finish as every one in dust ...
at some point i agree with you
yes it's long, sometime frustrating but let say it's surely the sign of a great projects ! 

What is a complete joke  in the web community ? 
- a project forked 52000 times

yes it's time to be serious ...

**Comment by Mustafa-Online** [comment]
As my self, i can wait forever to get it ..
btw, bootstrap 3 is working super fine & the current alpha too.
@bootstrapisajoke , you got all the options in-front of you, no one is forcing you to choose Boostrap.

**Comment by bootstrapisajoke** [comment]
> Bootstrap is a wonderful job of people who do it without receiving any penny

Yet they just launched "Bootstrap Jobs" which costs to be a job. Inform yourself [here](https://bootstrapjobs.zendesk.com/hc/en-us/articles/115008143987-How-much-does-it-cost-to-post-a-job-). $300 for 30 days. No money my ass.

> If you are not satisfied with the progress of version 4, help the project

I am not a maintainer, but I see pull requests open for more than a year that have been ignored. The v4 [PR](https://github.com/twbs/bootstrap/pull/17021) has been open since 2015; this project is not suitable, or maintainable by 1 individual, that's just arrogance to think so.

 > and stop criticizing the serious work of others.

People are allowed to openly criticize google for the state of Angular but not Bootstrap? Because poor mdo working at github amirite? I am not being unfair, or raising invalid concerns. It's a version of a software that's got no plan or foundations. But apparently they have a ["core team"](http://getbootstrap.com/about/) that are completely dysfunctional. Do you forget the [leftpad](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) disaster? People actually use and rely on open source, it's not unfair to have expectations, free or not.

> a project forked 52000 times

That just shows the main fork is so obviously, clearly not fit for purpose. Angular has 6,531 forks. Node has 7162 forks.

So yeah, people are forking because those maintaining this repo have absolutely no idea what they're doing and how to manage software in the modern ecosystem. 

You NEED an LTS.
You NEED clear and concise release times.

Or, you can be like NodeJS, which was so terrible IO.js had to come and be their saviors.

Get with the times or get left behind, we know what twbs is choosing to do.

**Comment by bardiharborow** [comment]
I'm sure that a detailed response will be provided to this in due time, and I may provide one myself tomorrow, but I would like to remind you that abuse toward any individual or group is not tolerated by [GitHub's terms of service](https://help.github.com/articles/github-terms-of-service/). While it is 3am in my timezone, and my tolerance for such things is significantly lowered, I'm awfully close to locking this issue. I have been highly demotivated with Bootstrap recently, and feeling guilty from my possibly poor management of some of the build system upgrades hasn't helped. I will reach out to the rest of the team internally over the next few days and I'll see what the plan to get back on track is, but please understand that I am doing so as a volunteer, and because I want to, not because you feel that you are entitled to free work. I can't speak for mdo, but I receive no money for any of this. Please go read #22576, especially the blog post linked.

**Comment by marcoarib** [comment]
> Yet they just launched "Bootstrap Jobs" which costs to post a job. Inform yourself here. $300 for 30 days. No money my ass.

How much you pay to use the Bootstrap Framework? As far as I know Bootstrap is under the MIT license. You need a course of text interpretation.

> I am not a maintainer, but I see pull requests open for more than a year that have been ignored. 

Again, if you not satisfied, help the project and stop to be a completely useless guy. If you'll do not want to help, you can use "Semantic UI", "UI Kit" or "Foundation". Go to be a useless guy there.

Since you came here to write "bootstrap is a joke", you show to everybody that you are not a serious guy.

**Comment by rafalp** [comment]
> At the moment, bootstrap is a complete joke in the web community, it's time you got serious.

This is it gals and guys! Bootstrap is officially so popular it has anon haters get to GH issues to Q.Q!

![Awww yisss](https://68.media.tumblr.com/18be1e27e3139ec087339c2d310de958/tumblr_inline_nipn5siX3g1rp0n6u.gif)

**Comment by mdo** [comment]
> Okay, so the point of this issue is to try and understand what is actually happening with Bootstrap regarding versioning and when we're actually going to get a release of v4.

Well, you could've just asked :). I'm an open book and I like hearing how I could be doing things better.

> Let's be clear: the latest stable version is almost 1 year old, and version 4 has been in 'development' for 984 days!

You've highlighted our major ships, yeah, but what's your point? Just because it's a few years old doesn't mean it isn't stable, widely used, and still helping folks build things for the web.

> I am sure the wider community can understand why, and how, this is a massive problem for anyone wanting to use bootstrap in their project: use a year old version with bugs and potential problems, or use an alpha version that will include another 756 changes when beta-1 drops.

Folks have been using the alpha releases for years. But yeah, it'll be a huge upgrade—just like v3 was when we shipped it. I honestly don't recommend upgrading—that's a monumental change for what is, in most cases, a dependency.

> Laravel has LTS/known release schedule
> NodeJS has LTS/known release schedule
> Angular 4 now has LTS/known release schedule
>
> Bootstrap is the exception.

Bootstrap isn't those other projects, why would it be anything like them? You're comparing apples to oranges. It'd be nice to have a release schedule. I don't work full-time on this. No one does, no one ever has. That makes it more difficult to schedule things. Not impossible, but difficult.

> Seemingly mdo decides at his whim when to release changes and what those changes will include.

As the creator and maintainer, yes, I do decide when we release. Would you like someone else to decide?

> Looking at themeforest and other sites, alpha's of this project are being sold...

None of that is new. Folks have been profiting from Bootstrap for years, for v3 and v4. I think it's great that people are building business models on top of the code myself and hundreds of others have contributed to.

> and I challenge everyone to use the latest bootstrap CSS and not have many things broken between each release.

v4 has only been alpha releases—yes, things will break between releases. That's why we're in alpha.

> What is going on here? When is version 4 going to actually be released to sable, if ever? Do we have a known release schedule or is it when this random internet dude can be bothered? How do actual people who are meant to use this do so when you are NEVER supposed to use alpha level software.

Yes, v4 will be will be stable soon, and that starts with the beta. I expect the beta releases to go much quicker given ideally nothing should be getting rewritten.

> I am not a maintainer, but I see pull requests open for more than a year that have been ignored. The v4 PR has been open since 2015; this project is not suitable, or maintainable by 1 individual, that's just arrogance to think so.

I'd love more folks to help. Like @bardiharborow mentions, it's hard to bring people into the project and encourage them to stick around. It's a massive project that most folks don't want to stick around to contribute to long term. I'd love to fix that somehow, and I've lost a lot of sleep to thinking about ways to fix that.

> Do you forget the leftpad disaster?

Yup, couldn't tell you anything about it. Honestly, I have no idea what leftpad is.

> You NEED an LTS.
> You NEED clear and concise release times.

You're spending a lot of time telling me what to do. That's fine, I don't mind it and know how to take it. But this conversation could've been entirely different had you asked instead of demanded.

> At the moment, bootstrap is a complete joke in the web community, it's time you got serious.

You're going to tell me a project that's apparently [used by ~4% of the entire internet](https://trends.builtwith.com/docinfo/Twitter-Bootstrap) is a joke? Something I've worked on for over six years of my life is a complete joke? Something that folks love to use, that may have made a difference on a project, that made something people were building possible, or maybe even just a little better or easier? Yeah, it's a complete joke.

People poke fun of Bootstrap because it means somethings look the same on the internet. Or because I've worked on v4 for over two years and that's somehow the worst thing ever in open source. Or because I stopped supporting v3 so I could focus what time I have on this project while also managing a 30 person design team at GitHub and trying to have some kind of life outside both those.

I don't say these things for pity or sympathy. I don't expect it, don't deserve it, and I don't want it. But next time, just ask me. Share your opinion, ask questions, provide helpful criticism, make suggestions, and don't be a jerk about it.
