### ISSUE TITLE
Communication transparency

### ISSUE THREAD

**Issue by dawidadach** [twbs/bootstrap#23120]
Dear Bootstrap Team, 

I can't emphasize more, how much I appreciate what you guys are doing here. Bootstrap is a fabulous piece of code which, let's be honest, has dominated it's part of the market. I've been using it since v 2.0.2 and felt in love since day 1. 

However, 
since few months I see some communication gap between @mdo and other team members and rest of the world. I know that this project is big and it needs time. I'm also aware that no one is working in it full time, it's side project very extensive, though. I am pretty sure that everyone understands that this is taking time and even Beta will take another 2 months, that's fine. However, 1 thing which makes me uncomfortable is a lack of any communication. Project status was jumping on and of 99% for months. Bootstrap slack also doesn't help, I've seen many questions about some deadlines but they never got a clear answer. 

I've been browsing lot, I even started following you guys on twitter and got excited every time when you posted anything regarding Beta ;) But from what I can see there are more and more people getting frustrated about the fact that there are no clear guidance nor roadmaps.  I see that I am not the only with this feeling:

https://github.com/twbs/bootstrap/issues/23054
https://github.com/twbs/bootstrap/issues/23027

I know that the best thing we could do is to contribute and believe me, along with my team we committed multiple PRs, however since few weeks although we would like to help we have a feeling that there is not much we can do. I am only getting suggestions to work on other issues but without clear roadmap my team and I we are losing motivation and hope that Beta will be ever released :( 

What I would expect to hear from @mdo is either:
- We want to release BETA in 2 weeks time, this list of open issues which have to be fixed, we have to configure new servers, CDN docs, and few other administrative tasks. You can help with point 1 and 2, the rest is mine.
or 
- There are too many new issues showing that current version is not stable so we will not release BETA until September or later. 

Anything would be better than an answer like "Beta will be ready when it will be ready".

**Comment by BFSzymanski** [comment]
I couldn't agree more. 

I love Bootstrap and I truly appreciate all the amazing work you've done guys.

But please, provide us a proper communication. 

I suppose it's not the biggest challenge of your life.

Just tell us what's going on, what we can expect and how we could help to get the things done.

**Comment by Ruffio** [comment]
A good idea for clarity for everyone would be to create 'issues' for all remaining issues/tasks and mark them with the milestone. Then everyone can see the progress and what is left, and then we avoid all/a lot of al these questions/responses about release date. I think that the most frustrating thing for people is that if you look here at GitHub, then it looks like everything is set and done and ready to be shipped, and have looked that way for some time. If everyone could see that there are issues/tasks remaing, then there would be no need for all/a lot of there release date questions IMHO.

**Comment by dawidadach** [comment]
@Ruffio , there is such milestone, however since weeks it's almost done:
https://github.com/twbs/bootstrap/milestone/41
As you said, it looks like everything is ready, however, I can understand the bootstrap team that there is still a lot of work not related to code itself but all supporting stuff like hosting etc. 
The point is that those things are not communicated to other contributors so since few weeks we don't have clue what is going on and it seems that @mdo is the only one who knows what is going on...

**Comment by bardiharborow** [comment]
> I am only getting suggestions to work on other issues but without clear roadmap my team and I we are losing motivation and hope that Beta will be ever released

As I said in #23054, if your team is being heavily inconvenienced waiting for us to ship the beta, then you probably should have already pulled the code from git (everything you need is in the `dist` folder) and moved on. Bootstrap is primarily CSS. It either works for you or it doesn't. There are minimal security implications to running bleeding edge CSS, and the worst thing that will happen is you'll get a version with a few unresolved bugs – which if you are very unlucky might be browser specific (you do have cross-browser testing, don't you). There's some minor risk running bleeding edge JS, but it's not a major issue in the scheme of things.

> There is such milestone, however since weeks it's almost done: https://github.com/twbs/bootstrap/milestone/41

You are correct that the place we would normally put the list of remaining pre-ship issues is the v4.0.0-beta milestone. The problem currently is that there are rough edges all over the place. These are generally easy to fix _once we find them_, but until we find them we can't put them on the milestone and after they've been fixed then they're not outstanding on the milestone again (hence why it's always sitting at 99% complete). If you do want an idea of what's remaining, it's this sort of stuff:

* Confirm that `github` variant of documentation functions correctly.
* Confirm that examples are up-to-date.
* Confirm that build tooling documentation is up-to-date.
* Confirm <insert component/documentation page/other critical thing> isn't broken.

There is an internal checklist for shipping, and I can confirm that the shipping issue was opened recently but has not currently been assigned a date. If you want a timeline, we're looking at closer to 2 weeks than September, but as always, I can't provide any guarantees.

> Bootstrap slack also doesn't help, I've seen many questions about some deadlines but they never got a clear answer.

You are very welcome to ping me there any time, and I'll give you the clearest answer I can. There is however, no deadline. We simply don't have enough resources as a volunteer project to have deadlines.

**Comment by rafalp** [comment]
I'll play *advocatus diaboli* here, but indulge me.

> Anything would be better than an answer like "Beta will be ready when it will be ready".

Imagine you are open source developer. Your working on project depends largely on those two factors:

- you have time
- you feel like it

For example one thursday you'll find 30 minutes for your project. You are back from work, somewhat exhausted, but you eat something, do fast cleaning around your hose, then open up GitHub and see new issues. You go them one by one. First one was easy - it was answered plenty of times and issue's opener didn't search for dupes before opening his. You close it as dupe and move on to next one. It seems something new, so you look up the part of code that you've or somebody else wrote 4 months ago and try to remember the context it was made. You sit on it and sit and sit and whoops, its already an hour, times up, your turn to take the dog for a walk and get dinner going.

But next day... next day you'll get to it for sure! ...only that the next day you've had hard day at work. You come back home, do the chores and just chill with your GF watching TV only once in a while peeking at Twitter with your mobile.

This day... man, this day's going to be yours. GF's out the town, she took the dog with her, you've slept well and ain't specially tired after the day of work. Chores can wait for tomorrow! You sit to your computer, look up that issue... and with today's mind it seems like something bigger than you've originally tough. You mark it for future release and move on to PR reviews. First PR reviewed... second one... woops, time's up, gotta call it night.

On friday you just sit down to chill after week. Weekend is great time to take of all the things you've put aside during week! This means doing shopping for home, taking car to shop, pet to vet and then your family drops with a visit.

Monday after work you just chill with games because you were absolutely not in the mood to on your project.

> Beta will be ready when it will be ready

Looking above, what approach do you want to use to estimate, even roughly, release date? Estimates make sense when effort put into project is constant and predictable, like in work when you drop it at 9, put 4 hours, break, another 4 hours for 5 days a week.

What if @mdo went "sure, we'll ship beta in two weeks" but couldn't find time for working on it? What if he said "we'll ship by September" but he shipped in August or October? I'm sure people would still drill into him for breaking the word and ruining their plans.

You need to assess all the risks. Its your responsibility alone to decide if technology mets requirements you have to work for your team or your project.

On side note, I've always considered waiting or betting on something not released yet irresponsible.

**Comment by dawidadach** [comment]
@rafalp , thanks for touching story, however it doesn't add anything new to this subject. 

I am not sure if you read my post carefully (or enough carefully) to notice that I didn't blame @mdo or any other core team member for not working on a project or working not hard enough. Actually, I said something exactly opposite and let me repeat that - I truly admire what those folks did for web development society especially, taking into account that this is their side project. 

However, this doesn't change fact that this is a project, and the project requires planning. Of course planning might be wrong, and deadline missed but still, any planning is better than none. And planning doesn't mean hard deadline. @mdo could simply say, that beta will be shipped once those tasks will be finished and provide us with the list of tasks which has to be done. The problem now is that this list of a task doesn't exist (or actually is marked as done) for a long time and product stuck at 99%. Me and many others folks which I know in person would like to help but currently, there is nothing we could do. 

And before you will say that we can work on issues, please consider that it isn't as simple. There are still plenty of open issues, each PR has to be reviewed by someone from the team. All issues/PR should pass new tests, which is again extra work to be done. Not to mention backward compatibility, regression tests etc. etc. Therefore if we think of stable release, that is kind of right. However, from Beta perspective, there has to be a thick line saying what will be included and what not (and will be fixed in next releases). Otherwise, we will skip Beta and go directly to a stable release. 

Bootstrap is yet another project, regardless whether it's open source or not it has to managed in some ways. And please do not manipulate my words - I didn't ask @mdo to provide us with hard deadline since we all know that this is a side project, what I asked was: 

> We want to release BETA in 2 weeks time, this list of open issues which have to be fixed, we have to configure new servers, CDN docs, and few other administrative tasks. You can help with point 1 and 2, the rest is mine.

This would clearly say what is ETD, what has to be done and what can be expected. Even if miss deadline, it would be clear why (not all tasks completed) and what to do to release it. That would be also an anwer for all haters - want beta faster? Do this and that.  And again - even if the answer would be - I don't have time now, don't expect Beta before Autumn it would be better than keeping beta at 99% and giving the impression that it will be released soon. Whether you like it or not this project has a huge impact on web development (and this is something which entire Bootstrap team should be proud of), but huge impact implies also a huge responsibility. I believe that many customers is confused whether they should stick to B3, B4A6 or wait for Beta...

**Comment by rafalp** [comment]
> thanks for touching story, however it doesn't add anything new to this subject.

Oh but it does. It provides context that people like you lack, requesting again and again for this project to be ran little more like commercial projects, with roadmaps, schedules, dates and full regalia thats impossible to do here. But every guy here has his own little slice of above pie that he or she considers important to them, so why your's should be one given?

> I am not sure if you read my post carefully (or enough carefully) to notice that I didn't blame @mdo or any other core team member for not working on a project or working not hard enough.

This is nice, but this isn't private exchange between you and core. This is up here changing for everyone to see. And if mdo would've answered it, you can bet that answer would be up here trending on reddit and hacker media in no time with other people holding its author to the word.

@dawidadach I know perfectly well where you are coming from. You've build your business around Material Boostrap, and now you are expecting some, however small, liability from BS guys for you to carry on with your business, even if you knew it well that this is Open Source project with no guarantees, warranty and liability not only promised but even written in its license.

**Comment by dawidadach** [comment]
I totally agree that this is not the place for personal discussion so let me just rephrase my original thought since it could be misread. 

I don't want to put ANY pressure on the team it's not about pushing Beta to come faster. What I wanted to ask is to have a more precise statement/expectation about delivery time. 

If @mdo would reply - I am going for holidays for 2 weeks, and forget about the beta within coming month, that's perfect, I know what to expect (or actually to not expect), fair and square and much more comfortable than having Beta opened for 99%.  That's it, nothing more.


And yes. I do use bootstrap in my business, and I hope that isn't something wrong ;)

**Comment by isapir** [comment]
Just a side note here:  @patrickhlauke [convinced me a few weeks ago](https://github.com/twbs/bootstrap/issues/19403#issuecomment-312072126) that I should look for other alternatives to Bootstrap.

I looked into Zurb Foundation and I love the features, communications, video tutorials, and everything else that it offers, so I decided to switch my next project to [Foundation CSS](https://github.com/zurb/foundation-sites/) rather than wait indefinitely for Bootstrap 4.

I have used Bootstrap 2 and 3 in the past, and I think that @mdo and @fat did a great job there and I'm thankful for that; but it seems that recently @mdo is busy, which is very understandable, and the project may have been "hijacked" by...  I think I'll stop there.
