### ISSUE TITLE
Google Safe Browsing warning when downloading the release bundle.

### ISSUE THREAD

**Issue by richiwarmen** [twbs/bootstrap#23148]
See http://getbootstrap.com/getting-started/#download

with link: https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip

Act as Phishing site in Google Safe Browsing

**Comment by bardiharborow** [comment]
Works for me, and Google Safe Browsing [reports the URL is clean](https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip). Could you provide details of your browser (go to `chrome://version`) and if possible, a screencast of this happening.

**Comment by richiwarmen** [comment]
Google Chrome | 59.0.3071.115 (Officiële build) (64-bits) (cohort: Stable)
-- | --
Revisie | 3cf8514bb1239453fd15ff1f7efee389ac9df8ba-refs/branch-heads/3071@{#820}
Besturingssysteem | Windows
JavaScript | V8 5.9.211.38

screencast
https://www.screencast.com/t/Kwhu6wA4KZJe

**Comment by Skyost** [comment]
[Same](http://i.imgur.com/2xhleDd.png).

**Comment by richiwarmen** [comment]
i did request to google:
https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

**Comment by mdo** [comment]
Very strange. Nothing has changed there for like two years haha.

**Comment by patrickhlauke** [comment]
going to assume that it's something to do with the https cert not applying to the amazon aws URL or something?

**Comment by bardiharborow** [comment]
Okay, I didn't realise that `github.com` was redirecting to `github-production-release-asset-2e65be.s3.amazonaws.com`, but that URL is reporting as clean as well. That error message is definitely a Safe Browsing warning, rather than a simple certificate mismatch. That being said, can those effected confirm that their computers are clean of malware, and that the SHA-256 fingerprint of `github-production-release-asset-2e65be.s3.amazonaws.com`'s certificate is `65 9A 3D 76 84 85 0E 6D 66 4F 51 31 F9 F8 76` (and hence you are not currently subject to a MitM attack).

**Comment by krisives** [comment]
Me and three people had this last night as well for any releases downloads hosted on Amazon S3

**Comment by XhmikosR** [comment]
Does this still happen with Chrome 60?

**Comment by richiwarmen** [comment]
All good here now 👍

**Comment by XhmikosR** [comment]
Cool, closing then. 👍
