### ISSUE TITLE
Missing semicolon at the end of bootstrap.js causes issues when bundled with other scripts

### ISSUE THREAD

**Issue by judowalker** [twbs/bootstrap#23175]
I am bundling `bootstrap.js` with other scripts and I get a runtime error which I found out is due to a missing semicolon at the end of `bootstrap.js`:
https://github.com/twbs/bootstrap/commit/ba312c20a5ceca42117dd53303bafda485d8facd#diff-5492e5c74c97b8b5256879d136b55c88R3631

Only the unminified file is missing the semicolon.

**Comment by XhmikosR** [comment]
That is why I don't like the no semi approach, personally. That being said. can't we just add the end of file semi [here](https://github.com/twbs/bootstrap/blob/v4-dev/build/stamp.js#L32)?

**Comment by Johann-S** [comment]
Yes that's just a mistake from `stamp.js` (Babel add semicolons to our dist files see : https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.js#L97) and when https://github.com/twbs/bootstrap/pull/22888 will be merge `stamp.js` won't exist 😄

**Comment by XhmikosR** [comment]
I believe that until that is merged we should fix it in dev branch. Because
as you know that might a while to merge...

On Jul 31, 2017 11:03, "Johann-S" <notifications@github.com> wrote:

Yes that's just a mistake from stamp.js (Babel add semicolons to our dist
files see : https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/
bootstrap.js#L97) and when #22888
<https://github.com/twbs/bootstrap/pull/22888> will be merge stamp.js won't
exist 😄

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/issues/23175#issuecomment-318996746>,
or mute
the thread

**Comment by XhmikosR** [comment]
I'm going to submit a PR later unless you beat me to it.

On Jul 31, 2017 11:26, "XhmikosR" <xhmikosr@gmail.com> wrote:

I believe that until that is merged we should fix it in dev branch. Because
as you know that might a while to merge...

On Jul 31, 2017 11:03, "Johann-S" <notifications@github.com> wrote:

Yes that's just a mistake from stamp.js (Babel add semicolons to our dist
files see : https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootst
rap.js#L97) and when #22888 <https://github.com/twbs/bootstrap/pull/22888>
will be merge stamp.js won't exist 😄

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/issues/23175#issuecomment-318996746>,
or mute
the thread
