### ISSUE TITLE
overflow on Internet Explorer 10

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23172]
So I was trying v4-dev docs locally with Internet Explorer 10 and I noticed this:

![28716442-f6cf1aa4-73a5-11e7-9dc1-c05c7a5fcf48](https://user-images.githubusercontent.com/349621/28753249-5f973eaa-753a-11e7-8a69-b32c9501519e.png)

I narrowed down to `.bd-docs` column. Also, the issue goes away if I remove `.flex-xl-nowrap` from the parent row.

On a project of mine I have switched to v4, I also have this issue in a row like this:

```html
.container-fluid.mt-6
  .row.justify-content-center
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
    .col-12 col-sm-6 col-lg-3 mx-auto card-deck
```

Probably not the same issue since this one goes away if I remove `justify-content-center`. If that's confirmed I should make a new issue for this to track it.

/CC @Johann-S @mdo

**Comment by XhmikosR** [comment]
Ok, about the second issue I'm having it's due to https://github.com/philipwalton/flexbugs/issues/117

Not sure if there's something we can do.

**Comment by MartijnCuppens** [comment]
This is actualy caused by `max-width: 320px;` (in /assets/scss/_sidebar.scss). This can be solved in IE11 by adding this below the max-width: `-ms-flex-preferred-size: calc(#{percentage(1 / 6)} - #{$grid-gutter-width});`

However, this doesn't solve the issue for IE10. We can set `-ms-flex-preferred-size` to `200px` which would set the sidebar-width to `200px` for IE10 and IE11.

Or make use of this media query to disable max-width for IE10/IE11:
https://philipnewcomer.net/2014/04/target-internet-explorer-10-11-css/

**Comment by XhmikosR** [comment]
Thanks for digging into the issue @MartijnCuppens. I guess I'll let @mdo decide how to proceed. Other things are broken in IE due to flexbox bugs so I'm not sure if he even wants to fix this.

I just wanted to track the issue.

**Comment by XhmikosR** [comment]
@mdo: is @MartijnCuppens's solution above acceptable for you?

**Comment by mdo** [comment]
I totally missed this. If that's a valid fix and the problem still exists, I'm down.

**Comment by Herst** [comment]
The IE11-only workaround would make it a candidate for mentioning at #25100.

**Comment by XhmikosR** [comment]
@mdo: yup, still happens.
