### ISSUE TITLE
Add a test to verify the SRI hashes

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23287]
So that we don't hit https://github.com/twbs/bootstrap/issues/23284 in the future.

**Comment by kylejrp** [comment]
I think I could probably take this on! I'm new to contributing to open source, so I appreciate any help you can give.

To summarize my understanding of the problem:

- `_config.yml` contains variables that reference bootstrapcdn files and their SRI hashes:
https://github.com/twbs/bootstrap/blob/8896827bd072a120705a0576a5bcde69c8ce2cda/_config.yml#L50-L59
- The command `npm run release-sri` is manually run before a new Bootstrap release to generate the hashes of each of these files using `generate-sri.js`. 
https://github.com/twbs/bootstrap/blob/8896827bd072a120705a0576a5bcde69c8ce2cda/build/generate-sri.js#L27-L60
- Then, the output of `npm run release-sri` is manually entered into `_config.yml`

Since this is a manual process, it can get missed during new Bootstrap releases, so we want a test to catch it.

I have a few questions:
- Would the test be downloading the file from bootstrapcdn and verifying the hash? Won't this slow tests down significantly?
- If not, are we verifying the hash of the generated files at build time? If so, won't the hashes in the config file be invalid immediately after modifying any code?
- Where should this test live? A "meta" test like this doesn't seem to match the other tests in `js/tests`. Should I just add an extra script to be run in `npm run test`?

**Comment by XhmikosR** [comment]
1) it's not manual; it runs when we do `npm run release` and also on Netlify for previews
2) using BootstrapCDN is wrong because we can't test things before a release is made

**Comment by kylejrp** [comment]
Thanks for the response - that seems really obvious that it's not manual now.

I was confused because I thought the test would cover two cases:
1. File changes in the config file but hash doesn't
2. Hash changes in the config file but file doesn't

It looks like the hash always matches the build files, but it doesn't always necessarily match the file in the config file. I'm not sure which case #23284 was.

Anyways, it looks like there was some discussion about changing how these values were calculated or eliminating release-sri script in #28014, so I'll back off this issue for now.

**Comment by puzuwe** [comment]
Thanks XhmikosR for the contribution.

**Comment by bardiharborow** [comment]
@XhmikosR how did you want to handle between release dists, make them update the SRI or disable the test somehow or what?

**Comment by XhmikosR** [comment]
I'm not sure how to test this. I was hoping that linkinator would maybe break but I haven't tried it, so I'm not sure if that's the case.

**Comment by XhmikosR** [comment]
Note that now things are in better state compared to when I made the issue. We still don't test this, but at least it's done when we run the release script.

**Comment by XhmikosR** [comment]
Closing this since we are using the npm release script which takes care of the SRI hashes.
