### ISSUE TITLE
Redo input group borders

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#23379]
Recently merged #22612 is causing some rendering issues.
<img width="428" alt="screen shot 2017-08-12 at 6 36 41 pm" src="https://user-images.githubusercontent.com/98681/29245373-35c8e3d2-7f8d-11e7-9b8f-5e1d75fc135d.png">

**Comment by nwoltman** [comment]
@mdo I opened a similar issue in #23344.

I'm not sure if you seeing this the same way I am, but to me it looks like the border around the text box is darker than the one around the button. However, it turns out that they're the exact same color. The contrast between the dark button and the light text box creates the illusion that their borders are different colors and this illusion is accentuated by the extra dark border between the button and the text box (as described in #23344).
