### ISSUE TITLE
Non-custom checkboxes don't change with .is-invalid

### ISSUE THREAD

**Issue by K1N5L4Y3R** [twbs/bootstrap#23426]
When upgrading to 4.0.0.beta, I noticed that when I was trying to set up server side validation, inputs and custom checkboxes were working correctly when adding `.is-invalid`. However, non-custom checkboxes like the following were not.

```
<div class="form-check">
  <label class="form-check-label is-invalid">
    <input class="form-check-input is-invalid" required="required" type="checkbox">
    Text
  </label>
</div>
```

Is there a way to make regular (browser-styled) checkboxes look invalid with server-side validation (e.g. when not filled and required) or is this only reserved to custom checkboxes?

JS Bin: https://jsbin.com/ruzodunuqe/edit

**Comment by hiddewie** [comment]
I agree with this problem. I am reworking the validation HTML template as generated by Symfony together with BS 4 (see PR  symfony/symfony#21751). 

There is no good way to set an invalid radio button/checkbox, because of the sibling selector which is required to show the `.invalid-feedback` block containing feedback to the user. Radio buttons and checkboxes are nested in their own `<div>`. 

Adding `was-validated` to the whole form would not be a good option for my use case.

**Comment by mdo** [comment]
Ah crap, yeah, we might need to break the markup on the checkboxes :(.

**Comment by mdo** [comment]
Lol oh no... found this in the Sass file.

<img width="337" alt="screen shot 2017-08-14 at 9 25 18 pm" src="https://user-images.githubusercontent.com/98681/29302220-19930a8e-8137-11e7-9beb-ecdcd53e734b.png">

**Comment by mdo** [comment]
PR with potentially breaking change coming in #23444.
