### ISSUE TITLE
Problems in compile/webpack/build JS

### ISSUE THREAD

**Issue by nam-co** [twbs/bootstrap#23436]
Hi, thanks for launching the beta version, 
I’m using codekit to build a compile version of jquery..popper.. Bootstrap4 beta, and other plugins all downloaded using npm, but at first I was getting a popper error, I check the compile js file and popper but I got the error that it could not be found, then I notice that all the following scripts didn’t work, so I tried putting idependenty the same jquery, popper, B4 files and it works, after testing I found that the js that is breaking the whole file is the bootstrap.js file, any ideas? Is not a codekit thing because it was working 100% with the alpha version 

Appreciate any help

**Comment by Johann-S** [comment]
Bootstrap depend on Popper.js and jQuery so you should ensure that `Popper` is available in the global scope

**Comment by nam-co** [comment]
Hi Johann thanks for the response, all 3 js files are compile in the same file + other scripts, and then inserted in the webpage using <script.... the problem is that bootstrap.js breaks every ja code after

**Comment by liquidvisual** [comment]
I'm having this problem too, although I'm using a Grunt script with Bower instead of Codekit. Everything works fine at first - but after running **concatenate** and **uglify** all Bootstrap JS stops working without throwing any errors.

I'm wondering if there's something grunt-uglify is doing? Is the Popper code ES6 possibly? Can grunt-uglify not convert that properly or something? :/

**Comment by adampatterson** [comment]
Make sure that you load the proper version of Popper.js, I spent half an hour question why the thing would not minify.

I then realized that /dist/popper.js is an ES6 version...

I had to include the UMD version of popper.js in order for Code kit to work properly.

This was rather frustrating because Bower is not the tool for ES6 code IMO.

https://github.com/FezVrasta/popper.js

**Comment by Johann-S** [comment]
I hope @nam-co found a solution for his problem.
If not do not hesitate to use StackOverflow [see our readme for more details](https://github.com/twbs/bootstrap#community).
