### ISSUE TITLE
Bootstrap 4 print problem in Firefox

### ISSUE THREAD

**Issue by jevanlingen** [twbs/bootstrap#23489]
Printing multiple pages in Firefox does not work. Only one page is printed, the rest of the pages is missing. Seems it is a known issue for years within the Mozilla community: https://bugzilla.mozilla.org/show_bug.cgi?id=104040.

**Case**
The Bootstrap v4 [documentation](https://getbootstrap.com/docs/4.0/) page. 

**Compare**
Version 3 of Bootstrap does not have this issue, compare the [old docs](https://getbootstrap.com/docs/3.3/css/) for example.

**Comment by patrickhlauke** [comment]
![capture](https://user-images.githubusercontent.com/895831/29359784-e72d03c8-8277-11e7-8ecc-e63d7a5b5f9f.PNG)

**Comment by prateekgoel** [comment]
It's the `display:flex` in `.row` that's causing the issue. Setting `display` to block for `print` resolves this.
Can I work on this?

**Comment by mdo** [comment]
This doesn't appear to be an issue in Firefox 59 on Windows or macOS. Just printed to PDF to see and all the pages show.

**Comment by kcantwel** [comment]
I am seeing this exact same issue with Firefox 60 and Bootstrap 4.1.1.

**Comment by garthtee** [comment]
I see this issue also, but only when scrolling using arrow keys on my laptop when I use my mouse it's fine.

**Comment by dozer75** [comment]
The referenced issue in the original post is marked as duplicate of duplicate in their bug tracking system, so just adding the real tracked [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=939897) for Firefox which still after 5 years (!!!) isn't solved (they do have ways to reproduce it since it's not possible to print their own bug tracking system).

The solution to use `display: block;` wasn't a good solution for me since it mess quite a bit with element margin usage, I will rather advice our users to avoid using print capabilities in Firefox.

**Comment by Lowell130** [comment]
> It's the `display:flex` in `.row` that's causing the issue. Setting `display` to `block` for print resolves this.
> Can I work on this?

thanks work great!
