### ISSUE TITLE
v4 - Scroll in modal-body

### ISSUE THREAD

**Issue by marlonmleite** [twbs/bootstrap#23637]
The current modal scroll when content is too large occurs on the page and I understand that this is a bootstrap pattern.

Is there a possibility in v4 of the scroll happening in modal-body?
I understand that the scroll on the page is standard for Bootstrap, but the UX area in my company is not acceptable to the user.

Is there any native support in the bootstrap put the scroll in modal-body?

**Comment by prateekgoel** [comment]
I think we can have a class on modal to achieve this. However, fixed height would be required on modal content in that case. May be we can use viewport unit `vh`.
Also, the modal container could not be have round corners in that case. I would look like this because of scrollbar.

![image](https://user-images.githubusercontent.com/8016566/31054998-74084c9e-a6db-11e7-973f-077f830442f0.png)


Any thoughts on this?
@XhmikosR @Johann-S @patrickhlauke @mdo

**Comment by mdo** [comment]
No plans to add this to Bootstrap—it's straightforward enough with a `max-height` and `overflow-y: auto` on the modal element of your choosing.
