### ISSUE TITLE
The clip CSS property has been depreciated by the CSS Masking Module Level 1 draft.

### ISSUE THREAD

**Issue by lffg** [twbs/bootstrap#23659]
Hi there,

Please, read this at MDN:
-> https://developer.mozilla.org/en-US/docs/Web/CSS/clip

And...
-> http://prntscr.com/gcnd39

o/

**Comment by prateekgoel** [comment]
I see that there is clip used in sr-only mixins. Can i work on removing that and look for other option?

**Comment by bardiharborow** [comment]
I note that the replacement property `clip-path` is [poorly supported by browsers](https://caniuse.com/#search=clip-path) at this time. User agents must still support the clip property until is formally removed by a later specification, and will likely do so for the foreseeable future. This is not a critical bug, but maybe something we can look at. If someone with more familiarly with `.sr-only` is able to chime in, that would be appreciated. I do remember reading an article about it at some point, and the whole thing is fairly painful.

**Comment by Lausselloic** [comment]
the one I know is @ffoodd for sr-only

**Comment by ffoodd** [comment]
In fact my own is already merged: https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_screen-reader.scss and it uses `clip-path` as a progressive enhancement for `clip`.

You might want to read [my post](https://hugogiraudel.com/2016/10/13/css-hide-and-seek/) on @HugoGiraudel 's blog for more explanations.

Due to the very little support for `clip-path`, we cannot afford using `clip` as a basis, or to totally switch to another solution (like `position: absolute` and offscreen position).

I don't think using `clip` is a problem since it's depreciated, not obsolete.

What are your opinions?

**Comment by bardiharborow** [comment]
@ffoodd yeah, I thought that might be the case. I note that article is linked in the code comments, which I somehow completely missed. Sounds like this is safe to close.
