### ISSUE TITLE
Bootstrap .hidden-* classes are simply not present in the distribution?

### ISSUE THREAD

**Issue by tucnak** [twbs/bootstrap#23704]
Hello,

I have downloaded the latest `4.0.0-beta` distribution of Bootstrap and was been wondering for quite some time why `.hidden-*` classes wouldn't work... I then grepped them across the distribution:
```
$ ack "\.hidden*"
js/bootstrap.js
649:      if (!document.hidden) {
```
That's all of the output. It does find all other classes though, it just seems that responsive utilities didn't make it.

Can anyone confirm?

**Comment by jipexu** [comment]
yes no more

**Comment by tucnak** [comment]
Good thing beta releases are a thing! 😄

**Comment by tiesont** [comment]
They were removed: https://github.com/twbs/bootstrap/pull/22113 (see also #21568).

**Comment by myorangeca** [comment]
You can find some useful notes here to change over: https://github.com/twbs/bootstrap/issues/23475

**Comment by tucnak** [comment]
Alright, it seems I indeed confused `alpha` and `beta` docs. Now looking through latest B1 docs, there's no mention of `.hidden-*`. @myorangeca thank you, very informative!

Sorry for noise.

**Comment by SuperPat45** [comment]
To replace 
`hidden-sm-down`
you need to use
`d-none d-sm-block`

I find this new method very regrettable because to replace hidden-*-down element, what is nevertheless the most common, it requires to know the default display of the element which is much less practical than before ...

Moreover the name is confusing because d-*-none has the impression that it hides an element only for a single breakpoint and not the upper also breakpoints.
