### ISSUE TITLE
hidden-* class removed?

### ISSUE THREAD

**Issue by goldboat90** [twbs/bootstrap#23736]
I recently downloaded the bootstrap 4 compiled css files, and noticed that all classes for "hidden" (hidden-sm-down, hidden-sm-up, etc...) are not included within. Was there a decision to remove the class, or was their inclusion simply neglected? I double checked to see if they were there, so I'm hoping the fault isn't on me, the user.

link used to download files (top-most download link):
https://getbootstrap.com/docs/4.0/getting-started/download/

**Comment by fchiumeo** [comment]
see the [Migration](https://getbootstrap.com/docs/4.0/migration/#utilities)

**Comment by Johann-S** [comment]
Closed thanks to @fchiumeo 👍

**Comment by SuperPat45** [comment]
To replace 
`hidden-sm-down`
you need to use
`d-none d-sm-block`

I find this new method very regrettable because to replace hidden-*-down element, what is nevertheless the most common, it requires to know the default display of the element which is much less practical than before ...

Moreover the name is confusing because d-*-none has the impression that it hides an element only for a single breakpoint and not the upper also breakpoints.
