### ISSUE TITLE
Table caption's padding should be set to the same values as td's and th's value

### ISSUE THREAD

**Issue by doekman** [twbs/bootstrap#23746]
In the file `_tables.scss` within bootstrap, the padding properties of the `td` and `th` element are set to some value. 

However, when creating a table with a `caption`-element, the layout is not "nice". In the annotated screenshot, the caption's text is left aligned to the red line. It would be nice it it was default aligned to the blue line, as is demonstrated by the second table in which both items are aligned by a green line.

It would be great if this would be standard out of the box behaviour.

[Test-html, screenshot and annotated screenshot attached here](https://github.com/twbs/bootstrap/files/1263917/bootstrap-caption-padding-test-case.zip)

**Comment by andresgalante** [comment]
Hi @doekman I don't mind the way bootstrap [styles captions](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L300-L306). It's not a bug but a style preference, and you can easily overwrite it if you want.

On the other hand there is no mentions of captions on tables documentation and I believe that there should be since "A caption can introduce context for a table, making it significantly easier to understand." 
https://html.spec.whatwg.org/multipage/tables.html#the-caption-element

If it's ok with you, I'll open a PR to introduce this, what do you think?

**Comment by doekman** [comment]
The reason I opened this issue was that I thought the caption element was forgotten. Never realized it was an style preference. And yes, I already redefined caption in my own stylesheet ;-)

Caption is a not very known element, so some extra documentation would be a good idea IMO.

**Comment by andresgalante** [comment]
@doekman I absolutely agree, the PR was approved by mdo, let's see what patrick has to say.

**Comment by mdo** [comment]
No intention on changing the padding on captions.
