### ISSUE TITLE
Support for form-control:focus-within

### ISSUE THREAD

**Issue by studds** [twbs/bootstrap#23792]
I'm using `.form-control` with a custom control that contains an input element. Because the `.form-control` class is added to a div, and not to an input element, it doesn't get the focus. If the `form-control-focus()` mixin could be updated to `&:focus, &:focus-within` this would mean that the form-control would get the correct focus styling when the input controls it contains are focussed.

This would not be supported by MS browsers but would not harm them either: http://caniuse.com/#search=focus-within

Would it be possible to this in?

**Comment by andresgalante** [comment]
I am up for it, I can't think of a use case where this could be harmful.

**Comment by mdo** [comment]
Going to close for now as a won't fix given the lack of IE and Edge support. Maybe in the future if Edge adds support.

**Comment by ArturGogiyan** [comment]
Edge supports focus-within since it was rebased on chromium. Is there any updates?

**Comment by felixfbecker** [comment]
If it doesn't _break_ IE, but is a progressive enhancement for new browsers, I don't understand why it should not be added? Or at least now that IE is being dropped in v5 it would be great to reconsider this. This also applies to other components, e.g. button groups with radio inputs could be focus styled using `:focus-within`.

**Comment by ffoodd** [comment]
[v5 still supports Legacy Edge (< 18)](https://github.com/twbs/bootstrap/blob/ed9c481ef4b018f77ebc5108071f2e92e6e8ea1a/.browserslistrc#L8) — [which does not support `:focus-within`](https://caniuse.com/#search=%3Afocus-within).

So, to be safely used as a progressive enhancement, it'd require to separate `:focus` and `:focus-within` to prevent invalidating the declaration block in Edge (@studds was wrong, using `&:focus, &:focus-within` would harm since it'd prevent Edge froma pplying the focus styles) —which means duplicating code.

We might find a workaround (eg. using a global variable to `$enable-focus-within` but it would be very verbose to use, disabled in our standard builds, for a very low interest. Moreover, it'd require to use a custom build to change this variable: at this point, you may simply override the mixin by yourself and get the same result…

@mdo @MartijnCuppens any thoughts on this?

**Comment by felixfbecker** [comment]
The code would only be duplicated in the CSS output as there are ways to deduplicate the code in Sass. And since the code would be identical, I doubt it would make any significant difference in gzipped bytes - is that what you're worried about?

**Comment by ffoodd** [comment]
It would still be useless additional code for Edge Legacy users, wich remains a concern. I'd be in favor of trying something, but would also like another thoughts :) 

Feel free to open a PR against `main` (v5) to give it a shot.
