### ISSUE TITLE
Shouldn't border-radius classes (rounded-*) replace element's default border-radius?

### ISSUE THREAD

**Issue by jesobreira** [twbs/bootstrap#23865]
Let's say we have a button:

```html
<button class="btn btn-primary">Test</button>
```
It will be applied the `.btn`'s default `border-radius`, which is a .25rem radius for every corner:

```css
    border-radius: .25rem;
```

Let's say we only want the left side corners to be rounded. So we do:

```html
<button class="btn btn-primary rounded-left">Test</button>
```

Nothing changes and every corner (even from right side) is still rounded. It happens because `.rounded-left` is:

```css
    border-bottom-left-radius: .25rem;
    border-top-left-radius: .25rem;
```
Shouldn't we add:

```css
    border-bottom-right-radius: 0 !important;
    border-top-right-radius: 0 !important;
```

Onto `.rounded-left` so it will change the element's default border radius to be controlled by `rounded-*` classes?

Or it's meant to be done somehow else?

**Comment by andresgalante** [comment]
That's an intresting point and usecase of the rounded corner utility classes. I am unsure of what's the expected result, if an utility class should overwrite the defaults styles in this case, but if it's ok with you I'll create a PR today to test this idea.

What do you think?

**Comment by morrissey-ingenious** [comment]
You can do this by stacking `rounded-0` and `rounded-left` on the button

`<button class="btn btn-primary rounded-0 rounded-left">Test</button>`

https://codepen.io/morrissey-ingenious/pen/NvZRzg

**Comment by andresgalante** [comment]
@morrissey-ingenious that works but the idea of resetting styles to set them again is in my opinion a "hack", not intuitive enough.

**Comment by morrissey-ingenious** [comment]
@andresgalante I would rather not see your `PR` going in as won't allow things such as rounding everything but the top right corner see my codepen above it has been edited.

`<button class="btn btn-primary rounded-0 rounded-left rounded-bottom">Test</button>`

**Comment by andresgalante** [comment]
@morrissey-ingenious you have a really good point by introducing this solution it generates other problems.

Also, I guess this gets twisted once someone wants to do [top-right + bottom left] or [top left + bottom right]

I'll leave it open and let @mdo decide.

Thanks a lot for your help, I honestly haven't consider the case you are showing.

**Comment by heikojansen** [comment]
imho, the utility classes should only do what their name says and have no hidden side effects.
Otherwise it'd be hard to consistently draw a line somewhere for the other utility classes; e.g.: why wouldn't ".pl-1" reset all other padding values then, too? 
Following this scheme, adding the 4 utility classes would be ok but I'd reject your existing PR.

**Comment by andresgalante** [comment]
You guys are right, I've close the PR. Thanks for the feedback.

**Comment by mdo** [comment]
Negative, we'll leave as-is.

**Comment by morrissey-ingenious** [comment]
@rediche this is probably best solved by using your own custom classes now

**Comment by SampsonCrowley** [comment]
why is `rounded-0` set to be more specific then the individual `rounded` classes? `rounded-bottom` should override `rounded-0`. the only class `rounded` should be more specific than, of the 5 available, is `rounded` (and maybe `rounded-circle`, but that's debatable)

this makes it impossible to use the built in classes to override things like the default button styles to only have the bottom of the button rounded

forcing custom css to do something that would otherwise be obvious seems like something bootstrap shouldn't be aiming for
