### ISSUE TITLE
large select

### ISSUE THREAD

**Issue by blue-eyed-devil** [twbs/bootstrap#23879]
Seems like select with `class="form-control form-control-lg"` would look better with property set to `height: 3rem;` instead of `height: calc(2.3125rem + 2px);`

**Comment by andresgalante** [comment]
Hi @blue-eyed-devil input heights are calculated by 
```scss
$input-height:                  calc(#{$input-height-inner} + #{$input-height-border}) !default;
```
here: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L350

Which makes sense since  `.form-control` is set to `background-clip: padding-box;` and borders should be calculated in `px`s.
here: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L18

**Comment by blue-eyed-devil** [comment]
well it may make sense but this is how it look even in your documentation pages.
![bs4-select](https://user-images.githubusercontent.com/19608742/30212051-97a855c4-94e6-11e7-9cd2-b88181d4c85f.jpg)

**Comment by mdo** [comment]
Duplicate of #23769.
