### ISSUE TITLE
_custom.scss file missing in sass-bootstrap

### ISSUE THREAD

**Issue by vikrantnegi** [twbs/bootstrap#23917]
I download the Bootstrap v4.0 beta [source files ](http://getbootstrap.com/docs/4.0/getting-started/download/) which includes the Bootstrap scss folder.

In the file _variables.scss it is mentioned in comments to copy the setting into the provided '_custom.scss' file to override the defaults but there is no such file in the downloaded folder.

```scss
// Variables
//
// Copy settings from this file into the provided `_custom.scss` to override
// the Bootstrap defaults without modifying key, versioned files.
```

Do we need to create that file ourselves or it should be provided in the download as well?

Thanks.

**Comment by Johann-S** [comment]
IMO it's your choice to create that file or not, but we shouldn't share this file because some users don't want that file

**Comment by andresgalante** [comment]
@Johann-S that's true, you wouldn't want an empty file on bootstrap.scss.

On the other hand the comment language is confusing: 
- There is no "provided" `_custom.scss` file
- Since the !default flag changes the order of the variables on sass, it might be really useful for user to be specific about where to import it (before `_variables.scss`).

I'll send a PR to fix it today.

**Comment by mdo** [comment]
No more custom Sass file and no more comment from our end, so closing out.
