### ISSUE TITLE
Feature Request: Additional Font Weight Classes

### ISSUE THREAD

**Issue by planetoftheweb** [twbs/bootstrap#23969]
I think it would be great to include some more font-weight options in bootstrap. Even when you look at the documentation, you can see that the weights have been modified because current design sensibilities call for a wider range of font weights that the default. I realized that when I'm creating bootstrap projects, I end up modifying the font-weights a lot, so maybe this could be added into the classes.

![screen shot 2017-09-16 at 7 22 29 pm](https://user-images.githubusercontent.com/216426/30516697-657091d2-9b14-11e7-9faf-a0866a469639.png)

Although `font-weight-bold` and `font-weight-normal` exist, I feel like there needs to be a bit more broad.  I'm proposing adding some font-weight classes.

`font-weight-light`
`font-weight-medium`
`font-weight-normal`
`font-weight-bold`
`font-weight-heavy`

These could be tied to sass variables. We could also add numbered font-weight classes.

`font-weight-100`
`font-weight-300`
...etc

**Comment by andresgalante** [comment]
Hi @planetoftheweb reading your issue I noticed that `font-weight-light` is defined on the code base but not surfaced on the docs. I've sent a PR to add it #23970

As for adding more utility classes I think it's a good idea, in fact I am doing it at my own project. 

From a bootstrap perspective I'd make sure to test it in different browsers and OS. Since Bootstrap has a System Font Stack, it might be the case that some font families don't have a specific weight (in numbers).

Using keywords is a safer bet and users can always define them on their projects.

anyway, good idea 👍

**Comment by XhmikosR** [comment]
We could add them, but we must have a note that based on the font used, the result might not be the expected one, and it's the developer's job to make sure the font weight they are using exists.

See for example an issue with our docs, #24419.

**Comment by polys** [comment]
Could you add `font-weight-medium` as well please?

It would set `font-weight: 500 !important;` similar to how `font-weight-light` is defined.

I find it very useful and keep adding it to my projects; it would be nice if it was part of bootstrap. I understand that it may not work with all fonts but at least it sets the _intent_. How's `font-weight-light` any different?

**Comment by mdo** [comment]
Closing since we had the lighter/bolder added. For any other weights and utilities, please feel free to open PRs to suggest :).
