### ISSUE TITLE
Modal with dynamic content - no way

### ISSUE THREAD

**Issue by Fruchtgummi** [twbs/bootstrap#24028]
With bootstrap 3, i create a modalbox end append on body, with follow JS-Script

 ```
jQuery("body").on("click","[data-toggle*=modal]",function(){
        var ha = Math.floor(Date.now() / 1000);
        var modal = $('<div class="modal fade" id="ewumodal'+ha+'" tabindex="-1" role="dialog" aria-labelledby="ewumodalLabel" aria-hidden="true"></div>');
        var button = $(this)
        $( "body" ).append( modal );
        $('#ewumodal'+ha).on('show.bs.modal', function (event) {

                var buttonArray = new Array();
                buttonArray = button.data();
                if (button.data('pophtml')) {
                    var cURL = "/popover/"+button.data('pophtml');
                } else {
                    var cURL = 0;
                }
                var funct = button.data('funct');
                var y = {};
                for(z in buttonArray) {
                        if (z.match('daten')) {
                            y[z.replace('daten','').toLowerCase()]=buttonArray[z];
                        }
                }
                $('#ewumodal'+ha).load(cURL, function(r, status) {

                        if (funct!=undefined) {
                                var fn = window[funct]
                                if (typeof fn === "function") {
                                        fn(buttonArray);
                                } else {
                                        setGlobalMessage("warning", "Error: Template nicht gefunden oder Init-Funktion im Template nicht gefunden.");

                                        $(modal).modal('hide')
                                }
                        }
                });
                 $('#ewumodal'+ha).on('hidden.bs.modal', function (e) {
                        $(this).removeData('bs.modal');
                        $(this).empty();
                        $(this).remove();
                });
    });
$("#ewumodal"+ha).modal("show");
});
});
```

*ha* is the variable for several boxes at the same time.

The trigger-button is:

```
<a href="#" class="nav-link js-scroll-trigger"
               data-pophtml="p_registry"
               data-funct="init_js"
               data-geturl="/"
               data-toggle="modal"
               data-keyboard="false"
               data-backdrop="static"
               data-target="#ewumodal">Login</a>
```

data-pophtml is a HTML for modal-tag inside

Under Bootstrap3 runs without problems. With Bootstrap4-Beta is the modal with extern html loaded, but the events on this modal do not work. 

It would be a pity if that is not possible, then Bootstrap4 would be useless.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Fruchtgummi** [comment]
Okay, here is the share from JS-Bin

https://jsbin.com/qiwamezoci/edit?js,console,output

The close-click and other events from modal do not work.

**Comment by herbalite** [comment]
I tried things on my development server and it worked without problems after I moved all files on that machine and adjusted the load() call. When I try to load p_registrieren.html remotely from the original source however, then the callback status variable comes back with an error condition, and things happen as youdescribe.

So it doesn't seem to be a Bootstrap4 issue.

In jQuery 3.x, the load() function has changed slightly, If you used jQuery 2.x with your original code, then you need to check there, And I'd suggest that you check the variable status in the load call for errors as it helps you to pinpoint issues much faster.

Notice also the disclaimer at the jQuery page ( http://api.jquery.com/load/ )

"Due to browser security restrictions, most "Ajax" requests are subject to the same origin policy; the request can not successfully retrieve data from a different domain, subdomain, port, or protocol. "

This was the reason why trying to load p_registrieren.html from the original server failed on my development server.

**Comment by herbalite** [comment]
The JSBin example doesn't work, because of cross domain loading of the p_registrieren.html file.

**Comment by Johann-S** [comment]
I checked on a local server and everything works fine, you should use same origin for your URL as mentionned by @herbalite 


[remoteModal.zip](https://github.com/twbs/bootstrap/files/1330684/remoteModal.zip)
