### ISSUE TITLE
[v4] Email validation does not check for a top level domain

### ISSUE THREAD

**Issue by smiller171** [twbs/bootstrap#24058]
Bootstrap 4
Chrome Version 62.0.3202.18 (Official Build) beta (64-bit)
OSX 10.11.6

The default email validation only checks for an `@` symbol, not a top level domain, so `a@b` is valid, when it should at least require `a@b.c` and preferably validate that the tld is a valid one.

**Comment by bardiharborow** [comment]
Bootstrap **does not** perform validation of email fields. This is [quite a messy road](https://stackoverflow.com/questions/46155/how-to-validate-email-address-in-javascript), and is beyond the scope of this project. You are probably referring to your browser's validation of `<input type="email">` elements, which [per the specification](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address) uses a regex that accepts `a@b`. This part of the specification is deeply flawed, stemming mostly from the fact that [RFC 5322](https://www.ietf.org/rfc/rfc5322.txt) (the email spec) is deeply flawed. There are a number of critical specification bugs, including [failure to appropriately handle internationalised domains](https://www.w3.org/Bugs/Public/show_bug.cgi?id=15489).

> preferably validate that the tld is a valid one.

This is a particularly terrible idea, because ICANN is accelerating the release of new TLDs, and such a list would be out of data very quickly.

If you do need to validate email addresses, then you should defer to an established library to do this. Please also ensure that you are validating on the server side as well, as client side validation is easily bypassed.

**Comment by smiller171** [comment]
Thanks @bardiharborow I didn't realize just how much of the validation is handled by the browser.
