### ISSUE TITLE
Button hover colors should be in _variables.scss file

### ISSUE THREAD

**Issue by mwentz** [twbs/bootstrap#24090]
The mixin for button-variant is defined like this:
```
@mixin button-variant($background, $border, $active-background: darken($background, 7.5%), $active-border: darken($border, 10%))
```

Because of this, if you want to have the active background 10% darker or 7.5% lighter (for example) you either have to change the mixin file or write more custom css. This could be easily fixed:

/mixins/_buttons.scss
```
@mixin button-variant($background, $border, $active-background, $active-border)
```

_variables.scss
```
$active-background: darken($background, 7.5%);
$active-border: darken($border, 10%);
```

It looks as though this was probably the original intent, but somebody forgot to move those variables out of the mixin file.

**Comment by andresgalante** [comment]
Hi, I believe this has already been brought up, for example here: #23750

**Comment by andresgalante** [comment]
Hi @mwentz I think this is a good move, would you like to send a PR?

**Comment by andresgalante** [comment]
Remember that variables should follow the `$component-state-property-size` formula. So it might something like:

```scss
$btn-active-bg: darken($background, 7.5%);
$btn-active-border: darken($border, 10%);
```

**Comment by cdikibo** [comment]
Can I do this?

**Comment by andresgalante** [comment]
I though a lot about this, at first it seems like a great idea, but the variable would make much sense outside the mixing, at least not to me. I mean the darken function of background and border without context will just be really confusing for users.

I love the idea to abstract the active hover state in a way users can change it. Is there any way to do it with another approach?

**Comment by mwentz** [comment]
Thanks @andresgalante for your thoughts. I created a PR with these changes before I saw your last comment. You are totally right, so I closed the PR.

**Comment by mwentz** [comment]
So basically the context of `$background` and `$border` are local variables so it does not make sense to extract them out into the _variables.scss file.

**Comment by andresgalante** [comment]
Well... it makes sense for you an me that we know the mixin and the context where btns are defined, but I don't think it does for users (and maybe I am completely wrong).

I honestly have been thinking a lot about how to abstract that into a variable to help you out, and I can't find a good way yet. Let's keep digging on this one, it'd be a huge win IMO if we can give the users the opportunity to change the hover and active state on the variables.

Thanks a lot for your patience with me.

**Comment by mdo** [comment]
Closing as a won't fix—leaving these as-is.

**Comment by johanneskrtek** [comment]
@andresgalante I find myself struggling with the button mixins often enough with the need to modify some states (especially the hard-coded percantages and 'lighten' vs 'darken'). As far as I can see the approach of the opening comment wouldn’t work, not so much because of the confusion, but because the `$background` variable is undefined until it gets set in the `@each` loop in `/scss/_buttons.scss`

How about a solution along these lines – this approach would users let easily adjust the percentages as well as the color funcion:

/scss/mixins/_buttons.scss
```
@mixin button-variant(
  $background,
  $border,
  $change,
  $btn-hover-change-bg,
  $btn-hover-change-border,
  $btn-active-change-bg,
  $btn-active-change-border) {
    @if $change == "darken" {
      $hover-bg:     darken($background, $btn-hover-change-bg);
      $hover-border: darken($border, $btn-hover-change-border);
      $active-bg:    darken($background, $btn-active-change-bg);
      $active-bg:    darken($border, $btn-active-change-border);
    } else {
      $hover-bg:     lighten($background, $btn-hover-change-bg);
      $hover-border: lighten($border, $btn-hover-change-border);
      $active-bg:    lighten($background, $btn-active-change-bg);
      $active-bg:    lighten($border, $btn-active-change-border);
    }
    
    ...

  }
}
```
/scss/_variables.scss
```
$btn-change: "darken";
$btn-hover-change-bg: 7.5%;
$btn-hover-change-border: 10%;
$btn-active-change-bg: 10%;
$btn-active-change-border: 12.5%;
```

**Comment by andresgalante** [comment]
Hi @johanneskrtek thanks for sending your idea. This issue had come up and was closed at least 2 times. I'll be happy to review a PR with your idea, but at mdo will have the final word on this subject.

**Comment by johanneskrtek** [comment]
Hi, I‘d be happy to provide a PR with a good solution for the button mixin. The buttons are a rather interconnected topic, so I’d like to improve my idea first so we won’t end up with a hasty result. E.g. from my own experience users might want to be able to switch between 'lighten' and 'darken' for the hover and active state independently. I’m also aware of the elegance of the current solution, it’s just a bit inflexible due to the hard-coded parts. I’ll try to strike a balance.

**Comment by johanneskrtek** [comment]
@andresgalante here you go: #24682.
