### ISSUE TITLE
We are close to 2018 and Bootstrap did not support RTL yet?

### ISSUE THREAD

**Issue by mtawil** [twbs/bootstrap#24332]
Hello,

Before that, in 2013, I pull a request https://github.com/twbs/bootstrap/pull/10534 and @mdo said that it's okay.
Then I pull a new request https://github.com/twbs/bootstrap/pull/10672 and he rejects that way, funny huh? :D

Anyway, we are now close to 2018, and Bootstrap 4 did not support RTL yet? Seriously?
May I know when you intended to support RTL? in 2030? Or v10?

Thank you.

**Comment by Johann-S** [comment]
They are a pull request which target that : https://github.com/twbs/bootstrap/pull/23703

**Comment by mtawil** [comment]
Here is a wiki article that talks about what is the best way to make RTL version of BS4 and why:
https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F

**Comment by mdo** [comment]
Beyond us doing it, there have been a handful of options available via third party since v2 even if I recall. I haven't had the time to test ideas and implement this myself, definitely not before shipping a final v4. Most folks that jump to implementing something for us skip any and all conversation about the method of implementation.

Given that, rather than complain, make jokes, and encourage negative criticism from others with your approach in this issue, how about we talk about the multiple methods of implementing RTL? Maybe we talk about who has coded it and how in other similar projects?

The issue and PR you reference are your own from four years ago and coded for v3. I can't recall why I closed it, but I know I never found the time to try out any RTL implementations. One comment on an issue isn't enough of an endorsement for that approach though, and four years later, I imagine it's not the only one.

I'm going to close this one out because it's not the place to have that discussion. I'd happily see a new one opened though with various options.
