### ISSUE TITLE
Form label inside card-body sometimes creates extra space at the bottom of a card

### ISSUE THREAD

**Issue by ryanfrawley** [twbs/bootstrap#24349]
Tested on Firefox 56 & Chrome 61

Example here:
https://codepen.io/anon/pen/dVjdYZ

Line 19 is where the issue occurs. If you delete any character but the space from the label text, you won't get the extra space at the bottom of the card body. Adding back the text will add the space. It must be some kind of issue with the card flex, because removing the card class makes everything work as expected.

You can increase the size of this space by copying and pasting the form-row on line 17 multiple times. Each one adds additional space to the bottom of the card-body.

![image](https://user-images.githubusercontent.com/267618/31502203-67b000ce-af3a-11e7-85bf-44ccf39f5789.png)

**Comment by andresgalante** [comment]
Hi @ryanfrawley, 2 things:

First, Wow this is odd!!
and Second, for your exact use case don't need the `form-row structure` . It can be much simpler:  https://getbootstrap.com/docs/4.0/components/forms/

And I am sure the problem comes from the structure itself.

Thanks for reporting it, I'll take a close look at it when I find a gap of time.

**Comment by mdo** [comment]
Remove `.row` on the `.card.
