### ISSUE TITLE
Button with Icons : recommended approach?

### ISSUE THREAD

**Issue by gkatsanos** [twbs/bootstrap#24358]
From what I see in the docs, there are no icons in v4.
Is there a recommended approach though to combine icons and buttons?

**Comment by XhmikosR** [comment]
We don't have any markup examples in our docs, which means you just use any utilities you might need along with the icon markup.

Not sure if we should cover this case, maybe in https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/extend/icons.md.

@andresgalante: thoughts?

**Comment by andresgalante** [comment]
Hi @gkatsanos What do you mean by combining icons and buttons? You can place an icon inside a btn and it should work.

I think it was a good move from bootstrap to stop delivering icons out of the box since the web is moving from icon fonts to svg icons and depending on your environment you'll probably set up your icons in a different way. I am writing a blog post about this, if you want I can update this issue when I publish it.

**Comment by gkatsanos** [comment]
Well I guess the issues to handle would be alignment issues (vertical and horizontal). The element doesn't have to be a fonticon per se could just be an svg. 
But I understand that it's not in the scope of the framework anymore. 
Yes would be interested in the blog post although I guess I can do the markup custom-made myself and extend the button classes accordingly :)

**Comment by andresgalante** [comment]
@gkatsanos if you have problems with alignment, please create a codepen and let's take a look if that's something we should to fix at bootstrap level.

**Comment by gkatsanos** [comment]
Should be fine but will do! Thanks.
