### ISSUE TITLE
Reduce size of generated CSS / more control over auto-generated helpers

### ISSUE THREAD

**Issue by c0defre4k** [twbs/bootstrap#24547]
Bootstrap generates a lot of helper functions based on breakpoints which leads to many classes which may be unused in production CSS. The problem gets even bigger if you want to add another breakpoint. Now since `offset-*` classes are back this isn't helping either.

In order to have more granular control I would suggest to add more option variables to allow the developer to choose which helpers should be auto generated and which ones not. I'll add some examples below.

Do you have any other plans or ideas in implementing such a feature? If necessary I would prepare a PR if this seems legit to be implement.

In case of `_flex.scss` it would be useful to limit the breakpoints for which the helpers should be generated as well as disabling some helpers at all. In this case I would suggest a new variable `$flex-breakpoints` which inherits its values from `$grid-breakpoints` as a default. Then I'd suggest the variables `$enable-flex-justify-content`, `$enable-flex-align-items`, `$enable-flex-align-content`, `$enable-flex-align-self` to enable or disable auto generation of these helpers. For the other `flex-*` helpers I'm currently unsure if there should be variables for each of them, or just disabling the wrap helpers or if we just keep them all the time as they were needed more often then the others.

The same scheme can be applied to `_grid-framework.scss` where I would create variables `$enable-grid-order` and `$enable-grid-offset` to disable them. Offsets, may not be used by many people since they had been removed and brought back in the newest beta.

I'd really appreciate your thoughts about this. In my opinion this would help developers a lot to keep their CSS small.

**Comment by mdo** [comment]
I can understand the use case here, but at that granularity it doesn't make much sense to me. I could see us adding flags for each set of utility classes (e.g., `$enable-utility-bgs` and `$enable-utility-colors`, etc), but that also gets tricky for us. We rely on some of those classes for components and necessary overrides. I'm open to hearing more here, but just want to preface there's a balance for us.

**Comment by c0defre4k** [comment]
The examples I wrote above may go very far, I know. 

In case of the utility classes it's already very easy to disable specific sets of them by replacing the import `@import "../node_modules/bootstrap/scss/utilities";` with a custom one. This works in my case as I don't import the main `bootstrap.scss` - I copy it and import the listed modules myself and disable what I don't need in the project.

But when i want to disable specific grid classes for example I run into a problem. Lets take the `order-*`-classes for an example. If I want to disable them following the same approach as with the `bootstrap.scss` I need to override `_mixins.scss`, `_grid-framework.scss` and then need to copy that mixin and remove that for-loop. But when there is a newer version i might run into a problem. It's OK to update my custom `bootstrap.scss`, but it gets more complicated when i have to go through every mixin and look for what has changed and what I wanted to be disabled.
Thats why I find it more convenient to have a simple variable that I just need to toggle.

I hope this helps to understand my main problem.

At my current project I switched to another approach using [PurgeCSS](https://github.com/FullHuman/purgecss) to remove that unnecessary CSS. I think this is a way superior approach, but I don't know how the majority of developers is implementing bootstrap into their projects and if this is even suitable for them.

**Comment by MartijnCuppens** [comment]
We could approach this like Tailwind does, but keep using sass for it: https://github.com/tailwindcss/tailwindcss/blob/master/defaultConfig.stub.js

**Comment by pavelloz** [comment]
There are couple of ways to tone down the explosion of bundle size, some require a lot of manual labor and some require even more manual labor when upgrading BT version. 

So far in 4.3.1 i've had most issues with utilities and those smaller classes that are blown because of X breakpoints (size) and Y variants. So adding "sizes", "utilities" when you really wanted to just make an `m-1` in one place gets out of hand because of those loops in loops. 

Most problematic (for me) examples:
https://github.com/twbs/bootstrap/blob/master/scss/utilities/_sizing.scss
https://github.com/twbs/bootstrap/blob/master/scss/utilities/_spacing.scss

And those cases i would tackle as first step ( https://github.com/twbs/bootstrap/blob/master/scss/_utilities.scss ), because other modules are not dependent on those and so there should not be any backward compatibility problems in doing that.

I would personally just unwrap `utilities.scss` into bootstrap.scss and provide control flags/vars for specific utilities, like you do with borders, etc. but maybe marked as `_flag` to signalize that it wont have any representational consequence.

--- 

Purgecss is only good if you have extremely simple setup. Anything remotely dynamic, composed from different sources, separated front from backend, render it very hard to use/useless.

**Comment by mdo** [comment]
Closing this out as we've added the majority of it with @MartijnCuppens's work.
