### ISSUE TITLE
Remove box-shadow when focusing on .btn classes

### ISSUE THREAD

**Issue by devmws** [twbs/bootstrap#24566]
All buttons, anchors and input[type="button"] which have the class ".btn" produce a box-shadow style when focusing on them and it's really UGLY!!!
![1](https://user-images.githubusercontent.com/25705547/32067589-70234f92-ba8c-11e7-8793-4bbb245989a1.PNG)

**Comment by mdo** [comment]
No, you're really ugly! Kidding aside—and next time, please don't open by insulting our project—this is intentional as it's a custom implementation of the browser's focus ring. It's there for accessibility and is customizable. We recommend you not remove it—if you do, be sure to replace it with something else.

**Comment by atomiks** [comment]
Have you guys considered using the `:focus-visible` polyfill? For people using a mouse, it won't create an outline, whereas keyboard navigation will. This means you don't penalize mouse users aesthetically while keeping it accessible. 

https://github.com/WICG/focus-visible
