### ISSUE TITLE
 The framework defines 12 columns of basic layout, why not 10 column or 15 column or other？

### ISSUE THREAD

**Issue by chailong** [twbs/bootstrap#24595]
Bolstap is easy to learn, suitable for quick layout. The framework defines 12 columns of basic layout, why not 10 column or 15 column or other

**Comment by jipexu** [comment]
because need to choose one  ( so it's 12) .... in your _variable.scss file you can redefine easy (and recompile)  ....  
 $grid-columns:               12 !default;

**Comment by acshef** [comment]
12 is a [superior highly composite number](https://en.wikipedia.org/wiki/Superior_highly_composite_number). You can divide it into halves, thirds, quarters, and sixths. Because it has so many divisors, it provides a very flexible grid system without being too ridiculous (in order to provide half, thirds, quarters, *and fifths*, we'd need to use a 60-column system. That's a lot!)
