### ISSUE TITLE
jQuery .Html() has XSS vulnerability

### ISSUE THREAD

**Issue by arc95** [twbs/bootstrap#24627]
I came across this while investigating security for my app: Bootstrap v3.3.7 (all browsers) on Windows uses the jQuery `.Html()`, which sets an object's inner HTML and poses [XSS risks](https://www.owasp.org/index.php/AJAX_Security_Cheat_Sheet#Use_.innerText_instead_of_.innerHtml). Here's the recommended alternative to `.Html()`: https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/

Here's an example of it from bootstrap.js, line 1834:
```if (!$tip.find('.popover-title').html())```

I searched (as best as I could) and didn't see this listed as an issue. Has this been addressed in 4.x?

**Comment by gijsbotje** [comment]
i don't think this is an issue for the bootstrap js, the article talks about ajax or api responses rather then the `.html()` method in whole
I can't image the bootstrap core making api calls, in my eyes this is a non issue

**Comment by andreasschiestl** [comment]
Using the `.html()` method itself is not a issue. Only using it with data from an untrusted source is a issue and may open a XSS vulnerability.

**Comment by Johann-S** [comment]
in v4 we don't use `.html()` but even if in the futur we use that method as it written [here](https://www.owasp.org/index.php/AJAX_Security_Cheat_Sheet#Don.27t_rely_on_client_logic_for_security) do not rely on client logic for security.

Plus on Bootstrap 3, you can set `html: false` (which is the default value) to tell Bootstrap to use `.text()` instead of `.html()` see : https://getbootstrap.com/docs/3.3/javascript/#popovers-options
