### ISSUE TITLE
V4.beta.2 missing transition for progress-bar

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#24643]
It appears that https://github.com/twbs/bootstrap/pull/22703 quietly removed the default transition CSS for `.progress-bar`: https://github.com/twbs/bootstrap/pull/22703/files#diff-2afc93127d8c7692f4efec8bedb49bb3L22

Just wondering if this was a mistake, or intentional.

**Comment by gijsbotje** [comment]
@andresgalante @mdo 
i could add it back on #24544

**Comment by andresgalante** [comment]
Good catch @tmorehouse it looks like it was remove by mistake.

@gijsbotje I'd create a new PR, try keeping that PR single purpose. Small PRs are easier to review and merge.

@mdo just a thought: animating width is not performant, I am for removing that animation from variables till we figure a way to animate a transform there.

**Comment by gijsbotje** [comment]
@andresgalante maybe your suggestion to switch to flex-basis could allow for smoother transitions

**Comment by tmorehouse** [comment]
The main thing is to allow it to transition smoothly from say 50% to 80% (i.e. when dynamically updating the "value" of the progress bar).

**Comment by andresgalante** [comment]
@gijsbotje flex basis will cause repaint, just like width.

A transforms scale3d will trigger GPU acceleration and it's the smoother and most performant for this cases. It can dynamically be change with inline styles just like we do width, but we would need an extra div to do it because it'll transform the container of the number. I'll put together codepen with a demo: better show than tell 😄

**Comment by andresgalante** [comment]
Here is a quick example:
https://codepen.io/andresgalante/pen/wPMPqp?editors=1100
But of course we need another div to show the value.

**Comment by gijsbotje** [comment]
yeah you're right, i somehow thought flex had support for gpu accelrated transition but can't find anything that says so

using scale3d is the best option, unfortunately you'll need extra markup as you mention.
and did you have an idea how to center that in the progress-bar?
i can't really think of a propper way...

**Comment by andresgalante** [comment]
@gijsbotje you are right, I can think of a way to center the value with some extra markup, but it's just too complicated and not practical enough to be in Bootstrap.

To me the options are either remove the animation variable or add the mixin and live with a non performant animation. Since it's a simple animation it's not the end of the world, and browsers are getting better and better at it every day.
