### ISSUE TITLE
IE 11 needs class w-100 in many locations. Inconsistency Chrome/firefox <-> IE11, iOS safari affected as well

### ISSUE THREAD

**Issue by Jossnaz** [twbs/bootstrap#24687]
Bootstrap 4 beta 2

Windows 10 IE 11

I just built a website, then looked at it in IE. Now I have to go through everything an add w-100 in many places

open with chrome, then with IE
https://codepen.io/anon/pen/MOejLY

IE:

![image](https://user-images.githubusercontent.com/2072058/32422251-516aad5a-c26d-11e7-9566-2f90bd4d0672.png)

chrome

![image](https://user-images.githubusercontent.com/2072058/32422257-5fd14f5c-c26d-11e7-867e-d4d0a9fce155.png)

fix / workaround:

add `w-100` to the div with class `.bippo`

code for completeness

HTML
```
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-12">
      <div class="foobar-mine  d-flex justify-content-center align-items-center ">
        <div class="row no-gutters  bippo">
          <div class="col-4">
            more stuff with a lot of content xx aa bbb ccc dd  ee f  gg
          </div>
          <div class="col-4">
            more stuff with a lot of content xx aa bbb ccc dd  ee f  gg
          </div>
          <div class="col-4">
            more stuff with a lot of content xx aa bbb ccc dd  ee f  gg
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```
CSS
```

.bippo div{
  background-color: cornflowerblue;
  
}

.foobar-mine {
  display: inline-block
}
```

**Comment by Jossnaz** [comment]
**UPDATE**

This issue _seems_ to be related to an issue with iOS Safari

a client just complained to me with this screenshot saying that he has a huge scrollbar left right on that page

iPhone 7 with iOS Safari:


![image](https://user-images.githubusercontent.com/2072058/32466012-7e73e1bc-c313-11e7-891d-a1deed5670af.png)


IE 11 same place same page:

![image](https://user-images.githubusercontent.com/2072058/32466074-b21d3c34-c313-11e7-9145-2d247dbbb0fc.png)

I will provide a codepen... will edit in a second

**Comment by Jossnaz** [comment]
codepen for the second issue as promised here:

https://codepen.io/jossnaz/pen/mqrdEN

looks in chrome as expected:

![image](https://user-images.githubusercontent.com/2072058/32466649-a37330b0-c315-11e7-8147-392137f26b6c.png)

IE11:

![image](https://user-images.githubusercontent.com/2072058/32466657-af33a402-c315-11e7-9491-75ddc55ab62e.png)

HTML

```
<div class="container-fluid">
        <div class="row no-gutters  bippo">
          <div class="col">
            <div class="my-item">
              11 11 11 11 11 <br>
11 11 11 11 11 <br>
              11 11 11 11 11 <br>
              11 11 11 11 11 <br>
              11 11 11 11 11 <br>
            </div>
          </div>
          <div class="col">
            <div class="my-item">
             22 22 22 22 22 <br>
              22 22 22 22 22 <br>
              22 22 22 22 22 <br>
              22 22 22 22 22 <br>
              22 22 22 22 22 <br>
            </div>
          </div>
          <div class="col">
            <div class="my-item">
             33 33 33 33 33 <br>
               33 33 33 33 33 <br>
               33 33 33 33 33 <br>
               33 33 33 33 33 <br>
               33 33 33 33 33 <br>
              
            </div>
          </div>
          
          
        </div>
      </div>

```

CSS

```
.bippo div{
  background-color: cornflowerblue;
}

body, html{
  width: 320px;
}


.my-item{
  width: 290px;
}
```

**Comment by Jossnaz** [comment]
these issues are maybe unrelated, maybe should have created a new issue... but the result looks very similar...

**Comment by Jossnaz** [comment]
added this workaround for the second issue (the second codepen)

just use d-flex and flex-wrap and avoid using `.col` as it seems a bit buggy


https://codepen.io/jossnaz/pen/EbgxQd

**Comment by andresgalante** [comment]
Hi @Jossnaz thanks for reporting this. there has been work around auto width, it's described in this issue:
https://github.com/twbs/bootstrap/issues/24319

Can you please let me know if what you are describing is fixed on `v4-dev` ?

**Comment by mdo** [comment]
Looking at your code, there are a few things wrong or confusing.

There's no need for the first `.row` or `.col-12`; that's completely unnecessary as it just adds two levels of markup without any change. This is literally the same as wrapping the rest of your code in nothing. Reduce that code down and it renders the same in IE11 and Chrome on latest Win10: https://codepen.io/anon/pen/MOBexY.

Your second example I don't understand at all. Why set the width of the parent to 320px, but the children within to 290px? `.col` is intended to create equal-width columns, but you're effectively forcing the browser to undo that (Chrome is getting it right here). If you want three equal width columns, nix the width.

All told, this doesn't seem like Bootstrap bugs, but either too much code or a browser bug with flex.

**Comment by Jossnaz** [comment]
@mdo correct, there is _no need_. Unless you work in a framework that makes use of bootstrap everywhere. For convenience, the default cause is that the content of sections/macros/components are always bootstraps `.cols` Now you could say: but you don't always need that. Well, yes. But most of the time you want to have a container, and inside dynamic content. The container is always the same. I could go on, but I guess you understand. So, no, we cannot just leave it out and do something entirely different.

So your answer: well just don't use bootstrap and it'll work, is disappointing to me. Ok I'll just go ahead and delete bootstrap from our framework then I guess... ?

second example: the width is 320 of the body, to fake mobile. Set it to 2000 so you see how it looks like on desktop.
I don't see how you can get it wrong. `.col` is meant to make the columns equal width, that we agree on. Does the _content_ of the `.cols` has to be as wide as the `.cols`, e.g. 100% width? really? because that sounds really odd to me.

I am quite disappointed I must say. "Issue closed"

I feel like @mdo doesn't care. Isn't bootstrap meant to be working and be compatible to the supported browsers? "browser bug with flex" isn't that exactly what bootstrap should take care of and not me? at least well document how to avoid them? *closed* ...

**Comment by Jossnaz** [comment]
looking back at it, it is actually funny

bootstrap issue XY:

solution:
don't use bootstrap

issue closed


not sure if I need to cry or laugh

I mean I get it, you have many issues with the new framework and everything
and want to close some

but that one is really some special way of closing your issues

**Comment by mdo** [comment]
@jossnaz Perhaps it was the tone in my comment that set us down this path, but please don't think I'm being disrespectful or telling you to not use Bootstrap.

Regarding bugs in Bootstrap, the browser, or the spec—flexbox support is pretty great, but it's not perfect. There's little we can do about that except to discuss workarounds, evaluate the premise of your markup, and point out alternatives. See https://github.com/philipwalton/flexbugs for an example of at least a dozen bugs across various browsers—from IE10 to latest Chrome and Safari.

Diving into your last two comments more...

---

> But most of the time you want to have a container, and inside dynamic content. The container is always the same. I could go on, but I guess you understand. So, no, we cannot just leave it out and do something entirely different.

Every situation is different, yes, and our tooling can add additional constraints, but without any additional information, all I can do is to suggest simplifying the HTML.

```html
<div class="row no-gutters">
    <div class="col-12">
	    <p>This renders the same...</p>
	</div>
</div>

<p>As this here...</p>
```

You can still always have a container, but I'm suggesting that you don't need this outer row or column as it effectively does nothing visually or structurally to your content. It's just like wrapping a single, unstyled `<div>` around the content.

> So your answer: well just don't use bootstrap and it'll work, is disappointing to me. Ok I'll just go ahead and delete bootstrap from our framework then I guess... ?

I literally never said don't use Bootstrap. I said you're potentially using too much HTML and that I don't fully understand the use case of the second example.

> I don't see how you can get it wrong.

That's the wrong way to approach any communication problem, here on GitHub or in person. If there's a misunderstanding, let's back up and work to communicate better.

> at least well document how to avoid them?

Here's the thing though—I have a decent understanding of the flexbox spec overall, but I still need to look things up. With Bootstrap, I'm super close to the code base because I've written the majority of it. When there are shortcomings in the docs or code comments, it's because I have more context than you. Because of that, I need folks who aren't as familiar to tell me where I can better explain things.

If there are specific parts of the docs that aren't cutting it, please open an issue to discuss them. It's the only way I can make them better.

> I feel like @mdo doesn't care.

Then you really don't understand who I am, what I do, or why I do it—and then I probably can't help you :(.

---

Now, revisiting your opening comment, you haven't shown me exactly what you're trying to accomplish. You said, this is wrong in IE but right in Chrome, but even with that context, I don't know exactly what you're trying to build. Similarly, I had no idea why you wanted to set fixed widths of 320px and 290px—sure that could've been faking a mobile device, or it's part of your layout.

Wrapping this all up, I need more information than you've provided, I'm not telling you to not use Bootstrap, and I do care about people being able to build rad shit with Bootstrap.

**Comment by mdo** [comment]
Let's revisit your first CodePen: https://codepen.io/anon/pen/pdxbZx. From mobile to desktop, here's what I'm seeing. Are you expecting something different?

<img width="384" alt="screen shot 2017-11-28 at 10 38 18 am" src="https://user-images.githubusercontent.com/98681/33337618-55fa9d4a-d428-11e7-9973-789d65e8342c.png">

<img width="1245" alt="screen shot 2017-11-28 at 10 38 05 am" src="https://user-images.githubusercontent.com/98681/33337619-5614438a-d428-11e7-86c8-3bcac36ca6c8.png">

**Comment by Jossnaz** [comment]
my fist code pen -> that is exactly what I was expecting. I provided a screenshot of IE (that is desktop resolution), and I provided a workaround that makes it work in IE. Look at the screenshot from IE and look at your screenshots. Again: yes I am sure there are different ways to do it. But people are using your library all over their components, just like I do, in non trivial html structures, nested etc.

tell me if you need further help understanding what is the issue

dont have IE / windows?

go here
https://netrenderer.com/index.php
enter url:
http://jsbin.com/vesuyafugo

renders the same in IE11 like on my local IE11 on windows
