### ISSUE TITLE
Use built-in position finder instead of popper.js

### ISSUE THREAD

**Issue by mojtabakaviani** [twbs/bootstrap#24717]
popper.js added 18k minified to bootstrap and not support right to left direction. write very lighter position finder library with options just need in bootstrap components.

**Comment by Johann-S** [comment]
Not sure we will go in this way, because we made the decision to remove position logic in our code in favor of a positioning library like Popper.js and before Popper.js, Tether.

I understand your concern about the size of Bootstrap and if Popper.js shipped a light release we will use it or if we found something lighter

/CC @FezVrasta about your proposal to have a lighter version of Popper.js

**Comment by FezVrasta** [comment]
Right now, if you take only the Popper.js core, without any modifier, is 12KB, or 6KB compressed server-side.

If you add the strictly required modifiers (`applyStyle`, `computeStyle`, `arrow`, `flip`, `keepTogether`, `offset`, `preventOverflow`) the total size is 20KB, or still 6KB compressed server-side.

This is the difference, compared to the 21 KB (or 6.3KB compressed server-side) of the complete bundle.

I don't think that the additional overhead is worth these .3KB of size reduction.

Anyway, if you want to see a smaller bundle, please feel free to send PRs to reduce its size. And, anyway, I doubt any home-made replacement would be able to provide the same feature set with a smaller size (considering that Popper.js doesn't have any additional dependency).

I hope these info can be useful.

**Comment by Johann-S** [comment]
We will stick to Popper.js plus Bootstrap + Popper.js inside it's only 68kb (see : https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.bundle.min.js) I think it's light and if you enable GZIP it'll be lighter

Thank you @FezVrasta :+1:
