### ISSUE TITLE
Drawer, sidebar, offcanvas nav

### ISSUE THREAD

**Issue by davidenco** [twbs/bootstrap#24718]
Does the navbar in BS4 have an option whereby the hamburger menu slides from right to left, also pushing the content to the left too, instead of top to bottom?

**Comment by farooq07** [comment]
You want an offcanvas menu ?

**Comment by SamThilmany** [comment]
This thread seems to have fallen into oblivion. Too bad, because an "offcanvas menu" in Bootstrap would be really great.

In this commentary I want to present some useful information that are – in my eyes – relevant for such a menu. For the developers it is certainly an advantage that the frontend framework [UIkit](https://getuikit.com) offers such an [offcanvas menu](https://getuikit.com/docs/offcanvas), which meets all requirements for a good menu. So you only have to add it in Bootstrap.

### A few important features:

The menu should be openable with different animations:
- Reveal
- Push
- Slide

Furthermore, an overlay should be placed over the rest of the page when the menu is open.

Most important is that the **body is not scollable** when the menu is open. Unfortunately, it is not sufficient to set the overflow to hidden, as touch devices ignore it. On mobile phones this results in a very annoying scrolling behaviour, especially if the menu itself is scrollable. Thus, a solution has to be found how to prevent the scrolling of the body both on the desktop and on mobile devices when the menu is open. The latter must of course remain scrollable.

This has already been implemented by UIkit. Just have a look at one of the [overlay examples](https://getuikit.com/assets/uikit/tests/offcanvas.html) on a touch device.

### Final words

I really hope that this can be implemented in the next version of BS4 since the lack of this component in my eyes would be a good reason for a switch to UIkit.

I wanted to create such a component myself and make it available as a pull request, but unfortunately I fail to implement the important scroll sublink. This was probably solved with JavaScript in UIkit, unfortunately I don't understand the code. To all developers: UIkit is, like Bootstrap, an open-source project, so you can find their approach on [GitHub](https://github.com/uikit/uikit).

**Comment by Johann-S** [comment]
There is a off canvas example here: https://getbootstrap.com/docs/4.1/examples/offcanvas/

**Comment by SamThilmany** [comment]
That's right, but it expands to the full width which is not recommended in the context of good UX design since the user no longer sees on which page he is. It could be the impression of a page change, although one has actually only opened a menu. For this reason, it is recommended to open the menu only over 80% to 90% of the width and thus still display the actual page. Here, the scrolling behaviour described by me becomes important.

Since bootstrap is usually a very user-friendly framework, I think there is definitely a lot of catching up to do here. I would like to refer you to the resource I mentioned, which solved the UX perfectly. Bootstrap should definitely do something in that form as well.

**Comment by viktorsmari** [comment]
I think the [Offcanvas](https://getuikit.com/docs/offcanvas) menu (not filling the whole screen, only ~80%) is becoming a _standard_, and I would really like Bootstrap to support it. 

There have been made a couple of PR on this, but I have never seen them merged, only talk about a new component being made, but I cannot find if it is being worked on.

**Comment by davidenco** [comment]
I ended up using [this ](https://github.com/FrDH/jQuery.mmenu)instead.

**Comment by thehitechpanky** [comment]
Last comment is more than an year ago. Is this in pipeline?

**Comment by viktorsmari** [comment]
Could this be related? https://github.com/twbs/bootstrap/pull/29017

**Comment by mariusa** [comment]
Would love a component similar to https://coreui.io/docs/components/sidebar/ or https://vuetifyjs.com/en/components/navigation-drawers

**Comment by dimitor115** [comment]
Hi everyone 😸 I have created some concept of bootstrap sidebar / side-menu. The design and behaviour is inspired by [gitlab](https://gitlab.com/) and [coreui](https://coreui.io/). The side-menus are really popular in the admin panels / dashboards and many of them uses Bootstrap components, so it will be awesome to have such component here.

Here is my concept: https://jsfiddle.net/dimitor115/v9sf4rxb/61/
@mdo @XhmikosR @MartijnCuppens If you like the whole idea, I would love to prepare PR and polish the code with your help! 


<img width="344" alt="obraz" src="https://user-images.githubusercontent.com/3342963/81786338-c885ba80-94ff-11ea-9f59-4a24848f435c.png">
<img width="344" alt="obraz" src="https://user-images.githubusercontent.com/3342963/81786406-e2270200-94ff-11ea-9976-5e4b3484c952.png">

**Comment by rafalp** [comment]
@dimitor115 Have you seen this PR?

https://github.com/twbs/bootstrap/pull/29017

**Comment by dimitor115** [comment]
@rafalp yes! But in that PR only the offcanvas was introduced. My goal was to extend bootstrap nav component to be use as sidebar with this minimized version (very helpful for smaller resolutions). I also think that these two feature can work together!

**Comment by XhmikosR** [comment]
At the moment, we plan to finish #29017 for v5.0.0. Not sure about your solution, but feel to make a PR against master and we'll try to have a look. So many things to do, so there might be a delay, though.

**Comment by dimitor115** [comment]
@XhmikosR thanks for responding! I will create a PR and describe carefully my idea for this components and it's potential usage. Understand that the maintainers are focused on 5.0.0 release, no pressure from my side 😸
