### ISSUE TITLE
if we zoom 200% https://getbootstrap.com websites shows mobile view instead of desktop view

### ISSUE THREAD

**Issue by onlinerahul** [twbs/bootstrap#24721]
Hello Guys, 

We have ADA defect under the section of 1.4.4 Resize text: Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality. (Level AA) 

If user zoom 200 %, Mobile view appear instead of that Desktop view should appear.

**Comment by dushkostanoeski** [comment]
It's an expected outcome. When zooming in, the size of the viewport goes down and eventually you'll move to a mobile view size.

**Comment by onlinerahul** [comment]
But dont you think we should fix this default issue? As it impact Accessibility challenges

**Comment by patrickhlauke** [comment]
full-page zoom in modern desktop browsers changes the CSS viewport width/height of the browser window. there's nothing that can be fixed. it's expected behavior.

the important part here is "without loss of content or functionality" - as long as your mobile view has the same content and functionality (and you've not simplified/dumbed down the site for mobile), there is no accessibility problem.
