### ISSUE TITLE
Why no sidemenu?

### ISSUE THREAD

**Issue by tarekgabarin** [twbs/bootstrap#24769]
I really don't see why there can't a built in option for a toggable side-menu like Materialize and other CSS frameworks. It's just annoying having to build my own every time I use Bootstrap. At least give people the option.

**Comment by wolfy1339** [comment]
There's actually someone who accomplished something like what you described using modals and sent in a PR. Try searching for that and check out that solution

**Comment by mdo** [comment]
We've never said no to it, we just haven't built it. #21540 is the latest pass and I'm leaving that PR open  for it. I've closed the issues for it since we haven't had someone around to code it and I don't want to set expectations around it, but maybe we leave one open for now.

Closing as duplicate of #24718 though.
