### ISSUE TITLE
Bootstrap 4  form-check alignment with horizontal label

### ISSUE THREAD

**Issue by migliori** [twbs/bootstrap#24844]
Vertical alignment between a main horizontal label and checkboxes or radio is wrong.

The main label has the `.col-form-label` class, which adds a padding-top: `padding-top: calc(.375rem + 1px)`

The radio buttons have no padding top, so they're too high.

I made this pen to show the issue: [https://codepen.io/migli/pen/yPKbwL](https://codepen.io/migli/pen/yPKbwL)

The pen also includes a simple css proposal to resolve it.

**Comment by ysds** [comment]
A horizontal label and control vertical alighment issue can be confirmed [here](https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form) as well. (The "Radios" row)
I think we should not solve this by CSS because CSS will be more complex and more difficult to understand the responsive behaveor. When resize a window to mobile size on your codepen, you can see a slightly larger spacing between the label and first checkbox.

To resolve this issue, just add `pt-{breakpoint}-0` to `.col-form-label` (or `.col-form-legend`).

```html
<form>
  <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-legend col-sm-2 pt-sm-0">Radios</legend>
      <div class="col-sm-10">                 ^^^^^^^
        <div class="form-check">...</div>

```

**Comment by migliori** [comment]
The mobile size spacing can be easily solved with a media query (I edited my pen)

My first idea was yours, but If you remove the label's top padding the label is too close from the previous element, it breaks the vertical alignment: https://codepen.io/migli/pen/mqxQjo

I also noticed that the [example code](https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form) was a bit inconsistent.

The main label for radio is `<legend class="col-form-legend col-sm-2">Radios</legend>` while the checkbox's main label is `<div class="col-sm-2">Checkbox</div>`

**Comment by mdo** [comment]
Perhaps we instead advise folks to simply not use that class? https://codepen.io/anon/pen/BmORRj

**Comment by migliori** [comment]
it's a possibility, but it breaks the regularity of the vertical alignment of labels.

**Comment by mdo** [comment]
The regularity of the alignment isn't my concern I think, and I don't imagine it's the concern of anyone else reporting this issue. The more important part is that this one label matches it's inputs.

**Comment by migliori** [comment]
it's up to you
