### ISSUE TITLE
Dropdown bug with initial position in IE 11

### ISSUE THREAD

**Issue by Dani216** [twbs/bootstrap#24851]
Hi everyone,

After click on menu item it opens the dropdown, but initial position of dropdown is left and that cause stretching `body` tag and horizontal scrollbar is visible. 
It works in Chrome but in IE11 not, sadly  IE11 is important for us.

Example: https://jsfiddle.net/n4wx19x5/
 ![b4-dropdown-bug](https://user-images.githubusercontent.com/14002753/33133101-00181140-cf9c-11e7-92e7-ca177304fbf5.gif)

- Windows 10, IE11, 4.0.0-beta.2

Thanks
Dan

**Comment by Johann-S** [comment]
Not sure if it's a Popper.js issue here 🤔

**Comment by FezVrasta** [comment]
The dropdown position is correct so I exclude a Popper.js bug.

**Comment by Dani216** [comment]
Hi guys,

do you have any advice how to fix this?

**Comment by naviciroel** [comment]
Having same issue but the scroll does not appear...
![bs-drop-issue](https://user-images.githubusercontent.com/6640515/34070362-f13ee718-e29f-11e7-8f6a-2f899c1e28b2.png)

**Comment by caseyjhol** [comment]
@Johann-S This same issue also occurs when the dropdown is at the bottom of the page: https://plnkr.co/edit/MsXrkv8L7SxpAGkrZTgo?p=preview.

![dropdown_popper](https://user-images.githubusercontent.com/2874325/40625665-13e99cf8-6271-11e8-8d12-422a9fa9a03f.gif)

This is happening because of the split-second styling that is applied before Popper can position the menu using translate3d/transform.

Using a modified version of Popper where [this line](https://github.com/FezVrasta/popper.js/blob/deb893feaeb62c800038f35d02db70f55c7a8fe5/packages/popper/src/modifiers/computeStyle.js#L89)
```js
styles[prefixedProperty] = `translate3d(${left}px, ${top}px, 0)`;
```
is removed, you can see why the extra scrollbar is created (https://plnkr.co/edit/EJ7OghknSZLeCl3f69Rc?p=preview).

![dropdown_popper2](https://user-images.githubusercontent.com/2874325/40625852-15fa406e-6272-11e8-9627-ac79c289c633.gif)

Apparently in modern browsers this has been optimized to never render the menu in the initial position, so the extra scrollbar is never created. A hacky workaround would be to temporarily force the menu to have `top: auto, bottom: 100%` (like a normal dropup), and once the transform has been applied revert top and bottom to whatever Popper initially set it to (`top: 0, bottom: auto`).

**Comment by Johann-S** [comment]
thanks @caseyjhol 👍 and you did the right thing by openning an issue on Popper.js 😄

**Comment by XhmikosR** [comment]
@Johann-S: should we close this?

**Comment by Johann-S** [comment]
yep 👍

**Comment by GavinSutherland** [comment]
Did a workaround to this ever get figured out? All I'm seeing is Bootstrap saying its a Popper bug and Popper saying it isn't a bug and that it's a Bootstrap issue.

I think it's an issue in Edge too as opening [this Plunker](https://next.plnkr.co/edit/e15FEWlKaHPdLGJo?preview) demonstrates.

**Comment by caseyjhol** [comment]
@GavinSutherland I never found a workaround. It is certainly a Popper issue (as you can see in the reduced test case I posted in https://github.com/FezVrasta/popper.js/issues/636). But I'm more inclined to say it's an Edge bug which comes to light due to the way Popper applies the positioning. I think it would be possible to find a solution, but so few of my users use Edge, I figured it wasn't worth it to spend any more time on it.

**Comment by caseyjhol** [comment]
@GavinSutherland See https://github.com/FezVrasta/popper.js/issues/636#issuecomment-474572516.

```js
new Popper(..., ..., {
  modifiers: {
    computeStyle: {
      gpuAcceleration: false,
    },
  },
});
```

**Comment by GavinSutherland** [comment]
Thanks @caseyjhol  ... I'll go check that out
