### ISSUE TITLE
Transitionend with bootstrap 4

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#24958]
When looking into the necessity of $.support.transition.end, it seems to be that this is no longer needed.

I see that some properties were removed here:

https://github.com/twbs/bootstrap/pull/24511

But `webkitTransitionEnd` remains. However, according to https://caniuse.com/#feat=css-transitions, all browsers that bootstrap 4 supports use `transitionend` just fine. Is this even needed anymore?

**Comment by Johann-S** [comment]
It seems you're right @719media :+1: 
/CC @XhmikosR

**Comment by XhmikosR** [comment]
True, we can remove it. I'll make a PR later or if someone else does just
CC me.

On Dec 7, 2017 10:37, "Johann-S" <notifications@github.com> wrote:

It seems you're right @719media <https://github.com/719media> 👍
/CC @XhmikosR <https://github.com/xhmikosr>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/issues/24958#issuecomment-349898627>,
or mute
the thread

**Comment by kamlekar** [comment]
@XhmikosR I did the PR. and cc'ed you. Not sure whether I have done it correct. Please check.
