### ISSUE TITLE
File browser does not show file name

### ISSUE THREAD

**Issue by Wolfr** [twbs/bootstrap#24995]
When you attach a file using the custom input type file, it does not show the name of the attached file. I believe this is a bug.

Expected behavior: change “Choose file” into the filename.

https://getbootstrap.com/docs/4.0/components/forms/?#file-browser

Tested with docs @ v4.0.0 in Google Chrome 63 and Safari 11.

**Comment by wolfy1339** [comment]
As per the docs:
> requires additional JavaScript if you’d like to hook them up with functional Choose file… and selected file name text.

**Comment by Johann-S** [comment]
closed thanks to @wolfy1339 :+1:

**Comment by deepaksood619** [comment]
What is the best way to do that? 
Documentation should include the code snippet for doing that using either js or jQuery.

**Comment by Wolfr** [comment]
Here's the jQuery based code I used.

````
$("input[type=file]").change(function () {

  var fieldVal = $(this).val();

  // Change the node's value by removing the fake path (Chrome)
  fieldVal = fieldVal.replace("C:\\fakepath\\", "");

  if (fieldVal != undefined || fieldVal != "") {
    $(this).next(".custom-file-control").attr('data-content', fieldVal);
  }

});
````

**Comment by deepaksood619** [comment]
Thanks a lot @Wolfr 
But I really think that this code snippet should be shown in **documentation**.

In you code snippet, `.custom-file-control` must be changed to `.custom-file-label` and also along with `data-content`, `text` value must also be set.

Also the label box is not responsive, since the text is overflowed and wrapped onto second line outside the label box. So css needs to be added. I think it should be reported as bug.

<img width="469" alt="screen shot 2017-12-29 at 6 13 46 pm" src="https://user-images.githubusercontent.com/13206612/34437419-0d64c902-ecc4-11e7-912c-c34de59a821c.png">

Here is the final implementation on [Codepen](https://codepen.io/deepaksood619/pen/zpwYrP)

**Comment by asyura** [comment]
## # qwqwq

**Comment by harshitbansal373** [comment]
Here's the jquery code which can be used to solve this **issue**

`      $('#inputGroupFile01').on('change',function(){
          //get the file name
          var fileName = $(this).val();
          // removing the fake path (Chrome)
          fileName = fileName.replace("C:\\fakepath\\", "");
          //replace the "Choose a file" label
          $(this).next('.custom-file-label').html(fileName);
      })`

This code is working successfully And this should be mention in the **documentation**  So that there are No conflict.
