### ISSUE TITLE
btn-dark with no href

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#25092]
bootstrap 4 beta2 (and looks like still happening on latest v4-dev as well)

Hello,

When using `<a class="btn btn-dark">Test</a>`, the text appears dark because of the no href rule that is setting `color: inherit` for <a> tags without href.

Minor issue, I know, but I thought it potentially should be fixed. I am not sure the best way to fix this because I don't fully understand the reason for the a without href being set to` color: inherit`

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by patrickhlauke** [comment]
an `<a>` without an `href` is an anchor, not a link, which is why it's not given any explicit text color. you should use a proper link or a `<button>` element if your control is meant to be interactive (for instance, your `<a ...>Test</a>` is currently not focusable nor actionable for keyboard users).

**Comment by mdo** [comment]
What @patrickhlauke said.

**Comment by patrickhlauke** [comment]
@mdo having said that, wondering if we should just set background AND foreground color for things like `.btn` classes explicitly. thoughts?

**Comment by mdo** [comment]
Don't all our buttons have `color` and `background-color` already? The problem is the `:not([href])` is more specific than the `.btn` class, right?

**Comment by patrickhlauke** [comment]
@mdo ah, good point - admit i've not looked at our actual styles in a while. if i get a moment, may look into maybe avoiding the `:not([href])` causing the issue, and instead making sure only `a[href]` get the link color instead (turning the issue around, in essence - style forward, rather than style and then backtrack the styling if `href` is missing)
