### ISSUE TITLE
Flex container-fluid inside navbar

### ISSUE THREAD

**Issue by andreypelykh** [twbs/bootstrap#25093]
- Operating system and version: Windows 10
- Browser and version: Chrome 63.0.3239.84
- Bootstrap version: 4.0.0-beta.2
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/andrey149502/pen/GyWgyO/)

1. Create `.container-fluid` block inside `.navbar` block
2. Add `.row` and two or more columns inside navbar
3. The columns get placed one under one.

Adding `.d-block` class for `.container-fluid` block resolves the problem. But I think initially `.container-fluid` inside `.navbar` shouldn't be `display: flex`.

**Comment by mdo** [comment]
The navbar wasn't intended to have grid classes within, which is why the containers are set to a `display: flex`, but that's beside the point. When you have a flex container (anything with `display: flex`), the elements within that will be flex children. Unless a width is specified, those flex children will collapse. Add `.w-100` to the `.row` if you need that particular markup.
