### ISSUE TITLE
4.0.0-beta.3 - breakpoints are broken in Safari with new support for fractional viewport widths

### ISSUE THREAD

**Issue by liquidvisual** [twbs/bootstrap#25166]
Beta 3 has broken some of my sites that were using the breakpoint-down mixin. This seems to only be affecting Safari (MacOS and iOS).

I realise this has to do with the support for fractional viewport widths as [discussed here](https://github.com/twbs/bootstrap/pull/24299).

I've put together a Codepen to demonstrate this:

https://codepen.io/liquidvisual/pen/VyWMGM?editors=1100 (open in Safari)

**Comment by patrickhlauke** [comment]
Due to a bug in Safari. Will see if there's some way to work around this bug.

**Comment by patrickhlauke** [comment]
xref https://bugs.webkit.org/show_bug.cgi?id=178261

**Comment by MartijnCuppens** [comment]
This case can easily be solved with `not`: https://codepen.io/MartijnCuppens/pen/LeLgRN/?editors=1100

However, for `media-breakpoint-between` and `media-breakpoint-only` this will not solve a thing because you can only use `not` to invert a media-query-rule and not a part of a media-query rule.
For examle `@media (min-width: $min) and not (min-width: $max)` doesn't work.
