### ISSUE TITLE
Error Starting react app "Undefined variable: \"$hr-margin-y\"

### ISSUE THREAD

**Issue by xandershk27** [twbs/bootstrap#25189]
When ever i start react app it give me this error
```
{
 "status": 1,
 "file": "/home/ubuntu/webapp/honeyguideapp/node_modules/bootstrap/scss/_type.scss",
 "line": 56,
 "column": 15,
 "message": "Undefined variable: \"$hr-margin-y\".",
 "formatted": "Error: Undefined variable: \"$hr-margin-y\".\n        on line 56 of node_modules/bootstrap/scss/_type.scss\n>>   margin-top: $hr-margin-y;\n   --------------^\n"
}
```
Any suggestion to solve this issue.
Server detail:
node v8.9.1
npm 5.6.0
dependencies: "bootstrap": "^4.0.0-beta.2"

**Comment by XhmikosR** [comment]
This isn't the right place to ask such questions. Maybe try StackOverflow.

**Comment by Johann-S** [comment]
Sorry, but we cannot help with how-to or general troubleshooting issues here; only bug reports and feature requests. You'll want to ask around in the official Slack team or Stack Overflow. [See our readme for more details](https://github.com/twbs/bootstrap#community).

**Comment by htmlstream** [comment]
@xandershk27 Try to update SASS files to bootstrap-4.0.0-beta.3 from beta.2 as the variable **$hr-margin-y** does not exist in _variables.scss (beta.2) file .

**Comment by dimitarangelkov** [comment]
Gentleman, I think this is the right place for this specific question, since looks like someone in your team changed completely some of the variables in the current state of version bootstrap-4.0.0-beta.2 . Make a diff with a state of the same "bootstrap-4.0.0-beta.2" version from November, and will see what I am talking about. It is complete disaster, since when someone want to install this specific version for code written at the end of the last year, the code will not work any more.
