### ISSUE TITLE
Progress bar text is wonky when <3% and in .card

### ISSUE THREAD

**Issue by jacroe** [twbs/bootstrap#25235]
When a progress bar is included within a card and its value is less than 3%, the text becomes stacked with the number above the percentage sign. https://jsfiddle.net/gseffeqr/

![image](https://user-images.githubusercontent.com/1142635/34690529-829fda3e-f487-11e7-86ff-4ee1768ee993.png)

This is occuring in Chrome, Firefox, and Edge.

**Comment by morrissey-ingenious** [comment]
you can add the class `text-nowrap` to the `progress-bar` to resolve this.

**Comment by mdo** [comment]
Probably should at the wrapping by default, hmm...

**Comment by km1230** [comment]
**.card** has a built-in style {word-wrap: break-word;} that wrap text into next lines.
It is better to add a style {word-wrap: normal;} for your content inside **.card**

**Comment by MartijnCuppens** [comment]
@km1230, that's indeed the reason why the `2%` breaks. But if we want to prevent texts like `2% done` to break, we should add `white-space: nowrap`.

**Comment by km1230** [comment]
@MartijnCuppens, totally agree! That's de facto what I did whenever I use Bootstrap card component. Overriding both word-wrap & white-space to secure the layout!

**Comment by MartijnCuppens** [comment]
`white-space: nowrap;` will always prevent word wrapping, so I don't think it would be necessary to add `word-wrap: normal;`

**Comment by MartijnCuppens** [comment]
@mdo, if you remove `word-wrap: break-word;` from `.card` (#25063), text with spaces will still break in the progress bar. #25248 would fix this.

**Comment by LeeEvans1234** [comment]
Thank You I'm 67 years old and very new to this but I'm a quick learner
please if I  mess up let me know how and I learn fix it

On Jan 17, 2018 5:35 AM, "Martijn Cuppens" <notifications@github.com> wrote:

@mdo <https://github.com/mdo>, if you remove word-wrap: break-word; from
.card (#25063 <https://github.com/twbs/bootstrap/pull/25063>), text with
spaces will still break in the progress bar. #25248
<https://github.com/twbs/bootstrap/pull/25248> would fix this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/issues/25235#issuecomment-358277950>,
or mute
the thread

**Comment by LeeEvans1234** [comment]
Thank you very much
