### ISSUE TITLE
Default z-index sequence in cards

### ISSUE THREAD

**Issue by SalehIA** [twbs/bootstrap#25272]
Default setting of z-index sequence in cards should be from the back to the front as follows
heading image
             image overlay
body
footer

image overlay in default settings blocks the body and footer.

**Comment by mdo** [comment]
Without a live demo, I'm unsure of the problem. My guess is you have all those elements in a `.card` and the overlay is covering them because of the absolute positioning. Either stick to the image caps or wrap your overlay and image in `.position-relative` to prevent it from overlapping additional content.
