### ISSUE TITLE
table-responsive broken?

### ISSUE THREAD

**Issue by AndiLeni** [twbs/bootstrap#25294]
I think the class responsive-table is corrupted. See codepen below.

https://codepen.io/AndiLeni/pen/aEKKdd

**Comment by lushkant** [comment]
@AndiLeni The latest Bootstrap beta3 release has made responsive tables a parent class once again and in order to make your tables responsive you should use .table-responsive class as  a parent class wrapping over the .table class.

`<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>`

**Comment by lushkant** [comment]
@AndiLeni The latest Bootstrap beta3 release has made responsive tables a parent class once again to avoid accessibility issues while changing display property.
In order to make your tables responsive you should use **.table-responsive** class as a parent class wrapping over the **.table** class.

**Comment by AndiLeni** [comment]
@lushkant thanks for your answer. I completely overlooked that fact. No hard feelings.
