### ISSUE TITLE
Upgrade from Alpha to latest Beta

### ISSUE THREAD

**Issue by danimanca** [twbs/bootstrap#25307]
Folks I am scraping the web for some instructions on how to upgrade to the latest version of BS4 without making too much damage, can anyone assist please, I couldn't find any good article nor video...

**Comment by mdo** [comment]
Each alpha was immensely different from the last, and same goes from alpha to beta. There's no comprehensive guide because of the length of time and breadth of changes. I'd suggest jumping to the latest beta docs and seeing what's broken after updating your CSS/JS. We've highlighted changes on our blog, too.
