### ISSUE TITLE
Resize examples screenshots

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#25311]
The old ones were 1600x1200, resized in the HTML to 800x600 (**ratio 1.33**).

The new ones after #24898 are 1440x900 so with **a ratio of 1.6**, yet we still resize them in the HTML to 800x600 (**1.33**).

IMO, we should resize the PNGs to whatever dimensions we show the thumbnails. Sure, they won't look as crisp as they can on retina displays but it's so many bytes to ignore.

/CC @mdo: ping me if you resize them and make a PR so that I can compress them before we merge.

**Comment by mdo** [comment]
Opened #25318 to tweak the dimensions and make one small column change, but haven't resized yet. the largest they'll be is 480px wide across all of `xs`. From there they stay smaller in most cases. For retina then, we want at least 2x, so that means `960px` for a reduction of 1/3 the pixels. I can see resizing to that, but the main reason I went with those dimensions is ease of updating for myself. Just pop into fullscreen at 1440x900 resolution, screenshot, compress, and push.

Might want to look into a script for myself.

**Comment by XhmikosR** [comment]
I'll have a look tomorrow please don't merge yet.
