### ISSUE TITLE
Bootstrap Navbar toggle button is not working on real iphone 7 device.

### ISSUE THREAD

**Issue by devgithubweb** [twbs/bootstrap#25368]
Hi everyone.
Please Help me.

Bootstrap Navbar toggle botton is not working on Iphone 7.
I tested on several devices but it is not working on only iphone 7.

One important point is that it is working well on desktop web browser mobile responsive and browserstack.com, but not work on only real device - Iphone.

**Comment by patrickhlauke** [comment]
the various examples on https://getbootstrap.com/docs/4.0/components/navbar/ work fine on my iPhone7. i'll hazard a guess that it's down to your implementation, rather than anything wrong with bootstrap itself. suggest you try asking (with some more specific example to show the problem you are having) on stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
