### ISSUE TITLE
Bootstrap v4 breaks Content-Security-Policy compared to Bootstrap v3

### ISSUE THREAD

**Issue by yahesh** [twbs/bootstrap#25394]
As it seems, Bootstrap v4 is now using "data:image/svg+xml" background-urls which leads to errors when using a Content-Security-Policy like `default-src 'self'; form-action 'self'; frame-ancestors 'self'; require-sri-for script style`. In order to be able to migrate from Bootstrap v3 to Bootstrap v4 one would have to weaken the Content-Security-Policy protection.

IMHO that's a regression.

![broken CSP in chrome](https://user-images.githubusercontent.com/103765/35200907-03c46dee-ff16-11e7-99c1-56787bca3d71.png)

**Comment by mdo** [comment]
Hmm, interesting—hadn't considered this at all with the embedded SVGs. I suppose the easiest path forward for this is documenting a way to swag our navbar toggler for a custom one.

**Comment by ogonkov** [comment]
Also, inline SVG put aside document parsing (more CSS to parse === more time document wait for it to be loaded)

I think it's better to inline them on project bundling via Grunt or Webpack (if you really want less http requests but bigger CSS bundle)

**Comment by cramhead** [comment]
When using the snippets on the [getbootstrap intro page](getbootstrap) I get a content security policy error.

There error in Firefox includes a line number, unfortunately Chrome does not. The error is
`Content Security Policy: The page’s settings observed the loading of a resource at self (“script-src http://localhost:5000 https://maxcdn.bootstrapcdn.com https://cdnjs.cloudflare.com https://code.jquery.com”). A CSP report is being sent. Source: !function(a,b,c,d){var e,f=document,g=f.....
Home:10
`

When look the html source in firefox I can see the new meta tag added that raises the issue
![image](https://user-images.githubusercontent.com/386035/37540699-2e196ada-2915-11e8-97a9-4dbc89bff54f.png)
Moving over to the right a bit I can see that is an inline injection from bootstrap
![image](https://user-images.githubusercontent.com/386035/37540752-6508f268-2915-11e8-9e38-1822127fb94e.png)

To remove the error I have to allow unsafe inlining of JavaScript

**Comment by XhmikosR** [comment]
@cramhead: definitely not something we have on the site.

**Comment by cramhead** [comment]
@XhmikosR: What do you mean? 
That you don't have inline scripting disabled? 
It seems there are no content security policies defined [getBootstrap csp headers](https://cspvalidator.org/#url=http://getbootstrap.com/docs/4.0/getting-started/introduction/)

**Comment by XhmikosR** [comment]
There's no CSP for our site. Also, we don't have any inline snippets in the
main page.

**Comment by cramhead** [comment]
You do realize that I'm referring to the snippets that others use to work with the bootstrap library. Correct?
![image](https://user-images.githubusercontent.com/386035/37542995-64b90ed0-291d-11e8-88e3-8bab3c2e8f24.png)

**Comment by XhmikosR** [comment]
I do, and I don't see why you say you get that with our snippet when
clearly the error message you posted mentions something inlined which we
don't do. So it's something else; Unrelated to this issue or even bootstrap
itself. But if you still believe it's something on our side make a separate
issue.

On Mar 16, 2018 22:27, "Marc" <notifications@github.com> wrote:

You do realize that I'm referring to the snippets that others use to work
with the bootstrap library. Correct?
[image: image]
<https://user-images.githubusercontent.com/386035/37542995-64b90ed0-291d-11e8-88e3-8bab3c2e8f24.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/issues/25394#issuecomment-373834770>,
or mute
the thread

**Comment by cramhead** [comment]
@XhmikosR Thanks for you help. 

Your clarification got to make a separate minimal example.
It turns out that asp.net core's mvc taghelper is injecting the code and violating the content security policy. It's part of the failover infrastructure to check if the script was correctly loaded and if not download the script from a secondary source. I was not aware of this problem, but apparently others were; https://github.com/aspnet/Mvc/issues/4300. 

Also @yahesh I bumped into this issue as well. It turns out if you use specify the `data:` schema in your policy it will stop complaining
Note the `data:` in the `img-src` below. The content security policy works with the code snippets defined on [getbootstrap intro](http://getbootstrap.com/docs/4.0/getting-started/introduction/)
```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://code.jquery.com https://cdnjs.cloudflare.com https://maxcdn.bootstrapcdn.com; style-src 'self' https://maxcdn.bootstrapcdn.com data:; img-src 'self' data:;">
 ```

**Comment by yahesh** [comment]
@cramhead Could you **please** stop spamming this issue with non-related content.

Furthermore... **of course** there is the possibility to relax the CSP and thus work around this issue. This issue is here because you would have to do that to be able to migrate from bootstrap v3 to bootstrap v4. That's **exactly** the regression this very issue is about - as can be seen in the second sentence of the issue text which reads _"In order to be able to migrate from Bootstrap v3 to Bootstrap v4 one would have to weaken the Content-Security-Policy protection."_ As you may know, allowing "data:" URLs is considered insecure, as can be read [over at Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src#Sources) for example:

> data: Allows data: URIs to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.

**Comment by mdo** [comment]
We'll try to tackle this as part of v5 when we get to that and can make breaking changes to our components to move the background images from base64 to in-HTML elements.

**Comment by mjgs** [comment]
@mdo Bootstrap v5 seems like it could be a long way off. You mentioned earlier in the thread that a good workaround might be to replace the navbar toggler icon with a custom one. I tried doing this but all the alignment was all messed up on small screens, could you share the documentation you had in mind, so those of us trying to implement CSP can get something functional and secure?

**Comment by ogonkov** [comment]
Could it be fixed with `file-loader`?

**Comment by XhmikosR** [comment]
Note that we don't use one SVG, so this isn't only about the navbar toggler icon.

Your best bet is to relax CSP allowing `data:` for now.

**Comment by XhmikosR** [comment]
Unfortunately, that's how it is. We can't introduce potentially breaking changes right now.

v5 is the next major version and work has already started in the `v4-without-jquery` branch.

**Comment by mjgs** [comment]
@xhmikosr in your opinion is the custom macabre toggler icon workaround
possible?

**Comment by XhmikosR** [comment]
Yeah, but like I said there are a lot more cases we use CSS-inlined SVGs, so I'm not sure if changing the toggler icon alone will be enough. I usually use purgecss in my build process so it's enough for me.

**Comment by mjgs** [comment]
It will at least be enough for fixing the navbar toggler csp issue. Using the [octicon hamburger icon](https://octicons.github.com/icon/three-bars/)...

When I swap out 

```
<span class="navbar-toggler-icon"></span>
```

for 

```
<span data-toggle="tooltip"
      data-delay="<%= tooltipDelayMs %>"
      data-placement="bottom"
      title="Menu">
  <%- include('../icons/three-bars.svg') %>
</span>
```

The toggler renders fine in the browser and without a CSP error, although it looks a little different (slightly smaller), but the main problem is that when viewed in Chrome devtools device tool, it's set in from the right side for most phone sized devices.

Do I need to add some other styling so that it renders correctly on all screens?

**Comment by emiranda04** [comment]
@mdo "We'll try to tackle this as part of v5". 
Amazing answer 👎 
is BS3 vulnerable ?  no rush to upgrade() : migrate to BS4()
Then you realize that BS4 breaks CSP.

**Comment by philwolstenholme** [comment]
For people building Bootstrap from the source (rather than including the compiled CSS and minified JS) you could use https://www.npmjs.com/package/patch-package to edit thrn subsequently patch (on each install) the Bootstrap source to remove the data URIs and include the SVGs in an alternative way that will satisfy your CSP requirements.

**Comment by emiranda04** [comment]
Thanks for this info! I will look into it :-)

**Comment by mjgs** [comment]
The rendering issue looks like it might be a Chrome devtools bug, I have checked using a responsive design testing browser extension and all device sizes render correctly. I was also able to extract the bootstrap svg and use it instead of the octicon svg. 

Here are the steps I took to get the toggler rendering without the CSP error:

1) Download the bootstrap hamburger svg using [devtools](https://stackoverflow.com/a/46259485)
2) Add the svg to the HTML
```
<span class="hamburger" 
      data-toggle="tooltip"
      data-delay="<%= tooltipDelayMs %>"
      data-placement="bottom"
      title="Menu">
  <%- include('../icons/hamburger.svg') %>
</span>
```
3) Add css
```
.hamburger {
  display: inline-block;
  height: 1.5em;
  vertical-align: middle;
  width: 1.5em;
}
```

**Comment by meteorplus** [comment]
what's the ETA on this? dont be lazy please

**Comment by philwolstenholme** [comment]
Hi @meteorplus, the maintainers of Bootstrap and other open-source projects put a **huge** amount of their own time and mental energy into providing an amazing product for absolutely no cost to users like you and I, that's the complete _opposite_ of lazy.

Please don't use such language on open-source projects; think how harder your life (and all of our lives at work) would be if all the open-source maintainers of the world got burnt out and said "_that's it, our time and energy clearly isn't being respected, we'll stop maintaining our projects and remove them from Github_".

It looks like some workarounds have already been posted in this thread, have you tried any of them? People will help if you have tried them and run into specific issues, but if you haven't tried them yet and are just waiting for the Bootstrap team to deliver a fully formed solution on your timescale while also working on the 270 other open Bootstrap issues on Github then that sounds a bit lazy in itself.

**Comment by Grinnz** [comment]
I have not found any reason that it is actually a problem to include `data:` only in your `img-src` policy to allow this. See https://security.stackexchange.com/a/167244

**Comment by KennyStier61** [comment]
Any update on the issue? I'm currently creating a CSP and the workaround is not ideal.

**Comment by C-REMO** [comment]
The same happened to me, luckily I was using font awesome icons and just switched
`<span class="navbar-toggler-icon"></span>` with `<span class="fas fa-bars"></span>` and it looks great, maybe someone finds it useful.

**Comment by rhalf** [comment]
i am also creating a new project using bootstrap 4 as aid for my design. bootstrap 4 has problem with csp. should i revert back to bootstrap 3?

**Comment by crustamet** [comment]
There are so many inline SVG (custom checkbox, radios), toggler, carousel NEXT PREV buttons.

There is a workaround very hard to do that removes those background images and just creates the image using css but this is not going to be good for the designs, because some times 1px left or 1px right on different browser breaks the design :(

**Comment by mdo** [comment]
Know this is still an issue for some folks, so I think there are two things we can do in a v4 patch release to help:

- Provide known options for CSS-only images to replace our embedded SVGs (navbar and carousel only I'm afraid). [See this CodePen demo.](https://codepen.io/emdeoh/pen/xxwberr)

- Update our docs to callout the CSP issue with links to MDN, StackExchange answers, etc for the known issues and relatively safe usage of embedded SVGs in CSS.

Thoughts on what else to include?

**Comment by crustamet** [comment]
Dude there are at least 10 embeded svg in the bootstrap css not only hamburgar and left right chevrons

**Comment by x5engine** [comment]
so how can we get rid of those svg?

**Comment by crustamet** [comment]
Very hard to do so :) in some cases it is enough to change the html and not use bootstrap like chevron and hamburgar

other times you have to fight the css with the browser to align an not embeded icon into place.

Other times is enough just to change the css with a fontawsome icon xD

**Comment by mdo** [comment]
I don't know what you're telling me how many there are or giving some attitude here—I'm the one that added them. 😆

I'm asking as the creator of the project what folks think is the best option in v4 to help folks out. I've shown that it's only really feasible to replace a handful of the icons—custom form controls and form validation styles aren't an option to change due to backward compatibility. And they're not really changeable in v5 either fwiw—there's only so much we can do to customize the appearance of things without requiring custom HTML or other hacks.

**Comment by yahesh** [comment]
What would really help me (with v4 as well as with v5 if it is still a problem there) is a description on how to circumvent the CSP issues created by "data:image/svg+xml" URLs. I'm fine with adding custom HTML and putting required images into an upload folder as long as I know what to do and how that custom HTML should look like.

If there were a resource where I could search for CSS classes that I should not use when using strict CSP rules and what custom HTML to use instead, this would definitely help to switch from Bootstrap v3 (which I'm still using because of this problem here) to Bootstrap v4 or directly to Bootstrap v5 if it's not too far down the road.

**Comment by yahesh** [comment]
At least it is worth a try. :)

**Comment by nickalbrecht** [comment]
I saw the other day that the v5 alpha1 is out. Is this item still on the radar for v5?

**Comment by 9mido** [comment]
Just tried the alpha out and this issue still persists. It is even worse now since practically everything is an svg element. Please bootstrap team fix this issue when the main bootstrap 5 is released!

**Comment by xi** [comment]
> Are you suggesting that replacing the image URLs with your own is enough to ease the problems here?

The workaround I currently use includes extracting the relevant images and adding additional CSS to use those image files:

```
.navbar-dark .navbar-toggler-icon {
    background-image: url("images/bootstrap/hamburger.svg");
}
```

This way I still get the warnings, but the images can be loaded without relaxing the CSP.

I can think of two things that would help with this approach:

- A complete list of selectors/images (e.g. as a CSS file in which I only have to adapt the upload location)
- A folder containing all images so I do not have to extract them manually.

**Comment by nickalbrecht** [comment]
I believe svg images can be embedded in the css as encoded data as well.  So if they are done that way instead of injected a src attribute, that should satisfy the CSP should it not?

**Comment by yahesh** [comment]
> This way I still get the warnings [...]
IMHO getting CSP warnings is not an option.

> I believe svg images can be embedded in the css as encoded data as well. So if they are done that way instead of injected a src attribute, that should satisfy the CSP should it not?
It should be tested before being released.

It's really worrisome that CSP seemingly isn't taken into account **again**. This issue here exists nor for 2,5 years. Noone who is serious about implementing proper CSP policies was was able to migrate from v3 to v4 (me included). Not being able to finally migrate to v5 **again** would mean that I would have to find a different framework that takes security best-practices into consideration during development which Bootstrap seemingly does not do.

**Comment by ffoodd** [comment]
We have open issues and PR about using inlined SVG (in the markup) instead of embedded in CSS. v5 is in it's first alpha, there'll be more breaking changes until a first stable release so please wait — or contribute.

But this issue is definetely in our v5 roadmap.

**Comment by yahesh** [comment]
@ffoodd Thanks for clarification.

**Comment by crustamet** [comment]
Inline SVG would do it, i don't know why they don't implement this already ? if they have a hamburger or other svg inlines they should reallly create some files that can be replaced by other icons also.

**Comment by xi** [comment]
@ffoodd I would be happy to contribute. Can you link the PR you mentioned? I could not find it.

**Comment by ffoodd** [comment]
There's no dedicated PR AFAIK, but multiple discussions on related issues and PR. You may start a dedicated PR if you want, just take some time to search and read comments here and there about inline SVGs.

**Comment by mdo** [comment]
After going back and forth with the team on this, we're most likely sticking with the embedded SVGs in v4 and in v5. We can't use SVGs in the HTML for things like our checkboxes, radios, and selects, so we'd have two different implementations for how we handle SVGs across the project (embedded CSS and inline HTML). It'd also be a larger departure from v4 than I'm willing to make just yet. v6 could be where we really overhaul some of this stuff though and make some different leaps.

Providing documentation on how to replace the images is definitely doable though. I'll stub out a PR shortly for that, along with guidance on what SVGs are included (most are from Bootstrap Icons, so they're easy to replace with external images).

Beyond that, anything else I'm missing

**Comment by nickalbrecht** [comment]
Maybe I'm misunderstanding. Wasn't the problem that enforcing a reasonable CSP policy of `'self'`, broke any element that uses inline style, inline script, or embedded images in the HTML. But that using Embedded images in the CSS itself was fine (since you can use SRI to trust the Bootstrap CSS/JS files? So in this instance it'd be embedded SVG's in the CSS, not injected into the HTML.

Also, ensuring that anything that needs to hide/show something _doesn't_ use inline styles, and instead sets a CSS class.

**Comment by gladiola** [comment]
I had this same problem with Boostrap Carousel colliding with Content Security Policy.  I know it's not an answer to the problem, but I was able to do a workaround with the following simple steps.

- Draft replacement left and right arrow icons in a drawing program.  I used Gimp and built 100x100 pixel PNGs with transparent background.  Place these graphics in a folder readily accessible under the Content Security Policy.
- Drill down into bootstrap.css and identify the classes that need to be overridden.  
- Install replacement CSS, calling the PNG icons with background-image url().
- Adjust the size of the receiving CSS class to meet the icons, as desired.  I found it helpful to completely shut off the background attribute of one of the class calls.

`.carousel-control-prev-icon {
  background-image: url("LeftArrow.png");
}

.carousel-control-next-icon {
  background-image: url("RightArrow.png");
}

.carousel-control-prev-icon,
.carousel-control-next-icon {
  display: inline-block;
  width: 100px;
  height: 100px;

}
`
Notice that with this technique for a workaround, the color of the icons needs to be predetermined.  The "fill" attribute of an SVG element won't be available.

**Comment by mdo** [comment]
Finally opened #32759 to suggest some copy around this. Please review and let me know what you think!

**Comment by 9mido** [comment]
For anybody who wants to see the results of that documentation PR here is the online version:

https://getbootstrap.com/docs/5.0/customize/overview/#csps-and-embedded-svgs

@mdo @XhmikosR and @ffoodd 

What I am confused with this documentation PR is that there is no reference to URLs that you can plug into your CSP configurations. You are just linking to the code documentation page for each element? 

I was hoping bootstrap could provide something like this:

https://content-security-policy.com/examples/

https://stripe.com/docs/security/guide#content-security-policy

Using URLs and plugging them in is much easier than locally hosted assets, inline images, etc.

I wouldn't know where to begin on where to actually download the images/svgs from and then figure out where to put them locally and then how to reference them in my code. There is no guidance for that.

**Comment by ffoodd** [comment]
@9mido Would you mind opening a new issue, please? Your suggestion makes sense and we can improve our docs, for sure.

**Comment by c-shubh** [comment]
Below I've included a stylesheet that overrides the background-image property to use SVG images from the assets directory instead of embedded SVGs.

[bootstrap-svg-fix.zip](https://github.com/twbs/bootstrap/files/7317163/bootstrap-svg-fix.zip)

**Comment by Harleym7000** [comment]
An easy but slightly inconvenient fix for this would be to download the required SVG from the [bootstrap icons website](https://icons.getbootstrap.com/icons/list/)

Then change your HTML document to point to that SVG instead of the bootstrap one. My example is to get the navbar toggle icon to display correctly on smaller-screen devices (mobiles and tablets)

I am saving the SVG to a folder named img

Change this:
`<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>`

To this:
`<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <img src="/img/list.svg">
    </button>`

Here is the result:
![image](https://user-images.githubusercontent.com/48868940/179023373-b703b071-56a3-48d5-a6fd-beeb0eb2770c.png)
