### ISSUE TITLE
When i compile the scss - all the alerts look darker.

### ISSUE THREAD

**Issue by sharomet** [twbs/bootstrap#25421]
Error. When i compile the scss - all the alerts look darker. 
For compilation I use koala-app.

![screen-alerts](https://user-images.githubusercontent.com/4848502/35323417-1705d910-00f6-11e8-83b8-e0f223870eae.jpg)

**Comment by ErinPo** [comment]
+1

It seems to be due to _alert.scss now referencing the new variable $alert-bg-level which is missing  in _variables.scss, though. Somebody forgot it, I presume.

**Comment by mdo** [comment]
Can't help without a reduced test case. Where's this happening, what version, any external changes or in the Bootstrap core?

**Comment by sharomet** [comment]
bootstrap v4.0.0.
I created a custom.scss file and imported it Bootstrap’s source Sass files.
```
@import "bootstrap/bootstrap";
@import "bootstrap/unctions";
@import "bootstrap/variables";
@import "bootstrap/mixins";
@import "bootstrap/reboot";
@import "bootstrap/type";
@import "bootstrap/images";
@import "bootstrap/code";
@import "bootstrap/grid";

// Custom variables
$primary:   #148DC4;
$success:   #0DCD82;
......
```

**Comment by mdo** [comment]
You’ve misspelled “functions” there... is that it?

**Comment by jugyhead** [comment]
I'm using the leafo/scssphp compiler and I expect you guys to face the same issue. The problem seems to be this line in _functions.scss:
`level: abs(level);`

While the leafo/scssphp compiler's `abs()` implementation returns the expected result it also changes the object's value itself. A negative value (-10) then becomes a positive 10 within that function. That means the problem does not occour on the first loop (primary) but on all following.

See here: https://github.com/leafo/scssphp/blob/master/src/Compiler.php#L4765

```
protected function libAbs($args)
{
    $num = $args[0];
    $num[1] = abs($num[1]);
    return $num;
}
```
`$args[0]` is a `Leafo\ScssPhp\Node\Number` (https://github.com/leafo/scssphp/blob/master/src/Node/Number.php) object which implements the `\ArrayAccess` interface. Manipulating the offset 1 of that object simply changes the value of `$dimension` permanentely.

A work-around? Yes:
```
@function theme-color-level($color-name: "primary", $level: 0) {
  $color: theme-color($color-name);
  $color-base: if($level > 0, #000, #fff);
  $level: abs($level + 0);

  @return mix($color-base, $color, $level * $theme-color-interval);
}
```

The `$level + 0` forces the compiler to create a fresh Number object on wich the `abs()` function cannot make any "damage" on.

**Comment by ErinPo** [comment]
I did use leafo scssphp. I got the same problem when compiling with the ruby gem though so I thought it wasn't due to scssphp. BS4 final from the official CDN has normal alert colors, obviously. Only the fiddlers are punished.

**Comment by endcore** [comment]
Got the same problem. 

I just downloaded bootstrap and only defined 

```
@import "bootstrap/bootstrap";
```

in my style.scss. Every alert, except the info, looks dark

![dark-alerts](https://user-images.githubusercontent.com/25451815/36301142-1a249972-1304-11e8-9d13-79f5fc8ff984.JPG)

Even if I activate the gradients:

```
$enable-gradients: true;
@import "bootstrap/bootstrap";
```
![dark-alerts-gradient](https://user-images.githubusercontent.com/25451815/36301203-4e401600-1304-11e8-827d-e88a595a6239.JPG)

Using the follow compiler: https://github.com/leafo/scssphp

**Comment by wolfy1339** [comment]
The problem here is your compiler, it's not acting the same as the official SASS compilers (node-sass and the SASS ruby compiler)

**Comment by mdo** [comment]
Closing this out since it's a problem with the Sass compiler and not our source code. Sorry y'all are having problems. @jugyhead I know you suggested a workaround here, if it's something not too bad to open a PR for on our end, we could review and see if there's something to help with. Otherwise, these kind of things need to be worked out with the compiler maintainers.

**Comment by sharomet** [comment]
Koala (Open Source) - official SASS compilers. The same mistake.
![img_2018 02 20_08h20m39s](https://user-images.githubusercontent.com/4848502/36409948-20a1951e-1617-11e8-8be4-94d5917bb111.png)

The problem is solved by changing the code. Thank you @jugyhead.

**Comment by hfittipaldi** [comment]
I'm using leafo/scssphp 0.6.7 and I'm getting the same error.

**Comment by hfittipaldi** [comment]
Well, according to bootstrap (https://getbootstrap.com/docs/4.0/getting-started/theming/):

I added this tom my custom scss file and it worked:

// Generate alert modifier classes
@each $color, $value in $theme-colors {
  .alert-#{$color} {
    @include alert-variant(theme-color-level($color, -10), theme-color-level($color, -9), theme-color-level($color, 6));
  }
}

**Comment by klebinhopk** [comment]
I had the same problem.
**My solution:** https://prnt.sc/qlyhob
