### ISSUE TITLE
class="form-inline" only prints one page in Firefox

### ISSUE THREAD

**Issue by bischofb** [twbs/bootstrap#25498]
Sending page to printer/pdf in Firefox only outputs one page when using firefox. It prints as expected in Chrome.

Anything within the form-inline tag doesn't print after the first page:

```html
<form class="form-inline">
blah blah blah for more than one page and it won't print
</form>
```

Here is my plunker:  https://plnkr.co/edit/k4J1lX

Now, if I add a d-block then it does print, but then it reverts the page to form-horizontal where the labels and inputs would be stacked instead of side by side (I don't demonstrate the stacking here, just the multi-page printing)

```html
<form class="form-inline d-block">
blah blah blah for more than one page
</form>
```

Here is the sample plunker:  https://plnkr.co/edit/A3jfaJ8CY6wfGYU0ozQj

**Comment by XhmikosR** [comment]
Does this still happen with latest Firefox?

**Comment by bischofb** [comment]
I downloaded the latest Firefox, 64.0, and both plunkers still have the same issues.

**Comment by ysds** [comment]
This is a browser bug. Unfortunately there is no general way to solve. There are [some workarounds](https://github.com/twbs/bootstrap/issues/26781#issuecomment-522019523), those are incompletely but may help for some cases.

Also please see:
https://bugzilla.mozilla.org/show_bug.cgi?id=939897

Sorry but closing this since we can't fix.
