### ISSUE TITLE
Bootstrap 4 Navbar collapse on iPhone - just opens and immediately closes

### ISSUE THREAD

**Issue by wingers999** [twbs/bootstrap#25514]
Hi

For some reason the Navbar collapse on iPhone screens just opens and immediately closes

Works fine on computer, even if browser resized so it is sm or xs small viewport - but on iPhone it misbehaves

See examples on my website here - [http://www.pcassistonline.co.uk/index_temp.html](url)

**Comment by patrickhlauke** [comment]
works for me. cannot reproduce the issue.

**Comment by wingers999** [comment]
Confused as to how it works for you, when I have tried above URL on more than one iPhone and clicking the three lines to open menu and it opens and then closes again straight away

Did you actually try it on an iPhone before just closing the issue?

**Comment by patrickhlauke** [comment]
> Did you actually try it on an iPhone before just closing the issue?

yes i did. iphone 7, safari and chrome. they work just as expected for me.

are you seeing the same behavior with the navbars on, say, getbootstrap.com?

**Comment by wingers999** [comment]
No I am not which is odd, as compared code word for word, and also as per that sample code copied a basic example navbar onto page and that doesn't work either - very odd

**Comment by wingers999** [comment]
May I ask what version of iOS you are using?

**Comment by patrickhlauke** [comment]
11.2.5, which is the latest. but more to the point: if you're experiencing weird behavior on your particular implementation of bootstrap, but not on the actual getbootstrap site/examples, then the problem is more than likely related to whatever you're doing (any additional scripts etc you're pulling in). unless you can provide a reduced test case (in something like jsbin, jsfiddle, codepen) using just bootstrap...i'm afraid there's not much we can do at this end. suggest perhaps referring to StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by wingers999** [comment]
http://www.pcassistonline.co.uk/index_temp.html contains navbar added to a bare bootstrap template - no additional scripts, nothing else at all - just simply a navbar

I had previous version of ios11 so not upgrade to 11.2.5 in case that fixes it
