### ISSUE TITLE
Octicons

### ISSUE THREAD

**Issue by dalu** [twbs/bootstrap#25527]
You suggest Octicons but how do you use octicons?
There are a bunch of js files and a essentially empty css file.

Stuff like this is making me angry. Instead of having a simple css file you suggest some hipster shit no one knows how to handle.

**Comment by patrickhlauke** [comment]
It's not really Bootstrap's job to explain how hipster shit outside of Bootstrap works. Suggest complaining directly to the maintainers of said hipster shit. https://github.com/primer/octicons

**Comment by cowbert** [comment]
@patrickhlauke well, since you guys dropped glyhpicons set, maybe you should have a more upfront disclaimer now saying that BS is no longer suitable for out-of-the-box css frameworking if requiring glyphs. (or "if you need OOB glyphs, do not upgrade/switch to BS4" instead of leaving it as a sidenote in migration notes).
