### ISSUE TITLE
Firefox css bug in the menu of the dashboard example

### ISSUE THREAD

**Issue by hi-rafa** [twbs/bootstrap#25684]
## Preconditions
- MacOs High Sierra 10.13.2
- Firefox Quantum 58.0.2 (64-bit)

## Bug Example
- http://getbootstrap.com/docs/4.0/examples/dashboard/
- https://codepen.io/rafaterangautier/details/yvERya

## Expected result
The first element (li) of the side menu should be "Dashboard".

## Actual result
The first element is being hidden under the main top navbar.

![screen shot 2018-02-22 at 3 19 50 pm](https://user-images.githubusercontent.com/3813277/36543870-569803d6-17e5-11e8-8164-219856659e0c.png)

![screen shot 2018-02-22 at 3 20 11 pm](https://user-images.githubusercontent.com/3813277/36543878-59799380-17e5-11e8-94f6-c0744b839f75.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by hi-rafa** [comment]
Hi @Johann-S,
I have included a new section in the issue where I added the links of the test case.

**Comment by weberlance** [comment]
FireFox 49.0.1 (win7 enterprise sp1) have the same view.
I think that problem is in "[sidebar-sticky](https://github.com/twbs/bootstrap/blob/5068b437a45ffb9ab7b74620d9edec600b1a28aa/docs/4.0/examples/dashboard/dashboard.css#L26-L27)" class. It looks like modificator of sidebar but we use it in context of sidebar.
And in this case it's better to use just relative position instead of sticky(I think that it's impossible to use correct .sidebar-sticky without .sidebar parent/ancestor). 

For IE11 there is another problem.
According to [_position.scss](https://github.com/twbs/bootstrap/blob/2dc9c76d75fcbbf3ff4181a09e0b0e0bae0caf20/scss/utilities/_position.scss#L31) IE doesn't understand @supports at all and properties top, z-index are missed too. And there is no fallback like "position: relative".

Also in dashboard.css there is no @supports rule and is the cause of errors in IE.

![ie11-sidebar-sticky](https://user-images.githubusercontent.com/25201835/36598844-8fd3e140-18be-11e8-8c54-2035e96f2470.jpg)
