### ISSUE TITLE
Validation Tooltip inside horizontal form not just below input when label multiline

### ISSUE THREAD

**Issue by Outlivier** [twbs/bootstrap#25694]
## Problem Description ##
When using validation tooltip whith horizontals forms, the tooltip position is not just below the input when label is display on multiple lines : 

![image](https://user-images.githubusercontent.com/3449244/36600781-7f202daa-18b3-11e8-894b-1c7b9b128275.png)

## Expected result ##

![image](https://user-images.githubusercontent.com/3449244/36601957-e4ea62c4-18b6-11e8-90f1-fd3eb57b1722.png)

## Reproduce ##

Source to reproduce the problem : [CodePen Source](https://codepen.io/Outlivier/pen/oEMPYY) (need a resolution at minimum of 1280*1024 to display the form horizontally)

## Question ##

I'm not sure if it's a bug or a design decision, because it's due to `top:100%` on invalid-tooltip class.

If it's a design decision, can i safely remove top 100% whithout side effects ?

**Comment by andresgalante** [comment]
Hi @Outlivier, thanks for reporting this. 

You are right, since the label stretches the col container, then the 100% becomes a problem on horizontal forms. This needs a fix.

**Comment by mdo** [comment]
We'll have to revisit this in v5 with some changes to our grid and form layout styles.

**Comment by mdo** [comment]
I know we slated this for a v5 redo, and I think our recent changes cover it, but I realized now that adding `.align-self-start` to the column containing the input will also help fix this as this is because of our flexbox styles. Closing since there's not much else we can do in v4 here that wouldn't be a breaking change, or something super specific.
