### ISSUE TITLE
Deeply nested columns do not always fit in row

### ISSUE THREAD

**Issue by dfalt** [twbs/bootstrap#25826]
I noticed an issue with horizontal overflow when creating a third level row/column structure. I have only tested a few permutations, but there seems to be a consistent issue with a third level row/column combination using `.col-11` and `.col-1`.

You can see an example of the issue [in this fiddle](http://jsfiddle.net/nbo0rnct/5/).

You can see the correct behavior (with `.col-10` and `.col-2`) [in this fiddle](http://jsfiddle.net/nbo0rnct/6/).

**Operating System**: macOS High Sierra 10.13.3
**Browser**: FireFox 58.0.2

**Comment by dfalt** [comment]
Didn't realize the preferred example sites were CodePen and JS Bin before I created the examples in JSFiddle. If it is a big issue, I can re-create them in one of the preferred site.

**Comment by MartijnCuppens** [comment]
@dfalt, It's not the fact that the columns are nested which causes this "issue", it's because the default `padding-left` and `padding-right` of columns combined are wider than the desired width.

I see two options how you could solve this:
- Add the `p-0` class to `.col-1` (example: https://codepen.io/MartijnCuppens/pen/MVwvoE, resize the screen below 360px to see the effect)
- Work with `no-gutters` (https://getbootstrap.com/docs/4.0/layout/grid/#no-gutters). This removes the padding from all columns.

**Comment by mdo** [comment]
Yup, closing per last comment.

**Comment by dfalt** [comment]
Ah, right... okay that makes sense. Thanks for the explanation.
