### ISSUE TITLE
Progress bar text for IE11 not displaying correctly

### ISSUE THREAD

**Issue by mdigi** [twbs/bootstrap#25872]
I'm trying to display some text inside a progress bar using bootstrap v4, but this doesn't seem to work with IE11.
[Here's a fiddle](https://jsfiddle.net/5dx2309e/4/)

Here is the result in Firefox 59 or Chrome 65:
![image](https://user-images.githubusercontent.com/5595405/37538356-c498d5f2-2926-11e8-90e2-934fc65a8041.png)

And here it is for IE11:
![image](https://user-images.githubusercontent.com/5595405/37538392-dfcdfa46-2926-11e8-927e-8146d75a50f1.png)

**Comment by wjvantilburg** [comment]
Hi mdigi,

You are telling the browser to position the element absolute, however, if you don't specify top,right.bottom,left properties IE-11 will set the values to "auto" resulting in this offset.

By giving the parent a relative position, we make sure the absolute child <b> tag cannot escape. 
By applying a top: 0 on the <b> tag we make sure there is no offset.

Take a look at the [updated fiddle](https://jsfiddle.net/5dx2309e/12/), I'm not sure if this can be fixed with B classes instead of applying the top manual though, but i hope this fixes your issue for the time being :)

~Wouter

**Comment by mdigi** [comment]
Yes, that works! Thank you.
