### ISSUE TITLE
isAndroid is not working properly.

### ISSUE THREAD

**Issue by humayuncep** [twbs/bootstrap#26183]
```js
var nua = navigator.userAgent;
var isAndroid = (nua.indexOf('Mozilla/5.0') > -1 && nua.indexOf('Android ') > -1 && nua.indexOf('AppleWebKit') > -1 && nua.indexOf('Chrome') === -1);
```

isAndroid is checking if it is Android as well as not Chrome. But I am facing a problem (the width is not enough) with Chrome for Android. It should not check whether it is Chrome or not.

Reference link: [Select menu](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/#select-menu)

**Comment by bkdotcom** [comment]
Referring to [this readme](https://github.com/twbs/bootstrap/blob/0b58340f141d5c93b84465cfbc6a32183dabbf63/docs/4.0/getting-started/browsers-devices.md#android-stock-browser)?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by humayuncep** [comment]
Thanks @bkdotcom and @Johann-S .

Bootstrap version: 4,
OS: Android,
Browser: Chrome, Firefox (I only check these two browsers. Don't know about other browsers)

Here is my [codepen demo](https://codepen.io/humayuncep/pen/oqyadx)

**Comment by Johann-S** [comment]
You should do : 

```js
if (isAndroid) {
  $('.form-control.proposed').css({ width: '100%' })
}

**Comment by humayuncep** [comment]
I want to detect not only the Android stock browser but also the other browsers like Chrome, Firefox, etc. That's why I proposed that.

BTW Thanks both of you.

**Comment by patrickhlauke** [comment]
that proposed code is there only to address a specific issue with Android/Browser. it's not intended to be a generic OS/browser detection script. Browser/OS sniffing is generally a bad outdated idea, the suggested code is only there as a last resort because Android/Browser messes up in ways that can't be nicely worked around. It's not the intention of Bootstrap to provide or suggest a generic sniffing code.

*If* there's an issue with Bootstrap in Android/Chrome, please file a specific issue about that, I'd say. There may be much nicer ways to address it in core CSS/JS without resorting to sniffing.
