### ISSUE TITLE
"no-gutters" function could work with responsive classes.

### ISSUE THREAD

**Issue by felicioandre** [twbs/bootstrap#26200]
On Bootstrap 4.x, maybe the class ".no-gutters" could work different with viewport classes, like "no-gutters-sm".

**Comment by AlexandreBeato** [comment]
It's so simple that is better to put it in the style file itself.

**Comment by mdo** [comment]
Skipping on more `.no-gutters` in favor of margin and padding utilities for now.

**Comment by guylepage3** [comment]
@mdo can you provide an example of how to layout a `container` with `no-gutters` on `xs`/`sm` and then gutters on `md` and above?

**Comment by trainoasis** [comment]
> @mdo can you provide an example of how to layout a `container` with `no-gutters` on `xs`/`sm` and then gutters on `md` and above?

I'm all for the no-gutters-<
You have to omit the` .no-gutters` class and use custom spacing utilities such as `.pl-<viewport>-<size>` and `.pr-<viewport>-<size>`, say `.pr-md-2`, but it's not very neat, since you have to be aware of the number of elements and which side to put padding to (depends on what you want, really). A quick, very basic example could be: 

```
<div class="container">
    <div class="row no-gutters">
        <div class="col-6 pr-md-2">
        </div>
       <div class="col-6 pl-md-2">
        </div>
    </div>
</div>
```

It does become quite a mess with complex layouts though, so +1 for .no-gutters with viewports ;)
