### ISSUE TITLE
Add out of date notice to v4.0.x docs

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#26225]
Now that v4.1.0 is here, we'll need to inform folks that the `docs/4.0/` page isn't the latest. I don't think a giant blue banner is the best or only solution, but I might pull that same approach from the alpha docs and use it here. Open to suggestions!

**Comment by Joyrex** [comment]
So are you suggesting maintaining a 4.0.0 _and_ a 4.1.0 document set? I would think (especially since 4.1.0 doesn't have any breaking changes as far as I can see) 4.1.0 would replace the existing 4.0.0 docs and likewise going forward until a more monumental change like 4.2 (although that kinda argues the point _for_ keeping 4.0.0 _and_ 4.1.0 docs, hehe).

**Comment by mdo** [comment]
> So are you suggesting maintaining a 4.0.0 and a 4.1.0 document set?

We're maintaining v4, but through the latest updates. v4.1 (and any 4.x release) won't have breaking changes. It's meant to ensure that new features, docs reorganizations, etc don't break URLs for folks.
