### ISSUE TITLE
4 Favicons

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#26268]
I see that there are 4 favicons in `bootstrap-4.1.0/assets/img/favicons/` that are **not** being used anywhere in Bootstrap.  These are the favicons:
![screenshot-favicons](https://user-images.githubusercontent.com/2222751/38629240-7b9602e8-3d81-11e8-8a06-e84cd08710e7.png)
Should they be removed?

**Comment by XhmikosR** [comment]
This is just a generated pack and adapted to our needs from https://realfavicongenerator.net/

I will regenerated the favicons since I saw I could improve a couple of things, but those are still generated. I guess they are there for compatibility with some IE versions.

Anyway, I don't think it hurts us having them for the time being.

Thanks for the report.

**Comment by LarryAzevedo** [comment]
I'm familiar with realfavicongenerator.net and how it may generate icons you may not use.  That's not the point.  The point is that there are images that Bootstrap is not using **at all** and we should be proactive and clean up after ourselves.

**Comment by XhmikosR** [comment]
You should report such issues on https://realfavicongenerator.net/. Reporting something here means nothing if you really want to fix something.

Link to this issue/or CC me on your issue upstream, and we can regenerate them if something changes.

**Comment by LarryAzevedo** [comment]
Ok so I'm very confused right now.  Are you saying that those images are not manually managed?

**Comment by XhmikosR** [comment]
It depends on what you by manually managed.

When I first added the favicons years ago, I didn't want to spend a lot of time. Thus I resulted in using a well-tested solution like RFG.

Now, while I have a way better knowledge on the matter, I still don't think this is important so that we play with different configs manually.

Thus, my suggestion above: if you think this is wrong, please make an upstream issue so that it's fixed there for us and for the whole community.

We can remove the favicons that seem to be unused (again, I can't say 100% none of the still supported IE versions doesn't use them, nor do I have the time to test it), but that beats the point of open-source.

I hope I explained it better now :)
