### ISSUE TITLE
Remove !important property from css of  Colors (utilities)

### ISSUE THREAD

**Issue by JasonGlez** [twbs/bootstrap#26513]
I'm unable to overwrite CSS styles because of all of them have an important attribute on their styles. 
https://getbootstrap.com/docs/4.1/utilities/colors/

**Comment by sts-ryan-holton** [comment]
@JasonGlez  Bootstrap tends to use `!important` on utility classes to ensure that they essentially always work. I don't think this is a massive problem and something that can be easily changed by using **SCSS/SASS** variables _(think this is how Bootstrap want you to do it)_

**Comment by dambrogia** [comment]
It would be much more flexible to reinstate utility classes with `!important` rather than apply `!important` to all of them by default. 

If you are using the CDN this makes it a nightmare to use other utility helpers like tailwind.

**Comment by robbieaverill** [comment]
It's not great for extensibility. I can't add a modifier class (e.g. `--inverted`) and flip the back and foreground colours without repeating the use of `!important`

**Comment by dietergeerts** [comment]
I currently have a situation with this too, and it would be great if someone as a very good solution for it:

```<parent class="bg-dark text-white"><child class="text-success">```

The classes on the parent are dynamic, meaning they will only be there when that element is set to 'active'.  The child must be green to show it's success state, but when the parent is set 'active', it becomes less readable. To solve this, I want the child to follow the parent text class instead in that case. Because of the `!important` on utilities, this doesn't work like I want.

I know that sometimes, you just want the other way around, having the child overwriting the parent, but that's not for this case. So what would be the most logical, good solution be for this? an extra class that targets children with a `text-` class to set the color to inherit?
