### ISSUE TITLE
Dropdown `data-boundary` option not working in scrollable column

### ISSUE THREAD

**Issue by jackmu95** [twbs/bootstrap#26512]
When a dropdown is placed in a scrollable column (`.col`) the `data-boundary` option has no effect.
As @rinick pointed out [here](https://github.com/bootstrap-vue/bootstrap-vue/issues/1819) this is due the columns `position: relative;` property.

Is this something Bootstrap or popper.js can/should fix or has the user to deal with it?

See: https://codepen.io/jackmu95/pen/XqBWwx

**Comment by andresgalante** [comment]
Hi @jackmu95, you are right, since the `.col` is position relative and the dropmenu is within the col, there is no way to increase the `z-index` to pop it out.

To be honest I don't see why the col is relative positioned. @mdo what am I missing?

**Comment by notaphplover** [comment]
First of all, sorry for my bad english :(.

Hi @jackmu95, I think the library is ok.

After analyzing your code, I´ve seen the following line:

`<div class="col-6 d-flex dropdown-container">...</div>`

I´m not an expert, but I think this is a bad practice. A col should be a col and no more. The framework is designed keeping this in mind. We use a div for a row and other div for the col due to the same reason.

There are few cases where col and other classes can be together.

I´ve forked your codepen with my implementation, i hope it could help you: 

[https://codepen.io/koro-sempai/pen/PerKLE](url).

This is just my opinion, i hope it does not sound arrogant :)

**Comment by jackmu95** [comment]
@notaphplover You are right that it's bad practice to style columns directly but I couldn't come up with better markup for my concrete situation where I faced the issue.

Here is a pen to show what I mean: https://codepen.io/jackmu95/pen/yjdzvy

The general question here is as @andresgalante mentioned why `.col` is position relative.

**Comment by notaphplover** [comment]
@jackmu95 Ah, ok. Then it was a misunderstood on my part. I´m not able to answer that question, but maybe this thread could be helpfull: #25254

**Comment by jackmu95** [comment]
@notaphplover Thanks for the investigation!

There is already a PR too (https://github.com/twbs/bootstrap/pull/25255) but it got stuck.
Maybe we could get it rolling again 👍

**Comment by notaphplover** [comment]
@jackmu95 You are welcome. Yeah, it would be wonderful ^_^.
