### ISSUE TITLE
Print view shows parentheses in accordion-heading

### ISSUE THREAD

**Issue by patriciomas** [twbs/bootstrap#26597]
In the print view, I'm getting parentheses inside the accordion-heading tag right after the title.
Does anyone know where this is coming from?

![parentheses in heading](https://user-images.githubusercontent.com/12055396/40563423-b48e39ac-6032-11e8-80a3-02d3f4da1d5e.png)

**Comment by XhmikosR** [comment]
@patrickhlauke: I know I've seen a tweet of yours. Maybe we should fix this here?

**Comment by XhmikosR** [comment]
@patriciomas: 
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by patrickhlauke** [comment]
it's not an issue in Bootstrap 4.x. this would only happen with Bootstrap 3.x. which is why i didn't pursue it further (but yes, if we did want to fix it in 3.x, we'd just need to target links that don't have a particular role applied to them). otherwise, the better solution for authors: don't use empty links for accordions and use `<button>` elements instead

**Comment by patrickhlauke** [comment]
https://twitter.com/patrick_h_lauke/status/997496773819228160

**Comment by XhmikosR** [comment]
Closing since v3 won't receive any fixes (well, unless there's an easy to review PR maybe).
