### ISSUE TITLE
Changing page size to A4 causes overflow

### ISSUE THREAD

**Issue by mikeday** [twbs/bootstrap#26598]
https://github.com/twbs/bootstrap/blob/c2b13b9c7851d62d3072989552a784e6c598580b/scss/_print.scss#L93

Specifying a large min-width for the body element (992px) makes the content overflow when the page size is reduced to A4; if Safari does not respect page size, could there be another way of doing this? Or perhaps restricting the min-width rules for Safari only?

When our customers use Bootstrap with Prince the output is often suboptimal and breaks in confusing ways due to the print style sheet, and fixing the page size would be a big help.

**Comment by SampsonCrowley** [comment]
yeah the min width here is breaking a lot of print styles that are relying on sizes to be accurate (eg. div set to height: 1.5in in print media) because the min-width is bigger than the set page size and that forces the browser to scale the page down. this is worse because for some reason `min-width: none` isn't a valid CSS value, and you have to remember to use `unset`

it at least needs to be brought down a bit (maybe 768px?) so people don't spend as much time as I just did trying to find why fixed unit print sizes were all being scaled down when actually printed

**Comment by SampsonCrowley** [comment]
for future users that end up here, this is what I'm using to make sure printing margins and page sizes are scaled to the printed medium:

```
@media print {
  ::first-letter{
    margin: 0;
    padding: 0;
  }
  html {
    &, body {
      margin: 0;
      background: #fff;
      background: transparent;
      padding-top: 0;
      padding-bottom: 0;
      font-size: 11px;
    }
  }
  .container {
    padding: 0 !important;
    margin:0 !important;
    width: 100% !important;
    max-width: none !important;
    min-width: unset !important;
  }

  @page {
    size: 8.5in 11in;
    margin: 0.25in;
  }
}
```

**Comment by mdo** [comment]
Closing as a stale won't fix I think—we've dropped the bulk of the print styles in v5 and I don't know how much we can change in v4 without it being considered a breaking change.

**Comment by SampsonCrowley** [comment]
@mdo would adding the small snippet above be acceptable?
