### ISSUE TITLE
docs service worker improvements

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#26600]
1. load workbox locally and not from Google's CDN
2. switch to `generateSW()` maybe, if we can find a way to fix the previous point; IIRC you can't configure the libs location with `generateSW()`
3. update mechanism?

/CC @Lyricalz  @gauntface

**Comment by XhmikosR** [comment]
@Lyricalz: it's way simpler :) After looking into it, we might as well use workbox-cli. The two things I want to do regardless of the way, is to

1. load the workbox files locally
2. specify the workbox files' location (maybe with `setConfig` or something)

The live deployment is currently broken because of #26594 after the docs refactoring.

**Comment by Lyricalz** [comment]
I remember using the cli option initially.

But I think I had to go with the node script way because the generated .md files aren't in the same route you would expect them to be, which was what the transform fixes [here](https://github.com/twbs/bootstrap/blob/v4-dev/build/workbox.js#L26-L40). The CLI is an easier way, but it won't let you apply transformations.

But checking the docs quickly, we can probably use [this](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#methods) to copy the libs we use locally, I think that would solve the problem?

**Comment by XhmikosR** [comment]
Yup, something like that.

If we can't make things work with either workbox-cli or `generateSW()`,I guess the only thing I'd change is to serve the workbox libraries ourselves :)

**Comment by gauntface** [comment]
you can serve them yourselves, some info here: https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn

Feel free to ping me or @jeffposnick if you still aren't finding things working the way you'd like.
