### ISSUE TITLE
<select> causes form elements to flicker on page load in Chrome

### ISSUE THREAD

**Issue by LeviHassel** [twbs/bootstrap#26609]
I'm using Bootstrap 4.1 in Chrome v66 on Windows 10.

When I load a page that has a `<select>`, I experience a quick flicker/flash of black outlines around all `.form-control` and `.btn` elements. If I remove the `<select>`, it doesn't happen. It also doesn't happen in Firefox v60.

![ezgif-3-74ae387739](https://user-images.githubusercontent.com/9669653/40601877-601a3312-621c-11e8-8bbf-68627e44829a.gif)

Here's a JS Bin to illustrate the issue: http://jsbin.com/vojetosiqi/edit?html,output. Simply click "Run with JS" to see the flicker.

I was able to stop the flickering by disabling transitions using this CSS:
```
.form-control, .btn {
    -webkit-transition: none;
    transition: none;
}
```

I'd be very happy if this was fixed so I could turn the great transitions back on. Thanks!

**Comment by notaphplover** [comment]
Hi @LeviHassel, is there any reason for inserting the scripts at the end of the body? 

At first, I thought that it was a CSS issue, but if you move the scripts to the head, the flickering should dissapear: http://jsbin.com/qusuholuvo/1/edit?html,output

I think that the javascript library does some kind of management task, and if you include the libraries at the bottom of the library, the library won´t be able to do something since the elements are already rendered.

Keeping this in mind, i did a second clone. I loaded the libraries between two containers.

http://jsbin.com/qiniranawa/1/edit?html,output

As you can see, the flickering is happening on the elements rendered before the library load process.

In conclussion, i think the library is Ok, just load it before the rendering of your elements (the head of the page could be a good place)

**Comment by LeviHassel** [comment]
Hey @notaphplover, thanks so much! That totally fixed it.

I was taught that scripts belonged at the end of the body, but after reading [this StackOverflow answer](https://stackoverflow.com/questions/436411/where-should-i-put-script-tags-in-html-markup?rq=1), I realize that's an antiquated recommendation.
