### ISSUE TITLE
Window scrolling is missing for a dialog (only a part of it visible)

### ISSUE THREAD

**Issue by vporton** [twbs/bootstrap#26670]
Put the HTML files from this archive [bug.tar.gz](https://github.com/twbs/bootstrap/files/2073625/bug.tar.gz) into a server.

Open `index.html`. Then you see that a dialog window overflowed the window size, but there is no scrolling to see the entire dialog.

Please fix the bug (and tell us about possible workaround).

**Comment by notaphplover** [comment]
Hi @vporton, I´ve seen the code and I´d like to help you just because :).

The cause of this behaviour is displaying two modals at the same time and then hiding one.

At this point, I will only refer to **Bootstrap 3.3.7** because you are pointing to that version of the library

After analyzing your code I focused on the javascript:

```
$(function () {
    $.ajax({
      url: 'update.html',
      type: 'GET',
      success: function(data) {
        $('#bigModal').modal('show')
        $('#bigModalContent').html(data);
        doPress();
      }
    });
});

function doPress() {
    $('#modalWait').modal('show');
    $.ajax({
      url: 'snippet.html',
      type: 'GET',
      success: function(data) {
        $('#modalWait').modal('hide');
        $('#bigModalContent').html(data);
      }
    });
}
```

As you can see, when calling doPress(), the modal with id 'modalWait' is shown, but the modal with id 'bigModalContent' was already shown. Then, the modal with id 'modalWait' is hidden.

At this point you will probably think something like "Ok, it´s true that showing two modals at the same time is a bit strange, but it should not break the modal". I totally think that, but unfortunatelly that is the problem. Let me explain you why:

The modal is able to scroll thanks to this rule in bootstrap.css:

```
.modal-open .modal {
    overflow-x: hidden;
    overflow-y: auto;
}
```
As you can see, it is required to have a parent (direct or not) with the class 'modal-open'.

¿Who is that parent?

That parent is the body element. In the line 967 of Bootstrap.js:

```
  Modal.prototype.show = function (_relatedTarget) {
    var that = this
    var e    = $.Event('show.bs.modal', { relatedTarget: _relatedTarget })

    this.$element.trigger(e)

    if (this.isShown || e.isDefaultPrevented()) return

    this.isShown = true

    this.checkScrollbar()
    this.setScrollbar()
    this.$body.addClass('modal-open')
    ...
```
And in line 1085:

```
  Modal.prototype.hideModal = function () {
    var that = this
    this.$element.hide()
    this.backdrop(function () {
      that.$body.removeClass('modal-open')
      that.resetAdjustments()
      that.resetScrollbar()
      that.$element.trigger('hidden.bs.modal')
    })
  }
```
So, what happens if you show two modals and then you hide one? The 'modal-open' class from the body element is removed and the other modal won´t be able to scroll :( :(.

**Workarounds:**

The main workaround is to display only one modal at a time. In your case, show the modal with the large content only after all the content is loaded. In that moment, hide the wait modal and then show the content modal.

This jsfidle shows your problem: 

http://jsfiddle.net/j65rp82L/8/

And the correct behavior would be:

http://jsfiddle.net/j65rp82L/10/

**What about Bootstrap 4?**

The behavior is exactly the same :(

Issue: http://jsfiddle.net/u62gsbhn/2/

Workaround: http://jsfiddle.net/u62gsbhn/3/

I hope it helps you :)

**Comment by Johann-S** [comment]
Sorry, but we cannot help with how-to or general troubleshooting issues here; only bug reports and feature requests. You'll want to ask around in the official Slack team or Stack Overflow. [See our readme for more details](https://github.com/twbs/bootstrap#community).
