### ISSUE TITLE
Placeholder is showing different alignment behavior in different browsers.

### ISSUE THREAD

**Issue by Harman02** [twbs/bootstrap#26725]
In chrome text is center aligned inside textbox as follows:
<img width="347" alt="capture12" src="https://user-images.githubusercontent.com/28998740/41641620-7aaaa83c-7483-11e8-9555-88fd61558970.PNG">

Whereas in Internet explorer, text seems to be bottom aligned as follows
<img width="232" alt="ieview" src="https://user-images.githubusercontent.com/28998740/41641625-7cb0fac8-7483-11e8-8d1e-5ea178065494.PNG">

Please see into this issue.

**Comment by mdo** [comment]
This is a universal font rendering problem, and one we simply cannot solve pixel perfect in every browser.

**Comment by Harman02** [comment]
It does not look good for me.Is it acceptable in I.E. from your side?

**Comment by varora1406** [comment]
I would agree with @Harman02 here for the part of that "this doesn't looks good".
@mdo , if you will try to understand, we are talking about" spacing of placeholder inside input field from bottom".

And it can be actually fixed easily, we have tried that.

Now, we are trying to contribute same into Bootstrap, so that it can be fixed over there instead of any local fix. And even it is more of acknowledgment part that if "line-height: normal" can fix it, then why it is not done in bootstrap itself?
It's not about blaming, but seeking knowledge for the outcomes in doing that in bootstrap. 🥇

**Comment by patrickhlauke** [comment]
> And it can be actually fixed easily, we have tried that

well, please show/submit the fixes then (showing how the fix has no adverse effects in different browser/OS combinations)
