### ISSUE TITLE
'Close Icon' utility in Bootstrap 4

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26749]
I'm just wondering whether we actually need this utility in the documentation? (https://getbootstrap.com/docs/4.1/utilities/close-icon/).

It seems a little redundant as it's mentioned in the intro text of this page that it can be used on **Modals** and **Alerts**, but you'll find on those components, in the examples, there's actually the `<button>` to close the modal:

> Use a generic close icon for dismissing content like modals and alerts.

**Comment by MicroDroid** [comment]
Maybe you want to make a closeable card.

**Comment by sts-ryan-holton** [comment]
@MicroDroid  True, but to my knowledge, I don't think cards come with the ability to be closed. It's something you'd have to build yourself, and in that situation, you'd probably end up implementing your own jQuery/Javascript, and whilst the close icon utility would still make a bit of sense, I'm not sure it needs to be in a section on it's own. We could simply add it to the cards component

**Comment by MicroDroid** [comment]
That's right, but if you use something like React/Vue/whatever you have to make your own JS anyways for even Modals because those frameworks don't like things that manipulate the DOM without their supervision.

Though I agree, it doesn't need a separate section/page

**Comment by MicroDroid** [comment]
I am not a Bootstrap developer but let me guess: Typical buttons don't need the text-shadow because generally there's enough contrast between the button background and the color of the text.

However for a `.close` button, the background is transparent and thus basically the parent's background, and thus this may cause color contrast issues in some cases. Here's an example of a dismissible but colored card **without `text-shadow`**:

![image](https://user-images.githubusercontent.com/8523135/41809779-fc7b7718-76fb-11e8-90b2-84121be357c7.png)

and here's **with:**

![image](https://user-images.githubusercontent.com/8523135/41809784-1220bbbe-76fc-11e8-8dfc-10e4544db4c8.png)

It's really just a very subtle effect to make it easier to see the button.

**Comment by asyncdesign** [comment]
Black isn't an appropriate font color for that blue background anyway. Why not use a normal button with a bright background?

**Comment by MicroDroid** [comment]
Using white there sounds bad for me, as it makes the button blend with the text. But anyways that's just me probably, and I only guessed the reason behind the text-shadow earlier, no that I am sure why.

**Comment by sts-ryan-holton** [comment]
@MicroDroid Fair comment, but typically you'd use the `.close` icon within a lighter element, like a modal with a white background, and with this it could look a bit blurred with the white background

**Comment by kogden** [comment]
I used it but since it's the only thing on that page it could probably be moved.

**Comment by andresgalante** [comment]
Hi @sts-ryan-holton I don't see any problem in keeping the close utility in the docs. As @MicroDroid not all implementations are done with jquery and an author would  want to use it in other places.

The shadow and colors are [variables](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L927-L932) that an author can customize.

**Comment by mdo** [comment]
No plans to remove the component—it's used in our modal headers and provides expected functionality (e.g., many native windows and dialogs include this). We can probably nix the shadow though if someone feels strongly about it, but I don't see value in leaving this open just to track that :).
