### ISSUE TITLE
Modal event 'shown.bs.modal' doesn't work without .fade class

### ISSUE THREAD

**Issue by poradz** [twbs/bootstrap#26762]
When .modal doesn't have .fade class, 'shown.bs.modal' event trigger before modal is visible.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by poradz** [comment]
Sorry, the bug wasnt's because of Bootstrap. Bug was caused because of initialization of modal before append, like this:
		
$('body').append(modalContainer);
modalContainer.modal(params);

It worked only with class .fade. I was suggested by old issue with class .fade
https://stackoverflow.com/questions/19662896/twitter-bootstrap-modal-event-not-fired-when-modal-is-shown

but fortunetally this bug is fixed in current version.

**Comment by saucyknave** [comment]
I hope I'm doing this right...

I'm using the latest Bootstrap version (5.3.3) and noticed this behavior.  See the following JS Bin to demonstrate:
https://jsbin.com/zebesacodi/edit?html,js,output

I'm on Windows 11 10.0.22631 using Chrome 129.0.6668.101, Edge 129.0.2792.89, and Firefox 131.0.3.

Is this intended behavior?  The Bootstrap Modal page (https://getbootstrap.com/docs/5.3/components/modal/) mentions "fade" 13 times, but doesn't ever describe any connection between the modal events ("shown.bs.modal", for example) and the fade effect.

**Comment by julien-deramond** [comment]
Hey @saucyknave 

For issues that have already been closed, feel free to open a new GitHub Discussion or issue if you believe it’s still relevant. This helps ensure we don’t overlook these messages or forget to respond. :)

Regarding your example, even if you do the following, you don't have the alert, that's the issue?

```js
$("#exampleModal2").on('shown.bs.modal',function(){
  alert("Goodbye");
});
```

**Comment by saucyknave** [comment]
> Hey @saucyknave
> 
> For issues that have already been closed, feel free to open a new GitHub Discussion or issue if you believe it’s still relevant. This helps ensure we don’t overlook these messages or forget to respond. :)
> 
> Regarding your example, even if you do the following, you don't have the alert, that's the issue?
> 
> ```js
> $("#exampleModal2").on('shown.bs.modal',function(){
>   alert("Goodbye");
> });
> ```

10-4 on the discussion issue; I don't think I noticed that it was closed.  My bad.  Plus I was eager to add my findings.  I'll do better next time.  

In any case, I get the alert in both cases; that's not the issue.  The problem is that without the "fade" class, the "order of pop-up" is reversed.  With "fade", the modal is displayed and THEN the alert is shown; without "fade", the alert is shown and THEN the modal is displayed.  The only difference is the existence of the "fade" class.  I sincerely apologize, I thought posting a link to a working example meant that you'd view the working example and understand the situation that way.  I should have done better explaining myself.

**Comment by julien-deramond** [comment]
No problem, I might have looked over it a bit too quickly. I get the issue now. I'll add it to my to-do list to check in depth whether it's intentionally implemented this way due to a technical constraint or if it's simply a bug. I agree with you; in the second example, it should be the other way around.
