### ISSUE TITLE
Documentation on https site is out of date

### ISSUE THREAD

**Issue by josegonzalez** [twbs/bootstrap#26773]
The current https site serves docs for the 4.0 version of bootstrap, while http defaults to 4.1.

**Comment by coliff** [comment]
Known issue - see #26441 for more details. It's caused by a service worker caching the docs.
If you're using Chrome - open Chrome Devtools, open Application tab and then **Application > Clear Storage**. Then tap the '**Clear site data**' button to wipe service worker storage etc. That'll fix it for you.

**Comment by josegonzalez** [comment]
Gotcha. Seems like there is hesitance to remove the service worker stuff - it's obviously broken to me, but probably provides some value to the project.

Closing since the original issue was closed.
