### ISSUE TITLE
Error: argument `$color` of `rgba($color, $alpha)` must be a color

### ISSUE THREAD

**Issue by franktopel** [twbs/bootstrap#26780]
Please be aware that introducing new stuff in something like `variables.scss` must be considered **breaking changes** as it will immediately break any customized Bootstrap on any project.

Also, the [issue](https://github.com/twbs/bootstrap/issues/23313) that is related to this is limited to collaborators now and clearly does **not offer a solution** for the problem presented.

Please elaborate in detail on the steps required to solve this problem, or, if that is the cause, how Bootstrap is meant to be customized (if that differs from how we did it with 3.x).

**Comment by mdo** [comment]
New variables are ideally only introduced in minor or major changes, except where they may solve a bug or broken behavior and end up in a patch. Adding variables is not inherently a breaking change though—we only consider removing them a breaking change.

I don't know what issue you're running into though since this is quite vague, but in the referenced issue, it's mentioned a few times that you must include the `functions.scss` file in the correct place.

**Comment by franktopel** [comment]
Some people also had that error by simply upgrading Bootstrap, even though they definitely include `functions.scss` before `variables.scss` which is what I'm running into as well. The issue I linked does not elaborate on that, at least not publicly.

**Comment by mischah** [comment]
>  […] include functions.scss before variables.scss […]

Thanks @franktopel for »documenting« this over here.  I have to update a customized Bootstrap (including overridden variables) from 4.x. to 5.x and didn’t get the point of this error message 🙈

**Comment by DrMueller** [comment]
@franktopel @mischah Sorry, I'm currently running in the same problem, but don't see the solution. Where would I need to include functions.scss?

**Comment by BarnacleJones** [comment]
@DrMueller its in the bootstrap.scss file. I fixed the issue in my solution by adding my custom site css before the functions import, (which was above the variables import by default)
