### ISSUE TITLE
Move tabs into Tabs component

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26934]
I think having the tabs functionality inside the current 'Navs' component is a little confusing, especially as they're listed further down the page.

What we should have, is an actual Tabs component as they do in fact act like tabs, rather than a navigation as outlined in the docs.

https://getbootstrap.com/docs/4.1/components/navs/#javascript-behavior

**Comment by XhmikosR** [comment]
I'm personally against this since tabs is a navigation component, not an individual component.

**Comment by mdo** [comment]
Closing as we wouldn't consider making a change like this until our next major version (v5). I'd consider it, but I don't think this makes anything clearer as it'd imply tab JS behavior can only be used with our tab style nav. Maybe v5 renames this to `nav.js` instead of `tab.js` to make the association clearer.
