### ISSUE TITLE
data-toggle collapse not triggered if id starts with a number

### ISSUE THREAD

**Issue by agriffard** [twbs/bootstrap#27000]
Since this commit in Bootstrap 4, on collapse.js: twbs/bootstrap@b1eb3fc#diff-6ef28a975ef633bb3b3318b9917df9e5, the collapsing will not be triggered if the id and data-toggle attribute are prefixed y a number.

**Comment by MartijnCuppens** [comment]
ID's can't start with a number, that's not valid. (see https://css-tricks.com/ids-cannot-start-with-a-number/) or this demo: https://codepen.io/anon/pen/jpZzvY?editors=1100#

It used to work because jQuery was used to do the querySelector.

**Comment by Johann-S** [comment]
Currently we use native method to query our elements (`querySelector` and `querySelectorAll`) so you must use valide id's

**Comment by ekoNHS** [comment]
Hi, I recommend adding this restriction to the docs, possibly near [Escaping selectors](https://getbootstrap.com/docs/4.1/getting-started/javascript/#escaping-selectors). While numeric ID's aren't valid in CSS, they *are* [valid in HTML5](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id):

> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

It can be a confusing issue to debug because it fails silently in the browser, with no console message, and it's a non-issue in jQuery (`$('#1')` works fine). Since Bootstrap uses jQuery for much of its core behaviour, it's an unexpected restriction.
