### ISSUE TITLE
Overriding $grid-gutter-width

### ISSUE THREAD

**Issue by seppebeelpez** [twbs/bootstrap#27038]
Tried to override the $grid-gutter-width: 30px !default; as pointed out in the documentation on following page: https://getbootstrap.com/docs/4.0/layout/grid/ with sass but didn't work.

Now instead of $grid-gutter-width i used $grid-gutter-width-base which works.

So is the documentation not up to date or am i doing it wrong? :)

**Comment by MartijnCuppens** [comment]
You're linking to the 4.0 version of the documentation, that's not the latest version. Maybe that's the cause? Apart from that, `$grid-gutter-width` should work. I don't know where your `$grid-gutter-width-base` variable is coming from, can't seem to find it anywhere in Bootstrap?

Are you loading your custom variables *before* you load the Bootstrap variables? Because the `!default` flag prevents variables to be overridden. (See https://getbootstrap.com/docs/4.0/getting-started/theming/#variable-defaults)

**Comment by seppebeelpez** [comment]
Indeed it was another version of the documentation, my bad.
Apparently when i installed it via NPM it installed the alpha version.
And the alpha version uses $grid-gutter-width-base instead of $grid-gutter-width.

Still thank you for replying so fast :)
