### ISSUE TITLE
Bootstrap blocks css var() property

### ISSUE THREAD

**Issue by anyotherway** [twbs/bootstrap#27059]
mod: do your own macos 10.13.6 jsbin, no time here, sorry
bootstrap is blocking standard css property color: var()
  BOOTSTRAP IS YOUR PRODUCT, NOT MINE, YOUR FYI

**Comment by wolfy1339** [comment]
Please take the time to make a live way to demonstrate your problem. 
Bootstrap does not block the usage of `var()` anywhere, you must not be doing something right.
Until, you show us a live example (on JSBin or similar) we cannot help you

**Comment by mdo** [comment]
Hey @anyotherway, I'm going to close this out because we don't know anything about the problem you're reporting and you're unwilling to provide an example or clarify. As such, we cannot help you. Your comment, including it's edited history, is also unnecessarily hostile. Please reconsider your approach next time you're asking for help.

**Comment by mdo** [comment]
Found your other issue btw—your example of a `skyblue` link color works as expected. https://codepen.io/anon/pen/PdYPMX

**Comment by anyotherway** [comment]
Dear prof., 2 box issues here -: disk fried on 4 month old Mac pro -: European hacker doesn’t like American blood, even attacking Applecare CR (heil mien trump). Thanks for fresh air confirmation, tc.

btw will use your pen on our color project, external evaluation, if you don’t mind
nominal primacy= 1(6) bluesky {{ 1+a(b+c)=(b(bc-c)+(c(cb-b)/((ab)’+(ac)’))’K-1 sortNcol
Css var is first (not only) coding error on disk fail… hmm ((Cupertino, security dissection)) ~o_0~
