### ISSUE TITLE
Consider updating design of badges component

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27096]
The current badges component with the contextual variants (https://getbootstrap.com/docs/4.1/components/badge/#contextual-variations) are considerably small with weird vertical positioning. I usually tend to overwrite the padding on these badges using my own styling as I feel they're a little too small. I've made a few minor tweaks to the current CSS and shall provide two screenshots with some code of what's different, what do you guys think?

**Before:**

![capture](https://user-images.githubusercontent.com/25177538/44312621-1d5fd400-a3f3-11e8-9292-7a17c48e1d0c.PNG)

**After:**

![capture](https://user-images.githubusercontent.com/25177538/44312634-41bbb080-a3f3-11e8-8afa-a00d5d2844f9.PNG)

_Code edits:_

```
.badge {
    padding: .4em .9em;
    /* line-height: 1; */
}
```

**Thoughts?**

**Comment by mdo** [comment]
Main issue here is Segoe UI sits far too low on the x-height, so the vertical alignment of the text within looks incorrect.

**Comment by sts-ryan-holton** [comment]
@mdo  Is there anything we can do about that?

**Comment by Joyrex** [comment]
On the documentation page, the font is being identified as "Apple System Bold", whereas the rest of the fonts are Segoe UI - is this correct (or is the tool I'm using mis-identifying the font)?
![image](https://user-images.githubusercontent.com/651646/44351427-72d5c880-a467-11e8-9daa-16811191d7ab.png)

**Comment by mdo** [comment]
Given the original issue is a question of updating the badge design, I'm going to close this out. We won't be making any changes to their appearance at this time.

Regarding the lower x-height, nothing we can do I'm afraid. Only option is changing the bottom padding, which we won't be doing because it'd need to be limited to Windows-only. FWIW we saw these issues in v3, too, even with Arial vs Helvetica.
