### ISSUE TITLE
Please ommit ".js" suffix in AMD names

### ISSUE THREAD

**Issue by vaxul** [twbs/bootstrap#27145]
Starting with v4.1.3 AMD was introduces into the JS files. Which I was really happy about.

But unfortunately you decided to us a naming like **./util.js**:
https://github.com/twbs/bootstrap/blob/b5ad6129a2d8039038a2998aa9d81f83005c7462/js/dist/modal.js#L3

Integrations with RequireJS [doesn't expect a ".js" suffix](https://requirejs.org/docs/api.html#jsfiles) and break.

> There may be times when you do want to reference a script directly and not conform to the "baseUrl + paths" rules for finding it. If a module ID has one of the following characteristics, the ID will not be passed through the "baseUrl + paths" configuration, and just be treated like a regular URL that is relative to the document:
> 
> - Ends in ".js".
> - Starts with a "/".
> - Contains an URL protocol, like "http:" or "https:".

Even most libraries don't use a suffix. jQuery for example.

It should be used a naming without ".js", like **./util**, which wouldn't break the common behavior.

**Comment by Johann-S** [comment]
Hi @vaxul, unfortunately we cannot remove the `.js` because we don't want to bundle our `Util` plugin in our other plugins, so we use local module.

Plus, it seems there are workarounds to handle that see: 
- https://github.com/requirejs/requirejs/issues/1560#issuecomment-231644928
- https://github.com/twbs/bootstrap/issues/25256

BTW we rely on `Rollup` to build our files, so if you think their is an issue on how they build UMD files, please tell us
