### ISSUE TITLE
.btn-link has border-color: transparent why?

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#27220]
I've looked for the reasoning behind adding border-color: transparent to the :hover and :focus states of .btn-link
https://github.com/twbs/bootstrap/blob/b7558830593711db0924bab6e9c44916865fd7c2/scss/_buttons.scss#L80-L92
but cannot find the reason for this. I came across this when trying to utilize some custom border styles on .btn-link and had the borders turn transparent on hover because of this.

Blame points to the change being introduced in https://github.com/twbs/bootstrap/pull/22951, but it isn't obvious to me the reasoning behind this rule. I propose removing it.

**Comment by tfevan** [comment]
Hi,
Thanks for asking. Read this, I think you'll get your answer. 
https://stackoverflow.com/questions/9612758/add-a-css-border-on-hover-without-moving-the-element

**Comment by mdo** [comment]
Because `.btn-link` is a modifier of `.btn`, you need both classes on the element. The `.btn-link` makes it transparent instead of removing the border outright to prevent any potential shifting (not likely these days with our box-sizing) and maintain some consistency.

I could go either way with it. I don’t know for sure if there are any situations where we absolutely need the border to stick around. We’d have to test more.

**Comment by MartijnCuppens** [comment]
`.btn` already sets `border-color: transparent;`, so indeed this can be removed. The same with `background-color: transparent;` which was added in #27003. See R14-R15: 

https://github.com/twbs/bootstrap/blob/ed48d9a4401ce0ad61b38a236e0a1c15bc3bb17b/scss/_buttons.scss#L7-L15

**Comment by andresgalante** [comment]
We kinda did the same here https://github.com/twbs/bootstrap/pull/27003
