### ISSUE TITLE
It is not possible to properly set $link-color variable in user-land config.

### ISSUE THREAD

**Issue by dilame** [twbs/bootstrap#27338]
In your `_variables.scss`
```scss
$link-color:                theme-color("primary") !default;
```
Your docs (https://getbootstrap.com/docs/4.1/getting-started/theming/#variable-defaults) says

> However, when overriding across Sass files, your overrides must come before you import Bootstrap’s Sass files.

But it is impossible to just change `$key` for `theme-color()` function, before import `_variables.scss`, because theme-color expects `$theme-colors` that declared in `_variables.scss`.
It turns out a vicious circle.
I know i can just use a variable instead of function call, but it is a bit confusing. Why you use `theme-color("primary")` instead of just `$primary`?

**Comment by MartijnCuppens** [comment]
The `theme-color` function is a bit redundant indeed. I will check to what extent we can simplify this.

**Comment by MartijnCuppens** [comment]
In my opinion we can deprecate the `theme-color`, `gray`, `color`. The `color` and `gray` functions are not used by Bootstrap and it's easy to remove the `theme-color` dependency.

@mdo, what do you think?

**Comment by retan** [comment]
Using $primary here is not an option either.
This code
```
$link-color:                $primary;
```
Throws an error: `Error: Undefined variable: "$primary".`
It's the same problem. If the custom _variables.scss is included before bootstrap, the SASS won't let you use undefined variable.

**Comment by dilame** [comment]
I define $primary in my own variables.scss, and it is not dirty. 
But define the whole `$theme-colors` map and include `functions` just to redefine `$link-color` is redundant.

**Comment by retan** [comment]
Of course typically you would define your own value for `$primary`. But the same problem occurs with many other variables.  Eg. I wanted to assign `$body-color: $gray-700` (instead the default `$gray-900`). To do that I need to declare that `$gray-700` variable in my file (though I want it to have te same value as the defaults).
I think at least the docs should clarify this.

**Comment by flexjoly** [comment]
I dont like to see these functions to disappear. Because then we need to make a separate variable for each color.
We just adopted the method of using the functions for colors and not the variables. We add colors to the maps, without making a separate var for it. 

We dont use the theme-color function.... I mapped the theme-colors with the colors. So we just use color() and gray().

I found this discussion because I wanted to ask if gray() could be changed so it would accept integers and strings both. Like: gray('100') and gray(100). At the moment gray(100) returns null :-( 

So please keep gray() and color(). Although if they are removed, I will add them via our own sass-functions.

Greetz, flexjoly
