### ISSUE TITLE
Range input validation feedback

### ISSUE THREAD

**Issue by Starzu** [twbs/bootstrap#27354]
Validation feedback for `form-control-range` is always hidden. The test case contains missing parts of CSS file. 

Tested on Windows 10 with Firefox 62.0.2 and Chrome 69.0.3497.100.
Test case: https://codepen.io/anon/pen/dgMmwY

**Comment by ysds** [comment]
`<input type="range">` elements don't have invalid state basically, because it has default value and browser fix the wrong value. It will be invalid only if [setCustomValidity()](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-cva-setcustomvalidity) is called, but a very special case.

Spesifications: [HTML Living Standard - The definition of '<input type="range">' in that specification.](https://html.spec.whatwg.org/multipage/input.html#range-state-(type%3Drange))

**Comment by mdo** [comment]
Closing per last comment.
