### ISSUE TITLE
Carousel Swipe

### ISSUE THREAD

**Issue by ben29** [twbs/bootstrap#27359]
Hi.

as requested here:
https://github.com/twbs/bootstrap/issues/23536
https://github.com/twbs/bootstrap/issues/17118

we ask for adding support for swipe on mobile.

but still not implemented.

please implement it.

thanks!

**Comment by slyk-style** [comment]
From a design point of view, I don't really see it warranted. The swipe feature is nice but is more of an interaction rather than a specific design trait/color etc. which bootstrap falls under. This would more likely fall under jquery. I personally would pitch it to them. An example of one that you can addon in the meantime to bootstrap is this link. It should work. Once again I personally feel bootstrap is very CSS based rather than being javascript even though there is a js file. http://kenwheeler.github.io/slick/

**Comment by Johann-S** [comment]
You can follow this PR https://github.com/twbs/bootstrap/pull/25776 which implement swipe left and swipe right
