### ISSUE TITLE
Modal not opening v4.1 after removing fade

### ISSUE THREAD

**Issue by far2005** [twbs/bootstrap#27402]
Hello

Modal works fine by default BUT if you remove fade from its class , the modal no longer opens

my version is 4.1 ( latest )

p.s: if i add bundle.js and bootstrap.min.js , it stops working

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

It's normal if you add `bootstrap.bundle.min.js` and `bootstrap.min.js` because you have to choose one of this file. 
`bootstrap.bundle.min.js` = Popper.js + Bootstrap
`bootstrap.min.js` = Only Bootstrap

**Comment by far2005** [comment]
I mean if i add `bootstrap.bundle.min.js` and `bootstrap.min.js` together my modal stops working IF i remove fade
I'll create a CodePen later

Thanks

**Comment by Johann-S** [comment]
That's normal because you have to choose **only** one of those files
