### ISSUE TITLE
Update v4.0 and v4.1 service workers on v4.2 deploy

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#27482]
Making a note of https://github.com/twbs/bootstrap/pull/26958#issuecomment-431232978.

**Comment by XhmikosR** [comment]
@mdo 

https://github.com/twbs/bootstrap/compare/v4.0.0-xmr-rm-sw
https://github.com/twbs/bootstrap/compare/v4.1.3-xmr-rm-sw

I suggest you don't make the changes directly to the gh-pages branch and push, instead make a PR so that we can review.

Theoretically you just need to switch to these branches and do:

```
bundle i
npm i
npm audit fix
npm run docs-github
```

But from a quick look I see other differences in docs like the newer Boostrap version callout, and the base paths. One thing is for sure, the dist files should stay the same.

**Comment by Ruffio** [comment]
If 4.2.1 has been shipped, howcome there are still two PRs in Inbox?

**Comment by XhmikosR** [comment]
They are not PRs, they are pending issues.

**Comment by Ruffio** [comment]
Shouldn't they be moved to 4.3? I don't guess they will be part of a release that has alredy been published?

**Comment by XhmikosR** [comment]
It's something I personally don't really care about as long as it's done.

**Comment by XhmikosR** [comment]
#27913 was merged.
