### ISSUE TITLE
Not able to scroll with touch support for carousels

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#27531]
Branch: `v4-dev`

It's not possible to scroll the page on touch devices if you start scrolling from a carousel. Tested on Chrome & FF on android and in mobile emulation mode in chrome on macOS (it's probably on every touch device). Caused by #25776.

cc @Johann-S

**Comment by Johann-S** [comment]
It seems that's because we add : `pointer-events: none` on the carousel 🤔 

/CC @patrickhlauke

**Comment by patrickhlauke** [comment]
nothing to do with `pointer-events: none;`. it's `touch-action: none;`. ideally, we'd have it set to `touch-action: pan-y` to allow the browser to handle vertical panning/scrolling, but Firefox in particular is far too fickle about what constitutes a horizontal-only movement and fires `pointercancel` as soon as you stray even just a few pixels up/down while swiping left/right, making it almost impossible to swipe horizontally there.

note that the scrolling is also impossible on devices that just support touch events (e.g. Safari/iOS), for different reasons (as the touch events are swallowed as they happen, and default browser action is prevented).

there's no clean way around this at the moment.

**Comment by XhmikosR** [comment]
Just a reminder, we can always go back to the hammer approach if we have issues we can't solve with the current implementation.

**Comment by Johann-S** [comment]
Unfortunately, using HammerJS won't fix that, because they do what we do 😟

**Comment by patrickhlauke** [comment]
the choice we have is basically: accept that this is what happens (as there's no good way around it, at least in touch-events scenario), or use the `touch-action: pan-y` approach but accept that currently Firefox is fickle in this regard and more often than not it won't allow you to swipe because if's too eager to `pointercancel` (but other, more popular browsers - well, Chrome... - are ok).

if we go for the former, it may be worth noting in the docs. then again, for the latter, a little note about Firefox's current behavior may also be worth it (i've flagged this with Mozilla folks at last week's TPAC, FWIW...and could file a bugzilla bug about it)

**Comment by XhmikosR** [comment]
I'm not sure how we should proceed with this after all. I guess we should aim for the best compatibility.
