### ISSUE TITLE
Trying to Open the same Modal inside a Modal won't work / Event swallowed?!

### ISSUE THREAD

**Issue by schmitch** [twbs/bootstrap#27799]
Hello, currently I'm trying to open a modal with the id `myModal` inside a already existing `myModal` via `data-toggle=modal`.
Basically it works, however (what I expected to happen) is that when clicking the link that the modal will `close` (This is not the Bug, I would expect that to happen).

However what is happening now, is that the Modal will close and then nothing will happend, no navigation to the new page, no content loading.

So Basically what I expected to happen:
1. Open myModal
2. Event `show.bs.modal` called (and after `shown.bs.modal`) 
3. Click Link in myModal with data-target myModal
4. Event `hide.bs.modal` called (and after `hidden.bs.modal`
5. Event `show.bs.modal` called (and after `shown.bs.modal`)

however step 5 will never happen, not as step 4, it will only call the hide.

i.e. I guess that either one of the following should happen:
- call the events and reopen the modal
- never close the modal, refresh the content
- just navigate the link (if it is a link)

however that it closes the modal and nothing happens is kinda unexpected.

**Comment by rafalp** [comment]
`data-toggle=modal` the keyword here is **toggle=modal**. It tells bootstrap to open or hide open modal. If you want a transition to new modal, you will need to implement it yourself I'm afraid.

**Comment by schmitch** [comment]
well maybe something like `data-open=modal` would be a great idea. especially since there is a `data-dismiss` attribute.

**Comment by dvmuccillo** [comment]
Bootstrap does not support multiple modals and discourages it as a poor behavior.

So i believe no step will be taken in the direction of supporting it.

You'll have to do as @rafalp says above and solve this on your own, maybe instead of intercepting a generic event for any modal you can handle the close of the old and then call the new modal, doing whatever you need/want between those two tasks.

Anymore on how-to is a thing for stackoverflow, do the question there and paste the link here so people can help you.
