### ISSUE TITLE
.table-dark is used in two conflicting contexts

### ISSUE THREAD

**Issue by linjialiang** [twbs/bootstrap#27879]
> version : `v4.1.3`

> Compiled `bootstrap.css` , The two conflict `.table-dark`

![default](https://user-images.githubusercontent.com/8848263/50205193-4c3a8680-03a2-11e9-8f6b-8e80116d0749.png)

**Comment by ysds** [comment]
I think he is right. The `.table-dark` class is used for two purposes - dark table and contextual class.

**Comment by linjialiang** [comment]
> ok，Recently began to try to read `v4` source code, feel very good

**Comment by davidjb** [comment]
Just for context, the effect of this is that table cell elements within a`.table-dark` row appear with a light gray background instead of using the dark gray background provided by the row.  The resultant bug is visible in the [Tables Contextual Classes](https://getbootstrap.com/docs/4.3/content/tables/#contextual-classes) example:

![image](https://user-images.githubusercontent.com/1002811/62608181-e67a1b00-b8ee-11e9-9730-37460e4f8bc4.png)


A slightly hacky workaround (at least for v4.3) is to include the following as an override in your build.  The mixin overrides the gray-colored cells and the hover rule ensures you don't get dark text on a dark background in a hover table.

```scss
@include table-row-variant("dark", $dark, $gray-600);

.table-hover tbody .table-dark:hover {
  color: $light;
}
```
