### ISSUE TITLE
Page overlaps header/footer when printing in chrome

### ISSUE THREAD

**Issue by shoe788** [twbs/bootstrap#27888]
Windows 10
Chrome 71.0.3578.98

[Image 1 depicting the problem](https://i.imgur.com/cvr3wu6.png)

[Image 2 depicting the problem](https://i.imgur.com/7BQAH9p.png)

Steps to reproduce.

1. Visit one of the examples on https://getbootstrap.com/docs/4.1/examples/
2. Ctrl-P to print
3. Set Paper size to 8.5x11, margins to "Default", and Headers and Footers to "On"
4. header/footer is visibly cut off from print page

**Comment by bakedbird** [comment]
The root of this issue is that inside the media print rule, the page size is explicitly set to A3, thus setting the default page margins the browser has for the A3 print preset.
Setting it to auto will solve your problem. 

I don't know why this has been set to A3 explicitly. If it has been done inadvertently, I am up to a quick PR.

**Comment by shoe788** [comment]
I changed page size to auto and it cleared that up. Thank you.

**Comment by SanjoyNath** [comment]
I faced the issue with Wikipedia prints. I hided the side bars in wiki and it solved the issue
