### ISSUE TITLE
tfoot after empty tbody shows no borders in firefox

### ISSUE THREAD

**Issue by josephzidell** [twbs/bootstrap#27949]
Windows 10 Home 64bit, Firefox 64.0

A `table-bordered` that has an empty `<tbody>` displays no borders in the `<tfoot>`.

This issue affects BS3 and 4.

https://jsfiddle.net/m9qc1be4/

![bs_borders_problem](https://user-images.githubusercontent.com/1812443/50540802-9ff95c80-0b66-11e9-89a8-1ff631baf3da.png)

**Comment by herbalite** [comment]
If you need the empty tbody tag to be in there in your example, you could use the following workaround

```
<tbody style="display:none"></tbody>
```

If that isn't good enough because of the `display: none`, you could use the following

```
    <style>
      tbody:after {
        content:''
      }
    </style>
```


Styling tables with CSS is quite a minefield because the way how thead, tbody, tfoot where defined in HTML 4 and changed in HTML 5. Add to it, for tables in general CSS is applied to the cells instead.

IMO Bootstrap's approach to tables is as generic as possible.  Table isses issues led to the Bootstrap grid as it is and in browsers it led to the CSS Grid.

**Comment by alecpl** [comment]
Old Mozilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=217769.

**Comment by mdo** [comment]
Dunno that it makes sense to even bother adding this to our browser bugs page if the bug is 16 years old lol. Thoughts on closing?

**Comment by josephzidell** [comment]
This is not a firefox bug per se. See [this fiddle](https://jsfiddle.net/4035qha7/) with BS styles removed, and borders show.

**Comment by mdo** [comment]
Right, this is because you're missing the `border-collapse: collapse` that triggers the bug. See https://jsfiddle.net/dkub5fLq/. This property is in Bootstrap's table styles, yes, but the problem with applying it is in Firefox, not in Bootstrap.

**Comment by josephzidell** [comment]
Fair enough 😄

**Comment by josephzidell** [comment]
As an aside, it's amazing how long these browser bugs lie around for... (smh)

**Comment by miketaylr** [comment]
> Dunno that it makes sense to even bother adding this to our browser bugs page if the bug is 16 years old lol. Thoughts on closing?

Old bugs get fixed, so it's worth tracking imho.

(we recently fixed https://bugzilla.mozilla.org/show_bug.cgi?id=218415, for example)

**Comment by lusd** [comment]
For 2024 bug is still reproducing:

quickfix only css: 
```
tbody:empty {
    display: none;
}
```

**Comment by Egor-Demeshko** [comment]
I have a big table with several **thead** and **tbody** elements. We use Bootstrap as well.
The problem is that the border is not rendered after the first pair of thead and tbody elements. And when the rule
```
table{ border-collapse: collapse}
```
is changed to **separate**, the borders that were rendered before become doubled, while the rest just appear.
Some Chromium-based browsers render all borders as expected.
