### ISSUE TITLE
@include box-shadow($dropdown-box-shadow); Not working

### ISSUE THREAD

**Issue by mkbctrl** [twbs/bootstrap#28001]
Hey community, 

just wanted to point out, that the 

`@include box-shadow($dropdown-box-shadow);`

is still in dropdowns, on line 33, and is obviously not working anymore (https://github.com/twbs/bootstrap/issues/12396). Which creates a question, should we have the variable `$dropdown-box-shadow` still there if by default dropdown menu doesn't have shadow?

Path to file:
`https://github.com/twbs/bootstrap/blob/v4-dev/scss/_dropdown.scss`

**Comment by florianlacreuse** [comment]
This issue was open and closed in 2014 and no longer seems relevant.

You need to toggle `.$enable-shadows` variable: https://github.com/twbs/bootstrap/blob/dc436427e9dcd74dded4cb79a0eb8ba16a1eb5d8/scss/_variables.scss#L111

See https://getbootstrap.com/docs/4.2/getting-started/theming/#sass-options

(assuming this is about bs4)

**Comment by mkbctrl** [comment]
Oh, my bad ( facepalm ). Thanks
