### ISSUE TITLE
carousel broke after upgrading to 4.2.1

### ISSUE THREAD

**Issue by suslikt** [twbs/bootstrap#28097]
After upgrading bootstrap 4.0.0 to 4.2.1

carousel was
https://codepen.io/kamenos96/pen/LQMxRe
carousel become
https://codepen.io/lumb/pen/jdNVgW

ps It would be nice to make a carousel for cards

**Comment by XhmikosR** [comment]
Please have a look at this branch https://github.com/twbs/bootstrap/tree/v4-dev-xmr-carousel-example, it might help you find the cause.

Generally this isn't supported, at least not yet. Any PRs welcome.

**Comment by frobinsonj** [comment]
You can add the below CSS to fix this:
`.carousel-item {
    margin-right: unset; 
}`

I've forked your codepen and added it to the bottom of the CSS: https://codepen.io/anon/pen/zedWrQ

**Comment by alejoHirsch** [comment]
Carousels wont slide since v4.1 anymore; not even in the examples

https://getbootstrap.com/docs/4.1/components/carousel/#with-controls
https://www.w3schools.com/bootstrap4/bootstrap_carousel.asp

Are the devs aware of this?

**Comment by MartijnCuppens** [comment]
@suslikt, the carousel didn't broke, your custom implementation did. Just remove `margin-right` from the `.carousel-item` and you'll be fine.

@alejoHirsch, you're question is unrelated to this issue and is caused by the reduced motion query: https://getbootstrap.com/docs/4.4/getting-started/accessibility/#reduced-motion

**Comment by alejoHirsch** [comment]
@MartijnCuppens Cheers! I was not aware of that query. I you don't tell me, I would have never found out!
