### ISSUE TITLE
Display Utility d-none should always be the dominant utility

### ISSUE THREAD

**Issue by fuhquan** [twbs/bootstrap#28113]
Hello everyone,

I'm currently working on changing a grid-based layout to a flex layout.
Unfortunatly the combination of d-flex and d-none result in d-none being blocked by d-flex.

Logically (at least for me) d-none should alsways be the dominant utility.

Would it have consequences within Bootstrap to change the order of display utlility initialisation to put d-none in last position to make sure it can successfully do it's job in any situation?

Best regards,
Sebastian

**Comment by fskreuz** [comment]
It can work both ways. Using `d-block` and `d-none` as examples:
- Element hidden initially with `d-none`, displayed with a dominant `d-block` (or something else).
- Element shown initially with `d-block`, hidden with a dominant `d-none` (like your case).

Both use cases are legit. There's no right or wrong but you can't have both be dominant (because physics don't allow it 😁 ). Why would you have `d-flex` and `d-none` together? Can't you remove `d-flex` when you put `d-none`?

**Comment by MartijnCuppens** [comment]
Utility classes shouldn't be combined with other conflicting utility classes. 
For your case, if you have control over your scss, you could switch the order of the display values:
https://github.com/twbs/bootstrap/blob/dfba588d0d1ea020634f1a8f2911c7222702b125/scss/_variables.scss#L1110
