### ISSUE TITLE
Events on .dropdown-toggle are only triggered once

### ISSUE THREAD

**Issue by grosser** [twbs/bootstrap#28121]
- Operating system and version (macOS)
- Browser and version (Chrome)
- reproduction with latest https://jsbin.com/pidipewuni/edit?html,js,output
 - workaround: use `mouseup`

```js
$(document).on('click', 'a', function(){
  alert("CLICK")
})
```

This should trigger on every click, but when it's on a .dropdown-toggle it only works once.
I suspect there is some code in bootstrap that unbinds all events by mistake.

**Comment by set-webmaster** [comment]
Has there been any investigation as to know why the event propagation is stopped? I'm trying to rely on the button click event to perform some actions too and it only works the first time the button is clicked, which is annoying as now I need to register event handlers for the `click` event and `show.bs.dropdown` and `hide.bs.dropdown` instead of only the first one.

**Comment by mattwebdev** [comment]
this still seems to be an issue. 
i cant for the life of me figure out why its a good idea to stop Propagation in this.

.on(Event$4.CLICK_DATA_API, Selector$4.FORM_CHILD, function(e) {
      e.stopPropagation();
});

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
