### ISSUE TITLE
Accordion: card-header border bottom hidden by card-body.

### ISSUE THREAD

**Issue by MargotPiva** [twbs/bootstrap#28134]
When an accordion element is open, the border bottom of the `card-header` element is hidden by the `card-body` element (in case of non-transparent background). See here the actual comportment : https://codepen.io/anon/pen/GzjNYL.
This behavior is due to this :

https://github.com/twbs/bootstrap/blob/e65dccfc95c04aba3de66d9880ad1e6852b659f2/scss/_card.scss#L286

This addition is due to those issues : #27124, #27108.
The bug reported here was the double `border-bottom` between the accordion elements when closed.

See the result when removing the rule over the `margin-bottom` : https://codepen.io/anon/pen/XOjNGz
Unfortunately the double `border-bottom` is back but the behavior of the `card-header` of an open element seems correct with a `border-bottom`.

**Comment by kampalex** [comment]
Using the dark colors the latest codepen example is very hard to exam.

The border-bottom is shown on transparent background. Due to the negative margin, the border-bottom of .card-header is covered by .card-body.
By applying 'z-index:1' onto .card-header styling, the border-bottom appears again.

**Comment by florianlacreuse** [comment]
OP already said that this issue only occur in cases with with non-transparent backgrounds because of the negative margin `.card-header`.

Using `z-index` seems to do the job but i'm not sure if this is a cleanest way to fix it. No clear-cut opinion about it, just wondering since I think this should be fixed in Bootstrap project.
