### ISSUE TITLE
Use disabled styling for the button part of the custom-file input

### ISSUE THREAD

**Issue by nathanmesser** [twbs/bootstrap#28176]
Disabled styling was added to the custom file input recently, but that didn't cover the button part of the component, so the button looks enabled when the input is disabled.

I think this could be achieved by adding something like:

  &::after {
    opacity: $btn-disabled-opacity;
    @include box-shadow(none);
  }

to the   
&:disabled {
    ~ .custom-control-label {

section of the _custom_forms.scss

**Comment by rcoops** [comment]
I came across this issue a few days ago. While it's good that disabled styling is there at all, it makes it look out-of-sync when one part of the control is clearly disabled and the other is seemingly unaffected, especially where other buttons on the page are also disabled.
If anything it's more important that the 'control' part of the control is shown as disabled. As a consequence a user might assume that the input is disabled only because it can't be typed into and that pressing the button will still allow a file to be chosen. When that doesn't work they'll think it's broken rather than being deliberately disabled for another reason.

Would like to see this sorted out as it seems a simple fix.
