### ISSUE TITLE
[v4.3] Including mixins multiple times shouldn't warn about RFS

### ISSUE THREAD

**Issue by lucagouty** [twbs/bootstrap#28235]
Hi everyone, I'm opening this issue after a quick talk with @MartijnCuppens here : https://github.com/twbs/rfs/pull/50#issuecomment-462481420

Before `4.3.0`, importing `~bootstrap/scss/mixins` multiple times was ok, but now we get a warning : 
```
WARNING: Watch out, RFS is included more than once!
```

Warning comes from [scss/vendor/_rfs.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/vendor/_rfs.scss#L197-L210) imported in [scss/_mixins.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_mixins.scss#L5-L6)

In my opinion bootstrap should not warn for this, especially as there's no warning of that kind elsewhere (so doing it only for `_mixins.scss` seems weird, as at the end it won't generate any duplicated `css`).

Feel free to read my [comment to rfs project](https://github.com/twbs/rfs/pull/50#issuecomment-462481420) for more details.

I'd be pleased to make a PR removing this warning, though as it's `vendor/_rfs` maybe we should do it in https://github.com/twbs/rfs instead.

Let me know, and have a good day guys 👋

**Comment by mdo** [comment]
@MartijnCuppens This is an update for RFS and not Bootstrap itself, correct? Or should we aim to develop RFS here and publish changes back to the main repo? (Let's figure that out and document it on our side for future reference.)

**Comment by XhmikosR** [comment]
I think it makes more sense to make any changes upstream first and then update it here.

**Comment by jcroll** [comment]
If including `rfs` multiple times is such a bad practice maybe it should be be decoupled from `mixins.scss`?

**Comment by MartijnCuppens** [comment]
This functionality was originally added because RFS broke if it was included more than once. That's fixed in the meanwhile but I build in this warning to warn people if RFS was included multiple times in their config because they're probably doing something wrong. In the scope of RFS this is quite a handy feature, but a lot of people will not know what RFS is when they include Bootstrap.

Guess I'm just going to remove it, it was more a nice-to-have feature but if it confuses more than it helps, it's moot.

I'll make PR's in both repos.
