### ISSUE TITLE
RFS: Fixed or fluid responsive font sizes?

### ISSUE THREAD

**Issue by jofran73** [twbs/bootstrap#28263]
Having tested the new RFS feature in 4.3, I am not sure how this is supposed to fit in the bootstrap way of handling responsive layout, which is designed around fixed breakpoints (xs,sm,md,lg,xl). These breakpoints are not required if I intend to design my page to be fluently scalable. Does this mean the breakpoint-approach might become deprecated in the near future?

If not, wouldn't it make sense to make RFS behave closer to the bootstrap paradigm? By this I mean that font-sizes (at least by option) don't scale fluently, but jump to the respective container-size (xs,sm,md,lg,xl). Because it looks weird if you slowly decrease viewport size and while the container keeps the same width for a while, font-size continually changes.

On the other hand, if I prefer the fluid change of font-size, I'd also want my container to resize fluently, to a maximum of 1200px.

It would be nice if there was a feature to control if I want to make use of breakpoints (for containers and fonts) or have fluid scaling (also both for containers and fonts).
Sorry if I completely misunderstood RFS.

**Comment by MartijnCuppens** [comment]
> Does this mean the breakpoint-approach might become deprecated in the near future?

No, there are no plans to move away from the breakpoints. 

> On the other hand, if I prefer the fluid change of font-size, I'd also want my container to resize fluently, to a maximum of 1200px.

We're probably going to do _more_ with containers in `v5`. Not sure yet what, but a some approaches are mentioned here: https://github.com/twbs/bootstrap/pull/25631 

The idea behind RFS was to provide a solution to rescale font sizes without having to worry about text becoming unreadable or losing it's relation to other text sizes (`h1` will always be bigger as `h2` ect..) The fluid rescaling turned out to be the easiest for font sizes because we don't have to generate media queries for all breakpoints.
