### ISSUE TITLE
Input height issues as a result of RFS

### ISSUE THREAD

**Issue by tracerx** [twbs/bootstrap#28301]
Windows 10 17763.316
Google Chrome 72.0.3626.109

Prior to 4.3, input heights were calculated using rem and px. With the changes for RFS (#23816 ), input-line-height is now multiplied by an em unit prior to calc which causes em and rem to be used in the calculation. This becomes an issue when you override the font-size of the input element while seeking a consistent height among elements. This could be by design but I thought it couldn't hurt to check.

I forgot to include a js bin of the issue:
https://jsbin.com/nozujuqefi/edit - 4.3.1 with issue
https://jsbin.com/kayoladuxe/1/edit - 4.2.1 without issue

**Comment by MartijnCuppens** [comment]
This is by design, you shouldn't override the font size with css only, this will misalign some form controls. What you should do is one of the following thing:
- Use the sizing modifiers: https://getbootstrap.com/docs/4.3/components/forms/#sizing or https://getbootstrap.com/docs/4.3/components/input-group/#sizing
- If you want to change the font size for the default form control, you can change the `$input-btn-font-size`: https://github.com/twbs/bootstrap/blob/ececf644f4886ef8bf2935fcc6b8f5a3dd7f37f1/scss/_variables.scss#L386
This will also change the font size of the buttons, handy when they are used in `.input-group`. You will need to rebuild the sass for this.
- You also use the `button-size` mixin to generate your own variant:
https://github.com/twbs/bootstrap/blob/ececf644f4886ef8bf2935fcc6b8f5a3dd7f37f1/scss/mixins/_buttons.scss#L101-L107
