### ISSUE TITLE
Links are not working in Popover

### ISSUE THREAD

**Issue by mjohal** [twbs/bootstrap#28379]
Upgraded to BS 4.3.1, and found that links in Popover are no working, they appear as simple text.

Bug reports must include:

- Operating system and version - (macOS)
- Browser and version (Chrome, Firefox, Safari)

**Comment by paul-turner-github** [comment]
Same issue, buttons no longer show in popovers.

Bug reports must include:

* Operating system and version - (Windows 10)
* Browser and version (Chrome, Firefox, IE11)

**Comment by patrickhlauke** [comment]
worth noting that, ideally, popovers should not be used to contain interactive elements (as it won't work properly for keyboard users) ...

**Comment by bardiharborow** [comment]
You need to pass `data-html="true"`. Keep in mind that as of 4.3.1, we now pass HTML through a sanitizer before echoing in back to the page (to fix CVE-2019-8331). See [the documentation](https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer) on how to configure this.

**Comment by mjohal** [comment]
Thanks, tried that already, still an issue.

Following is the popover init on page load:
$('[data-toggle="popover"]').popover();

Following is the test button:
<a href="javascript:void(0);" class="btn btn-secondary" id="testbtn"
tabindex="0" **data-html="true"** data-toggle="popover" data-trigger="focus" data-container="body" data-placement="bottom" 
data-content="<a href='javascript:void(0);' onclick=$('#docUpload').modal('show')> Upload</a>" 
role="button" data-original-title="" title=""> Actions</a>

Following is the screenshot of output with above code:

<img width="123" alt="popover-screenshot" src="https://user-images.githubusercontent.com/4934202/53644562-cb63fa80-3c2e-11e9-8e36-80abf1a46a39.png">

**Comment by bardiharborow** [comment]
`javascript:` URLs are denied by the sanitizer. `onlick` will also be stripped by default. See [sanitizer.js#L60](https://github.com/twbs/bootstrap/blob/v4.3.1/js/src/tools/sanitizer.js#L60) and [sanitizer.js#L24](https://github.com/twbs/bootstrap/blob/v4.3.1/js/src/tools/sanitizer.js#L24). See [this StackOverflow question](https://stackoverflow.com/a/1293130/1414639) for some reasons you shouldn't use `javascript:void(0);`. More generally, popovers are not a good engine for an action menu because they are not appropriately accessible by keyboard and screenreader users (it's an absolutely positioned div that's `aria-describedby`, the ARIA attribute for tooltipy things, not navigation).
