### ISSUE TITLE
Not a bug, not a feature: a will-change improvement on fixed navbars.

### ISSUE THREAD

**Issue by frederikhors** [twbs/bootstrap#28541]
I read about fixed navbars repaint problem (not just) on Chrome: https://medium.com/@kulor/one-small-css-hack-to-improve-scrolling-performance-c5238029e518.

Until Chrome 72 I can confirm this problem also using Bootstrap 4.3.1. But today with Chrome 73 I'm not seeing it anymore. And nothing changed in my site.

What do you think about?

**Comment by XhmikosR** [comment]
@twbs/css-review: thoughts?

**Comment by MartijnCuppens** [comment]
I've experimented with this in the past but it caused some blurry rendering in some browsers. Also, this is a hack to fix Chrome. I don't want and and up with a lot of browser hacks in a year or 2 because two years ago this was an issue in a browser.

I just tested this here and I couldn't reproduce the paint issues. The article was written in 2016 and browser have changed a lot in the meanwhile.

We'll pass on this, but thanks about caring about our performance, @frederikhors 😉
