### ISSUE TITLE
img-retina mixin deprecated

### ISSUE THREAD

**Issue by thedotmack** [twbs/bootstrap#28576]
"I see this is now deprecated but I use it frequently, is there some other method I should be using that you think is better, since you suggested it's removal?"

I asked this elsewhere to @MartijnCuppens and he suggested I move the question here. His answer over there was this:

"In most cases you'll probably be better of using <img> with srcset and position it under the component because this way the image is requested faster (browser doesn't need to wait for the css to be download, and the CSSOM to be processed)."

@MartijnCuppens are you suggesting people stop using the background-image property altogether? Also if you're suggesting that positioning an image underneath a component to serve as it's background image because it's faster, wouldn't the positioning CSS be written in the stylesheet also (it could be inline each time, but how far are we going here)? Or am I just not understanding this correctly?

I'm all for new methods but this seems excessive. Additionally I think I read that one of the issues that people had was that you needed to include image size with the mixin, but I've always ignored this as the image sizing parameters never really worked right. I just adjusted size afterwards. Maybe dropping those parameters might be a solution?

**Comment by thedotmack** [comment]
I see now you also spoke about `object-fit` but then wouldn't I have to `position: relative` all of the parent container's content and `z-index` it above the image in order to have it act like a background image?

**Comment by MartijnCuppens** [comment]
`object-fit` is probably the best solution for now but keep in mind this is not supported in IE. There are polyfills available though which sets the correct image as background image.

> @MartijnCuppens are you suggesting people stop using the background-image property altogether? 

No, in specific cases this could be the right solution. But just keep in mind getting control over these images can be a hell of a job. 

> ... Or am I just not understanding this correctly?

You're understanding this correctly, and this is what makes it so hard to control.


> Maybe dropping those parameters might be a solution?

We could, but this would introduce issues for the situations where those parameters are useful.

We ditched the `img-retina` mixin because there are several approaches on responsive images and it depends in which situation the image is used to provide a correct solution. I which I could have just helped you with: always use "approach X" to handle background images, but reality is a bit more complicated.

**Comment by thedotmack** [comment]
So for example are you suggesting this is done instead of using background images and media queries: 
`<img class="background-image" src="..." srcset="..., ... 2x">`
`.parent {
  position: relative;
  img.background-image {
    position: absolute;
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center top;
    z-index: 0;
  }
  > .content {
    z-index: 1;
  }
}
`
What exactly are the benefits to this in your opinion? I'm not arguing I'm just wondering.

**Comment by MartijnCuppens** [comment]
Yup, something like that 'll do. `<img>` and `<picture>` will give you more flexibility over which image you want to load. While with `img-retina`, you could only use 2 images, you have a lot more flexibility with just using images.
There's also a small performance benefit because images can be loaded while the `html` is parsed and not when the `css` file is parsed.

**Comment by thedotmack** [comment]
Great, thanks.
