### ISSUE TITLE
dropdown menu isn't not ontop of sticky div

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#28590]
There's an issue in the current release where the z-index values of dropdown menus and sticky-top items are round the wrong way.

The current behaviour makes any sticky divs appear ontop of active dropdown menus, which is not correct.

The following should be applied (I'm not sure how to create pull requests for BS, because it needing to be compiled, I didn' t just want to create a PR for the distributed CSS file).

```
.sticky-top {
    z-index:5;
}
```

Following on further from the docs: the dropdown and sticky values are round the wrong way, as the dropdown menus (wherever they appear) should always be ontop of anything that's sticky. In my scenario, my main navigation is a dropdown, but if there's a sticky div on the page, the navigation menu items are not seen because they appear BEHIND the sticky sidebar I have, which is terrible UX.

```
$zindex-dropdown:          1000 !default; ** MOVE DOWN
$zindex-sticky:            1020 !default; ** MOVE UP
$zindex-fixed:             1030 !default;
$zindex-modal-backdrop:    1040 !default;
$zindex-modal:             1050 !default;
$zindex-popover:           1060 !default;
$zindex-tooltip:           1070 !default;
```

**Comment by mdo** [comment]
@leecollings I get that you might be frustrated, but your comment over at https://github.com/twbs/bootstrap/issues/28569#issuecomment-478634970 is a little out of line. You say this is a bug, but as I mentioned in my comment on your last issue, the current stacking behavior is by design and hasn't changed in at least two years. If you need the order to change, you should change it as your project requires.
