### ISSUE TITLE
Add opaque backgrounds to accompany opaque text classes

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#28634]
It's nice to be able to quickly use opaque text classes for both light and dark scenarios:

```
<p class="text-black-50">.text-black-50</p>
<p class="text-white-50 bg-dark">.text-white-50</p>
```

However, I have always thought an even better need or feature would be to have opaque background classes for both, to quickly apply to overlay divs or even the navbar.

We have a `bg-dark` and `bg-white`, even a `bg-transparent` but nothing in between similar to the text classes.

```
<div class="p-3 mb-2 bg-black-50 text-white">.bg-dark</div>
<div class="p-3 mb-2 bg-white-50 text-dark">.bg-white</div>
```

A simple rgba background value should easily achieve these

```
.bg-black-50 {
    background-color:rgba(0,0,0,.5);
}
.bg-white-50 {
    background-color:rgba(255,255,255,.5);
}
```

**Comment by patrickhlauke** [comment]
so when you say "opaque" you're actually meaning "semi-transparent"?

**Comment by leecollings** [comment]
Yes! Sorry.. no idea what my brain was thinking there

**Comment by mdo** [comment]
Going to pass on this for now—for text, this is super helpful, but I rarely see folks needing to set something to exactly half opacity `background-color`.

**Comment by leecollings** [comment]
@mdo With all due respect, I disagree this is super helpful for text, it's more helpful for background.

The card overlay image for example, the text would be much nicer to be viewed as text-white, with the card-body div having a semi-opaque black background so the white text is much easier to read on top of the image.

But sure, it's your game!

**Comment by iainhallam** [comment]
@mdo I agree with @leecollings here - it's not uncommon to want to overlay text on a background in such a way as the image can still be seen, but the text is guaranteed to be readable. Most places I see this tend to use a semi-transparent background colour on the text element, so I'd support adding `-50` classes for the background colours to help with this use case.

In my case, I was looking for a semi-transparent primary background, not just dark or light, so it would be worth doing for all the defined colours, rather than just those two. Actually, I'd also quite like to see `-50` versions of the remaining text colours as well 😄

**Comment by mdo** [comment]
I think our utilities API is a good solution here until I see more requests for something like this. We're somewhat hesitant to add new utilities unless there's a fairly large community request.
