### ISSUE TITLE
'progress-bar-animated' not working on latest chrome version

### ISSUE THREAD

**Issue by DarkCompiled** [twbs/bootstrap#28709]
I'm running Windows 10, Chrome 74.0.3729.108 (64 bits).

It's easy to check by just opening the documentation page on the specified Chrome version:
https://getbootstrap.com/docs/4.3/components/progress#animated-stripes

Could you please check what is wrong?

**Comment by patrickhlauke** [comment]
you most likely have the reduced motion preference set in your windows, which browsers now expose in media queries and which suppress most animations in bootstrap? https://getbootstrap.com/docs/4.3/getting-started/accessibility/#reduced-motion
(Settings > Ease of Access > Display > Show animations in Windows ... make sure it's set to "on")

**Comment by DarkCompiled** [comment]
You are completely correct! 👍 
I had no idea that setting would influence pages displayed on Chrome!

**Comment by mdo** [comment]
Wondering if we can tell folks that in our docs somehow?

**Comment by myorangeca** [comment]
The option for this in bootstrap is set to true by default, it shouldn't be the case. I spent hours trying to find out why my animations stopped working, it was driving me nuts!  FYI, setting it to false turns back some animation not all, so there is a bug somewhere...

**Comment by patrickhlauke** [comment]
the problem is, oddly, on the side of the users...they've disabled animations in windows, and now that browsers take advantage of this system-wide preference, they're seeing the result of their setting. unexpectedly, but browsers (and bootstrap) are behaving correctly here.

(if we want to point fingers, it's probably Microsoft's fault for not being very upfront about what these settings do/the effect they can have beyond just suppressing Windows' own animations)

**Comment by patrickhlauke** [comment]
> Wondering if we can tell folks that in our docs somehow?

explaining this fully is very lengthy ... i've just splurged out a soon-to-be-published blog post on it. we can link to that, and/or cross post to bootstrap blog and reference it there?

**Comment by patrickhlauke** [comment]
xref https://twitter.com/patrick_h_lauke/status/1105256703430414336

**Comment by mdo** [comment]
Doesn’t need to be fully explained. I’m thinking something like, “Reduced motion blur is enabled on your device. As such, some transitions for this component have are disabled.” with a link to some sort of external documentation? Unsure what it would take to conditionally show this notice...

**Comment by patrickhlauke** [comment]
if just for the docs (aimed at developers, rather than end users of sites built with BS), i suppose some simply extra docs-specific CSS class that's `display:none` normally but `display:block` when the MQ evaluates to true would do the trick...

or you can get fancier with javascript-based `window.matchMedia` type logic to inject something...

**Comment by patrickhlauke** [comment]
the problem will be finding an appropriate "external documentation" - most articles/resources out there assume users have enabled this option knowingly. on windows in particular, it seems many (power) users have disabled windows animations for perf/aesthetic reasons, rather than to cater to their accessibility needs...which is causing problems now that browsers also react to this setting

**Comment by patrickhlauke** [comment]
randomly, here's the blog post (finally published) about the problem https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/

**Comment by peterblazejewicz** [comment]
This applies to other OS to, including Mac OS:
https://developers.google.com/web/updates/2019/03/prefers-reduced-motion

**Comment by patrickhlauke** [comment]
@peterblazejewicz yes, as explained in the blog post there. on windows it seems particularly common for users to have disabled motion accidentally though to reduce Windows' own animations, not realising this sets the preference globally (and it's apparent only now that browsers take a hint from it)
