### ISSUE TITLE
Replacing components for utilities

### ISSUE THREAD

**Issue by afuno** [twbs/bootstrap#28789]
Why don't you want to replace part of the components to the utilities? More specifically, delete the code of some components.

For example, Jumbotron, Card, Input group and others?

These components can be completely replaced by utilities that are already in Bootstrap. In fact, now there is a huge pile of copy-paste in the code.

I understand that some classes exist for JS. But they are not so many.

**Comment by afuno** [comment]
For example, this is Card:

```html
<div class="bg-white">
  <div class="h5 p-3">
    Header
  </div>

  <div class="p-3 pt-0">
    Content
  </div>
</div>
```

**Comment by XhmikosR** [comment]
That's already the plan. We have started dropping components in favor of utilities.

@twbs/css-review

**Comment by afuno** [comment]
@XhmikosR Super! I was glad to know about it.

**Comment by MartijnCuppens** [comment]
We 'll ditch the jumbotron & media in `v5`. I prefer to keep the `.card` component because if we want to cover all functionality for cards (like the word-wrapping or [stretched links](https://getbootstrap.com/docs/4.3/utilities/stretched-link/)), we'll end up with a component with lots of classes which might be hard to keep in sync in larger projects.
