### ISSUE TITLE
Wrong reboot value for webkit/safari button

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#28859]
reboot uses
```
[type=button], [type=reset], [type=submit], button {
    -webkit-appearance: button;
```
and should be:
```
[type=button], [type=reset], [type=submit], button {
    -webkit-appearance: none;
```
Edit: haven't managed really to completely disable this appeareance thing ¬¬
Regards

**Comment by tomasts248** [comment]
I ended up using this: input {
	-webkit-appearance: none;
}


[type=button], [type=reset], [type=submit], li[type="button"] {
-webkit-appearance: none !important;
opacity:1;
}

[type=button] {
    -webkit-appearance: none;
    -webkit-background-color:#FFF0CA !important;
	-webkit-font-family:'Minion Pro Regular';
	-webkit-color:#CB9E68;
	border:none;
	-webkit-opacity: 1;
}

**Comment by patrickhlauke** [comment]
the point of reboot is not to remove any browser specific styles, but to just set a few baselines so that bootstrap's own styles can be applied consistently and without any browser-specific overrides. as such, i'd say the current reboot styles are correct, unless you have more information about why you feel they're not.

**Comment by AMIT1122** [comment]
Hello Greetings...I have a very unique question..... I blocked all the cookies  SafariBrowser and does it resulted in clearing all my tabs in safari in private and non private mode so how can I get the open tabs back as I didn't found that in history as well.
