### ISSUE TITLE
btn-outline-light is not visible

### ISSUE THREAD

**Issue by vosidiy** [twbs/bootstrap#28861]
I cannot see btn-outline-light
It would be better if make text a bit darker
![2019-06-03_0200](https://user-images.githubusercontent.com/36692987/58789669-90fa5880-85a3-11e9-8500-ea43ae652229.png)

**Comment by florianlacreuse** [comment]
It's just because the background color is white, it looks better on a darker background.

You can override the default value if you want:

https://github.com/twbs/bootstrap/blob/5baad139023770250a0df11f1b77d73a8de53697/scss/_variables.scss#L75

I don't know if the Bootstrap team has planned to change the colors for the v5.

**Comment by mdo** [comment]
No plans to change the color—this one exists for darker backgrounds as mentioned.
