### ISSUE TITLE
Add column gap size as :root variable

### ISSUE THREAD

**Issue by boutzamat** [twbs/bootstrap#28936]
By adding column gap to :root variables, it will be much easier to create adaptable stylesheets that matches Bootstrap, no matter how it is customized.

**Comment by MartijnCuppens** [comment]
Bootstrap supports Internet Explorer which doesn't support custom properties. We currently can't do this.

**Comment by boutzamat** [comment]
But... you're already using root variables?
With that logic, we need to remove --primary, --secondary etc as well?

**Comment by MartijnCuppens** [comment]
That's an enhancement we have for those who want to use those custom properties. But this might be a bit confusing indeed since we don't mention anything about IE support: https://getbootstrap.com/docs/4.3/getting-started/theming/#css-variables

Probably need to change the documentation or drop them.

Thoughts, @twbs/css-review?

**Comment by mdo** [comment]
We don't support any other grid variables there (largely because media queries cannot use CSS custom properties at this time). We added them before realizing that, so they've stuck around. I think given that, we'll likely keep the list of variables really small here and remove those vars before adding new ones.
