### ISSUE TITLE
Bootstrap modal header accessability best practices: heading levels should only increase by one

### ISSUE THREAD

**Issue by bbarry** [twbs/bootstrap#29013]
All operating systems, all browsers. 

https://getbootstrap.com/docs/4.1/components/modal/

With the [Chrome extension Axe](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) installed, analyzing the above page or just about any page that happens to use an `<h5>` tag to host the modal title, Axe reports an issue for every open modal dialog: "Heading Levels should only increase by one"

The rule documentation describes the issue with html `<h#>` tags having semantic meaning that could be interpreted by various screen readers: https://dequeuniversity.com/rules/axe/3.3/heading-order

Is there a semantic reason for using an `<h5>` tag or would it be reasonable to use `<div class="h5">` in the documentation on this page?

**Comment by patrickhlauke** [comment]
skipping heading levels in itself isn't a failure, and the main reason an actual `<h5>` is used here is to provide some form of real-world markup example for the modal (as devs will tend to copy/paste this stuff...otherwise you'd end up with authors starting to litter `<div class="h5">` constructs in their actual sites.

in an ideal world, the live examples would be completely isolated from the outer structure of the documentation page, but unfortunately it's not something that can be semantically expressed in html.

**Comment by patrickhlauke** [comment]
some of this was already discussed and debated over here. while the current approach isn't perfect, it's the least bad option i'd say.
