### ISSUE TITLE
box-sizing redundant property

### ISSUE THREAD

**Issue by ashfahan** [twbs/bootstrap#29057]
Do we still need to set box-sizing: border-box; on input when we already have box-sizing: border-box; on universal selector
https://github.com/twbs/bootstrap/blob/78c9c8bdd4cad5e6d1fc349d45b7503bad84a19b/scss/_reboot.scss#L408-L412

https://github.com/twbs/bootstrap/blob/78c9c8bdd4cad5e6d1fc349d45b7503bad84a19b/scss/_reboot.scss#L14-L18

**Comment by herbalite** [comment]
That seems to be a IE10 workaround. Bootstrap 4 supports that browser.

https://getbootstrap.com/docs/4.3/migration/#browser-support

Although it's quite a while since I ran into this issue, I remember that there were issues with box-sizing behaving different on different browsers and messing up things,
