### ISSUE TITLE
Carousel slides overlapping and sometimes not animating after Chrome 75 update

### ISSUE THREAD

**Issue by MarkFeltwell** [twbs/bootstrap#29072]
After a Chrome update the standard carousel markup doesn't seem to be producing the correct slide results. Works fine in other browsers both desktop and mobile versions.

[https://srscarpentry.co.uk/](https://srscarpentry.co.uk/) is one example where the carousels do not slide as they do in other browsers. They seem to overlap and sometimes do not even animate at all.

I used to host bootstrap files myself but in an attempt to solve the issue I've used the CND, but with no fix.

Any ideas to whats happening are greatly appreciated. Thanks

**Comment by acshef** [comment]
Did you review the bug report template before submitting this ticket? (Emphasis mine):

> Before opening:
> 
> - [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
> - __*[Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML*__ to avoid common problems
> - Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)
> 
> Bug reports must include:
> 
> - __*Operating system and version*__ (Windows, macOS, Android, iOS, Win10 Mobile)
> - __*Browser and version*__ (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
> - __*[Reduced test case](https://css-tricks.com/reduced-test-cases/)*__ and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by MarkFeltwell** [comment]
As they do on the Bootstrap website on my Mac OS 10.14.5, Chrome 75.0.3770.100 but not on websites that I've built in wordpress since this last big Chrome update

I know I'm not alone in this either

**Comment by XhmikosR** [comment]
@twbs/js-review can anyone reproduce this? I tried this on Windows and works as expected.

**Comment by patrickhlauke** [comment]
@MarkFeltwell as the carousels on https://getbootstrap.com/docs/4.3/components/carousel/ work correctly for you, but you're saying the ones you implement aren't, it sounds like the issue is likely in your implementation/the way you use them/possibly any additional code you have on your sites.

I've had a look at https://srscarpentry.co.uk/ and the carousel with the "Current project"/"Bungalow renovation" /etc, and I can indeed see that it behaves oddly and erratically. However, can't really dive in to see where the problem might be. Unless you can boil it down into a clean, isolated test case example that shows the problem in isolation, I'd suggest checking first on StackOverflow or Slack (see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker) for implementation advice.
