### ISSUE TITLE
v3.4.1 hidden-* utilities not working at specific widths

### ISSUE THREAD

**Issue by KayakinKoder** [twbs/bootstrap#29154]
- Operating system and version
Windows 10

- Browser and version
Chrome 75, Firefox 68

- Test Case
https://codepen.io/cpj22/pen/WVoKON

The following should be hidden at all device widths. At 767px, 991px, and 1199px widths, it becomes visible.

```
<div class="row hidden-xs hidden-sm hidden-md hidden-lg">
    <div class="col-xs-12">
        this should always be hidden on all device widths!
    </div>
</div>
```

I hope I'm missing something!

**Comment by mdo** [comment]
v3 is no longer actively supported, but couple notes:

- Use `.hidden` instead of all those classes.
- Nix the `.row` and `.col-xs-12` unless you need grid classes, it's the same as a regular ol' `<div>`.
- Since v4, we use fractional pixels to ensure media queries don't cause issues like the one you're seeing.
