### ISSUE TITLE
Revisit composer.json

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29273]
I don't use it myself so I'm not sure if what we have now in v4-dev and master branches is OK.

https://github.com/twbs/bootstrap/blob/9519b9e055f886858dec3e80b9938ef9414de41f/composer.json#L31

If anyone has experience with composer please chime in or even propose a PR.

docs: https://getcomposer.org/doc/articles/aliases.md#branch-alias

**Comment by pavarnos** [comment]
probably OK to delete the whole "extra" section.

**Comment by andreasschroth** [comment]
You can delete the `extra` section from your `composer.json` file.

**Comment by TomasVotruba** [comment]
I had similar problems until it got automated

**Comment by perk11** [comment]
This section is unnecessary. Composer is using tags from github, it doesn't need version information in composer.json.

**Comment by hparadiz** [comment]
You could add scripts like unit tests and linters and the source code URL.
```json
    "scripts": {
        "fix-code": "php-cs-fixer fix",
        "test": "vendor/bin/phpunit --coverage-clover build/logs/clover.xml"
    },
    "support": {
        "issues": "https://github.com/twbs/bootstrap/issues",
        "source": "https://github.com/twbs/bootstrap/"
    }
```

Also a link to the readme.md. See: https://getcomposer.org/doc/04-schema.md#readme

But to be honest it doesn't make sense to even have a composer file cause the best practice in the PHP world is to not expose vendor in your public folder.

Most modern PHP projects will have this directory structure:

Project folder
- src < PHP code
- public < this is the site root, assets go here and a single index.php to setup routing
- tests < unit testing
- vendor < composer dependencies


So in a proper modern PHP project the bootstrap folder would be in `project/vendor/twbs/bootstrap/dist/` which is not accessible publicly.

You can view an example project here:
https://github.com/thephpleague/skeleton

To use bootstrap with composer it's better to just make a directory link from `public/js/bootstrap` to `vendor/twbs/bootstrap/dist` making the files in the vendor directory accessible.

Your other option is a custom URL rewrite like so (for Nginx):
```nginx
location ^~ /bootstrap {
    alias /usr/share/nginx/html/vendor/twbs/bootstrap/dist;
}
```

In this example the `dist` folder would become accessible as `/bootstrap`.

Since the entire source code folder for bootstrap is a lot of files most people don't need it doesn't make much sense to clone the entire repo into the vendor directory and this is why most people will simply copy only the files they need into their projects.

**Comment by XhmikosR** [comment]
#29420
