### ISSUE TITLE
Provide `bootstrap‑reboot` as a separate package (e.g. `@bootstrap/reboot`)

### ISSUE THREAD

**Issue by ExE-Boss** [twbs/bootstrap#29311]
Currently, projects that only use `bootstrap‑reboot` still get security warnings about security issues present in the Bootstrap JavaScript code, it’s also a whole bunch of code that has to be downloaded into `node_modules` that is completely unused and doesn’t make it to [the final bundle](https://exe-boss.tech/smwc-style/exe-boss.min.css).

Using just `@bootstrap/reboot` would also greatly simplify the [`postcss‑import`](https://github.com/postcss/postcss-import) configuration and ensure that it doesn’t break by bootstrap changing where `bootstrap-reboot.min.css` is located.

**Comment by Johann-S** [comment]
Hi @ExE-Boss,

AFAIK we don't have any open security issues 😉 

For your other points: /CC @twbs/css-review @twbs/js-review

**Comment by XhmikosR** [comment]
I agree at some point we should do this, but last time we had a PR about this kind of change (using lerna) it changed quite a few things and we didn't feel like it was the right solution.

**Comment by ExE-Boss** [comment]
I meant, when security vulnerability is discovered, GitHub and npm send security vulnerability alerts about it.

A CSS‑only package can’t really have classical security vulnerabilities due to what CSS is (a declarative stylesheet language, which only controls how the web page is displayed on the screen).

**Comment by MartijnCuppens** [comment]
> ... and then include it via npm

We currently don't depend on npm yet, that's why RFS is copied in a vendor folder for example. Depending on npm will break composer, NuGet and repo installs.

But yeah, I like the idea of splitting it up, we just got to find out how.

**Comment by ExE-Boss** [comment]
You could also just keep it as is, and just create a second package by copying `bootstrap‑reboot.css` from `dist` into a new package as `index.css`.

**Comment by XhmikosR** [comment]
The only way when we last discussed this was lerna.

Just one thing to keep in mind, we should keep things simple, whatever we decide.

**Comment by julian-hecker** [comment]
I think it would be nice to have separate packages for each of bootstrap’s `dist` files, including utilities, reboot, and grid, assuming they don’t already exist.

**Comment by mdo** [comment]
Would still love to see this happen—adding the `help wanted` label to see if someone wants to take a pass and then bring it over to the `@twbs` org.

As a first pass, we could consider making `twbs/reboot` a mirror of the upstream `_reboot.scss` file located here in Bootstrap proper. No docs, no expansive build system—just the stylesheet and minimum support around it. Could even disable Issues on the repo if necessary.

**Comment by XhmikosR** [comment]
IMHO either we do it properly or not, otherwise it will be an extra maintenance burden.

Node.js 15.x, which will be the next 16 LTS version is using npm 7.x. I don't know if they'll backport npm 7.x to 14.x (my guess is probably not) has added support for workspaces. yarn does already support this for quite some time.

So, the solution seems to still be lerna or another npm package that does the same job. Regardless, that would mean we'd still need to refactor our source files into packages, which will be a breaking change.

As an intermediate solution, sure, we could move reboot to a separate package. But then people will wonder why don't we do the same with JS and other CSS files.

That being said, it shouldn't be a lot of work since reboot does not change frequently. We'd still need the same upstream Stylelint and some kind of CI.

**Comment by stormwild** [comment]
@mdo Possible implementation: [Reboot](https://github.com/stormwild/reboot), [Reboot npm package](https://www.npmjs.com/package/@stormwild/reboot)

**Comment by mdo** [comment]
Closing as stale.

**Comment by sean-au** [comment]
Any progress on this? Often reboot is the main part of bootstrap which I need to fully use in a project
