### ISSUE TITLE
Tweak /utilities/borders/#border-radius

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29343]
https://twbs-bootstrap.netlify.com/docs/4.3/utilities/borders/#border-radius

This doesn't look so good, and also on mobile the images don't have any vertical margins. Could be improved IMO.

**Comment by SeasonLeee** [comment]
Hi,😊 I also discover this issue in the live v4.3 doc, when the viewpoint is less than 1132px
![image](https://user-images.githubusercontent.com/13610283/64067290-f91b1200-cc58-11e9-9b7c-31ae8e49041f.png)

And I think we can add `margin: .25rem` to fix this issue just like it's used on the border example above
![image](https://user-images.githubusercontent.com/13610283/64067324-6e86e280-cc59-11e9-92a8-943a7a656205.png)

although I know that this class name `bd-placeholder-img` is widely use in the project, but I have check the other usage and most of them are only use single one, so I think adding this margin won't affect other usage. 

What do you think?😁

**Comment by XhmikosR** [comment]
The proper solution would be to not touch `bd-placeholder-img` but use our utils in this specific case instead.

I'm not sure about v4, it can probably stay as is unless the patch can be cherry picked cleanly :)

**Comment by XhmikosR** [comment]
Also, the brand page wraps now in [master](https://twbs-bootstrap.netlify.com/docs/4.3/about/brand/#name), we should probably fix this too. Generally there might be more places with such issues due to the master doc-related changes.

**Comment by SeasonLeee** [comment]
> The proper solution would be to not touch `bd-placeholder-img` but use our utils in this specific case instead.

Thanks for reply! And yeah, you absolutely are right and darn it! I totally forgot that in bootstrap we have those space utilities! I'm sorry to make that awful and thoughtless "change one and affect everywhere" suggestion! SORRY!!!😫

_By the way, I used to use that helper class a lot when I am in charge of design. But lately the task assign to me is to translate other people's design and that design is totally messy, meaning each page or screen's element have different space or width, which is so.... then I have no choice but write another set of space helper class... I guess that's why I forget our mighty bootstrap have this feature..._

Anyway... I guess we can use bootstrap's `.m-1` class in here to fix this issue then, right?😊

> 
> I'm not sure about v4, it can probably stay as is unless the patch can be cherry picked cleanly :)

Ugh... sorry I don't quite understand what that "the patch can be cherry picked cleanly" means.

Does it means someone has fixed it already? But commit on another branch? 

I haven't use cherry pick before sorry... now, I'm on my way to google it...

**Comment by SeasonLeee** [comment]
> Also, the brand page wraps now in [master](https://twbs-bootstrap.netlify.com/docs/4.3/about/brand/#name), we should probably fix this too. Generally there might be more places with such issues due to the master doc-related changes.

Do you mean the brand section under about navigation also have the same issue?

But I don't see anything wrong here...
the online working doc:
![image](https://user-images.githubusercontent.com/13610283/64074170-9bc7a500-ccda-11e9-92ac-0fe4c6da081f.png)

the link you in your comment:
![image](https://user-images.githubusercontent.com/13610283/64074179-b3069280-ccda-11e9-91ba-02509883d412.png)
