### ISSUE TITLE
collapse not expanding in 4.1.2 and later

### ISSUE THREAD

**Issue by schnitty** [twbs/bootstrap#29390]
Bug reports must include:

- Windows 10
- Chrome

In version 4.1.2 and above when I have multiple collapse components clicking on the button does not expand the collapsed element.

Same html layout works in 4.1.1

codepen not working in 4.3.1
https://codepen.io/schnitty/pen/aboqQQg

codepen working in 4.1.1
https://codepen.io/schnitty/pen/VwZQqZj

Looks like it might be a problem with the javascript library

**Comment by Johann-S** [comment]
Hi @schnitty,

That's because we use native methods to query our elements (`querySelector`/`querySelectorAll`) and your ids aren't valid. You can try to run `document.querySelector('#24A70BC1-C8AB-4D12-AF5D-D1471DC8AA7A-details')` and you'll get that error:

![image](https://user-images.githubusercontent.com/1689750/64520235-fcb43600-d2f5-11e9-872c-6f01fdd5eefa.png)

More information here:
 - https://getbootstrap.com/docs/4.3/getting-started/javascript/#selectors
 - https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier
