### ISSUE TITLE
Set overflow:hidden on a .card

### ISSUE THREAD

**Issue by korthjp17** [twbs/bootstrap#29643]
When a card has a fairly large border radius, the background color can be seen outside of the card. Adding `overflow:hidden` to a card will fix this.

Here is an example with just changing the border radius of a card to 2rem instead of 0.25rem
![image](https://user-images.githubusercontent.com/3858661/68246642-d6053980-ffde-11e9-8c1f-f4fca47acf37.png)

Mac OSX - Mojave -- Safari 12.1.1 and Chrome 78.0.3904.70

**Comment by rafalp** [comment]
`overflow: hidden` will break popups/dropdowns that are positioned with CSS only, which is potential backwards-compatibility issue.

IMHO if you are increasing border radius on card, you should tweak radius on card items accordingly.

**Comment by MartijnCuppens** [comment]
Closing this per comment above and comments in PR https://github.com/twbs/bootstrap/pull/29644

**Comment by leecollings-sb** [comment]
This should be added because currently images at the top of a card will not reflect the rounded corners of the card (the docs make no mention of this).

![Screenshot 2021-10-14 at 11 28 19](https://user-images.githubusercontent.com/12139008/137300478-18d0826e-1454-4edc-89f8-b8029c317edf.png)

![Screenshot 2021-10-14 at 11 28 50](https://user-images.githubusercontent.com/12139008/137300563-aa84a0ce-bf00-406f-98d8-d68bf0f0664d.png)
