### ISSUE TITLE
Docs: add a warning about the Sass implementation

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29760]
See #29743

**Comment by mdo** [comment]
Less of a warning and more of a mention: #32764.

**Comment by voltaek** [comment]
As requested by mdo in #32764, I've updated my PR #32512 to address this issue for the v5 docs.

As this issue is also labeled for v4, I assume that you'd like a PR for similar changes to be made to its doc. In [Getting Started > Downloads](https://getbootstrap.com/docs/4.5/getting-started/download/#source-files), it's mentioned that both LibSass and Ruby Sass are supported. Is that true for v4, or is it just LibSass?

Lastly, in the PR for v4, would you like it mentioned that LibSass is now deprecated, or should the v4 docs stay as more of a "snapshot in time" of when they were originally put together, back when LibSass was still current? I think it may be tricky to state that the recommended Sass compiler is also a deprecated one, but it would be more informative.
