### ISSUE TITLE
Custom control border color missing on focus and checked

### ISSUE THREAD

**Issue by QballDevelop** [twbs/bootstrap#29774]
Focus border color is missing when a custom checkbox is checked.

It's because of the following line of code:
```
&:focus:not(:checked) ~ .custom-control-label::before {
  border-color: $custom-control-indicator-focus-border-color;
}
```

It should be without
`
:not(:checked)
`

Resulting in:
```
&:focus ~ .custom-control-label::before {
  border-color: $custom-control-indicator-focus-border-color;
}
```

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by QballDevelop** [comment]
Here you go:

https://codepen.io/dnl-code/pen/mdydgJN

In all browsers (except safari and IE) and all operating systems.

**Comment by MartijnCuppens** [comment]
You have removed the focus box shadow, which we add for accessibility reasons (some people don't notice the subtle border color change).

**Comment by TAOlijun** [comment]
I&nbsp;Received，thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martijn Cuppens"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午3:42
收件人:&nbsp;"twbs/bootstrap"<bootstrap@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [twbs/bootstrap] Custom control border color missing on focus and checked (#29774)




Closed #29774.

**Comment by QballDevelop** [comment]
@MartijnCuppens that doesn't mean that the focus border should be omitted. Why prohibit the possibility to change this? People can easily increase the border thickness which I did and then they will notice the border color change.

I've intentionally removed the box shadow so you would see more clearly what's going on. I know I can change it with my own css but it took me a while to figure out what's wrong here because of the following line in the variables:
`
$custom-control-indicator-focus-border-color:   $input-focus-border-color !default;
`

Please reopen this issue.
Let me fix this and I will create a merge request.

**Comment by TAOlijun** [comment]
I was wrong at the beginning. I'm sorry. It's very late now. It's delayed your time. Please have a rest earlier. If we can make a friend, I come from China.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"QballDevelop"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午5:00
收件人:&nbsp;"twbs/bootstrap"<bootstrap@noreply.github.com&gt;;
抄送:&nbsp;"风信子"<1252652385@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [twbs/bootstrap] Custom control border color missing on focus and checked (#29774)




@MartijnCuppens that doesn't mean that the focus border should be omitted. Why prohibit the possibility to change this? People can easily increase the border thickness which I did and then they will notice the border color change.
 
I've intentionally removed the box shadow so you would see more clearly what's going on. I know I can change it with my own css but it took me a while to figure out what's wrong here because of the following line in the variables:
 $custom-control-indicator-focus-border-color:   $input-focus-border-color !default;
 
Please reopen this issue.
 Let me fix this and I will create a merge request.

**Comment by MartijnCuppens** [comment]
> and then they will notice the border color change.

No, not everyone will. The color contrast ratio between the border color and the background color in your example is `2.42`, which is too low.

> Let me fix this and I will create a merge request.

The fix you're suggesting will result in this when we leave the `box-shadow` (which we will):

<img width="34" src="https://user-images.githubusercontent.com/11559216/70515482-b14c3680-1b35-11ea-9404-e717125ebcea.png">

This looks a bit odd.

**Comment by QballDevelop** [comment]
>This looks a bit odd.

I agree.

What if we change the following line:
`
$custom-control-indicator-focus-border-color: $input-focus-border-color !default;
`

into:

`
$custom-control-indicator-focus-border-color:   $custom-control-indicator-checked-border-color !default;
`

Then the default would be the same as it is now.

**Comment by MartijnCuppens** [comment]
Could work, let's see what you got. If you make a PR, keep in mind:

- The default theming with box shadow should look like it is now
- I rather not add additional CSS for this case since we have accessibility issues here

The only reason it makes sense to do this is from my POV is if the background of the checked input is changed and the border contrast needs to be adjusted. This is another reason than what you have in mind but if you find a solution on which we can both agree on, I'm ok with continuing on this.

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/29836#issuecomment-586539937
