### ISSUE TITLE
Add an option to compile using css variables

### ISSUE THREAD

**Issue by mojimi** [twbs/bootstrap#29791]
Would be great to have an option (either in node or a sass variable) to choose to not hard-code the colors, but use css variables instead!

So, for example, the class .bg-secondary would compile like this :

```css
.bg-secondary {
  background-color: var(--secondary) !important;
}
```

Of course this could be extended to not only the theme colors, but pretty much any common value

The benefits I see are :

1. Most new projects do not support or try to support IE, these end up missing a lot of flexibility not using css variables. [93% of user browsers support css variables](https://caniuse.com/#feat=css-variables)
2. You wouldn't need to recompile Bootstrap to change the colors, development and testing would be much quicker, not everyone that uses Bootstrap knows how to deal with SASS/NodeJS
3. You'd be able to change colors on the fly, for example if you want to leverage the `prefers-color-scheme` selector to quickly change between light/dark mode

I understand the historical purpose of the compiled colors, but it would be great to have an alternative!

**Comment by mojimi** [comment]
Also, this article is cool : https://medium.com/@Hermanhasawish/how-i-repainted-bootstrap-without-sass-d789f41aa74b

**Comment by MartijnCuppens** [comment]
> Most new projects do not support or try to support IE

Still a lot do. We decided to keep IE support for Bootstrap 5 so we can't implement this yet. Once we drop IE support, we will probably switch to CSS variables.

**Comment by mojimi** [comment]
@MartijnCuppens 

Yes I understand, but just reiterating that I'm talking about a compiling option, not to drop IE support

**Comment by hadi-roudaki** [comment]
have some mercy on angular developers,  the demand for dark mode and multiple themes has increased significantly. this is driven from Apple having dark mode as an option on  OS and IOs. 
I know Material (https://material.angular.io/) offers a better solution for having dynamic themes.  (some of us like bootstrap)
I've read most of the comments against having CSS variables, but the reality is the industry adds features when is trendy and it seems there isn't a nice solution for this on bootstrap. 

shouldn't the focus be on the future feature on V5 instead of having to support old mate Internet Explorer?

overall look bootstrap and thanks for everything you guys do <3
