### ISSUE TITLE
Need more updates on components

### ISSUE THREAD

**Issue by gobi004** [twbs/bootstrap#29797]
Hi,

1. Nowadays all accordions are designing with icons like plus,arrows or some other icons and the click option is enable for whole title box, but i can see from long days its still needs to click on the title to open the accordion body. 

2. Nav menu needs to implements with mega menu  as default component. like normal nav menu option.

3. And https://getbootstrap.com/docs/4.4/components/navs/#working-with-flex-utilities  section while clicking on the tab menu the content body it should open immediate below of the tab title, but it shows after the tab titles.this needs to implement
 
Nowdays all designs are designing with some default behaviors, so please take care of those things while adding and updating the components  
Some of the above points are will helpful for developers to use bootstrap.

**Comment by mdo** [comment]
Accordions are customizable, you can change how they’re toggled.

Navigation doesn’t need mega menus as any kind of default. This is something you can create and others can create as needed for your projects.

The example there isn’t functional by design—there is JS for toggling tabs though, just look at the nav components page.
