### ISSUE TITLE
Stretched link extending beyond containers

### ISSUE THREAD

**Issue by thehitechpanky** [twbs/bootstrap#29804]
- Operating system and version (Ubuntu)
- Browser and version (Chrome)
Stretched link not working as expected. For example, in case of <tr><td><a class="stretched-link">Some text<a></td></tr> it makes whole row link instead of a single cell. It should make immediate container link and not parent of parent.

**Comment by ffoodd** [comment]
You're probably missing a `position: relative` (using `.position-relative` helper class) on your container.

This is [very well explained in the stretched link utility documentation](https://getbootstrap.com/docs/4.4/utilities/stretched-link/).

**Comment by thehitechpanky** [comment]
> You're probably missing a `position: relative` (using `.position-relative` helper class) on your container.
> 
> This is [very well explained in the stretched link utility documentation](https://getbootstrap.com/docs/4.4/utilities/stretched-link/).

The documentation is not clear for usage in tables. Whether, we have to add position-relative class in link itself or in containing cell or row or table?

**Comment by ffoodd** [comment]
@thehitechpanky Usage in tables do not differ from others. And as mentionned in the documentation:

> Add .stretched-link to a link to make its containing block clickable via a ::after pseudo element. In most cases, this means that an element with position: relative; that contains a link with the .stretched-link class is clickable.

So you need to put `.position-relative` class on the element you want to be clickable. That's all, and clearly described :/

**Comment by masoudd** [comment]
Take this case for example:
https://codesandbox.io/s/withered-frost-nq91i
It works on firefox but not on chrome. On chrome the whole page becomes clickable leading to the latest element with .stretched-link
[Similar report on stackoverflow](https://stackoverflow.com/questions/61342248/streteched-link-bootstrap-utilities-doesnt-work-in-chrome)

**Comment by ffoodd** [comment]
Well, that's [a known bug in Blink](https://bugs.chromium.org/p/chromium/issues/detail?id=417223). 

A few searches made me find a related [CSS WG issue](https://github.com/w3c/csswg-drafts/issues/1899) about a previous version of the spec mentions an interesting workaround: using something like `transform: scale(1);` solves your test case, [because it creates the containing block `position: relative` should but can't](https://drafts.csswg.org/css-transforms-1/#containing-block-for-all-descendants). You may also try `perspective`.

@mdo @MartijnCuppens should we mention this in our docs?

**Comment by MartijnCuppens** [comment]
Wow, I wasn't aware of the `transform: scale(1);` hack. This is a duplicate of https://github.com/twbs/bootstrap/issues/28608 btw
