### ISSUE TITLE
Mixin text-emphasis-variant fails

### ISSUE THREAD

**Issue by jbmolle** [twbs/bootstrap#29844]
Hi,
I've just got this error from Bootstrap 4.4.1
SassError: wrong number of arguments (3 for 2) for `text-emphasis-variant'
        on line 48 of node_modules/bootstrap/scss/utilities/_text.scss, in mixin `text-emphasis-variant`

On 4.3.1 everything works fine.

Best,
JB

**Comment by florianlacreuse** [comment]
`text-emphasis-variant` has 3 arguments now:

https://github.com/twbs/bootstrap/blob/v4.4.1/scss/mixins/_text-emphasis.scss#L5

Did you also update the mixins files like `_text-emphasis.scss`?

**Comment by jbmolle** [comment]
Thanks for the answer. I've noticed that there were 3 arguments now but I download bootstrap directly with NPM so I think the problem comes from the NPM package.

**Comment by mdo** [comment]
Don't think there's a problem with npm package. Closing out since this seems resolved.

@twbs/css-review We may need to be more careful about when we add new arguments if it breaks things for folks upon upgrading.

**Comment by prma85** [comment]
I having the same issue when using webpack.

```bash
 Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: wrong number of arguments (3 for 2) for `text-emphasis-variant'
            on line 48 of node_modules/bootstrap/scss/utilities/_text.scss, in mixin `text-emphasis-variant`
            from line 48 of node_modules/bootstrap/scss/utilities/_text.scss
            from line 71 of sass/themes/default/utilities/_base.scss
            from line 17 of C:\Users\Paulo.Andrade\Documents\GitHub\Hub.Common.Styling\sass\themes\default\_base.scss
    >>   @include text-emphasis-variant(".text-#{$color}", $value, true);
       -----------^
```

The error is coming from bootstrap itself on the `bootstrap/scss/utilities/_text.scss` on line 48.
I am not using this mixing right now, but it is broken on bootstrap :(
Probably the same issue that @jbmolle was having but {s}he just forgot to put more details.

Any idea of how it can be solved @mdo @florianlacreuse ? If I rollback to bootstrap `4.4.0` this issue is gone. I am using right now the version `4.5.0`.

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/issues/29844#issuecomment-565125409 has details on what happened I think. Without knowing more, there may be something else off in your setup.

**Comment by prma85** [comment]
I saw that. And as I said, I am not using this mixing, but I am importing the `bootstrap/scss/utilities/_text.scss` because of the styling. I am also not overriding the mixing.

If I remove the import of this file, my project will build. However, I will miss all the styling from the text utility.

It looks like it is trying to send all three parameters to the mixin, but the mixin is not accepting, only 2.

If you guys have no idea, I will probably end up copying the entity content locally and fixing it for me (removing the parameter).

**Comment by jbmolle** [comment]
Hi prma85,
Actually I had the problem because I was overwriting text-emphasis-variant in one of my scss file and I was using 2 arguments instead of 3. When I found the file everything was working again. The problem was not coming from the NPM package so it was right from the bootstrap-vue team to close this issue.

**Comment by prma85** [comment]
I see, in my case, I am not overriding it, just calling it :(

**Comment by jbmolle** [comment]
Ok weird...
Are you not using another package that may use an older version of bootstrap-vue? The package could overwrite the mixin with 2 arguments and cause the error?
