### ISSUE TITLE
Switch - other variants

### ISSUE THREAD

**Issue by DM2489** [twbs/bootstrap#29887]
The current implementation of switched in bootstrap only caters for the primary colour.

https://getbootstrap.com/docs/4.4/components/forms/#switches

Would it be possible to add other variants? It's common to want to have a switch that shows a different colour (red, green, purple etc.) to go with the theming of the component being used. For example, I might have a switch in an success alert or danger alert. This is always blue, and doesn't look great.

https://codesandbox.io/s/bootstrap-4-example-cli31

This has been marked as an upstream issue in Bootstrap-Vue. https://github.com/bootstrap-vue/bootstrap-vue/issues/4312

**Comment by mdo** [comment]
Because we support form validation states on our checks (and switches), I don't think we'd go the route of enabling custom colors here. It'd cause additional confusion IMO. See v5's upcoming docs preview for how this looks in practice: https://twbs-bootstrap.netlify.com/docs/4.3/forms/validation/#supported-elements.

**Comment by DM2489** [comment]
@mdo Thanks for the reply.  Just so I understand, what would be the issue with validation states (when applied) overriding the chosen theme in the same way that it does for the `primary` colour?
