### ISSUE TITLE
Bootstrap 4 carousel pause function is not working when it's getting called from the event of an element inside of the carousel

### ISSUE THREAD

**Issue by cuartas15** [twbs/bootstrap#29890]
I made a question on Stack Overflow and didn't get a response (surprise), it is detailed with code and everything so I'm gonna link that.

 A TL;DR is that calling carousel('pause') from an element's event inside of the carousel (that being a button, a whole div, etc) wont work on phones using mobile browsers.

So if I do:

`$('.element-to-pause-carousel').click(function() {`
    `$('#my-carousel').carousel('pause);`
    `$(this).parents('#my-carousel').carousel('pause'); // alternative`
`}`

It wont work IF .element-to-pause-carousel is contained inside the Carousel HTML structure, the slider never stops and just keeps cycling through images / content.
On the other hand, if the element is outside anywhere in the DOM, it works.

Remember, this is only happening to me on mobile, on desktop it's working as intended.

I don't really know if this is a bug or not but I flagged it as one just in case, I've tried a lot of different approaches that you can find in the Stack Overflow post and none of them worked.

https://stackoverflow.com/questions/59403454/why-is-bootstrap-4-carousel-pause-function-not-working-when-its-getting-called

**Comment by mendozagioo** [comment]
@cuartas15  it's working to me.
You have a typo:
`$('#my-carousel').carousel('pause');` instead of: `$('#my-carousel').carousel('pause);`
Tested on Chrome mobile v79 on iOS.
Watch here: https://codepen.io/mendozagioo/pen/qBEpWpx

**Comment by minaelee** [comment]
This is not a mobile/desktop issue but a touchscreen issue. Same issue occurs in desktops/laptops with a touch-enabled monitor. Testing with Bootstrap 4.5 and jQuery 3.5.1.

The default pause: "hover" behavior seems to be the culprit, where the carousel hover behavior overrides the jQuery click event inside the carousel. If the buttons are placed _outside_ of the carousel, the jQuery works, as cuartas15 noted, for this reason. Setting the default pause: "hover" property to pause: "false" in the .carousel() method call will also fix this. See: https://codepen.io/minae/pen/jOqvWvK and comment/uncomment lines 2/3 on a touchscreen device to see the bug in action.

In mendozagioo's Codepen, note that he already has the pause: "false" option in his JS carousel() method, which is why it works, but this was not mentioned in the comment. 

Desired behavior: Even if the jQuery click event is triggered by elements inside the carousel div, it should still work. OR documentation should be updated about this behavior to use jQuery methods outside of the carousel. For alignment reasons it's natural for people to place the buttons inside the carousel.

**Comment by westerbail** [comment]
Does anyone know why this is closed? I think the typo was a red-herring. I can confirm @minaelee comment's above as the exact scenario I am facing as well

**Comment by minaelee** [comment]
Agreed, @patrickhlauke this should not be closed. It was closed because it was assumed that the fix was to correct the typo. It was not. The fix (or rather, workaround) was to set pause: "false" when calling .carousel() from inside the carousel div, and again, it should either be mentioned in the documentation or it should be fixed so that it isn't necessary.

**Comment by cuartas15** [comment]
Yeah, it was a typo on my part, ON THIS POST, not in the actual code. At the moment I created the post I did a code example from scratch in the same GH text editor, because as you can see, the example in the Stack Overflow post is too big. So I just went with a TL;DR code example over here.
I'm just gonna say, I found a workaround for it, but it's been sooo long that I don't remember exactly what I did, so following @minaelee 's solution may be the best thing you can do

**Comment by justingolden21** [comment]
Still facing this issue. It should really be reopened @patrickhlauke
