### ISSUE TITLE
Customising theme Colors!

### ISSUE THREAD

**Issue by raxraj** [twbs/bootstrap#29947]
Bug reports must include:

- Operating system and version 
PLATFORM INDEPENDENT
- Browser and version
PLATFORM INDEPENDENT

As I was going through the source files! 
Changing the theme color is not possible by just defining the CSS.

I know that bootstrap defines variables such as --primary to define the color of buttons (in this case .btn-primary). Instead, I would like to have my custom color. However, I didn't manage to set another "primary" color, even inserting the following snippet of code in the HTML files before or after the <link> tag for the bootstrap.css.

<style>
  :root {
     --primary: #009c68;
  }
</style>

Because of the SASS variable script changes.

**Comment by MartijnCuppens** [comment]
You'll need to use Sass to change the variables, see https://getbootstrap.com/docs/4.4/getting-started/theming/#sass for more info.

**Comment by SharakPL** [comment]
Hi @MartijnCuppens I'm trying to make bootstrap customizable but your theming docs don't help 😕 
The main problem is it's impossible to use 1 custom file with variable overrides. I'm stuck at this point:
```
@import "overrides"; 
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
@import "custom";
@import "../../node_modules/bootstrap/scss/root";
(... and the rest of bootstrap files)
````
In *_overrides.scss* file I override default variables i.e. `$primary: #dc3545` but I can't use `$primary: $red` - default $red from bootstrap variables because it's loaded afterwards and causes error in webpack. I have to specifically define $red in my _overrides_ in order to use it this way, wich means that I will basically repeat a lot of default variables content.

If I move it to *_custom.scss* instead then default values are available and webpck bundles it with no errors, but in the same time overrides from _custom_ file are ignored. If I put there `$primary: $cyan`, then the value of primary color will be the one from _overrides_ file or default blue one from _~bootstrap/scss/variables_. Not $cyan! How am I supposed to know where can I place each variable for it to still take effect?

Of course I can't put everything in overrides because some variables are set with help of functions and mixins. For example if I want to add $tertiary color and be able to use it with components like btn-tertiary I have to do map-merge in *_custom.scss*:
````
$tertiary: $cyan default;

$theme-colors: map-merge(
    (
        "tertiary": $tertiary
    ),
    $theme-colors
);
````
But if I would like to use $tertiary also as value of my other variables placed in _overrides_ file then I would have to move definition there and only merge it with $theme-colors in _custom_. 

I'll honestly go insane if I have to do it this way. The only logical enough way would be to not import default variables at all and use whole file as my custom variables instead:
````
@import "~bootstrap/scss/functions";
// @import "~bootstrap/scss/variables";
// copy content of "~bootstrap/scss/variables" to _variables.scss below and set everything there
@import "variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/root";
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/images";
@import "~bootstrap/scss/code";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/dropdown";
@import "~bootstrap/scss/button-group";
@import "~bootstrap/scss/input-group";
@import "~bootstrap/scss/custom-forms";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/card";
@import "~bootstrap/scss/breadcrumb";
@import "~bootstrap/scss/pagination";
@import "~bootstrap/scss/badge";
@import "~bootstrap/scss/jumbotron";
@import "~bootstrap/scss/alert";
@import "~bootstrap/scss/progress";
@import "~bootstrap/scss/media";
@import "~bootstrap/scss/list-group";
@import "~bootstrap/scss/close";
@import "~bootstrap/scss/toasts";
@import "~bootstrap/scss/modal";
@import "~bootstrap/scss/tooltip";
@import "~bootstrap/scss/popover";
@import "~bootstrap/scss/carousel";
@import "~bootstrap/scss/spinners";
@import "~bootstrap/scss/utilities";
@import "~bootstrap/scss/print";
````
Isn't there a better way?

**Comment by mdo** [comment]
If you need access to Bootstrap's variables in your own custom Sass, you'll likely need to import the beginning of our imports (functions, variables, mixins), import your custom Sass, and then the rest of Bootstrap. We're limited by how Sass works, though perhaps their new module improves upon things.

Duplicating our `bootstrap.scss` though and inserting a `custom.scss` between the first support files and the rest of the components and more isn't a bad thing though—this is quite typical and gives you the functionality you want I believe.
