### ISSUE TITLE
offset taking extra margin-left if it exceeds 12 columns

### ISSUE THREAD

**Issue by vishwa12345** [twbs/bootstrap#29972]
As per my Bootstrap-4 understanding for below code, **Output-1** should be the output

       `<div class="row">
            <div class="col-md-4">
               1
            </div>
            <div class="col-md-4">
                2
            </div>
            <div class="col-md-4 offset-md-4">
                3
            </div>
        </div>`

**Output-1** 

![Output1](https://user-images.githubusercontent.com/18283439/71896288-6136b300-3179-11ea-8933-8484612bcf84.png)

But it is displaying as **Output-2**

 **Output-2**
![Output2](https://user-images.githubusercontent.com/18283439/71896408-bb377880-3179-11ea-8888-d01757f2e8f7.PNG)

I mean if 12 columns exceed in the first row, if last columns is having offset then it will come down and again it will take margin-left for declared class. Is this is correct? or My understanding is wrong?

Thanks in advance.

**Comment by herbalite** [comment]
This is because offset-md-4 sets margin-left to 33.3333%.

Section 3 doesn't fit into the first line, because of the margin-left offset-md-4. Once it is wrapped to the new line, offset-md-4 forces Section 3 to the right because of the margin-left.

Essentially, the mix of flex and margin-left doesn't work well in a situation like that.

So you have to find another way to arrange the desired grid .

**Comment by florianlacreuse** [comment]
You can use [column breaks](https://getbootstrap.com/docs/4.4/layout/grid/#column-breaks) to get "Output-1".

**Comment by mdo** [comment]
Per last comment here, you need to use column breaks instead. This is how every browser renders this and is not a Bootstrap bug. I'm unaware of a way to essentially "separate" the margin of an element from said element—that simply isn't possible. You could set the `margin-right` instead, though.

Example: https://codepen.io/emdeoh/pen/JjoLKOv
