### ISSUE TITLE
Sass files are not added to the project, when installed bootstrap.sass nuget package

### ISSUE THREAD

**Issue by Liero** [twbs/bootstrap#30045]
when installing bootstrap.sass into ASP.NET Core 3.1 project, the sass files are not added to the project.

The reason is described [here](https://stackoverflow.com/a/59712339/475727): 
> package authors should use contentFiles element instead of old content element when creating packages.
> The author do include those files in the contentFiles folder when generating nuget packages. However, he also need to specify the contentFiles element in xx.nuspec file like this [issue](https://stackoverflow.com/questions/34031650/nuspec-contentfiles-example). Only one folder whose name is contentFiles in xx.nupkg is not enough if we want to access those files in VS Solution Explorer

Steps to reproduce:

1. Create default asp.net core project with either CLI or Visual Studio
   `dotnet new webapp`
2. cd web-app
3. Install-Package bootstrap.sass

- .NET Core 3.1
- Operating system and version Win10
- Visual Studio 16.4 (optional)

**Comment by MartijnCuppens** [comment]
I don't use NuGet myself. Anyone else who can confirm/contradict this issue?

**Comment by Liero** [comment]
Well, it was confirmed by the Lance Li from Microsoft in the linked stackoverflow answer

**Comment by XhmikosR** [comment]
I really think it's time we ignore anything else than what we use. Nuget and composer are 2 examples.

/CC @mdo.

**Comment by mdo** [comment]
According to our GitHub repo `Used by` dropdown, we have nearly 300k NuGet projects that depend on Bootstrap. No way of knowing if those are all active, but that’s a good amount.

<img width="767" alt="Screen Shot 2020-01-19 at 2 37 29 PM" src="https://user-images.githubusercontent.com/98681/72689734-64ab3200-3ac9-11ea-95e4-e77093524b94.png">

We could definitely drop Composer and look at what that other NuGet package is for 300 dependent repositories.

**Comment by XhmikosR** [comment]
Yeah, but we don't maintain this ourselves not we do use it.

**Comment by Liero** [comment]
@XhmikosR: 
> Yeah, but we don't maintain this ourselves not we do use it.
How so?

The official bootstrap documentation says, that we can install bootstrap using nuget: https://getbootstrap.com/docs/4.4/getting-started/download/ and the nuget package is in this repo: https://github.com/twbs/bootstrap/blob/master/nuget/bootstrap.sass.nuspec.

So either make the package obsolete, remove it from docs or fix the bug :) I can do the PR if you want

**Comment by XhmikosR** [comment]
Like I said, I'd rather nuke anything that we don't control ourselves.

I can make the change if we come to an agreement.

**Comment by XhmikosR** [comment]
I just now remembered that @supergibbs maintains the NuGet package. Can you check this issue @supergibbs please?

**Comment by supergibbs** [comment]
@Liero Why are you using NuGet for bootstrap on a .net core web app? As [previously discussed, NuGet is meant for compiled code](https://github.com/twbs/bootstrap/issues/16692#issuecomment-117922208), better to use npm or something else for client side packages. VS2019 has [LibMan](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/?view=aspnetcore-3.1) built in and I was able to install bootstrap with all the scss files using the libman.json file:

`{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "provider": "jsdelivr",
      "library": "bootstrap@4.4.1",
      "destination": "wwwroot/lib/bootstrap/"
    }
  ]
}`

NuGet is still often used in .NET Framework Web Apps since client side lib support is lacking. I tried a quick fix of the `contentFiles` element in metadata but that didn't seem to work on a core webapp until deploy. Happy to review a PR if you know how to make it work or I can try more this weekend. The `MyGet.ps1` can be edited to build locally.

As for @XhmikosR's comment about dropping nuget support, [it seems like there are users that want it](https://github.com/twbs/bootstrap/issues/28902). All the needed code is [part of the repo](https://github.com/twbs/bootstrap/tree/master/nuget) and technically @mdo has access to deploy to nuget.org. I am happy to continue to support a bootstrap NuGet package and can do so in a more official capacity if you want. I'd love to setup GH actions to create and deploy instead of me manually doing it.

**Comment by Liero** [comment]
> @Liero Why are you using NuGet for bootstrap on a .net core web app?

Irrelevant. There's a nuget package that I used exactly as mentioned in the bootstrap docs and it doesn't work. I suggest: remove it from the docs and mark the package as obsolete... That would be ideal.

**Comment by XhmikosR** [comment]
> As for @XhmikosR's comment about dropping nuget support, [it seems like there are users that want it](https://github.com/twbs/bootstrap/issues/28902). All the needed code is [part of the repo](https://github.com/twbs/bootstrap/tree/master/nuget) and technically @mdo has access to deploy to nuget.org. I am happy to continue to support a bootstrap NuGet package and can do so in a more official capacity if you want. I'd love to setup GH actions to create and deploy instead of me manually doing it.

The problem I have with this, is that something we don't use or test in some way, it is bound to break. That's OK if someone's around to take care of it, but none of us does use NuGet.

That being said, I guess having an action to take care of things automatically sounds good.

Now back to this issue. Is there something wrong with the currently published bootstrap.sass NuGet package? Reading the OP, it seems the output folder needs to be adapted?

**Comment by supergibbs** [comment]
I think I figured it out, waiting for clarification on the desired result: https://stackoverflow.com/a/60065053/40887

**Comment by supergibbs** [comment]
I've published two new packages with the fix for dot net core projects:

https://www.nuget.org/packages/bootstrap/4.4.1-content-files
https://www.nuget.org/packages/bootstrap.sass/4.4.1-content-files

As a side effect, you need to check ![image](https://user-images.githubusercontent.com/1106331/74074785-9460a200-49c4-11ea-873f-4e4423db7586.png) to install them (won't be the case for v4.4.2 if released).

There are open PRs to make sure this is applied the next release as well.
