### ISSUE TITLE
Table headers and text-align

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#30321]
<img width="838" alt="Screen Shot 2020-02-29 at 9 12 03 AM" src="https://user-images.githubusercontent.com/98681/75611927-b6d17100-5ad3-11ea-98e7-5ebfb9c6b5da.png">

The Reboot docs talk about `text-align` being matched to the `<td>`, but as you can see above, `<th>`s aren't left-aligned. This is because we're not explicitly setting `text-align` anywhere up the DOM. We updated our styles while back I believe to lower the selector specificity to allow `.text-*` classes on `.table`, but we didn't reset the default value.

I'd like to fix this by doing one of the following:

- Setting `text-align` on the `<body>` to a default `left` value.
- Setting an explicit `text-align` on the `<th>` in Reboot (my preferred I think, given lowest specificity and an existing selector).
- Setting an explicit `text-align` on the `.table`.

Thoughts @twbs/css-review?

**Comment by MartijnCuppens** [comment]
Hmm, this seems to be caused by https://github.com/twbs/bootstrap/pull/28989, which we didn't test in Safari.

> Setting text-align on the <body> to a default left value.

This will reintroduce the rtl issue

> Setting an explicit text-align on the <th> in Reboot (my preferred I think, given lowest specificity and an existing selector).

This way `text-center` will need to be set on each th to override alignment

> Setting an explicit text-align on the .table.

Like the body alignment, this will reintroduce the rtl issue.

`text-align: -webkit-match-parent;` does seem to fix this (with inherit as fallback for non webkit browsers):
 https://codepen.io/MartijnCuppens/pen/PoqjNxx

Need to test this more though.
