### ISSUE TITLE
add jquery to requirement in package.json

### ISSUE THREAD

**Issue by bhalial** [twbs/bootstrap#30641]
I think jquery should be a requirement for bootstrap, so version control is done by bootstrap instead of us trying to fix bugs that are caused by a mismatch of versions between the two.

**Comment by ffoodd** [comment]
Well, it is not: one may only want to use JS free components, that's why [it's a `peerDependency`](https://github.com/twbs/bootstrap/blob/v4.4.1/package.json#L101): this is where you'll find version control informations.

This is pretty well explained in [Getting started / Introduction](https://getbootstrap.com/docs/4.4/getting-started/introduction/) — you even have a list of components requiring JavaScript — as well as in [Getting started / JavaScript](https://getbootstrap.com/docs/4.4/getting-started/javascript/#dependencies).
