### ISSUE TITLE
Jquery < 3.5.0 security vulnerabilities

### ISSUE THREAD

**Issue by jcoyne** [twbs/bootstrap#30692]
There are two security vulnerabilities reported with the version of jquery that bootstrap 4.4.1 requires

GHSA-jpcq-cgw6-v4j6
GHSA-gxr4-xjj5-5px2

This appears to be fixed by https://github.com/twbs/bootstrap/pull/30559, but i don't believe that's been released yet.

**Comment by lightning-dabbler** [comment]
I don't think it's been released either. I'm still getting 
```javascript
Cannot convert object to primitive value
```
error because of collapse.js on v4.4.1.
Are they waiting to release this in v4.4.2?

**Comment by XhmikosR** [comment]
It's not released yet, but you should wait for jQuery v3.5.1 because more libraries are probably broken.

We are wrapping up any v4.4.2 patches and I'll try to release v4.4.2 ASAP.

**Comment by lorvent** [comment]
out of curiosity, this breaking change is only for jquery 3.x or for 1.x, 2.x too?

and will bootstrap 4.4.2 works with jquery 1 and 2 or no?

many thanks

**Comment by XhmikosR** [comment]
Only v3.5.0 has this bug AFAICT. But they made some security fixes in the same version, which is why they need to release v3.5.1 ASAP.

That being said, one can stay on jQuery  v3.4.1 if they value that they are not affected by the security fixes.

As for older versions of jQuery, we actively test v1.9.1 and 3.4.1 and both work fine for Bootstrap v4.4.1. Bootstrap v4.4.2 which has the fix from our side will also work with jQuery v3.5.0.

But I **really** hope they release a new patch version too soon.

**Comment by Gemorroj** [comment]
jquery 3.5.1 released https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

**Comment by XhmikosR** [comment]
jQuery [v3.5.1](https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/) was released a few hours ago. This should work with Bootstrap 4.x fine.

I'm going to close the issue, although we do have a fix in our v4-dev branch but now it's irrelevant.

**Comment by sleepinzombie** [comment]
I tried using the `v3.5.1` with Bootstrap `v4.4.1` and `collapse.js` is now throwing another error : `TypeError t`.

Am I doing something wrong or the fix they released doesn't work?

**Comment by XhmikosR** [comment]
You are doing something wrong.

**Comment by lightning-dabbler** [comment]
Hmm I'm not having this issue and the release works for me.
