### ISSUE TITLE
custom-radio and custom-checkbox are not clickable when no label associated to input controls

### ISSUE THREAD

**Issue by jalik** [twbs/bootstrap#30702]
Hello, I noticed that when not labels are associated to radio controls with `custom-radio` class, it's impossible to select a radio control, it also happens with checkboxes and `custom-checkbox` class.

This is because the input has a `z-index: -1`, so it is below the custom radio shape and the click is always caught by the custom shape and never by the input radio.

A simple fix would be to set `z-index: 1` on `.custom-radio`, to move the input control over the custom shape, it should not be a problem since it has `opacity: 0`.

Here is an example: https://codesandbox.io/s/bootstrap-custom-radio-bug-with-react-35tuw?file=/src/App.js

OS: KDE neon User Edition 5.18 x86_64
Browsers: Firefox 75.0 (64 bits) / Chromium 80.0.3987.163

**Comment by mdo** [comment]
Yes, this is because the custom form controls are generated by pseudo-elements from the label itself. Without that class and element present, there's no custom radio or checkbox. This changes in v5 since we've combined our native and custom checks into a single set of classes with no extra markup required.
