### ISSUE TITLE
touch for carousel does not work onload

### ISSUE THREAD

**Issue by SnippetsUnlimited** [twbs/bootstrap#30700]
I have issue with Carousel for version 4.3.1.
Swipe on Carousel does not work on mobile on load (with "data-touch" is set to true) unless we click the next button first. I have tested this with a touch supported laptop (using chrome) as well and its not a device issue.
Looking at the bootstrap code for carousel, It seems that the event handlers are not properly bound at the time of construction of carousel class. Clicking the navigation elements fixes and sets the event binding correctly. A proof of this is when the carousel is loaded there is no "pointer-event" css class on the main element and is only added once you click the "next" navigation link.

**Comment by XhmikosR** [comment]
Patches welcome. Also please don't skip filling the issue template.

**Comment by gnoot** [comment]
Hi ! @SnippetsUnlimited 
Can't I work around this problem by doing the following?

`<div id="myCarousel" class="carousel slide" data-interval="false" data-touch="true" data-ride="carousel">`

The key points are`data-interval="false"` stops autoplay. And  add`data-ride="carousel"`.
It seems to be contradictory, but without `data-ride="carousel"`, no instance will be created and no event handlers will be set.

You might want to take a look here.
https://github.com/twbs/bootstrap/blob/v4.3.1/js/src/carousel.js#L585

Hi @XhmikosR 
The bootstrap is very cool.
I use it a lot. Thank you.

I thought I'd try to solve this problem.
Because I didn't know how to fix it.
I'd love some advice.

**Comment by Johann-S** [comment]
Hi,

Yes if you want the touch events to be set on load you have to use `data-ride` as @gnoot said 👍
