### ISSUE TITLE
SassError when consuming Bootstrap 4 variables when importing into SCSS files, how to resolve?

### ISSUE THREAD

**Issue by adamm-monek** [twbs/bootstrap#30790]
What import is needed in order to import Bootstrap 4 at SCSS level, AND also be able to use the variables? I get a SassError for undefined variables. This feels like it might be a bug?

Generally speaking, Bootstrap works. The utility classes work. I can use mixins. I can re-define variables with no problem. I just can't _consume_ existing BS4 variables.

See https://stackoverflow.com/questions/60948890/sasserror-undefined-variable-with-angular-9-and-bootstrap-4-out-of-the-box for further details.

**Comment by ffoodd** [comment]
This seems completely unrelated to Bootstrap, since as you said in StackOverflow you made it work with Angular 8.

[Importing Sass files](https://getbootstrap.com/docs/4.4/getting-started/theming/#importing) is documented, as well as overriding variables and working with maps, functions, etc.

Either you are using the wrong path, or not including this path in your Sass compilation script, or not importing it at the right place (since `_variables.scss` has to be imported before you use any variables).

I'll bet on **not importing it at the right place / moment**, since you said you can override variables: it's imported. Maybe should you explicitly import `_variables.scss` at the beginning of your your `styles.scss`?

But importing our variables works and is documented. We cannot provide support for working in Angular. I hope my comment will help, otherwise please wait for any Stack Overflow help on this. You may ask on our Slack, too.

**Comment by adamm-monek** [comment]
Thanks for the reply, and I am sure your advice is helpful. 

I guess that Angular is one of the main JS libraries out there, and that it might have been something that someone at Bootstrap has encountered.

I have tried explicitly importing _variables.scss, I've tried the following variants:
```
@import "~bootstrap/scss/bootstrap";
@import "~bootstrap/scss/_variables";
@import "~bootstrap/scss/_variables.scss";
@import "../node_modules/bootstrap/scss/_variables.scss";
@import "../node_modules/bootstrap/scss/variables";
```

**Comment by mdo** [comment]
> I just can't _consume_ existing BS4 variables.

This is a limitation of Sass unfortunately... when you override the Sass default variables, you do so before the import of Bootstrap itself. See this WIP v5 docs page for customizing: https://twbs-bootstrap.netlify.app/docs/4.3/customize/sass/#variable-defaults

You could double import _I think_, but I'm not 100% sure that'd solve what you're experience.
