### ISSUE TITLE
Typo in the docs code provided, should be card-img-bottom

### ISSUE THREAD

**Issue by iuriirudov** [twbs/bootstrap#30839]
![Capture](https://user-images.githubusercontent.com/64018778/82112755-1c6dea80-971e-11ea-92ea-3f93cad8e8f9.JPG)

**Comment by ffoodd** [comment]
@XhmikosR I'm quite confused here: 
- [deployed site is wrong](https://getbootstrap.com/docs/4.5/components/card/#image-caps) as mentionned here—and smae result locally.
- but [source code is not](https://github.com/twbs/bootstrap/blame/v4-dev/site/docs/4.5/components/card.md#L374) and is accurate for years.

I think it could be related to the `example.html` partial, [which processes `class` on placeholder images](https://github.com/twbs/bootstrap/blob/v4-dev/site/_includes/example.html#L40).

Don't know how to fix this, though.

**Comment by XhmikosR** [comment]
I'd just use the raw HTML and be done with it. Like https://github.com/twbs/bootstrap/blame/v4-dev/site/docs/4.5/components/button-group.md#L94. Master is fine and I can't/don't want to dig into this Jekyll/Liquid mess a lot...

From a quick look, though, it seems we should loop through `content_chunk` because currently it just gets the first match.

**Comment by XhmikosR** [comment]
Fixed by #30925.
