### ISSUE TITLE
Wrong vertical align in button links

### ISSUE THREAD

**Issue by Miqueliu** [twbs/bootstrap#30837]
I saw that the button links doesn't obey to `vertical-align` style. It keep being to top, not in the middle. [Here](https://jsfiddle.net/ebj9L6vx/) is visible this problem.

**Comment by mdo** [comment]
This doesn't appear to be a problem with `vertical-align`. Looks like `<button>`s get some flexbox styling that anchors do not. We could perhaps reset this in Bootstrap with two additional properties on our `.btn` elements, but I'm unsure of the downstream affects of that.

This fixes it in your demo:

```
.btn {
  display: inline-flex;
  align-items: center;
}
```

**Comment by Miqueliu** [comment]
Yes, it is a nice solution.

However, according I'm testing, buttons doesn't apply any native flex style. This is verifiable adding only `display: inline-flex;` declaration.

**Comment by mdo** [comment]
It's a user agent style, directly from the browser.
<img width="374" alt="Screen Shot 2020-05-15 at 5 25 06 PM" src="https://user-images.githubusercontent.com/98681/82105614-1271ca80-96d1-11ea-8ece-d18b831b5b0e.png">

**Comment by Miqueliu** [comment]
Sorry, but it has no sense. Despite your browser applies some secondary property of flex, the Bootstrap's `display: inline-block;` declaration to `.btn` nullifies any flex effect.

Besides that in Firefox `align-items` is displayed as the default value (`normal`).

![Anotación 2020-05-16 133749](https://user-images.githubusercontent.com/20933395/82118910-77352f80-977a-11ea-9c9e-80d558d08fc0.png)

**Comment by ffoodd** [comment]
@mdo FWIW, in Boosted `.btn` is `display: inline-flex` as a default (mostly to ease alignment within button, eg. an icon or multiple pieces of text). 

The only drawback I know off is that there's no more "automatic" whitespaces between two button (since they're due to `inline-block`).

**Comment by ffoodd** [comment]
Investigating a bit further, it's defintely related to `vertical-align` and our misunderstanding of how it works. Just have a look at [the same, extended Fiddle](https://jsfiddle.net/2d8oxjfm/1/) for a fresh example. Even when using `vertical-align: bottom`, link is top aligned.

This is because for `inline-block`s, the content box is affected by `vertical-align`, not the text node.

However this wouldn't solve the issue. @Miqueliu You'd have to either use `inline-flex`, or to use a custom `line-height` which value should be equal to your `min-height`.

You may want to read [ CSS-Tricks' "Centering in CSS: A Complete Guide"](https://css-tricks.com/centering-css-complete-guide/).

@mdo is there any good reason to keep `vertical-align` on `.btn`? Just tested in `master` and I can't see any difference anywhere (buttons, buttons groups, dropdowns…). It's pretty confusing.

And shouldn't we use `inlmine-flex` on buttons, now? As I said, this is used in Boosted for months (years, maybe) without any drawbacks I can think of. And it'd be simple to PR :)

**Comment by mdo** [comment]
Not sure how to move forward on this one. Our buttons have been pretty bulletproof on alignment and what not. Having half a year go by with no movement here makes me think this isn't worth fixing.

Thoughts @twbs/css-review?

**Comment by Miqueliu** [comment]
Your `display: inline-block;` maybe is a good solution. The class `vertical-align` would have to be coherent applied in any element.

**Comment by ffoodd** [comment]
I'd recommend closing this, @mdo. Using `inline-flex` would have side-effects (as @MartijnCuppens mentionned in #30923) — mostly eating whitespaces out — and dropping `vertical-align` would't solve this at all.

The initial issue is using `height` or `mon-height` on our buttons: they're not designed to handle this (and should probably not). So I'd simply stick to my previous recommendation: if using `height` or `min-height` on our button, ensure to set `line-height` with the same value.

Feel free to step in to discuss or re-open if needed. :)

**Comment by Miqueliu** [comment]
[Here](https://jsfiddle.net/sxq786ym/) is an extended demo.

**Comment by ffoodd** [comment]
Yup, and as mentionned, [applying a `line-height` matching `min-height` solves the issue](https://jsfiddle.net/w4bLctmf/). Since you're applying `min-height` already, applying `line-height` alongside shouldn't be difficult.

**Comment by Miqueliu** [comment]
Yes, @ffoodd, this works with absolute values, but [not for relative ones](https://jsfiddle.net/208qp3ax/).
