### ISSUE TITLE
Revisit .babelrc.js

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#31007]
Not sure what was the reason behind using @babel/plugin-proposal-object-rest-spread; spread seem to be transpiled even without the extra plugin.

Also, `exclude: ['transform-typeof-symbol']` does not seem to apply in our codebase.

Any hints welcome.

**Comment by razh** [comment]
- `@babel/plugin-proposal-object-rest-spread`

  This is enabled by default because it's a part of ES2018.

  https://github.com/babel/babel/pull/10820

- `@babel/plugin-transform-typeof-symbol`

  This does nothing if `loose: true` in the `@babel/preset-env` options:

  https://github.com/babel/babel/pull/6831

**Comment by XhmikosR** [comment]
Thanks for the reply!

It doesn't seem that the transpiled spread code is 100% the same though. It seems without `@babel/plugin-proposal-object-rest-spread` in plugins, babel is extending Object.assign. https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#loose

Not sure if there is any issue.
