### ISSUE TITLE
Glyphicons show up as random native emoji on Safari in poor network conditions

### ISSUE THREAD

**Issue by monstermac77** [twbs/bootstrap#31010]
Today my co-founder alerted the rest of the development team that she saw a monkey emoji on our production web app. It was pretty late in the day and we were all pretty exhausted from an iOS app update we were pushing (not to mention nobody had touched the web app code in weeks) so we were all heavily inclined to believe she had completely lost her mind.

Nevertheless, we spent 40 minutes trying to reproduce it on her and our iPhones. We opened the page in private browsing mode, turned on/off WiFi, visited the pages she had visited before our page in case some sort of memory was leaking between tabs. Nothing. Clearly, this was all monkey business.

But it kept bugging me. So I decided to try one last thing. As part of our iOS app update, we had been using our app under really poor network conditions using the [Network Link Conditioner](https://www.natashatherobot.com/simulate-bad-network-ios-simulator/). Her phone was one of the test devices we had used, so I checked her settings and saw that somebody had forgotten to turn it off. I decided to try switching the speed from 3G down to Edge. I reloaded the page and there he was.

Where our `glyphicon-calendar` once was.

🐵 was staring back at me.

_Originally posted by @monstermac77 in https://github.com/twbs/bootstrap/issues/13485#issuecomment-642328180_

**Comment by razh** [comment]
- Glyphicons are a part of Bootstrap 3 which is no longer under active development.
- You can emulate this by [blocking requests](https://umaar.com/dev-tips/68-block-requests/) to `getbootstrap.ocm/docs/3.3/dist/fonts/*` at https://getbootstrap.com/docs/3.3/components/#glyphicons or by removing the `font-family: Glyphicons Halflings` rule.

Some possible solutions are:

- Using `<link rel="preload">` with the Glyphicons font so that browsers know to fetch the font file before they load & parse the Bootstrap CSS files:

  https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches

- Setting a `font-display` value so that browsers don't render the icons until the Glyphicons font file has loaded:

  https://css-tricks.com/font-display-masses/

**Comment by mdo** [comment]
Yeah we can’t help with this here for the above reasons. We’ve not maintained or developed v3 for quite some time.
