### ISSUE TITLE
dropdowns and checkboxes

### ISSUE THREAD

**Issue by dilyanpalauzov** [twbs/bootstrap#31032]
I want to create a dropdown with a checkbox and an associated label.

When the dropdown is shown (opened), and either the label is clicked, or the input/checkbox is clicked, two things shall happen: the checkbox is toggled and the dropdown is closed.

Please extend the examples at https://getbootstrap.com/docs/4.5/components/dropdowns/#forms so that they contain such use-case.

At https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic when the menu under “Weekly” (left from “Today” is clicked) the checkboxes have the desired behaviour, but I cannot achieve this with bootstrap.

**Comment by mdo** [comment]
Reduced test case from the latest in the docs shows this works: https://codepen.io/emdeoh/pen/VweKWQY. Please provide a reduced test case and more details in a comment or new issue and we can revisit if needed.

**Comment by dilyanpalauzov** [comment]
The provided codepen example does not close the dropdown, when the checkbox is clicked.

The example at https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic does close the dropdown menu, when the example is clicked.  I cannot minimal example, since the fuctionality is not provided.

**Comment by patrickhlauke** [comment]
this is additional functionality which is not part of bootstrap, and you'll have to code it for yourself (add additional function with JS that, when a checkbox is checked, the dropdown is closed programmatically)

i don't think we have an intention to somehow add this extra functionality as part of core bootstrap.

i think @mdo may have gotten confused here that the bug was about checkboxes not working in dropdowns, and may have missed the additional ask here.
