### ISSUE TITLE
[RFC] Remove blacklist and other oppressive terminology

### ISSUE THREAD

**Issue by core23** [twbs/bootstrap#31064]
I just stumbled opon the new [Bootstrap 5 alpha page](https://v5.getbootstrap.com/docs/5.0/getting-started/javascript/#sanitizer) and saw some words that could be improved to a more natural / tech specific wording, e.g. the `allowlist` and `blocklist` instead of `whitelist` and `blacklist`.

There are many projects that try to ban oppressive words from their code. This could be a great chance when releasing BS5

Refs: https://tools.ietf.org/id/draft-knodel-terminology-00.html, https://localheinz.com/blog/2020/06/12/black-lives-matter/

**Comment by patrickhlauke** [comment]
this was already on our planned list of changes (following the change from `master` to `main`). thank you for raising it nonetheless.

**Comment by core23** [comment]
Did not find the issue for this. So can i close this?

**Comment by patrickhlauke** [comment]
Leave it open. it's now cross-referenced from https://github.com/twbs/bootstrap/pull/31066 so once that's merged, it will auto-close this issue as well.

And no, there wasn't an open issue here about ... it was an internal list of planned changes the team was discussing. So no worries...this issue here just gave me a good "hook" to just go ahead and do my PR :)
