### ISSUE TITLE
Add scrollbar utility

### ISSUE THREAD

**Issue by aswinkumar863** [twbs/bootstrap#31100]
I'd suggest adding scrollbar utilities. 

Firefox supports `scrollbar-color` and `scrollbar-width` properties since `v64`. 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars

Webkit offers even more customization.
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

```
.scrollbar-thin {
    scrollbar-width: thin;
    scrollbar-color: #c1c1c1 #f5f5f5;
    scroll-behavior: smooth;
}
.scrollbar-thin::-webkit-scrollbar{
    width: 6px;
    height: 6px;
    background-color: #f5f5f5;
}
.scrollbar-thin::-webkit-scrollbar-thumb{
    border-radius: 10px;
    background-color: #c1c1c1;
}
.scrollbar-thin::-webkit-scrollbar-thumb:hover {
    background-color: #9d9d9d;
}
```
I hope this utility would make a scrollable sidebar and modal a little concise.

**Comment by aswinkumar863** [comment]
Here's the example on CodePen, https://codepen.io/aswinkumar863/pen/NWxgqRw

**Comment by MauricioHernanCabrera** [comment]
wooow it is a great feature. If are you interested. I can do a pull request with this feature @aswinkumar863

**Comment by aswinkumar863** [comment]
You can @MauricioHernanCabrera. But I don't get any comment about this feature from the bootstrap team.

**Comment by MauricioHernanCabrera** [comment]
> You can @MauricioHernanCabrera. But I don't get any comment about this feature from the bootstrap team.

okasss

**Comment by ffoodd** [comment]
There's almost [no browser support](https://caniuse.com/#feat=css-scrollbar) in [our targetted browsers in v5](https://github.com/twbs/bootstrap/blob/ed9c481ef4b018f77ebc5108071f2e92e6e8ea1a/.browserslistrc):
1. Firefox implements CSS WG standardized properties since 64, but we currently support above 60;
2. WebKit & Blink browsers support non-standards pesudo-elements, the spec going to properties and not pseudo-elements…
3. Edge Legacy has no support at all;
4. all those implementations are buggy: Firefox does not support some values, iOS Safari can not make it work in WebView, etc.

Those properties clearly don't meet our requirement to be added as utilities in v5, as of now. I'll keep this open for further discussions–and keep an eye on this for v6?

**Comment by mdo** [comment]
Closing for now given this is _maybe_ something we’d do in v6.
