### ISSUE TITLE
Use a custom domain for the Slack invitation page

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31390]
`https://bootstrap-slack.herokuapp.com/` should be changed to `https://slack.getbootstrap.com/`.

**Comment by XhmikosR** [comment]
I remember I tried that in the past and I had trouble with Heroku's SSL. Not that it affects production since Cloudflare is behind, but still. Plus we'd need to redirect in the express app to our custom domain.

I'm not sure it's worth it, but if someone has instructions that works out of the box for our setup, I could give it a go.

1. We use Cloudflare
2. The bootstrap-slack code can be found here: https://github.com/emedvedev/slackin-extended

**Comment by mdo** [comment]
Closing as a won't fix.
