### ISSUE TITLE
V5 Modal: Illegal invocation

### ISSUE THREAD

**Issue by ivarlovlie** [twbs/bootstrap#31447]
When showing modals, selector-engine.js throws an error resulting in the modal not showing.

The error differs between Firefox and chrome but the result is the same.

This code was working fine 05.08 but today it is not.

 - macOs 10.15
 - Firefox 79
 - Chrome 78

not working: https://codesandbox.io/s/elated-bhaskara-rbhlx?file=/index.html
working with 4.5.0 and Jquery: https://codesandbox.io/s/elated-bhaskara-rbhlx?file=/working.html

**Comment by Johann-S** [comment]
Hi @ivarlovlie,

That's because your modal do not follow our modal html structure. Your modal must contain a `.modal-dialog` element.
https://v5.getbootstrap.com/docs/5.0/components/modal/#modal-components

See this working example: https://codesandbox.io/s/morning-silence-t2b0j?file=/index.html

**Comment by gregbown** [comment]
@Johann-S In my case I was dynamically rendering the modal dialog into the .modal container and getting the reference to the .modal container prior to this render, so I believe when bootstrap uses find to locate the .modal-dialog it was failing this same way despite being rendered since the original reference did not have the child.  Thank you for your help and direction here
