### ISSUE TITLE
Dropdown in the header in mobile view 

### ISSUE THREAD

**Issue by AdityaSharma911** [twbs/bootstrap#31456]
The list in the header **doesn't render all the items in one go** and themes isn't fully shown. This can be enhanced by adding a dropdown while switching over to the mobile view.

![bootstrap mobile](https://user-images.githubusercontent.com/55270982/89735115-d3f46d80-da7d-11ea-9133-e66446c27de4.JPG)

**Comment by Deckluhm** [comment]
Just like the Github nav, it's (horizontally) scrollable so I guess it's not a bug but an UI/UX choice.

The first time I saw that kind of UI, I also thought it was a bug (it's kinda weird visually) but I have to admit it works.

**Comment by AdityaSharma911** [comment]
Yes, I agree this looks kind of weird and annoying because both bootstrap CDN and bootstrap studio provide custom layouts with toggle button dropdowns.
![sup](https://user-images.githubusercontent.com/55270982/89741617-4a11c800-dab0-11ea-97d7-e23312b73fa8.JPG)

**Comment by herbalite** [comment]
IMO the hamburger design could do with a better UI/UX design, especially for a navbar.

To see what I mean insert the navbar at the bottom of a document. Since it is a collapsible, browsers will be forced to extend the page height. Meaning the user will have to scroll down the screen to see the expanded link list.

Additionally if the navbar has dropdown menues they must be included as dropups when positioned at the bottom. That's all fine, but for whatever reason, after being expanded from the hamburger button the dropups behave like dropdowns. Meaning yet another round of scrolling for the user. Not sure if that is a UI/UX design flaw or a programming bug in Bootstrap.

In any case the hamburger navbar design has some serious restrictions.

**Comment by mdo** [comment]
We have plans to redo the header navigation, but for now, it's behaving and looking as intended :).
