### ISSUE TITLE
fixed-top margin err

### ISSUE THREAD

**Issue by bghuan** [twbs/bootstrap#31462]
fixed-top + container + body{overflow:overlay;}      ->          margin-left error
windows 10
chrome 84.0.4147.125/Microsoft Edge 84.0.522.58
https://www.buguoheng.com/b5.html

**Comment by bghuan** [comment]
![20200811085858](https://user-images.githubusercontent.com/37129521/89845975-862d5180-dbb2-11ea-9c9c-22b0d36efd17.png)

**Comment by Deckluhm** [comment]
`overflow: overlay` is deprecated according to MDN (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#Values) so I'm not sure this is something which is going to be fixed.

Also, since this is your first Github issue, just a friendly advice: next time your open an issue, try to describe/explain the issue more. The example you provided is helpful but it was pretty hard to understand what the problem was without a short description.

**Comment by mdo** [comment]
Closing per above comment.
