### ISSUE TITLE
Include responsive column gutters in v5

### ISSUE THREAD

**Issue by samwilliscreative** [twbs/bootstrap#31499]
Often I want to create a grid that has gutters that shrink down for smaller screen sizes. Currently, I have to manually add each responsive gutter class to each row individually. It would be nice if these responsive gutter classes could be automatically added to columns at their respective breakpoints.

**Comment by mdo** [comment]
I don't think we'd go this route and add more classes for that. Using Sass mixins or extended the classes in your own sounds like it could be the best path forward.

/cc @twbs/css-review for thoughts

**Comment by MartijnCuppens** [comment]
We actually already have that 😄
https://twbs-bootstrap.netlify.app/docs/5.0/layout/gutters/#row-columns-gutters (see `g-2 g-lg-3`)

**Comment by samwilliscreative** [comment]
@MartijnCuppens yes I have seen that, but my ask is for there to be a way for those responsive gutters to be added automatically to rows and columns, similar to the default gutter size.

**Comment by ffoodd** [comment]
> It would be nice if these responsive gutter classes could be automatically added to columns at their respective breakpoints.

I think what's being asked for is to modify gutters on columns depending on breakpoints—to avoid relying on utilities—probably by using breakpoints mixins in `make-row` to change`--bs-gutter-x` for each breakpoint.

@samwilliscreative I'm not in favor of this because we don't modify spacers either depending on breakpoints: modifying gutters would result in inconsistent spacings everywhere…

Since gutters are custom properties in v5, it's pretty easy to customize even when using Bootstrap CDN. So I don"t think there's a point here.

BTW, maybe spacers could end as custom properties too?

**Comment by mdo** [comment]
Closing since we're passing on this change given our grid utilities.
