### ISSUE TITLE
v5: Improve customization by allowing manually setting calculated variables in styles

### ISSUE THREAD

**Issue by ydmitry** [twbs/bootstrap#31538]
Hello!

We can have cases when we need to change specific style property, but we can't do this because this property value set up in Bootstrap library as calculated formula. The idea is to create separate variables for these cases and precalculate it in default values of these variables.

The same was done in this issue and PR, but only for button component:
https://github.com/twbs/bootstrap/issues/28899
https://github.com/twbs/bootstrap/pull/29444

The idea is to follow this practice in all components.

### Example

Before:

```
@mixin list-group-item-variant($state, $background, $color) {
  .list-group-item-#{$state} {
    // ...
    background-color: darken($background, 5%);
    // ...
  }
}
```

After:

```
@mixin list-group-item-variant($state, $background, $color, $background-hover: darken($background, 5%)) {
  .list-group-item-#{$state} {
    // ...
    background-color: $background-hover;
    // ...
  }
}
```

The same can be done not only for colors, but for calculated unit values:

Before:
```
.card-subtitle {
  margin-top: -$card-spacer-y / 2;
}
```

After:
```
// In variables:
$card-subtitle-spacer: -$card-spacer-y / 2 !default;

// In styles:
.card-subtitle {
  margin-top: $card-subtitle-spacer;
}
```

### Benefits

- Allows to customize more properties and if you don't need - just keep default calculation of the value
- Allows to transform it to CSS variable usage by setting e.g. `$background-hover: var(--bs-background-hover);` (if we have `background-color: darken($background, 5%);` we can't do this)

### Drawbacks

- More variables to support
- Longer migration guide (probably) 

What do you thik about this? Should I do a PR?

**Comment by MauricioHernanCabrera** [comment]
I can do that!

**Comment by ydmitry** [comment]
Thank you :) . What about to do it as a rule for all scss styles? The original feature request to have this as styleguide rule and apply it everywhere, not only for list group and card subtitle

**Comment by ffoodd** [comment]
@ydmitry That sounds great indeed. It may require to think our variables organization again—and probably to document each components' variables too, as already requested several times…

Any thoughts, @mdo?

**Comment by MauricioHernanCabrera** [comment]
> Thank you :) . What about to do it as a rule for all scss styles? The original feature request to have this as styleguide rule and apply it everywhere, not only for list group and card subtitle

if you want, I can work on that

**Comment by mdo** [comment]
Been trying to find the best way to review these PRs, and I think overall most of the changes feel over-engineered.

Take popovers (#31756) for instance—you've added variables for different arrow sizes for the four sides, but why would you ever have a popover-right be different than a popover-left?

In other situations like alerts (#31753), you've added new global feature flags (with a different syntax and place in our `_variables.scss` file) for things that don't need to be an option. We're moving to CSS custom properties slowly but surely—we shouldn't enable flipping between them, but bridging Sass and custom properties. I can understand improving the mixin parameters, though.

https://github.com/twbs/bootstrap/blob/a6156ede326efe682935fa148d96d6e5772027e1/scss/_alert.scss#L43-L51

The parameters there could easily seem random and not so well formatted.

Form validation (#31757) seems like a straightforward enough improvement to the mixin. I don't think the focus styles need a parameter, but otherwise I think this is a helpful iteration. Needs a rebase and some docs improvements, though.

With list groups (#31758), the improvements to the mixin itself are helpful, but I feel like we should drop the changes you've made to the `_variables.scss` and `_list-group.scss`. No need to change how we generate our variants IMO.

Similarly, your altnerate alerts PR (#31789) over complicates the improvements to the mixin and added customization docs with an added global option for the variants and unnecessary map-merge.

---

Long story short, this needs to be rethought. I can see a few things potentially coming out of this in smaller PRs:

- Improved mixins with additional parameters for all states. Maybe start with the alerts mixin for now?

- It could be nice to at least add variable/map reassignment from `$theme-colors` to `${component}-variants` instead of global toggles. This way you could modify, extend, or disable all of a component's variants.

  For example (and I'm not 100% if this would work):

  ```scss
  // Bootstrap default
  $alert-variants: $theme-colors !default;

  // Remove some variants
  $alert-variants: map-remove($alert-variants, "info", "light", "dark");

  // Remove all variants
  $alert-variants: null;
  ```

- When adding new variables, don't over complicate. With stuff like popover arrows, all arrows should be the same size, so we only need one variable. In many cases, the abstraction and reassignment is honestly probably a better experience because it reduces overhead.

Hope that helps! Happy to keep discussing here to not further waste any time or effort—I appreciate the contributions so regardless of their status :).

**Comment by ydmitry** [comment]
@mdo  thank you for your feedback! Actually created more pull requests to have better preview and stress test the idea and get more feedback

> Take popovers (#31756) for instance—you've added variables for different arrow sizes for the four sides, but why would you ever have a popover-right be different than a popover-left?

I see two use cases for customization on product side:
1. I want to switch to CSS variables mode for popover sizing in different places or for theme switching. Currently I can't do this because there are SCSS formulas. 
2. I want to `null` not needed "arrows" to decrease CSS bundle size. E.g. I'm creating banner and want only styles I use.
We can actually try to avoid SCSS formula and keep "right" and "left" with one variable.

> It could be nice to at least add variable/map reassignment from $theme-colors to ${component}-variants instead of global toggles. This way you could modify, extend, or disable all of a component's variants.

For this case sometimes you have a mockup with exact colors for simple state, for hover, active, etc. And this can't be matched with formulas, so if we use just `$alert-variants` as e.g. `"info", "light", "dark"` we will be constrained with these formulas e.g. `scale-color($value, $alert-bg-scale)`

Regarding this https://github.com/twbs/bootstrap/pull/31708 - it is more about CSS variables handling, actually SCSS variables too, could you please check discussion there and in https://github.com/twbs/bootstrap/pull/31708 ?

**Comment by septatrix** [comment]
I really like this idea though I think it will be most useful for colors (and therefore theming).
The majority of people is unlikely to tinker with margins.
Instead there is an abundance of people wanting to tweak and adjust colors.

Introducing this for parameters unrelated to colors is certainly nice however it needs to be carefully evaluated what properties are of relevance and as @mdo pointed out where some distinctions are over-engineered and superfluous.

Where I cannot wait for this feature however are colors.
Bundled with css custom properties this allows many great new opportunities while still being backwards compatible.
Many components calculate colors based on the SCSS color map and this map also gets exported as css variables.
However as lightening and darkening of these colors is necessary the components do not use the css variables themself.
Changing them therefore has no effect but they only grant the ability to match one's own css to the bootstrap colors.

Most variables are however already defined inside `variables.scss`.
Some of these are already exposed as css variables and actually used by components (tables, some gutters, breadcrumb divider).
Expanding the usage of this pattern seems to be a goal of the bootstrap authors and I expect more components to adopt this behaviour for v5.1 (as I do not expect any substantial features for the next beta(s)) as it is backwards compatible.
What I am really excited for however would the adoption of this pattern for colors.
This would enable many possibilities of changing things during the runtime (e.g. dark and light theme).

**Comment by mdo** [comment]
Revisiting this, what's our next steps with our beta status and beyond?

**Comment by ydmitry** [comment]
Personally, I'm still interested in these changes, I think better not to do this for sizes, only for colors and do small PRs as you said

If I'm only one contributor for this issue I need to know target dates for beta to check if I can contribute

**Comment by mdo** [comment]
Closing out this overall issue for now. Feel free to submit new PRs on a per-component basis so we can review, provided they don’t break backward compatibility.
