### ISSUE TITLE
Collapse animation is not smooth when toggled via a button within the "collapse" element

### ISSUE THREAD

**Issue by alexpls** [twbs/bootstrap#31554]
Bootstrap Version: 5.0.0-alpha1
Operating system: Windows 10
Browser: Firefox 80, Chrome 84

---

Hello,

I've noticed a case where the close animation for collapsible elements does not display smoothly:

### Repro

1. Visit this JSBin https://jsbin.com/xihawedasa/edit?html,output
2. Click the "Outer toggle" button to open the collapsible element
3. Click the "Inner toggle" button to close it

### Expected

1. The animation for closing the element displays smoothly

### Actual

1. It doesn't

### Notes

- This appears to be a regression since Bootstrap 4 ([discussion](https://github.com/twbs/bootstrap/issues/31554#issuecomment-688053415)).

---

If you consider this a bug, I'm happy to investigate what its cause is and open a PR to fix it.

Thanks for your awesome work on Bootstrap 😄

**Comment by ashishrathod95** [comment]
@alexpls hey have you tried changing the speed value or tried using external jQuery??

**Comment by alexpls** [comment]
Hi @ashishrathod95 - Boostrap 5 doesn't use jQuery, so I don't think adding it would help with anything. What do you mean by changing the speed value? It's [not an option for collapse](https://v5.getbootstrap.com/docs/5.0/components/collapse/) as far as I can see?

**Comment by marcomaiermm** [comment]
hi @alexpls i had the same "issue". The Bootstrap 5 documentation says that Bootstrap supports the  [prefers-reduced-motion media feature](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion). 
[https://v5.getbootstrap.com/docs/5.0/getting-started/accessibility/#reduced-motion](https://v5.getbootstrap.com/docs/5.0/getting-started/accessibility/#reduced-motion)

I simply added 

@media (prefers-reduced-motion: reduce):
{
    .collapsing
    {
        transition-property: height, visibility;
        transition-duration: 0.35s;
    }
}

to an additionally loaded css file.

**Comment by patrickhlauke** [comment]
ah, so when you say that it "doesn't display smoothly", do you mean it doesn't animate at all and just opens/closes in one go? if so then yes, it'll be the `prefers-reduced-motion` kicking in on your page. If a user has set that preference, I'd advise against just brazenly ignoring it and reenabling animations regardless though...

incidentally, if it is this, it's likely you changed your settings on your machine, maybe without realising it? https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/

**Comment by mznet** [comment]
@alexpls i've confirm the case on even my chrome and firefox on mac. So, i changed bootstrap version to v4 to check that this issue was a known issue but suprisingly, it worked well on v4.

**Comment by alexpls** [comment]
Hi @marcomaiermm @patrickhlauke - I don't think it's a case of `prefers-reduced-motion` kicking in, since the animation that plays when the element is expanded is smooth, as is the animation that plays when the element is collapsed by using a button _outside_ itself. It's only when the element is collapsed via a button contained within itself that the animation gets stuttery.

[Here's a video of the issue](https://streamable.com/kppwe9) - unfortunately video was only captured at about 30fps so the stuttery animation isn't as obvious as it is when you see it on a computer screen.

**Comment by alexpls** [comment]
@mznet that's interesting - you're right - the issue does not appear on Bootstrap 4!

I verified this by keeping the HTML in my repro exactly the same but switching out Bootstrap 5 to Bootstrap 4, and it works as expected, link here: https://jsbin.com/xihawedasa/1/edit?html,output

I'll update the issue description to highlight that it's a regression.

**Comment by patrickhlauke** [comment]
ah, thanks for the video @alexpls (i have my system set up with reduced motion, hadn't turned it off to check the original jsbin)

**Comment by mdo** [comment]
Checking the demo out from @alexpls, this looks smooth on my end in Safari, but does appear choppy in Firefox and Chrome. Anything significant change in v5's collapse, @Johann-S?

**Comment by Johann-S** [comment]
It looks smooth on my end too 😟 and no particular breaking changes here, maybe it's on the CSS part

**Comment by XhmikosR** [comment]
The properties collapse transitions are not the most performant ones, unfortunately. I think we have an issue about it, but I'm unsure how we can fix this properly, i.e. by using transforms, opacity etc, properties that are performant.

**Comment by GeoSot** [comment]
@alpadev I think,  this is related to #33845

**Comment by orware** [comment]
Good afternoon @GeoSot and @alpadev ,

I know Bootstrap 5.0.2 isn't released yet, but I went ahead and was reviewing some of the suggestions above (like @marcomaiermm's suggestion) but also tried bringing in the changes to the files made in #33845 manually to see if that might help (I'm not too familiar with all of the JS tooling so wasn't quite sure if when I ran gulp after bringing in the changes manually to the src files in my node_modules directory if it did integrate in the changes as expected...in any case, for my particular webapp it actually seemed to feel a bit worse afterwards, but take that with a grain of salt and I can retest after 5.0.2 is officially released).

The issue I am having though related to this item is that I have large amount of HTML output being displayed in a webapp I am currently working on, which is an upgrade to an older webapp I had built back in 2013. I believe I ran into this same issue back then as well since I have a lot of instances of collapse on the page and I simplified the approach then to use a more basic hide/show option instead, but on the new version I wanted to make use of the Collapse plugin (since it had some of that extra ARIA support built-in mainly), but I'm currently struggling a bit with the overall performance since it performs fine on a page with less output, but performs much worse on the pages with more output (currently testing in Chrome...however, I just pulled up the page in Firefox to compare and it appears to be much more performant...additionally, on my iPhone the performance is a  lot better and more "normal" feeling as well, so at the moment it appears to be that Chrome is the least performant out of the 3).

If you'd like to example the issue in action, I can share the publicly accessible URL of the webapp to test (although I'd prefer not to advertise it here out in the open) but if you can drop me a quick email (shown on my GitHub profile) I can share that with you privately. 

Overall, I'm a bit surprised at the moment at how performant Firefox is compared to Chrome right now for this particular situation so I'm not exactly sure what would be the difference here that would amount to such a substantial difference.
