### ISSUE TITLE
[Utilities][Opacity] Add opacity classes

### ISSUE THREAD

**Issue by PululuK** [twbs/bootstrap#31592]
Easily change the opacity of elements with the opacity utilities.

This can be very useful in some context, for example : 

```html
<section class="module-list {% if not hook['active'] %} opacity-50 {% endif %}"> 
```
Instead of : 

```html
<section class="module-list" {% if not hook['active'] %} style="opacity:50%" {% endif %}> 
```

I can provide a PR if you are interested in this feature.

 - opacity-10     => opacity:10%
 - opacity-20     => opacity:20%
 - opacity-30     => opacity:30%
 - opacity-40     => opacity:40%
 - opacity-50     => opacity:50%
 - opacity-60     => opacity:60%
 - opacity-70     => opacity:70%
 - opacity-80     => opacity:80%
 - opacity-90     => opacity:90%
 - opacity-100   => opacity:100%

**Comment by MauricioHernanCabrera** [comment]
I can do that @PululuK

**Comment by PululuK** [comment]
> I can do that @PululuK

Yes please ! Thank you man

**Comment by juhas96** [comment]
Hey I want to contribute on this issue.

**Comment by NeOMakinG** [comment]
I'm against it on this project (not even because of my own advice, but because this project is not globally following this workflow at all, and it means that we'll mix 2 different patterns).

Sometimes you'll have to go through scss files in order to modify some styles, and sometimes you'll have to go to twig files in order to modify some styles, this could make the project harder to maintain. If you are working on a certain component style, and you want to modify his opacity on a specific state, you'll have to go to a twig file, you'll have to modify some markup (which could include breaking changes), instead of only modifying a single line, on a single state selector of this component !

**Comment by PululuK** [comment]
> I'm against it on this project (not even because of my own advice, but because this project is not globally following this workflow at all, and it means that we'll mix 2 different patterns).
> 
> Sometimes you'll have to go through scss files in order to modify some styles, and sometimes you'll have to go to twig files in order to modify some styles, this could make the project harder to maintain. If you are working on a certain component style, and you want to modify his opacity on a specific state, you'll have to go to a twig file, you'll have to modify some markup (which could include breaking changes), instead of only modifying a single line, on a single state selector of this component !

This request has nothing to do with the template engine you are using.
The idea is to do something like : 
`<section class="opacity-50"`>  Instead of : `<section style="opacity:50%"> `

**Comment by NeOMakinG** [comment]
Damn, I just seen that we were on the bootstrap repo 🤦 

This is not related to my message then...

sorry :)

**Comment by PululuK** [comment]
> Damn, I just seen that we were on the bootstrap repo facepalm
> 
> This is not related to my message then...
> 
> sorry :)

Ok ! don't worry @NeOMakinG  !

**Comment by mdo** [comment]
Closed for now per attached PR. Not seeing too much interest here and these can easily be added via the API.
