### ISSUE TITLE
[reboot] button: border-radius: 0; destroys native styling

### ISSUE THREAD

**Issue by leeoniya** [twbs/bootstrap#31603]
https://github.com/twbs/bootstrap/blob/d79ffeceeaef6c829dee1bd4bc87bd8febae243a/scss/_reboot.scss#L401-L407

messing with `border*` (and sometimes `background*`) properties of form controls usually causes them to become un-styled. the above code which fixes a minor annoyance in macOS causes far bigger problems in at least Firefox and Chrome on Windows and Chrome on Android. i've had to work around this by adding `button {border-radius: revert}` to undo the damage, but obviously this is not an ideal situation.

still scratching my head how this made it past QA ¯\\_(ツ)_/¯

repro: https://jsfiddle.net/hLuj1xp4/

Windows 10, Firefox:

![button-border-radius-firefox](https://user-images.githubusercontent.com/43234/92293619-8e935680-eeea-11ea-8719-f212d1171e55.png)

Windows 10, Chrome:

![button-border-radius-chrome](https://user-images.githubusercontent.com/43234/92293620-8e935680-eeea-11ea-8a20-f8bc73463d16.png)

Android 7.1, Chrome:

![Screenshot_20200904-201256_1](https://user-images.githubusercontent.com/43234/92293712-40cb1e00-eeeb-11ea-9b69-c8b98ef4dd49.png)

**Comment by neralex** [comment]
With Bootstrap 4 you can use the btn and rounded classes, which works on all supported browsers:

```<button class="btn btn-primary rounded-0">Button</button>```

https://getbootstrap.com/docs/4.5/utilities/borders/#border-radius

**Comment by leeoniya** [comment]
the only part of bootstrap which i use is reboot (as a css reset), so that's not gonna work. i have no issues with adding the `revert` rule in my code. my point is that `border-radius: 0` needs to move out of `reboot` and into perhaps the base `.btn` class.

**Comment by mdo** [comment]
Reboot intentionally resets many elements to a preferred styling ahead of Bootstrap's components, layout, and more. I don't see a reason to remove this at this time.

**Comment by mdo** [comment]
Thoughts @twbs/css-review?

**Comment by ffoodd** [comment]
Might we only drop it when `$enable-rounded` is `false`—like we do for `text-decoration` on links?

**Comment by patrickhlauke** [comment]
i'm split on this. can see the rationale that reset should not change too much of the stuff outside of bootstrap-specific classes. but then again, it is more a normalisation than a simple reset. would also say that it's rare that designers actually *want* the platform/browser specific styles, unless they're very specifically aiming to blend in/make it look pseudo-native (though browsers themselves don't always adhere to platform conventions themselves, so they get weird results either way).

i'd say since reset has always done more than merely reset/paper over some very odd quirks, and instead sets a baseline level of (idiosyncratic in their own right) styles, we should probably leave it as is now. and not switch it based on `$enable-rounded` either, as the jump from "yes i want round corners" to "now the corners are not round, and OMG what's that windows 95 looking chunky button with giant 3D bevel?" is a bit too big.

**Comment by leeoniya** [comment]
another option is to set some minimal additional border and background properties that are at least less windows 95 and also *more* normalized than simply allowing the non-uniform uncontrolled uglification to take place.

**Comment by mdo** [comment]
Does adding `border: 1px solid` (without a color) solve the issue enough? I’d prefer not to add too many extra properties since we have our `.btn` styles.

**Comment by mdo** [comment]
Closing as a won’t fix for now.
