### ISSUE TITLE
Spinner Vertical Alignment in Button

### ISSUE THREAD

**Issue by hashnimmo** [twbs/bootstrap#31915]
I have a button with a spinner but by default, the spinner doesn't look like it's really vertically centered inside the button. With the text, it appears like the spinner is somewhat below the text. What am I missing here?
```
<button type="submit" class="btn btn-outline-primary" name="send" id="send" disabled>
<span class="spinner-border spinner-border-sm" role="status"></span>
Sending...
</button>
```
![spinner-not-aligned](https://user-images.githubusercontent.com/24617729/96362780-53bd4900-114d-11eb-82f1-35004d9c1e41.png)

I'm using;
Bootstrap: Version 4.4.1
Operating system: Microsoft Windows 10 Version 2004 (OS Build 19041.508) 64-bit
Browser: Microsoft Edge Version 86.0.622.43 64-bit

**Comment by hashnimmo** [comment]
Solved it by using `d-flex` utility:
```
<button type="submit" class="btn btn-outline-primary d-flex align-items-center" name="send" id="send" disabled>
<span class="spinner-border spinner-border-sm mr-2" role="status"></span>
Sending...
</button>
```
![spinner-aligned](https://user-images.githubusercontent.com/24617729/96365245-bec24c00-115c-11eb-80b7-97be498d3be1.png)

I will just leave this issue open for the developers to decide.

**Comment by mdo** [comment]
Yeah this is a slightly annoying one for us because of the font-rendering differences across operating systems. Windows' main font sits so low compared to Apple's and others. Using the utilities to improve alignment feels like the best answer and option here unfortunately. We can't set all our buttons to be flex containers, so not sure what else we can do here.

Closing out as a won't fix for now, but I'm open to further ideas if folks have them! If someone also wants to add a note to the docs, I'd happily review a PR.

**Comment by hashnimmo** [comment]
Thank you for that detailed clarification.

> Using the utilities to improve alignment feels like the best answer and option here unfortunately.

Yes and always, clean, simple, and ideal to use the default [utilities](https://getbootstrap.com/docs/4.4/utilities/flex) before anything else.

**Comment by musapinar** [comment]
+ ```justify-content-center``` instead of ```align-items-center``` AFAIAC
