### ISSUE TITLE
Improve default behavior of toast (z-index issue)

### ISSUE THREAD

**Issue by guldi011** [twbs/bootstrap#31977]
Issue: Toasts are per default covered by other html elements (to which I see not one reason).
What is the reason for this usless default setting ? every user needs to "dive into the depths" of the CSS and fix the broken code ?
I read your comment about users responsibility, but for other features you make great / working default settings (and thank you so much for this !).
The behaviour is on all tested browser (see below) identically (html elements cover the toast) with the expeption of Chrom but only under Win10 (chrom 86.0.4240.111). Under chrom I only found h1 elements covering the toast on my code.
I suggest also changing the alpha value to 1.0 as default since you use white as bg. Alpha 1.0 seems to be the logical setting for the default white bg (to me), I could not see a difference with chrome / FireFox or Edge under win10 when playing with the white alpha number.
One may argue about may z-index value proposal of 1.0. Maybe I missed an element which is still higher.

Bug reports must include:

- Tested OS / Browsers: Win10 1909 (FireFox 82.0, Edge 86.0.622.51), iOS (Safari), Android (chrom, Samsung web, different versions) 
- code situation leading to bug: I used the code from the doc (ver 4.5) respectively the .js / .css files 

Solution:
Change the .toast and .toast-header class (update in bold text):

.toast {
  background-color: rgba(255, 255, 255, **1.0**);
  **z-index: 1;**
  **position: relative;**
}

.toast-header {
  background-color: rgba(255, 255, 255, **1.0**);  
}

I noted issue 27919 and 29924 but it's hard to understand why you leat "everyone" run in the same issue when the fix ist that easy ? Pls make the default work to get more people say thank to your great work.

**Comment by mdo** [comment]
> Toasts are per default covered by other html elements (to which I see not one reason).

No they aren't: https://codepen.io/emdeoh/pen/dyXvrqV. Unless you're talking about specific Bootstrap components that already have `z-index` set on them like dropdowns, navbars, modals, popovers, and tooltips.

> What is the reason for this usless default setting ? every user needs to "dive into the depths" of the CSS and fix the broken code ?

Every JS framework is different, so how you choose to render toasts is up to you. As such, it's up to you to decide where they should render as well. Good news is though we're adding some positioning options to the plugin in v5. See https://github.com/twbs/bootstrap/pull/28783.

>  suggest also changing the alpha value to 1.0 as default since you use white as bg.

The translucency is done on purpose. The `background-color` can be customized in our Sass via variable, or with a `.bg-*` utility class. It was previously paired with a background blur filter, but we removed it due to Safari bugs. Intent is to bring that back whenever the bug is resolved.
