### ISSUE TITLE
[Accessibility] NVDA is not reading modal popup as dialog

### ISSUE THREAD

**Issue by rmishra19** [twbs/bootstrap#32000]
NVDA is not reading modal pop as dialog. 
In the modal pop up component example with NVDA(https://getbootstrap.com/docs/4.0/components/modal/), I have following observation.
![image](https://user-images.githubusercontent.com/19684228/97528252-46b51b00-19d3-11eb-97ed-5d910bfab084.png)
While in following website NVDA reading modal popup as dialog.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

![image](https://user-images.githubusercontent.com/19684228/97533810-eb892580-19de-11eb-9cde-b4ca82eebd92.png)

**Comment by patrickhlauke** [comment]
That's a decision/choice by NVDA. It's not announcing the "dialog" part because focus was set to the dialog itself, which is a reasonable approach for modals that are not specifically form-based (where you'd send focus to the first element) but that can contain any type of content. But the correct `role` (and, in versions that are newer than Bootstrap 4.0, `aria-modal="true"`) are correctly present in Bootstrap's dialogs.

Still waiting for some more solid conclusions here https://github.com/w3c/aria-practices/issues/442 - but in short, the current behavior you're seeing is purely down to NVDA deciding not to announce the `role` that is actually there.

FWIW Jaws will announce the Bootstrap modal as a "modal dialog".
