### ISSUE TITLE
docs: Review necessarity of warning about customizing values form-valiation-state mixin

### ISSUE THREAD

**Issue by ydmitry** [twbs/bootstrap#32082]
Wanted to ask about phrase in the docs in `/site/content/docs/5.0/forms/validation.md`:

```
Please note that we do not recommend customizing these values without also modifying the `form-validation-state` mixin.
```

Should we keep this? Why need to modify a mixin? Seems should be OK now without modifying. What do you think?

_Originally posted by @ydmitry in https://github.com/twbs/bootstrap/pull/31757#discussion_r499489191_

**Comment by ffoodd** [comment]
I guess it's related to the pseudo-classes, which used to be generated even when it wasn't `valid` or `invalid` (resulting in invalid selectors). It's been fixed in #28447 1.5 years ago — and now outputs `.is-#{$state}` instead of ``:#{$state}`.

So the sentence you're pointing can be safely removed IMHO.
