### ISSUE TITLE
Button Remains Greyed Out after executing document.getElementById('button').removeAttribute('disabled')

### ISSUE THREAD

**Issue by JF0001** [twbs/bootstrap#32103]
I initially set the disabled attribute of a button in the html code upon loading the page as follows:
`<b-button id="button" type="button" disabled="disabled" v-on:click="function()">Button</b-button>`

Afterwards, upon clicking on another button, the following code is triggered in Javascript.
`document.getElementById('button').removeAttribute('disabled')`

The button does become clickable and is thus disabled. However, it remains greyed out, even if it actually is enabled. Shouldn't its colour also be changed automatically upon enabling it?

Thank you. J

**Comment by patrickhlauke** [comment]
Per the contributing guidelines, we need at least a [reduced test case](https://css-tricks.com/reduced-test-cases/) (e.g. on  [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)) that shows the problem.

Based on what you added to the issue, it also doesn't look like Bootstrap is involved here at all? Likely the problem lies with whatever else you're using? https://github.com/bootstrap-vue/bootstrap-vue ?

**Comment by JF0001** [comment]
Yes, you are right, I am using bootstrap-vue. My apologies and thank you for your answer. JF
