### ISSUE TITLE
Bootstrap should have a color pallet like implemented in Tailwind CSS out of the box

### ISSUE THREAD

**Issue by rx5700xt** [twbs/bootstrap#32236]
For changing the color we should have classes like

red-100, red-200 till red-900 each class increasing the color strength .100 being the lightest red and 900 being the brightest

Similar color pallet must be developed for most colors included in bootstrap template out of the box and without any kind of sass or scss compilation. 
https://v5.getbootstrap.com/docs/5.0/customize/color/

**Comment by patrickhlauke** [comment]
personally no, not a fan of copying all this tailwind approach to "a class for every possible property and every possible value of that property"

**Comment by rx5700xt** [comment]
Its not copying but Bootstrap already has a color palette which should come default out of the box..:)
https://v5.getbootstrap.com/docs/5.0/customize/color/

**Comment by rexarvind** [comment]
just create on your own, like this

```
.bg-grey-100{background-color:#F3F4F6}
.bg-grey-200{background-color:#E5E7EB}
.bg-blue-50{background-color:#EFF6FF}
.bg-teal-50{background-color:#F0FDFA}
.bg-teal-700{background-color:#0F766E}
.bg-teal-800{background-color:#115E59}
```

**Comment by mdo** [comment]
I mean, we could definitely do this, and encourage folks to use PurgeCSS on top of Bootstrap, but I feel like most folks wouldn't take that step. I've opened #32319 to document some kind of approach here.

**Comment by ADDISON74** [comment]
I got this post as result by searching on the web for colors tailwind bootstrap. Someone already implemented the idea in Bootstrap here: https://www.youtube.com/watch?v=0J_e_7QQ-uU.

In the last months I played with Tailwind CSS and one thing I liked very much. I can do fast than ever all CSS stuff inside the HTML skeleton without using a separate CSS file (padding, margins). I created projects with Bootstrap since 2013 and my personal opinion is that the color pallet is limited. Tailwind understood this issue and added this feature. Of course we can create this pallet in a separate CSS but at that moment the idea of -primary -secondary is useless. Flexibility should be a prior in using colors for button, background, text and many more.

**Comment by patrickhlauke** [comment]
>  I can do fast than ever all CSS stuff inside the HTML skeleton without using a separate CSS file

good for you. however, this fundamentally goes against the feelings of many other folks who like to build things with a separation of concerns / maintainability...

**Comment by ADDISON74** [comment]
Thank you for your reply. My message was intended to draw attention to an issue discussed here and inform you there are solutions already out there. The fact I am using BS for almost 8 years says a lot about my loyalty to this project.
