### ISSUE TITLE
Dropdown-item error with external link when using Scrollspy.

### ISSUE THREAD

**Issue by jeijei4** [twbs/bootstrap#32273]
Hello!
I am using Bootstrap 5.0.0-alpha3.
```html
<li><a class="dropdown-item" href="https://duckduckgo.com/">other</a></li>
```
Using <b>Scrollspy</b> I added in a dropdown a <b>dropdown-item</b> that contains a link to an external page (https://duckduckgo.com/) and I get an error in the console.

The error occurs on the following line:
https://github.com/twbs/bootstrap/blob/c63aebc86ba05f0ebb420add653b80804c6a0cff/dist/js/bootstrap.bundle.js#L96-L102

If the selector variable is equal to some external link such as "https://duckduckgo.com/", the following error occurs:

```diff
- 'https://duckduckgo.com/' is not a valid selector
```

My proposal is to enclose it in a try catch:
```js
  var selector = getSelector(element);

  try {
    return document.querySelector(selector) ? selector : null;
  } catch (_) {
    return null;
  }
```

Operating system: "windows 10";
Browser and version : {"Firefox":"83.0", "Microsoft Edge":"87.0.664.47"};

A reduced test case [here](https://jsfiddle.net/vj6x5ek2/5/).

**Comment by XhmikosR** [comment]
We actually do that in v4 https://github.com/twbs/bootstrap/blob/8e59752ee1f815bbc30a06465b8d19de35a76c9d/js/src/util.js#L81-L94

@Johann-S I remember we changed this in v5 on purpose, but how about this use case?

**Comment by RoflCopter24** [comment]
[5.0.0-beta1] Dropdown in navbar.
Unfortunately this happens with any href that is not an element id and therefore kills the whole menu script. I would also like to see this selector error caught. It also happens, when the dropdown toggle in a navbar has a 'real' url.

In my case the CMS outputs a valid href in the dropdown toggle link instead of a simple `#` and I am not sure why the href is used as a selector at all in this case.  Is there any case where the dropdown toggle is not inside the `.dropdown` container element and might require the use of the href as a selector?

`<a class="nav-link dropdown-toggle" href="vorsorge/beratung" itemprop="url" rel="nofollow" title="Vorsorge" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span itemprop="name">Vorsorge</span></a>`

**Comment by XhmikosR** [comment]
We should probably restore the v4 behavior. The use case seems to be a valid one.

PRs welcome!

**Comment by RoflCopter24** [comment]
@XhmikosR I would like to tackle this in a pull request. 

However before I set foot on the wrong path, do you agree that the assumption in this test might be a contributor to the problem? I don't think that a class name (`href=".target"`) is valid in a href attribute per spec (see https://www.w3schools.com/tags/att_a_href.asp for example):
https://github.com/twbs/bootstrap/blob/86802f701cdff9a2fe91278fe42684a32426bc61/js/tests/unit/util/index.spec.js#L49-L53

I would only consider an anchor `#example` as a valid selector in an href attribute. What do you think?

Then this issue would be easily preventable by adding something like this
```javascript
if (!hrefAttr || !hrefAttr.includes('#')) {
      return null
}
```
to
https://github.com/twbs/bootstrap/blob/86802f701cdff9a2fe91278fe42684a32426bc61/js/src/util/index.js#L35-L45

**Comment by rohit2sharma95** [comment]
Dropping support for the class selector in href would be a breaking change, so it is better to keep it for now. :slightly_smiling_face:

**Comment by kevinramharak** [comment]
Is this going to land in  `5.0.0-beta2`? The PR seems to have an open review. I would agree with the PR that a class selector should be an invalid `href` attribute value. That is what `data-bs-target` is for.
