### ISSUE TITLE
.visually-hidden-focusable should also apply to :focus-within

### ISSUE THREAD

**Issue by septatrix** [twbs/bootstrap#32370]
Currently the `visually-hidden-focusable` class only shows elements which are directly focused.
It is however rather common to have a single hidden element which contains two or more anchors to skip to content, navigation, footer etc.

As it is right now this is rather cumbersome and requires manual styling/classes.
Changing the class to also show elements when the `focus-within` pseudo-class applies should not break things and simplifies this a lot.

The only cases where this would break stuff is if one was using nested focusable elements (e.g. a link inside a button - which I don't even know if something like that is allowed) **and** depends on the behaviour that focusing the element would hide and therefore unfocus both of them.

**Comment by ffoodd** [comment]
Even if I like the idea —I even implemented this on our own site, take a look at our skip links [on docs pages](https://getbootstrap.com/docs/5.0/getting-started/introduction/)— I can't see a way to add this without breaking things, in fact.

Say you use `:focus-within .visually-hidden-focus  { … }`, you'd make element appear for each focus in the page. Making it more spoecific, eg. `:focus-within > .visually-hidden-focus { … }`, you'd make the pattern very limited to direct children (thus preventing to use things like ou grid to layout things).

We may try to think around a new helper class dedicated to this, to allow a defined scope for this pattern (eg. `.focus-within-scope:focus-within .visually-hidden-focusable`) but its usage would be extremely limited… Probably only useful on skip links.

Even though I really like this CSS feature, I'm not quite sure there's a way to use it in our core and moreover, to make it useful.

I'd like to have your thoughts on this, you may already have a better approach to suggest or maybe some more specific use cases?

**Comment by septatrix** [comment]
I thought `.visually-hidden-focusable:focus-within` should work as it simply matches a superset of the current selector

**Comment by ffoodd** [comment]
So you'd want to apply this class on a container, alongside `.visually-hidden-focusable:focus`? I'm so used to apply the class on focusable elements I didn't thought about this, thanks :) 

Well, since [`:focus-within` is very well supported](https://caniuse.com/css-focus-within) that could be done this way, indeed. This would require some docs though—and I'd still be in favor of a new class name, since it's not doing the same job and could introduce some confusion.

However that doesn't answer my questions above: 
- it'll be triggered by anything having focus inside, so te be used very conscisouly,
- usage would really be restricted to skip links, I guess.

@patrickhlauke Would you have any insight on this?

**Comment by septatrix** [comment]
It would augment the current behaviour. Before it would have been nonsensical to apply the class to a container as you rarely make a whole container focusable by manually setting a `tabindex=0`. However another class also would not hurt.

**Comment by patrickhlauke** [comment]
i think keeping the same class wouldn't be a problem, as long as it's properly documented. giving this a whirl to see how it ends up...

**Comment by ffoodd** [comment]
I really like it, and as @septatrix said, there shouldn't be any side-effect if there's no nested focusable elements.
