### ISSUE TITLE
Breakpoint overriding creates media queries of default and overriden breakpoint size

### ISSUE THREAD

**Issue by denni-hill** [twbs/bootstrap#32426]
```
$grid-breakpoints: (
        xs: 0,
        sm: 456px,
        md: 789px,
        lg: 999px,
        xl: 1250px
);

@import 'node_modules/bootstrap/scss/bootstrap';
@import "node_modules/bootstrap-vue/src/index";
```
Code above causes creation of default breakpoints sizes and overriden ones with same class names inside. It displays as 2 media queries which are contain same class-names (example: d-xl-none). In cases when instruction contains !important keyword it causes unexpectable behaviour.

**Comment by mdo** [comment]
Confirmed this does happen in v4. That's odd though since there's no `map-merge` happening in v4.x for `$grid-breakpoints`. Can you confirm what version you're using?

**Comment by denni-hill** [comment]
This does happen in latest (4.5.3) bootstrap version

**Comment by ffoodd** [comment]
Don' know what's happening but might it concern `$container-max-widths` too, or any other map?

**Comment by mdo** [comment]
Realized this is caused by the variables being before the full import stack. This isn't a problem with some variables I believe, which is why If you want to modify Sass maps, you'll need to import functions, variables, and mixins _first_, then your custom code, and then the rest of the components. https://getbootstrap.com/docs/5.0/customize/sass/#remove-from-map

I think our docs will need some clarification for this.

**Comment by mdo** [comment]
As an example...

https://github.com/twbs/bootstrap-npm-starter/blob/852218ac314c4da58d70c7725b6675a4ec944cd1/scss/starter.scss#L13-L42

**Comment by mdo** [comment]
Opened #32795.
