### ISSUE TITLE
Checkboxes/switches go invisible temporarily when "held down" in specific situations

### ISSUE THREAD

**Issue by MasterEvilAce** [twbs/bootstrap#32441]
Operating System: Windows 10 64 bit
Browser: Chrome 87.0.4280.101 (Official Build) (64-bit)
(Does not happen in Firefox 83 64-bit)

Example case: https://jsfiddle.net/16v5n4cx/

When a Bootstrap switch or checkbox is in the second column of a list (ul or ol) it disappears during the toggle transition. If you hold the mouse button down on them, they will remain invisible until the mouse button is released.

The first time you click the checkbox, it is fine. Any clicks after that, it will disappear momentarily. You can hold the mouse button down to witness the element being completely invisible until you release the mouse button,

This only seems to happen when the element is in the SECOND column. This does not happen to checkboxes that are completely unstyled by bootstrap. This also does not happen in Firefox.

**Comment by XhmikosR** [comment]
It's a browser issue AFAICT. Firefox behaves normally here.

Not sure if there's something we could do @twbs/css-review?

**Comment by MartijnCuppens** [comment]
Seems to be caused by `column-count: 2`. We've encountered lots of rendering issues when using CSS columns (like our card columns in v4 https://getbootstrap.com/docs/4.5/components/card/#card-columns, which we removed in favor of the masonry plugin).

I would recommend using our bootstrap grid to create columns instead 😉
