### ISSUE TITLE
rtl Support for bootstrap 4.5

### ISSUE THREAD

**Issue by rosell921** [twbs/bootstrap#32518]
Dear Bootstrap
I work in a company and I have a new project to migrate bootstrap from ver3 to ver4, our website is bilingual so I need to migrate the rtl pages too, where can I find a reliable rtl framework or support for bootstrap 4.5 rtl

**Comment by ffoodd** [comment]
You may have a look at [RTLCSS](https://rtlcss.com)'s [fork of Bootstrap](https://rtlcss.com/cdn/css-frameworks/bootstrap/index.html).

Never used it before, but we're using RTLCSS to support RTL in v5—so that'd be my favorite suggestion. You may also want to skip v4 and get on v5 directly, but it'd be more ambitious (and maybe too much).

I close the issue since there's not much we can do, but feel free to comment again if you need.
