### ISSUE TITLE
Bootstrap 5 Beta 1 RTL support inside NPM

### ISSUE THREAD

**Issue by pixieaka** [twbs/bootstrap#32546]
Default import with LTR Bootstrap version is:
```
@import "~bootstrap";
```
How possible now to import RTL version without minified files.

_Regards, All the best Bootstrap Team._

**Comment by ffoodd** [comment]
Hi there,

I think you're asking about Sass imports. If so, you can't: sources are the same for both LTR and RTL. RTL dist files are post-processed from the LTR dist files.

If you want to work from our sources to output RTL files, you'll need to use RTLCSS as we do—just like other dependencies we use to compile our CSS (Autoprefixer, minification, etc.).

I hope that answers to your question?

Might be added to the docs!

**Comment by pixieaka** [comment]
@ffoodd I really appreciate your help.

I need to custom some variables like `$font-family-sans-serif` for example It's very important to RTL users to add RTL fonts with LTR fonts & some other variables.

I think two sources is better to work with same experience like LTR version.

**Comment by ffoodd** [comment]
This is [the exact example given in our docs](https://getbootstrap.com/docs/5.0/getting-started/rtl/#alternative-font-stack), did you read it? There's a whole section about customizing RTL from our sources.

IMHO we're only missing in the docs the requirements to build RTL dist files in a custom build from sources—but using alternative values, adding or removing properties or declaration blocks is really easy (and already documented) thanks to [RTLCSS](https://rtlcss.com/).

Having the same sources looked way more accurate and straightforward to us,  since our goal was to be able to use the same markup for both directions, and only switch CSS files. And with the help of RTLCSS, this is both easy to set up and a breathe to customize using their values and controls directives.

Feel free to comment, open issues (or even PR) if you have any insights on how to get things easier — and obviously if you find any bug or keep struggle on something.

**Comment by pixieaka** [comment]
@ffoodd Thanks for your explanation, I really appreciated.
