### ISSUE TITLE
Floating labels and select positioned with different padding on Firefox

### ISSUE THREAD

**Issue by ddneat** [twbs/bootstrap#32636]
While reading the documentation with the v5 examples, I noticed that the floating labels and select value are off. The following screenshot was taken from the documentation: https://getbootstrap.com/docs/5.0/forms/floating-labels/#selects

<img width="767" alt="Bildschirmfoto 2020-12-28 um 13 07 45" src="https://user-images.githubusercontent.com/4222309/103213494-1b38a900-490e-11eb-986c-476cdaa5c5a6.png">

- macOS 11.0.1
- Firefox 84.0.1

I could not reproduce this issue on Safari nor Chrome. My first investigation using the devtools and playing around with different paddings and font-sizes was unsuccessful.

Would you have any hints on resolving this issue? I would be happy to provide a PR.

**Comment by XhmikosR** [comment]
padding left/right of .5rem fixes the issue for me on Firefox but then it breaks on Chromium.

Not sure if it's a browser issue, but it looks like it.

**Comment by linhub15** [comment]
Material-UI also had this [issue](https://github.com/mui-org/material-ui/issues/8946).
Looks like Firefox is rendering `<select>` differently than other browsers.

This is also present in the normal `<select class="form-select">`

> ![image](https://user-images.githubusercontent.com/10420994/103464294-ca4ef900-4cef-11eb-968b-dff07d7bc005.png)


## Temporary Workaround
Add negative `text-indent` for Firefox.

```css
@-moz-document url-prefix() {
  .form-select {
    text-indent: -.13rem;
  }
}
```
Example: https://codepen.io/linhub15/pen/RwGMogY

**Comment by ddneat** [comment]
Thanks for your investigation and answers!

I would suggest to enhance the bootstrap reboot to resolve this issue? Probably the reboot should unify text-indent of all browsers by a fixed value.

What's your opinion? May I provide a PR?

**Comment by ddneat** [comment]
It seems like Safari has a similar issue with line-height https://github.com/twbs/bootstrap/issues/32672

**Comment by mdo** [comment]
Not seeing this issue in v84.0.2 on macOS 11.1.

<img width="1792" alt="Screen Shot 2021-01-09 at 2 21 42 PM" src="https://user-images.githubusercontent.com/98681/104109780-1537b600-5286-11eb-9058-7eba2f261c6f.png">

**Comment by mdo** [comment]
Looks like this might be documented as a Firefox bug already: https://bugzilla.mozilla.org/show_bug.cgi?id=1582545. Unsure if we implement the hack, or go with mentioning the bug? Thoughts @twbs/css-review?

**Comment by ffoodd** [comment]
Isn't this related to a fix @MartijnCuppens had for our new file input? I recall talking about a `-moz-` proprty related to left padding…

I’d be in favor of implementing the hack, however I'd change `padding` instead of an arbitrary `text-indent` (to make it obvious) with a link to the related bug.

**Comment by mdo** [comment]
I don't think so @ffoodd? At least I don't see anything for that in our CSS—might be missing something. I thought the issue was with vertical alignment and sizing, not horizontal.

**Comment by XhmikosR** [comment]
The issue is with horizontal alignment, and that Firefox has that extra padding compared to Chromium. IMHO we should add the hack if possible.

**Comment by ffoodd** [comment]
I confirm this is unrelated (found the comment tackling it ATT: https://github.com/twbs/bootstrap/pull/31955#issuecomment-716147361). 

However [`select > option` have `padding-inline-start: 3px`](https://searchfox.org/mozilla-central/rev/0b7007a23bc16c857f894140e12f307bfeef2fdd/layout/style/res/forms.css#364)  which might cause this? 

After a few tries, `padding` doesn't work, so I'd stick to `text-indent` as suggested. I'd go with `2px` as a value, since it perfectly matches and I deduced this from comments in linked source file: they add `3px`, taking a `2px` border into account; we set a `1px` border.

Turning this around, I didn't find a better way.

**Comment by alecpl** [comment]
`padding-inline-start: 0.5rem` on the select fixes it for Firefox, but breaks for Chrome. But `-moz-padding-start: 0.5rem` does the trick. This would have to be applied to both `.form-select` as well as `.form-floating > .form-select` because both cases are broken.

**Comment by alecpl** [comment]
The PR is assigned to v5.0.2, but this ticket to v5.1.0, please correct this.
