### ISSUE TITLE
.popover-header do not have default color

### ISSUE THREAD

**Issue by omoridi** [twbs/bootstrap#32804]
Hi,
Please add color to popover-header, if some parent node have any color, this header inherit from that.
`.popover-header
{
    color: ??;
}`

**Comment by mdo** [comment]
Yes it does.

https://github.com/twbs/bootstrap/blob/b5bf3131fb6170d3ad0485d18dda2c8f420658e0/scss/_variables.scss#L1096

https://github.com/twbs/bootstrap/blob/b5bf3131fb6170d3ad0485d18dda2c8f420658e0/scss/_popover.scss#L156-L168

It just doesn't compile because it's default value is set to `null` so it can inherit automatically.

https://github.com/twbs/bootstrap/blob/b5bf3131fb6170d3ad0485d18dda2c8f420658e0/scss/_variables.scss#L444
