### ISSUE TITLE
Customize sass variables not work in rtl mode

### ISSUE THREAD

**Issue by miladcatalan** [twbs/bootstrap#32816]
First problem: I can't import bootstrap's rtl to custom.scss
Second problem: I can't change default values of variables

**Comment by ffoodd** [comment]
Hi there.

You can't import RTL files to your Sass since there's no such thing in Bootstrap. We use a single Sass source, which outputs our LTR files, then run RTLCSS on it to compile their RTL counterparts.

RTLCSS allows customizations using comments block in the LTR sources, as [mentionned in our docs](https://getbootstrap.com/docs/5.0/getting-started/rtl/#customize-from-source).

We might be clearer on how to proceed, I guess: any suggestion is welcome.

**Comment by ffoodd** [comment]
I'm closing this but I added a mention in #32330 to see what can be done in our docs.
