### ISSUE TITLE
Error: CSS minification error:  Missed semicolon. File: my-file.css

### ISSUE THREAD

**Issue by tcastelly** [twbs/bootstrap#32873]
Hello,

I'm using VueJS with bootstrap. Since the version `4.6.0` I can't build anymore my application:
> Error: CSS minification error: /home/.../my-file.css:1:141721: Missed semicolon. File: my-file.css

Same behavior if I try to build with `sass` or `node-sass`.

I found a workaround by changing the order of `animation` values in `_progress.scss`.

```diff
diff --git a/scss/_progress.scss b/scss/_progress.scss
index b48ffc4b8..a3fbecf2b 100644
--- a/scss/_progress.scss
+++ b/scss/_progress.scss
@@ -34,7 +34,7 @@

 @if $enable-transitions {
   .progress-bar-animated {
-    animation: $progress-bar-animation-timing progress-bar-stripes;
+    animation: progress-bar-stripes $progress-bar-animation-timing;

     @if $enable-reduced-motion {
       @media (prefers-reduced-motion: reduce) {
```

same in `_spinners.scss`
```diff
diff --git a/scss/_spinners.scss b/scss/_spinners.scss
index 7444ed1d1..00bb01784 100644
--- a/scss/_spinners.scss
+++ b/scss/_spinners.scss
@@ -3,7 +3,7 @@
 //

 .spinner-border {
@@ -15,7 +15,7 @@
   border-right-color: transparent;
   // stylelint-disable-next-line property-disallowed-list
   border-radius: 50%;
-  animation: $spinner-animation-speed linear infinite spinner-border;
+  animation: spinner-border $spinner-animation-speed linear infinite;
 }

 .spinner-border-sm {
@@ -47,7 +47,7 @@
   // stylelint-disable-next-line property-disallowed-list
   border-radius: 50%;
   opacity: 0;
-  animation: $spinner-animation-speed linear infinite spinner-grow;
+  animation: spinner-grow $spinner-animation-speed linear infinite;
 }
```

I think the name of the animation should be the first value.

**Comment by XhmikosR** [comment]
/CC @MartijnCuppens @mdo we recently changed the order in 4.6.0 and main

**Comment by mdo** [comment]
If it compiles fine for us, unsure why it'd be a problem for this situation. Without details on the `my-file.css`, not sure what we can do to help debug.

**Comment by tcastelly** [comment]
I created a repo, you just have to run:
`npm run build`

https://github.com/shenron/vue-bootstrapjs

Btw, my scss file:

```scss

@import '../node_modules/bootstrap/scss/bootstrap';
```

Thank you for your help.

**Comment by XhmikosR** [comment]
Seems like a (serious) bug with cssnano. We use clean-css and there are no issues. You should report your issue there so that there's a chance for it to be fixed.

@mdo your call if we should revert the change or not. Again, do note that we have applied the same changes to main too.

**Comment by tcastelly** [comment]
@XhmikosR thank you for your help.

I'm trying to reproduce the error with only cssnano, without success:
https://github.com/shenron/cssnano-error

**Comment by XhmikosR** [comment]
Well, you need to pinpoint what's failing for you exactly. I hardy just looked at your first repo.

The fact is that our CI passes with the latest node-sass and sass.

**Comment by mdo** [comment]
Very strange situation IMO—ideally these tools shouldn't care about the order, right? Do we know where there's a list of official value orders for shorthand properties?

**Comment by tcastelly** [comment]
I found information here:
https://www.w3.org/TR/css-animations-1/

"Note that order is important within each animation definition: the first value in each <single-animation> that can be parsed as a <time> is assigned to the animation-duration, and the second value in each <single-animation> that can be parsed as a <time> is assigned to animation-delay.

Note that order is also important within each animation definition for distinguishing <keyframes-name> values from other keywords. When parsing, keywords that are valid for properties other than animation-name whose values were not found earlier in the shorthand must be accepted for those properties rather than for animation-name. Furthermore, when serializing, default values of other properties must be output in at least the cases necessary to distinguish an animation-name that could be a value of another property, and may be output in additional cases."

I guess in our case the order should not matter.

**Comment by mdo** [comment]
Yeah from that same page:

> For example, a value parsed from `animation: 3s none backwards` (where `animation-fill-mode` is `none` and `animation-name` is `backwards`) must not be serialized as `animation: 3s backwards` (where `animation-fill-mode` is `backwards` and `animation-name` is `none`).

So I think that's saying the animation name should come first?

**Comment by tcastelly** [comment]
Maybe if the shorthand property is confusing we can use multiple properties?

**Comment by saifulriza** [comment]
Same problem here. when compiling to production using version 5 or 4.6.0. to solve this I have to downgrade to version 4.5.3

**Comment by ffoodd** [comment]
Just as a reference, this was changed in #32121 (along with other shorthand values reordering).

**Comment by mdo** [comment]
Can this be closed given the referenced PR?

**Comment by XhmikosR** [comment]
The referenced PR is where this was introduced in :)

**Comment by mdo** [comment]
Doh lol

**Comment by alpadev** [comment]
This is not an issue of Bootstrap. 

Using the name at the end corresponds to the spec. (This is true at least since [2017](https://www.w3.org/TR/2017/WD-css-animations-1-20171130/#animation) - The [2013](https://www.w3.org/TR/2013/WD-css3-animations-20130219/#animation-shorthand-property)'s spec mention the name at the beginning but also this issue: `Need to also explain how order is important in terms of animation-name versus keywords, and probably also adjust the canonical order to match.` The oldest version on github I found is from [2014](https://github.com/w3c/csswg-drafts/blob/e7acf8c4b304ffbc89d7380764a2d169c4f1ceb9/css-animations/Overview.bs#L577) and already has the name at the end.)

The OP's problem results from setting
 ```js
 css: {
     requireModuleExtension: false,
}
```
in the vue.config.js. 

According to the vue-cli doc this does the following:
> By default, only files that ends in *.module.[ext] are treated as CSS modules. Setting this to false will allow you to drop .module in the filenames and treat all *.(css|scss|sass|less|styl(us)?) files as CSS modules.

The line that breaks the compilation looks like this (after being transformed to CSS modules syntax):
```css
.style_progress-bar-animated_gVpPS {
  -webkit-animation:1s linear infinite :local(progress-bar-stripes);
  animation:1s linear infinite :local(progress-bar-stripes)
}
```
The error message is misleading because it's not cssnano having a problem with this code, but the postcss parser that is used by cssnano.

Not sure why moving the name around should solve this problem or how the OP found that solution.

The real cause for this problem is the `css-loader` (among others) version being outdated in `@vue/cli-service`.

I setup a project with webpack (which is used by `@vue/cli-service`) and the latest versions of dependencies that are required to compile bootstrap with css-modules support and it compiled without errors (even when minifying with cssnano).

@tcastelly either create a ticket at their repo or add
```json
"resolutions": {
    "css-loader": "^5.2.4"
  }
```
to your package.json and run yarn install again.

**Comment by tcastelly** [comment]
Thank you for your help, I confirm install `css-loader` fix the problem.
> ```json
> "resolutions": {
>     "css-loader": "^5.2.4"
> }
> ```
> 
> to your `package.json` and run `yarn install` again.
