### ISSUE TITLE
[Feedback] Don't remove left and right for the time being

### ISSUE THREAD

**Issue by willnode** [twbs/bootstrap#32937]
Upgrading from alpha to beta I usually don't expect anything suprise me, but [it did](https://getbootstrap.com/docs/5.0/migration/#rtl). 

I use `ml-` and `mr-` a lot. This convention rename seems too hurry to me. Honestly I don't even like the new convention `e` or `s` because it's kinda not obvious to me (or it's just that i'm not used with it yet).

I appreciate the new RTL support, but to me the cost of this compatibility break is much higher than actually supporting RTL itself, especially when i'm expecting that my website is not even be seen by RTL userlands. I've been using bootstrap for years and I kinda afraid this change will affect my working performance (imagine telling your co-workers that why `ml-`/`mr-` not working anymore over and over).

My suggestion is, please support both convention left-right and start-end, and mention that left-right is deprecated and will be removed in the future (6.x or somewhere when usage is low). Font-awesome already doing this when they want to deprecate `fa` in favor for `fas`.

**Comment by mdo** [comment]
@ffoodd How likely is it that we could actually support something like this? Should we add aliases or no? We've had a few issues opened up asking about it.

**Comment by ffoodd** [comment]
> imagine telling your co-workers that why ml-/mr- not working anymore over and over

Yeah I imagine quite well actually, since you're not the first one I'll explain this again. 😄

@mdo I added to the docs several ways to either [rename utilities](https://main--twbs-bootstrap.netlify.app/docs/5.0/utilities/api/#rename-utilities), [add aliases](https://main--twbs-bootstrap.netlify.app/docs/5.0/utilities/api/#add-utilities) for such cases or even [wrap our entire code base with `.ltr`/`.rtl`](https://main--twbs-bootstrap.netlify.app/docs/5.0/getting-started/rtl/#ltr-and-rtl-at-the-same-time).

Regarding arguments, please [read the related discussion](https://github.com/twbs/bootstrap/discussions/32402) or any other issues this one duplicates.

If you're using a custom build, you're able to add those aliases.

On our side, adding them would only: 
- make things really confusing for everyone, having two classes for rhe same thing;
- would for sure prevent anyone from using them, and making this discussion happen again in v6;
- add hundreds of duplicate utilities (bloating codebase and dist files);
- kinda defeat the point of supporting RTL;
- this is a major release, there's no better moment to introduce breaking changes.

IMHO, documenting how-tos is done and enough. One can very easily get its oldish v4 names, and I already suggzsted someone could make release the utilities overrides as a side-project.
Related discussion already explains and details the whole topic.

Your call @mdo if you want to make something else in our core, but looking at our current doc should help.

**Comment by ffoodd** [comment]
Closing per last comment.

**Comment by rawoke083** [comment]
Agreed ! `the *-l &&  *-r` mechanism is "core" to my base (incomplete) knowledge of BS - I have been using that convention for YEARS ! Imagine getting into a car and the steering wheel is now two levers for STARBOARD and PORT SIDE ?  :)
