### ISSUE TITLE
v5: Ratio not working for images inside picture tags

### ISSUE THREAD

**Issue by sthabring** [twbs/bootstrap#32991]
Ratios are not working in combination with images in picture tags.

Example HTML: 
```html
<figure class="ratio ratio-16x9">
  <picture>
    <img src="//placehold.it/1600x900">
  </picture>
</figure>
```

The selector `ratio > * ` matches the picture element, but the style should be applied to the image instead.

**Comment by ffoodd** [comment]
Well, that's pretty much [what's explained in our docs](https://getbootstrap.com/docs/5.0/helpers/ratio/):

> Styles are applied from the parent .ratio class directly to the child.

So you can't expect it to be different, as of now. FYI, simply add another `.ratio` class on your `picture` element does the trick: [here's a CodePen demonstrating this](https://codepen.io/ffoodd/pen/wvoMEBg?editors=1100).

I don't think we're gonna change this helper since there's an easy workaround, being the helper itself. @twbs/css-review any opinion on this?
