### ISSUE TITLE
problem with form-group row and  text-md-right.....BOOTSTRAP 5

### ISSUE THREAD

**Issue by SarajevoNo1** [twbs/bootstrap#33010]
I see several problems in new bootstrap 5:

- there is no padding bottom like before for form-group row

- text label "password, " email", : text-md-right ; not working,

- also other not stylished stuffs after installing fresh laravel and with bootstrap cdn deliver included,,, its not like in before versions, many things and elements are not arranged normally like before.

Fresh installation in laravel. THANKS !

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by SarajevoNo1** [comment]
I am attaching URL: live demo video of problem related:


https://streamable.com/xtau7u

**Comment by ffoodd** [comment]
This is not a live demo, and you're pointing several different issues so there's not much we can do for now.

You're mentionning "new Bootstrap 5", from what I deduce you're upgrading from v4: if so, please [read our migration guide](https://getbootstrap.com/docs/5.0/migration/) carefully since this is a major release, you're likely to have some changes to make in your markup.

**Comment by mdo** [comment]
Closed per last comment. Consult the migration guide between major versions.
