### ISSUE TITLE
Background coloring of cards broken in MS Edge (v 78)

### ISSUE THREAD

**Issue by twisbrogan** [twbs/bootstrap#33064]
When setting the background color of a card in the outer div:
```
<div class="card bg-info mb-3">
...
```

...the color doesn't seem to be getting set. Setting the value in other (contained) divs sets the color as expected.
```
<div class="card text-center">
  <div class="card-header bg-info">
...
```

The version of Edge being used is 87.0.664.75 and I have seen this behaviour on my own sites but also in the Bootstrap documentation site itself:
https://getbootstrap.com/docs/4.6/components/card/#background-and-color
https://getbootstrap.com/docs/5.0/components/card/#background-and-color 

![2021-02-12 at 15 47](https://user-images.githubusercontent.com/722159/107789586-b2847f00-6d49-11eb-93bb-1d645df7eabc.png)

**Comment by ffoodd** [comment]
Seems to work fine on Edge 87, see screenshot below made in BrowserStack.

![bs_win10_Edge_87 0](https://user-images.githubusercontent.com/2890570/107794932-5a08ae00-6d58-11eb-90a4-a426457826d6.jpg).

Please provide any additional infos you can, and maybe a reduced test case since our docs are fine.

**Comment by mdo** [comment]
These definitely are working for me too, so until further details are shared, closing out.
