### ISSUE TITLE
Bootstrap Reboot 4.x CSS contains duplicate text-decoration style for abbr[title]

### ISSUE THREAD

**Issue by matosconsulting** [twbs/bootstrap#33197]
The generated reboot css file contains a duplicate property:

![image](https://user-images.githubusercontent.com/1933317/109015192-7d95f780-767a-11eb-9a52-32e4642c6243.png)

https://github.com/twbs/bootstrap/blob/056216a3bd2fd1f28ba9ec6f2797aa2aaec5c6f0/scss/_reboot.scss#L145-L146

CSS allows duplicate property names but only the last instance of a duplicated name determines the actual value that will be used for it. Therefore, changing values of other occurrences of a duplicated name will have no effect and may cause misunderstandings and bugs.

- Operating system and version: All/Unrelated
- Browser and version: All/Unrelated
- Suggested Fix: Remove the duplicate that doesn't align with the vision of the product

**Comment by ffoodd** [comment]
Hi there, thanks for reporting!

It was done on purpose, since `text-decoration` as a shorthand had very poor support back in the days: the first declaration was a fallback value for non-supporting browsers (which is a very common pattern for progressively enhance some properties allowing modern values).

However after [checking support on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration#browser_compatibility), it appears that our current targets all support the shorthand value. I think it's now safe to drop the first one in v5 then.

Feel free to suggest a patch, or we'll take of it when possible.
