### ISSUE TITLE
Bootstrap 5 modal does not hide by script

### ISSUE THREAD

**Issue by codetuner** [twbs/bootstrap#33195]
Scripted hiding a bootstrap v5 modal does not work. The modal stays open when calling the hide() method on the bootstrap.Modal object.

Bootstrap version: 5.0.0-beta2
OS: Windows 10
Browsers tested: Google Chrome 88.0.4324.190 (64-bit), Microsoft Edge 88.0.705.74 (64-bit)
Test case:
`&lt;!-- Button trigger modal --&gt;
&lt;button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"&gt;
    Launch demo modal
&lt;/button&gt;

&lt;!-- Modal --&gt;
&lt;div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"&gt;
    &lt;div class="modal-dialog"&gt;
        &lt;div class="modal-content"&gt;
            &lt;div class="modal-header"&gt;
                &lt;h5 class="modal-title" id="exampleModalLabel"&gt;Modal title&lt;/h5&gt;
            &lt;/div&gt;
            &lt;div class="modal-body"&gt;
                &lt;button type="button" onclick="**new bootstrap.Modal(document.getElementById('exampleModal')).hide();**"&gt;Close me via script&lt;/button&gt;
            &lt;/div&gt;
            &lt;div class="modal-footer"&gt;
                &lt;button type="button" class="btn btn-secondary" data-bs-dismiss="modal"&gt;Close&lt;/button&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;`

**Comment by rohit2sharma95** [comment]
The `hide` method called on an instance can hide only the modal that was opened by calling the `show` method on that instance. Since there is a property on that instance that maintains the state of the modal. (And in your case you are creating a new instance to hide the modal that would not work :slightly_smiling_face:) 

https://github.com/twbs/bootstrap/blob/5560c86070c8be08f76801bbc7e525eea4fc0cf6/js/src/modal.js#L156-L158

You should use `data-bs-dismiss="modal"` in your case, but if you really want to get that instance and then hide modal you can get it:
```js
var modalInstance = null;
var modelElem = document.querySelector('#exampleModal');
modelElem.addEventListener('shown.bs.modal', function (){
  modalInstance = bootstrap.Modal.getInstance(modelElem);
});
```

```html
<button type="button" onclick="modalInstance.hide()">Close me via script</button>
```
https://jsbin.com/xivitikine/1/edit?html,js,output

**Comment by codetuner** [comment]
Thanks a lot! Solves my problem :)

**Comment by farsunset** [comment]
> ```js
> modalInstance
> ```

That is bad func for modal close
