### ISSUE TITLE
Treeview support for bootstrap 5

### ISSUE THREAD

**Issue by williamjmorenor** [twbs/bootstrap#33449]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)

Did not find any relevant issue.

- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Done

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap

A treeview allows you to naturally display a parent-child hierarchy with multiple levels of nesting to the user, I have been looking for oficial Bootstrap support in the docs but di not find a match for the up comming 5 mayor release.

Reviewing in forums and other resources I find that normally to implement this feature should resort to third-party libraries that do not always fit well with the features and functionality provided by bootstrap, so I want to ask if native support for tree views can be added to Bootstrap 5.

The tree view is supported in most desktop application development tools:

- .Net: https://docs.microsoft.com/es-es/dotnet/api/system.windows.forms.treeview?view=net-5.0
- QT: https://doc.qt.io/qt-5/qtreeview.html
- GTK: https://developer.gnome.org/gtk3/stable/GtkTreeView.html
- https://docs.oracle.com/javase/tutorial/uiswing/components/tree.html

With most apps moving from desktop to Browser will be a great improvement to support this feature to support people looking for move a dektop feature to the web in a easy path. 

Also many projects requires JQuery that is now not required for bootstrap

- Relevant links to prior art, screenshots, or live demos whenever possible

This demo from the Patterfly Project is bassed on Bootstrap3: https://www.patternfly.org/v3/components/patternfly/dist/tests/bootstrap-treeview.html

This is the current implementation off patternfly that no requires bootstrap: https://www.patternfly.org/v4/components/tree-view/#treeview

This is a third party implementation on top of bootstrap: https://github.com/jonmiles/bootstrap-treeview

Some screenshotps:

![treeview_front](https://user-images.githubusercontent.com/3522386/112203739-73630c80-8bd8-11eb-87fe-5fbcfb3473f3.png)

![hq720](https://user-images.githubusercontent.com/3522386/112204031-d05ec280-8bd8-11eb-8c03-2e21394a0a76.jpg)

**Comment by mdo** [comment]
Closing as a won’t implement. You could build this with our accordion component, but we won’t be providing it. Thanks though!

**Comment by Orgoth** [comment]
Thank you for the feedback and justification.

But unfortunately the Accordion component did not stand the test.
In order to be able to map the behavior of a tree view, considerable adjustments have to be made.

With the current Accordion component, it is not possible to click/tap on an item without the submenu opening or closing.
Or that the submenu only opens when the arrow/icon is clicked/tapped.

In the end, it will come back to using the "list-group" component with significant customization, or buying it from mdb for a yearly recurring price. :-1: 

https://mdbootstrap.com/docs/standard/plugins/tree-view/

It would probably still please some users if it were included.
Have a nice day.

**Comment by garymoon** [comment]
Is this proposal possibly worth reconsidering in light of the reactions? No worries if not, just worth asking 👍 

Thanks for Bootstrap! 💙

**Comment by Orgoth** [comment]
I do not think anything will happen.
@mdo made it clear already, they are not willing to do anything!
Regardless of the feedback visible.
24 downvotes for @mdo

Since the last update/release was 2024-02-20 I think this project stopped development.
Even the blog is dead.
https://blog.getbootstrap.com/

When I look at the commits, it seems that only 2 - 3 people are still working on the framework, otherwise nobody else.

Based on all the open pull requests, the introduction of code will also be pointless.
https://github.com/twbs/bootstrap/pulls
The open requests date back to 2019.

**Comment by garymoon** [comment]
Oh my, I hadn't realized at all! Thanks for drawing my attention, sorry for the noise!
