### ISSUE TITLE
Reset inside a Dialog does not work if data-dismiss="modal" is set.

### ISSUE THREAD

**Issue by meduzapat** [twbs/bootstrap#33469]
Hello, I found an issue when using the reset form button inside a Dialog.
If the button does reset and dismissal by using data-dismiss="modal", the dialogs close fine but the form is never reset.

Test case on codepen: https://codepen.io/meduzapat/pen/LYxpGNe

I added 3 buttons, normal close, reset and close, and my work around: reset and js close.

Tested on:
Chrome OS, Linux: Firefox 86.0.1 (64-bit) and chrome Version 89.0.4389.90 (Official Build) (64-bit) an Windows.

**Comment by GeoSot** [comment]
Thank you for your report. :)
Unfortunately if you replace the icon with text, it works fine. So this makes me believe it is an EventHandler issue

**Comment by rohit2sharma95** [comment]
It's because the default behavior is prevented in the hide method:
https://github.com/twbs/bootstrap/blob/232e392c9126fcb1dbe13c963e7edcdbd62cfeb8/js/src/modal.js#L151-L154

And the default behavior is being prevented intentionally here. (Like clicking anchor tag updates the route)

/CC @twbs/js-review
