### ISSUE TITLE
Tooltip placement does not work with a parent container has overflow: auto or overflow: scroll

### ISSUE THREAD

**Issue by KeenthemesHub** [twbs/bootstrap#33463]
The tooltip placement does not work with a parent container has overflow: auto or overflow: scroll.  boundary: 'window' did not help either.

**Comment by GeoSot** [comment]
@KeenthemesHub can you provide an example replicating the problem using codepen?

**Comment by amarinediary** [comment]
@GeoSot I can confirm the issue. As @KeenthemesHub isn't answering I will takeover this bug report.

If the parent container is set to x/y `overflox:scroll`  or x/y `overflow:hidden;`, the `data-bs-placement` will be ignored and fallback to default `auto` placement.

As per Bootstrap website documentation about tooltips: 
> Overflow auto and scroll
> ---
> Tooltip position attempts to automatically change when a parent container has `overflow: auto` or `overflow: scroll` like our `.table-responsive`, but still keeps the original placement’s positioning. To resolve, set the boundary option to anything other than default value, `'scrollParent'`, such as `'window'`:

Specifying `data-bs-boundary="window"` won't work and the tooltip will still remain in default auto state.

[Here is a reduced test case](https://codepen.io/amarinediary/pen/wvggqZq)
___
- macOS Mojave version 10.14.3 (18D109)
- Chrome version 89.0.4389.90 (Official Build) (x86_64)


- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by amarinediary** [comment]
@GeoSot Any news on that subject ?

**Comment by GeoSot** [comment]
@rohit2sharma95 , can you help us here?  🧑‍🤝‍🧑

**Comment by jasonlewis** [comment]
When initialising with JavaScript you can use the following `popperConfig` to work around this, though it feels like it needs to be addressed either as docs or elsewhere.

```js
popperConfig: function (config) {
  const flip = config.modifiers.find(({ name }) => name === 'flip')

  flip.options = {
    ...flip.options,
    boundary: 'window'
  }

  return config
}
```

**Comment by kadsyy** [comment]
![Screenshot 2021-04-19 153239](https://user-images.githubusercontent.com/4100091/115198358-89ef7b80-a124-11eb-891d-c98925e0cb34.png)
This happen for dropdown in a `table-responsive` as well when there in only 1 row inside the table.

referring to @jasonlewis answer setting up `altAxis` to true in  `preventOverflow` modifier might do the trick.

```JavaScript
popperConfig: function(config) {
 const preventOverflow = config.modifiers.find(({ name }) => name === 'preventOverflow')

 preventOverflow.options = {
  ...preventOverflow.options,
  altAxis: true,
 }

 return config
}
```

![Screenshot 2021-04-19 153248](https://user-images.githubusercontent.com/4100091/115199884-3c740e00-a126-11eb-8166-a9e5e61090f3.png)

I'm not sure if this a proper solution since when i'm using `flip` id does not change anything.

**Comment by alpadev** [comment]
I think we should review the Popper config in general. 
I'm not experienced with Popper but from what I'm seeing every modifier module supports options like boundary.

Currently we're setting boundary only for the preventOverflow module and I'm not sure if those settings are inherited or something. Also from my first investigation it looks like what causes problems for the OP is the flip module rather than preventOverflow.

Currently we're using this flip module together with `altBoundary` set to true (which is false by default). I wish the Popper docs would be a little bit more detailed about what every setting really does. Might be me, but I'm still not completely sure about which of them causes our problems.

> ### altBoundary
> This describes whether to use the alt element's boundary. For example, if the elementContext is "popper", then it will check the reference's boundary context, and vice-versa.

If I set `altBoundary` to false which is the default the behaviour seem a little bit more like what the OP expected from what I can tell.

**Comment by rohit2sharma95** [comment]
I am a bit late here, but this is not an issue, instead, it is a feature of Popper. (Also this is not related to bootstrap)
`boundary` option is different for all modifiers of Popper and the user can not set the value for this option for all the modifiers (means for the whole Popper instance) at once. And seems that there is no intention of maintainers to do so for now, see this discussion here: https://github.com/popperjs/popper-core/discussions/1277

Thanks, @jasonlewis for posting the solution here and in #33579, that's not the workaround instead the proper way of changing the popperConfig directly. Even it is mentioned in the official docs as well: https://getbootstrap.com/docs/5.0/components/tooltips/#using-function-with-popperconfig

But setting the `altBoundary` option to true for the flip modifier is not needed here since the boundary should be checked for the tooltip element (that is popper) not for the button (that is reference element). The tooltip is appended to the body by default so there is no need to change the value for the boundary option in the flip modifier if we are not changing the value of the `altBoundary` option. Will create a PR for the same.

I hope this discussion is clear to you @amarinediary :slightly_smiling_face:
