### ISSUE TITLE
No way to call modals without using javascript

### ISSUE THREAD

**Issue by jerodion** [twbs/bootstrap#33493]
Every single modern frontend framework uses props in order to show modals. Literally every single one.

Why, in this newest version, are you still requiring an event to be fired in order to show modals? Why can't we just assign a prop or a CSS class in order to show/hide a modal? Nobody uses modals this way anymore. Like explain to me how I can have a modal be visible on page load without firing a javascript event in onload? You can't.

If there is a way of doing this and I'm wrong, go ahead and feel free to show me.

Let's look at tailwind modals, for example: https://tailwindui.com/components/application-ui/overlays/modals

The modals in those examples use alpine props in order to show/hide. You can easily entangle these props using any other framework you want if you don't like alpine. Like react, or vue. The syntax may differ but the concept remains consistent.

It can't be that hard to recode the bootstrap modals so you aren't having to modify things like the `body` element just to show them, especially when you can just use CSS transitions and stuff nowadays. I have absolutely no idea why bootstrap modals actually modify the `body` element when they are opened.

Even bulma modals don't modify the `body`: https://bulma.io/documentation/components/modal/

I think this needs rethinking and recoding entirely. You could just have a `data-bs-show` attribute on the model container with a boolean value e.g. `data-bs-show="1"`, or have it so the `show` class actually works properly without having to modify the `body` tag. Not to mention that a lot of the modal-related stuff in your docs doesn't even work properly, like the full page examples.

Stuff like this is killing bootstrap. It just seems like there is no progress. All of the components still look exactly the same and it's a bad sign when people would rather use atomic frameworks and basically write everything from scratch over and over than use this library, which used to be the best in the world. I mean I get that you're finally ditching jquery but it seems like you're not considering what tools people actually use nowadays. It seems like you're just ditching jquery for the sake of ditching jquery. Nobody in their right mind wants to pollute their global space with bizarre event handlers to do things that can be done without even requiring javascript at all.

**Comment by marek95** [comment]
> I have absolutely no idea why bootstrap modals actually modify the body element

it is to put `overflow: hidden;` on it so that you cannot scroll the website while a modal is open. try to put your cursor over the backdrop and you wont be able to scroll. that is good because you dont want to interact with the website while a modal is open. I think one reason is that it would break your expectation what to see when you close the modal... you would be out of place. 

thats just part of why you would need to modify the body.

> Even bulma modals don't modify the body

but it modifies the `<html>` instead

> Why can't we just assign a prop or a CSS class in order to show/hide a modal? 

there is more to opening modal then just applying css styles. it is not so simple. for example, you need to turn on some sort of '`tab` trapping', as per the accessibility guidelines https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal ... and there are other accessibility concerns that bootstrap handles for you ...

**Comment by jerodion** [comment]
> > I have absolutely no idea why bootstrap modals actually modify the body element
> 
> it is to put `overflow: hidden;` on it so that you cannot scroll the website while a modal is open. try to put your cursor over the backdrop and you wont be able to scroll. that is good because you dont want to interact with the website while a modal is open. I think one reason is that it would break your expectation what to see when you close the modal... you would be out of place.

You don't need to add `overflow: hidden` in order to make the body non-scrollable. Did you look at the tailwind examples? Go into web inspector and make the modal content huge so it scrolls. You'll see that only the modal scrolls, not the content behind it. Is this magic, or did the tailwind people somehow figure this out using CSS alone?

> thats just part of why you would need to modify the body.

You don't have to in order to accomplish this.

> > Even bulma modals don't modify the body
> 
> but it modifies the `<html>` instead

Look at the tailwind examples then. I don't even care about bulma. My point was that this is achievable without having to modify elements of the document that make standard DOM morphing impossible without fixing a bunch of new bugs that shouldn't need to be fixed.

> > Why can't we just assign a prop or a CSS class in order to show/hide a modal?
> 
> there is more to opening modal then just applying css styles. it is not so simple. for example, you need to turn on some sort of '`tab` trapping', as per the accessibility guidelines https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal ... and there are other accessibility concerns that bootstrap handles for you ...

Every modern JS library allows you to specify accessibility handlers when props change or elements are initialized. Nobody in their right mind is going to use bootstrap with vanilla javascript. The whole point of bootstrap is that it makes getting things done fast.

**Comment by marek95** [comment]
> Did you look at the tailwind examples? 

yes, but I havent used tailwinds or alpine js before, so it is a mess for me to look at. 

> Go into web inspector and make the modal content huge so it scrolls. 

it is about the content _behind_ the modal, you should put the content there... then, put your cursor over the overlay and you should be able to scroll... that is what bootstrap is trying to prevent...

**Comment by hax18** [comment]
> it is about the content _behind_ the modal, you should put the content there... then, put your cursor over the overlay and you should be able to scroll... that is what bootstrap is trying to prevent...
@marek95  I'm i wrong or u are talking about "**Modal Backdrop**" ?
If so i'dont see why u should be able to scroll when a **Modal** is shown that'd be annoying!!

**Comment by marek95** [comment]
> @marek95 I'm i wrong or u are talking about "Modal Backdrop" ?

yes, I am talking about the "backdrop" . sometimes this thing is called an overlay, but yea bootstrap calls this a "backdrop" .

> If so i'dont see why u should be able to scroll when a Modal is shown that'd be annoying!!

yes, i agree that it would be anoying. and bootsrap developer seem to agree. they put `.modal-open` class on the `<body>`, when a modal is open https://github.com/twbs/bootstrap/blob/4c7a3e8adf73bf55a5fba5905b356468be17bc0e/scss/_modal.scss#L8

in my last comment when I said ...

> put your cursor over the overlay and you should be able to scroll...

... I was refering to the tailwind ui example https://tailwindui.com/components/application-ui/overlays/modals

I _think_ you would run into this "body scroll" problem when using the tailwind ui example ... But I dont know for sure, because the tailwind example is in a wierd iframe thing... so i was telling @jerodion what to do so he can test it himself

**Comment by rohit2sharma95** [comment]
Hi, @jerodion
> Not to mention that a lot of the modal-related stuff in your docs doesn't even work properly, like the full page examples.

Can you please mention what is wrong with fullscreen modal examples? :slightly_smiling_face:

> I have absolutely no idea why bootstrap modals actually modify the body element when they are opened.

There are more things to handle when the bootstrap modal is shown. Like scrolling, fixed (and sticky) elements (handling padding and margin) and focusing, etc. The body is modified to give some of these features to the user. :slightly_smiling_face:

**Your main point:**
> Why can't we just assign a prop or a CSS class in order to show/hide a modal

Modal can not be shown by default without emitting any event or without JavaScript, that's true. But then bootstrap needs to attach one more load event itself that will check for the `show` class to be present on the modal and then open it.

It can be considered though since a few days ago it has been done for Offcanvas component: #33382

/CC @XhmikosR and @GeoSot

**Comment by marek95** [comment]
@jerodion could you tell more about what kind of situation you are in? why do you consider it so problematic to make a short script that would 'on page load' open the modal? why would it be so bizzare?

**Comment by rohit2sharma95** [comment]
Should keep it open? @XhmikosR
