### ISSUE TITLE
V5 Popovers & Modal : Calling a modal from popover not working!

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33546]
I'm trying to call modal popup from popover but is seems that something is wrong with it??

**Here is my code example :**

```
<button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-html="true" title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right? <a href='#myModal' role='button' data-bs-toggle='modal' data-bs-target='#myModal'>Click here</a>">Click Here</button>

<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by mdo** [comment]
@devhoussam You've opened enough issues here to know you need to produce a working example of the problem and additional information :). Please do so and I'll reopen this issue.

**Comment by korki43** [comment]
@devhoussam The Popover is not opening because you have to initialize them yourself. The link for the modal isn't working because the bootstrap html sanitizer strips all attributes except `href` and `role` from the anchor.
You also need to lower the `z-index` of the popover because it's `z-index` (1070) is higher than the modal one's (1060).

You can add allowed attributes to the html santizer by (modifying the `AllowList`)[https://getbootstrap.com/docs/5.0/getting-started/javascript/#sanitizer] or disable the sanitizer completly by using `sanitize: false` when initializing the component. 

Here is a small demo: https://codepen.io/korki43/pen/PoWjPyB

_Note: With the code in my example it's impossible to have another popover in the modal, because it's z-index will be lower than the modal's. To do something like that you would have to differentiate between popovers within and outside of a modal._
