### ISSUE TITLE
BS5 beta-3: backdrop overlays nested Offcanvas content inside .fixed-top

### ISSUE THREAD

**Issue by neralex** [twbs/bootstrap#33581]
Hi,

is there a way to prevent the backdrop-overlaying without moving the nested div.offcanvas outside of the parent-element .fixed-top?

- OS: Windows 10
- Browser: latest Chrome and Firefox
- Test case: https://codepen.io/neralex/pen/XWpeqRb

Thanks in advance.

**Comment by alpadev** [comment]
The problem is how z-index or particularly stacking contexts work. A new stacking context is created for the element and all nested elements. Since the z-index of .fixed-top is lower than the z-index of the backdrop, you can't go _higher_ than the backdrop from within the .fixed-top element itself.

I guess it would be possible to change the backdrops behaviour, but in my opinion it would be just easier to move .offcanvas out of the .fixed-top element.

Are there any reasons why you need that inside of .fixed-top?

**Comment by neralex** [comment]
Not really at the current point but I would have to ask before. Maybe there is an easy without moving out.

**Comment by neralex** [comment]
Not really at the current point but I would have to ask before. Maybe there is an easy way without moving out.
