### ISSUE TITLE
popover content - title attr broken with span but works with a

### ISSUE THREAD

**Issue by hrvoj3e** [twbs/bootstrap#33585]
https://jsbin.com/merawucugi/edit?html,js,console,output

Please see the jsbin example.
It fails when `span` with attr `title` but works with tag `a`.

Expected
 - preserve title attribute on spans also

**Comment by ffoodd** [comment]
Please have a look at [HTML sanitizer docs](https://getbootstrap.com/docs/5.0/getting-started/javascript/#sanitizer), I guess that's what you need.

AFAICT `title` on non-interactive elements is pretty useless and only gives a visual hint. Since we don't use nor recommend this usage, it's sanitized in our default sanitizer options.

Does this help enough?

**Comment by hrvoj3e** [comment]
Client wants `title`/hint in that place. Thank you for the hint.

Solved with 

```js
var myDefaultWhiteList = $.fn.tooltip.Constructor.Default.whiteList
myDefaultWhiteList['span'].push('title');
```

https://getbootstrap.com/docs/4.6/getting-started/javascript/#sanitizer
