### ISSUE TITLE
[BS5] RFS overrided by another media query

### ISSUE THREAD

**Issue by 5ulo** [twbs/bootstrap#33703]
I found a weird behaviour of RFS in latest BS5 beta3. My SCSS file contains:
```
.post.-card {
    .post__title {
        @include media-breakpoint-up(xl) {
            @include font-size(3rem);
        }
    }
}
```

and is outputed like this:

```
@media (min-width: 1200px) {
    .post.-card .post__title {
        font-size: calc(1.425rem + 2.1vw);
    }
}
@media (min-width: 1200px) and (min-width: 1200px) {
    .post.-card .post__title {
        font-size: 3rem;
    }
}
```

When I change breakpoint to XXL, output is

```
@media (min-width: 1200px) {
    .post.-card .post__title {
        font-size: calc(1.425rem + 2.1vw);
    }
}
@media (min-width: 1400px) and (min-width: 1200px) {
    .post.-card .post__title {
        font-size: 3rem;
    }
}
```

Can't reproduce in codepen as there's no BS5 sass available

```font-size: rfs-fluid-value(3rem);``` works as expected though

edit: another example using ```media-breakpoint-only(xl)```

```
@media (min-width: 1200px) and (max-width: 1399.98px) {
    .navbar .navbar-nav .nav-link {
        font-size: calc(1.325rem + 0.9vw);
    }
}
@media (min-width: 1200px) and (max-width: 1399.98px) and (min-width: 1200px) {
    .navbar .navbar-nav .nav-link {
        font-size: 2rem;
    }
}
```

**Comment by mdo** [comment]
Does this happen in the examples or use cases of the RFS project? https://github.com/twbs/rfs

**Comment by 5ulo** [comment]
actually it is..  I checked this sass codepen https://codepen.io/MartijnCuppens/pen/vqaEBG?editors=0100 where
```
.title {
  @include font-size(2.2rem);
  font-weight: 400;
  line-height: 1.2;
  margin-bottom: .5em;
}
```
outputs as:
```
@media (min-width: 1200px)
.title {
    font-size: 2.2rem;
}
.title {
    font-size: calc(1.345rem + 1.14vw);
    min-width: 0vw;
    font-weight: 400;
    line-height: 1.2;
    margin-bottom: 0.5em;
}
```
so 2.2rem is aaplied, calc is ignored. This applies to viewport > 1080. On the other hand in viewport < 1080 things change and calc version is applied.
I really don't understand how it works.

**Comment by alpadev** [comment]
I'm not the SASS expert here but I think there is some misconception. The font-size mixin already _includes_ some media query that will kick in at the `$rfs-breakpoint` (which is set to 1200px by default) because this is when the fluid value reaches its maximum (the value you passed to `font-size()`).

So with simple words:

While the browsers' width is less $rfs-breakpoint make the font-size fluid. 
```css
.title {
  font-size: calc(1.345rem + 1.14vw);
}
```

If it's wider just use the defined value. (This prevents the font-size from growing bigger than what was defined.)
```css
@media (min-width: 1200px) {
  .title {
    font-size: 2.2rem;
  }
}
```

I guess the `font-size` mixin isn't really meant to be nested within some other media queries. So this is why it messes with the other media queries wrapped around.

Like you already had figured you can use `rfs-fluid-value()` since that won't add any media queries. Have in mind that in this case the computed value may get bigger than what you passed to the function once the screen is wider than the 1200px ($rfs-breakpoint).

Not sure what you're trying to achieve with this.

**Comment by mdo** [comment]
The code you've mentioned doesn't output as you've shown. Note the difference here...

```css
/* Your original snippet */
@media (min-width: 1200px)
.title {
    font-size: 2.2rem;
}
.title {
    font-size: calc(1.345rem + 1.14vw);
    min-width: 0vw;
    font-weight: 400;
    line-height: 1.2;
    margin-bottom: 0.5em;
}
```

```css
/* Actual output */
@media (min-width: 1200px)
  .title {
    font-size: 2.2rem;
  }
}
.title {
  font-size: calc(1.345rem + 1.14vw);
  min-width: 0vw;
  font-weight: 400;
  line-height: 1.2;
  margin-bottom: 0.5em;
}

This is working as intended. RFS is essentially setting a max `font-size` in the media query, then scaling that down for smaller viewports so that the type size feels appropriate for the medium/device.
