### ISSUE TITLE
Tooltip is going upside in example of sidebar

### ISSUE THREAD

**Issue by Anoopkumarseth** [twbs/bootstrap#33748]
Please check this link https://getbootstrap.com/docs/5.0/examples/sidebars/#: 

in the sidebar after clicking the tooltip is going upside, (I'm checking it in chrome latest version)

![Screenshot 2021-04-26 093441](https://user-images.githubusercontent.com/30388576/116027628-04fbe900-a673-11eb-8e2c-42abf22cc72a.png)
![Screenshot 2021-04-26 093449](https://user-images.githubusercontent.com/30388576/116027634-075e4300-a673-11eb-974d-b37356dde96e.png)

**Comment by alecpl** [comment]
Confirmed with Chromium 90.0.4430.72, Works in Firefox.

**Comment by sanyogchangmai** [comment]
The above issue is addressed here #33753

**Comment by alpadev** [comment]
> The above issue is addressed here #33753

To elaborate on this fix a bit more. We use `height: -webkit-fill-available` on the body and `min-height: -webkit-fill-available` on every child element of that body (including the tooltip element). This causes the tooltip to grow to the height of the viewport thus popper is using wrong dimensions when it tries to position that tooltip.

While trying to figure out why we use `height: -webkit-fill-available` in addition to `height: 100vh` on the body, I found this [article](https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/) which suggests that there was a problem with that page on mobiles. 

The snippet in that article is a bit different tho.  Instead of setting `height: -webkit-fill-available` on the `body` they set it on the `html` element and use `min-height` for the `body`. I guess the intention behind using `min-height` rather than `height` is to make the `body` scrollable, while our `body` uses `overflow-y: hidden` to prevent this, so this makes sense I guess.

The thing is I'm not sure why it was moved one level down e.g.
Snippet | Us
--- | ---
`html` { height } | `body` { height }
`body` { min-height } | `body > *` { min-height }

I found that the page looks frankly different when applying `height: -webkit-fill-availble` to the `html` element.

body:
![body](https://user-images.githubusercontent.com/2838324/116083250-b5321780-a69c-11eb-8640-4a7ddb24e900.png)

html:
![html](https://user-images.githubusercontent.com/2838324/116083269-b9f6cb80-a69c-11eb-82f6-82e4ceca8518.png)
