### ISSUE TITLE
Getting Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mike-spb** [twbs/bootstrap#33760]
I'm using 5.0.0 beta3
The exception raises at line 854, col 14 of bootstrap.bundle.js
` Object.keys(element.dataset).filter(key => key.startsWith('bs')).forEach(key => {`

Is it ok to wrap this block with  ?
` if (element.dataset != null) {...}`

**Comment by alpadev** [comment]
Thanks for reporting this issue.

Can you please add an example or stacktrace that shows this error?

**Comment by mike-spb** [comment]
Could not reproduce at my side, but I kept getting error messages from clients until I ​unminified 3d part js code and everything went fine with no errors

**Comment by alpadev** [comment]
I mean, sure you can wrap the mentioned line within an if-condition. But if `element.dataset` is null or undefined there seems to be something wrong in general with the initialization of a component.

I'm going to close this since I can't reproduce it properly without a demo or more details how the code ended up in this state.

Feel free to reopen it in case you got more informations to share.
