### ISSUE TITLE
Offcanvas Hardcoded focusout event

### ISSUE THREAD

**Issue by devsorice** [twbs/bootstrap#33852]
I would like to use the offcanvas sort of like a modal,   but every time a click on something external to the offcanvas it loses focus and so it gets hidden.
It could be useful if the offcanvas could be used this way and not just like a mobile menu.
 
**Suggested change** (i don't know if is a best practice but you'll get the gist)
adding a function sort of like this

```
removeLoseFocusListener(){
   EventHandler.off(this._element, EVENT_CLICK_DISMISS, this.hide)
}

```
Looking at the source code   _addEventListeners  on line 209
https://github.com/twbs/bootstrap/blob/main/js/src/offcanvas.js#L209

I can see that EVENT_CLICK_DISMISS is hardcoded,  and there is no way to remove this listener if unwanted via settings.

```
_addEventListeners() {
    EventHandler.on(this._element, EVENT_CLICK_DISMISS, SELECTOR_DATA_DISMISS, () => this.hide())

    EventHandler.on(this._element, EVENT_KEYDOWN_DISMISS, event => {
      if (this._config.keyboard && event.key === ESCAPE_KEY) {
        this.hide()
      }
    })
  }

```

**Comment by GeoSot** [comment]
@devsorice  please can you provide a 'working' example of your problem with replication steps?

PS: The `EVENT_CLICK_DISMISS`  applies **only** if you click on  `SELECTOR_DATA_DISMISS`

**Comment by devsorice** [comment]
Like a said it's not like a bug or something.
I managed to get it working for my needs by commenting //this.hide();
but it would be nice if it would be an option for it

this is from the dist version (from the npm package)
https://github.com/twbs/bootstrap/blob/main/js/dist/offcanvas.js
```
  EventHandler__default['default'].on(document, EVENT_CLICK_DATA_API, event => {
        const target = SelectorEngine__default['default'].findOne(getSelectorFromElement(event.target));

        if (!this._element.contains(event.target) && target !== this._element) {
          //this.hide();
        }
      });
```

**Comment by alpadev** [comment]
I'm closing this, since you refuse to provide us with an example, that would show the behaviour that appears to be a problem for your use-case.

`EventHandler.on(this._element, EVENT_CLICK_DISMISS, SELECTOR_DATA_DISMISS, () => this.hide())` requires the presence of `data-bs-dismiss="offcanvas"` on the clicked element to hide the offcanvas.

The other code you provided seems to be outdated or doesn't exist in our dist files. If you search on the link you provided, it doesn't exist there as well.

As you can see in our documentation https://getbootstrap.com/docs/5.0/components/offcanvas/#backdrop, if you use the `Enable body scrolling` button to open the offcanvas, it will stay open even while losing focus by clicking around.
