### ISSUE TITLE
Bootstrap 5 Popover : Events, styles and data tags added to popover content is not getting added to DOM

### ISSUE THREAD

**Issue by VishalPTank3010** [twbs/bootstrap#33876]
Operating system and version : Windows
Browser : Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser

Issue : As per the bootstrap 5 popover doc we use below code for initialize and render popover.

bootstrap.Popover(document.getElementById('id'), {
                    html: true,
                    placement: 'bottom',
                    title: '<span style="font-weight: bold;font-size: 18px;">Search Results</span>',
                    content: '<h1 **data-name="bug" onclick="alert()" style="color:blue;"**>asd</h1>',
                    template: `<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-header"></h3> <div class="popover-body"> <p></p> </div> <div class="popover-footer"></div></div></div>`
});

but data tag, events and styles are not getting added to DOM.
[Codepen link](https://codepen.io/vishaltank3010/pen/dyvPWJm)

**Comment by rohit2sharma95** [comment]
Yes, these attributes will not be added since these are not allowed. Below are the globally allowed attributes:
```js
'*': ['class', 'dir', 'id', 'lang', 'role', ARIA_ATTRIBUTE_PATTERN]
```
https://github.com/twbs/bootstrap/blob/488fd8afc535ca3a6ad4dc581f5e89217b6a36ac/js/src/util/sanitizer.js#L58-L61

You can pass your own `sanitizeFn` (see in the [options](https://getbootstrap.com/docs/5.0/components/popovers/#options)) if you don't want to remove those attributes, however, that's not a good thing :slightly_smiling_face: 

So, it is not an issue.
