### ISSUE TITLE
Docs: focus handling after Copy to clipboard button pressed

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#33894]
I thought we addressed this ages ago, but: setting keyboard focus on one of the "Copy" buttons and activating it, focus is then lost/reset to the start of the page. While browsers try to error-correct for this (meaning that a subsequent `Tab` moves to the next focusable element), the issue becomes evident when using AT (e.g. Chrome/JAWS, activate the button, then use reading keys to carry on reading...focus was moved back right to the start of the page).

Ideally, focus should remain on the "Copy" button, but I'm assuming this was not done in order to "clear" the visual style of the button. Perhaps this needs to dynamically set a class  immediately after a copy operation was carried out, which suppresses/changes the styling (maybe suppressing the tooltip, OR adding some indicator like a tick that shows it was indeed copied), and clearing that class again as soon as the button loses focus.

**Comment by rohit2sharma95** [comment]
Focus is not removed manually from the button, the button loses focus because of the `clearSelection` method of clipboardjs.

https://github.com/twbs/bootstrap/blob/6ecf21870aa4c5bbd7a8e2ad8733b7123920727f/site/assets/js/application.js#L147

But this is needed to unselect the code :slightly_smiling_face: 

There are few issues in the [official repo](https://github.com/zenorocha/clipboard.js) but those are closed without any solution :thinking:
1. https://github.com/zenorocha/clipboard.js/issues/695
2. https://github.com/zenorocha/clipboard.js/issues/680

/CC @zenorocha

PS: This behavior is present on their official website also: https://clipboardjs.com/

**Comment by patrickhlauke** [comment]
Thanks for investigating, @rohit2sharma95 ... and yes, turns out that I had actually fixed this originally in clipboard.js https://github.com/zenorocha/clipboard.js/pull/419

**Comment by mdo** [comment]
Is this still applicable @patrickhlauke?

**Comment by patrickhlauke** [comment]
It is still a problem, but a problem at Clipboard.js' end. Since the original issue over there was summarily closed for no reason, I just reopened a fresh one https://github.com/zenorocha/clipboard.js/issues/805

Wonder if it's worth keeping the issue here open until we see whether there'll be an upstream fix or not.

**Comment by patrickhlauke** [comment]
My PR on clipboard.js has been merged, so once we grab the most recent release, this issue here will also be addressed https://github.com/zenorocha/clipboard.js/pull/807

**Comment by patrickhlauke** [comment]
do we need to actively grab the latest version of clipboard.js, or is this done automagically?

**Comment by patrickhlauke** [comment]
i see this is now fixed in `main`. closing.
