### ISSUE TITLE
Toast-timing is very inconsistent.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [twbs/bootstrap#33906]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) **Done, couldn't find any.**
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems. **Done, just two warnings because I generate some stuff with JS.**
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md) **Done.**

## Toast-timing is very inconsistent.
Sometimes it's the regular delay (for example 10 seconds), but sometimes the toast just disappears way quicker.

- Operating system and version: Linux Mint 20.1 Cinnamon
- Browser and version: Firefox
- I'm not sure how to compile that code into a test-case but I took a screen capture:

https://user-images.githubusercontent.com/59611881/117564418-3c738800-b0ac-11eb-8cc8-f9ed8f1fb249.mp4

**Comment by alpadev** [comment]
I think we need to clear the timeout in the `hide()` method as well. 🤔

**Comment by GeoSot** [comment]
@RyanBerliner any opinion on this, as you recently had a look on `toast.js`?

**Comment by RyanBerliner** [comment]
I don't believe clearing the timeout in the hide method would fix this issue (though it certainly wouldn't hurt), because the timeout is already being cleared in the show method. This looks to be the same bug that was fixed with #31155 - so I'd first recommend checking if version v5.0.0-alpha2 or later is being used.

**Comment by Glitchy-Tozier** [comment]
I used the version recommended in the bootstrap-dokumentation.

No idea whether that's tha alpha or not though.

**Comment by alpadev** [comment]
> I don't believe clearing the timeout in the hide method would fix this issue (though it certainly wouldn't hurt), because the timeout is already being cleared in the show method. This looks to be the same bug that was fixed with #31155 - so I'd first recommend checking if version v5.0.0-alpha2 or later is being used.

I agree, this shouldn't happen but it could if you manually close it through the dismiss button and initialize a new one without disposing the old one. IMO the problem in general is when the click handler looks something like this:

```js
button.addEventListener('click', () => {
  const toast = new bootstrap.Toast(toastEl);
  toast.show();
});
```

Hard to tell because we don't know what the code looked like, but

>The way i now got around this issue was by making the Toast a global variable in JS and then always doing toast.dispose() before showing it again.

suggests the OP used a code similiar to my example. In that case the timeout is never cleared and may overlap.

**Comment by Glitchy-Tozier** [comment]
@alpadev Yep, that's pretty much what I did.

**Comment by AucT** [comment]
if you still need a fix, I've posted here https://github.com/twbs/bootstrap/discussions/37577#discussioncomment-4320814
