### ISSUE TITLE
how to compile rtl versions in vue framework?

### ISSUE THREAD

**Issue by kindslayer** [twbs/bootstrap#33989]
Hi, I want to make an RTL version of CSS using RTLCSS and Vuejs but it doesn't work.

First of all, in my Vue project, I installed pre processor compilers `npm install -D sass-loader node-sass`. and append sass-loader config to my config like this.

    module.exports = {
      module: {
        rules: [
          {
            test: /\.scss$/,
            use: [
              'vue-style-loader',
              'css-loader',
              'sass-loader'
            ]
          }
        ]
      },
    }

This is my SCSS file.

    @import './partials/aviny';
    @import './partials/variables';
          
    @import '~@fortawesome/fontawesome-free/scss/fontawesome';
    @import '~@fortawesome/fontawesome-free/scss/solid';
    @import '~@fortawesome/fontawesome-free/scss/regular';
          
    @import "~bootstrap/scss/bootstrap";

    html{
       background : red /* rtl:green */
    }

and here is my index file 

<template>
  <p>Hello world!</p>
</template>

    <style src="assets/scss/main.scss" scoped></style>

**Comment by ffoodd** [comment]
Hi there. We don't provide support for RTLCSS nor Vue, please head to their docs or try on StackOverflow.

RTLCSS is a postcss plugin so you should have a look to postcss and Vue.

BTW your path to fontawesome seems wrong: `@fortawesome` won't work.

Closing this since it isn't an issue with Bootstrap.
