### ISSUE TITLE
Template example navbar should support multiple links

### ISSUE THREAD

**Issue by olimart** [twbs/bootstrap#33987]
Regarding this template https://getbootstrap.com/docs/5.0/examples/dashboard/

The current code does not support multiple links.
I understand it looks good as-is but at the same it should allow for some flexibility.

<img width="1421" alt="Capture d’écran, le 2021-05-14 à 15 11 39" src="https://user-images.githubusercontent.com/547754/118343352-7bfc0300-b4f6-11eb-8cbd-77129abaaf1c.png">

**Comment by alpadev** [comment]
This is only one example of a navbar. We got a whole example section for navbars https://getbootstrap.com/docs/5.0/examples/navbars/ and a documentation too https://getbootstrap.com/docs/5.0/components/navbar/.

AFAICT the examples are meant to be an inspiration and to showcase what you can do with our components not to provide you with a complete copy & paste solution.

**Comment by olimart** [comment]
I understand and went through the docs.
You can certainly not address everyone's needs with examples but at the same time and that's what I always appreciated with Bootstrap is that most of the time components are ready to go and you have the peace of mind they will work in all situations.

However here, it works with one link but breaks with two which I think is counter-intuitive and with the new utility-based direction, one has to figure out what tweaks and additional classes to add to the mix.

Feel free to close if the template cannot evolve ✌️

**Comment by ffoodd** [comment]
Well, the template could evolve (and will, opening a PR) since there's IMHO something to change here: this single link shouldn't be in a list item since it's the only one.

However when it comes to the use of such examples, you can't expect it'll exactly fit your needs: it's only an example, tailored on a semantic basis and using the less possible HTML and CSS to accomplish what it means to. As long as you're modifying it to fit your needs, well, you're modifying it.

There's not so much things we could do here since we can't predict what people will use our examples for.

In this specific case, using `.flex-row` on the `.navbar-nav` element is what you need.

**Comment by alpadev** [comment]
@olimart Sorry, I didn't mean to be rude or anything. Just wanted to point out that this is just an example that may not fit your needs perfectly. You made a valid point to some extent, which is why this issue wasn't closed. But as you said, it's impossible to predict what needs people might have and to address them all.

There is always room for improvements and we try our best to provide good solutions. As this is an open source project there is always the possibility to contribute with a PR to improve things.

**Comment by olimart** [comment]
@alpadev no worries I did not take it personal at all. The work done by the team is stellar and quite impressive, what a project.

@ffoodd thanks for the PR and suggestion will definitively give it a try soon.
