### ISSUE TITLE
Bug: scroll position changes when the button is dropdown

### ISSUE THREAD

**Issue by delef** [twbs/bootstrap#33993]
![009455260bd0a7ab75fc0c9d2f295f7b](https://user-images.githubusercontent.com/2103263/118356299-32a2c680-b57d-11eb-89a8-8c7ee56e1387.gif)

- Operating system and version: macOS, 11.3
- Browser and version: Safari, 14.1

**Comment by anderlaw** [comment]
bro, you need to provide steps to reproduce this issue

**Comment by alpadev** [comment]
Someone of @twbs/css-review owes me a coffee!😏

Figured it might be something with our JS. It happens because of the button receiving focus which is done programmatically in our script. (Safari doesn't focus a button automatically when you click it.. go figure)

The click that closes it returns focus to the body again, because we focus it only when we call `show()`. So toggling the dropdown like this, will make the focus change back and forth between body and button, as such the behaviour is repeating.

This only happens because the navbar is made `sticky` - with `fixed` it doesn't do that.

As a side note, I couldn't find any bug report about our page scrolling when you type something into the search. (Which happens for Chromium based, Firefox and Safari. Why I mention it? Because this is caused by the same thing..)

**Comment by ffoodd** [comment]
Does it only happen in Safari? I can't reproduce on either Firefox or Chromium on Ubuntu.

This looks like an odd browser bug, and since we don't use `scroll-padding-top` in Bootstrap itself I'd say that's not a big deal. Could try to find a workaround for Safari, but I probably won't take time to search for it :/

**Comment by ffoodd** [comment]
Ow and @alpadev up for the coffee ;)

**Comment by alpadev** [comment]
@ffoodd yeah the dropdown toggle scroll only happens in Safari.

Scrolling while typing into the search tho, happens for me on Chromium based and Firefox (nightly) on Windows, Safari on Mac.

![scroll-search](https://user-images.githubusercontent.com/2838324/118536843-81528b00-b74c-11eb-91ca-e3eb79bf9172.gif)
