### ISSUE TITLE
V4: checkbox-and-radio-buttons does not move “checked” to the active input

### ISSUE THREAD

**Issue by dilyanpalauzov** [twbs/bootstrap#34033]
I load https://getbootstrap.com/docs/4.6/components/buttons/#checkbox-and-radio-buttons in FIrefox/Chromium/Epiphany(WebKit).  On the Active|Radio|Radio line, the first label has class ‘active’ and its input has attribute “checked”.

I click on the last “Radio”.

The class “active* is removed from the first label, and added to the last label, which visually achieves the right thing.

However, the „checked“ attribute remains on the first input.  My understanding is, that for accessibility reasons, the checked attribute must be moved to the last input.

Please extend the example to move the checked attribute.

**Comment by dilyanpalauzov** [comment]
I mean, the HTML code in the Broswer’s Inspector shows `checked=""` on the initially checked element.  Iterating over the code by JavaScript seems to show the correct checked state.

**Comment by alpadev** [comment]
Yeah, we just update the checked property (or IDL attribute) of the element. The checked (content) attribute you refer here is not updated in that process because it defines the _defaultChecked_ property. You can find a description here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#htmlattrdefchecked

I think this behaviour is perfectly valid. @patrickhlauke do you have any insights from the a11y side? Do we have to change this?

**Comment by patrickhlauke** [comment]
@alpadev is correct. and yes, the behavior of the checkboxes/radio buttons is correct (and is exposed correctly to assistive technologies, changes correctly when using keyboard, etc).

@dilyanpalauzov for a quick visual verification that things are working properly, you can temporarily disable the `position:absolute` styling of the `<input>` and see that it all changes correctly.

![docs page with checkbox and radio, and chrome devtools showing position:absolute style unticked for the input - the actual inputs show up in the docs page](https://user-images.githubusercontent.com/895831/118878904-01612800-b8e8-11eb-8f35-d1ad65e6bef3.png)

**Comment by alpadev** [comment]
Thanks for confirming things! ❤️
