### ISSUE TITLE
V5 btn-light/btn-black hover and normal colours too close

### ISSUE THREAD

**Issue by iustin** [twbs/bootstrap#34123]
I'm not familiar with Bootstrap's color schemes/utilities to debug this, but from what I see, `btn-light` and `btn-black` have too "close" normal and hover colours:

* `btn-light`: v4 `#f8f9fa` with hover `#e2e6ea`, v5 `#f8f9fa` with hover `#f9fafb`
* `btn-dark`: v4 `#343a40` with hover `#23272b`, v5 `#212529` with hover `#1c1f23`

Using an online calculator, btn-light in v4 has a delta-E of ~7, wheras v5 has a delta-E of only 0.34, which means it's practically invisible.

In practice this can be seen by hovering in the [v4 docs](https://getbootstrap.com/docs/4.6/components/buttons/) vs. [v5 docs](https://getbootstrap.com/docs/5.0/components/buttons/), or thanks to helpful github rendering inline here (although the circles are too small to be clearly visible, but it is).

Is this intentional?

**Comment by ffoodd** [comment]
Probably, but that's still good to improve :)

**Comment by ffoodd** [comment]
FWIW it's because we check if background color should be light or dark (to contrast with foreground color) and apply either `tint()` or `shade()` on hover. Basically our dark and light backgrounds or too close to black and white, so that `tint()` and `shade()` aren't very effective.

**Comment by mdo** [comment]
See #36168 for a potential solution.

**Comment by fitcwill** [comment]
Noticed this was resolved in 5.2.0 but when applying the update to take advantage of this I noticed that the rounded corners changed so they don't appear so nicely when inside a card (the rounded corner is different to the rounded corner of the card)

![image](https://user-images.githubusercontent.com/49989660/180571008-a8c166e4-dcbe-43bd-8cea-03fb32010a5f.png)

![image](https://user-images.githubusercontent.com/49989660/180571053-7cb98f7d-1a49-41d1-9865-1773a2f2cf9f.png)

Sorry it's a tiny thing... but thought worthy of option nevertheless.  Easily missed and possibly even by design to someone in the know.

**Comment by mdo** [comment]
@fitcwill This was mentioned in our blog posts. Was an intentional design update :).
