### ISSUE TITLE
Docs: Global import of JS plugins with Webpack

### ISSUE THREAD

**Issue by olimart** [twbs/bootstrap#34122]
This is a suggestion regarding the docs about Webpack setup.
https://getbootstrap.com/docs/5.0/getting-started/webpack/#importing-javascript

The examples refer to the class name of each plugin `Alert`...
However, individual examples such as https://getbootstrap.com/docs/5.0/components/tooltips/#example-enable-tooltips-everywhere all begin by the root `bootstrap` object such as `return new bootstrap.Tooltip(tooltipTriggerEl)`

So, my question is, should a section explaining how to import all plugins at once with `import 'bootstrap'` be added?
If so, it should read `import bootstrap as 'bootstrap'` (pseudo-code since not sure how to do so) so individual examples work with Webpack import as well

Else for now we have to do the following:
```
import Tooltip from 'bootstrap/js/dist/tooltip'

var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new Tooltip(tooltipTriggerEl)
})
```

**Comment by GeoSot** [comment]
@olimart nice idea. 

We will appreciate any MR on this

**Comment by rcackerman** [comment]
The easiest way to do this is
```
import * as bootstrap from "bootstrap"
```

I'm coming from Python, which *strongly* encourages people not to import `*` so this feels not great. But I'm not sure if there's the same concerns in javascript.

**Comment by tobiasberge** [comment]
Hi,

I also ran into this recently reading the docs. And I ended up using [webpack.ProvidePlugin()](https://webpack.js.org/plugins/provide-plugin/) in our setup in order to provide a global "bootstrap" 😆  which might have been totally unnecessary using the import mentioned by rcackerman. So this example is definitely helpful in my opinion. 👍  

It seems that it was already added to the webpack docs for [5.1](https://getbootstrap.com/docs/5.1/getting-started/webpack/) as well as [5.2](https://getbootstrap.com/docs/5.2/getting-started/webpack/). Not sure if this issue should be considered as fixed.

However, looking at other JS examples (e.g. here: https://getbootstrap.com/docs/5.1/getting-started/javascript/#programmatic-api) the "bootstrap" is just there without import or something. And people might not actually read the bundler stuff and go straight to the examples.

Maybe it could be an idea, to add the import to all JS examples just to avoid all misunderstandings:

Current version:
```js
var myModalEl = document.getElementById('myModal')

var modal = new bootstrap.Modal(myModalEl) // initialized with defaults
var modal = new bootstrap.Modal(myModalEl, { keyboard: false }) // initialized with no keyboard
```

Always show global import?
```js
import * as bootstrap from 'bootstrap' // <--

var myModalEl = document.getElementById('myModal')

var modal = new bootstrap.Modal(myModalEl) // initialized with defaults
var modal = new bootstrap.Modal(myModalEl, { keyboard: false }) // initialized with no keyboard
```

Or show specific import in normal examples (Global is just an alternative in bundler docs)
```js
import { Modal } from 'bootstrap' // <--

var myModalEl = document.getElementById('myModal')

var modal = new Modal(myModalEl) // initialized with defaults
var modal = new Modal(myModalEl, { keyboard: false }) // initialized with no keyboard
```

What do you think? @olimart @GeoSot @rcackerman 

I would also be happy to make an MR for this if wanted.

**Comment by mdo** [comment]
Feel free to open PRs against the guides or in our twbs/examples repo if there’s more to do :). Otherwise closing as stale.
