### ISSUE TITLE
Modal window not displaying

### ISSUE THREAD

**Issue by LidinNT** [twbs/bootstrap#34268]
Hi,

This is regarding a bug related to displaying the modal window if the modal window body is defined on one file (we can call it as popUp.jsp) where the button/link to call the modal window is within a different file(call it as parent.jsp). In this scenario we are facing an issue like the modal window is not displaying on the GUI.

So that, we have modified the source file 'bootstrap.bundle.js'  by removing 'data.toggle(this);' from line no '4799' and placing the same on line no: '4758' to resolve the issue.

![image](https://user-images.githubusercontent.com/85997962/122229564-7e2af600-ced6-11eb-9e4d-19f1f0f2df5b.png)

![image](https://user-images.githubusercontent.com/85997962/122229656-9438b680-ced6-11eb-938e-2004321a7a11.png)

Please verify the fix and let us know if any harm on this.

Thanks in advance.

- Operating system and version - Windows 10
- Browser and version - Google Chrome Version 91.0.4472.106 (Official Build) (64-bit).

**Comment by alpadev** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by alpadev** [comment]
Looks like you're calling the modal through jQuery but without using `'toggle'` as parameter.

**Comment by LidinNT** [comment]
Thanks for the support.

We have added the 'data-bs-toggle="modal"' attribute in the modal button component and once clicking on the same nothing is happening. At the same time, we are getting the following console error.
![image](https://user-images.githubusercontent.com/85997962/123427307-182f2480-d5e2-11eb-8bcd-b31b2c14d6d1.png)

**Comment by alpadev** [comment]
I wasn't talking about adding `data-bs-toggle="modal"`. You seem to use jQuery to open a modal. You moved the `toggle()` from one spot into the jQuery interface to fix your problem. Instead of this I proposed to use `$(selector).modal('toggle')` instead of `$(selector).modal()`.

AFAIK JSP will render to some markup that is sent to the browser so it shouldn't matter if the code for the modal is within one file or several. To me it seems there is something wrong with the markup, that's why I asked you to create a codepen, so we're able to validate what's happening.

The error that is thrown because it can't find the modal so I assume you forgot to add `data-bs-target` or the selector is wrong.
