### ISSUE TITLE
non-centered vertical text alignment in Windows, due to the Segoe Ui system font 

### ISSUE THREAD

**Issue by egoson** [twbs/bootstrap#34294]
The Segoe UI font has a different line height from the rest of the system fonts, it cannot be fixed with css.

On Windows in the tooltip, this difference is very noticeable and brings discomfort to the user experience.

I see only two ways to solve the problem, these are additional styles that are activated if the user has Windows, or remove this font.

Additional overriding styles for Windows users:

```
.tooltip-inner {
     // some styles
    padding: 0.28rem .5rem;
}

.tooltip {
    // some styles
    line-height: 1.4;
}
```
MacOs
![mac-1](https://user-images.githubusercontent.com/42109109/122551852-9883e180-d046-11eb-8e90-c18221d4267e.jpg)
![mac](https://user-images.githubusercontent.com/42109109/122551859-99b50e80-d046-11eb-8402-ada6829cb94f.jpg)

Windows
![windows](https://user-images.githubusercontent.com/42109109/122551862-9a4da500-d046-11eb-8eac-2f8aec86680f.jpg)
![windows-1](https://user-images.githubusercontent.com/42109109/122551856-991c7800-d046-11eb-8ceb-bc1cc48d7c16.jpg)

Windows without Segoe UI
![without-segoe](https://user-images.githubusercontent.com/42109109/122552416-57400180-d047-11eb-9da8-ed9fc65aa915.jpg)

**Comment by mdo** [comment]
Yes, it's slightly different, but there's nothing we plan to do to change about this right now. Customizing styles per OS isn't something we want to get into. We've had this since v4 a few years ago, so nothing new here. Ideally we've limited the issues overall, but there's not much we can do short of rotating back to Arial or something equally terrible for today's screens.
