### ISSUE TITLE
Using .text-center . text-sm-start not working as it should in v5.0.1

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#34318]
Basically is not enforcing .txt-sm-start
instead is centering for all screen sizes
![image](https://user-images.githubusercontent.com/32283036/122804093-7502a600-d295-11eb-875b-136d9288398d.png)

I'm running Windows and using Firefox

**Comment by mdo** [comment]
Works for me: https://codepen.io/emdeoh/pen/mdWYELd.

Also, once you set `.col-12`, you don't need to set it to 12 columns again at the `sm` breakpoint unless it changes. 12 columns remains 12 columns until you say otherwise. So your classes can be simplified to `col-12 col-md-6` (and you can likely drop `col-12` as that's the default).

**Comment by tomasts248** [comment]
> Works for me: https://codepen.io/emdeoh/pen/mdWYELd.
Oh okey is problem on my end then. Thanks!

> Also, once you set .col-12, you don't need to set it to 12 columns again at the sm breakpoint unless it changes. 12 columns remains 12 columns until you say otherwise. So your classes can be simplified to col-12 col-md-6 (and you can likely drop col-12 as that's the default).
Nice!! Thank you so much for this!! :)
