### ISSUE TITLE
conflict enable-smooth-scroll in bootstrap 5

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#34337]
I have use [Easing jQuery](https://gsgd.co.uk/sandbox/jquery/easing/) with below code for nice smooth scroll effects. 
```
$('.smooth-scroll').on('click', function() {
    event.preventDefault();
    var sectionTo = $(this).attr('href');
	$('html, body').stop().animate({
      scrollTop: $(sectionTo).offset().top}, 1500, 'easeInOutExpo');
});
```

and It was working fine with Bootstrap 4. and, It is working fine in firefox browser with Bootstrap 5. but, **It does conflict and not work in Chrome browser with Bootstrap 5.** Because, Have added `scroll-behavior: smooth` in bootstrap 5. 

if, will added `scroll-behavior: auto;` for html tag in css. So, It does working fine.
So, will need to auto for scroll-behavior with css? or will need to something do with above jquery code? can you please guide which is proper way and what should to do for that?

**Comment by ffoodd** [comment]
`scroll-behavior: smooth` enables native smooth scrolling with CSS only. So you could basically drop your jQuery code.

The only thing your code allows and CSS can't handle (for now) is defining duration and timing function.

Your call to decide which one you need : disabling pour CSS feature is very straightforward thanks to `$enable-smooth-scroll` variable— but I obviously recommend to keep our CSS since it's native: no need for jQuery (nor JavaScript) and it accounts for user preference, which your code doesn't handle.

**Comment by circularchaos** [comment]
@ffoodd Thanks this works, I'm curious to know why this was added as it directly conflicts with the `easing` property in the jQuery code below. If `scroll-behavior: smooth` then the scroll behaviour applies easing to `html` else if `scroll-behavior: auto` then the jQuery code works as expected. 

```
$('html, body').animate({
        scrollTop: $(".section2").offset().top
}, 2000);
```
