### ISSUE TITLE
please change your navbar toggler icon it's very old now 

### ISSUE THREAD

**Issue by dipdey155** [twbs/bootstrap#34418]
please change your navbar toggler icon because it's very old now or give us tool or anything to change this icon I think as a user we have some rights to chose our own decision to what kind of component we want to use please change it or give use a tool or create a way change it our own. Thank you,  I think you appreciate use to take our own decision.

**Comment by devhoussam** [comment]
check `_variables.scss` file you will find 

`$navbar-light-toggler-icon-bg:      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'><path stroke='#{$navbar-light-color}' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/></svg>") !default;`

`$navbar-dark-toggler-icon-bg:       url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'><path stroke='#{$navbar-dark-color}' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/></svg>") !default;`


you can change the Icon from here

**Comment by chaziz94** [comment]
> please change your navbar toggler icon because it's very old

what do you mean by the navbar toggler icon being "old"?

**Comment by craftwerkberlin** [comment]
I think to know what @dipdey155 mean and see that in same way. 

The navbar-toggler is a button with straight design and less flexibility. It uses the colors from navbar-light/dark and a CSS generated svg. But it is what it is: a button. 

Compared to .btn-primary, .btn-outline-danger etc. the toggler does not fit to them. Place a button beside toggler in collapsed navbar and you will see the difference.

The important thing what the .navbar-toggler does is hiding it above the breakboints. This can be done by removing .navbar-toggler class and adding for example .d-lg-none to a toggler using one of the default buttons. 

But there are Bootstrap icons, which can be used as svg as well. In this case it would be better to remove all .navbar-toggler styles (included the icon), keep only display none to toggler above the breakpoints and move styles and icon to HTML by classes instead of predefined CSS.

From here, users have full freedom to choose button size, button style, button color and button content as they like. They can use Bootstrap Icons, an own image, text or any icon font of their choose for the toggler.

**Comment by mdo** [comment]
This can be changed with the Sass variables, or manual overrides. Closing for now—we can re-evaluate for v6 for more flexibility.
