### ISSUE TITLE
V5 Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34501]
this error shows up only in `5.0.2`, not in `5.0.1`  

![Image](https://i.imgur.com/7RIGeoQ.png)

**Comment by GeoSot** [comment]
@devhoussam  Please STOP making **spam issues**.  
Since 4 of April I am counting [70 issues](https://github.com/twbs/bootstrap/issues?q=is%3Aissue+author%3Adevhoussam+is%3Aclosed) of yours, most of them lack of description and at least an example

We are trying to help, as contributors, and not as full-time debuggers or wish Jinns 


If you want to help, there are steps you can follow:

* do I make proper usage of js/html markup?
*  do I respect the library guidelines?
* is it a real bug?
*  is it a logical requirement or I am trying to make it my way?
* if it is, can I describe it enough?
* lets try to make a full example with description, in order to help these poor contributors, saving some of their personal time 

PS:  Give it a real try next time, having in mind that most of the team members, are thankful developers, trying to give back
