### ISSUE TITLE
bootstrap.Modal.getInstance is not a function

### ISSUE THREAD

**Issue by jackdaniel9** [twbs/bootstrap#34510]
Hi,

Bootstrap return "bootstrap.Modal.getInstance is not a function" on "modal.show()".

1. Yes "modalContact" modal exist in html. 
2. Console.log(bootstrap) return this "{ Alert: ƒ, Button: ƒ, Carousel: ƒ, Collapse: ƒ, Dropdown: ƒ, … }" (Modal exist).

My code:

const bootstrap = require('bootstrap');
console.log(bootstrap);
var modalContact = document.getElementById('modalContact');
var modal = bootstrap.Modal.getInstance(modalContact);
modal.show(); ----> FAIL "bootstrap.Modal.getInstance is not a function"

If i make this:

var myModalEl = document.getElementById('modalContact');
var modal = new bootstrap.Modal(myModalEl);
modal.show(); ----> Open only backdrop

What i don't understand ?

Thank you

**Comment by GeoSot** [comment]
Hello @jackdaniel9 , Please it would be handy if you could provide a test page, to help see the problem

**Comment by jitangupta** [comment]
Hello,

I am facing the same issue, and to provide an example, please follow below steps:

1.  Visit bootstrap's modal's official document page https://getbootstrap.com/docs/5.0/components/modal/
2. Open console window and execute below commands
```
var modal = new bootstrap.Modal('#exampleModalToggle');
modal.show(); // This works
```
Now from anther function, if I want to hide this modal, I am not able to.

Here is what I have tried so far
```
var alreadyOpenedModal = bootstrap.Modal.getInstance('#exampleModalToggle');
```
Note: alreadyOpenedModal is null
```
console.log(alreadyOpenedModal);
alreadyOpenedModal.hide(); 
```
does nothing because alreadyOpenedModal._isShown is false
and if I set alreadyOpenedModal._isShown = true; manually, then the backdrop is not hiding
```
alreadyOpenedModal._isShown = true;
alreadyOpenedModal.hide(); 
```
the alternate way
```
var newModal = bootstrap.Modal.getOrCreateInstance('#exampleModalToggle');
```
 now I have new instance of Modal but it does not return the state of existing Modal i.e.
newModal._isShown is still false
```
newModal._isShown
```

**Comment by GeoSot** [comment]
Closing this as it lacks any reply

**Comment by marccollin** [comment]
an example here of this issue
https://jsfiddle.net/L46FX/2107/
