### ISSUE TITLE
Accordian not working properly

### ISSUE THREAD

**Issue by KrishAgarwal2811** [twbs/bootstrap#34567]
I am using bootstrap version 5.0.1 and made an accordian which works well in my local PC at the time of making it but when i hosted it online it isn't working. I tried changing the version too but no change.

My hosted site : [Krix Discord bot](https://krix.vercel.app/commands)

I hope I will get a response soon.

**Comment by mdo** [comment]
Make sure your URLs are correct when uploading. Since it works locally and not remotely, guessing the problem is in your setup.

**Comment by candacebutler8879** [comment]
I have reason to believe the person who hacked my accounts is using an enterprise account on GitHub with my other email address how can I fine out? I'm not real smart with this stuff the only reason I even know about this website is because I found it in my phone with multiple profiles in my name with different emails some of which are the ones im trying to get back into. I'm really sorry to ask for help with this but this person has invaded my entire life

**Comment by KrishAgarwal2811** [comment]
> Make sure your URLs are correct when uploading. Since it works locally and not remotely, guessing the problem is in your setup.

You mean the CDN links?

If yes then I have checked the CDNs thrice in my code and also in the rendered page. The CSS and JS files are connected.

**Comment by alpadev** [comment]
@KrishAgarwal2811 your markup is broken and the JS file isn't loaded.

**Comment by KrishAgarwal2811** [comment]
@alpadev I think I have impoted the js file the right way but even why isn't it loading. And my markdown is broken... How?

**Comment by alpadev** [comment]
> @alpadev I think I have impoted the js file the right way but even why isn't it loading. And my markdown is broken... How?

The  mark<ins>up</ins>, the HTML. Didn't you recognize, that half of your page isn't interpreted/rendered properly including the script tag? That's why the JS isn't loaded.

You need to replace the angle brackets (<, >) - see https://www.w3schools.com/html/html_entities.asp. Validate your HTML code with https://validator.w3.org/ and fix the errors and you should be fine.

**Comment by KrishAgarwal2811** [comment]
@alpadev Thanks a lot 🙏🙏

The main issue was with dots used in ids that was because I am using ejs and didn't realise those are using dots lol
