### ISSUE TITLE
V5 Feature Request: controlling the :hover, :focus, & Other States in HTML class Attribute

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34568]
it will be great and more helpful to all bootstrap users who use only Utility Classes to build UI without creating custom styles.

in my case, I always wondered why bootstrap did not support controlling: hover, focus, & Other States in HTML class Attribut

**Here is an example:**

`<button type="button" class="btn btn-lg bg-purple border-purple border-2 text-white hover:bg-primary hover:border-primary focus:bg-primary focus:border-primary">Button</button>`

**Reference:** https://tailwindcss.com/docs/hover-focus-and-other-states

**Comment by mdo** [comment]
This exists in the utilities API, you can modify it to add those utilities.

**Comment by devhoussam** [comment]
> This exists in the utilities API, you can modify it to add those utilities.

not explained in the docs?

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.0/utilities/api/#states

**Comment by alpadev** [comment]
> > This exists in the utilities API, you can modify it to add those utilities.
> 
> not explained in the docs?

Dang I was to post the same link 😄

This is pretty much the same request as with https://github.com/twbs/bootstrap/issues/34460

And since you obviously missed it.. Read the comment from @GeoSot https://github.com/twbs/bootstrap/issues/34501#issuecomment-879807210

Feel free to fork this repo and add stuff you want, or use tailwind if you prefer the utility approach.

We're not "wish Jinns".
