### ISSUE TITLE
V5 Modals: issue in position inside modal component

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34576]
I'm trying to change my close button position with some custom style but as I figure out that the position not working as expected it becomes ugly.

**issue example:**

https://codepen.io/themes4all/pen/xxdpdWZ

**reference:** https://getbootstrap.com/docs/5.0/utilities/position/

**Comment by GeoSot** [comment]
remove `.translate-middle`  

Ps: The scope of the issues is not, to teach, fix custom coding purposes.  Please try the [discussions](https://github.com/twbs/bootstrap/discussions) or [slack](https://bootstrap-slack.herokuapp.com/)

**Comment by devhoussam** [comment]
> remove `.translate-middle`
> 
> Ps: The scope of the issues is not, to teach, fix custom coding purposes. Please try the [discussions](https://github.com/twbs/bootstrap/discussions) or [slack](https://bootstrap-slack.herokuapp.com/)

you got the whole thing wrong. I'm not asking anyone to solve my problem try to visit my preview link and see exactly what I'm trying to explain

**Comment by devhoussam** [comment]
> > remove `.translate-middle`
> > Ps: The scope of the issues is not, to teach, fix custom coding purposes. Please try the [discussions](https://github.com/twbs/bootstrap/discussions) or [slack](https://bootstrap-slack.herokuapp.com/)
> 
> you got the whole thing wrong. I'm not asking anyone to solve my problem try to visit my preview link and see exactly what I'm trying to explain

the problem's not about removing `.translate-middle`

**Comment by alpadev** [comment]
Use `.position-absolute` instead of `.position-fixed` like it's used in the documentation and move the button underneath the `.modal-body` or the click area will be cut off..

We can't and won't cover every need there might be. If the stuff we provide doesn't satisfy your needs, you need to figure out a solution or research it on your own (or open a _proper_ feature request if you truly believe that this is something the _majority_ of our users might find useful).

Fixing issues is one thing, but we're definitely not here to teach a "Full Stack Web Developer PHP (Laravel - Symfony) Javascript (Angular - ReactJS - VueJS)" how to achieve certain things.

Keep in mind that we already offer stuff to the community without asking for anything in return. We use our spare time to move this project forward and there is really only a handful people who keep this project running.

Tailwind (which you mention a lot) sells pre-built components to fund their development, which allows them to work on it full-time, by the way.
