### ISSUE TITLE
Shadow helper not working in 5.1?

### ISSUE THREAD

**Issue by lowwhistler** [twbs/bootstrap#34858]
### Discussed in https://github.com/twbs/bootstrap/discussions/34816

<div type='discussions-op-text'>

<sup>Originally posted by **lowwhistler** August 24, 2021</sup>
Not sure what's happening, but for me, Shadow is rendering the box black. Even the docs page has them rendered black in Chrome and Firefox?

<img width="1058" alt="Shadow" src="https://user-images.githubusercontent.com/3652907/130652666-ed8b9369-bd3b-4e53-8da3-eb30657802a1.png">

</div>

**Comment by ffoodd** [comment]
What browser and version are you using? We need more info to investigate.

Also please don't double post with discussion. Either it's an issue or not.

**Comment by lowwhistler** [comment]
I'm new to this and trying to help. I thought that's what you were supposed to do, there's a link in discussion to create an issue.

Chrome Version 92.0.4515.159 (Official Build) (64-bit)
Firefox 91.0.2 (64-bit)
Win 10 19043.1200

**Comment by rafalkrupinski** [comment]
Same here - Firefox 91.0.2 (64-bit) macOS 11

**Comment by rafalkrupinski** [comment]
Perhaps related issue? - no gradient
<img width="961" alt="Screenshot 2021-08-31 at 23 13 15" src="https://user-images.githubusercontent.com/3732079/131576777-0c3a0a7d-d6e3-436a-bec8-061205ca6c8d.png">

**Comment by coliff** [comment]
heya @lowwhistler - perhaps it's because you are using a background color on the box? Try it without `bg-body` and they look correct. https://codepen.io/coliff/pen/PojNPmK

![image](https://user-images.githubusercontent.com/1212885/131591521-174f5aeb-15ec-48df-b706-3546a8f35ea7.png)

@rafalkrupinski I can see the gradients in that screenshot. It's quite subtle on its own but noticeable when compared to example above without gradients.

**Comment by lowwhistler** [comment]
Nice workaround but not practical for my use case. I can avoid upgrading until it's fixed

**Comment by coliff** [comment]
> Nice workaround but not practical for my use case. I can avoid upgrading until it's fixed

What do you mean? There isn't a problem with the shadow utility classes. The examples on the site are using `.bg-body` which has a bug which will be fixed in the next update (I reported that issue before #34688) but there isn't a problem with the shadow classes themselves. You don't need to use `.bg-body` with them.

**Comment by ffoodd** [comment]
Indeed, as @coliff explained shadows are correctly rendered but `.bg-body` has a bug in the current release. Closing this since utilities do work and the background bug is already fixed.
