### ISSUE TITLE
Bootstrap offer CSS Grid via CDN

### ISSUE THREAD

**Issue by nikkwong** [twbs/bootstrap#35450]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi, I opened thiis in the discussion but didn't receive a response.

Hi, I have a family of sites that I am taking care of. We would like to implement bootstrap or tailwind; but I prefer bootstrap. However, the project needs to use CSS Grid and cannot use sass to compile the source sass files. Are there any CDNs that have bootstrap available on the web that have CSS Grid enabled?

It's 2021 and I definitely think it's time to include CSS Grid by default! Hope there is a solution for this. Thanks.

### Motivation and context

There are many implementations which require CSS Grid.

**Comment by CoderHArsit** [comment]
hello sir,
I am a new comer here can you please elaborate the issue please so i can make progress in contributing towards resolving the issue.

**Comment by thewebartisan7** [comment]
You can find it here https://unpkg.com/browse/bootstrap@5.1.3/dist/css/

https://unpkg.com/browse/bootstrap@5.1.3/dist/css/bootstrap-grid.css

**Comment by ffoodd** [comment]
No, there's currently no distribution files with CSS Grids enabled. As mentionned in the docs, [it needs to be enabled in a Sass custom build](https://getbootstrap.com/docs/5.1/layout/css-grid/#how-it-works). Since this new grid replaces the previous (flex) one, they cannot live beside each other. So it's unlikely to be enabled by default before V6 — which hasn't started yet.

I'm not aware of any fork that'd switch to CSS Grid, but that could be something to look after.
