### ISSUE TITLE
Bootstrap for React/Vue

### ISSUE THREAD

**Issue by alexisenache** [twbs/bootstrap#35505]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap is still the main CSS toolkit I use to build websites. It is great. However, recently I started thinking about how will it evolve in order to remain relevant in the context where JS libraries are more and more used by developers. 

What is the best way to use Bootstrap with JS frameworks? Should I use Bootstrap as it is or do I need third-party libraries like Reacstrap? Wouldn't it be a good option to give developers the tools and documentation to build stuff in various environments? 

Thanks in advance!

**Comment by WinterSilence** [comment]
> Wouldn't it be a good option to give developers the tools and documentation to build stuff in various environments?

what tools you mean? In programming, there is a principle of single responsibility: package should not contain anything superfluous

**Comment by alexisenache** [comment]
I don't mean to add something to the actual package, but to add support for JS libraries for example. Another library maybe?

This way we don't rely on third-party libraries that are not updated or depend on other developers that are not in the core team. Also, this ensures a more consistent codebase and syntax. Third-party libraries are great but they are created by different people with different visions.

Anyways, it's just something worth discussing, at least for me it's something that would be very helpful.

Out of the box, Bootstrap is great for back-end frameworks like Laravel, but when it comes to front-end libraries, it is not that easy.

**Comment by WinterSilence** [comment]
@alexisenache what's you mean "add support for JS libraries"? can you show example?

> This way we don't rely on third-party libraries that are not updated or depend on other developers that are not in the core team. 

bs have only one optional dependency - popperjs
https://github.com/twbs/bootstrap/blob/63d38b19740eac25b8603dc9a9ae11e1df4667f7/package.json#L100

> Anyways, it's just something worth discussing, at least for me it's something that would be very helpful.

I'm trying to understand what exactly you want 

> Out of the box, Bootstrap is great for back-end frameworks like Laravel, but when it comes to front-end libraries, it is not that easy.

why? use bs5 with vue3, mithril  without any problem

**Comment by alexisenache** [comment]
> why? use bs5 with vue3, mithril without any problem

What about JS components: dropdowns, modals. I am referring more to those.

**Comment by WinterSilence** [comment]
@alexisenache BS component use event's and work fine with dynamic content generated by vue/mithril

**Comment by RyanBerliner** [comment]
(As already mentioned) loading bootstrap is all you need to do to make your dropdowns, modals, etc work inside your react or vue project. So long as the framework you're using outputs html onto the page, bootstrap is completely capable of initializing any of its interactive components with your html. However, there are some caveats and headaches (including but not limited to)

- properly disposing of bootstrap components when your framework removes dom nodes
- accessing bootstraps dom events with frameworks that use virtual doms can be cumbersome
- initializing bootstrap components on dom elements with frameworks that use virtual doms can be cumbersome (think tooltips & popovers that require manual initialization)

Solving these are possible, but could certainly be non-obvious unless you are very familiar with bootstrap and your javascript framework. Because of this, I do think there is utility in creating other (separate) bootstrap _wrappers_ that solve these problems without the need for complete re-implementations like reactstrap that you mentioned.

For example, I've created a wrapper for react that does exactly this called [bs5-react-elements](https://github.com/RyanBerliner/bs5-react-elements). It provides a better developer experience to use bootstrap in react projects. It handles the framework and bootstrap specific caveats without the need for the developer to handle it themselves.

IMO while small wrapper libraries like this one certainly aren't necessarily, they make life much easier. Other wrappers for other frameworks (either community or twbs maintained) could help a lot as people look to use bootstrap on their projects. I'm not entirely sure how this would align with bootstraps goals, but I do think its worth considering.

**Comment by ffoodd** [comment]
> This way we don't rely on third-party libraries that are not updated or depend on other developers that are not in the core team. 

That's probably why it won't happen any time soon, sadly. The core team is a few people only, all volunteers, and trying to maintain and improve Bootstrap core. Handling yet another side project is improbable due to the lack of time and capabilities.

> Third-party libraries are great but they are created by different people with different visions.
 
And for different needs, too. We cannot handle React, Angular, Vue, Svelte, etc. libraries on top of our core. Wrapper like your own exists, have maintainers, and anyone is free to contribute to it too.

FYI there're currently a few PR aiming at being more SSR-friendly, which covers a part of your request I guess?

In my opinion, if you're able to spot an issue on our side and provide a reduced test case, we'll consider working on a fix.
