### ISSUE TITLE
CDN file for new CSS Grid. Where is it?

### ISSUE THREAD

**Issue by webdev3301** [twbs/bootstrap#35845]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Where is the new Bootstrap 5.x CSS Grid actual CSS file? Please tell me someone didn't make it available only through SASS. Where is the source? I've searched all CDNs.

### Motivation and context

Because you got a manual page for code that can't just be looked at.

**Comment by ffoodd** [comment]
Duplicates #35450.

As explained in the docs, it's experimental and needs to be enabled through Sass.

**Comment by webdev3301** [comment]
So I have to learn SASS to compile CSS that is disabled by default to look at the CSS that could just be store in a text file.css

Got it.

**Comment by mdo** [comment]
> So I have to learn SASS to compile CSS that is disabled by default to look at the CSS that could just be store in a text file.css
> 
> 
> 
> Got it.

Your sarcasm aside, yes! We built something experimental and shipped it to get feedback. We're still not done with testing and iterating, as the note in our docs and blog post announcing the feature clearly indicate.

Instead of being annoyed we haven't yet done what you want and need, please consider that our time is limited, our focus sometimes elsewhere, and that PRs are always welcome. So if you want to play around with it—either in our docs or yes, with Sass—please don't hesitate! Otherwise, we will get to it in a future release :).

**Comment by webdev3301** [comment]
I'm done looking for your elusive grid update. No one knows where it is, or what it is but it's provocative! Gets people going!

How in God's name did you think something that can't even be accessed, something that you want people to try and post feedback on, should be first introduce to people in the most difficult way possible?

I'll go ahead and put my time to better use and learn Tailwind's Grid by just visiting the Grid page.

**Comment by ffoodd** [comment]
Feel free to fork Bootstrap by clicking the fork button, then tweak your Sass options and publish on npm.
