### ISSUE TITLE
Active Nav Tabs are not displayed correctly in the current main branch 

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#35986]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

current release looks good https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior
![grafik](https://user-images.githubusercontent.com/1651241/157604290-8c3237eb-8772-4958-9bb5-5e13f1265c8e.png)

current brunch looks bad https://twbs-bootstrap.netlify.app/docs/5.1/components/navs-tabs/#javascript-behavior
![grafik](https://user-images.githubusercontent.com/1651241/157604405-12be1745-a19f-4177-b550-0410fbe67308.png)

### Reduced test cases

https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior
https://twbs-bootstrap.netlify.app/docs/5.1/components/navs-tabs/#javascript-behavior

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3 and Current main Brunch

**Comment by mdo** [comment]
Same applies to our list groups and pagination. This is because we were doing some lazy Sass math like `-$list-group-border-width`, which with the CSS vars change for `border-width`, was generating `-var(--bs-border-width)` in our compiled CSS.

This does make me think we could either fix the problem with `calc()`, or we could call this a breaking change and drop it until a v6 when we can clean up all these things. I'm 50/50 and could go either way.

Thoughts?

**Comment by jonnysp** [comment]
works for me, can be applied
