### ISSUE TITLE
Scrollspy does not function within nav tabs

### ISSUE THREAD

**Issue by chrisrodkey** [twbs/bootstrap#36615]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am attempting to use Scrollspy within nav-tabs. Scrollspy _does_ work on the first tab of the nav tabs, but _not_ the second tab, or any other tabs. See the codepen for an example. 

### Reduced test cases

https://codepen.io/chrisrodkey/pen/PoQvOzQ

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v5.2 beta 1

**Comment by talesmota** [comment]
Hi @chrisrodkey, just to complement the issue, I have tried the codepen here with Ubuntu 20.04 and chrome. I realized that the Scrollspsy marks the Section1. If I roll the scroll down the Section 3 is marked and after Section 4 and so on. 

When I am in Section 3 if I roll the scroll up the Section 2 is marked. I realized if there are many anchors on visible area the Scrollspy marks the last one. Is the correct behavior?

Other test I have tried was change the height of the section content from 250px to 200px and the expect behavior worked. After that, I have tried increase a text inside the Sections and again the expected behavior worked again.

**Comment by GeoSot** [comment]
It doesn't work 'by design'  :/ ..... 

if you check:
 https://github.com/twbs/bootstrap/blob/d05c42a3979be30efc7a932c3c0f483098841b19/js/src/scrollspy.js#L207-L215
we omit not visible sections. Hidden tab of course content is not `visible`, so the scrollpsy entries are empty 
I don't think this is a bug.

Quick solution 

```js

document.querySelectorAll('#nav-tab>.nav-link').forEach(el =>
  el.addEventListener('shown.bs.tab', event => {
   const scrollElem= el.getAttribute('data-bs-target')+'>[data-bs-spy="scroll"]'
    bootstrap.ScrollSpy.getInstance(scrollElem).refresh()
  });
});
