### ISSUE TITLE
Toast max-width is width and padding-y is not set for body

### ISSUE THREAD

**Issue by TomONeill** [twbs/bootstrap#36623]
The `$toast-max-width` Sass variable is mapped to the `width` property:
https://github.com/twbs/bootstrap/blob/d05c42a3979be30efc7a932c3c0f483098841b19/scss/_toasts.scss#L19

The `$toast-padding-y` Sass variable is mapped to the `toast-header` class, but not to the `toast-body` class:
https://github.com/twbs/bootstrap/blob/d05c42a3979be30efc7a932c3c0f483098841b19/scss/_toasts.scss#L68
(only x is being applied)

**Comment by julien-deramond** [comment]
Not saying that it is normal or not but just for information for the one who will study/tackle this issue: it was [already the case before the integration of CSS vars](https://github.com/twbs/bootstrap/pull/35961/files#diff-84a7935decf58a2c246ba26d1a02eb8da154e35a704f32fc998921289c028387).

**Comment by mdo** [comment]
Both of these are intentional based on the project history. We didn't want to break existing Sass variables, so we kept them as-is and changed their property. Not the best, but easier than removing or deprecating.

As for the padding, for the toast body yes I wanted increased padding so I assigned the `-x` padding to all sides.

**Comment by mdo** [comment]
We can clean this up in v6 btw :).
