### ISSUE TITLE
min-vh-100 responsive classes like min-vh-sm-50 is not present

### ISSUE THREAD

**Issue by prakharisg** [twbs/bootstrap#36981]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

suppose if we add min-vh-100 (minimum viewport height is 100) now i want to change this height on responsive can u please provide it

### Reduced test cases

desktop & mobile is different 

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.2

**Comment by louismaximepiton** [comment]
Hi,

I don't think that this kind of feature will appear in Bootstrap since it'll increase the bundle size and won't be that useful for every single user. However here are some workarounds depending on what you're using:

- You can implement the classes you need yourself.
- You may modify the Bootstrap API map on your side by adding `responsive: true,`:
```css-scss
$utilities: (
  "min-viewport-height": (
    responsive: true,
    property: min-height,
    class: min-vh,
    values: (0: 0vh, 25: 25vh, 50: 50vh, 75: 75vh, 100: 100vh)
  ),
);
```
- You may have a `maps.scss` file and fill it with:
```css-scss
$utilities: map-merge(
  $utilities,
  (
    "min-viewport-height": (
      responsive: true,
      property: min-height,
      class: min-vh,
      values: (0: 0vh, 25: 25vh, 50: 50vh, 75: 75vh, 100: 100vh)
  )
);
```
