### ISSUE TITLE
Util getElement uses getElementById whenever possible

### ISSUE THREAD

**Issue by Mrks83** [twbs/bootstrap#37051]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The utility `getElement` currently uses `document.querySelector` if it detects a string. It would be nice in terms of speed and stability (see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id#sect2) to make use of `document.getElementById` once it detects a `#string`.

### Motivation and context

We use a Markdown page (rendered with Markdig) with bootstrap scrollspy and now it fails, whenever someone adds a `.` character in a headline string.

```
// markdown
## Release 1.0

// js
var nav = document.querySelector('#markdownToc .list-group');
document.querySelectorAll('#markdownContent h2[id]').forEach(h => {
    var anchor = document.createElement('a');
    anchor.textContent = h.textContent;
    anchor.className = 'list-group-item list-group-item-action';
    anchor.href = '#' + h.id;
    nav.appendChild(anchor);
});
var scrollSpy = new bootstrap.ScrollSpy(document.body, {
    target: '#markdownToc',
});

// browser console because of Scrollspy
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#release-1.0' is not a valid selector.
```

**Comment by GeoSot** [comment]
For now, please try to use a selector that is managed using `querySelector`

And let's start considering this change/feature. (Because of #35566 there have been spent some thoughts over this case.)

* Simple solution: 
    check if it starts with hash(#) and use `getElementById`. As far as I now the first minute of merging this change, a new issue 
   will be open saying. "I am trying to use a selector `#random-1/3 .foo` and a new adventure starts :rofl: 
   
   another issue will fairly ask "support Id selectors everywhere"

   etc  etc   etc


So maybe is a good start to add a PR using our internal SelectorEngine and if  #35566 is merged in the future it will solve all this ;)

**Comment by Mrks83** [comment]
Oh I‘ve missed #35566. I agree this will solve it. In the meanwhile we use another Markdown ID generator.
