### ISSUE TITLE
`.btn-link:hover` styles are overridden

### ISSUE THREAD

**Issue by NicoLB** [twbs/bootstrap#37130]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

All the styles from `.btn-link:hover` are overridden by `:not(.btn-check) + .btn:hover`.

With the following variables values 
```
$link-decoration = none;
$link-hover-decoration = underline;
```
the underline doesn't work for example.

### Reduced test cases

https://codepen.io/team/bootstrap/pen/qBamdLj

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.1

**Comment by RandScullard** [comment]
Just ran into the same issue. It looks like the problem was introduced in this commit: https://github.com/twbs/bootstrap/commit/32c457db4b6ff389efbd35772b24746c7ffb0b6d

In our case, the problem is caused by the second selector in this group, since it applies to any button that is the first child of its parent. Seems way too broad for its stated purpose:

    :not(.btn-check) + &:hover,
    &:first-child:hover {

Looks like we will revert to 5.2.0 for now.
