### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#37307]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The .text-opacity classes should have "!important" added

### Reduced test cases

Self explanatory, they are the only .text-* classes that don't have the "!important" and sometimes don't work.

While you are at it, why does .text-muted have a fixed color? It seems to assume that the text color is black.  So, to "mute" a colored text presumably one needs to use the .text-opacity classes, which is how I found the problem.

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.1

**Comment by mdo** [comment]
`.text-muted` doesn't use any new CSS variables, so it's not modifiable by `.text-opacity-*`. We don't need `!important` on the `.text-opacity-*` classes because they're only setting CSS variables.

`.text-muted`'s color is not yet computed based on body color and background color. That may change in v5.3.0, but we tried this earlier and had to roll it back during v5.2.0's development.
