### ISSUE TITLE
The activation target element is discontinuous

### ISSUE THREAD

**Issue by yyjiugui** [twbs/bootstrap#37302]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The activation target element is discontinuous, Guess the problem is caused by IntersectionObserver.

### Reduced test cases

case:  https://codepen.io/yyjiugui/pen/NWMeMPx

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.2

**Comment by GeoSot** [comment]
It would be a valid approach to just include the whole wrapper as observable
Example: https://getbootstrap.com/docs/5.2/components/scrollspy/#nested-nav

**Comment by chrisyeh96** [comment]
@GeoSot: even setting the whole wrapper to be observable still does not seem to solve this issue. See the following video, which is a screengrab from the current Boostrap v5.3.0-alpha3 docs page.

OS Information: Windows 11 version 22H2
Browsers tested: Microsoft Edge v112, and Mozilla Firefox v111.0.1

There are 2 major issues:
1. Sometimes, even when a child element is marked "active," the parent element is somehow not marked "active."
2. Sometimes, no element is marked "active," even when an element clearly should be marked "active."

https://user-images.githubusercontent.com/7686641/232427578-93cc6177-6e8d-470d-a94f-4612dc4d0b5d.mp4

This issue seems to have been introduced in Bootstrap v5.2 with the Scrollspy rewrite. This issue was is not present in Bootstrap v5.1.
