### ISSUE TITLE
navbar visibility error

### ISSUE THREAD

**Issue by majidp04** [twbs/bootstrap#37509]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

the navbar items are not visible by default.the collapse class name is conflicting

### Reduced test cases

navbar listing not working

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by julien-deramond** [comment]
@majidp04 or @iomes2 Could you provide a reduced test case on [CodePen](https://codepen.io/) or [StackBlitz](https://stackblitz.com/)? The description is not precise enough so that I can investigate.

**Comment by mdo** [comment]
Closing as stale.

**Comment by cesariouy** [comment]
In case it helps anyone else: I experienced a similar issue where collapsible navbar items were appearing invisible. It turned out the page in question was using both Bootstrap and Tailwind, and both frameworks define a `collapse` class. In my case the fix was as simple as keeping one and dropping the other, but for those who require both, Tailwind provides a [prefix option](https://tailwindcss.com/docs/configuration#prefix) to namespace its utility classes.
