### ISSUE TITLE
Toggler issue?

### ISSUE THREAD

**Issue by firely7** [twbs/bootstrap#37513]
I am very new to this and might be mistaken; but I used this code in https://www.codeply.com/ and it did  not work; you can see the hamburger button, however the dropdown menu is missing; may be someone wants to look into it?

```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
<div>
```

**The code that did work :** 

```
<navbar class="navbar navbar-expand-lg navbar-dark bg-dark">
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
    data-bs-target="#navbarTogglerDemo02" 
    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggler navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
<div>
```

**Comment by julien-deramond** [comment]
_I've added backticks in your description so that we could see the code_

In your first code, there are `data-toggle="collapse" data-target="#navbarTogglerDemo01"`. This is the old syntax. Now it is `data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"` (see https://getbootstrap.com/docs/5.2/components/navbar/#toggler).
