### ISSUE TITLE
Resposive visiblity class 

### ISSUE THREAD

**Issue by mdwalters** [twbs/bootstrap#37641]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

A responsive visiblity class would be helpful, like a class that shows only on a specific screen size.

### Motivation and context

I feel like a responsive visiblity class should be added because, for example, if a element is intended to be seen on smaller screens, it should not display on bigger screens and display on smaller screens.

**Comment by julien-deramond** [comment]
Thanks for opening this issue @mdwalters. Do you mean something linked to our [`.visibility` utility](https://getbootstrap.com/docs/5.2/utilities/visibility/)?
Because we have already [`d-(*-)none` classes](https://getbootstrap.com/docs/5.2/utilities/display/#notation): (e.g. `.d-none`, `d-sm-none` etc.).

**Comment by mdwalters** [comment]
> Do you mean something linked to our [`.visibility` utility](https://getbootstrap.com/docs/5.2/utilities/visibility/)?

yes

**Comment by mdwalters** [comment]
but since this already exists, should this be closed?
