### ISSUE TITLE
There is an unecessary `list-type` on the `.carousel-indicators` element

### ISSUE THREAD

**Issue by CyrilKrylatov** [twbs/bootstrap#37769]
Right here: https://github.com/twbs/bootstrap/blob/9e17b2b34cdec9dce063bba09b01aa9a63e7dd94/scss/_carousel.scss#L168

I think it could be removed as in the documentation Bootstrap is using a `div` element, not an `ul`.

If you think it's worth the shot, I could make a PR about it.

Should I make it?

One of my 2023 goal is to be more involved in Bootstrap, so it could be a good very first exercice for me!

✌️

**Comment by julien-deramond** [comment]
I did some archeology and when this line was introduced, carousel indicators in the documentation were created like this:

```
<ol class="carousel-indicators">
  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
  <li data-target="#myCarousel" data-slide-to="1"></li>
  <li data-target="#myCarousel" data-slide-to="2"></li>
</ol>
```

We can still find it in https://getbootstrap.com/docs/4.6/components/carousel/.
I don't have the history but I suppose taht we let that either because we forgot 😇 or to help with the migration from v4 to v5.

In v5, we don't provide anymore a carousel indicators example with `<ol>` + <li>`s but with `<div>` + `<button>`s. It's not mentioned in the docs that it could be done with lists.
So I'm not against dropping `list-style: none;` and changing the corresponding comment in the Sass file.
Thoughts @twbs/css-review? Any strong opinion to keep this style?

**Comment by mdo** [comment]
Can probably be removed—we dropped it in https://github.com/twbs/bootstrap/pull/32661 (v5 beta 2) and then backported it to v4.x.

**Comment by mdo** [comment]
@CyrilKrylatov I'd say go for it!

**Comment by CyrilKrylatov** [comment]
> @CyrilKrylatov I'd say go for it!

Yay! I'll do it within the week; can't wait to open my very first PR on Bootstrap!

**Comment by jeff-at-livecanvas** [comment]
IMHO using **ol / li** or **ul / li** tags looked a bit better, code-wise, at least at first sight.
But I can see why, semantically, it's not a big difference. Indicators bring little meaning inside the tag. 
Buttons totally make sense.

_From a practical POV:_
This change broke some old templates in our world - but no big issue. You will see a number close to the carousel indicator.

In case somebody finds it useful, you can fix things in old carousels by adding the **list-unstyled** class to the **ol**
