### ISSUE TITLE
SASS variables in compiled CSS output with 5.3.0-alpha1

### ISSUE THREAD

**Issue by picobots** [twbs/bootstrap#38166]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A handful of SASS variables seem to be sneaking through into the compiled CSS with Bootstrap 5.3.0-alpha1. This is a regression from 5.2.3.

I'm compiling Bootstrap using webpack, with an unmodified npm install of Bootstrap 5.3.0-alpha1 and the latest versions of node-sass (8.0.0) and sass-loader (13.2.0).

Am I missing something here? Is there a requirement change in the intended way of compiling SASS for Bootstrap 5.3.0-alpha1? Or are these calc declarations with SASS variables not being properly interpolated in Bootstrap source? e.g. `#{$var}`

----

# Example 1

For example, take the `.table-group-divider` rule in the file `_tables.scss` in 5.2.3 vs. 5.3.0-alpha1:

#### _tables.scss line 44:

```
.table-group-divider {
  border-top: ($table-border-width * 2) solid $table-group-separator-color;
}
```

#### Compiled output:

```
.table-group-divider { border-top: 2px solid currentcolor; }
```

#### _tables.scss line 44:

```
.table-group-divider {
  border-top: calc($table-border-width * 2) solid $table-group-separator-color; // stylelint-disable-line function-disallowed-list
}
```

#### Compiled output:

```
.table-group-divider { border-top: calc($table-border-width * 2) solid currentcolor; }
```

Note that **$table-border-width** incorrectly appears in the compiled output in 5.3.0-alpha1, which results is an invalid CSS rule.

----

# Example 2

Similarly, a variety of `$input-border-width` instances also incorrectly end up in the compiled CSS due to the change in how `$input-height-border` is defined in `_variables.scss`:

#### _variables.scss line 850:

```
$input-height-border:                   $input-border-width * 2 !default;
```

#### _variables.scss line 890:

```
$input-height-border:                   calc($input-border-width * 2) !default; // stylelint-disable-line function-disallowed-list
```

### Compiled output (in a variety of places):

```
min-height: calc(1.5em + 1rem + calc($input-border-width * 2));
```

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0-alpha1

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @picobots. I suppose that the two examples are linked to the following modification: https://github.com/twbs/bootstrap/commit/7cb376a8fd2133d28960c3a1a1fa2b5016747bae where the custom property is used instead of the Sass variable and so requires the usage of `calc()`.

I know that there were some issues in the past with the usage of `calc()`, but if I remember well, it was more due to some multiplication with negative values.

With our current compilation, there's no issue since we correctly have in `dist/css/bootstrap.css`, for the table example:
```css
.table-group-divider {
  border-top: calc(var(--bs-border-width) * 2) solid currentcolor;
}
```

I need to find a way to reproduce your issue. If someone can create a reproducible environment on StackBlitz for example, it would be great. Otherwise, I'll try to look at it when I'll find some time.

**Comment by mdo** [comment]
@julien-deramond is right, there's no issue on our end for the compilation, so we'll need a live demo to see what's going on.
