### ISSUE TITLE
Custom property ignored: not scoped to the top-level :root element

### ISSUE THREAD

**Issue by misiyevich** [twbs/bootstrap#38436]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

After upgrade my bootstrap from 3 to 5 version, i got tons of errors and warnings, include these (there are a lot of them):
![Ashampoo_Snap_11 апреля 2023 г _10h17m39s_003_](https://user-images.githubusercontent.com/117369147/231085446-5d385bc0-b038-437b-9d8d-1bfeac37b4b0.png)

`Custom property ignored: not scoped to the top-level :root element (.g-sm-1,.gx-sm-1 { ... --bs-gutter-x: ... }), in atrule`

But i never rewrote/used this variable `--bs-gutter-x`
What could be the reason?

### Reduced test cases

There is no ability to reproduse it in the sandbox, sorry.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3

**Comment by julien-deramond** [comment]
We have a lot of custom properties not scoped to the top-level `:root` element. For example:

https://github.com/twbs/bootstrap/blob/b000f2ace1cd70a141ff0a90f2d18a57d4ecfae4/dist/css/bootstrap.css#L738

It is voluntary.

So the warnings should be disabled in this precise use case in your PostCSS configuration (if I understand correctly the screenshot, they are generated by postcss-loader).
I've seen some things like https://github.com/MoOx/postcss-cssnext/issues/186 that could give you an idea of how to disable those warnings.

So I'm closing the issue since it's not an issue on Bootstrap side.
