### ISSUE TITLE
when using bg-dark text is disappeared

### ISSUE THREAD

**Issue by niirdan** [twbs/bootstrap#38430]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Good Evening Guys ! ,
I Found This Old issue : 
https://github.com/twbs/bootstrap/issues/36096
which I Suffer the Exact same bug in The New  V 5.3.0
When using bg-dark & texted-muted Text vanishes 
* same problem when I remove the 'text-muted' 
I Solved it By Downgrading to V 5.2.3
Please let me know if picture's from my project for the bug is necessarily (the pictures in the old issue is exactly the same problem that I suffer)

### Reduced test cases

Downgrading to V 5.2.3 "Solved" it ..

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v5.3.0

**Comment by mdo** [comment]
This is covered in our docs—we have new `.text-body-*` classes to do color mode friendly text colors.

**Comment by mdo** [comment]
That is, unless we want to revert #37890. Thoughts @julien-deramond?

**Comment by julien-deramond** [comment]
Regarding this issue, in https://twbs-bootstrap.netlify.app/docs/5.3/components/navbar/#color-schemes we are using `data-bs-theme="dark"` in combination with `.bg-dark`.
So in https://twbs-bootstrap.netlify.app/docs/5.3/components/navbar/#external-content, we could use it as well since `.bg-dark` is forced for this example in light and dark mode.
No need to change the rest of the content.
