### ISSUE TITLE
"Hugo Help New" Using Yarn

### ISSUE THREAD

**Issue by AvocadoVR** [twbs/bootstrap#38523]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I go into nodue_modles/bootstrap and run yarn install.  Everything installs as intended but then as I run a command like yarn run start or any other command on the docs it gives exits code and say "Unable to locate config file or directory" and to do "hugo help new"

![image](https://user-images.githubusercontent.com/103474655/235092132-5c809b6f-0540-4b59-ba81-ad224eff55d4.png)
![image](https://user-images.githubusercontent.com/103474655/235092162-735f1d77-1245-41ab-9c04-f4020326c716.png)

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.2.3

**Comment by julien-deramond** [comment]
Thanks for opening this issue @AvocadoVR but I'm not sure to understand what you're trying to achieve here.
If you need to run commands from the Bootstrap repository locally to see the docs (or anything else), you need to clone the repository instead of installing the package. More info in our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md#pull-requests).

Closing it since it is not an issue.
If you need help to contribute to the project, you can create a [new discussion](https://github.com/orgs/twbs/discussions/categories/q-a) where the community will be able to help you.
