### ISSUE TITLE
Add support for Offcanvas sizes (like `offcanvas-size-lg`, `offcanvas-size-xl`)

### ISSUE THREAD

**Issue by marceloverdijk** [twbs/bootstrap#38557]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The [Offcanvas](https://getbootstrap.com/docs/5.2/components/offcanvas/) component has a "fixed" width of 400px (adjustable via `$offcanvas-horizontal-width`) for any breakpoint.

It would be very useful to have different size options similar as Modal also has optional [sizes](https://getbootstrap.com/docs/5.2/components/modal/#optional-sizes).

Like:

offcanvas-size-sm (default 300px)
offcanvas (default 400px)
offcanvas-size-lg: 500px
offcanvas-size-xl: 600px
offcanvas-size-xxl: 700px

Proposed withs are just an example.

### Motivation and context

This especially useful as screens tend to get wider and wider but one still wants to use a Offcanvas to hide some content by default; like an advanced filtering pane.

**Comment by mootezaloui** [comment]
You appear to be making an effort to support the creation of the Offcanvas component inside the Bootstrap open source project. In the problem you brought up, it is suggested that support be added for several Offcanvas sizes, such "offcanvas-size-sm," "offcanvas-size-lg," "offcanvas-size-xl," etc.

The existing Offcanvas code could be changed to support these new size classes and the Offcanvas width could be adjusted as a result. To support the "offcanvas-size-lg" class, you might edit the Offcanvas code as shown in the following example:


`.offcanvas-size-lg {`
  `width: 500px; /* Change the width to 500px */`
`}`

`.offcanvas.show.offcanvas-size-lg {`
 ` transform: translateX(0); /* Reset the transform property */`
`}`




For the other size classes, you can also apply equivalent CSS rules. The JavaScript code for the Offcanvas must also be changed in order to handle these new size classes and toggle the proper class when the Offcanvas is opened.

Before sending a pull request, don't forget to test your changes properly and make sure they work on all popular browsers and gadgets.

**Comment by mdo** [comment]
No plans to change the width here ourselves—feel free to address this in your own overrides :).
