### ISSUE TITLE
Bootstrap's RTL version in Persian

### ISSUE THREAD

**Issue by hajivalie** [twbs/bootstrap#38598]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Use Persian Language and Fonts (Sahel or Yekan) for RTL examples

### Motivation and context

Thank you for the RTL example, but it is not user-friendly for Persian languages

**Comment by julien-deramond** [comment]
Thanks for opening this issue @hajivalie.

What do you mean by "it is not user-friendly for Persian languages"? Is something missing or not working while using [Bootstrap RTL](https://getbootstrap.com/docs/5.3/getting-started/rtl/) for websites using Persian languages?

The aim of RTL examples is mainly to show that RTL is working with all of our examples, show how in the code, and also for us to avoid RTL non-regression more easily.

**Comment by hajivalie** [comment]
Arabic and Persian fonts are different. And it is better to have a page from right to left in Persian language in the examples

**Comment by julien-deramond** [comment]
Thanks for the proposal but we're going to stick with Arabic as an example of RTL in Bootstrap as we can't maintain several different languages. Let's keep in mind as an improvement in the future the fact that it's not user-friendly for all, and maybe try to provide a switch to show these examples in "English RTL" as well in order to distinguish more easily the elements of the layout for non-Arabic speakers.
