### ISSUE TITLE
themeSwitcher[aria-label] Attribute values ​​that are not multi-locale-friendly should not be used

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#38649]
https://github.com/twbs/bootstrap/blob/f0be063c9792f6fd123d933335efd0d8cc7f6f1f/site/static/docs/5.3/assets/js/color-modes.js#L52

(${btnToActive.dataset.bsThemeValue})

This value is only suitable for use in the English environment, not suitable for other languages, and will cause people with disabilities to learn the meaning of the corresponding characters in English, as well as English words in other color modes.

In addition, the current script is only suitable for the case where there is only one color mode set on the page, or the case where the color mode and color matching mode are separated, it will not be suitable.

**Comment by ZhangChengLin** [comment]
demo address
https://jzeg-net.github.io/bs-themeSwitcher/5.3/index.html
http://jzeg-net.github.io/bs-themeSwitcher/

Because this color mode involves the entire page, it needs to be adapted to quite a few common popular layouts. I hope that Bootstrap can make scripts more compatible as much as possible. Of course, if the goal of this script is that only Bootstrap's official website is available, then in the current situation, it works very well.

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @ZhangChengLin 

IMO this `color-modes.js` is more an example extracted from our own documentation (only in English), rather than something that can be used as-is for all use cases. It can help some folks to start from something simple, and adapt it depending on what they are building.

It is mentioned partially in https://twbs-bootstrap.netlify.app/docs/5.3/customize/color-modes/#javascript but isn't maybe very clear 🤷 

Do you have some suggestions to improve this script so that it can be more useful for folks in general but still close to our documentation use case?

**Comment by mdo** [comment]
Closing as this is definitely just an example.
