### ISSUE TITLE
--body-font-family doesn't adhere to $prefix - var(--bs-font-sans-serif)

### ISSUE THREAD

**Issue by WilliamStam** [twbs/bootstrap#38866]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

when changing the prefix `$prefix: '';`  (blank but can be anything) the `--body-font-family` still uses `--bs-` prefix ie   `--body-font-family: var(--bs-font-sans-serif);` no matter what you change the prefix to. (when self compiling it from scss)

![image](https://github.com/twbs/bootstrap/assets/182800/73def2d0-eb9e-4d8a-a7b4-4ca4c6610d03)

### Reduced test cases

```
// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "bootstrap/scss/functions";

// 2. Include any default variable overrides here
$prefix: "";

// 3. Include remainder of required Bootstrap stylesheets (including any separate color mode stylesheets)

// 4. Include any default map overrides here

// 5. Include remainder of required parts
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/root";

// 6. Optionally include any other parts as needed
@import "bootstrap/scss/utilities";
@import "bootstrap/scss/reboot";


@import "bootstrap/scss/helpers";

// 7. Optionally include utilities API last to generate classes based on the Sass map in `_utilities.scss`

// 8. Add additional custom code here
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @WilliamStam.
Tried it in https://stackblitz.com/edit/github-lffuht?file=src%2Fscss%2Fstyles.scss,src%2Findex.html with the following Sass code:

```scss
@import 'bootstrap/scss/functions';

$prefix: yo-;

@import 'bootstrap/scss/variables';
// [...]
```

When I use `<h1 style="color: var(--yo-primary)">Yo</h1>`, the text color is blue as it should be (primary color).
And:

![Screenshot 2023-07-04 at 13 55 07](https://github.com/twbs/bootstrap/assets/17381666/c1c1bd8a-66fa-46cb-8513-294e0f65c0f9)

In your reduced test case, I don't see the import of `variables`, maybe something is missing in your project.

Closing it since it seems to be rather a usage issue. If you still got a problem with it, please create a [Q&A discussion](https://github.com/orgs/twbs/discussions/new?category=q-a), and someone from the community hopefully will be able to help :)
