### ISSUE TITLE
Files not been copied to project source folder after added with nuget package manager in Visual Studio 2022 - v.17.6.5 

### ISSUE THREAD

**Issue by tHesTx** [twbs/bootstrap#38932]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I created a new `.net 6.0 MVC Web` project and removed the preinstalled bootstrap from `wwwroot/lib` because I wanted to add it with NuGet Package Manager. After installing the package (bootstrap v5.3.0), files are shown as a reference in my `wwwroot`, and when I try to link them from code browser gives not found error cause they don't actually exists in my project.

Now I'm trying this: `<link rel="stylesheet" href="~/css/bootstrap.min.css" />` but as I said is not working. The only solution I've got is to copy those file from `C\..nuget\packages` to my `wwwroot` but I've read that this reference is actually an intended behaviour from Microsoft, so it should be a way to use those referenced files but I can't seem to find it.

Also [this](https://developercommunity.visualstudio.com/t/NuGet-Package-Content-is-not-copied/25259#T-N244926) comment suggests that is a nuget bug not a Visual Studio bug.

I have a post [here ](https://stackoverflow.com/questions/76673639/visual-studio-2022-v-17-6-5-link-installed-nuget-package-css-file-in-layout?noredirect=1#comment135244895_76673639) with a screen 

### Reduced test cases

Steps to reproduce:

1. Start new .net core 6 MVC project
2. Remove preinstalled bootstrap files 
3. Add with Nuget Package Manager latest stable version of bootstrap (v.5.3.0 in my case)

As a result, files are showed in `wwwroot/css` and `wwwroot/js` folder but as a simple reference, they are not physically there - so when I try to build the project, not styles or scripts of bootstrap are loaded because they could not be found.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0

**Comment by mdo** [comment]
This sounds like a problem with some starter project and not with Bootstrap.

**Comment by HeinziAT** [comment]
@mdo The "starter project" is only used in the repo instructions, this is a general issue. It appears that the bootstrap nuget package works as intended with ASP.NET 4.8 projects, but not with ASP.NET 5+ (aka Core) projects.

This issue has also been documented in quite a few SO questions, all of which have the "solution" of not using nuget:

https://stackoverflow.com/q/76673639/87698
https://stackoverflow.com/q/68353885/87698
https://stackoverflow.com/q/57038463/87698

Apparently, in ASP.NET 5+ projects, the relevant files are just linked instead of copied to the project. If you copy the files manually, you lose the ability to manage your dependency with nuget, i.e., upgrading the nuget package will (obviously) not upgrade the files you copied manually into your project.

Unfortunately, I am only familiar with consuming nuget packages, not with writing them, so I don't know whether this can be fixed. If it can't be fixed (which would be a pity, since it's *extremely* convenient to have all .NET dependencies managed by the same system), it would be nice to somehow mark the package as "not compatible with .NET 5+".
