### ISSUE TITLE
Help with Vue 3 adaptation of Carousel

### ISSUE THREAD

**Issue by VividLemon** [twbs/bootstrap#38997]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Normally I don't need help with the Vue adapation. Usually things are straightforward. However, some sore spots are transitions. They can be difficult, especially because not all transitions are built the same. 

One thing that's presenting an issue to me is the carousel. Previously I somehow made it work by reversing the direction of the start/end carousel items https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue#L160 and the carousel item being declared in the transition class -- rather than just being a static class. 

I tried to fix it in this in this diff https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/main...VividLemon:bootstrap-vue-next:carousel-hack#diff-add493a7ac584c35f6cbfa84f4f62bec7152e3b9c0ff8cd1eed7398d4871b2a1
The previous worked "fine", but it suffered from the mentioned above issues.
I mention it in the code https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/77fe9cd85cc911bca5aaff41294afead30e52dc4/packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue#L153

I can upload a video of what occurs, but the most straightforward way to play with it yourself is to 

```
clone https://github.com/VividLemon/bootstrap-vue-next.git 
git switch carousel-hack
pnpm i
pnpm dev --filter bootstrap-vue-next
```
Then open the dev link that appears
When clicking through the controls, it does two things, first, it stutters around, the second issue, it clips on the ends. It seems as if it's out of sync. I have a hard time believing it's strictly a Vue issue, and more it's an issue with both Vue and Bootstrap. 

It would be a great help to get some official Bootstrap support on this issue, as I seemingly can't get this one done alone.

### Reduced test cases

na

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
This sounds like a question for the Vue Bootstrap project instead of here.

**Comment by VividLemon** [comment]
> This sounds like a question for the Vue Bootstrap project instead of here.

I am the project 👀 lol

**Comment by julien-deramond** [comment]
@VividLemon I'll try to look at it. Seems like your `carousel-hack` branch doesn't exist anymore. Is there another branch to use or maybe it's been merged already in the _main_ branch?

**Comment by VividLemon** [comment]
> @VividLemon I'll try to look at it. Seems like your `carousel-hack` branch doesn't exist anymore. Is there another branch to use or maybe it's been merged already in the _main_ branch?

@julien-deramond Sorry about that. 

https://github.com/VividLemon/bootstrap-vue-next/tree/carousel-hack it's strange. There doesn't seem to be any difference between the Bootstrap classes that are added during transition and the classes I add during transition. 

https://github.com/VividLemon/bootstrap-vue-next/blob/carousel-hack/packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue#L158

**Comment by julien-deramond** [comment]
So I tried the `carousel-hack` branch and not yet the other version in [bootstrap-vue-next/main](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue#L160).

I've added the following CSS override in `styles.scss` to see the animation more slowly and the classes added and removed more easily:
```scss
.carousel-item {
  transition: transform 2s ease-in-out !important;
}
```

Also added temporarily the following CSS to see more what's in action:
```css
.carousel-item-next:not(.carousel-item-start),
.active.carousel-item-end {
  transform: translateX(100%) translateY(50%) !important;
}

.carousel-item-prev:not(.carousel-item-end),
.active.carousel-item-start {
  transform: translateX(-100%) translateY(50%) !important;
}
```

I'm not that familiar with Vue.js but the combo of `Transition` + `v-for` + `v-show` would probably make only one item displayed at the same time. When we transition from one slide to another, there's an extra `display: none` inline CSS for slides that are not the current one. It seems to be added directly by Vue with the combo mentioned before since it's not done "manually" by your code in `BCarouselSlide.vue` and/or `BCarousel.vue`. This extra forced `display: none` could cause an issue because it's handled directly with the classes in Bootstrap:

```css
.carousel-item {
  /* ... */
  display: none; 
  /* ... */
}

.carousel-item.active,
.carousel-item-next,
.carousel-item-prev {
  display: block;
}
```

And anyway, two slides must appear at the same time during the animation.

Based on this observation, I've started to modify the `*.vue` files and naturally, based on the documentation, tried out `TransitionGroup`. Now I can see that's what you've done in [bootstrap-vue-next/main](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue#L160). I'll try to check what you've done here as well to compare.

But based on these first observations, it seems that the combination of Bootstrap classes used in your `*.vue` files are the right ones and rather at the right time in the chain of events. Maybe there's a timing issue coming from the Vue transitions or something, I'm not sure yet what happens here for now.
