### ISSUE TITLE
navbar-toggler-icon and CSP

### ISSUE THREAD

**Issue by Tealk** [twbs/bootstrap#39040]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

I noticed that the navbar-toggler-icon is not displayed when you set the following csp

```
default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self'; object-src 'none'; media-src 'none'; frame-src 'none'; frame-ancestors 'none'; form-action 'none'; connect-src 'self';
```

```
Content-Security-Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml,%3csvg xmlns='http://… (“img-src”).
```

### Reduced test cases

You can see it here when you select a mobile width: https://rollenspiel.monster

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.1

**Comment by geronimoD18** [comment]
I had that happen to me a few days ago. I just don't remember how I solved it. I think I changed the class to light instead of dark or something like that.

**Comment by RedBeret** [comment]
Hello @Tealk,

I looked into your issue report and after researching a bit, it seems that the error you're seeing is because of the Content Security Policy (CSP) blocking the inline SVG data URI used by the `navbar-toggler-icon`.

Your current CSP is:

```
default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self'; object-src 'none'; media-src 'none'; frame-src 'none'; frame-ancestors 'none'; form-action 'none'; connect-src 'self';
```

From what I've gathered, the directive `img-src 'self'` means that images can only be loaded from the same source. Now, Bootstrap's `navbar-toggler-icon` is using an inline SVG data URI, and that's what's getting blocked by your CSP.

To fix this, you might want to tweak the `img-src` part of your CSP to allow `data:` URIs as well. Like this:

```
img-src 'self' data:;
```

So, incorporating that change, your CSP would look more like:

```
default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data:; object-src 'none'; media-src 'none'; frame-src 'none'; frame-ancestors 'none'; form-action 'none'; connect-src 'self';
```

Just a word of caution: security settings can be tricky, so always ensure you're confident in any changes you make.

Hope this helps and clears things up a bit!

**Comment by Tealk** [comment]
> To fix this, you might want to tweak the `img-src` part of your CSP to allow `data:` URIs as well. Like this:

Hi, thanks for the explanation but I know that; my concern was more if it could not customize it in Bootstrap so that you do not need this data: attribute?

In general I think CSP will be used more and more often and it would be nice if the users would have to put less effort into creating the CSP.

**Comment by ff0041** [comment]
If you build Bootstrap with Webpack, you can extract SVGs into separate files following the documentation at https://getbootstrap.com/docs/5.3/getting-started/webpack/#extracting-svg-files

**Comment by mdo** [comment]
CSP issues are something we cover in our docs, closing out as there's nothing else to do here for us. Even in a potential v6 world, I don't see us fully eradicating embedded SVGs due to elements like checkboxes and radios.
