### ISSUE TITLE
link issue

### ISSUE THREAD

**Issue by klaustransformtranslatey** [twbs/bootstrap#39178]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

i can not link my ejs file with bootstrap using the <link> attribute however i tried multiple versions 
my code :
![image](https://github.com/twbs/bootstrap/assets/134975959/f83c2b11-a394-4dea-884b-2794c0baea6d)the error:
![image](https://github.com/twbs/bootstrap/assets/134975959/90728a05-25f5-4aed-a7f0-5d848d98c9d9)

### Reduced test cases

![image](https://github.com/twbs/bootstrap/assets/134975959/0e989050-4565-420e-8733-809323598399)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.3

**Comment by klaustransformtranslatey** [comment]
![image](https://github.com/twbs/bootstrap/assets/134975959/e28a8ec2-8d91-4d5d-89d8-533f3be2b7b3)

**Comment by julien-deramond** [comment]
Is it working with [this CodePen link](https://codepen.io/team/bootstrap/pen/qBamdLj)? If you have the same error, it's probably because `cdn.jsdelivr.net` is blocked by some network rules: in your company, country, or others.
- It can be linked to something like https://github.com/orgs/twbs/discussions/39143 or https://github.com/orgs/twbs/discussions/38782

If that's the case, you can try some [Alternative CDNs](https://deploy-preview-39179--twbs-bootstrap.netlify.app/docs/5.3/getting-started/download/#alternative-cdns).

**Comment by mdo** [comment]
Closing out given this sounds like an isolated incident.
