### ISSUE TITLE
Issue on Navbar toggler button in mobile view

### ISSUE THREAD

**Issue by Haseeb3952** [twbs/bootstrap#39232]
Whenever we use #id in our website when we click on nav-link in mobile view Navbar automatic did't turn off i think there you need to correct it

**Comment by pragyamishra56** [comment]
hey i can resolve this issue

**Comment by julien-deramond** [comment]
Thanks for opening an issue @Haseeb3952 
However, I'm going to close it as invalid since no issue template has been used and the description is not detailed enough.
Please use [the issue template](https://github.com/twbs/bootstrap/issues/new?assignees=-&labels=bug&projects=&template=bug_report.yml&title=Provide+a+general+summary+of+the+issue).
