### ISSUE TITLE
Floating labels direcrtion issue with RTL

### ISSUE THREAD

**Issue by mrgharabaghi** [twbs/bootstrap#39251]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The label stays in the left side.

![a](https://github.com/twbs/bootstrap/assets/40915667/e03e52c2-59d0-4406-9a54-466a140bcf30)

### Reduced test cases

```html
<html lang="ar" dir="rtl">

<div class="form-floating">
    <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
    <label for="floatingPassword">رمز</label>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3.2

**Comment by julien-deramond** [comment]
Thanks for opening this issue @mrgharabaghi 
Tried your example from our [RTL starter template](https://getbootstrap.com/docs/5.3/getting-started/rtl/#starter-template): https://codepen.io/julien-deramond/pen/GRPGBQy
It seems to work well. Maybe you've loaded `bootstrap.min.css` instead of `bootstrap.rtl.min.css`?

**Comment by mrgharabaghi** [comment]
You are right Julien.
Working well by changing the `bootstrap.min.css` to `bootstrap.rtl.min.css`.
Thank you.
