### ISSUE TITLE
Styling does not work on higher resolutions

### ISSUE THREAD

**Issue by thomaswcptgroup** [twbs/bootstrap#39333]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A lot of the styling, doesn't appear on higher resolutions. 

### Reduced test cases

css classes wrapper bg-white rounded shadow and table-striped  styles not appearing on 3840 x 2160. 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.2

**Comment by julien-deramond** [comment]
Hello @thomaswcptgroup. Thanks for reporting this issue.
Would you mind updating your issue's description by adding a **live demo** of the issue (e.g. a specific use case that doesn't work) by creating a reduced test case on [CodePen](https://codepen.io/) or [StackBlitz](https://stackblitz.com/), or by just sharing a link in the documentation where it doesn't work.
And also please add the corresponding screenshots so that we can see the broken rendering, and so that other members of the community can double-check if they have the same issue. On my side, can only test until 3440x1440.

**Comment by thomaswcptgroup** [comment]
After further, analysis I found that it's the colors used in with the stripping and the shadow that seems to be an issue.

**Comment by mdo** [comment]
This is very not likely a bug—we don't do anything to scope styles by resolution other than `min-width` media queries, which doesn't exclude any styling or screen size.
