### ISSUE TITLE
Incorrect link to v.5.x starter project

### ISSUE THREAD

**Issue by curious-broccoli** [twbs/bootstrap#39361]
https://github.com/twbs/bootstrap/blob/a4d2f597029cb36169bb2e20252317198cdd988d/site/layouts/partials/callouts/info-npm-starter.md?plain=1#L1 
..links to a repository for Bootstrap 4, which has a link to [Bootstrap 5 examples](https://github.com/twbs/examples) as well. So I think it should directly link to the Boostrap 5 examples.

Bootstrap version: v.5.x

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @curious-broccoli 
I'm not sure to catch the issue here.

> links to a repository for Bootstrap 4

The link that you mention is https://github.com/twbs/examples/tree/main/sass-js. This is the "Bootstrap Sass & JS" (Bootstrap 5) sub-project within `twbs/examples`. So the link is right.

As you can see, in the `package.json` of this sub-project, Bootstrap 5 is used:
https://github.com/twbs/examples/blob/570cee2dbf6f7e5fb4eac233ae15509f5ff823fd/sass-js/package.json#L24

**Comment by curious-broccoli** [comment]
Ah sorry, in https://github.com/twbs/bootstrap/commit/8a3540803015cf9e1a9406ad7ffbfb264ac72ec9 it was already changed for 5.3. I didn't see that because the 5.2 docs don't show the 5.3 as latest in the small version dropdown
