### ISSUE TITLE
Automatically Remove Unused CSS and JavaScript Code in Bootstrap Builds

### ISSUE THREAD

**Issue by sabeerbikba** [twbs/bootstrap#39469]
### Discussed in https://github.com/orgs/twbs/discussions/39451

<div type='discussions-op-text'>

<sup>Originally posted by **sabeerbikba** November 29, 2023</sup>

Currently, Bootstrap includes all of its CSS and JavaScript code in the production build, even if not all of the code is used by the application. This can lead to larger page sizes and slower loading times. Tailwind CSS addresses this issue by automatically removing unused CSS code during the production build process.

We propose implementing a similar feature for Bootstrap to automatically remove unused CSS and JavaScript code during the production build process. This would improve page performance and provide a more consistent development experience with Tailwind CSS.

**Benefits:**

* **Reduced page size:** By removing unused code, the production build size of Bootstrap would be significantly smaller, leading to faster loading times.
* **Improved performance:** Smaller page sizes translate to improved page performance, providing a better user experience.
* **Consistent development experience:** The ability to automatically remove unused code would align Bootstrap with Tailwind CSS in terms of development workflow and optimization techniques.

**Implementation:**

The feature could be implemented using a tool like PurgeCSS or UnCSS. These tools analyze the HTML and CSS files to identify which CSS selectors are actually used and remove the unused ones. For JavaScript, a similar tool could be used to analyze the JavaScript code and remove unused code.

**Additional considerations:**

* **Whitelist mechanism:** To ensure that critical Bootstrap components are not removed, a whitelist mechanism could be implemented. This would allow developers to specify which CSS selectors and JavaScript code should always be included in the production build.
* **Configuration options:** The feature could provide configuration options to control the level of optimization. For example, developers might want to choose to remove only unused CSS selectors or to also remove unused JavaScript code.

We believe that this feature would be a valuable addition to Bootstrap and would help to improve the performance and development experience of Bootstrap projects.
![IMG_20231129_232844](https://github.com/twbs/bootstrap/assets/59386700/d3908df4-5feb-4f2c-a777-0f35f0a2d8db)
</div>
```[tasklist]
### Tasks
```

**Comment by nextgenthemes** [comment]
I fail to see your point.

What are "Bootstrap builds"?s it. You mean the docs?

They use pretty much all the CSS Bootstrap offers, do they not? Maybe there could be a few bytes cut because they not use every single utility class or something, but I am nor sure if it's worth it.

People can use PurgeCSS with their CSS with Bootstrap. I use it, but I have to set it up with my HTML/JS and my specific needs, Bootstrap devs can't help me. Never used Tailwind, but I have seen some vids, and it seems they have a watcher on a few HTML files running that just scans for CSS file names and generate CSS for that. They HAVE TO do that because otherwise the CSS file would be insanely huge and slow the browser down. I heard the devs explain that. Bootstrap is different, using all CSS in development is perfectly fine, even after because it's not that big.

I am too lazy to downsize the JS and import only the things I use, I just include the bundle, people can already just import the parts they need. So it's up to people to implement the CSS minification on their own, it's only needed for production. The tools already exist, as you mentioned. Something like Tailwind has is not needed. The comparison makes not much sense.
