### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Ezel4** [twbs/bootstrap#39582]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

ne souvrre pas 

### Reduced test cases

sa ne marche pas 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5

**Comment by CyrilKrylatov** [comment]
Bonjour,

le template de création d'issue permet d'apporter plus d'informations concernant le souci que vous rencontrez ; n'hésitez pas à utiliser Google Translate pour traduire ce qui vous est demandé.

Là littéralement votre issue c'est "ça ne s'ouvre pas sur Windows, Microsoft Edge, Bootstrap v5" sans plus d'information, cela va être compliqué de vous aider.

-- 

Good morning,

the issue creation template allows you to provide more information regarding the problem you are experiencing; do not hesitate to use Google Translate to translate what is asked of you.

There literally your issue is "it doesn't open on Windows, Microsoft Edge, Bootstrap v5" without more information, it will be complicated to help you.
