### ISSUE TITLE
Missing "uppercase" in Algolia search

### ISSUE THREAD

**Issue by khalyomede** [twbs/bootstrap#39685]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When we search on the Algolia search for "upper" or "uppercase", no entry is shown. However, there is a utility with this name.

### Reduced test cases

![Capture d’écran du 2024-02-18 10-25-06](https://github.com/twbs/bootstrap/assets/15908747/c7b7f932-64cd-48b9-ab0d-29187959f2fa)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.2

**Comment by rekcus2** [comment]
And nobody can fix it because they for some stupid reason decided to use this stupid closed serve service and promote them with their insane huge banner they plaster over the search.

This while there are perfectly capable open source alternatives like https://github.com/typesense/typesense. But it does not need anything this complicated at all anyway. It's just a bunch of headers and texts the needs to be searched and displayed. And apparently the all to get Algolia commercial fails hard at this basic task.

**Comment by rekcus2** [comment]
How is my comment off-topic? It's totally on topic, it's a fact that the code that causes this issue can NOT be verified and fixed anyone like the rest of the BS project including the docs. What a dishonest way to censor.

**Comment by mdo** [comment]
@rekcus2 I'm not sure who minimized your comment, but they may have done it because of your tone/delivery. It may be possible to improve this by iterating on our setup for indexing search terms. We don't index every word in every page currently as I understand it. Shitting on the maintainers and their current implementation, while simultaneously touting something else, isn't a great way to approach things.

All that said, if you have time to look at how to improve search—or replace it with a better, faster, easier, OSS solution—we're always open to listening to that! Issues, discussions, or PRs are very much welcome.
