### ISSUE TITLE
React Bootstrap doesn't let me set background color

### ISSUE THREAD

**Issue by reinaldofox** [twbs/bootstrap#39812]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In my React app the tables suddenly started to appear with a background that I didn't define.
![image](https://github.com/twbs/bootstrap/assets/1627337/35c8e4cd-02c1-438a-8a29-4aeac608e015)

I researched and discovered that Bootstrap automatically defines a Light theme, so much so that when I define <html " data-bs-theme="dark"> the tables become dark.
It turns out that I don't want either Dark or Light, I want to define my backgrounds and even overwriting the rule doesn't work.

How the table should look like:
![image](https://github.com/twbs/bootstrap/assets/1627337/e69f51e1-3921-4855-9edd-45e8287d4193)

Maybe it's something silly, but I'm racking my brain and this nonsense is making me mad.

### Reduced test cases

no test

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @reinaldofox. The default background has been changed in https://github.com/twbs/bootstrap/pull/37084 from `transparent` to `var(--bs-body-bg)` because of some issues with the nesting tables. If you think about a way to keep that `transparent` and make everything works, don't hesitate to suggest some things, it'd be really appreciated!

If you're never using nested tables, and you have a custom Sass compilation, you should be able to change `$table-bg` to `transparent` in `_variables.scss`. If not, you could probably (not tested) add a CSS rule on your side that basically does something like that:

```css
.table {
   --bs-table-bg: ; // or --bs-table-bg: transparent
}
```
