### ISSUE TITLE
SSL Not working

### ISSUE THREAD

**Issue by welovedsncom** [twbs/bootstrap#39947]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css Hello guys! Ur SSL is not working so my clients websites have destroyed styling. How long will it take to solve that?

### Reduced test cases

SSL time expired

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.2

**Comment by welovedsncom** [comment]
I see now it works but my websites are marked as unsecure

**Comment by yeinahn** [comment]
It seems to be related to this issue: https://github.com/jsdelivr/jsdelivr/issues/18565

**Comment by Curo-Dev** [comment]
Use this [https://fastly.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css](https://fastly.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css)

**Comment by babprog** [comment]
Same here, I wonder when it will be fixed

**Comment by julien-deramond** [comment]
Hello there,

> Ur SSL is not working so my clients websites have destroyed styling. How long will it take to solve that?

jsdelivr is not maintained by Bootstrap team. As mentioned by @yeinahn, it seems to be related to https://github.com/jsdelivr/jsdelivr/issues/18565. You can enable the notifications to check whenever it'll be fixed on their side. On our side, I'm going to close this issue since there's nothing to do.

In the meantime, if technically possible for you, you could switch to [alternative CDNs](https://getbootstrap.com/docs/5.3/getting-started/download/#alternative-cdns) such as [cdnjs](https://cdnjs.com/) or [unpkg](https://unpkg.com/).

As mentioned by @Curo-Dev, it may be possible to switch to fastly.jsdelivr.net or gcore.jsdelivr.net too. Some folks in the jsdelivr thread seem to say that it's working.

**Comment by shivanraptor** [comment]
Is there an official CDN version instead of jsdelivr ones?
