### ISSUE TITLE
Docs have conflicting information regarding customization

### ISSUE THREAD

**Issue by NuktukDev** [twbs/bootstrap#40560]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On the docs it shows:
> Variable overrides must come after our functions are imported, but before the rest of the imports.
https://getbootstrap.com/docs/5.2/customize/sass/#variable-defaults

But the docs then link to a starter package which doesn't follow this rule:
https://github.com/twbs/bootstrap-npm-starter
https://github.com/twbs/bootstrap-npm-starter/blob/2258953be2d3bed2edfdee796aa7da9a550b3faf/scss/starter.scss#L33

I am wondering if this is a mistake, are the docs right, or is it outdated? If we can clarify this in the docs so it doesn't confuse others like it did me, that would be great.

### Reduced test cases

None

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @NuktukDev

In https://github.com/twbs/bootstrap-npm-starter/blob/2258953be2d3bed2edfdee796aa7da9a550b3faf/scss/starter.scss#L33, the overridden Sass variables don't use the functions, so it's not really an issue (even if it should follow what's said in the doc).

In our current documentation (v5.3.3), it's already fixed as:
- https://getbootstrap.com/docs/5.3/customize/sass/#variable-defaults mentions the [Sass & JS example](https://github.com/twbs/examples/tree/main/sass-js) instead of https://github.com/twbs/bootstrap-npm-starter/ that is now archived
- https://github.com/twbs/examples/blob/main/sass-js/scss/styles.scss defines the colors correctly

v5.2 documentation won't be updated as it's an old version now, so please rather follow what's described in the v5.3: https://getbootstrap.com/docs/5.3/customize/sass/#variable-defaults + https://github.com/twbs/examples/blob/main/sass-js/scss/styles.scss
