### ISSUE TITLE
Add jQuery 4 compatibility to the bootstrap 3x branch

### ISSUE THREAD

**Issue by joejoseph00** [twbs/bootstrap#40701]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add jQuery 4 compatibility to the bootstrap 3x branch.

### Motivation and context

Drupal 11 requires jQuery 4 and we would like to be able to use Bootstrap 3x with Drupal 11.

we have tens of thousands of installs of bootstrap 3x and are continuing to use it for a variety of reasons.

Spun from: https://github.com/twbs/bootstrap/issues/16834

Should this not be acceptable by the twbs project, any guidance/recommendations on forking would be appreciated.

Thanks

Joseph Olstad

**Comment by julien-deramond** [comment]
Hello @joejoseph00,
Bootstrap v3 is EOL (End-Of Life) since 2019-07-24, and we won't make new v3 releases.

> Should this not be acceptable by the twbs project, any guidance/recommendations on forking would be appreciated.

To fork Bootstrap v3 and enhance it, you'd probably have to:
- Create a new repository starting from the latest v3 tag: `v3.4.1` (e.g. `git checkout v3.4.1`)
- Then, you'll have to make it compile. Either it'll work right away, either you'll need to bump some dependencies
- Then, you'll have to bump all dependencies to use the latest ones, and maintain them
- From there, I suppose you'll be able to start the work with jQuery 4 to update the framework
- If you do that, and share it to other people, FYI, there are CVEs that could be fixed too listed at https://security.snyk.io/package/npm/bootstrap

**Comment by olstjos** [comment]
Hi @julien-deramond I'm pretty serious about forking 3.4.x to make jQuery 4 happen quickly.  Can you also point me to a get started guide with how to compile your builds of bootstrap, especially 3.4.x?

Assuming I'll need to have npm installed.  Wondering if there's a docker build with a specific npm setup or maybe it's grunt that is needed.  Any type of extra pointer to get started for an experienced software engineer with zero experience compiling bootstrap.

**Comment by olstjos** [comment]
Julien, je suis parfaitement bilingue, donc tu peut me fournir de quoi en français si c'est plus facile pour vous.

**Comment by julien-deramond** [comment]
Unfortunately, I've never compiled Bootstrap v3.
I've looked at the v3 branch but haven't found any developer guide. However, it seems pretty straightforward, as I suppose you'll need to `npm i` and then simply run `grunt` or `node_modules/.bin/grunt`. It would generate a `dist` directory containing the compiled Bootstrap version.

**Comment by joejoseph00** [comment]
An alternative to forking would be to offer a bounty for the twbs to provide an update.  We could start a crowdsource for this.  I could justify offering 2000$ usd out of my own pocket to get the ball rolling.

**Comment by joejoseph00** [comment]
With that said, I was told to test the existing bootstrap with jQuery 4 before going to far.  It may already be compatible.

**Comment by joejoseph00** [comment]
Basically our sub library closes the gap between bootstrap 3 and bootstrap 5.  The major functionality offered by bootstrap 5 is covered by the library we use on top of bootstrap 3.  with that said, I'm offering 2000$ usd out of pocket to see if that gets any ears perked up.

**Comment by sayaghi** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
-------- الرسالة الأصلية --------من: Joseph Olstad ***@***.***> التاريخ: 15‏/8‏/2024  9:49 م  (GMT+03:00) إلى: twbs/bootstrap ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: Re: [twbs/bootstrap] Add jQuery 4 compatibility to the bootstrap 3x branch (Issue #40701) 
With that said, I was told to test the existing bootstrap with jQuery 4 before going to far.  It may already be (mostly?) compatible.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/twbs/bootstrap/issues/40701#issuecomment-2291976989",
"url": "https://github.com/twbs/bootstrap/issues/40701#issuecomment-2291976989",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sayaghi** [comment]
...  . Sent from my Verizon, Samsung Galaxy smartphone
-------- الرسالة الأصلية --------من: Joseph Olstad ***@***.***> التاريخ: 15‏/8‏/2024  9:51 م  (GMT+03:00) إلى: twbs/bootstrap ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: Re: [twbs/bootstrap] Add jQuery 4 compatibility to the bootstrap 3x branch (Issue #40701) 
Basically our sub library closes the gap between bootstrap 3 and bootstrap 5.  The major functionality offered by bootstrap 5 is covered by the library we use on top of bootstrap 3.  with that said, I'm offering 2000$ usd out of pocket to see if that gets any ears perked up.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/twbs/bootstrap/issues/40701#issuecomment-2291980645",
"url": "https://github.com/twbs/bootstrap/issues/40701#issuecomment-2291980645",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by joejoseph00** [comment]
? What is this about?

**Comment by joejoseph00** [comment]
@julien-deramond  I have forked twbs/bootstrap and set the default branch to v3-dev in my fork, however my fork is lacking all of the travis setup.  Wondering if you could please assist with the travis setup, I've added you as a full maintainer of my fork for this purpose.

> To fork the Travis setup of a repository, you can migrate the repository to your Travis CI account. Here are the steps to migrate a repository to your Travis CI account:
> 
>     Grant access via GitHub Apps to the repositories you’d like to build and transfer. (@julien-deramond  this part requires permissions to twbs/bootstrap that I do not have)
>     Visit the “Migrate” tab on Travis CI by going to the following URL: [Migrate Tab](https://travis-ci.com/account/migrate).
>     Select the repositories you’d like to migrate and click “Migrate selected repositories”.
>     Confirm the migration. The icons next to your repository name will show the migration status.
> 
> By following these steps, you can migrate the abandoned project’s repository to your Travis CI account and take over the Travis setup.
> 
> For more detailed information on migrating repositories, you can refer to the official Travis CI documentation on open-source repository migration: [Open Source Repository Migration](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

Appreciate your assistance on this one.

**Comment by joejoseph00** [comment]
Ok,I've upgraded bootstrap 3 to accept jQuery 4, it's in a testing/ review phase now

https://github.com/entreprise7pro/bootstrap/archive/refs/tags/v3-dev-1.zip

**Comment by joejoseph00** [comment]
Cancelling the 2000$ usd offer, I did the job myself. https://bootstrap.7pro.ca

**Comment by joejoseph00** [comment]
Update to this issue:

bootstrap-sass has also been forked

* A gem has been published for [entreprise7pro-bootstrap-sass](https://rubygems.org/gems/entreprise7pro-bootstrap-sass) 
* npm publishing will continue tomorrow.
* Bower is ready now - `bower install entreprise7pro/bootstrap --save` AND `bower install entreprise7pro/bootstrap-sass --save`  

### See these two repos:

https://github.com/entreprise7pro/bootstrap

https://github.com/entreprise7pro/bootstrap-sass

We also fixed [CVE-2024-6485](https://nvd.nist.gov/vuln/detail/CVE-2024-6485)
