### ISSUE TITLE
Heads-up: Projects (classic) will be sunset on August 23, 2024. Only cards that have been updated in the last year will be migrated.

### ISSUE THREAD

**Issue by nextgenthemes** [twbs/bootstrap#40713]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Just a heads-up as I just noticed this warning on the [v6 project](https://github.com/twbs/bootstrap/projects/37) and specifically this "Only cards that have been updated in the last year will be migrated."

So you probably want to manually migrate this to not lose anything, as I believe there are cards that are not updated from 2022. 

### Reduced test cases

https://codepen.io/team/bootstrap/pen/qBamdLj - will this make the bot shut up?

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v6

**Comment by julien-deramond** [comment]
Thanks for the heads-up @nextgenthemes 
Appreciate it, :) the v6 project has been migrated and is available at https://github.com/orgs/twbs/projects/38

**Comment by sayaghi** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
-------- الرسالة الأصلية --------من: nextgenthemes ***@***.***> التاريخ: 10‏/8‏/2024  6:45 م  (GMT+03:00) إلى: twbs/bootstrap ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: [twbs/bootstrap] Heads-up: Projects (classic) will be sunset on August 23, 2024. Only cards that have been updated in the last year will be migrated. (Issue #40713) 
Prerequisites

 I have searched for duplicate or closed issues
 I have validated any HTML to avoid common problems
 I have read the contributing guidelines

Describe the issue
Just a heads-up as I just noticed this warning on the v6 project and specifically this "Only cards that have been updated in the last year will be migrated."
So you probably want to manually migrate this to not lose anything, as I believe there are cards that are not updated from 2022.
Reduced test cases
https://codepen.io/team/bootstrap/pen/qBamdLj - will this make the bot shut up?
What operating system(s) are you seeing the problem on?
Linux
What browser(s) are you seeing the problem on?
Firefox
What version of Bootstrap are you using?
v6

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/twbs/bootstrap/issues/40713",
"url": "https://github.com/twbs/bootstrap/issues/40713",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
