### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by gazhay** [twbs/bootstrap#40772]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

site/content/docs/5.3/utilities/spacing.md

The examples relating to grid gap spacing are incorrect.
They specify a class of "grid" - however that will not work - it is class "d-grid"

### Reduced test cases

na

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.3.2

**Comment by louismaximepiton** [comment]
Hey, thanks for your contribution.

The `.grid` is intended here to have a grid template. The class is defined in [`_grid.scss`](https://github.com/twbs/bootstrap/blob/e3e00b5002139adb0d5dadd6002e15b7b6cd371f/scss/_grid.scss#L22). TBH, I think the implementation is correct since the `.grid` class exists if the `$enable-cssgrid` is set to `true`. The process is well explained in [CSS grid](https://getbootstrap.com/docs/5.3/layout/css-grid/) part of the documentation. However, the concept explained here still work using flex display.
Closing the issue for now.
