### ISSUE TITLE
[Docs] Column order classes missing Sass variable name

### ISSUE THREAD

**Issue by TobiGr** [twbs/bootstrap#40816]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The docs say at https://getbootstrap.com/docs/5.3/layout/columns/#order-classes:

>### Order classes
>
> Use `.order-` classes for controlling the visual order of your content. These classes are responsive, so you can set the `order` by breakpoint (e.g., `.order-1.order-md-2`). Includes support for `1` through `5` across all six grid tiers. If you need more .`order-*` classes, you can modify the default number via Sass variable.

It is not clear which Sass variable needs to be modified. Adding the var name would be helpful.

### Reduced test cases

Not applicable to docs, I guess?

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.3

**Comment by julien-deramond** [comment]
Thanks for opening this issue @TobiGr 

I think that the sentence is even misleading, as there's not really a Sass variable to modify. I mean, there is, but it's the content of `$utilities` that must be updated, because the responsive order utility is built like this:

https://github.com/twbs/bootstrap/blob/dcec1df61f107e2b449486aafefbb1d14abe0333/scss/_utilities.scss#L335-L348

**Comment by julien-deramond** [comment]
Tried something in https://github.com/twbs/bootstrap/pull/40821. See you there for comments and feedback :)
